vercel/turborepo

docs/pages/docs/features/pipelines.mdx
https://turborepo.org/docs/features/pipelines#defining-a-pipeline
=> Fix 404 links

cli/npm/turbo-install/README.md
=> Fix faulty CODE_OF_CONDUCT.md link

docs/components/Footer.tsx
=> Fix Github link

docs/pages/docs/features/pipelines.mdx, docs/pages/docs/upgrading-to-v1.mdx
Added the section in red to the documentation on pipelines because it took me far too long to figure out how to run a pipeline 🤦
=> Add a codeblock showing how to run a pipeline

create-turbo/templates/_shared_ts/package.json, create-turbo/templates/pnpm/package.json
=> Stop running yarn in base template

cli/internal/fs/package_json.go
=> Fix packageJson struct

.github/ISSUE_TEMPLATE/-bug_report.yml
Fix the typo in the product name Turbrepo -> Turborepo
=> ci: Fix typo in issue template

cli/internal/context/context.go
=> Fix internal deps

cli/cmd/turbo/main.go, cli/internal/run/run.go
=> Fix error when passing --api, --url, --heap, --cpuprofile, --trace, --no-gc flags

docs/nextra-theme-docs/search.js, docs/nextra-theme-docs/utils/use-mounted.js
=> docs: Set timeout before closing search

examples/kitchen-sink/apps/api/package.json
=> Add nodemon to api in kitchen sink

cli/internal/client/client.go
=> Set user agent on GET

docs/pages/docs/acknowledgments.mdx
Fix type of the product name :)
=> docs: fix turborepo name

docs/pages/docs/reference/configuration.mdx
Very small PR to not forget pnpm for `npmClient` config option
=> docs: Update npmClient with pnpm option in documentation

cli/scripts/generate.mjs, create-turbo/templates/_shared_ts/packages/tsconfig/base.json, create-turbo/templates/_shared_ts/packages/tsconfig/nextjs.json, examples/basic/packages/tsconfig/base.json, examples/basic/packages/tsconfig/nextjs.json, examples/design-system/packages/acme-tsconfig/base.json, examples/design-system/packages/acme-tsconfig/nextjs.json, examples/kitchen-sink/packages/tsconfig/base.json, examples/kitchen-sink/packages/tsconfig/nextjs.json, examples/kitchen-sink/packages/tsconfig/vite.json, examples/with-pnpm/packages/tsconfig/base.json, examples/with-pnpm/packages/tsconfig/nextjs.json
=> Use "node" module resolution by default for all tsconfigs

create-turbo/__tests__/cli.test.ts, create-turbo/src/index.ts, create-turbo/src/shouldUsePnpm.ts, create-turbo/templates/pnpm/README.md, create-turbo/templates/pnpm/apps/docs/package.json, create-turbo/templates/pnpm/apps/web/package.json, create-turbo/templates/pnpm/packages/ui/package.json
=> Enable pnpm starter

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
- Add [hyperfine](https://github.com/sharkdp/hyperfine) benchmarking tool to devcontainer
- Add other quality of life VSCode extensions
=> chore: Update devcontainer 

docs/pages/docs/glossary.mdx
=> docs: Fix dag diagram

create-turbo/src/index.ts, create-turbo/src/shouldUsePnpm.ts
[pnpx command is deprecated in version 6.x](https://pnpm.io/pnpx-cli)
=> fix: pnpx command is deprecated in version 6.x

cli/internal/fs/copy_file.go
=> fix: treat symlink directory as directory

docs/pages/docs/reference/configuration.mdx
fix these invalid JSON syntax for using in package.json
=> docs(configuration): fix commas in JSON

scripts/run-examples.sh
=> fix: run examples

.vscode/launch.json, CONTRIBUTING.md
* Added a bare-bones `CONTRIBUTING.md` (will update as I come across more).
* Added a `launch.json` to get a basic debugging setup in VS Code
=> Start on some contributing notes and tools

turbo-codemod/src/git.ts, turbo-codemod/src/index.ts
Remove references to `turbo-migrate`
=> Fix @turbo/codemod help text

scripts/run-examples.sh
Add back npm to `run-exampes.sh` to ensure PRs check against npm
=> Add back npm to `run-exampes.sh`

.github/workflows/large-monorepo.yml
=> schedule key needs to point to an array of crons

docs/package.json, yarn.lock
Should fix this issue: https://github.com/vercel/turborepo/pull/734#issuecomment-1045041407 (problem with Webpack's loader dependencies).
=> Upgrade Nextra

cli/internal/analytics/analytics.go, cli/internal/cache/async_cache.go, cli/internal/cache/cache.go, cli/internal/cache/cache_fs.go, cli/internal/cache/cache_http.go, cli/internal/client/client.go, cli/internal/run/run.go
Track duration locally in .turbo/:hash-meta.json for accuracy
=> Store local artifact durations 

examples/basic/packages/config/eslint-preset.js, examples/design-system/packages/eslint-preset-acme/index.js, examples/with-pnpm/packages/config/eslint-preset.js, packages/create-turbo/templates/_shared_ts/packages/config/eslint-preset.js
Fixes upsteam https://github.com/yannickcr/eslint-plugin-react/issues/3215
=> fix: upstream eslint-plugin-react issue causing next build and lint to fail

.github/workflows/cancel.yml
Cancel's previous GitHub Actions Workflows if there are newer commits. 
See https://github.com/styfle/cancel-workflow-action
=> chore: Add cancel workflow GH Action

docs/pages/docs/faq.mdx
Replace "and" with "any" in "Does Turborepo collect any personally identifiable information?".
I don't believe that the sentence makes sense with "and", so I'm assuming it's a typo and is meant to be "any"
=> Update FAQ wording

docs/pages/docs/faq.mdx
https://twitter.com/dotey/status/1500948145722822658
=> docs: Add note about Fast Refresh to the FAQ docs

packages/create-turbo/__tests__/cli.test.ts
AFAICT this test is just slow. Bumping the timeout.
=> Bump timeout on create-turbo CLI test

cli/internal/run/run.go
Add more details to dry run output
=> Add more info to --dry-run

docs/pages/docs/features/pipelines.mdx
- Include outputs to make more copy and paste friendly
=> Improve pipelines documentation

docs/pages/docs/reference/configuration.mdx
=> Remove outdated npmClient reference in docs

cli/internal/run/run.go
Remove references to turborepo.com team and token
=> Update run command's --help 

cli/Makefile
=> Use CGO on macOS M1 darwin-arm64

docs/pages/_app.js
Fixes https://github.com/vercel/turborepo/issues/991
=> fix(docs): update css order to fix docs hero

cli/internal/scope/scope.go
=> only prepend since w/ ... if since is not empty

cli/internal/run/run.go
=> Don't run log replay asynchronously

cli/internal/context/context.go
Closes #720
Most of time is walking about node_modules who we should ignore.
=> Apply global ignore patterns for global deps

examples/design-system/README.md, examples/kitchen-sink/README.md, examples/with-changesets/README.md
fix documentation casing from Typescript to TypeScript
=> docs: fix Typescript to TypeScript

cli/scripts/generate.mjs
This should fix CI by setting things to a compatible set of versions.
=> Set version range.

cli/internal/cache/cache_http.go, cli/internal/cache/cache_signature_authentication.go, examples/kitchen-sink/apps/blog/app/routes/demos/params/$id.tsx
=> Fix typo in comment

docs/pages/docs/guides/continuous-integration.mdx
Recreating the PR after the #1124 Kodiak automerge disaster.
=> docs: Add recipe for CircleCI

docs/next.config.js, docs/pages/docs/ci.mdx, docs/pages/docs/ci/circleci.mdx, docs/pages/docs/ci/github-actions.mdx, docs/pages/docs/ci/meta.json, docs/pages/docs/guides/meta.json, docs/pages/docs/meta.json
=> docs: Refactor to have CI section

cli/internal/client/client.go, cli/internal/login/link.go, cli/internal/login/login.go, cli/internal/login/login_test.go, cli/internal/login/status.go
Add a check to `/artifacts/status` to `turbo login --sso-team`, since it implicitly links the repo to a team.
=> Implement status check for SSO login

.github/.kodiak.toml
`blocking_labels` needs to be an array. TOML IS FUN LOL
=> Fix kodiak config

examples/with-changesets/.eslintrc.js
Followup to #1172 (tweak all the ESLint things!) and #1174 (much better name) we have one spot that needs re-linking.
=> ESLint: one more spot change

cli/internal/fs/package_deps_hash.go
=> Add better diagnostic errors when we fail to hash files with git

docs/pages/docs/ci/github-actions.mdx
Hello,
I updated the GitHub Actions example to maximize caching capabilities.
=> docs: better gh-actions example

docs/pages/docs/ci/github-actions.mdx
=> Revert "docs: better gh-actions example"

cli/internal/run/run.go
=> Skip cache fetch for tasks that are marked cache: false

cli/internal/fs/package_deps_hash.go
We do not presently use any of the behavior implied by these APIs and should remove it.
=> fix: Remove unused arguments and code paths.

cli/internal/run/run.go
We were not explicitly calling `Close` or `Flush` on our logstreamers, and the call to close the underlying log file was coming too late, due to `defer`
=> Ensure logs are flushed before we attempt to cache them

docs/components/Footer.tsx
someone was probably `.`-trigger-happy in vim
=> Fix a class in FooterLink

packages/create-turbo/src/index.ts
fixes https://github.com/vercel/turborepo/issues/1329
fixes https://github.com/vercel/turborepo/issues/1288
=> fix(create-turbo): yarn berry & lint fix

cli/cmd/turbo/main.go, cli/go.mod, cli/go.sum, cli/internal/cmd/auth/logout.go, cli/internal/cmd/auth/unlink.go, cli/internal/config/config.go, cli/internal/config/config_file.go, cli/internal/config/config_file_test.go, cli/internal/fs/path.go, cli/internal/globby/globby.go, cli/internal/globby/globby_test.go, cli/internal/login/link.go, cli/internal/login/login.go, cli/internal/login/login_test.go, cli/internal/packagemanager/packagemanager_test.go
The `afero` experiment was interesting but we have discovered that the package has significant deficiencies and many ecosystem projects (e.g. https://github.com/adrg/xdg) do not currently support virtual file systems. As this is not a primary portion of what we're focusing on we don't at this time see ROI from responsibility for trying to push our corner of the ecosystem in this direction.
If we want to adopt something similar in the future we would consider https://github.com/avfs/avfs.
=> Remove afero.

.github/CODEOWNERS
=> Add @tknickman to CODEOWNERS

.github/.kodiak.toml
On #1354 Kodiak trolled us. This expands the blocking labels to ensure that the labels that look like they should be blocking are indeed blocking.
=> Expand the blocking labels for Kodiak.

.github/workflows/ci-go.yml, .gitignore, cli/Makefile, cli/npm/turbo-install/node-platform.js, cli/npm/turbo-install/package.json, cli/package.json, cli/scripts/bump-version.js, package.json, pnpm-lock.yaml
A lot of little build housekeeping bundled into one PR.
=> Code Housekeeping

cli/internal/cache/cache_http.go, cli/internal/cache/cache_http_test.go, cli/internal/fs/path.go, cli/internal/util/set.go
Also start adding some tests for untarring.
=> Add root boundary to untarring

cli/scripts/e2e/e2e.ts, cli/scripts/monorepo.ts
Also add an assertion that we start with a clean `git status`
=> Bump e2e pnpm to 7

cli/internal/cache/cache_fs.go, cli/internal/cache/cache_fs_test.go, cli/internal/fs/copy_file.go, cli/internal/fs/path.go
Follow up to https://github.com/vercel/turborepo/pull/1429
=> fix(cli): prefer IsDir() over explicit type check

CONTRIBUTING.md
Update `CONTRIBUTING.md` with new required dependencies
Dependencies:
- `jq` required by `scripts/`
- protobuf required by cli: `make protoc`
Other:
- Swap to auto-incrementing ordered lists
[Rendered markdown](https://github.com/vercel/turborepo/blob/f2223a7c1c33cbcf4a8f29d826ede3e5f374ea38/CONTRIBUTING.md)
=> docs(cli): update contributing.md with new deps

cli/Makefile, pnpm-lock.yaml
The root project needs to update the lockfile after publish.
=> Update lockfile after version bump

.github/CODEOWNERS
=> chore(owners): add chris & mehul

cli/internal/env/env.go, cli/internal/env/env_test.go
Support blocklist for automatically include env vars
=> feat(cli): add TURBO_CI_VENDOR_ENV_KEY

examples/with-create-react-app/packages/ui/package.json
Fixes https://github.com/vercel/turborepo/issues/1627
=> fix(examples): fix cra ui package

packages/eslint-config-turbo/package.json, packages/eslint-plugin-turbo/package.json
LICENSE files were correct, but the identifier in package.json needed updating.
=> Correct the license identifiers.

cli/Makefile
When run via `make` and directly on the command line this was getting different results.
=> Weird makefile differences

docs/pages/blog/turbo-1-4-0.mdx
=> Fix tab/spaces for 1.4 post.

packages/create-turbo/README.md
=> Make it easier to copy paste command from README

.github/workflows/ci-js.yml, packages/eslint-config-turbo/package.json, packages/eslint-plugin-turbo/package.json, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/package.json, packages/turbo-ignore/src/getComparison.ts, packages/turbo-ignore/src/index.ts, pnpm-lock.yaml
=> chore(ci): test all other packages in CI

docs/components/clients/Clients.tsx, docs/components/clients/Logo.tsx, docs/components/clients/users.ts, docs/components/pages/home.tsx, docs/components/pages/showcase.tsx
Handle logo size correctly and fix showcase layout shift
=> fix(docs): fix showcase layout shift

cli/go.mod, cli/go.sum
I'm still wrapping my head around how Go does package management, but I think this is a follow up from #1472. cc @bguedes-moz
=> Run go mod tidy

packages/create-turbo/src/index.ts
The registry argument is being read from the configuration paths and then being passed back in via `--registry` which is entirely unnecessary. The package managers already default to deferring to system-configured registries.
This was added in #885, but is unnecessary.
=> [create-turbo] Remove registry argument to install.

docs/pages/docs/core-concepts/remote-caching.mdx
https://www.youtube.com/watch?v=9Ht5RZpzPqw
=> Removed key emoji

.github/workflows/release.yml, cli/Makefile, package.json, pnpm-lock.yaml, scripts/version.js
This PR depends on #1455. After landing we would get this fun release button:
It currently, intentionally, has a commented out load of the `turbobot` `npm` token so that it's assured harmless until reviewed.
=> Script for releasing from CI.

.github/workflows/large-monorepo.yml
Fix syntax for github action so that it triggers properly
=> Remove errant indentation

examples/basic/packages/tsconfig/package.json, examples/design-system/packages/acme-tsconfig/package.json, examples/kitchen-sink/packages/tsconfig/package.json, examples/with-changesets/packages/acme-tsconfig/package.json, examples/with-create-react-app/packages/tsconfig/package.json, examples/with-docker/packages/tsconfig/package.json, examples/with-pnpm/packages/tsconfig/package.json, examples/with-prisma/packages/tsconfig/package.json, examples/with-react-native-web/packages/tsconfig/package.json, examples/with-tailwind/packages/tsconfig/package.json, examples/with-vite/packages/tsconfig/package.json, packages/create-turbo/templates/_shared_ts/packages/tsconfig/package.json, packages/tsconfig/README.md, packages/tsconfig/package.json, packages/turbo-ignore/package.json, pnpm-lock.yaml
Follow up to https://github.com/vercel/turborepo/pull/1807 based on comments received post merge (thanks @nathanhammond)
=> chore(configs): update tsconfigs & packages

examples/basic/turbo.json
This helps keep things simpler in the basic example
=> Removed dependsOn and dist/** from build in basic example

docs/pages/docs/guides/monorepo-tools.mdx
Sorry, I had missed this small change in the previous PR.
=> added code-shaper to the code generation intro line

examples/design-system/README.md
Update file path to reflect current directory structure.
=> docs(examples/design-system): update readme

examples/with-nextjs/README.md
Add a comment to ensure we don't forget that this is linked to and accidentally kill this in the future (shoutout @mehulkar)
=> chore(examples): add comment for maintainability

cli/internal/fs/turbo_json.go
- This PR is stacked on top of #1950, merge that first.
- @tknickman will merge this when the codemod is ready and we can do a release at the same time as that
=> chore(core): deprecation messages for legacy env keys

.github/workflows/pr-js-tests.yml
- windows is showing a "The batch file cannot be found." error that we are not currently looking into
- only run the tests if this PR changes something relevant to them.
=> Disable windows variant

docs/pages/docs/handbook/deploying-with-docker.mdx
Just a tiny fix for a tiny typo.
=> Fix typo in docs

cli/internal/lockfile/berry_lockfile.go, cli/internal/lockfile/berry_lockfile_test.go, cli/internal/lockfile/testdata/berry.lock, cli/internal/lockfile/testdata/minimal-berry.lock
=> Change Berry's `cacheKey` to be a string

cli/internal/run/run.go
We have an issue with threading our `AF_UNIX` socket properly through grpc on windows. Disable the daemon attempt on windows while we work out the issue, so that users aren't bothered by the warning that it isn't working.
=> Temporarily disable daemon on windows

docs/.gitignore, docs/package.json, docs/pages/blog/joining-vercel.mdx, docs/pages/blog/turbo-0-4-0.mdx, docs/scripts/generate-rss.js, pnpm-lock.yaml, turbo.json
- Cleaned up some missing og images in post frontmatter
- Added script to generate sorted RSS feed, with image enclosures. 
- Updated .gitignore and turbo.json to ensure the RSS feed is generated automatically when building the docs site
=> seo: Add script to generate RSS feed.xml to docs site

docs/pages/docs/handbook/workspaces.mdx
Fix broken links on Page "Workspace"
Ref: https://turborepo.org/docs/handbook/workspaces
=> Fix broken links on "Workspace" Doc

packages/create-turbo/package.json, packages/eslint-config-turbo/package.json, packages/eslint-plugin-turbo/package.json, packages/turbo-codemod/package.json
Add missing repo, directory, and bugs fields to packages.
=> fix(packages): add repo, directory, and bugs fields

docs/pages/docs/getting-started/create-new.mdx
Explanation is for web depending on ui, but the filename indicates that ui depends on ui; fix to reflect the correct change.
=> fix: filename for web depending on ui

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.5.6-canary.2

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.5.6-canary.3

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.5.6-canary.4

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.5.6

turbo.json
=> fix(turbo): add new docs env vars

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.5.7-canary.0

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.6.0-canary.0

cli/internal/cacheitem/filepath.go
This file keeps updating locally, even if I don't open it. Might as well commit the formatting change
=> Save file that keeps autoformatting on its own

cli/internal/fs/turbo_json.go
This struct does not represent a pipeline, it represents a single task
=> Rename struct to be more accurate

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.6.0-canary.1

cli/integration_tests/turbo_help.t, cli/internal/cmd/root.go
Update the help text to reflect the new state of the world.
=> Update help text

cli/internal/cmd/root.go, shim/src/main.rs
Make the shim handle `--help` and `--version` prior to advancing.
=> fix(shim): Fixed version flag

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.6.0-canary.4

docs/pages/docs/handbook/dev.mdx
=> Include the argument separator for dotenv.

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.6.0

crates/node-file-trace/src/lib.rs
=> Do not forget

cli/integration_tests/turbo_help.t, shim/Cargo.lock, shim/Cargo.toml, shim/src/commands/bin.rs, shim/src/main.rs, shim/tests/mod.rs
Adding tests for both CLI parsing and e2e.
=> tests(turbo): Rust CLI Tests

docs/pages/repo/docs/core-concepts/caching.mdx
This PR improves the improve description of `--force` and `--no-cache` in the Caching documentation.
https://turbo.build/repo/docs/core-concepts/caching
=> chore(docs): improve description of `--force` and `--no-cache`

Cargo.lock, crates/turbo-tasks-fs/Cargo.toml, crates/turbo-tasks-fs/src/lib.rs, crates/turbopack/tests/node-file-trace/integration/ts-package/tsconfig.json
=> Revert "Support comments in tsconfig.json"

Cargo.lock, crates/turbo-tasks-fs/Cargo.toml, crates/turbo-tasks-fs/src/lib.rs, crates/turbopack/tests/node-file-trace/integration/ts-package/tsconfig.json
Reverts vercel/turbo#2432, rolls forward vercel/turbo#2429.
=> Revert "Revert "Support comments in tsconfig.json""

.github/CODEOWNERS
Both teams own by default, but specific files/dirs are
owned by specific teams.
=> Update CODEOWNERS config

crates/turbo-tasks/src/id.rs
Currently in `with_task_id_mapping`, the ID mapping object with any lifetime is promoted to `'static` through unsafe function `std::men::transmute`. It actually assumes the object could not outlive the function, however it is possible when a panic throws in the callback, possibly causing a use-after-free from safe code.
The following code snippet exhibits the undefined behaviour:
```rust
#[cfg(test)]
mod tests {
use crate::id::{with_task_id_mapping, IdMapping, TaskId};
struct IdentIdMapping<'a>(&'a usize);
impl<'a> IdMapping<TaskId> for IdentIdMapping<'a> {
fn forward(&self, _id: TaskId) -> usize {
self.0 + 1
}
fn backward(&self, id: usize) -> TaskId {
id.into()
}
}
#[test]
fn with_task_id_mapping_panic() {
let _ = std::panic::catch_unwind(|| {
let tid = 5;
let m = IdentIdMapping(&tid); …
```
=> Fix unsound `with_task_id_mapping` implementation

crates/next-dev/src/lib.rs
This PR makes devserver's behavior to match existing next.js devServer.
`allow_retry` is introduced to configure attempt to retry, then if bind fails due to addrinuse devserver now will retry with incrementing port number.
=> feat(next/dev): allow to retry bind

docs/styles.css
We can apply this quick fix first and remove it when fixing it in the upstream.
=> Fix line-height of blog post articles

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
=> Merge release branch staging-1.6.3-canary.0

cli/cmd/turbo/version.go, packages/create-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo/package.json, version.txt
👑 Merge release branch back to main
=> Merge release branch staging-1.6.3

.github/workflows/check-codestyle-filtered.yml
Followup for https://github.com/vercel/turbo/pull/2498, try to display diff actually.
=> ci(action): try to display clippy diff

cli/internal/core/engine.go, cli/internal/core/engine_test.go, cli/internal/run/run.go
Some refactor work extracted from #2258 so it's easier to review that diff. 
There should be no behavioral changes, and I would recommend reviewing one commit at a time. I could break this up into separate PRs, but the overhead of making CI pass and getting reviews is too high for that.
Stacked PRs:
1. #2546 (this one)
2. #2258 
3. #2548
=> Refactor TaskGraph construction

.github/labeler.yml, .github/workflows/labeler.yml
Add automatic labeler to help keep organized 😄 
Using: https://github.com/marketplace/actions/labeler
=> chore(repo): add auto labeler

.github/labeler.yml
Don't escape them, just quote them
=> fix(repo): fix the yaml keys

packages/create-turbo/src/index.ts
Closes #2249 
I tested this out with `pnpm build and running `./dist/index.js --help` and `./dist/index.js --version` and got the expected output.
=> create-turbo: Remove unnecessary code to show help version text

Cargo.lock, Cargo.toml, crates/turbopack-css/Cargo.toml, crates/turbopack-css/src/references/import.rs, crates/turbopack-css/src/references/mod.rs
Bumps up swc_core to align with next-swc's swc_core version.
=> feat(turbopack): bump up swc_core

.github/workflows/test.yml
fix typos in CI workflow
make CI change detection more specific
=> workflow fixes

packages/turbo-ignore/README.md, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/src/ignore.ts
Fixes one README error and updates the logs for better readability.
=> feat(turbo-ignore): docs update & improved output

packages/turbo-ignore/package.json, packages/turbo-ignore/tsup.config.ts
=> feat(turbo-ignore): release 0.4.0

.github/renovate.json
=> Ignore integration tests and examples for renovate dep updates

.github/workflows/test.yml
Trying to update -raw clippy output.
=> ci(actions): update clippy cache

cli/internal/context/context.go, cli/internal/core/engine.go, cli/internal/core/engine_persistent_deps_test.go, cli/internal/graph/graph.go, cli/internal/prune/prune.go, cli/internal/run/dry_run.go, cli/internal/run/run.go, cli/internal/run/run_test.go, cli/internal/scope/filter/filter.go, cli/internal/scope/filter/filter_test.go, cli/internal/scope/scope.go, cli/internal/scope/scope_test.go, cli/internal/taskhash/taskhash.go
Workspace Info and WorkspaceGraphs. I'm working on trying to figure out where each workspace will resolve its turbo.json and these renames/refactors are useful to be able to read code more easily. 
Also partially related to #1229
=> Replace "Package" with "Workspace"

docs/next.config.js
Fixes 404s (exported from google search console)
=> docs: Fix 404s

crates/turbo-tasks-memory/src/task.rs
This saves 8 bytes per task (504 bytes -> 496).
=> Use parking_lot::Mutex in Task to save some bytes

cli/internal/inference/inference.go, cli/internal/inference/inference_test.go
Fix framework inference in non-monorepos
=> fix(cli): framework inference in nonmonorepos

docs/components/Navigation.tsx, docs/pages/_meta.json
Link to new enterprise page (https://vercel.com/solutions/turborepo) for Turborepo
=> feat(docs): update ent link for turborepo

Cargo.lock, crates/next-dev/Cargo.toml, crates/next-dev/src/main.rs
Trying to disable git feature to not to bring zlib-sys.
=> fix(next-dev): disable git version info

examples/design-system/.npmrc, examples/design-system/pnpm-lock.yaml
As it turns out storybook doesn't play well with pnpm yet. Change the hoisting strategy to get this to work:
https://github.com/storybookjs/builder-vite/issues/55
=> fix(examples): design system linking

packages/turbo-ignore/__tests__/errors.test.ts, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/__tests__/test-utils.ts, packages/turbo-ignore/package.json, packages/turbo-ignore/src/errors.ts, packages/turbo-ignore/src/ignore.ts, packages/turbo-ignore/src/logger.ts, packages/turbo-ignore/src/types.ts
Prettier errors for some common turbo-ignore exceptions
=> feat(turbo-ignore): pretty errors

.editorconfig, crates/next-core/src/app_source.rs, crates/next-core/src/fallback.rs, crates/next-core/src/next_client/context.rs, crates/next-core/src/next_import_map.rs, crates/next-core/src/server_rendered_source.rs
Basically just adds the react refresh runtime to the fallback chunk, so the global variable required by all components exists
=> fix fallback error overlay

crates/next-core/js/src/dev/hmr-client.ts, crates/next-core/js/src/dev/hot-reloader.tsx, crates/next-core/js/src/entry/app/hydrate.tsx, crates/next-core/js/src/entry/server-renderer.tsx, crates/next-core/js/src/overlay/client.ts, crates/next-core/js/src/overlay/internal/ErrorBoundary.tsx, crates/next-core/js/src/overlay/internal/ReactDevOverlay.tsx, crates/next-core/js/src/overlay/internal/bus.ts, crates/next-core/js/src/overlay/internal/components/Overlay/maintain--tab-focus.ts, crates/next-core/js/types/compiled-next.d.ts, crates/next-core/js/types/globals.d.ts, crates/next-core/js/types/next.d.ts
As the title says, gets the latest changes to the error overlay from next.js
Also fixes the typescript errors we had in the overlay
=> get upstream error overlay changes and fix typescript errors

cli/Makefile, cli/integration_tests/monorepo_one_script_error/run.t
Fix integration tests (failing in main) and Makefile typo
=> fix(turbo): update regex in integration tests

packages/turbo-ignore/README.md, packages/turbo-ignore/__tests__/args.test.ts, packages/turbo-ignore/__tests__/checkCommit.test.ts, packages/turbo-ignore/__tests__/getComparison.test.ts, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/__tests__/test-utils.ts, packages/turbo-ignore/package.json, packages/turbo-ignore/src/args.ts, packages/turbo-ignore/src/checkCommit.ts, packages/turbo-ignore/src/errors.ts, packages/turbo-ignore/src/getComparison.ts, packages/turbo-ignore/src/ignore.ts, packages/turbo-ignore/src/types.ts
Allow some commit messages to skip, or deploy automatically.
=> feat(turbo-ignore): check commit body

crates/turbopack-core/Cargo.toml
#2866 was behind main when merged 😬
=> taplo format

packages/eslint-config-turbo/package.json, packages/eslint-plugin-turbo/package.json, pnpm-lock.yaml
Fixes https://github.com/vercel/turbo/issues/2889 (already released and validated)
=> fix(eslint): include all versions above 6.6

Cargo.lock, crates/turbo-tasks-fs/src/invalidator_map.rs, crates/turbo-tasks-fs/src/lib.rs, crates/turbo-tasks/Cargo.toml, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/state.rs, crates/turbopack-dev-server/src/source/asset_graph.rs, crates/turbopack-dev-server/src/source/conditional.rs, crates/turbopack-dev-server/src/update/stream.rs
add mark_stateful() method to make tasks with state
=> add turbo_tasks State

crates/next-core/js/src/dev/hmr-client.ts, crates/next-core/js/src/entry/next-hydrate.tsx, crates/next-core/js/src/entry/page-loader.ts, crates/next-core/js/types/globals.d.ts, crates/next-core/src/lib.rs, crates/next-core/src/page_loader.rs, crates/next-core/src/server_rendered_source.rs, crates/next-core/src/util.rs, crates/turbopack-dev-server/src/html.rs
=> add page chunk loader

crates/next-core/js/src/entry/server-renderer.tsx, crates/next-core/js/types/turbopack.d.ts, crates/next-core/src/app_source.rs, crates/next-core/src/server_rendered_source.rs, crates/next-core/src/util.rs, crates/turbopack-node/src/node_rendered_source.rs
=> add json route for page data requests

.github/workflows/update-google-fonts.yml, crates/next-core/src/next_font_google/__generated__/font-data.json
Previously, node-fetch wasn't available to the script when it ran.
Test Plan:
=> Run setup-node in update-google-fonts workflow

crates/turborepo-lib/src/lib.rs, shim/.gitignore, shim/build.rs, shim/src/main.rs
See: https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script
=> generate shim bindings into `OUT_DIR`

crates/turbo-updater/src/lib.rs
Support disabling update notifier via NO_UPDATE_NOTIFIER env var
=> feat(turbo): support disabling update notifier

.github/workflows/build_rust.yml, crates/turborepo/build.rs
Hat tip to @chris-olszewski who unknowingly pointed me in the right direction.
=> Update release process to support current app layout.

.github/CODEOWNERS
Set overrides in CODEOWNERS for the crates that turborepo owns
=> chore(repo): update codeowners

crates/next-core/src/server_rendered_source.rs, crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/src/task/meta_state.rs, crates/turbo-tasks-memory/src/task/stats.rs, crates/turbo-tasks-memory/src/viz/mod.rs, crates/turbo-tasks-memory/src/viz/table.rs
Easy clippy improvements via `clippy --fix`.
=> style(turbopack): clippy --fix

.github/workflows/build_rust.yml
Follow up to https://github.com/vercel/turbo/pull/3039
=> fix(release): build x86 ubuntu in xenial for GLIBC

.github/workflows/test.yml
Needs to be merged to apply properly though
=> fix clippy ci diff

.github/workflows/test.yml
This will make the quick rust compilation step faster and allows to start the test suite faster.
=> run next-binding feature check in linting phase

.vscode/launch.json, .vscode/tasks.json, crates/turborepo-lib/src/shim.rs
Add a vscode action that uses the turbo crate as an entrypoint to debug the rust shim
=> chore(dev): turborepo shim entrypoint

.vscode/launch.json, .vscode/tasks.json
Remove extra commas in vscode tasks and launch
=> fix(vscode): prettier

cli/cross-release.yml, cli/darwin-release.yml, cli/scripts/npm-native-packages/npm-native-packages.js
Ensure the Go pieces are called `go-turbo`
=> Use the correct binary name for Go binaries, also copy them

crates/turborepo-lib/src/package_manager.rs
We can support both by creating an [untagged enum](https://serde.rs/enum-representations.html#untagged) in serde. Quick spot checked the issue we saw on `vercel/vercel` and it no longer happens with this shim.
=> fix: support both formats of workspace definition for npm and yarn

docs/pages/repo/docs/ci/circleci.mdx, docs/pages/repo/docs/ci/github-actions.mdx, docs/pages/repo/docs/ci/gitlabci.mdx, docs/pages/repo/docs/ci/travisci.mdx, docs/pages/repo/docs/core-concepts/caching.mdx, docs/pages/repo/docs/core-concepts/monorepos/running-tasks.mdx, docs/pages/repo/docs/getting-started/add-to-project.mdx, docs/pages/repo/docs/getting-started/create-new.mdx, docs/pages/repo/docs/getting-started/existing-monorepo.mdx, docs/pages/repo/docs/handbook/linting.mdx, docs/pages/repo/docs/handbook/testing.mdx, docs/pages/repo/docs/reference/codemods.mdx, docs/pages/repo/docs/reference/configuration.mdx, packages/eslint-plugin-turbo/docs/rules/no-undeclared-env-vars.md, packages/turbo-types/src/types/config.ts
Stacked PRs:
- #2712 
- #2714
- Release `turbo@1.7`
- **(This one)** #2713
- #2738
=> Update docs on default outputs

docs/pages/repo/docs/core-concepts/monorepos/filtering.mdx, docs/pages/repo/docs/core-concepts/remote-caching.mdx, docs/pages/repo/docs/faq.mdx, docs/pages/repo/docs/getting-started/add-to-project.mdx, docs/pages/repo/docs/getting-started/create-new.mdx, docs/pages/repo/docs/getting-started/existing-monorepo.mdx, docs/pages/repo/docs/handbook/building-your-app.mdx, docs/pages/repo/docs/handbook/sharing-code/internal-packages.mdx, docs/pages/repo/docs/handbook/testing.mdx
Do not merge until `1.8` is deployed to npm.
=> Moved docs to global turbo installation

.github/workflows/test.yml
Currently it fails with permission error
=> add necessary permissions to commit step again

docs/components/output-mode-table.mdx, docs/pages/repo/docs/reference/command-line-reference.mdx
Add docs for new output-logs options. Follow up to https://github.com/vercel/turbo/pull/2588
=> feat(docs): update output-logs options

docs/components/ExtraContent.tsx, docs/components/RemoteCacheCounter.tsx, docs/lib/useTurborepoMinutesSaved.ts, docs/package.json, docs/theme.config.js, pnpm-lock.yaml
Adds a remote cache time saved ticket to Turborepo docs
=> feat(docs): add remote cache counter

docs/components/RemoteCacheCounter.tsx
=> One pixel transparent border to reveal background.

.github/workflows/test.yml
=> only try to push benchmark data

docs/pages/blog/turbo-1-7-0.mdx, docs/pages/repo/docs/getting-started/add-to-project.mdx, docs/pages/repo/docs/getting-started/existing-monorepo.mdx
Fixes https://github.com/vercel/turbo/issues/3286
=> fix(docs): update yarn install command

docs/pages/blog/turbo-1-7-0.mdx
=> fix(docs): corect blog typo

examples/with-docker/.dockerignore
Fixes https://github.com/vercel/turbo/issues/3257
=> fix(examples): ignore node_modules in docker

docs/pages/pack/docs/advanced/profiling.mdx
This is so minor, but seeing CI check failure earliest with this prettier check can be confusing so attempt to fix it.
=> style(docs): fix prettier

.vscode/extensions.json, .vscode/settings.json
Adds syntax highlighting in .t integration files and allow
configuration with [cram] language support
=> Recommend cram extension in dev environment

crates/turbopack/tests/node-file-trace/integration/mdx/example.mdx
=> fix(prettier): format

cli/internal/graph/graph.go
The way we resolve a taskDefinition will change
once we start allowing workspaces to create their own config so it makes sense to factor this method out first.
=> Factor out method to get resolved TaskDefinition

.github/workflows/test.yml
=> Revert "ci(actions): ensure cargo check with frozen lockfile"

docs/content/team.ts
=> Anthony changed his Twitter handle!

packages/turbo-codemod/README.md, packages/turbo-codemod/src/cli.ts
Ensures codemod backwards compatibility
=> feat(codemod): use transform as default command

cli/Makefile
Forgot to uncomment the build for turbo-ignore 🤦🏼‍♂️
=> fix(release): build turbo-ignore

examples/with-prisma/apps/web/pages/api/users.ts, examples/with-prisma/packages/database/src/client.ts
For context:
https://twitter.com/javier_dev/status/1592532624635199489
=> Fixed prisma example to allow importing interfaces from database

crates/turborepo-lib/src/shim.rs
=> fix(shim): use custom version parser

examples/with-changesets/.github/workflows/release.yml
pnpm needs to be set up before it can be installed inside Actions
=> `changesets` action: add pnpm install

packages/turbo-codemod/src/commands/migrate/steps/getLatestVersion.ts
Fixes incorrect version validation for the `--to` option
=> fix(codemod): correct to flag validation

crates/next-core/js/src/internal/page-server-handler.tsx, crates/next-core/src/manifest.rs, crates/next-dev/src/turbo_tasks_viz.rs, crates/turbo-tasks-fs/src/lib.rs, crates/turbo-tasks/src/task_input.rs, crates/turbopack-dev-server/src/introspect/mod.rs, crates/turbopack-dev-server/src/lib.rs, crates/turbopack-dev-server/src/source/asset_graph.rs, crates/turbopack-dev-server/src/source/mod.rs, crates/turbopack-dev-server/src/source/source_maps.rs, crates/turbopack-dev-server/src/source/static_assets.rs, crates/turbopack-dev-server/src/update/stream.rs, crates/turbopack-node/src/render/mod.rs, crates/turbopack-node/src/render/render_static.rs, crates/turbopack-node/src/render/rendered_source.rs, crates/turbopack-node/src/source_map/content_source.rs
This PR adds support for returning `redirect: { destination, permanent, statusCode }` from `getStaticProps`.
=> Handle getStaticProps.redirect

.github/workflows/pr-clean-caches.yml
it runs every second right now
=> clean branch caches less often

.github/workflows/test.yml, examples/basic/packages/eslint-config-custom/index.js, examples/design-system/packages/eslint-config-acme/index.js, examples/kitchen-sink/packages/eslint-config-custom/index.js, examples/with-changesets/packages/eslint-config-acme/index.js, examples/with-docker/packages/eslint-config-custom/index.js, examples/with-prisma/packages/config/eslint-preset.js, examples/with-rollup/packages/eslint-config-custom/index.js, examples/with-tailwind/packages/eslint-config-custom/index.js
CI currently fails on main because of Prettier.
=> Fix prettier for examples

docs/pages/repo/docs/handbook/_meta.json, docs/pages/repo/docs/handbook/environment-variables.mdx
Folks have asked about how to handle environment variables. Our current recommendation is to use `dotenv-cli`.  A Turborepo-native solution for environment variables is something we are all looking forward to.
=> Doc for environment variables.

crates/next-core/src/next_font_google/mod.rs, crates/next-dev-tests/tests/integration/next/font-google/basic/pages/index.js
This addresses feedback from #3505
=> @next/font/google: css variable followup

examples/with-tailwind/apps/docs/src/pages/index.tsx, examples/with-tailwind/apps/web/src/pages/index.tsx, examples/with-tailwind/packages/ui/package.json, examples/with-tailwind/packages/ui/postcss.config.js, examples/with-tailwind/packages/ui/src/Button.tsx, examples/with-tailwind/packages/ui/src/Card.tsx, examples/with-tailwind/packages/ui/src/index.tsx, examples/with-tailwind/packages/ui/tailwind.config.js, examples/with-tailwind/packages/ui/tsup.config.ts, examples/with-tailwind/pnpm-lock.yaml, examples/with-tailwind/turbo.json
Tailwind example improvements:
* Enable treeshaking by bundling to esm instead of cjs
* Prefix UI classes to avoid app conflicts
* Use tsup to bundle css instead of tailwindcss
* Write new `Card` component to demo bundle size difference between web / docs
=> feat(example): tailwind improvement and treeshaking

.github/renovate.json
Trying to progress WEB-510. PR updates renovate config to include specific dependencies we want to get an update.
This might need some verification once it lands.
=> ci(renovate): trying to enable swc_* updates

.github/renovate.json
=> style(prettier): apply prettier

cli/internal/core/engine.go, cli/internal/run/dry_run.go
This starts to clean up / consolidate the differences between the information Dry Run gathers and the information RealRun has, so we can consolidate to a RunSummary. Extracted from #3431.
=> Move helpers for getting task ancestors/descendants to engine

.github/workflows/upload-nextjs-integration-test-results.yml
Trying to fix filename issue for the uploading test results.
=> ci(workflow): fix version trim for test results data

.github/actions/next-integration-stat/index.js, .github/actions/next-integration-stat/src/index.ts
=> ci(actions): skip unparseable tree

cli/internal/ci/ci.go, cli/internal/ci/vendors.go, cli/internal/client/client.go, cli/internal/ui/ui.go
Brings in https://github.com/jaredpalmer/ci-info which is ported from https://github.com/watson/ci-info
=> feat(cli): support ci header

.github/workflows/test.yml
Before that the PR will be Ok even if rust code doesn't compile
=> add rust_prepare to Ok requirements

cli/internal/ci/ci.go, cli/internal/ci/ci_test.go, cli/internal/ci/vendors.go
=> fix(cli): ci detection

cli/internal/ci/ci.go, cli/internal/client/client.go
Prefer constant over name for metrics
=> fix(cli): prefer constant over name

.github/actions/next-integration-stat/index.js, .github/actions/next-integration-stat/src/index.ts
closes WEB-541, test summary format adjustments.
=> ci(actions): adjust test summary format

examples/with-tailwind/packages/ui/package.json, examples/with-tailwind/packages/ui/src/index.tsx, examples/with-tailwind/packages/ui/tsup.config.ts, examples/with-tailwind/pnpm-lock.yaml
The UI package had a few residual config issues from tweaks.
=> Update minor tailwind example issues.

cli/integration_tests/basic_monorepo/verbosity.t
Fixes breakage introduced in #3661
I'll open another PR that expands when these tests get run to prevent breakages from landing.
=> fix: update verbosity integration tests

cli/Makefile
Revert the part of #3705 that hadn't been vetted properly.
=> Re-add ffi-install step during make

.github/actions/next-integration-stat/index.js, .github/actions/next-integration-stat/src/index.ts, .github/workflows/nextjs-integration-test.yml, .github/workflows/on-nextjs-release-publish.yml
Trying to fix slack posting issue.
=> ci(workflow): set diff_base for release publish event

cli/integration_tests/composable_config/composing-add-keys.t, cli/integration_tests/composable_config/composing-add-tasks.t, cli/integration_tests/composable_config/composing-missing-workspace-config-deps.t, cli/integration_tests/composable_config/composing-missing-workspace-config.t, cli/integration_tests/composable_config/composing-omit-keys-deps.t, cli/integration_tests/composable_config/composing-omit-keys.t, cli/integration_tests/composable_config/composing-override-values-deps.t, cli/integration_tests/composable_config/composing-override-values.t, cli/integration_tests/composable_config/composing-persistent.t, cli/integration_tests/composable_config/monorepo/apps/persistent/package.json, cli/integration_tests/composable_config/monorepo/apps/persistent/turbo.json, cli/integration_tests/composable_config/monorepo/turbo.json, cli/internal/core/engine.go, cli/internal/fs/turbo_json.go
=> Allow overriding persistent flag from workspace

.github/release.yml
Generate release notes automatically.
=> chore(releases): add release config

crates/next-core/src/app_source.rs
fixes app dir with `/(basic)/about` routes
=> fix incorrect segment path

crates/turbo-updater/src/lib.rs, crates/turborepo-lib/src/shim.rs
Recommend using codemod update in the updater so we can leverage @turbo/codemod to handle the package manager, and install type detection for us.
=> feat(cli): reccomend codemod in updater

crates/turbo-tasks-fs/src/attach.rs
avoid a few resolve tasks in this hot code
=> reduce function count

.github/ISSUE_TEMPLATE/0-turborepo-bug-report.yml, .github/ISSUE_TEMPLATE/1-turbopack-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml
=> Add needs:triage label to new issues

.vscode/settings.json, cli/integration_tests/basic_monorepo/monorepo/turbo.json
This doesn't c lose #3793, but verifies that comments work
=> add test to verify that turbo.json can have comments

CONTRIBUTING.md
This process is a little tedious, but it's worth documenting for now. Hopefully in the future we'll have better ways of splitting up our workflows.
=> docs: Documented process for adding crate

crates/next-core/js/src/entry/app/hydrate.tsx, crates/next-core/js/src/entry/next-hydrate.tsx, crates/next-core/src/env.rs
This ensures our tests can run properly as they rely on the next global being present.
=> Ensure next global is initialized correctly

cli/turbo.json, docs/turbo.json, packages/create-turbo/turbo.json, packages/eslint-plugin-turbo/turbo.json, turbo.json
Trying out Workspace Configs in our own repo. Some things I tested:
```
pnpm run turbo run e2e
pnpm run turbo run e2e-prebuild
pnpm run turbo run integration-tests
pnpm run turbo run docs
```
=> Move workspace-specific tasks to workspace configs

crates/turbopack/src/module_options/mod.rs
celling a String in module_options will create a different node.js pool for every processed asset
=> make assets share the webpack loader executor again

.github/actions/next-integration-stat/index.js, .github/actions/next-integration-stat/src/index.ts, .github/workflows/daily-nextjs-integration-test.yml, .github/workflows/nextjs-integration-test.yml, .github/workflows/setup-nextjs-build.yml
- closes WEB-601
This PR setups workflow to trigger next.js integration test daily, then post its result into slack. The summary from this daily run is simplified - no base, no commit link unfurl.
=> ci(workflow): notify daily test results

examples/with-svelte/pnpm-lock.yaml
Svelte example looks like it's not deploying due to some dependency drift.
=> fix(examples): svelte (#3919

examples/kitchen-sink/apps/blog/app/entry.client.tsx, examples/kitchen-sink/apps/blog/app/entry.server.tsx, examples/kitchen-sink/apps/blog/app/root.tsx, examples/kitchen-sink/apps/blog/package.json, examples/kitchen-sink/apps/blog/remix.config.js, examples/kitchen-sink/apps/blog/remix.env.d.ts, examples/kitchen-sink/apps/blog/vercel.json, examples/kitchen-sink/pnpm-lock.yaml
Update lock and remix app for kitchen sink example
=> fix(examples): kitchen-sink (#3920

examples/kitchen-sink/apps/blog/package.json
Force merged an example to unblock the template and missed this line. 
:shame:
=> fix(prettier): remove whitespace from example (#3924

crates/next-core/src/page_source.rs
lazy parse page config from pages
this avoids to need to transform and parse all pages
=> improve startup performance

crates/next-core/js/src/entry/app/route-bootstrap.ts, crates/next-core/js/src/entry/app/route.ts, crates/next-core/js/src/entry/edge-bootstrap.ts, crates/next-core/js/src/internal/edge.ts, crates/next-core/src/app_source.rs, crates/next-core/src/app_structure.rs, crates/next-core/src/next_edge/transition.rs, crates/next-core/src/next_import_map.rs, crates/next-core/src/next_server/context.rs, crates/next-core/src/next_server/transforms.rs, crates/next-core/src/page_source.rs, crates/next-core/src/router.rs, crates/next-dev-tests/tests/integration/next/app/route/input/app/[slug]/route.ts, crates/next-dev-tests/tests/integration/next/app/route/input/app/layout.tsx, crates/next-dev-tests/tests/integration/next/app/route/input/app/page.tsx, crates/next-dev-tests/tests/integration/next/app/route/input/app/test.tsx, crates/next-dev-tests/tests/integration/next/app/route/input/next.config.js, crates/turbopack-node/src/render/node_api_source.rs
https://beta.nextjs.org/docs/routing/route-handlers
=> implement route.js support

crates/next-core/js/package.json, crates/next-core/js/src/entry/app/layout-entry.tsx, crates/next-core/js/types/modules.d.ts, crates/next-core/src/next_import_map.rs, crates/next-dev-tests/tests/package.json, crates/next-dev/benches/bundlers/turbopack/mod.rs, pnpm-lock.yaml
* add `@opentelemetry/api` alias
* fix some renamed imports
=> update to 13.1.7-canary.28

docs/components/Avatar.tsx
Avatar's shouldn't load lazily (they're always above the fold)
=> fix(docs): loading eager for blog avatars

docs/pages/repo/docs/installing.mdx
=> Fix relative links on installing page

.github/CODEOWNERS
=> Remove ownership on Cargo.lock file

docs/pages/repo/docs/getting-started/create-new.mdx
Hey @thilllon! Thanks for opening a PR. That spurred me to get back around to updating this to be a per-package-manager variant.
Closes #3157
=> Add per-package-manager instructions to create-new

.github/CODEOWNERS, CONTRIBUTING.md
Also updated documentation on adding crate
=> docs: Updated codeowners with new turborepo crates

cli/integration_tests/no_args.t, cli/integration_tests/turbo_help.t, crates/turborepo-lib/src/cli.rs, crates/turborepo-lib/src/shim.rs, docs/pages/repo/docs/reference/command-line-reference.mdx
Add new arg and docs to support disabling the update notifier. 
Fixes https://github.com/vercel/turbo/issues/3874
=> feat(cli): support --no-update-notifier

docs/components/ExamplesArea.tsx, docs/components/Feature.tsx, docs/pages/repo/docs/getting-started/_meta.json, docs/pages/repo/docs/getting-started/from-example.mdx, docs/pages/repo/docs/index.mdx, examples/basic/meta.json, examples/design-system/meta.json, examples/kitchen-sink/meta.json, examples/non-monorepo/meta.json, examples/with-changesets/meta.json, examples/with-create-react-app/meta.json, examples/with-docker/meta.json, examples/with-prisma/meta.json, examples/with-react-native-web/meta.json, examples/with-svelte/meta.json, examples/with-tailwind/meta.json
Add examples to docs via SSG and add new page in getting started to improve discoverability. 
@anthonyshew feel free to workshop these titles.
=> feat(docs): use ssg for examples

.github/pull_request_template.md
=> chore(repo): fix markdown checkbox in PR template

.github/workflows/daily-nextjs-integration-test.yml
Small fixes to adjust condition to post to slack for daily test run.
=> ci(workflow): fix slack post condition

crates/next-core/src/next_client_chunks/with_chunks.rs, crates/next-core/src/next_client_component/with_client_chunks.rs, crates/turbopack/src/resolve_options_context.rs
Follow-up changes for https://github.com/vercel/turbo/pull/4018
=> follow up changes from review

.github/workflows/turbopack-nightly-release.yml
=> Typo Turobpack -> Turbopack

.github/pull_request_template.md
=> chore(repo): remove auto label option

crates/next-core/js/src/entry/server-edge-api.tsx, crates/next-core/src/app_source.rs, crates/next-core/src/env.rs, crates/next-core/src/page_source.rs, crates/next-core/src/router.rs, crates/turbo-tasks-env/src/lib.rs, crates/turbopack-node/src/lib.rs, crates/turbopack-node/src/render/node_api_source.rs, crates/turbopack-node/src/render/render_proxy.rs, crates/turbopack-node/src/render/render_static.rs, crates/turbopack-node/src/render/rendered_source.rs
=> add env to spawned processes

crates/node-file-trace/src/lib.rs
Quick follow up to https://github.com/vercel/turbo/pull/3839
=> Hoist TransientInstances in Turbotrace

.cargo/config.toml
This includes the values of generics in debug symbols which improves profiling
=> improve symbol mangling for profiling

.github/workflows/test.yml, crates/next-core/src/next_font_google/mod.rs
Minor fix for the daily next.js test runs.
=> ci(workflow): fix build errors

crates/next-core/js/src/entry/router.ts, crates/next-core/src/app_source.rs, crates/next-core/src/next_edge/transition.rs, crates/next-core/src/page_source.rs, crates/next-core/src/router.rs
allows to use jsx in middleware
=> fix module options in middleware

.github/workflows/setup-nextjs-build.yml
=> ci(workflow): fix detecting current next.js version

crates/turbo-tasks-fs/src/lib.rs
left-over warnings for previous PR
=> fix windows/macOS only warnings

Cargo.lock, crates/turbopack-ecmascript/Cargo.toml, crates/turbopack-ecmascript/src/parse.rs, crates/turbopack-ecmascript/src/transform/mod.rs, crates/turbopack/src/module_options/mod.rs
=> Revert "feat(turbopack_ecmascript): support partial tsconfig for the transform"

crates/next-dev-tests/Cargo.toml, crates/turbopack-core/Cargo.toml, crates/turbopack-tests/Cargo.toml
=> disable issue_path again

crates/next-core/src/next_import_map.rs
=> fix assert alias

crates/turbopack-ecmascript/src/chunk_group_files_asset.rs
Had this diff in my stash, might as well commit it.
=> Small cleanup for ChunkGroupFiles

crates/next-core/js/src/entry/app-renderer.tsx, crates/next-core/src/next_import_map.rs
* [fix manifest for __ssr_module_mapping__](https://github.com/vercel/turbo/commit/4abd87312d05a74ee858a8f556bfe567f3a9e008)
* [add missing styled-jsx alias](https://github.com/vercel/turbo/commit/d9b4a4df7f81b18e657689f4e182bc9ef2259633)
layout-playground
=> fix app dir with latest next.js

crates/next-core/src/next_client_chunks/with_chunks.rs, crates/next-core/src/next_client_component/with_client_chunks.rs, crates/turbopack-cli-utils/src/lib.rs, crates/turbopack-core/src/chunk/list/reference.rs, crates/turbopack-core/src/chunk/mod.rs, crates/turbopack-core/src/introspect/asset.rs, crates/turbopack-css/src/module_asset.rs, crates/turbopack-dev-server/src/introspect/mod.rs, crates/turbopack-dev-server/src/source/asset_graph.rs, crates/turbopack-ecmascript/src/chunk/manifest/chunk_asset.rs, crates/turbopack-ecmascript/src/chunk_group_files_asset.rs, crates/turbopack-ecmascript/src/references/esm/base.rs, crates/turbopack-ecmascript/src/references/esm/dynamic.rs, crates/turbopack-ecmascript/src/references/esm/module_id.rs, crates/turbopack-ecmascript/src/references/esm/url.rs
Add more details to introspection and make it more robust to errors during introspection
go to http://localhost:3000/__turbopack__/
=> improve introspection

.github/turbo-orchestrator.yml
=> Revert "chore(labels): add rule to label non-vercel PRs" (#4144

packages/turbo-ignore/__tests__/checkCommit.test.ts, packages/turbo-ignore/__tests__/getComparison.test.ts, packages/turbo-ignore/__tests__/getTask.test.ts, packages/turbo-ignore/__tests__/getWorkspace.test.ts, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/src/checkCommit.ts, packages/turbo-ignore/src/getComparison.ts, packages/turbo-ignore/src/getTask.ts, packages/turbo-ignore/src/getWorkspace.ts, packages/turbo-ignore/src/ignore.ts
Update logging to use unicode symbols instead of emoji and fix capitalization
=> feat(turbo-ignore): update logging

pnpm-lock.yaml
I forgot to update the lockfile after the next.js removal
=> update lockfile due to removed packages

cli/integration_tests/prune/composable-config.t, cli/integration_tests/prune/produces_valid_turbo_json.t, cli/internal/run/run.go
=> Downgrade git warning to debug.

cli/Makefile, cli/combined-release.yml, cli/combined-shim.yml, cli/cross-release.yml, cli/darwin-release.yml, cli/internal/ffi/ffi.go
=> chore: Flip the Rust switch

.vscode/settings.json
make it easier to find the thing I'm looking for
| Before | After |
| --- | --- |
| <img width="768" alt="CleanShot 2023-03-15 at 15 16 58@2x" src="https://user-images.githubusercontent.com/490968/225455992-b05371e0-ad9d-4f36-a0ed-dbcbede45b27.png"> | <img width="734" alt="CleanShot 2023-03-15 at 15 17 59@2x" src="https://user-images.githubusercontent.com/490968/225456088-90c682d5-5dcb-4e92-8608-dc004a3d7778.png">|
=> Exclude snapshots from VSCode search

.github/workflows/test.yml
new crate was added which need to be excluded for the tests
=> add missing turborepo exclude in turbopack tests

crates/turbo-tasks/src/manager.rs
Previous PR introduced a bug, which caused the update to be incorrectly taken: https://github.com/vercel/turbo/pull/4208/files#diff-a50d2da0351cec2aa42fefbb4374be064cc62bcf56c0d56f3b7edf96a92bac33L585-L588
=> fix incorrect refactoring and add comments

crates/turbopack-node/src/evaluate.rs, crates/turbopack-node/src/lib.rs
emit a package.json to .next for evaluate pool
fixes WEB-729
=> emit a package.json in evaluate too

docs/components/Footer.tsx, docs/components/FullTurboCTA.tsx, docs/components/Navigation.tsx, docs/pages/blog/you-might-not-need-typescript-project-references.mdx
contact/turborepo is replaced by contact/sales
=> fix(docs): update ent link

crates/turbopack-dev/js/src/runtime.none.js
When the runtime chunk is the last one executed, we still need to run the runtime module.
=> fix chunk runner when all chunks are available

crates/turbo-tasks-macros/src/func.rs, crates/turbo-tasks/src/native_function.rs
Reduces a few copies of functions
=> reduce number of generic instances

crates/turbopack-node/src/source_map/mod.rs
Avoid stack traces getting to noisy
=> limit number of code frames per stack trace to 3

crates/turbopack-node/src/source_map/mod.rs
This reverts commit 6b935dd966ca11c5da0ee9cc278ee6826223319d.
=> Revert "remove left-over print out"

crates/turbo-binding/Cargo.toml
This PR exposes a new feature from dependencies for the next-swc.
=> feat(turbo-binding): expose new features

cli/integration_tests/basic_monorepo/run_summary/run_summary.t, cli/internal/cache/async_cache.go, cli/internal/cache/cache.go, cli/internal/cache/cache_fs.go, cli/internal/cache/cache_fs_test.go, cli/internal/cache/cache_http.go, cli/internal/cache/cache_noop.go, cli/internal/cache/cache_test.go, cli/internal/run/real_run.go, cli/internal/runcache/runcache.go, cli/internal/taskhash/taskhash.go
Reverts vercel/turbo#4225
Fixes https://github.com/vercel/turbo/issues/4389
=> Revert "Add cache state to task summaries on real runs"

crates/turbopack-ecmascript/src/references/cjs.rs
require("x") where x is ignored should lead to an empty object
fixes WEB-829
=> ignored modules yield empty objects insteaad of throwing

cli/integration_tests/no_args.t, cli/integration_tests/turbo_help.t, crates/turborepo-lib/src/cli.rs
Closes #4417.
Added tests for parsing `-F` to CLI parser tests
=> feature(turborepo): `-F` as filter shorthand

crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-core/src/resolve/pattern.rs, crates/turbopack-tests/tests/snapshot.rs
e. g. `"browser": { "fs": false, "net": "./other.js" }` need to be handled
tests in next.js
fix WEB-839
=> use alias field for resolving module requests in packages

.github/actions/next-integration-stat/src/index.ts, package.json, pnpm-lock.yaml
Updates prettier to latest and runs fix
=> chore(prettier): update and run

crates/turbopack-create-test-app/src/main.rs, crates/turbopack-create-test-app/src/test_app_builder.rs
allow to pass effect mode to create-test-app CLI
=> allow to specific effect mode for creating test app

crates/turbopack-node/js/src/ipc/index.ts
avoid zombie node.js processes
=> make sure Node.js process closes when server disappears

crates/turbopack-core/src/chunk/list/update.rs, crates/turbopack-core/src/version.rs, crates/turbopack-dev-server/src/source/mod.rs, crates/turbopack-dev-server/src/update/protocol.rs, crates/turbopack-dev-server/src/update/server.rs, crates/turbopack-dev-server/src/update/stream.rs, crates/turbopack-dev/src/ecmascript/merged/update.rs
this adds HMR support for streaming responses
=> fix HMR for streaming responses

docs/package.json, pnpm-lock.yaml
Fix for error here: https://github.com/vercel/turbo/actions/runs/4610595523/jobs/8149244203#step:3:171
=> fix(docs): correct peer dependency error

.github/workflows/nextjs-integration-test.yml
This test is a tiny test suite recently fixed by WEB-667, we can include it in subset tests to verify flakyness.
=> test(turbopack): add one more test for flaky subsets

crates/turbopack-ecmascript/src/references/esm/module_item.rs
due to eventual consistency these errors might occur temporarily
This change improve how they are handled and avoids panics here
=> avoid panic in EsmModuleItem

examples/with-rollup/apps/web/package.json, examples/with-rollup/package.json, examples/with-rollup/packages/ui/package.json, examples/with-rollup/pnpm-lock.yaml
Fixes https://github.com/vercel/turbo/issues/4507
=> fix(examples): with-rollup

docs/components/LogoContext/index.tsx
Missed a class on the new context menu
=> fix(docs): context menu wide screen

docs/pages/repo/docs/core-concepts/caching.mdx
Adds a missing comma in an example `turbo.json` file.
=> docs: add missing comma in `turbo.json`

.github/workflows/bench-turbopack-scheduled.yml, .github/workflows/dispatch-turbopack-custom-bench.yml, .github/workflows/dispatch-turbopack-custom-matrix-bench.yml
follow up from https://github.com/vercel/turbo/pull/4553
=> review follow ups

crates/turbopack-dev-server/src/lib.rs
need to call listen() on the socket
=> fixup bind v6 PR: add missing listen call

crates/turbopack-ecmascript/src/references/esm/module_item.rs
remove panic since this might happen due to eventual consistency
=> remove panic since this might happen due to eventual consistency

crates/turbopack-node/src/bootstrap.rs, crates/turbopack-node/src/evaluate.rs, crates/turbopack-node/src/lib.rs
lazy creation of the chunk group to make walking introspection faster
=> make node bootstrap asset lazy

examples_tests/setup.sh
Fixes path to script in examples tests
=> fix(tests): correct path in examples setup

.github/workflows/test.yml
Benchmark windows and macos in PRs too
=> run benchmarks on windows and macOS too

crates/turbo-tasks-memory/src/task.rs
=> reduce size of TypeType from 32bytes to 16bytes

crates/turbo-tasks/src/task_input.rs, crates/turbopack-dev-server/src/source/source_maps.rs, crates/turbopack-dev-server/src/source/wrapping_source.rs, crates/turbopack-image/src/process.rs
* refactor image processing
* fallback guess format for extension
* expose pathname_to_url for wrapped source usage
see also https://github.com/vercel/next.js/pull/48622
=> Image processing improvements

Cargo.lock, crates/turborepo-api-client/src/lib.rs, crates/turborepo-lib/src/cli.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/unlink.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/config/turbo.rs, crates/turborepo-vercel-api-mock/src/lib.rs
Extend link/unlink to support target.
=> feat(turbo): add spaces link

.github/CODEOWNERS
=> Turborepo should own turborepo-tests

crates/turbopack-dev-server/src/http.rs
We never reported issues from get_from_source. This leads to cryptic fatal errors from get_from_source without further details.
Now we report the actual issues with show the details.
Before:
```
[500] error (1056ms): node process exited before we could connect to it with exit status: 1
Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NodeRenderGetContentResult::get failed
- Execution of render_static failed
- node process exited before we could connect to it with exit status: 1
Process output:
Process error output:
/workspaces/nextpack/next.js/packages/next-swc/crates/next-dev-tests/tests/integration/next/app/implicit-metadata/input/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_688069._.js:429
^
Error: Could not …
```
=> fix error reporting for get_from_source errors

Cargo.lock, crates/turbopack-image/Cargo.toml, crates/turbopack-image/src/process/SVG_LICENSE, crates/turbopack-image/src/process/mod.rs, crates/turbopack-image/src/process/svg.rs
=> add svg size extraction

crates/turbopack-image/src/process/svg.rs
see https://github.com/vercel/next.js/pull/48947#issuecomment-1528900774
thanks @joacub
=> fix viewbox with decimals

crates/turborepo-lib/src/config/repo.rs
Fix up linting complaining about unused imports.
N/A
=> chore: remove unused path imports

crates/turbopack/src/lib.rs, crates/turbopack/src/resolve.rs, crates/turbopack/src/unsupported_sass.rs
See [Next.js PR](https://github.com/vercel/next.js/pull/49151)
link WEB-981
=> Print a warning when importing Sass files

crates/turbopack-core/src/issue/resolve.rs
Better error message when import mapping fails
=> avoid errors in computing issue details

docs/components/pages/landing/index.tsx, docs/pages/pack/docs/comparisons/webpack.mdx, docs/pages/pack/docs/features.mdx, docs/pages/pack/docs/features/frameworks.mdx, docs/pages/pack/docs/features/imports.mdx, docs/pages/pack/docs/features/javascript.mdx, docs/pages/pack/docs/index.mdx
=> Update Turbopack docs for beta release

examples/with-rollup/turbo.json
=> fix(examples): with rollup

docs/components/pages/pack-home/PackBenchmarks.tsx
=> Update Next.j 13 benchmark version to 13.4

.github/workflows/nextjs-integration-test.yml
Adding one more test into flaky subset.
=> ci(workflow): enable more test

crates/turbopack-ecmascript-plugins/src/transform/directives/server.rs
=> refactor(ecmascript-plugins): update serverdirective signature

crates/turbopack-ecmascript/src/transform/mod.rs
Closing WEB-1024 on turbopack end.
=> refactor(ecmascript): remove unwrap_module ast cloning

CONTRIBUTING.md, docs/turbo/generators/config.js, docs/turbo/generators/templates/release-blog-post.hbs, docs/turbo/generators/utils.js
Use our own generators for release blog posts
=> feat(docs): add generators for release posts

crates/turbopack-mdx/src/lib.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_options_context.rs
=> expose mdx `providerImportSource` option

packages/turbo-gen/tsconfig.json
Exclude templates from the turbo/gen templates type check
=> fix(turbo-gen): add templates to excludes

.github/CODEOWNERS
@anthonyshew want to make it official so you get tagged in reviews?
=> Update CODEOWNERS for docs

examples/basic/package.json, examples/basic/packages/ui/index.tsx, examples/basic/packages/ui/package.json, examples/basic/packages/ui/turbo/generators/config.ts, examples/basic/packages/ui/turbo/generators/templates/component.hbs, examples/basic/pnpm-lock.yaml
Add a simple generator to the basic example
=> feat(basic): add generators to basic example

packages/turbo-gen/src/commands/run/index.ts, packages/turbo-gen/src/commands/run/prompts.ts, packages/turbo-gen/src/commands/workspace/index.ts, packages/turbo-gen/src/generators/custom.ts, packages/turbo-gen/src/templates/simple-js/config.js, packages/turbo-gen/src/templates/simple-js/templates/turborepo-generators.hbs, packages/turbo-gen/src/templates/simple-ts/config.ts, packages/turbo-gen/src/templates/simple-ts/templates/turborepo-generators.hbs
Improves the experience of running `turbo gen` without existing configuration
=> feat(turbo/gen): improved onboarding

crates/turborepo-paths/src/absolute_system_path.rs, crates/turborepo-paths/src/absolute_system_path_buf.rs, crates/turborepo-paths/src/anchored_system_path_buf.rs, crates/turborepo-paths/src/lib.rs, crates/turborepo-paths/src/relative_unix_path.rs, crates/turborepo-paths/src/relative_unix_path_buf.rs, crates/turborepo-scm/src/git.rs
We don't need two Path error types, so consolidated them.
Existing tests should suffice.
=> refactor(turborepo): Consolidated PathError and PathValidationError

crates/turbopack-core/src/reference_type.rs, crates/turbopack-ecmascript/src/text/mod.rs
Small fix to avoid breakin 1 next.js test
=> followup fix

docs/pages/blog/turbo-1-9-0.mdx
=> fix(blog): correct docs link copy

docs/pages/repo/docs/core-concepts/monorepos/code-generation.mdx
Link examples with Turborepo generators
=> feat(docs): link examples with generators

Cargo.lock
update dependencies to be in sync with next.js
=> sync dependencies with next.js

CONTRIBUTING.md, benchmark/README.md
=> docs: add better instructions for building turbo in benchmarking readme

docs/components/ExamplesCard/index.tsx
Update color of examples card titles
=> feat(docs): change cards title color

cli/internal/server/server.go, crates/turborepo-lib/Cargo.toml
Flip flag to use Go daemon for hotfix on `1.10.1`
=> feat(turborepo): Set feature to use Go daemon

cli/Makefile, packages/turbo-types/README.md, packages/turbo-types/package.json
Published as alpha - https://www.npmjs.com/package/@turbo/types/v/0.0.0-alpha.0
=> feat(types): publish turbo types

cli/internal/daemon/connector/connector.go, crates/turborepo-globwatch/src/lib.rs, crates/turborepo-lib/src/cli.rs, crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/endpoint.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/tracing.rs
Adds clean command to turbo daemon.
=> feat(daemon): clean

cli/internal/runsummary/run_summary.go
Add comment about changing run summary version
=> chore(cli): add note about changing run summary

.github/CODEOWNERS
=> chore(ci): CODEOWNERS updates

crates/turborepo-lib/src/commands/generate.rs
Fixes https://github.com/vercel/turbo/issues/5075
Verified this works via parallels:
=> fix(gen): swap to which for windows

crates/turbopack-image/src/process/mod.rs
=> feat(turbopack-image): enable a few more image formats

crates/turbopack-node/src/pool.rs
* I need more than 60s to debug a problem.
* print nicer error messages when JSON is invalid
=> improve error reporting, omit timeout while debugging

.github/workflows/test.yml
=> fix next-swc CI check

packages/create-turbo/jest.config.js, packages/eslint-plugin-turbo/jest.config.js, packages/turbo-codemod/jest.config.js, packages/turbo-gen/jest.config.js, packages/turbo-ignore/jest.config.js, packages/turbo-utils/jest.config.js, packages/turbo-workspaces/jest.config.js
Only run jest in verbose mode when we have also set the github action to run in verbose mode.
=> feat(ci): conditionally set jest verbosity

.github/workflows/test.yml
Update filter for JS Package Tests
=> fix(packages): update filter for JS tests

packages/devlow-bench/README.md, packages/devlow-bench/package.json, packages/devlow-bench/src/browser.ts, packages/devlow-bench/src/cli.ts, packages/devlow-bench/src/describe.ts, packages/devlow-bench/src/file.ts, packages/devlow-bench/src/index.ts, packages/devlow-bench/src/interfaces/compose.ts, packages/devlow-bench/src/interfaces/console.ts, packages/devlow-bench/src/interfaces/datadog.ts, packages/devlow-bench/src/interfaces/interactive.ts, packages/devlow-bench/src/interfaces/json.ts, packages/devlow-bench/src/runner.ts, packages/devlow-bench/src/shell.ts, packages/devlow-bench/src/table.ts, packages/devlow-bench/src/types.d.ts, packages/devlow-bench/src/units.ts, packages/devlow-bench/src/utils.ts, packages/devlow-bench/tsconfig.json, pnpm-lock.yaml
adds `@vercel/devlow-bench` package which can run a benchmark file
=> add tool to benchmark developer workflow performance

docs/pages/repo/docs/ci/github-actions.mdx, examples/design-system/.github/workflows/release.yml, examples/with-changesets/.github/workflows/release.yml
There are no code changes here, so it should be a pretty easy ✅
=> docs(examples): update examples and docs to use node 18

Cargo.lock
Preparation to release to next.js
=> update dependencies to sync with next.js

cli/internal/run/real_run.go
- iterate over channel rather than relying on a count
- close the channel to exit output loop
=> feat(turborepo): A few cleanup nits around log grouping

.github/workflows/test.yml, crates/turborepo-globwalk/src/lib.rs, crates/turborepo-lib/src/package_graph/mod.rs, crates/turborepo-lib/src/run/global_hash.rs, crates/turborepo-lib/src/run/graph.rs
Turns out we weren't actually erroring on clippy warnings in CI. Now we do.
Verify that clippy CI is running
=> fix(ci): Actually make us error on clippy warnings

.github/workflows/test.yml, crates/turbo-tasks-macros/src/lib.rs, crates/turbo-tasks-memory/src/lib.rs, crates/turbo-tasks-signposter-sys/src/lib.rs, crates/turbo-tasks-tracing-signpost/src/layer.rs, crates/turbopack-dev-server/src/update/server.rs, crates/turbopack-ecmascript-plugins/src/transform/styled_jsx.rs, crates/turbopack-ecmascript-plugins/src/transform/swc_ecma_transform_plugins.rs, crates/turbopack-ecmascript/src/analyzer/graph.rs, crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-ecmascript/src/transform/mod.rs, crates/turbopack-ecmascript/src/tree_shake/graph.rs, crates/turbopack-ecmascript/src/typescript/resolve.rs, crates/turbopack-node/src/lib.rs
=> fix(ci): Turbopack Clippy CI

turborepo-tests/e2e/index.ts
- add debugging for e2e test failures
=> feat(turborepo): Debugging output for e2e tests

crates/turborepo-lib/Cargo.toml, crates/turborepo-updater/Cargo.toml
https://doc.rust-lang.org/cargo/reference/features.html#dependency-features
=> chore: replace  `default_features` with `default-features`

.github/workflows/test.yml, examples-tests/setup.sh, turbo.json
- Run examples whenever we change the cli
- Use the locally-built `turbo` when running examples
Runs the examples
=> Run examples in more scenarios

docs/pages/repo/docs/core-concepts/monorepos/task-dependencies.mdx
Iterating on the doc for dependencies outside of a task!
=> Plainer explanation for synthetic tasks.

crates/turbopack-ecmascript/src/references/esm/base.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-ecmascript/src/tree_shake/tests.rs
I've look at this 1500 line abomination too many times
=> reduce indent in `analyze_ecmascript_module` by splitting the function up

crates/turborepo-globwalk/src/lib.rs
- if the calculated root for a glob doesn't exist, `wax` returns an error
- handle the "not found" io error
- new test for the relevant case
=> fix(turborepo): Handle globbing into directories that don't exist

Cargo.lock, Cargo.toml
=> Revert "Update `swc_core` to `v0.78.24`"

crates/turbopack-ecmascript-runtime/js/src/build/runtime.ts
=> Fix rebase error with ESM interop

crates/turborepo-lib/src/cli.rs, crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/package_graph/builder.rs, crates/turborepo-lib/src/package_graph/mod.rs, crates/turborepo-lib/src/run/graph.rs, crates/turborepo-paths/src/anchored_system_path_buf.rs, turborepo-tests/integration/tests/command-info.t, turborepo-tests/integration/tests/no_args.t, turborepo-tests/integration/tests/turbo_help.t
Wrote a simple turbo info command. It's hidden because it's not meant for public use just yet (gotta write a proposal and do some devex work before that). Mostly meant to exercise and test package graph
Added some integration tests for `turbo info`
=> feature(turborepo): Turbo Info Command

examples-tests/npm-non-monorepo/test.t, examples-tests/npm-with-npm/test.t, examples-tests/npm-with-yarn/test.t, examples-tests/pnpm-basic/test.t, examples-tests/pnpm-gatsby/test.t, examples-tests/pnpm-kitchen-sink/test.t, examples-tests/pnpm-with-svelte/test.t, examples-tests/yarn-non-monorepo/test.t, examples-tests/yarn-with-npm/test.t, examples-tests/yarn-with-yarn/test.t
- setting examples tests to `errors-only` should give us some output when they break
Examples test suite
=> feat(turborepo): Switch examples over to errors-only

Cargo.lock, crates/turbo-tasks-env/Cargo.toml, crates/turbo-tasks-env/src/dotenv.rs, crates/turbopack-tests/tests/snapshot/env/env/input/.env, crates/turbopack-tests/tests/snapshot/env/env/input/index.js, crates/turbopack-tests/tests/snapshot/env/env/output/crates_turbopack-tests_tests_snapshot_env_env_input__env__env_b53fce.js, crates/turbopack-tests/tests/snapshot/env/env/output/crates_turbopack-tests_tests_snapshot_env_env_input__env__env_b53fce.js.map, crates/turbopack-tests/tests/snapshot/env/env/output/crates_turbopack-tests_tests_snapshot_env_env_input_index_b53fce.js, crates/turbopack-tests/tests/snapshot/env/env/output/crates_turbopack-tests_tests_snapshot_env_env_input_index_b53fce.js.map
This package support expansion with default like: `VAR=${OTHER:-default}`
=> use dotenvs package instead

docs/pages/repo/docs/getting-started/create-new.mdx
-- Update outdated documentation in create-new.mdx
=> docs: update create-new.mdx

examples/kitchen-sink/README.md, examples/kitchen-sink/apps/admin/turbo.json, examples/kitchen-sink/apps/api/turbo.json, examples/kitchen-sink/apps/blog/turbo.json, examples/kitchen-sink/apps/storefront/turbo.json, examples/kitchen-sink/packages/logger/turbo.json, examples/kitchen-sink/packages/ui/turbo.json, examples/kitchen-sink/pnpm-lock.yaml, examples/kitchen-sink/turbo.json
We don't have any examples to show folks for [Workspace Configurations](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces). This example is a good one for doing so because of the various output directories involved.
=> Use Workspace Configurations.

Cargo.lock, Cargo.toml, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/config/turbo.rs
=> Revert "fix(turborepo): use serde_jsonc recommended pattern."

crates/turbo-tasks-memory/src/memory_backend.rs
very simple detection of dumb mistakes
=> add direct cycle detection

packages/create-turbo/package.json, packages/create-turbo/src/cli.ts, packages/turbo-gen/package.json, packages/turbo-gen/src/cli.ts, pnpm-lock.yaml
- set global agent based on env vars, handled via `ProxyAgent`
- fixes #5446 
Verified manually, by setting env vars
=> feat(turborepo): Add proxy support to create-turbo and turbo-gen

crates/turbopack-build/src/chunking_context.rs, crates/turbopack-core/src/chunk/chunking_context.rs, crates/turbopack-dev/src/chunking_context.rs, crates/turbopack/src/transition/mod.rs
Using the new ability to return `Vc<Self>`
=> make with_layer return Vc<Self>

Cargo.lock, Cargo.toml
=> update swc_core and sync deps

crates/node-file-trace/src/lib.rs, crates/turbopack-core/src/issue/mod.rs, crates/turbopack-core/src/reference/mod.rs, crates/turbopack-dev-server/src/source/issue_context.rs, crates/turbopack-dev-server/src/update/stream.rs, crates/turbopack-node/src/render/rendered_source.rs, crates/turbopack-node/src/transforms/postcss.rs, crates/turbopack-tests/tests/execution.rs, crates/turbopack-tests/tests/snapshot.rs
This name better describes the trait.
=> IssueFilePathExt -> IssueDescriptionExt

crates/turbopack-dev/src/ecmascript/content.rs
The default implementation will handle that without an error
=> remove error in update

packages/turbo-gen/package.json, pnpm-lock.yaml
Reduce published and install bundle size of @turbo/gen
=> chore(gen): reduce published bundle size

crates/turbo-tasks/src/raw_vc.rs, crates/turbo-tasks/src/trait_ref.rs, crates/turbopack-build/src/chunking_context.rs, crates/turbopack-build/src/ecmascript/minify.rs, crates/turbopack-build/src/ecmascript/node/content.rs, crates/turbopack-cli/src/build/mod.rs, crates/turbopack-tests/tests/snapshot.rs
* Pass MinifyType as value instead of Vc
* Avoid panic in parsing code
* add into_trait_ref_strongly_consistent_untracked method on trait vcs
=> Cleanup minify

crates/turborepo-lib/src/package_graph/builder.rs
We currently don't include the path to the package json with a missing name. This adds it.
=> feat: expose path to invalid package.json in error

packages/turbo-gen/src/generators/empty.ts, packages/turbo-gen/src/utils/gatherAddRequirements.ts
Use better placeholder scripts. Also, don't ask about source unless we're actually copying.
=> fix(turbo-gen): better placeholders

packages/turbo-ignore/src/errors.ts, packages/turbo-ignore/src/types.ts
Prettify this error for users since it became a bit more opaque during port (I believe)
=> feat(turbo-ignore): add better error message

.github/workflows/test.yml, .vscode/settings.json, examples/basic/tsconfig.json, examples/with-tailwind/tsconfig.json, packages/devlow-bench/.eslintrc.cjs, packages/devlow-bench/tsconfig.json, packages/eslint-config/library.js, packages/turbo-ignore/__tests__/args.test.ts, packages/turbo-ignore/__tests__/checkCommit.test.ts, packages/turbo-ignore/__tests__/getComparison.test.ts, packages/turbo-ignore/__tests__/getTask.test.ts, packages/turbo-ignore/__tests__/getWorkspace.test.ts, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/package.json, packages/turbo-ignore/src/args.ts, packages/turbo-ignore/src/checkCommit.ts, packages/turbo-ignore/src/errors.ts, packages/turbo-ignore/src/getComparison.ts, packages/turbo-ignore/src/getTask.ts, packages/turbo-ignore/src/getWorkspace.ts, packages/turbo-ignore/src/ignore.ts, packages/turbo-ignore/src/index.ts, packages/turbo-ignore/src/logger.ts, packages/turbo-types/src/index.ts, packages/turbo-types/src/types/config.ts, packages/turbo-types/src/types/dry.ts, pnpm-lock.yaml, turbo.json
=> fix(lint): turbo-ignore

crates/turborepo-lib/src/opts.rs
Porting the section of [`configureRun`](https://github.com/vercel/turbo/blob/main/cli/internal/run/run.go#L132) that configures fields related to our github actions detection/logging.
These fields are used by `execContext` for logging behavior.
👀 
Closes TURBO-1251
=> feat: port github action detection

crates/turbopack-core/src/reference_type.rs
next.js needs that
Closes WEB-1439
=> add middleware entry type

.github/workflows/test.yml, packages/create-turbo/src/cli.ts, packages/create-turbo/src/commands/create/index.ts, packages/create-turbo/src/commands/create/prompts.ts, packages/create-turbo/src/transforms/errors.ts, packages/create-turbo/src/transforms/git-ignore.ts, packages/create-turbo/src/transforms/official-starter.ts, packages/create-turbo/src/transforms/package-manager.ts, packages/create-turbo/src/transforms/types.ts, packages/create-turbo/src/utils/git.ts, packages/create-turbo/src/utils/isOnline.ts, packages/create-turbo/src/utils/notifyUpdate.ts
=> fix(lint): create-turbo

.github/workflows/test.yml, packages/eslint-plugin-turbo/.eslintrc.js, packages/eslint-plugin-turbo/lib/index.ts, packages/eslint-plugin-turbo/lib/rules/no-undeclared-env-vars.ts, packages/eslint-plugin-turbo/lib/utils/calculate-inputs.ts, packages/eslint-plugin-turbo/lib/utils/dotenv-processing.ts, packages/eslint-plugin-turbo/lib/utils/wildcard-processing.ts
=> fix(lint): eslint-plugin-turbo

.github/actions/cargo-sweep/package.json, .github/actions/next-integration-stat/package.json, .github/actions/turbopack-bump/package.json, examples/with-tailwind/packages/ui/package.json, packages/create-turbo/package.json, packages/devlow-bench/package.json, packages/eslint-plugin-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo-gen/package.json, packages/turbo-ignore/package.json, packages/turbo-test-utils/package.json, packages/turbo-tracing-next-plugin/package.json, packages/turbo-types/package.json, packages/turbo-utils/package.json, packages/webpack-nmt/package.json
Fix globs -  silly mistake from copy pasting from the first package that I converted. 
Closes TURBO-1270
=> fix(lint): correct globs

crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/manager.rs
avoids cloning a vec/set for invalidation
Closes WEB-1461
=> avoid cloning a large list of task ids

docs/pages/repo/docs/handbook/linting/eslint.mdx
Updated wording from comment on https://github.com/vercel/turbo/pull/5812
Closes TURBO-1276
=> chore(docs): update lint callout

.github/workflows/test.yml, packages/turbo-utils/__tests__/getTurboConfigs.test.ts, packages/turbo-utils/package.json, packages/turbo-utils/src/convertCase.ts, packages/turbo-utils/src/createProject.ts, packages/turbo-utils/src/examples.ts, packages/turbo-utils/src/getTurboConfigs.ts, packages/turbo-utils/src/getTurboRoot.ts, packages/turbo-utils/src/isFolderEmpty.ts, packages/turbo-utils/src/isWriteable.ts, packages/turbo-utils/src/logger.ts, packages/turbo-utils/src/managers.ts, packages/turbo-utils/src/searchUp.ts, packages/turbo-utils/src/types.ts, packages/turbo-utils/src/validateDirectory.ts, packages/turbo-workspaces/src/utils.ts, pnpm-lock.yaml
=> fix(lint): @turbo/utils

.github/workflows/test.yml, packages/webpack-nmt/src/index.ts
=> fix(lint): webpack nmt

.github/workflows/turborepo-release.yml
Fix Turborepo release process
Closes TURBO-1303
=> fix(release): use capnproto in release tests

.github/workflows/nextjs-integration-test.yml
The name of the flag has changed
=> Switch integration tests to turbopack

examples-tests/pnpm-kitchen-sink/test.t, examples/kitchen-sink/apps/storefront/package.json, examples/kitchen-sink/pnpm-lock.yaml
Changed the number of packages for the kitchen-sink tests which broke the automated prysk tests. 
Closes TURBO-1320
=> fix(tests): kitchen-sink updates

examples-tests/pnpm-gatsby/test.t
Fix gatsby examples test
Closes TURBO-1325
=> fix(examples-tests): correct gatsby prysk test

crates/turbo-tasks-fs/src/lib.rs, crates/turbopack-core/src/issue/resolve.rs, crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-core/src/resolve/options.rs, crates/turbopack-ecmascript/src/references/async_module.rs
Reduces the load on turbo-tasks
Closes WEB-1559
=> Reduce the number of tasks for better performance

crates/turbo-tasks-fs/src/lib.rs, crates/turbopack-core/src/issue/resolve.rs, crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-core/src/resolve/options.rs, crates/turbopack-ecmascript/src/references/async_module.rs
Reverts vercel/turbo#5950
Closes WEB-1569
=> Revert "Reduce the number of tasks for better performance"

crates/turbo-tasks-fs/src/lib.rs
=> reduce unneccessary fs tasks

CONTRIBUTING.md, docs/pages/repo/docs/getting-started/create-new.mdx, packages/create-turbo/__tests__/index.test.ts, packages/create-turbo/src/cli.ts, packages/create-turbo/src/commands/create/index.ts, packages/create-turbo/src/commands/create/types.ts
#5979 was on automerge and I didn't notice. This contains the review changes.
Closes TURBO-1336
=> fix:(create-turbo) Review changes for package manager flag.

crates/turbopack-convert-trace/src/main.rs
add progress
add top 10 self time spans
Closes WEB-1624
=> add progress and top self time to convert trace tool

.github/actions/next-integration-stat/index.js, .github/actions/next-integration-stat/src/index.ts, .github/workflows/nextjs-integration-test.yml, .github/workflows/upload-nextjs-integration-test-results.yml
Print out passed test suite end of the action run, so we can easily grab & compare for the postprocessing.
Closes WEB-1627
=> ci(workflow): print passed test lists for daily

README.md
Copies the latest test results to a known location, instead of waiting for the next daily run.
Re: https://github.com/vercel/turbo/pull/5998
Closes WEB-1630
=> Copy test results to known location

.github/workflows/nextjs-integration-test.yml
Updates test pattern as same as latest upstream.
Closes WEB-1644
=> ci(workflow): update test filter

docs/components/output-mode-table.mdx, docs/pages/repo/docs/reference/command-line-reference/run.mdx, docs/pages/repo/docs/reference/configuration.mdx
Make the outputMode docs more clear
Closes TURBO-1345
=> Output logs docs update

docs/pages/blog/turbo-1-10-0.mdx, docs/pages/showcase.mdx
This includes two small typo fixes in two separate documents.
Nothing special here, it's just markdown files being updated.
=> Fix typo in showcase.mdx

.github/workflows/nextjs-integration-test.yml
Small bug in #6038, didn't remove the dependencies from other tasks.
=> Fix action dependency

crates/turbo-tasks-macros/src/value_trait_macro.rs, crates/turbo-tasks/src/backend.rs, crates/turbopack-convert-trace/src/main.rs
* Add tracing for resolve tasks
* add per execution span summary
Closes WEB-1678
=> Tracing improvements

crates/turbo-tasks-auto-hash-map/src/lib.rs, crates/turbo-tasks-auto-hash-map/src/map.rs, crates/turbo-tasks-auto-hash-map/src/set.rs, crates/turbo-tasks-memory/src/count_hash_set.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-testing/src/lib.rs, crates/turbo-tasks/src/id.rs, crates/turbopack-ecmascript/src/lib.rs
* increase sharding to avoid lock contention
* fix availablity info typo
* add size hints to avoid multiple allocations
* improve AutoMap/Set thresholds
* uses non-zero usize to leverage Option<> optimization
Closes WEB-1679
=> Performance Improvements (1)

Cargo.lock, Cargo.toml, crates/turbo-tasks-auto-hash-map/Cargo.toml, crates/turbo-tasks-auto-hash-map/src/map.rs, crates/turbo-tasks-auto-hash-map/src/set.rs, crates/turbo-tasks-memory/Cargo.toml, crates/turbo-tasks-memory/src/aggregation_tree/bottom_connection.rs, crates/turbo-tasks-memory/src/aggregation_tree/bottom_tree.rs, crates/turbo-tasks-memory/src/aggregation_tree/leaf.rs, crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks-memory/src/output.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/src/task/aggregation.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/manager.rs
Use SmallVec to inline some elements into the field/stack
Closes WEB-1680
=> Performance Improvements (2)

cli/internal/taskhash/taskhash.go
When file hashing encountered an error, we return an error from the worker goroutine. After every worker encounters an error, we cannot make more progress, and cannot send more hashing tasks.
This PR adds a check for the first error returned and aborts the loop that sends more hashing requests. Any failure here was intended to be a failure of the whole operation to begin with, and would've been reported as such if all the workers were not exhausted. 
Manually on repro repo from #6016 
Fixes #6016
=> Handle errors from file hashing

crates/turbo-tasks-memory/src/aggregation_tree/bottom_connection.rs, crates/turbo-tasks-memory/src/aggregation_tree/bottom_tree.rs, crates/turbo-tasks-memory/src/aggregation_tree/leaf.rs, crates/turbo-tasks-memory/src/aggregation_tree/mod.rs, crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks-memory/src/output.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/src/task/aggregation.rs, crates/turbo-tasks-testing/src/lib.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs
=> Performance Improvements (1+2) review follow-up

.github/workflows/test.yml
Save CI cost by removing unused jobs
Closes WEB-1704
=> remove unnecessary CI jobs and reduce timeout

cli/Makefile, crates/turborepo/Cargo.toml, crates/turborepo/build.rs
Always build the run stub so we can turn it on/off at will
Closes TURBO-1436
=> chore: Always build run stub
