vercel/turborepo

- docs/pages/docs/getting-started.mdx
Fixes typo found on Getting Started docs page
> Typo: it's chaching –> its caching

- create-turbo/templates/npm/package.json
It looks like this isn't necessary and I got an error trying this out with the npm template because yarn was not installed.
> Remove yarn from npm template scripts

- cli/internal/login/link.go
This PR adds a fallback for a User's name to their username. Name is an optional field in Vercel. My user, for example, does not have a name (I don't know how or why). 
This then makes it impossible to set up `turbo link` to a personal workspace. 
e.g. 
Selecting the empty option prompts: `X Sorry, your reply was invalid: Value is required`
Post change:
> Set a fallback for the user's name when running turbo link

- create-turbo/README.md
`Turbo` has been misspelled as `tubro` or `turebo` in the create-turbo package readme
> Fix Spelling Errors in create-turbo readme

- examples/with-pnpm/web/package.json
When i run "pnpm dev" (same as "pnpm run dev") inside the web directory, it comes up with this errors:
These errors appear beacause the "ui" package has not been added yet, so I did it:
```diff
+ "ui": "workspace:*"
```
However, it continues to show other errors because we are using typescript but missing some types library:
And i just added them:
```diff
+ "@types/react": "^17.0.37",
+ "@types/react-dom": "^17.0.11",
```
Run "pnpm dev" again and it worked:
> Fix: add ui package & types library in with-pnpm example

- docs/pages/docs/features/pipelines.mdx
Sometimes one dot can make things different.
Before (on the official site):
Fixed:
> Fix: broken "topologically" link in pipelines docs

- create-turbo/templates/_shared_ts/apps/docs/package.json
- create-turbo/templates/_shared_ts/apps/web/package.json
- examples/basic/docs/package.json
- examples/basic/web/package.json
- examples/with-pnpm/docs/package.json
- examples/with-pnpm/web/package.json
Fix #169 . Turbo does what it is supposed to, we forgot to add ui as a listed dependency
> Fix ui dep in examples

- cli/internal/core/scheduler.go
- cli/internal/core/scheduler_test.go
- cli/internal/run/run.go
- docs/pages/docs/reference/command-line-reference.mdx
Add a new `--only` flag to support restricting task execution to only the tasks specified in `run`. This is to make it easier to adopt turbo in a Lerna codebase since `--only` behavior is effectively an exact match.
For this pipeline:
```json
"turbo": {
"pipeline": {
"build": {
"outputs": [
"dist/**/*"
],
"dependsOn": [
"^build"
]
},
"test": {
"dependsOn": [
"^build"
]
}
}
```
```sh
turbo run test
```    
```sh
turbo run test --only --graph
```
> Add support for `--only` flag that matches lerna/pnpm run behavior

- create-turbo/templates/_shared_ts/package.json
- create-turbo/templates/npm/package.json
- create-turbo/templates/pnpm/package.json
- create-turbo/templates/yarn/package.json
I tried [Getting Started with Turborepo](https://turborepo.org/docs/getting-started), and I found that perhaps some unintentional settings.
I hope it cloud help.
> fix: remove `.`, which is not needed

- docs/pages/docs/guides/complimentary-tools.mdx
According to Cambridge dictionary, `foreseeable` is the correct writing
https://dictionary.cambridge.org/dictionary/english/foreseeable
> Fix forseeable typo in complimentary-tools

- docs/pages/docs/features/scopes.mdx
According to [Wikipedia](https://en.wikipedia.org/wiki/Wildcard_character), [Microsoft](https://support.microsoft.com/en-us/office/examples-of-wildcard-characters-939e153f-bd30-47e4-a763-61897c87b3f4) and [NextJS](https://nextjs.org/docs/api-reference/next.config.js/headers#wildcard-path-matching), `wildcard` is the correct writing.
(Sorry for all the typo PR's 🙈 )
> Fix wildcard typo in scopes docs

- create-turbo/templates/_shared_ts/gitignore
Thank you for the great work on turborepo!
Was using pnpm and noticed the .gitignore from create-turbo does not include pnpm.
> update create-turbo template gitignore pnpm

- create-turbo/templates/_shared_ts/package.json
- create-turbo/templates/npm/package.json
- create-turbo/templates/pnpm/package.json
- create-turbo/templates/yarn/package.json
When running the `yarn format` command on Windows Powershell, double quotes are added to the file pattern and makes it invalid.
```
PS C:\Users\yangshun\developer\my-turborepo> yarn format
yarn run v1.22.5
$ prettier --write '**/*.{ts,tsx,md}'
[error] No files matching the pattern were found: "'**/*.{ts,tsx,md}'".
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The fix is to change the single quotes into escaped double quotes instead. This is used in [Docusaurus](https://github.com/facebook/docusaurus/blob/main/package.json#L44-L47)
```
PS C:\Users\yangshun\developer\my-turborepo> yarn format
yarn run v1.22.5
$ prettier --write "**/*.{ts,tsx,md}"
apps\docs\next-env.d.ts 19ms
apps\docs\pages\index.tsx 14ms …
```
> Use double quotes for prettier file glob in yarn format

- cli/internal/fs/package_json.go
Latest version of turborepo was having issues parsing [lodash](https://www.npmjs.com/package/lodash)'s `package.json` file. Because it has the `keywords` field defined as:
```json
"keywords": "modules, stdlib, util"
```
And not using the standard format:
```json
"keywords": ["modules", "stdlib", "util"]
```
- `lodash` version used is: `v4.17.21` (latest version).
Turborepo was failing (exiting) with errors like:
```
ERROR  error parsing ... /node_modules/lodash/package.json: json: cannot unmarshal string into Go struct field PackageJSON.keywords of type []string
```
This PR handles the above and some slightly weirder ways of defining keywords in package.json
I incremented the version, LMK if this is not the scope of this PR.
> Fix parsing weird formats of the keywords field of some package.json files

- examples/kitchen-sink/package.json
> Kitchen sink: Update cache to boolean, not string

- create-turbo/src/index.ts
This PR is intended to address https://github.com/vercel/turborepo/issues/203. Reading through the code, it seems like this functionality was intended to be supported and seemed like a simple fix so I thought I'd give it a go!
The installation would successfully create all template project files but fail on
```ts
process.chdir(relativeProjectDir);
```
Thus not completing the `git init` step and failing to print out success instructions.
**Output**
```
>>> TURBOREPO
>>> Welcome to Turborepo! Let's get you set up with a new codebase.
? Where would you like to create your turborepo? .
? Which package manager do you want to use? Yarn
? Do you want me to run `yarn install`? Yes
>>> Bootstrapping a new turborepo with the following:
- apps/web: Next.js with TypeScript
- apps/docs: Next.js with …
```
> Fix initiating a project within the current directory

- create-turbo/__tests__/cli.test.ts
- create-turbo/jest.config.js
- create-turbo/tsconfig.json
Got tests running for `create-turbo`.
----
Initially running into:
```
$ jest
FAIL  __tests__/cli.test.ts
● Test suite failed to run
Jest encountered an unexpected token
Details:
/Users/sean/development/turborepo/create-turbo/node_modules/strip-ansi/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import ansiRegex from 'ansi-regex';
^^^^^^
SyntaxError: Cannot use import statement outside a module
```
This was happening for both the `strip-ansi` and the `ansi-regex` libraries.
The combination of the changes in `create-turbo/jest.config.js` and `create-turbo/tsconfig.json` allows the specific modules to be correctly transformed and run by `jest`/`ts-jest`. Not 100% sure if this is the ideal answer here.
Commit: …
> Running create-turbo tests

- create-turbo/src/index.ts
Improved success output for `create-turbo` namely for  the current directory use case. (Follow-up task to https://github.com/vercel/turborepo/pull/212)
Items changed (since indentation was changed so diff is not as easy to parse):
- removed the `if (projectDirIsCurrentDir)` block, inlined the `else` logs
- check `projectDirIsCurrentDir` wherever `relativeProjectDir` is used in the logs
- changed docs link from `https://turborepo.org` -> `https://turborepo.org/docs`
(notice no `cd ...` lines in the success output as we are already in the project directory)
> Improved success output for create-turbo

- cli/internal/fs/fs.go
Should fix #195
- It still uses `filesytem.Split` but just to get the directory name to create it if it doesn't exist.
- It opens the file with `os.OpenFile` and set the file permissions there instead of after copying.
- It removes the file if `io.Copy` returns an error.
- It doesn't need error handling on `toFile.Close` as it only returns an error if it's called multiple times.
> Remove WriteFile and move it into CopyFile

- docs/components/pages/home.tsx
- docs/pages/_document.js
- docs/theme.config.js
- Fix font-display to remove jank
- Fix dark-mode hero start building button
> Docs papercuts

- cli/internal/cache/cache.go
- cli/internal/config/config.go
Change logic to support `teamId` or `teamSlug` being present to enable remote caching
> Fix remote cache config detection to support just slug

- cli/internal/run/run.go
- docs/pages/docs/reference/command-line-reference.mdx
- Dash case all flags (non-breaking)
- Document --cache-dir 
- Deprecate --cacheFolder
- Fix --global-deps flag
- Support --include-dependencies
Shipping this as a bandaid now so I can focus my attention on #218
> CLI papercuts

- docs/pages/docs/guides/complimentary-tools.mdx
The repository linked from the current documentation has been archived (see archive message [here](https://github.com/microsoft/playwright-test)). The new repo for `playwright` is:
https://github.com/microsoft/playwright
This updates the docs to point to the new repo!
> fix(docs): update playwright link

- examples/with-pnpm/packages/tsconfig/package.json
> chore: removes dup base.json file from package files export

- cli/internal/run/run.go
Solves an issue where if you ran a task without outputs defined, it gets cached, and then you changed outputs to be empty. You would get an incorrect cache hit because the of when in the codebase we hashed outputs (prior to setting defaults). This PR fixes that issue.
> Correctly hash empty outputs first

- cli/internal/context/context.go
- cli/internal/context/context_test.go
Fix #326 and vercel/next.js#32621
> Fix pass thru arguments from becoming targets

- cli/internal/context/context.go
- cli/internal/context/context_test.go
- cli/internal/run/run.go
Fix flaky getTargetsFromArgs tests by returning slices instead of util.Set
> Fix flaky getTargetsFromArgs tests

- cli/internal/context/color_cache.go
- cli/internal/context/context.go
- cli/internal/run/run.go
* Allocate correct capacity for workspace json globs
* Extract workspace ignores into constant slice
* Better encapsulate ColorCache and remove global
* Set ExternalDeps capacity
* Remove redudant word
* Better slice allocation in dependency analysis
> Papercuts in context.go

- .gitignore
- cli/internal/context/context.go
- cli/internal/run/run.go
Fix incorrect assignment of external dependencies list
> Fix internal dep hashing

- docs/pages/docs/features/pipelines.mdx
- docs/pages/docs/features/scopes.mdx
This pull request adds a note to the docs pages for “Scoped Tasks” and “Pipelines” to properly attribute Microsoft for copyrighted content that Turborepo copied from the documentation for Microsoft’s monorepo tool, Lage. Currently, both pages on Turborepo’s documentation come across as original work by the Turborepo team, even though the credit seems it mostly belongs with the Lage maintainers at Microsoft. 
If you compare the pages on Turborepo’s and Lage’s docs, you can see how similar the text content, and APIs are:
* Turborepo’s “Scope Tasks” page: https://turborepo.org/docs/features/scopes
* Lage’s “Scoped Builds” page: https://microsoft.github.io/lage/guide/scopes.html
* Turborepo’s “Pipelines” page: https://turborepo.org/docs/features/pipelines
* Lage’s “Pipelines” page: …
> docs(guides): give appropriate attribution to Microsoft Lage

- cli/internal/cache/cache_fs.go
- cli/internal/prune/prune.go
- cli/internal/run/run_state.go
Close #156 
This is only draft if someone can have discussion with me it would be great
> fix: preserve file permission

- create-turbo/templates/_shared_ts/packages/config/eslint-preset.js
- examples/basic/packages/config/eslint-preset.js
- examples/design-system/packages/eslint-preset-acme/index.js
- examples/with-pnpm/packages/config/eslint-preset.js
Turning this off prevents new turbo users getting eslint-config-next warning about incorrect or unspecified pages directory in the `ui` starter package
> Turn off no-html-link-for-pages eslint rule causing false warning

- cli/internal/context/context.go
Reverts mistake in #358 
Fixes: #398 #414 and possibly even #417
> Fix regression in internal dep hashing

- create-turbo/templates/_shared_ts/apps/docs/package.json
- create-turbo/templates/_shared_ts/apps/web/package.json
- create-turbo/templates/_shared_ts/packages/config/package.json
- create-turbo/templates/pnpm/apps/docs/package.json
- create-turbo/templates/pnpm/apps/web/package.json
- examples/basic/packages/config/package.json
- examples/with-pnpm/packages/config/package.json
This updates Next.js-related packages to the latest version in `create-turbo` and in `examples`. 
v12.0.3 has a [security vulnerability](https://github.com/vercel/next.js/releases/tag/v12.0.5) that is fixed in versions >= 12.0.5 of `next`. Within `create-turbo` and the `examples`, the `next` version is pinned to v12.0.3.
Thanks for taking the time to review this!
> examples: bump next package version

- cli/go.mod
- cli/go.sum
- cli/internal/backends/nodejs/nodejs.go
- cli/internal/context/context.go
- cli/internal/fs/lockfile.go
- cli/internal/fs/lockfile_windows.go
- cli/internal/fs/yarn_lockfile.go
- cli/internal/prune/prune.go
- cli/package.json
- yarn.lock
Fix #252 #145
Finally got a Windows machine for work. This PR fixes a handful of Windows bugs:
- Fixes yarn based build command w/ `cross-env` package
- Fixes "parsing" (i.e. regexing yarn.lock SYML into YAML with correct line endings)
- Removes hacky `CheckIfWindows` 
- Windows users should now have same hashes as non-windows users
> Fix yarn lockfile parsing on Windows

- examples/basic/apps/docs/package.json
- examples/basic/apps/web/package.json
- examples/kitchen-sink/apps/api/package.json
- examples/kitchen-sink/apps/storefront/package.json
- examples/kitchen-sink/packages/logger/package.json
- examples/kitchen-sink/packages/ui/package.json
- examples/with-pnpm/apps/docs/package.json
- examples/with-pnpm/apps/web/package.json
Update the version of `eslint` to the same version everywhere in the examples
> chore: sync the versions of `eslint` to the same 7.32.0 version

- docs/pages/docs/features/scopes.mdx
Fixes the warning:
```console
[WARNING] The --includeDependencies flag has renamed to --include-dependencies for consistency. Please use `--include-dependencies` instead
```
> Prefer `--include-dependencies` in docs

- docs/pages/docs/guides/migrate-from-lerna.mdx
Removes an extra "using" in the docs
> docs: fix typo in migrate-from-lerna.mdx

- cli/internal/context/context.go
- cli/internal/run/run.go
- cli/internal/ui/ui.go
Fix #422 #374 #452 #453
- Refactor log streaming in to move away from `io.MultiReader` which was trying to concatenate streams, and failing when commands wrote directly to stderr. This PR inverts log steam logic to use `io.MultiWriter`, but only when actually caching, as well as new `logstreamer` primitive. 
- Logs now _include_ their own `cache hit, replaying output [hash]` line
- Subsequently, we change the global internal cache key to force new artifacts
- Logs store colored output now
- Ansi-codes are stripped in non-TTY environments
The result of the last 3 bullets are a small perf gain since there is less work to be done when reading logs (colored prefixing isn't cheap).
> Refactor log streaming

- docs/pages/docs/acknowledgments.mdx
> fix: `monroepo` to `monorepo` typo

- examples/kitchen-sink/packages/ui/tsconfig.json
Fix #466
- add `dom` to `tsconfig.compilerOptions`.
> fix kitchen-sink test #466

- docs/pages/docs/getting-started.mdx
The current documentation to install Turborepo with pnpm results in an error, because of a safeguard to prevent unwanted dependencies in the workspace root:
This is easily solved with the `-w` flag, which as far as I understand is equivalent to Yarn's `-W` flag.
> docs: add missing flag for pnpm install command

- cli/internal/run/run_state.go
`runOptions.stream` is now `true` by default, so `Listen` now performs
a lot of empty runs, causing cpu load (one core having 100% load all the time).
This fix prevents the overload by never running the loop if `stream` is set
to `true`, as all cases in the loop relied on it being false.
I left a bunch of debugging notes here: https://github.com/vercel/turborepo/issues/205#issuecomment-1008337702
Should solve these two issues:
Fix https://github.com/vercel/turborepo/issues/205
Fix https://github.com/vercel/turborepo/issues/521
> fix: Move runOptions stream checks before the `for` loop to prevent cpu load

- cli/internal/backends/nodejs/nodejs.go
- cli/internal/context/context.go
The workspaces are required for turborepo to work, but lack of them results in unfriendly error message that does not explain that. The PR may need some changes, that's just a quick fix you could use.
> fix: error when workspaces are not defined

- .github/workflows/ci-go.yml
- cli/internal/prune/prune.go
- scripts/run-examples.sh
Fixes #503 
Sets correct indentation of generated yarn.lock from `turbo prune`. This fixes a regression from <1.0 and re-enables `yarn install --frozen-lockfile` flag to work from within a pruned subset
> Fix syml/yaml lockfile indentation in turbo prune

- cli/internal/fs/copy_file.go
Fixes  #549
The issue is due to an unhandled error bubbling in the case where a symlink exists but the target has been deleted.
Two other things to note here, which may just show my naiveté w Go (this is my first project working with it):
1. I am unsure if there is a standard/best practice for error handling here. Seems errors can bubble/disappear really easily right now
2. A fix like this would benefit from a regression test, but I am not too sure how the testing in this project is handled. I think even a small doc on that would be valuable. I am happy to help put that together or contribute.
> fix: handle dead symlinks in walk

- cli/internal/backends/nodejs/nodejs.go
- cli/internal/util/backends.go
implements https://github.com/vercel/turborepo/pull/544#issuecomment-1013244988.
This PR logs a warning when `packageManager` is not set and falls back as per https://github.com/vercel/turborepo/pull/544#issuecomment-1013244988.
> fix: warn when no packageManager

- docs/pages/docs/reference/command-line-reference.mdx
This PR corrects a minor typo
- `sepecify` => `specify`
> docs(typo): corrects "sepecify"

- .devcontainer/Dockerfile
When running a dev container on a non arm64/Apple Silicon machine I got the following:
```sh
...
#7 0.924 2022-01-21 21:52:15 (7.02 MB/s) - 'hyperfine_1.12.0_arm64.deb' saved [553772/553772]
#7 0.924 
#7 0.938 dpkg: error processing archive hyperfine_1.12.0_arm64.deb (--install):
#7 0.938  package architecture (arm64) does not match system (amd64)
#7 0.944 Errors were encountered while pr
[2022-01-21T21:52:15.716Z] ocessing:
#7 0.944  hyperfine_1.12.0_arm64.deb
...
```
This PR will account for some architectures other than `arm64` (e.g. `amd64`)
See also: https://stackoverflow.com/a/58222507
_note:_ for architectures other than `arm64`, `amd64`, `armhf` or `i686` the install will still fail, so maybe we want a smarter check here.
> fix: conditionally set arch when installing hyperfine

- docs/pages/docs/getting-started.mdx
This PR aims to consolidate install commands across package manager examples to use the shorthand syntax.
While [pnpm's docs](https://pnpm.io/cli/add#--ignore-workspace-root-check--w) are confusing for workspace root installs, it accepts a capital W as the `workspace-root` flag
```
> pnpm add -h
-w, --workspace-root                Run the command on the root workspace project
```
> docs: consolidate install commands

- create-turbo/src/getPackageManagerVersion.ts
- create-turbo/src/index.ts
- create-turbo/src/types.ts
Set `packageManager` in `create-turbo` before install so that the `--no-install` flag will yield a turborepo that will work on the first run without warnings
> Set packageManager in create-turbo before install

- .vscode/launch.json
- cli/cmd/turbo/main.go
- cli/cmd/turbo/signals.go
- cli/go.mod
- cli/go.sum
- cli/internal/process/child.go
- cli/internal/process/child_nix_test.go
- cli/internal/process/child_test.go
- cli/internal/process/manager.go
- cli/internal/process/manager_test.go
- cli/internal/process/sys_nix.go
- cli/internal/process/sys_windows.go
- cli/internal/run/run.go
* When we receive an external signal, send `SIGINT` to our child processes
* When a child process exits w/ a non-zero exit code, and `--continue` is not set, send `SIGINT` to all of our child processes
Practically, this means that hitting `Ctrl+C` on the terminal will shut down all of the child processes via `SIGINT`. Additionally, if one task fails, other tasks will not be left lingering, and will be sent a `SIGINT`.
Some considerations: if `turbo` is invoked via `yarn` or `npm`, it will not be the root of the process tree, and as such `Ctrl+C` will hand control back to the user before `turbo` has exited, meaning that the user will likely get `stdout`/`stderr` after the prompt has reappeared. I don't _think_ there's anything we can do about this.
Running `turbo` directly should avoid …
> Improve child process management

- cli/internal/run/run.go
When executing over the graph, we log to `stdout` and `stderr` from multiple goroutines at once, which is technically not safe. This leads to missing newline characters, which contributes to e2e test flakiness.
> Make logging threadsafe

- cli/internal/run/run.go
Track if we saw any child exit with a non-zero exit code, and use the highest one.
Fixes #694
> Track child exit codes and propagate them

- cli/internal/process/manager_test.go
Bump timeout to make windows tests more likely to pass while still ensuring we are not running in sequence
> Continue de-flaking tests

- cli/internal/backends/nodejs/nodejs.go
- cli/internal/fs/package_json.go
- cli/internal/util/backends.go
Hi.
I fixed a small issue: if there is no version specified in `packageManager` (or just if a value is invalid), the CLI goes into panic. I have also added a friendly error message. I hope it'll make CLI a bit friendlier 🙂
> Fixed crash and added error message if packageManager field is invalid.

- docs/package.json
- docs/pages/docs/guides/migrate-from-lerna.mdx
- yarn.lock
- initial build: https://turbo-site-bd3h6v06j.vercel.sh
- incremental build (edited a page ef3d5d0cd3483f527dfe941c70cd93e63721363d) with cache enabled: https://turbo-site-ji7y3vjb2.vercel.sh 
And the new added word is indexed (along with other pages):
> Fix cache index being missing after incremental builds

- docs/nextra-theme-docs/styles.css
Currently the sidebar text in darmode is text-gray-500 which does not contrast well against the background compared to lightmode and other text in darkmode.
> Increased contrast on the sidebar text in darkmode

- cli/internal/process/child.go
Fixes #729 
We don't need to separately include the command in the label for a child process, `exec.Command` includes the command in the list of arguments.
> Fix doubling of command name in failed child process error

- cli/internal/context/context.go
- cli/internal/run/color_cache.go
- cli/internal/run/run.go
- cli/internal/run/run_state.go
- cli/internal/run/run_test.go
This PR makes a few changes to `Run`. The intention is to separate out a few distinct pieces:
* The complete graph, inferred from the the filesystem and pipeline configuration. This should be reusable across multiple runs on the same filesystem / pipeline
* Run specific configuration: what tasks to run, whether to include dependencies, etc.
* The mechanics of how to execute the run. In parallel? Cache the output? etc.
Review note: it may be easier to go commit by commit.
> Start splitting the Run command up

- cli/npm/turbo-install/install.js
Fix #766 
See https://github.com/evanw/esbuild/issues/1711#issuecomment-1027554035
Following behind `esbuild`, this patches `turbo` postinstall script to fix node 16 ubuntu installation
> fix(cli): Fix install on node 16 on ubuntu

- packages/create-turbo/src/index.ts
To avoid confusion with `lerna boostrap`, this PR changes the word "Bootstrapping" for "Creating" in `create-turbo`
> Change "Bootstrapping" to "Creating" in `create-turbo`

- cli/internal/api/types.go
- cli/internal/backends/nodejs/nodejs.go
- cli/internal/context/context.go
- cli/internal/fs/lockfile.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
- cli/internal/run/run_test.go
`turbo run` should now work properly with the `--cwd` flag. Cleaned up a bunch of usages of implicit current directory as well as `os.Getwd()`
> Running build with --cwd works

- cli/npm/turbo-install/node-platform.js
As mentioned here: https://github.com/vercel/turborepo/issues/693#issuecomment-1055497641
The call to require.resolve(turbo) was failing because the package does not have a main export
defined in the package.json, nor is there an index.js. Since we are just looking for the directory
the package is unplugged into, we can resolve the path to the package.json and get the dirname
of that.
This basically fixes things to the point where the binary is able to execute before hitting the nodeLinker
checks and bailing out with a proper error message.
Before:
```
> yarn turbo --version
C:\source\test-repo\.yarn\unplugged\turbo-npm-1.1.4-c2216ae885\node_modules\turbo\bin\turbo:13
throw e;
^
Error: Qualified path resolution failed - none of those files can be found on the disk.
Source path: …
```
> fix(yarn-pnp): fixing generateBinPath when yarn pnp is enabled

- cli/internal/context/context.go
- cli/internal/context/context_test.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
* `Args` doesn't need to hang off of `Context`
* `TraceFilePath` isn't used, tracing is done via `RunState` instead.
* global hash calculations and root `package.json` calculations can use local variables
* `TaskGraph` is unused.
> Continue evolving `Context` towards a data structure that can be sent over the wire

- cli/internal/config/config_file.go
Edge case on new repo when `.turbo/config.json` doesn't exist.
Normally the `.turbo/config.json` would be written on `yarn turbo link`.
`yarn turbo link` is not applicable after logging in to an --sso-team
> [login sso] Ensure that the RepoConfig Directory and file exists before writting team ID and API url

- cli/internal/login/link.go
Even if the former is technically more accurate (control + c), let's err on the side of more inclusive language.
> Update link.go for more inclusive language.

- cli/internal/context/context.go
- cli/internal/context/context_test.go
- cli/internal/fs/fs.go
- cli/internal/fs/fs_test.go
Check if file paths pointed to by `file:...` are within the monorepo. If so, consider them internal dependencies, and otherwise consider them as external dependencies.
Fixes #847
> Add back support for file:... dependencies

- cli/internal/context/context.go
- cli/internal/context/context_test.go
This technically doesn't conform to semver. `yarn`, `berry`, `pnpm`, and `npm` use `includePrerelease` in their matching, which goes a bit beyond this, so there may be more work required.
However, this change unblocks usage of tools like [semantic release](https://github.com/semantic-release/semantic-release)
> depending on "*" should match everything

- cli/internal/cache/cache_fs.go
- cli/internal/context/context.go
- cli/internal/run/run.go
- cli/scripts/e2e/e2e.ts
This allows people to specify `outputs` outside of the package folder from which the command originated, which is especially useful for code-generation tools and polyglot repos. To enable this, we store artifacts in the cache relative to the root of the monorepo (see screenshot) below for before (top) and after (bottom).
Since we are changing how cache is structured, I updated the global cache key in turbo in order to prevent prior old artifacts from ever ever being cache hits with after this change
The only downside to this change, which might not be a downside at all, I guess, is possibility that artifacts are now tied to the directory structure of outputs relative to the root of the monorepo.
> Allow specifying cache outputs outside of package folder

- docs/pages/docs/getting-started.mdx
Since Turborepo is moving past its "initial public launch" phase, here's a more evergreen statement about remote caching on Vercel.
> docs: make remote caching evergreen

- cli/internal/core/scheduler.go
The main change in this PR switches the task graph construction to add edges only between direct dependencies, rather than the entire ancestor subtree. 
As an example, say `a` depends on `b`, `b` depends on `c`. If `b#build` depends on `c#some-task`, and a#build` depends on `^build`. 
Currently, running `a#build` will do `c#some-task`, `c#build`, `b#build`, and `a#build`.
But, we don't need `c#build`. We just need `c#some-task`, since that's what `b#build` depends on, and `a` doesn't really know anything about `c` directly, just via `b`. So, we instead just draw an edge to direct dependencies, and then let them sort out their own dependencies.
For a large example, here are before and after graphs for running `turbo run build` in `examples/kitchen-sink`:
Before:
After:
Also get rid of an …
> Switch task graph edges to direct dependencies

- cli/internal/run/run.go
Small change to the output of `--dryn-run` command for when the `outputs`-array is empty instead of outputting all but the first one we display all entries
> fix: dump all contents of Outputs instead of all but the first one

- cli/internal/run/run.go
> Remove tabs from run help text

- CONTRIBUTING.md
- package.json
Was hitting `lint-staged` command not found. 
I think the pre-commit linting was misconfigured based on https://github.com/toplenboren/simple-git-hooks
> [Fix] Update CONTRIBUTING.md for pnpm. Use pnpm to run line-staged

- cli/internal/fs/package_deps_hash.go
Note: 
* this will cause a wave of cache misses on windows, as we move to normalized POSIX paths
* merge base is #888
> Normalize paths coming from ls tree

- cli/internal/context/context.go
- cli/internal/fs/package_deps_hash.go
- cli/internal/fs/package_deps_hash_test.go
- examples/basic/README.md
Fixes #886 
`GitHashForFiles` now takes absolute paths for all files. It was previously receiving a mix of absolute and relative paths. Also clean up execution of `git hash-objects` a little.
> Hash correct file paths for global dependencies

- packages/create-turbo/src/index.ts
In some country or district, install dependencies from npmjs.org could be very slow, China for example.
> feat: use user customized npm registry in create-turbo

- .vscode/launch.json
- cli/internal/client/client.go
- cli/internal/client/client_test.go
Read the tar artifact into memory so that we can compute the content-md5 
This read was already happening implicitly via the `retryableHttp` module.
> Explicitly read the artifact into memory before uploading to the remote cache api

- cli/internal/run/run.go
I will try to add a test for tomorrow, but I'm not a Go dev, so I might need some help at some point 🙂
> fix: #909 - turbo run exit code always 0

- cli/internal/run/run.go
- cli/internal/run/run_test.go
- cli/internal/util/parse_concurrency.go
- cli/internal/util/parse_concurrency_test.go
Closes #761
This is modeled after the way that `jest` [allows to set workers by providing a percent with `--maxWorkers=50%`](https://jestjs.io/docs/configuration#maxworkers-number--string).
I've updated Turbo's CLI parsing to accept `--concurrency=50%`. It also supports percentages over 100%, so  `--concurrency=500%` is valid. It uses `runtime.NumCPU()` to get the number of available logical processors, and calculates from there.
Setting the percentage to zero or less is an error. Setting percentage very low, to eg `1%` results in always at least `1` as the value for concurrency.
> Allow concurrency to be set with percentage values

- cli/internal/run/run_state.go
Close https://github.com/vercel/turborepo/issues/859
With this change, `>> FULL TURBO` will only ever show if more than 1 attempted task is run.
> Do not show >>> FULL TURBO on 0 attempt runs

- cli/internal/run/run_state.go
- cli/internal/ui/ui.go
Fix ansi reset after >>> FULL TURBO
> fix: Reset ansi after >>> FULL TURBO

- cli/Makefile
- cli/internal/run/run.go
- cli/internal/run/run_test.go
- cli/internal/scope/filter/filter.go
- cli/internal/scope/filter/filter_test.go
- cli/internal/scope/filter/matcher.go
- cli/internal/scope/filter/matcher_test.go
- cli/internal/scope/filter/parse_target_selector.go
- cli/internal/scope/filter/parse_target_selector_test.go
- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
> Implement `--filter` RFC

- cli/scripts/e2e/e2e.ts
- cli/scripts/monorepo.ts
`e2e` changes:
* Add `lint` tests. These are helpful because they don't have dependencies, so can illustrate future improvements
* Specify a dependency on `"^build"` for `test`. This required changing some matching to `.includes` rather than exact line matches, as now potentially-cached `build` tasks are mixed into the output, and they output in a non-deterministic order. We're still matching the same hits and misses though.
* Start exercising `--dry=json` a little for testing purposes.
> Work on e2e

- cli/internal/scope/filter/filter.go
- cli/internal/scope/filter/filter_test.go
When we're matching dependencies, make sure to check if the named package is the one that changed
> Include entry packages, not just dependencies when checking changed packages.

- cli/internal/run/run.go
- cli/internal/run/run_state.go
During refactoring of `context` it seems that `--profile` flag was no longer working. This turns on chrometracing if `--profile` has a value
> fix: Enable chrome tracing if `--profile` is specified

- cli/internal/util/backends.go
Fix https://github.com/vercel/turborepo/issues/962
In a follow up, we ideally should not need to make an `exec` call to start `yarn` which is written in node.js just to determine it's version. All we need to know is if it is greater than 2. We Also don't need to be parsing full semver. As soon as we know the first character is a >= 2 we know it is berry
> Only check for yarn berry if it is installed

- docs/package.json
- pnpm-lock.yaml
Since it's an alpha build, it should be exact version, otherwise managers do weird things
> fix(docs): use exact version

- cli/internal/core/scheduler.go
We used to have some tests that depended on running against all packages if none were specified. Those tests have been refactored, and now we no longer need that specific hook.
Fixes #958
> Drop behavior that was previously used in tests

- .github/workflows/ci-go.yml
- cli/cmd/turbo/main.go
- cli/internal/run/run.go
- cli/internal/ui/colors.go
- cli/internal/ui/ui.go
- docs/pages/docs/reference/command-line-reference.mdx
This change checks for --color / --no-color as command-line arguments as a mechanism for forcing color in non-TTY situations, or forcing --no-color for TTY. Additionally, this change hooks into the `FORCED_COLOR` environment variable that is used by the [`supports-color`](https://www.npmjs.com/package/supports-color) npm package which is used by a variety of packages in the node ecosystem.
The intention of this PR is to alleviate some of the concerns from Issue #897 by allowing users of turborepo to enable color output on CI runners such as Github Actions which support color output (as mentioned in the [fatih/color documentation](https://github.com/fatih/color/tree/master#github-actions)). When github actions and local builds are both running in color, then the cached output should be …
> feat(colors): add options for forcing color/no-color

- .github/workflows/ci-go.yml
- cli/internal/ui/colors.go
- docs/pages/docs/reference/command-line-reference.mdx
I had a typo in the environment variable name for the original commits.
> chore(force_color): use FORCE_COLOR instead of FORCED_COLOR

- docs/pages/docs/reference/command-line-reference.mdx
Updated the internal link to the Filtering packages page on the CLI usage page
> docs: update link to filtering page

- cli/internal/context/context.go
- cli/internal/context/context_test.go
This is similar to the work done for `file:...` dependencies in 32cebb1094bfb572fcdff01c0cb6d09f7538b418.
Check if file paths pointed to by `link:...` are within the monorepo.
If so, consider them internal dependencies, and otherwise consider them as external dependencies.
This can be useful because pnpm uses the `link:` protocol when using `pnpm install ./package-a/`.
> Add back support for `link:...` dependencies

- cli/internal/fs/package_json.go
- cli/internal/fs/package_json_test.go
- cli/internal/fs/testdata/turbo.json
- cli/internal/run/hash.go
- cli/internal/run/run.go
- cli/internal/run/run_test.go
* Avoid leaking the struct we parse to from JSON in the struct that we use in the remainder of the code
* Make the struct we use in the remainder of the code more semantically useful. 
* Parse out environment dependencies
* Split task and topological dependencies
* Apply default outputs during parsing, rather than during use
* Rename `Pipeline` -> `TaskDefinition` and `PipelineConfig` -> `Pipeline`.
Note that the merge base is #951, which we ought to merge first, and then update this to be against `main`.
> Refactor Pipeline parsing

- cli/internal/scope/scope.go
Fixes #1032 
We were using the raw `--since` flag value instead of the `since` parsed from `--filter=[<commit>]`
> Use correct `--since` in filters

- cli/internal/core/scheduler.go
- cli/internal/core/scheduler_test.go
- cli/internal/run/run.go
* Check when adding package-task dependencies that the package in question exists
* Don't crash if we somehow try to execute a task on a package that doesn't exist
* Record an error if any tasks errored, even if none of them were child exit code errors
> Handle unknown package in graph traversal

- cli/internal/run/run.go
Fixes #1002 
Instead of hanging during graph traversal, we instead print out the list of packages that form a cycle and exit with exit code `1`
> Handle cycles in package dependency graph

- cli/internal/process/manager_test.go
`go` scheduling doesn't actually guarantee the thing this was testing.
> Delete flaky and bad test

- examples/kitchen-sink/apps/blog/package.json
Remix 1.4 does appear to work in Yarn, NPM, or PNPM workspaces at the moment (see screenshot below). In the interim, this pins Remix to 1.0.6. In another PR, we can upgrade it 1.3.5 (which also works), but I have to head out and don't have time. This change at least will fix our test suite
> Fix remix example by pinning version

- cli/internal/config/config.go
- docs/pages/docs/reference/command-line-reference.mdx
Follow-up to #1052 per @jaredpalmer's [request](https://github.com/vercel/turborepo/pull/1052#issuecomment-1100316913) to reduce CLI args clutter.
> Support loading preflight option from env var TURBO_PREFLIGHT

- cli/internal/cache/cache_fs.go
- cli/internal/fs/copy_file.go
Previously we would fall back to reading the file, which inlined the contents of the linked-to file.
> Cache symlinks in filesystem cache

- cli/internal/cache/cache_http.go
* Symlink-from-tar handling is now in one place
* `storeFile` now returns 0 values in all error cases
* `name` -> `repoRelativePath` to be a little clearer for upcoming switch to `fs.AbsolutePath`
Not included is better sorting of broken symlinks. In pathological cases, symlinks pointing to symlinks can still fail to get properly recreated on windows. OSX and linux allow for creating the link target after the link itself.
> Unify symlink handling in http cache

- package.json
`lint-staged` will no longer fail
> fix: lint staged

- .vscode/launch.json
The `launch.json` config file had an errant flag.
This also reorders the launch configurations to make a bit more sense.
> Fix launch config

- docs/pages/docs/features/pipelines.mdx
Update 'Implicit Dependencies and Specific Package Task' example in pipelines.mdx with missing "backend#health-check" referenced in text.
> docs: Add missing "backend#health-check" in pipelines example

- .vscode/settings.json
We adopted `golangci-lint` to handle linting on CI, this configures VSCode to use that by default.
> Configure VSCode to use the same lint tool as CI.

- .vscode/settings.json
VS Code was complaining about this error where `autoFix` is `true` by default and doesn't need to be specified.
> Fix lint error in VS Code settings.

- cli/internal/cache/cache_http.go
- cli/internal/client/client.go
Replace direct config dependency in http cache with an interface that can be mocked in tests.
Also deletes an unused argument in `ApiClient.FetchArtifact`.
> Use interface for API Client in HTTP Cache

- cli/go.mod
- cli/go.sum
- cli/internal/globby/globby.go
- cli/internal/globby/globby_test.go
- cli/internal/run/run.go
This PR does three things:
- Adopt `afero` inside of the `globby` module. This is a nice isolated test of `afero`, which we can expand into the rest of the codebase if we remain happy with it.
- Writes a bunch of tests of the `globby` implementation in order to attempt to specify the behavior prior to rewriting the implementation of `GlobFiles`.
- Removes the implicit dependency on `os.Getwd` in one call to `GlobFiles`.
I've added a review for questions.
> Adopt afero, create tests for globby.

- cli/internal/context/context.go
- cli/internal/globby/globby.go
- cli/internal/globby/globby_test.go
- cli/internal/run/run.go
This PR is a fast-follow to #1108 to plumb through the error cases. This work is intentionally split to reduce the scope for each change (1. change implementation, 2. change interface).
This results in user-facing changes if they have globs or patterns that push them outside of their root directory.
>  Plumb through errors in globbing. 

- cli/internal/packagemanager/npm.go
- cli/internal/packagemanager/pnpm.go
- cli/internal/scope/filter/parse_target_selector.go
- cli/npm/turbo-install/README.md
- docs/components/features.js
- docs/pages/blog/turbo-0-4-0.mdx
- docs/pages/blog/turbo-1-1-0.mdx
- docs/pages/blog/turbo-1-2-0.mdx
- docs/pages/blog/you-might-not-need-typescript-project-references.mdx
- docs/pages/docs/acknowledgements.mdx
- docs/pages/docs/core-concepts/pipelines.mdx
- docs/pages/docs/getting-started.mdx
- docs/pages/docs/guides/migrate-from-lerna.mdx
- docs/pages/docs/guides/monorepo-tools.mdx
- docs/pages/docs/reference/command-line-reference.mdx
- docs/pages/docs/reference/configuration.mdx
- docs/schema.d.ts
- examples/design-system/README.md
- examples/with-changesets/README.md
- examples/with-pnpm/README.md
- packages/create-turbo/templates/npm/README.md
- packages/create-turbo/templates/pnpm/README.md
as titled. the npm and pnpm brands prefer to use all lowercase. yarn seems to alternate between Yarn and yarn so I didn't modify that one
> docs: fix capitalization of npm and pnpm

- docs/pages/docs/ci/circleci.mdx
- docs/pages/docs/ci/github-actions.mdx
- docs/pages/docs/ci/gitlabci.mdx
- docs/pages/docs/ci/travisci.mdx
Adds `npm` `yarn` and `pnpm` tabs for all of our CI guides
> docs: add package manager tabs to CI

- cli/internal/context/context.go
These directories aren't excluded by default in any package manager. We should aim to match the behavior of the upstream package managers even if this may result in a quality of life improvement for some users.
This is an incomplete fix, but I believe that addressing a compatibility issue is more-important than trying to deliver the complete fix.
Closes #1143
> Remove test directories from workspace ignores.

- cli/internal/cache/cache.go
- cli/internal/cache/cache_http.go
- cli/internal/cache/cache_http_test.go
- cli/internal/cache/cache_test.go
- cli/internal/client/client.go
- cli/internal/client/client_test.go
- cli/internal/run/run.go
- cli/internal/util/status.go
If the Remote Caching server returns a `403` indicating that caching is disabled, stop trying to use the HTTP cache.
> Handle 403s

- docs/pages/docs/ci/gitlabci.mdx
- docs/pages/docs/ci/travisci.mdx
lets make sure our ci scripts all pin the user to pnpm v6
> docs: pin pnpm versions in ci to 6

- cli/internal/context/context.go
Fixes #1162 
Includes resolved `Pipeline` configuration, rather than the file contents directly.
> Include pipeline definition in global hash

- cli/internal/cache/cache_signature_authentication.go
- cli/internal/fs/package_deps_hash.go
- cli/internal/run/run.go
Go has numerous linters which are dependent upon `x/tools/go/ssa` which has not yet been updated to support generics (https://github.com/golang/go/issues/48525).
This PR addresses all of the lint detected in our codebase via linters which depend on SSA analysis.
```
internal/cache/cache_signature_authentication.go:102:6: type `readCloser` is unused (unused)
internal/cache/cache_signature_authentication.go:78:45: func `(*ArtifactSignatureAuthentication).streamValidator` is unused (unused)
internal/fs/package_deps_hash.go:169:2: S1011: should replace loop with `cmd.Args = append(cmd.Args, patterns...)` (gosimple)
internal/fs/package_deps_hash.go:225:8: S1009: should omit nil check; len() for nil slices is defined as zero (gosimple)
internal/run/run.go:310:5: S1038: should use fmt.Fprintf …
```
> Address all SSA-dependent lint.

- cli/internal/run/run.go
You should be allowed to traverse up to the repository root for package outputs.
> fix: allow cache outputs external, but relative to packages

- cli/internal/run/run.go
- cli/internal/scm/git.go
- cli/internal/scm/scm.go
- cli/internal/scm/stub.go
- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
* Delete a lot of unused git integration code
* Don't crash in git integration code, return an error instead (remove `log.Fatalf` instances)
* Provide a more helpful error message when the user supplies a non-existent commit
Fixes #1157
> git integration cleanup

- cli/internal/fs/package_deps_hash.go
- cli/internal/fs/path.go
- cli/internal/run/hash.go
- cli/internal/run/hash_test.go
- cli/internal/run/run.go
We were setting the wrong (relative) path for `git ls-files`. Use `fs.AbsolutePath` to ensure that we have the right thing, and plumb it through from `Config`.
Fixes #1085 #1198
> Send proper paths to git cmd for file hashing

- cli/internal/fs/package_deps_hash.go
- cli/scripts/e2e/e2e.ts
- cli/scripts/monorepo.ts
When hashing files for `inputs` calculations, we were also including any uncommitted changes. So, in the event that an irrelevant file had changes, it would cause a cache miss. Apply the filtering properly, and add an `e2e` test.
Fixes #1085
> Apply inputs filter to uncommitted changes

- cli/internal/run/run.go
Related to #937 and #1135
When executing a dry run, don't short-circuit on tasks with a non-existent command. Instead, set the command to `<NONEXISTENT>` and include it in the display.
> Don't filter non-existent tasks in dry run

- docs/pages/docs/core-concepts/scopes.mdx
Current link shows a "Page Not Found". I fixed that by linking to https://microsoft.github.io/lage/docs/Guide/scopes#scoped-builds-with-all-its-dependents
> docs: fix link to Scoped builds from Microsoft Lage

- cli/internal/nodes/packagetask.go
- cli/internal/run/hash.go
- cli/internal/run/run.go
- cli/internal/taskhash/taskhash.go
- cli/internal/taskhash/taskhash_test.go
* Move `packageTask` from `run` to `nodes.PackageTask`. If we eventually have other kinds of nodes, they can perhaps be colocated
* Move `run/hash.go` to `taskhash/taskhash.go` with associated test
> chore: Extract a couple packages

- examples/design-system/README.md
This will fix a typo in the [docs of design-system](https://github.com/vercel/turborepo/blob/c8da722cf920b455e857501978adf0d0a6023547/examples/design-system/README.md?plain=1#L87) example.
> Fix a typo in design-system example README.md

- .github/workflows/ci-go.yml
We can revert back to `pnpm/action-setup` when https://github.com/pnpm/action-setup/issues/44 is fixed.
> Route around pnpm action

- cli/internal/context/context.go
- cli/internal/fs/path.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
- cli/internal/run/run_test.go
- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
Cleans up our `RunOptions` in advance of porting over to `cobra`. Attempts to have the zero value be the default in as many cases as possible, which means that some booleans needed to be flipped to be expressed internally as default: false. The external-facing arguments are unchanged.
Going commit-by-commit is probably the best way to go through this one.
There's definitely some refactoring still to be done around `run` and `runOpts`, but this felt like a big enough change to stand on its own.
> Options cleanup

- cli/internal/packagemanager/berry.go
- cli/internal/packagemanager/yarn.go
Fixes https://github.com/vercel/turborepo/issues/1311
See note https://github.com/Masterminds/semver#checking-version-constraints:
> If you want to have it include pre-releases a simple solution is to include -0 in your range.
Tested with both prerelease, and major releases.
> fix(yarn): include prerelease versions in constraints

- cli/internal/cache/cache.go
- cli/internal/cache/cache_fs.go
- cli/internal/cache/cache_noop.go
- cli/internal/cache/cache_test.go
- cli/internal/run/run.go
This makes it possible for a repository whose CI configuration is `--remote-only` to work when receiving pull-requests from forked repositories that do not have access to secrets configuration in CI.
Example failures:
- https://github.com/vercel/turborepo/pull/1302: [Error](https://github.com/vercel/turborepo/runs/6681959655?check_suite_focus=true#step:8:56)
- https://github.com/vercel/vercel/pull/7575: [Error](https://github.com/vercel/vercel/runs/6599439965?check_suite_focus=true#step:10:12)
One example workaround:
https://github.com/vercel/vercel/pull/7873
However, since this does not prevent the build from running to completion, I do not believe that it should be a hard error. While in the process of addressing this I also discovered that, since the `httpCache` can remove itself, …
> Create noopCache to ensure that users always have a valid cache object.

- cli/internal/cache/cache.go
- cli/internal/fs/path.go
- cli/internal/run/run.go
- cli/internal/run/run_test.go
- cli/internal/runcache/runcache.go
- cli/internal/scope/scope.go
Removes some long-deprecated flags:
- `serial`
- `includeDependencies`
- `cacheFolder`
> Port run to cobra

- cli/internal/config/config.go
- cli/internal/prune/prune.go
Ports `prune` over to `cobra`. There is still a fair amount to be done to refactor prune, but this is a start that allows easier expansion of commandline configuration.
Fixes #1258
Adds the feature requested in #1159 (flag for outputs of `prune`)
Note that this PR stacks on top of porting over `run`
> Port prune command to cobra

- cli/internal/context/context.go
The first candidate is `VERCEL_ANALYTICS_ID`
> Add default env vars

- cli/internal/fs/path_test.go
- cli/internal/run/run.go
- cli/internal/run/run_test.go
- cli/internal/runcache/runcache.go
Addressing some of @nathanhammond's review comments from #1298 
I added a test for `AbsolutePathVar` so that we can have a way to discuss the intended behavior.
> Follow up to porting run to cobra

- docs/pages/docs/getting-started.mdx
The Getting Started guide contains broken commands. Without `run` the commands listed there fail to execute.
> Add missing command to package.json scripts

- docs/pages/docs/ci/circleci.mdx
- docs/pages/docs/ci/github-actions.mdx
- docs/pages/docs/ci/gitlabci.mdx
- docs/pages/docs/ci/travisci.mdx
Updates docs to reflect findings from https://github.com/vercel/turborepo/issues/1343
> This appears to be an issue with how CircleCI environment variables work. 
Because we're setting the environment variables [on the project](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project), you actually don't need to specify them in the workflow. Adding these in the workflow is overriding the variables set on the project [because they have a higher precedence](https://circleci.com/docs/2.0/env-vars/#order-of-precedence), so the environment variables literally end up being the strings $TURBO_TEAM and $TURBO_TOKEN, and your remote cache requests are failing to authenticate.
> fix(docs): update circleci remote cache docs

- cli/internal/fs/path.go
- cli/internal/runcache/runcache.go
Log files are hard-linked into the cache, so when re-running a task we need to ensure we don't pollute a previous run. 
This changes our logging to stream to a temp file, which we then rename to the actual log file. This serves to break the hard link. 
Note that:
* renames will succeed even if the target already exists, as long as the target isn't a directory. All of our targets are log files
* renames can fail if the rename is across filesystem boundaries. Our renames are within the same directory.
Fixes #1323
> Log to temp files then rename

- cli/internal/fs/path.go
- cli/internal/runcache/runcache.go
Reverts vercel/turborepo#1351
We don't need this PR, as #1354 supersedes it.
> Revert "Log to temp files then rename"

- cli/internal/run/run.go
- cli/internal/run/run_test.go
- cli/internal/runcache/runcache.go
- cli/internal/util/parse_concurrency.go
- cli/internal/util/parse_concurrency_test.go
Fixes #1336 
Implemented a custom value to accept either a number or percentage.
> Fix parsing concurrency as a number or percent

- .github/workflows/golangci-lint.yml
@gsoltis had a good minimally-invasive suggestion which gets our linters back working: https://github.com/vercel/turborepo/pull/1168#issuecomment-1150243992
This PR implements that suggestion. We still build and publish with 1.18, the only real difference is we run lint against 1.17; which will happily break us if we introduce 1.18-specific features.
> Run lint against Go 1.17 to constrain introduction of 1.18 features.

- cli/internal/config/config_file_test.go
- cli/internal/fs/path.go
Backup existing config and restore it at the end of the test.
> Handle running the tests by a logged-in user

- cli/.golangci.yml
Since we're using Go `1.17` when running `golangci-lint`, mark the linter mode as `1.17` until https://github.com/golangci/golangci-lint/issues/2649 is resolved.
> Use Go 1.17 mode for lint

- cli/internal/run/run.go
Fixes #1355 
Prefix passthrough args with `--` so that they get routed through the package manager
> We lost -- prefixing passthrough args

- docs/pages/docs/getting-started.mdx
Update the tabs to use matching keys to keep in sync.
> docs: Fix yarn tab storage key name

- cli/internal/fs/package_deps_hash.go
Also ensure mutex is captured by reference, rather than by value.
Fixes #1433
> Ensure maps are accessed with a lock

- docs/package.json
This is kind of a weird fix. I believe it works by resetting the execution root for the `compileProgram` execution; not based upon any actual configuration in our TSConfig file.
The previous state would succeed or fail based upon the `node_modules` directory structure, this changes the execution location to be from a known-good location.
> Update schema generation script invocation.

- scripts/run-example.sh
This catches the error we previously saw where examples would "run" but due to incorrect argument passing were not actually running any examples.
> Ensure we fail if no examples are run

- cli/.golangci.yml
- cli/internal/chrometracing/chrometracing.go
- cli/internal/chrometracing/chrometracing_close.go
- cli/internal/run/run_state.go
- cli/scripts/e2e/e2e.ts
- cli/scripts/monorepo.ts
- Vendor `chrometracing` (mostly, it still references a sub-package that is just a `struct` definition)
- Implement `Close` function for `chrometracing`: it overwrites the trailing `,\n` with `]\n` and closes the file.
- Add an `e2e` test to make sure `JSON.parse` succeeds on the profiling output.
- Exempt `chrometracing` from linting
> Vendor chrometracing, add Close method

- cli/internal/fs/package_deps_hash.go
- cli/internal/fs/package_deps_hash_test.go
We were passing the repo root and paths rooted at the package root to `gitHashObject`. Fixed to pass the package path. Also created array of paths to hash directly, rather than creating an intermediate array and converting.
Added a test for the hashing behavior.
> Fix hashing uncommitted changes

- cli/Makefile
CGO is required to deal with DNS resolution on Darwin (see #941), we need to do this for both `arm` and `amd64`.
> Cross-compile amd64.

- cli/internal/fs/copy_file_test.go
Our file copying doesn't have a detailed test for all of the behaviors that we care about. This adds it to constrain future behavior.
> Add test to confirm that file copying works as expected.

- cli/internal/cache/cache.go
- cli/internal/cache/cache_fs.go
- cli/internal/cache/cache_fs_test.go
- cli/internal/cache/cache_http.go
- cli/internal/cache/cache_test.go
- cli/internal/config/config.go
- cli/internal/context/context.go
- cli/internal/login/link.go
- cli/internal/login/login.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
First commit: 
* moves `ApiClient` out of `config.Config`. Replaces it with a helper to construct it on demand. Currently all of the values for constructing one still come from a `config.Config` instance. No behavioral change
Second commit:
* Move `TurboJSON` out of `config.Config`. Instead, read it on demand in `run` and `prune`
* Behavioral change: running `turbo` in a directory w/o a `turbo.json` will no longer immediately error, so we can display usage / help information. `package.json` is, however, still required as of this change.
Notes on future work: `prune` requires `TurboJSON` because `context.WithGraph` requires it. But `WithGraph` only needs it to construct the global hash value, which isn't needed for constructing the package-dependency graph. If migrate `calculateGlobalHash` …
> Move some fields out of Config

- examples/design-system/.gitignore
Very minor: there are two `.turbo` declarations - I removed one.
> chore: remove redundant `.turbo`

- examples/kitchen-sink/apps/blog/package.json
When trying to run the app using `yarn start` it will fail with the following error:
```
turbo-kitchensink/apps/blog is 📦 v0.0.0 via ⬢ v16.13.1
➜ yarn start
yarn run v1.22.17
$ remix-serve build
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module '/Users/eli/projects/temp/turbo-kitchensink/apps/blog/build'
```
The issue being the `build` directory isn't at the top level as the script expects.
Changing the script to run `remix-serve api/build` resolves the issue.
> Fix `yarn start` not working

- examples/basic/packages/tsconfig/nextjs.json
- examples/basic/packages/tsconfig/react-library.json
- examples/design-system/packages/acme-tsconfig/node16.json
- examples/design-system/packages/acme-tsconfig/react-library.json
- examples/kitchen-sink/apps/blog/tsconfig.json
- examples/kitchen-sink/packages/tsconfig/nextjs.json
- examples/kitchen-sink/packages/tsconfig/react-library.json
- examples/kitchen-sink/packages/tsconfig/vite.json
- examples/with-changesets/packages/acme-tsconfig/nextjs.json
- examples/with-changesets/packages/acme-tsconfig/node14.json
- examples/with-changesets/packages/acme-tsconfig/react-library.json
- examples/with-pnpm/packages/tsconfig/nextjs.json
- examples/with-pnpm/packages/tsconfig/react-library.json
- packages/create-turbo/templates/_shared_ts/packages/tsconfig/react-library.json
Fixes https://github.com/vercel/turborepo/issues/1446
This also:
- Alphabetically sorts all keys in TS config compiler options
- Removes redundant keys (keys with the same value specified both in the base config and an inheriting child config)
> chore(examples): update tsconfig declaration val

- cli/internal/context/context.go
Fixes #1333 
Previously, our package dependency graph used whatever name the root `package.json` had. This PR changes it to always use our internal root-package token (`//`). This lets us reference the root package later in the process and properly work out dependency- / dependent-relationships that include the root package.
Unfortunately, we don't yet have the infrastructure for unit testing this part of the code. We'll likely need to break apart `context.go` a bit more before it's really tractable. Verified experimentally using the repo in the linked issue.
> Label root package in dependency graph

- examples/with-tailwind/packages/ui/package.json
The wrong npm package was installed in the tailwind example `tailwind` => `tailwindcss`.
I also added exports field for styles.css as it was not found from within the `_app.tsx` in next applications, but I am not sure if this is required.
```
web:dev: error - ./pages/_app.tsx:3:0
web:dev: Module not found: Package path ./styles.css is not exported from package
~/turborepo/examples/with-tailwind/node_modules/ui (see exports field in ~/turborepo/examples/with-tailwind/node_modules/ui/package.json)
```
> Fix tailwind example

- examples/with-nextjs/README.md
Add a `with-nextjs` directory with pointers to other examples that contain `Next.js` applications.
> feat(examples): add nextjs

- cli/internal/cache/cache_http.go
- docs/pages/blog/turbo-1-2-0.mdx
- docs/pages/docs/core-concepts/remote-caching.mdx
**summary**
While reading the TurboRepo docs I found a typo on the [Remote Caching](https://turborepo.org/docs/core-concepts/remote-caching) page. 
Searched for the typo and found it in a few more places.
> Typo: verifcation --> verification

- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
Previously we didn't properly check for package prefixes being at actual file-addressing boundaries. This PR resolves the issue.
Fixes #1528
Closes #1533
> Filter in package

- packages/create-turbo/templates/_shared_ts/apps/docs/package.json
- packages/create-turbo/templates/_shared_ts/apps/web/package.json
- packages/create-turbo/templates/_shared_ts/packages/eslint-config-custom/package.json
- packages/create-turbo/templates/pnpm/apps/docs/package.json
- packages/create-turbo/templates/pnpm/apps/web/package.json
Fix error where `npx create-turbo@latest` with `pnpm` throws an error on completion due to incorrect peer dependencies. 
Below stack trace is visible when reinstalling a repo created with `create-turbo@latest` and `pnpm` (after removing the `pnpm-lock.yaml` from the original install)
```
04:46 PM | ~/Desktop/turbo_tests/my-turborepo ()
0 > pnpm install
Scope: all 6 workspace projects
Already up-to-date
Progress: resolved 156, reused 133, downloaded 0, added 0, done
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
apps/docs
└─┬ next
└─┬ styled-jsx
├── ✕ missing peer @babel/core@"*"
└─┬ @babel/plugin-syntax-jsx
└── ✕ missing peer @babel/core@^7.0.0-0
Peer dependencies that should be installed:
@babel/core@">=7.0.0 <8.0.0"
apps/web
└─┬ next
└─┬ styled-jsx
├── ✕ missing peer @babel/core@"*" …
```
> fix(create-turbo): pnpm peer deps error

- cli/internal/core/scheduler.go
- cli/internal/core/scheduler_test.go
Fixes a bug introduced by https://github.com/vercel/turborepo/pull/1485 which causes turbo to exit when no dependent tasks are found to run. 
This breaks expected behavior (turbo should skip packages that don't contain the specified task)
> fix(cli): don’t exit when no tasks are found

- packages/turbo-ignore/index.js
When using `npx turbo-ignore`, the `HEAD^` used to fetch the previous commit will fail if there is _only one_ commit. 
This is a common case (especially when importing a project) and should be handled gracefully (the build should not be skipped when the diff encounters an unknown error)
Currently, this fails on Vercel with the following error when running on a repository with only a single commit:
```
Running "npx turbo-ignore"
--
15:00:41.493 | npx: installed 1 in 1.272s
15:00:41.515 | ≫ Using Turborepo to determine if this project is affected by the commit...
15:00:41.515 | ≫ Inferred `docs` as scope from "./package.json"
15:00:41.515 | ≫ Analyzing results of `npx turbo run build --filter=docs...[HEAD^] --dry=json`...
15:00:46.444 | exec error: Error: Command failed: npx turbo run build …
```
> fix(turbo-ignore): build on error

- cli/Makefile
- scripts/await-publish.js
Last automated release attempt resulted in a partial lockfile update:
https://github.com/vercel/turborepo/commit/c0861594540f6004adad524cf82870578ae00b46
This inserts a delay mechanism to make sure we don't proceed before ready.
> Await publish before attempting lockfile update.

- packages/eslint-config-turbo/LICENSE
- packages/eslint-config-turbo/README.md
- packages/eslint-config-turbo/index.js
- packages/eslint-config-turbo/package.json
- packages/eslint-plugin-turbo/lib/configs/recommended.ts
- packages/eslint-plugin-turbo/package.json
- pnpm-lock.yaml
Setting up lint for turbo is now as easy as adding `turbo` to your eslint extends array:
```
{
"extends": ["turbo"]
}
```
> feat(packages): eslint-config-turbo

- docs/components/clients/Marquee.tsx
This reverts commit 2e2f54aa59c7f1ea426cc7091972b63917dd024e.
The static height was introduced to fix a layout shift that doesn't
reproduce anymore. The static height clips logos that are taller than
then 40px. Shows up even more on larger screens where images are scaled
larger. This static height isn't needed anymore.
> Revert "hotfix: set height on marquee to avoid layout shift"

- .github/workflows/ci-go.yml
An action I was using to debug CI jobs in #1632 accidentally got merged
> fix: remove debug action from CI

- cli/Makefile
Defensive behavior caught a build issue, but not where I expected it.
> Make the defensive behavior correct.

- .github/workflows/ci-go.yml
- cli/Makefile
- cli/scripts/e2e/e2e.ts
- cli/scripts/monorepo.ts
I don't actually know if this will work, but I was trying to make the system itself responsible for maintaining the executable paths so that we didn't need to account for it in our e2e scripts.
> Attempt at an alternative corepack implementation.

- packages/create-turbo/templates/_shared_ts/apps/docs/package.json
- packages/create-turbo/templates/_shared_ts/apps/web/package.json
- packages/create-turbo/templates/_shared_ts/packages/ui/package.json
- packages/create-turbo/templates/pnpm/apps/docs/package.json
- packages/create-turbo/templates/pnpm/apps/web/package.json
- packages/create-turbo/templates/pnpm/packages/ui/package.json
This updates `create-turbo` package to use React 18 instead of React 17.
note: 2 snapshot tests fail but are unrelated to the changes made and not something I'm familiar enough to test presently. Tested locally and the examples apps run as expected without issue.
> update: create-turbo templates to use react v18

- examples/with-nextjs/README.md
Add a link to with-nextjs starter to Prisma starter.
> docs: Update with-nextjs readme to add prisma starter link

- .github/workflows/large-monorepo.yml
- benchmark/package.json
- pnpm-lock.yaml
Baby steps to getting our benchmark up and running. 
Removed cron trigger, will only trigger manually, and only run on ubuntu. Once we can verify that's all working, we can add more triggers / platforms.
> Flip benchmark to manual, only run on ubuntu, add protoc setup

- cli/internal/packagemanager/berry.go
- cli/internal/packagemanager/packagemanager.go
- cli/internal/packagemanager/packagemanager_test.go
- cli/internal/packagemanager/yarn.go
- cli/internal/prune/prune.go
- cli/scripts/e2e/e2e.ts
Before I add support for pnpm in the prune command I wanted to add some more tests and take a quick pass at deduping some code.
- Add e2e test for `--docker` flag
- Move the check for if a package manager supports the prune command into the PM abstraction
- Dedupe the `--docker` vs vanilla codepaths
Unsure of the signature of `CanPrune` as it could be simplified to just return an error if the package manager doesn't support, but that feels off to me. Would appreciate any thoughts on this.
> refactor: Prune prefactor

- cli/go.mod
- cli/go.sum
- cli/internal/cache/cache.go
- cli/internal/run/run.go
- cli/internal/spinner/spinner.go
As a stopgap before we move cache uploads to the daemon, I added some terminal output if uploading is blocking process completion. 
While obviously not ideal that users are just waiting for cache population, I think it's at least better that they know that that is what is happening, rather than the process appearing to hang.
> output to terminal when we are just waiting for cache uploads

- .github/workflows/ci-go.yml
- .github/workflows/ci-js.yml
- packages/create-turbo/__tests__/cli.test.ts
- Make existing tests pass
- Add GH action to run tests in CI
Set up a new Github Action that builds the turbo CLI (since that is
required for the create-turbo tests) and runs the JS tests for that
package.
Notable things:
- Installs yarn and disables corepack as part of the test suite. This
is the pristine state we want for the tests that exist today. For
future tests cases that have a different setup, we may need to
modify this more.
- Disables Windows tests. This yarn setup on Windows does not seem to
work, but this gets us one step forward.
> create-turbo: improve test cases and make them pass

- cli/internal/context/context.go
- cli/internal/hashing/package_deps_hash.go
- cli/internal/hashing/package_deps_hash_test.go
- cli/internal/taskhash/taskhash.go
Passing `"inputs"` directly to `git ls-files` uses `git`'s globbing, which is not the same as the rest of `turbo`. Do the globbing ourselves instead, and use `git hash-object`.
> Use git hash-object instead of git ls-files for inputs hashing

- .github/workflows/ci-js.yml
- packages/create-turbo/__tests__/cli.test.ts
Add --runInBand to speed up CI. npm installation tests are timing out
in CI, possibly becuase of lack of hardware resources. runInBand
can improve performance by running tests in serial. There may also be an
issue where tests are using the same directory to write node_modules and
when running in parallel are erroring out. This doesn't reproduce
locally, so it's possible that Jest only parallelizes in CI or non-TTY
environments?
> create-turbo: Add tests to assert package installation works

- cli/internal/spinner/spinner.go
In the previous change, I accidentally forgot to wait for a timeout before displaying the message when we're not using a TTY. This unifies the behavior between TTY and no TTY.
> Wait for initial delay even with no TTY

- packages/create-turbo/.gitignore
- packages/create-turbo/__tests__/cli.test.ts
- packages/create-turbo/src/constants.ts
- packages/create-turbo/src/getPackageManagerVersion.ts
- packages/create-turbo/src/index.ts
- packages/create-turbo/src/types.ts
This would be somewhat cleaned up in a `corepack` world.
> Add yarn/berry switch in create-turbo tests.

- .github/workflows/large-monorepo.yml
40 minutes is sufficient for ubuntu, but not macOS apparently.
> MacOS times out on large monorepo

- examples/design-system/apps/docs/stories/button.stories.mdx
Removed "/blocks" from "@storybook/addon-docs/blocks" since it's deprecated, one should only use "@storybook/addon-docs".
> Removed blocks from storybook import

- cli/internal/hashing/package_deps_hash.go
- cli/internal/run/global_hash.go
Falls back to manual hashing when git is not available for global dependencies
Fixes https://github.com/vercel/turborepo/issues/1257 (follow up to https://github.com/vercel/turborepo/pull/1239/files)
> fix(cli): fallback to manual hashing for global

- cli/internal/fs/testdata/package.json
- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
I'm starting to work on updating where `env` vars are read from. As I started writing a test case,, I noticed that our unit test is against a function that we don't actually use, so I've updated the test case here.
> Turbo Config refactor

- cli/internal/chrometracing/chrometracing.go
- cli/internal/doublestar/glob.go
- cli/internal/doublestar/globwalk.go
- cli/internal/doublestar/match.go
- cli/internal/doublestar/utils.go
- cli/internal/doublestar/validate.go
- cli/internal/util/closer.go
- cli/internal/util/filter/filter.go
We have a ton of lint errors not getting caught in CI right now, because it only runs lint on new code every PR. This at least runs the lint and fixes things that can be fixed automatically.
```
golangci-lint run --fix
```
> Autofix fixable lint issues

- .github/workflows/release.yml
- CONTRIBUTING.md
- cli/Makefile
Pass at clarifying documentation based upon questions in #1562.
> Update docs for release to clarify questions.

- docs/pages/docs/getting-started.mdx
- docs/pages/docs/guides/migrate-from-lerna.mdx
- docs/pages/docs/upgrading-to-v1.mdx
Shorthand command flags are for expert users, we want to teach users what is happening.
> Remove command flag shorthands from docs.

- cli/internal/context/context.go
- cli/internal/fs/package_json.go
- cli/internal/fs/path.go
- cli/internal/fs/turbo_json_test.go
- cli/internal/globby/globby.go
- cli/internal/hashing/package_deps_hash.go
- cli/internal/nodes/packagetask.go
- cli/internal/packagemanager/berry.go
- cli/internal/packagemanager/npm.go
- cli/internal/packagemanager/yarn.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
- cli/internal/runcache/runcache.go
- cli/internal/scope/filter/filter.go
- cli/internal/scope/filter/filter_test.go
- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
- cli/internal/taskhash/taskhash.go
- cli/internal/taskhash/taskhash_test.go
- cli/internal/turbopath/anchored_system_path.go
Updates `fs.ReadPackageJSON` to take an `AbsolutePath` so that we respect `--cwd`
Pulls the thread on updating `PackageJSON.Dir` and `PackageJSON.PackageJSONPath` to have the correct `turbopath` types.
cc @nathanhammond note in particular changes to `taskhash_test.go`
> Change fs.ReadPackageJSON to operate on AbsolutePath instances

- examples/basic/turbo.json
- examples/design-system/turbo.json
- examples/kitchen-sink/turbo.json
- examples/with-changesets/turbo.json
- examples/with-create-react-app/turbo.json
- examples/with-docker/turbo.json
- examples/with-pnpm/turbo.json
- examples/with-react-native-web/turbo.json
- examples/with-svelte/turbo.json
- examples/with-tailwind/turbo.json
- examples/with-vite/turbo.json
While working with the examples I noticed only some of them specify the incredibly useful `turbo.json` schema dialect (`"$schema": "https://turborepo.org/schema.json"`). This PR adds it to all of them :)
> Add schema dialect to example turbo.json files

- packages/eslint-plugin-turbo/lib/rules/no-undeclared-env-vars.ts
Tried to click on the linked doc in vscode and ended up with a 404. File extension was needed.
> fix: rule doc link

- .gitignore
- .npmrc
- cli/Makefile
Generate the `.npmrc` file before publishing, but don't check it into the repo
> Generate .npmrc just-in-time

- .github/workflows/ci-js.yml
- packages/create-turbo/jest.config.js
- packages/create-turbo/package.json
- packages/create-turbo/tsconfig.json
- packages/create-turbo/tsup.config.ts
- packages/eslint-plugin-turbo/jest.config.js
- packages/eslint-plugin-turbo/package.json
- packages/eslint-plugin-turbo/tsconfig.json
- packages/eslint-plugin-turbo/tsup.config.ts
- packages/tsconfig/base.json
- packages/tsconfig/library.json
- packages/tsconfig/package.json
- packages/turbo-codemod/jest.config.js
- packages/turbo-codemod/package.json
- packages/turbo-codemod/tsconfig.json
- packages/turbo-codemod/tsup.config.ts
- packages/turbo-ignore/jest.config.js
- packages/turbo-ignore/package.json
- packages/turbo-ignore/tsconfig.json
- packages/turbo-ignore/tsup.config.ts
- packages/turbo-utils/jest.config.js
- packages/turbo-utils/package.json
- packages/turbo-utils/tsconfig.json
- pnpm-lock.yaml
- turbo.json
This PR includes some packages maintenance: 
1. Abstract common tsconfigs to a shared package
2. Unify our tsup handling (use config)
3. Setup check type scripts
4. Setup lint and type check in CI
> chore(packages): typecheck and abstract ts config

- .github/workflows/ci-js.yml
Use remote cache for our JS CI jobs
> chore(ci): use remote cache for JS tests

- cli/cmd/turbo/main.go
- cli/internal/run/run.go
This PR:
* Removes the `--no-gc` flag
* Makes using the GC the default.
A parsing bug meant no one was using `--no-gc`, so use this opportunity to enable GC. Benchmarks show negligible difference in execution time.
> Remove --no-gc flag, always run with garbage collection

- cli/internal/fs/turbo_json.go
> Update to insert newlines.

- docs/pages/docs/getting-started/existing-monorepo.mdx
The document was moved from `/docs` to `/docs/getting-started` in [the previous commit](eaab599b9214f22d184aa37647e6e55f7f1d916c)
which made the relative path referred to by those links change.
Ref. https://turborepo.org/docs/getting-started/existing-monorepo#next-steps
> Fix broken links at "Next Steps" on "Add to Existing Monorepo"

- cli/internal/client/client.go
- cli/internal/login/link.go
- cli/internal/run/run.go
Fixes a bug where `turbo link` tried to verify that we were already linked, while `turbo run` needs to know if we're linked to use analytics.
> Split notion of logged in into user and linked-team

- packages/eslint-plugin-turbo/__tests__/lib/no-undeclared-env-vars.test.ts
- packages/eslint-plugin-turbo/lib/rules/no-undeclared-env-vars.ts
`eslint-plugin-turbo` will happily treat JavaScript variable names as environment variable names because it doesn't attempt to detect if the property being accessed is dynamic. This adds tests and a fix for that issue.
> fix(eslint): exclude variables in rule

- cli/internal/config/config.go
We don't have a `turbo version` command, so don't special case it in argument parsing.
Fixes #1839 
This is superceded by #1792
> Don't special case version command

- packages/turbo-ignore/src/index.ts
Check for the presence of `TURBO_FORCE`, and skip the ignore check if it exists. 
Because `turbo-ignore` now checks against `VERCEL_GIT_PREVIOUS_SHA` when deploying on Vercel, manually queued builds that skip the cache will _not_ deploy if there are no changes between the selected build and production. This is confusing, and generally not what the user wants when redeploying a build. 
NOTE: This isn't a Vercel specific env var (hence it's not gated by a `process.env.VERCEL` check) - any CI provider could set this when manually skipping the cache is selected (similar to how Vercel is handling this)
> feat(ignore): check for turbo force

- cli/internal/hashing/package_deps_hash.go
- cli/internal/hashing/package_deps_hash_test.go
We want to include each workspace's package.json as an input when
the user has configured a smaller set of inputs, because the package.json
defines the actual task turbo will execute for that workspace (via scripts).
If that task definition changes, the cache is invalid.
We only apply this inclusion when inputs are defined, because if inputs
are not defined, all git-tracked files are included in the hash,
which will also include the package.json file.
> Always include package.json in hash

- cli/internal/graphvisualizer/graphvisualizer.go
`dot --help` specifies that `-v` is for verbose mode, whereas `-V` is print version and exit. We want the latter, so change the flag to do that.
> Use correct flag for graphviz version

- cli/integration_tests/turbo_help.t
- cli/internal/cmd/root.go
- cli/internal/daemon/daemon.go
* Change the root command to match the expectation in the help test
* Change the daemon subcommand to match the expectation in the help test
* Fix the help test to expect a consistent description for the daemon subcommand
This is probably at the point where we want to wire it to CI, so that'll be coming shortly.
> Reconcile cram tests and help text

- .github/workflows/pr-go-lint.yml
`golangci-lint` expects to be able to find the previous revision, this guarantees it will be there.
> No shallow checkout for linting.

- cli/internal/fs/testdata/invalid-env-1/package.json
- cli/internal/fs/testdata/invalid-env-1/turbo.json
- cli/internal/fs/testdata/invalid-env-2/package.json
- cli/internal/fs/testdata/invalid-env-2/turbo.json
- cli/internal/fs/testdata/legacy-env/package.json
- cli/internal/fs/testdata/legacy-env/turbo.json
- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
Re-opening #1932 because CI refuses to pass there.
> Add ability to declare a env key in each pipeline task

- docs/package.json
- packages/eslint-plugin-turbo/lib/utils/findTurboConfig.ts
- packages/eslint-plugin-turbo/lib/utils/getEnvVarDependencies.ts
- packages/eslint-plugin-turbo/package.json
- packages/turbo-types/package.json
- packages/turbo-types/src/index.ts
- packages/turbo-types/src/scripts/codegen.js
- packages/turbo-types/src/types/config.ts
- packages/turbo-types/tsconfig.json
- pnpm-lock.yaml
We constantly need to share the types for the `turbo.json` config across packages (`eslint-plugin-turbo`, `turbo-utils`, `turbo-codemod`). 
This PR:
- Abstracts these types into their own private package. 
- Supports generating a json schema from the TS definitions for the config (currently, docs handles this which has always been a little strange. Keeping the types alongside the generation scrips provides a more clear separation of concerns)
This also won't be the last time we need to share types, so establishing a spot for this now should be useful moving forward.
> feat(types): add turbo types package

- packages/turbo-codemod/__tests__/migrate-env-var-dependencies.test.ts
- packages/turbo-codemod/package.json
- packages/turbo-codemod/src/git.ts
- packages/turbo-codemod/src/index.ts
- packages/turbo-codemod/src/logger.ts
- packages/turbo-codemod/src/transforms/add-package-manager.ts
- packages/turbo-codemod/src/transforms/create-turbo-config.ts
- packages/turbo-codemod/src/transforms/migrate-env-var-dependencies.ts
- packages/turbo-codemod/src/types.ts
- packages/turbo-types/src/types/config.ts
- pnpm-lock.yaml
Codemod to support migrating turbo.json "globalDependencies" and "dependOn" to the new "env" key.
> feat(codemod): migrate turbo.json dependsOn

- packages/turbo/node-platform.js
- packages/turbo/package.json
Our `package.json` and installed script don't need references to these packages anymore
> Drop no-longer-supported platform references

- .github/workflows/release.yml
- scripts/version.js
We don't do "latest" versions of "pre" releases, so infer the "canary" or "latest" identifier based on the kind of release we're doing.
> We can infer identifer, we don't need to specify it

- cli/internal/config/config_file.go
- cli/internal/config/config_file_test.go
- Ensure we are binding `--api` and `--team` to `viper`. 
- Ensure we don't mix a config-produced teamId with a flag-produced teamSlug
- Add a test for the desired behavior
Fixes #2040
> Wire up api and team flags with viper

- cli/internal/fs/turbo_json.go
Unsorted environment variables cause hashes to be unstable, meaning a large number of environment variables leads to essentially no cache hits.
Fixes #2029
> Ensure environment variables are sorted

- cli/internal/fs/testdata/correct/turbo.json
- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
- sort array fields on `turbo.json`
- add test to ensure we are sorting fields used for hashing
Fixes #2029
> Add test to ensure relevant fields are sorted

- cli/internal/cache/async_cache.go
- cli/internal/cache/cache.go
- cli/internal/cache/cache_fs.go
- cli/internal/cache/cache_fs_test.go
- cli/internal/cache/cache_http.go
- cli/internal/cache/cache_http_test.go
- cli/internal/cache/cache_noop.go
- cli/internal/cache/cache_test.go
- cli/internal/fs/path.go
- cli/internal/runcache/runcache.go
- cli/internal/turbopath/absolute_system_path.go
As prework for merging cache-to-tar, this ensures that we know what types of paths we're dealing with at (almost) every step in the cache process.
It also makes the first argument to `Put` (previously unused) and `Fetch` the anchor of the enumerated list of files being saved or restored.
> Add path types for cache.

- docs/theme.config.js
This PR fixes the url of `Edit This Page on GitHub` button
> Fix: Docs Edit This Page Button not working

- docs/pages/docs/reference/configuration.mdx
With the [1.5 release](https://turborepo.org/blog/turbo-1-5-0), a new `globalEnv` (and `env`) keys were introduced. However, the documentation seems to merge `globalDependencies` and `globalEnv` without explicitly describing what the later does.
The PR adds a new `globalEnv` section to clearly explain what this key does, and such remove environment variables terms in `globalDependencies`.
> chore(docs): sections for `globalDependencies` and `globalEnv`

- cli/internal/fs/copy_file.go
- cli/internal/fs/copy_file_test.go
- cli/internal/prune/prune.go
- cli/internal/turbopath/absolute_system_path.go
- cli/internal/turbopath/absolute_system_path_test.go
Fixes #1872
This PR ended up having larger scope than I originally intended. A few things that changed:
- `RecursiveCopyFile` now attempts to copy directories with the correct permissions
- Added `MkdirAllMode` which is similar to `MkdirAll` but it will ensure that the created directory has the permissions passed
- Change prune to use `MkdirAllMode` instead of `EnsureDir`
Currently we don't consider [`umask`](https://en.wikipedia.org/wiki/Umask) when creating files. When copying files that we get from users we should make sure that the permissions are kept, but when creating files for turbo itself, we should probably respect `umask`.
When copying user files and we want to make sure permissions remain the same, the standard solution is to `chmod` after creating a new dir/file. This would …
> fix(prune) respect dir permissions during prune

- cli/internal/prune/prune.go
Fix for issue that @mattpocock discovered.
This places the workspace definition file into the `json` directory and `full` directory instead of the `out` directory. This reflects the new documentation in #2013
> fix(prune): place workspace configuration file in json directory

- docs/next.config.js
This adds a rewrite to Vercel's [internal sitemap service](https://github.com/vercel/crawled-sitemap) (not OSS) which now scans turborepo.org
> seo: Add rewrite to turbo sitemap crawler

- .gitignore
- cli/Makefile
- shim/Cargo.lock
- shim/Cargo.toml
- shim/build.rs
- shim/src/main.rs
- shim/tests/mod.rs
Implements basic logic for finding local turbo and executing it. If any of this fails, we fall back on executing global turbo.
Using `assert_cmd` to test shim commands. Currently I only have commands verifying that we're using the correct binary.
> feature(shim): Basic shim setup

- cli/internal/cache/cache_http.go
- cli/internal/tarpatch/tar.go
- cli/internal/tarpatch/tar_unix.go
- cli/internal/tarpatch/tar_windows.go
This moves the `tar` portion that is relevant to CGO outside of the larger PR.
The entirety of this is extracted from:
https://github.com/moby/moby/blob/924edb948c2731df3b77697a8fcc85da3f6eef57/pkg/archive/archive.go
https://github.com/moby/moby/blob/924edb948c2731df3b77697a8fcc85da3f6eef57/pkg/archive/archive_windows.go
https://github.com/moby/moby/blob/924edb948c2731df3b77697a8fcc85da3f6eef57/pkg/archive/archive_unix.go
...with minor adjustments to use `turbopath`.
> Extract the patch for `tar`

- cli/internal/run/run.go
Some small changes that will make the diff in #2126 a bit easier to read / work through.
- `targetUi` -> `targetUI` because lint fails when i change lines with that variable
- `e` -> `ec` because I wanted to find all instances of where execContext.log* things are happening
> Change some variable names

- cli/internal/daemon/connector/connector.go
- cli/internal/run/run.go
- Use a url format that survives grpc parsing to produce a valid unix domain socket on all platforms
- Re-enable daemon on windows, now that we can properly address the socket
> Use unix:path to address unix socket

- docs/theme.config.js
Settiing canonical URLs in nextra head on all pages to prevent duplicates in Google Crawler
> seo: set canonical urls

- cli/internal/context/context.go
- cli/internal/lockfile/berry_lockfile.go
- cli/internal/lockfile/berry_lockfile_test.go
- cli/internal/lockfile/lockfile.go
- cli/internal/lockfile/pnpm_lockfile.go
- cli/internal/lockfile/pnpm_lockfile_test.go
- cli/internal/lockfile/yarn_lockfile.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
This PR lets turbo fallback to the "dumb" behavior if there's an issue with parsing or querying the lockfile. Operations such as prune will still hard error if there's a lockfile failure due to prune's reliance on accurate lockfile information.
Notes:
- Adds `context.Warnings` as an error type for indicating when the construction of `Context` produces a functional structure, but might be missing some features. It's expected that callers handle this error type and choose to proceed. The default Go error handling process will throw on any warnings.
-  `lockfile.ResolvePackage` now returns a product type instead of a tuple along with an error so we can avoid panicking during the creation of `Context`
Testing:
Example of unparseable lockfile:
```
olszewski@chriss-mbp pnpm-patch % turbo_dev …
```
> feat: Avoid panic from lockfile issues

- cli/integration_tests/single_package/run.t
- cli/integration_tests/single_package_deps/run.t
- cli/integration_tests/single_package_no_config/run.t
- cli/internal/run/run.go
Revert log "Remote caching enabled" line to how it used to be, without the `INFO` prefix, but keep additional "Remote caching disabled".
> Remove INFO prefix from log line

- cli/internal/client/client.go
- cli/internal/login/link.go
- cli/internal/login/login.go
- cli/internal/login/status.go
- cli/internal/util/status.go
Part of PI-1319
Handles the new `paused` status from https://github.com/vercel/api/pull/14585 for when a customer has reached their defined spend cap and their spending has been paused.
> support new paused status

- cli/combined-release.yml
The rest of our scripts expect the `turbo` binary at `bin/turbo`
> Add back bin/ directory

- scripts/ignore-examples.js
Because we are deploying our examples now, we only want to build them when absolutely necessary. This ignore script will only rebuild the examples when:
1. The examples themselves have changed
2. The turbo version has changed
> feat(examples): add custom ignore script

- examples/with-svelte/turbo.json
Correct caching for sveltekit example. if using adapter-auto. it will detect `process.env.VERCEL` when deploying to Vercel and delegate to `adapter-vercel`. This takes the intermediate output in `.svelte-kit` and writes a build to `.vercel`.
> fix(examples): cache .vercel for adapter-vercel

- .vscode/launch.json
- cli/internal/run/run.go
- cli/internal/taskhash/taskhash.go
Log any auto included env variables and their respective framework. 
We treat auto detected global env vars similarly: https://github.com/vercel/turborepo/blob/main/cli/internal/run/global_hash.go#L67
So adding this as a debug log for consistency. 
In the future, we should include these (framework at the very least) in dry run as well.
> feat(cli): log auto included envs and framework

- cli/internal/scope/filter/filter.go
- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
Filtering should take into account global changes when deciding what should run. This includes:
1. turbo.json
2. package manager lockfile
3. root package.json
With these included, this means when running a command like (for example):
`npx turbo run build --filter=docs...[HEAD^]`
Docs would build on changes to any of the three listed files above, even if there are no changes to docs or it's dependencies.
> feat(cli): global defaults for filters

- .github/workflows/stage.yml
Show the branch that we're going to release from, rather than the hash. This is more useful for the second phase where we build from a branch.
> Show branch name rather than commit

- examples/with-changesets/README.md
- examples/with-changesets/apps/docs/package.json
In two places, the pakage eslint-config-acme is incorrectly referred to as eslint-preset-acme. This breaks the yarn install.
> fix(examples): fix inconsistent package naming in with-changesets example

- examples/with-docker/apps/api/Dockerfile
- examples/with-docker/apps/web/Dockerfile
- update Dockerfile examples  to ensure libc6-compat is installed as well as per latest turbo update  
command : `RUN apk add --no-cache libc6-compat`
> feat(examples): update docker file to install libc6-compact

- cli/internal/run/run.go
- docs/pages/docs/reference/command-line-reference.mdx
This flag no longer needs to be hidden, as the daemon is on by default.
> Mark no-daemon as publicly visible

- cli/internal/cache/cache.go
- cli/internal/cache/cache_fs.go
- cli/internal/context/context.go
- cli/internal/packagemanager/packagemanager.go
- cli/internal/prune/prune.go
- cli/internal/run/run.go
While reading through some packagemanager code, I noticed we were no longer using the cache directory while building up the package-graph, so I pulled it out of the function signature and unwound some dependencies from there.
> Drop unused dependency on cache location

- cli/internal/core/engine.go
- cli/internal/core/engine_test.go
- cli/internal/run/run.go
- cli/internal/run/run_test.go
This PR consolidates some internal terminology around the task graph.
"Scheduler", "Engine" and "TaskGraph"[^1] are all the same thing. The receiver
on the methods for the now `Engine` struct was also confusingly named `p`,
so I've replaced that with `e`.
Touching this file also triggered errors from the linter, so I've also fixed those.
[^1]: Task Graph, as opposed to the "Topological Graph", which refers to the package dependencies
graph.
> Consolidate engine, taskGraph, and scheduler naming to Engine

- cli/internal/lockfile/npm_lockfile.go
- cli/internal/lockfile/testdata/npm-lock.json
`npm` has an additional historically-valid format for the `engines` field in `package.json`. This PR changes the parsing behavior to support _any_ value for the `engines` object.
Closes #2270
> Ensure that the Engines field parses correctly.

- .editorconfig
- .github/workflows/build_go_lib.yml
- .github/workflows/build_rust.yml
- .vscode/settings.json
- cli/Makefile
- cli/combined-shim.yml
- cli/cross-lib.yml
- cli/darwin-lib.yml
Add workflows to:
- build Go static library
- build Rust shim, linking against static library
Add Makefile targets:
- snapshot static library
- publish static library
- snapshot rust shim
- publish rust shim
There are some remaining TODOs in the code, beyond verifying final published artifacts:
> Start on a shim release process

- docs/pages/docs/handbook/what-is-a-monorepo.mdx
Small typo I noticed while reading the "[What is a monorepo](https://turborepo.org/docs/handbook/what-is-a-monorepo#the-root-workspace)" page
> Fix typo in monorepo docs

- cli/internal/packagemanager/infer_root.go
- cli/internal/turbopath/absolute_system_path.go
- cli/internal/turbopath/absolute_system_path_test.go
- cli/internal/turbopath/find_up.go
This reverts the changes to find-up and reuses the previous known-good implementation.
Fixes #2296
> Revert find-up change.

- docs/next.config.js
Otherwise, the rules listed below it are never reached.
Examples: `/docs/guides/workspaces` `/docs/changelog` `/docs/glossary`
We just need to make sure all our cases are still covered without the need of the wildcard. @mattpocock
> Remove wildcard redirect rule from list

- README.md
The title says it all!
(Also, `wSokra` instead of `wsokra` because that's the capitalization the twitter handle shows when opened up on Twitter)
> fix: twitter handle for Tobias in Readme

- docs/pages/pack/docs/features/css.mdx
The command used to compile Tailwind on its own requires an "--input" flag before the input file. 
This flag was missing in the docs.
See https://tailwindcss.com/blog/standalone-cli
> add missing --input flag for the Tailwind command

- docs/pages/repo/docs/handbook/dev.mdx
Link for  filtering a workspace was anchoring to a wrong documentation page
> Fixed the link in a documentation

- README.md
- crates/turbopack/README.md
- packages/turbo/README.md
click the license badge is a 404 page.
> fix: license link not found

- architecture.md
While reading the architecture doc some links to code were failing, seemingly because of a rename.
> Fix links for Architecture: Registry

- docs/components/QuickStart.tsx
Currently the "why turborepo?" card link send us to a 404 page
> fix: why turborepo? link

- cli/Makefile
- cli/integration_tests/setup.sh
- cli/integration_tests/turbo_help.t
- cli/integration_tests/turbo_version.t
A quick PR that should add some tests to make sure we're aware of how we're changing the help text with the Rust shim.
Also updated the version test so we check the version against the contents of `version.txt` instead of just making sure it matches the semver regexp.
> feat: add shim to help and version integration tests

- docs/package.json
- docs/pages/_app.tsx
- pnpm-lock.yaml
- Source code: https://github.com/vercel/analytics
- Docs: https://vercel.com/docs/concepts/analytics/audiences/quickstart
> Add Audience Analytics to turbo.build site

- .github/ISSUE_TEMPLATE/1-turbopack-bug-report.yml
these are being manually added right now: https://github.com/vercel/turbo/labels/area%3A%20turbopack. We also have `pkg: *` prefixes, but it's not super clear how they are different from `area: `.
> Add area label to turbopack bug reports

- Cargo.lock
- crates/turbo-tasks-fs/Cargo.toml
- crates/turbo-tasks-fs/src/lib.rs
- crates/turbopack/tests/node-file-trace/integration/ts-package/tsconfig.json
Adds support for trailing commas in tsconfig.json to match the behavior of TypeScript. Uses the [jsonc-parser](https://crates.io/crates/jsonc-parser) crate from dprint, which is used by Deno to parse config files. Deno differs from TypeScript in that it allows unquoted property names, the default behavior of jsonc-parser. Since there's no specification for JSONC there's no real right answer, although being conservative and matching TypeScript seems reasonable.
An alternative would be to extend `skip_json_comments` to remove trailing commas as well, but IMO this is a reasonable dependency.
References:
- [jsonc-parser in Deno](https://github.com/denoland/deno/blob/a189c5393e1b106687736635fea0b8aeca283826/cli/args/config_file.rs#L582)
- [Quoted property requirement in …
> Support comments in tsconfig.json

- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/entry/server-api.tsx
- crates/next-core/js/src/entry/server-renderer.tsx
This hook is needed to ensure we properly map compiled modules like `styled-jsx` correctly. 
x-ref: [slack thread](https://vercel.slack.com/archives/CGU8HUTUH/p1666824437456749?thread_ts=1666819473.031139&cid=CGU8HUTUH)
> Add Next.js require hook

- crates/next-core/src/nodejs/pool.rs
We now wait 30s instead of 1s before declaring the Node.js process a lost cause. We also early exit if the process has exited as well, which could trigger a timeout before.
> More forgiving timeout when waiting for Node.js to connect

- crates/turbo-tasks-memory/src/scope.rs
@sokra told me this isn't used anyway, but might as well fix it just in case.
> Fix decrement_tasks incrementing instead

- crates/next-dev/benches/bundlers/turbopack.rs
[ijjk/add-require-hook](https://github.com/vercel/turbo/pull/2434) broke the Turbopack benchmarks because they are using an older canary version of Next.js. This bumps the dependency to 13.0.0 to fix it.
> Update Next.js dependency for the TP benchmark

- crates/next-dev/Cargo.toml
- crates/next-dev/src/main.rs
This PR adjusts next-dev's cli args to be compatible with next.js, to consolidate implementation across places.
> refactor(next/dev): allow devserver args serializable

- crates/next-core/src/next_client/context.rs
- crates/turbo-tasks/src/primitives.rs
- crates/turbopack/src/lib.rs
- crates/turbopack/src/module_options/mod.rs
- crates/turbopack/src/module_options/module_options_context.rs
- crates/turbopack/src/module_options/module_rule.rs
Turning `ModuleRuleCondition::matches` into a `tt::fun` generates ~500,000 tasks _just_ for the 10k modules app. Our overhead per-task is quite high at the moment, so it doesn't make sense to pay that cost. On 20k modules I see a ~6% performance improvement.
TODO: We don't need to turn `ModuleRuleCondition` into a Vc at all. It could store a FileSystemPathReadRef/RegexReadRef directly. I'll do that next.
> Fix large regression with turning ModuleRuleCondition::matches into a tt::fun

- crates/turbo-tasks-memory/src/task.rs
In our 30k example test app, for the Turbopack SSR benchmark, we schedule very large background tasks which can block other incoming foreground tasks. This is particularly noticeable in our HMR benchmarks as the HMR updates will be severely slowed down when run alongside these large tasks. This contributed to the volatility of our HMR numbers.
Future work (next week?) will be to split up these large tasks and keep them in the background, but for now moving them to the foreground is good enough.
> Avoid expensive background work

- crates/next-dev/benches/mod.rs
With https://github.com/vercel/turbo/pull/2482, we don't need as complicated benchmark warmups to get reliable numbers.
> Simplify benchmark warmup

- .github/workflows/test-cargo.yml
This PR allows to workaround npm install failurs on the windows ci like this:
https://github.com/vercel/turbo/actions/runs/3353855000/jobs/5556978248#step:13:440
However, note this won't make windows CI itself green - there is an actual test failure need to be addressed separately.
> ci(action): workaround windows node-gyp failure

- .github/workflows/bench-turbopack.yml
- .github/workflows/bench-turbotrace-against-node-nft.yml
- .github/workflows/check-codestyle-filtered.yml
- .github/workflows/dispatch-next-dev-custom-bench.yml
- .github/workflows/dispatch-next-dev-matrix-bench.yml
- .github/workflows/pr-turbopack-bench.yml
- .github/workflows/quick-test-cargo.yml
- .github/workflows/release-turbopack.yml
- .github/workflows/test-cargo.yml
There's a deprecate warning 
https://github.com/vercel/turbo/actions/runs/3356892324/jobs/5562302817#step:3:7
> Warning: The `save-state` command is deprecated and will be disabled soon
in current rust-action cache. Bump up to resolve.
> ci(action): bump up rust cache

- crates/turbopack-ecmascript/src/path_visitor.rs
remove all allocations during visiting
rust magic with lifetimes
use binary search instead of hash map
sort visitors initially
> fix bad performance in ApplyVisitors

- docs/components/pages/pack-home/PackBenchmarksGraph.tsx
This PR increases the precision of numbers shown on the benchmarks bar charts and displays `ms` instead of `s` when the value is < 1s. It also fixes a rounding error where some values would be rounded down instead of up. For instance, 0.015s was incorrectly rounded down to 0.01s.
> Fix rounding issue and use proper units

- packages/create-turbo/templates/_shared_ts/apps/docs/package.json
- packages/create-turbo/templates/_shared_ts/apps/web/package.json
- packages/create-turbo/templates/_shared_ts/packages/eslint-config-custom/package.json
- packages/create-turbo/templates/pnpm/apps/docs/package.json
- packages/create-turbo/templates/pnpm/apps/web/package.json
Follow up to #2317 where these packages didn't get their next version updated, but started using the [`transpilePackages`](https://github.com/vercel/next.js/pull/41583) config option which isn't in `12.3.1`.
Fixes #2499 #2493 #2513
> fix: create-turbo update next version in templates

- .github/workflows/check-codestyle-filtered.yml
Chore to store raw output of clippy itself, so we can display it later.
> ci(actions): store raw clippy output

- packages/turbo/bump-version.js
This prevents Prettier from getting into a fight with our release process.
> Include trailing newline when serializing package.json

- cli/internal/daemon/connector/connector.go
- cli/internal/daemon/connector/connector_test.go
As reported by Jesse, we had a non-exhaustive PID error check. This is a Red/Green PR with test recreating the panic, and then a test demonstrating that the panic no longer exists.
https://discord.com/channels/818588653005176832/854119566413922365/1036524672046604359
> fix:Non-exhaustive PID error check

- docs/package.json
> Specify node@16 in engines for docs workspace

- crates/next-dev/src/devserver_options.rs
- crates/next-dev/src/lib.rs
There are few non-clap parseable flags in devserveroption for the usecase via api bindings only. PR disables those properties if feature is not enabled.
> refactor(next/dev): do not expose unsupported cli options

- xtask/src/visualize_bundler_bench.rs
Our benchmarks charts already have this change applied. This will ensure all future charts do too.
> Line charts: Ensure the time range starts at 0 instead of the minimum time value

- crates/next-core/src/app_source.rs
- crates/next-dev/benches/bundlers/mod.rs
- crates/next-dev/benches/bundlers/turbopack.rs
- crates/next-dev/benches/mod.rs
- crates/next-dev/benches/util/page_guard.rs
- crates/next-dev/benches/util/prepared_app.rs
- crates/turbopack-create-test-app/src/test_app_builder.rs
RSC: whole page is a server component
RCC: whole page is a client component
add `app` directory to test app
This also makes sure that app dir is tested as part of the benchmark tests
> add RSC and RCC for turbopack to benchmarks

- packages/create-turbo/package.json
- packages/create-turbo/src/index.ts
- pnpm-lock.yaml
Support node 14 for create-turbo. Swap from native `fs` to `fs-extra` which supports a `copySync` method in 14. 
Fixes https://github.com/vercel/turbo/issues/2602 (and a bunch of others)
> fix(create-turbo): support node 14

- cli/internal/lockfile/berry_lockfile.go
- cli/internal/lockfile/testdata/berry.lock
Fixes #2590
We were producing incorrect `yarn.lock` files due to not parsing the `unplugged` field in dependency metadata.
Tested by adding `unplugged: true` to an entry in the lockfile fixture and making sure that it survives the roundtrip.
> fix: add unplugged to Yarn 2+ lockfile

- .github/workflows/pr-go-e2e-filtered.yml
- .github/workflows/pr-js-tests-filtered.yml
Skip e2e on examples changes. Examples are not used for these flows. So we can speed up CI by skipping them.
> chore(ci): skip e2e on examples changes

- crates/turbo-tasks/src/manager.rs
The current behavior is broken: when the scheduled foreground task count becomes 0 in between the two atomic loads, we return an event listener that will _never_ be notified if there are no other foreground tasks left to schedule.
> Fix tasks hanging when waiting for foreground tasks to be done

- crates/next-core/js/package.json
- crates/next-core/js/src/dev/hot-reloader.tsx
- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/src/app_render/mod.rs
- crates/next-core/src/app_source.rs
- crates/next-dev/benches/bundlers/turbopack.rs
- pnpm-lock.yaml
This adds the missing `error` `loading` `template` `not-found` and `head` next to `layout` and `page` files in app dir
updates app renderer code to latest next.js updates
> add different keyed app route elements

- Cargo.lock
- Cargo.toml
- shim/Cargo.toml
The latest version cause circular reference issue while compiling with next-rs wasm crate.
```
error: cyclic package dependency: package `indexmap v1.9.1` depends on itself. Cycle:
package `indexmap v1.9.1`
... which satisfies dependency `indexmap = "^1.5.2"` of package `serde_json v1.0.87`
... which satisfies dependency `serde_json = "^1.0"` of package `wasm-bindgen v0.2.83`
... which satisfies dependency `wasm-bindgen = "^0.2.83"` of package `js-sys v0.3.60`
... which satisfies dependency `js-sys = "^0.3"` of package `getrandom v0.2.8`
... which satisfies dependency `getrandom = "^0.2.3"` of package `ahash v0.7.6`
... which satisfies dependency `ahash = "^0.7.0"` of package `hashbrown v0.12.3`
... which satisfies dependency `hashbrown = "^0.12"` of package `indexmap v1.9.1`
... which …
```
> Downgrade indexmap and serde_yaml

- Cargo.lock
- Cargo.toml
- crates/turbopack-css/Cargo.toml
- crates/turbopack-css/src/module_asset.rs
- crates/turbopack-css/src/parse.rs
Due to transitive dependency version conflict (css_modules specifically), it was not able to build with current swc_core version in next-swc. 
Instead, trying to bump up both to latest, and removes direct reference to swc_css_modules to avoid conflict.
> build(cargo): bump up dependencies

- .github/workflows/pr-go-e2e-all.yml
- .github/workflows/pr-go-e2e-filtered.yml
- .github/workflows/pr-go-integration-all.yml
- .github/workflows/pr-go-integration-filtered.yml
e2e tests are very slow, and integration tests are sometimes flakey. It is a pain to wait for all e2e tests to run and then find out the integration tests failed. Separating them will parallelize the two.
> Update integration test workflows

- packages/turbo/install.js
This adds a helpful error when we fail to run the turbo binary in alpine linux pointing to the related doc to help users get unblocked when failing to run with glibc compat installed as currently they will just see an `ENOENT` error which doesn't lead to the docs very well. 
x-ref: https://github.com/vercel/turbo/pull/2212
x-ref: https://github.com/vercel/turbo/issues/2198
> Add proper error with doc link on failure in alpine

- docs/theme.config.js
At least one person out there has misconfigured their browser such that `navigator.language` is an array, not a locale string.
Event ID [9857031a464d4493a3d1ac6932611794](https://sentry.io/organizations/vercel/issues/3731718814/events/9857031a464d4493a3d1ac6932611794/)
> try/catch wrap gitTimestamp's useEffect

- cli/integration_tests/monorepo_one_script_error/run.t
- cli/integration_tests/single_package/dry-run.t
- cli/integration_tests/single_package/run.t
- cli/integration_tests/single_package_deps/dry-run.t
- cli/integration_tests/single_package_deps/run.t
- cli/integration_tests/single_package_no_config/dry-run.t
- cli/integration_tests/single_package_no_config/run.t
- cli/internal/taskhash/taskhash.go
We should be considering the path of the task that is executing as part of its hash.
Fixes #1671
> Include the directory into the task hash.

- crates/next-dev/src/devserver_options.rs
This PR exposes few napi-only bindings options to next-dev cli as well.
Aligned with https://github.com/vercel/next.js/pull/42656, attempts to allow to run custom binary with next.js transparently. It is mostly for the easier CI testing (pick up next.js, run its test with turbopack PR) however also allows local dev testing bit easier since it is possible to avoid to rebuild napi bindings per each turbopack changes.
Cli options are not stablized yet, so I expect this won't cause noticeable breaking changes in the future. It'll be breaking changes, but this is more close to internal api currently.
> feat(next-dev): align devserver cli options to napi bindings

- docs/pages/repo/docs/reference/codemods.mdx
Fixes code blocks in [Turborepo Codemods](https://turbo.build/repo/docs/reference/codemods#migrate-env-var-dependencies).
> fix(docs): fix typo in code blocks

- docs/pages/repo/docs/getting-started/existing-monorepo.mdx
Change implemented https://github.com/vercel/turbo/pull/1903 from discussion https://github.com/vercel/turbo/discussions/1891
> chore(docs): correct supported os list

- cli/integration_tests/monorepo_one_script_error/monorepo/turbo.json
- cli/integration_tests/monorepo_one_script_error/run.t
The flakiness introduced in #2672 stemmed from the fact that if `error` was selected to run first it would exit early and not attempt the `okay` task. Cleanest solution I could think of was to have `error` depend on `okay` so we ensure it gets run and can verify that the `okay` logs don't get displayed with the new output mode.
> fix: force execution order in monorepo error tests

- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
This behavior is frameworks-specific and unintuitive to new users.
Specifically, this removes the confusion between omitting the outputs
key and setting to an empty array. Additionally, this will allow us to
more clearly define turbo.json composition, so locally-scoped turbo.json
configs can override outputs, without rationalizing what happens to this
implicit behavior.
Stacked PRs:
> Remove default task outputs when outputs is not defined

- docs/pages/repo/docs/reference/command-line-reference.mdx
We now support `prune` w/ npm as of https://github.com/vercel/turbo/pull/2203
> docs: Remove callout now that we support prune w/npm

- .github/workflows/bench-turbopack-scheduled.yml
- .github/workflows/test.yml
- crates/next-dev/benches/bundlers/mod.rs
- crates/next-dev/benches/bundlers/nextjs/mod.rs
- crates/next-dev/benches/bundlers/nextjs/next.config.js
- crates/next-dev/benches/bundlers/turbopack.rs
- crates/next-dev/benches/mod.rs
- crates/next-dev/benches/util/mod.rs
- crates/turbopack-create-test-app/src/test_app_builder.rs
- xtask/src/visualize_bundler_bench.rs
measure hmr_to_commit with detector component
add Next.js 13 to benchmarks with RSC and RCC measurements
this tests RSC HMR
make HMR warmup faster
make browser launch lazy
test benchmarks for other bundlers on CI too
> fix HMR for RSC benchmarking

- cli/internal/lockfile/berry_lockfile.go
- cli/internal/lockfile/berry_lockfile_test.go
Solves the issue that @jsbrain found in #2313. Still unable get reproduce the original issue.
The underlying issue was that `refine-antd` listed `antd` as a peer dependency and direct dependency with different version constraints and the `peerDependency` version was overriding the direct version.
We ran into a similar issue with pnpm that I fixed in #2151. I'll be investigating if we need to do something similar for npm as well.
> fix: Yarn 2+ no longer include peer dependencies in AllDependencies

- .github/workflows/bench-turbopack-scheduled.yml
since this is tested in the single workflow
> disable testing other bundlers in special branch names

- cli/internal/lockfile/npm_lockfile.go
- cli/internal/lockfile/npm_lockfile_test.go
When unmarshalling the package-lock.json, since `PeerDependenciesMeta` is not present on the `NpmPackage` struct it gets dropped when `turbo prune` does its thing. This caused `npm ci` to complain due to the package and lock-file being out of sync as described in #2739 
By adding this property to the struct, it gets preserved when unmarshalling and persists in the lockfile after the prune, resulting in a pruned package and lock-file that remain in sync according to `npm`.
> fix: adding `PeerDependenciesMeta` to `NpmLockfile` to fix issue with `turbo prune`

- cli/internal/run/dry_run.go
- cli/internal/run/graph_run.go
- cli/internal/run/real_run.go
- cli/internal/run/run.go
- cli/internal/run/run_spec.go
This PR factors out dry runs and graph runs from `run.go` and combines `run()` and `runOperation()`. The goal was originally to clean up how DryRuns work so I could add more information into it (namely resolved turbo.json configs and more run summary info), but it was easy to go one step further and clean up a lot of `run.go`. 
I would recommend looking at the `run()` and `runOperation()` code before and the `run()` function after. I was also able to reduce some duplication around how the analytics and caching structs are initialized.
> Separate turbo run.go code into separate files

- docs/pages/repo/docs/getting-started/add-to-project.mdx
Given Turborepo is intended to use on workspaces, it is very likely users are adding it to the root of an already configured workspace.
If you run `pnpm add` on a workspace root, you get an error:
```
 ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.
```
This adds the `--workspace-root` flag to the docs command so this is skipped.
This might also be needed for yarn but I'm not sure if they have a stable option besides `--ignore-workspace-root-check` on 1.x.
> docs: include --workspace-root on pnpm add command

- examples/with-react-native-web/apps/native/metro.config.js
Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`. Without this line, the native app was crashing due to the following error: 
```
Error: Unable to resolve module ./packages/ui/node_modules/react-native/Libraries/HeapCapture/NativeJSCHeapCapture from /Users/username/code/turbo/with-react-native-web/apps/native/.
"Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Registered callable JavaScript modules (n = 0): .
A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native."
```
I followed the Expo docs and added step 3 to get this example working again for …
> Update metro.config.js 

- crates/next-dev/Cargo.toml
- crates/next-dev/src/devserver_options.rs
Partially related with WEB-206: current next.js test suites set port via env variable, we'd like to support it for the integration tests.
> feat(next-dev): support port via env variable

- docs/pages/repo/docs/getting-started/add-to-project.mdx
Address two issues with the "add to project" docs. 
1. provide reference to `turbo.json` docs
2. include `.gitignore` step
> fix(docs): update add to project docs

- Cargo.lock
- crates/next-dev/Cargo.toml
- crates/next-dev/build.rs
- crates/next-dev/src/devserver_options.rs
- crates/next-dev/src/main.rs
Digging WEB-206 and I'm really not sure what's going on now, so would like to add few more diagnostic points to ensure correctly reproduce issues on the CI vs. local for the specific changesets.
PR adds new cli option `--display-version`, which attempts to print out known status of the build. This might need some touch if this'll be used in public, but for now simple println! would do the trick.
> feat(next/dev): allow to display version

- .github/workflows/test.yml
Curious if we could use things like https://github.com/actions-rs/clippy-check instead.
> ci(actions): try to diff correct clippy results

- crates/turbo-tasks-macros/src/value_macro.rs
- crates/turbo-tasks-macros/src/value_trait_macro.rs
- crates/turbo-tasks-memory/src/cell.rs
- crates/turbo-tasks-memory/src/memory_backend.rs
- crates/turbo-tasks-memory/src/memory_backend_with_pg.rs
- crates/turbo-tasks-memory/src/task.rs
- crates/turbo-tasks-rocksdb/src/db.rs
- crates/turbo-tasks-rocksdb/src/old_version/backend.rs
- crates/turbo-tasks-rocksdb/src/old_version/db.rs
- crates/turbo-tasks-testing/src/lib.rs
- crates/turbo-tasks/src/backend.rs
- crates/turbo-tasks/src/lib.rs
- crates/turbo-tasks/src/manager.rs
- crates/turbo-tasks/src/persisted_graph.rs
- crates/turbo-tasks/src/raw_vc.rs
- crates/turbo-tasks/src/task_input.rs
- crates/turbopack-core/src/chunk/optimize.rs
We used to keep some state about the assignments of cells in Tasks between executions, but that has some problems:
* Executions are not pure anymore, bad for distributed execution
* We need to store the state for each task (high memory usage)
* We can't fully unload task state as we always need to keep the state.
This PR removes the state in favor of
* no more keyed_cell. It was only used in 3 places, these were converted to `cell()` instead. If we need the ability to key cells in future we might need to add the key to `CellId` (potentially converting it to an enum).
* `RawVc` stores the ValueTypeId in addition to the index and Tasks have cell arrays keyed by value type.
This makes tasks pure and allows to drop CellMappings from TaskState.
As it's very likely that Tasks only store cells …
> get rid of CellMappings

- .github/workflows/test.yml
Part 1 for WEB-133.
I tried nearly week to create a complete PR to including running custom turbopack binary, but currently hard blocked by WEB-169 (unknown hang / timeout).
Instead, this PR starts from an obvious step to create known-working state, by running a specific canary of next.js tests on turbo CI. This seems to correctly passing, and further changes can be ensured to pass when adding new changes.
> test(next): run latest next.js canary test on the CI

- .github/workflows/test.yml
- .taplo.toml
- Cargo.lock
- Cargo.toml
- crates/next-binding/Cargo.toml
- crates/next-binding/README.md
- crates/next-binding/src/lib.rs
- crates/turbopack-ecmascript/Cargo.toml
Related with WEB-225.
This is not a complete solution, more close to stop-gap instead. As shared before,  if I want to bump up swc_core to certain version without dupe (i.e, if there are breaking changes we should bump altogether) it need couple of steps
- Update swc_core in swc-plugins, publish new plugin crates
- Update swc_core and plugins (emotion, etcs) in turbopack
- Update swc_core in mdxjs-rs , wait for new version publish
- Finally, in next-swc, update swc_core, swc-plugins, mdxjs-rs, lastly turbopack
Not only these steps are verbose, also requires to move lot of parts in different repo altogether.
We can't cleanly resolve transitive dependencies version between turbopack & plugin + others, but at least we can control direct dependencies version between `next-swc` and `turbopack` …
> build(cargo): setup next-binding package

- .github/renovate.json
- cli/Makefile
We don't need renovate to be auto update these.
> chore(renovate): skip turbopack crate tests

- crates/next-dev/src/devserver_options.rs
- crates/next-dev/src/lib.rs
- crates/next-dev/src/turbo_tasks_viz.rs
- crates/node-file-trace/src/lib.rs
- crates/turbo-tasks-memory/src/lib.rs
- crates/turbo-tasks-memory/src/memory_backend.rs
- crates/turbo-tasks-memory/src/memory_backend_with_pg.rs
- crates/turbo-tasks-memory/src/stats.rs
- crates/turbo-tasks-memory/src/task.rs
- crates/turbo-tasks-memory/src/task_stats.rs
- crates/turbo-tasks-memory/src/viz/graph.rs
- crates/turbo-tasks-memory/src/viz/mod.rs
- crates/turbo-tasks-memory/src/viz/table.rs
- crates/turbo-tasks/src/backend.rs
- crates/turbo-tasks/src/lib.rs
- crates/turbo-tasks/src/manager.rs
- crates/turbo-tasks/src/small_duration.rs
- crates/turbo-tasks/src/timed_future.rs
- crates/turbopack/examples/turbopack.rs
This decreases the size of the `Task` struct from 504 bytes to 488 (16 bytes saved), by only computing stats that are absolutely necessary unless `--full-stats` is passed.
> Make task stats take less memory by default

- package.json
Before #2859:
`eslint --quiet --fix`
After #2859:
`pnpm run lint --quiet --fix --`
=>
`eslint . --ext js,jsx,ts,tsx --quiet --fix --`
After this:
`eslint --ext js,jsx,ts,tsx --quiet --fix --`
Removes the sneaky `.`.
> Update lint-staged behavior.

- docs/next.config.js
This PR does three things:
1. Prevents double redirects by setting the correct destination the first time.
2. Redirects URLs accidentally recreated in the new scope. 🤦‍♂️
3. Removes a catch-all to trigger any additional missing links to appear.
Changes are easy to review commit-by-commit.
> Fix the missing links.

- crates/next-core/js/src/entry/server-renderer.tsx
- crates/next-core/src/app_source.rs
- crates/next-core/src/server_rendered_source.rs
- crates/next-core/src/util.rs
- crates/turbopack-node/src/node_rendered_source.rs
The next.js client code looks for the `[id]` segments in the pathname and only then passes `params`, previously we only passed the resolved path
> pass params to dynamic pages

- crates/turbopack-node/src/lib.rs
Now `process.cwd()` is the next project directory instead of the output directory
> set correct cwd for server renderer

- Cargo.lock
- Cargo.toml
- crates/turbopack-core/Cargo.toml
- crates/turbopack-ecmascript/src/parse.rs
Fixes WEB-155
This is the final piece in turbopack resolves circular deps with indexmap. This can go next.js with swc_core bump.
Prerequisites:
- https://github.com/swc-project/plugins/pull/114
- https://github.com/wooorm/mdxjs-rs/pull/7
> build(cargo): update swc_core, dependencies to resolve circular deps

- crates/turbopack-core/src/chunk/mod.rs
For example:
```js
// index.js
setTimeout(() => {
import('./async.js').then(() => console.log('async.js loaded'))
}, 1000)
```
```js
// async.js
import './async.css';
console.log('async.js content')
```
For now the graph generated by above code will be like this:
The `ChunkGroup_async` will be a async chunk group of `ChunkGroup_index`, pushed at [turbopack-core/src/chunk/mod.rs#L462](https://github.com/vercel/turbo/blob/b7bcfc312e41367e2ec7f5fb37a6ee88a6b6545a/crates/turbopack-core/src/chunk/mod.rs#L462), and it will have a reference between `ChunkGroup_index` and `ChunkGroup_async`, but `ChunkGroup_async` will also be a chunk group of `ChunkGroup_async-manifest-chunk` created at [turbopack-ecmascript/src/chunk/loader.rs#L165](https://github.com/vercel/turbo/blob/b7bcfc312e41367e2ec7f5fb37 …
> make lazy bundling for dynamic import more lazy

- crates/turbo-tasks-macros/src/value_impl_macro.rs
- crates/turbo-tasks-macros/src/value_trait_macro.rs
- crates/turbo-tasks/src/manager.rs
- crates/turbo-tasks/src/task_input.rs
- crates/turbo-tasks/src/value_type.rs
* use Cow to avoid creating Strings for trait function names
* trait calls avoid the resolve trait wrapper task when called on a resolved VC
* eagerly resolve some Vc that would otherwise create a lot of wrapper tasks
Depends on #2416
> Reduce the number of Strings and wrapper tasks

- crates/turbo-tasks-memory/src/memory_backend.rs
- crates/turbo-tasks-memory/src/task.rs
Move bound task function into TaskState to allow unloading
Fixes WEB-238
cuts memory usage by 9% and allows to unload more memory in case of GC
> Share TaskInputs between task cache and task

- Cargo.lock
- crates/next-dev/src/lib.rs
- crates/turbopack-core/Cargo.toml
- crates/turbopack-core/src/resolve/mod.rs
- crates/turbopack-core/src/resolve/parse.rs
- crates/turbopack-core/src/resolve/pattern.rs
- crates/turbopack-ecmascript/src/references/typescript.rs
- crates/turbopack-ecmascript/src/typescript/mod.rs
- crates/turbopack-ecmascript/src/typescript/resolve.rs
- crates/turbopack/src/lib.rs
This adds a query field to the module struct in the request enum. Currently, specifiers that include a queryparam-like `?foo=bar` are treated as literal parts of the filename. This change means that (at least for module requests for the time being), this query param is no part of the file name during resolving.
> @next/font [1/n] Add query structure to module requests

- Cargo.lock
- Cargo.toml
- crates/turbo-tasks-fetch/Cargo.toml
- crates/turbo-tasks-fetch/build.rs
- crates/turbo-tasks-fetch/src/lib.rs
- crates/turbo-tasks-fetch/tests/fetch.rs
This implements an initial, basic version of retrieving resources (GET-only for now) over http via turbo-tasks. It currently supports specifying the resource url and an optional User-Agent header string, which is needed for upcoming `@next/font` support.
For now, the results of these requests will never be invalidated in the turbo-tasks cache, which is acceptable as the lifetime of the cache is the lifetime of the turbopack process. In the future, we should probably leverage cache context for http like Cache-Control headers to invalidate cache.
Test Plan: Added several unit tests, including that the result is never invalidated and requests are never re-sent.
Closes WEB-190
> [3/n] turbo-tasks-fetch

- crates/turbopack-css/src/references/import.rs
- crates/turbopack-tests/tests/snapshot/css/css/output/crates_turbopack-tests_tests_snapshot_css_css_input_style.css
fix this: https://github.com/vercel/turbo/pull/2839#discussion_r1044202479
> fix css indent in `ImportAttributes::print_block`

- crates/next-dev/src/lib.rs
This is vestigial and isn't used by anything.
> Remove next_static_source

- shim/src/main.rs
This can otherwise cause rustfmt to fail with the following when ffi.rs hasn't been generated yet:
```
Error writing files: failed to resolve mod `ffi`: /Users/alex/dev/turbo/shim/src/ffi.rs does not exist
```
> Skip formatting ffi.rs

- crates/next-core/src/next_font_google/mod.rs
- crates/next-core/src/next_font_google/options.rs
- crates/next-core/src/next_font_google/util.rs
- crates/turbo-tasks/src/primitives.rs
This adds `font-weight`, `font-style`, and a fallback font both to the css styled by the exported `className` as well as to the exported `style` object.
Test Plan:
Given `const inter = Inter({weight: "500", fallback: ["Arial"]});`, verified the following css properties were generated and the following js was exported:
```css
.className◽\[project-with-next\]... {
font-family: 'Inter', 'Arial';
font-weight: 500;
font-style: normal;
}
```
```js
{ 
className: ".className◽\[project-with-next\]...",
style: {
"fontFamily": "'Inter', 'Arial'",
"fontWeight": 500,
"fontStyle": "normal"
}
}
```
> [7/n] @next/font/google: Add font weight, style to css and js properties

- cli/internal/core/engine.go
- cli/internal/core/engine_test.go
Bug Introduced in a refactor https://github.com/vercel/turbo/pull/2546/files
> fix(core): fix turbo engine task builder

- Cargo.lock
- crates/next-core/src/next_font_google/mod.rs
- crates/turbo-tasks-fetch/Cargo.toml
- crates/turbo-tasks-fetch/src/lib.rs
- crates/turbo-tasks-fetch/tests/fetch.rs
Fixes WEB-274.
This emits issues whenever a fetch fails. This happens within fetch itself, and it's still up to the caller to handle the results of errors.
Note that there is a change in behavior: turbo-tasks-fetch now uses reqwest's `error_for_status`, meaning that `Error`s will be returned if a status of >= 400 is received in a response. This trades a bit of control from the caller for better handling the common need of informing the user when bad responses are received.
Test Plan: Added unit tests for failed connetion and bad response statuses.
> turbo-tasks-fetch: Emit issues on failed fetches

- crates/next-core/src/next_font_google/mod.rs
- crates/turbo-tasks-hash/src/deterministic_hash.rs
This uses hex-encoded hashes so that filenames for virtual assets for @next/font/google are unique. Previously, every virtual asset generated by @next/font/google would have the same path to the asset, impacting the quality of sourcemaps. This also keeps the basename consistent between the js and css module counterparts This also keeps the names consistent between the js and css module counterparts.
This also implements `DeterministicHash` for the `&str` type.
Test Plan: Given
```js
import {Inter} from '@next/font/google';
import {Open_Sans} from '@next/font/google';
const inter = Inter({weight: "500"});
const sans = Open_Sans({weight: "500"});
```
...Chrome shows a tree of sourcemapped sources of:
```
[embedded_modules]/@vercel/turbopack-next
internal
font/google …
```
> @next/font/google: Hash filenames used in virtual file paths

- .github/workflows/update-google-fonts.yml
- package.json
- pnpm-lock.yaml
- scripts/fetch-google-font-data.js
#2960 broke the Google font-data.json update script, since `node-fetch` is distributed as ESM-only as of version 3: https://github.com/vercel/turbo/actions/runs/3681051865
This has the script use the native implementation in Node instead.
This highlights an issue: Nothing checked that the script worked and prevented this change from landing. We should probably run this update (maybe in a dry-run mode?) on PRs.
> Use native fetch in fetch-google-font-data.js

- cli/internal/daemon/connector/connector.go
- cli/internal/daemon/connector/connector_test.go
- cli/internal/daemon/daemon.go
- cli/internal/daemon/status.go
Previously if the daemon were contacted by a client process with a different version the client would attempt to kill the daemon.
This makes `status` harmless.
> fix(daemon): make status harmless.

- cli/integration_tests/bad_flag.t
- cli/scripts/monorepo.ts
- crates/turborepo-lib/src/cli.rs
Drop deprecated flags that are no longer respected. If a user passes these to a 1.7 binary it will now error instead of silently throwing away the values.
These flags no longer appear in run command misuse text as the snapshot shows.
> chore(turborepo): drop deprecated run flags

- crates/turborepo-lib/src/shim.rs
We're currently too restrictive with the semver as `>=1.7.0` doesn't include canaries of 1.7.0. This relaxes that constraint and adds tests to make sure it's correct now.
> fix: expand semver for skip infer flag

- Cargo.lock
- Cargo.toml
- crates/turbopack-css/src/references/import.rs
- crates/turbopack-ecmascript/tests/analyzer/graph/declarations/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/fn-array-2/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/fn-array/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/iife/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/md5-reduced/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/md5/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/md5_2/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/nested/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/object/graph.snapshot
- crates/turbopack-ecmascript/tests/analyzer/graph/peg/graph.snapshot
Implement / fixes WEB-308
Bumps up all of swc_core* transitive deps, and update test fixtures with latest updates.
> build(cargo): bump up swc_core*

- Cargo.lock
- Cargo.toml
- crates/next-core/Cargo.toml
- crates/next-dev/Cargo.toml
- crates/turbo-tasks-fetch/Cargo.toml
- crates/turbo-tasks-fetch/build.rs
Implement / fixes WEB-306.
We can't rely on default tls backend for reqwest and hope to work with every target platform we support, due to several constraints. Some target cannot use -sys (openssl-sys), and some can't build rustls due to trasnsitive dep support issue.
PR creates explicit opt-in features for those and let upstream application can specify what they need. `next-dev` currently sets `native-tls` as default for the general dev workflow conveniences, but that doesn't mean we promote it as default feature set - next-swc, or other like standalone turbopack will configure features by themselves when build binaries for their own.
> build(next/core): allow to specify tls backend for reqwest

- cli/integration_tests/global_turbo/uses_global.t
- cli/integration_tests/no_args.t
- cli/integration_tests/turbo_help.t
- crates/turborepo-lib/src/cli.rs
Somehow we didn't support parsing `--skip-infer`, the shim parser would allow it, but the actual parser didn't.
> fix: add support for --skip-infer

- cli/integration_tests/global_turbo/repo_with_local/package.json
I committed some invalid JSON in #3011 as the node linter doesn't run on json changes. I'll put up another PR fixing that, but I just wanted to get this out since it's making all PR's that change JS red.
> fix: invalid json in integration test

- packages/turbo/install.js
I think this should fix the install errors with the current canary since the repo inference is having trouble when being run inside of `node_modules/turbo`.
This should be valid for all installs going forward as we now support `--skip-infer`. Any previous versions that don't support it will use the old install script.
> fix: use --skip-infer during install

- Cargo.lock
- Cargo.toml
- crates/next-core/src/server_rendered_source.rs
- crates/turbopack-ecmascript/src/lib.rs
- crates/turbopack-mdx/Cargo.toml
- crates/turbopack-mdx/build.rs
- crates/turbopack-mdx/src/lib.rs
- crates/turbopack/Cargo.toml
- crates/turbopack/src/lib.rs
- crates/turbopack/src/module_options/mod.rs
- crates/turbopack/src/module_options/module_rule.rs
Implements / fix WEB-86. This PR is an initial attempt to support mdx natively inside of turbopack. 
It uses mdxrs (https://github.com/wooorm/mdxjs-rs) internally to interop - compile - mdx inputs into renderable ecma outputs. PR creates a new type of asset `MDXAsset`, and then let its extension (`.mdx`) can be consumed by turbopack. 
Since mdx is a variant of ecma asset to be rendered, it requires to perform all of the ecma transforms in the current running turbopack session. But since its AST is not compatible to plain swc (or ecma), it also cannot be passed into existing ecmaassets. MDXAsset does interop for those, by creating a virtualasset for the ecma once mdx is compiled into plain ecma. This might not be feasible appoarch and requires different way to chain asset types, something …
> feat(mdx): initial turbopack-mdx asset

- Cargo.lock
- crates/turborepo-lib/Cargo.toml
- crates/turborepo-lib/src/shim.rs
The Windows kernel normalizes paths by converting them to UNC, but silly things like starting a process with a working directory given as a UNC path don't work on Windows:
```
'\\?\C:\Users\Chris\Documents\code\junk\yarn-test'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```
This PR uses `dunce` when normalizing paths on windows so we produce non-UNC paths which are better supported by the Windows ecosystem.
> fix: normalize current directory to non-UNC path on Windows

- .github/workflows/build_rust.yml
Fixes an issue with our release process where we need to build the Rust binary for Ubuntu in an environment with an old version of GLIBC because Rust dynamically links to it. So if we build in an environment with a new version, it will fail when run on older systems (for example - the binary we build on ubuntu latest in github actions (2.35) fails on Vercel (2.26), and on ubuntu 18 because of GLIBC differences
> fix(release): build ubuntu in xenial for GLIBC

- .github/workflows/build_rust.yml
This is a hack for the items in the matrix that don't run in a container. You can specify a blank image, but not blank options. 
We should split this out into two runs in a follow up, those that need a container and those that don't.
Priority now is getting the release out
> fix(release): add placeholder options

- crates/next-core/src/next_client/context.rs
- crates/next-core/src/next_config.rs
- crates/turbopack-dev-server/src/html.rs
- crates/turbopack-node/src/source_map/trace.rs
Re: code review nits from #2955
> Fix nitpicks with load-next-config

- packages/turbo-ignore/__tests__/args.test.ts
- packages/turbo-ignore/__tests__/getTask.test.ts
- packages/turbo-ignore/__tests__/ignore.test.ts
- packages/turbo-ignore/src/args.ts
- packages/turbo-ignore/src/getTask.ts
- packages/turbo-ignore/src/ignore.ts
- packages/turbo-ignore/src/types.ts
`turbo-ignore` by default specifies `build` as the task it will run. This makes it possible to specify an alternative task name as the entry point.
This enables `npx turbo-ignore --task="workspace#build"`, for example.
> Allow specifying tasks.

- crates/next-dev/src/turbo_tasks_viz.rs
- crates/turbopack-core/src/source_map.rs
- crates/turbopack-ecmascript/js/src/runtime.js
- crates/turbopack-ecmascript/js/types/protocol.d.ts
- crates/turbopack-ecmascript/src/chunk/mod.rs
- crates/turbopack-node/src/source_map/content_source.rs
- crates/turbopack-node/src/source_map/trace.rs
- crates/turbopack-tests/tests/snapshot/basic/async_chunk/output/crates_turbopack-tests_tests_snapshot_basic_async_chunk_input_index_9be35c.js
- crates/turbopack-tests/tests/snapshot/basic/chunked/output/crates_turbopack-tests_tests_snapshot_basic_chunked_input_index_b11d49.js
- crates/turbopack-tests/tests/snapshot/css/absolute-uri-import/output/crates_turbopack-tests_tests_snapshot_css_absolute-uri-import_input_index_e03a4b.js
- crates/turbopack-tests/tests/snapshot/css/css/output/crates_turbopack-tests_tests_snapshot_css_css_input_index_907a50.js
- crates/turbopack-tests/tests/snapshot/emotion/emotion/output/crates_turbopack-tests_tests_snapshot_emotion_emotion_input_index_b6dbf3.js
- crates/turbopack-tests/tests/snapshot/env/env/output/crates_turbopack-tests_tests_snapshot_env_env_input_480486.js
- crates/turbopack-tests/tests/snapshot/evaluated_entrry/runtime_entry/output/a587c_tests_snapshot_evaluated_entrry_runtime_entry_input_index_50fbca.js
- crates/turbopack-tests/tests/snapshot/example/example/output/crates_turbopack-tests_tests_snapshot_example_example_input_index_a7beb7.js
- crates/turbopack-tests/tests/snapshot/import-meta/cjs/output/crates_turbopack-tests_tests_snapshot_import-meta_cjs_input_index_859774.js
- crates/turbopack-tests/tests/snapshot/import-meta/esm-multiple/output/79fb1_turbopack-tests_tests_snapshot_import-meta_esm-multiple_input_index_a53493.js
- crates/turbopack-tests/tests/snapshot/import-meta/esm-mutable/output/crates_turbopack-tests_tests_snapshot_import-meta_esm-mutable_input_index_bbd10b.js
- crates/turbopack-tests/tests/snapshot/import-meta/esm-object/output/crates_turbopack-tests_tests_snapshot_import-meta_esm-object_input_index_31d622.js
- crates/turbopack-tests/tests/snapshot/import-meta/esm/output/crates_turbopack-tests_tests_snapshot_import-meta_esm_input_index_7072f9.js
- crates/turbopack-tests/tests/snapshot/import-meta/url/output/crates_turbopack-tests_tests_snapshot_import-meta_url_input_index_94525c.js
- crates/turbopack-tests/tests/snapshot/imports/json/output/crates_turbopack-tests_tests_snapshot_imports_json_input_index_e24981.js
- crates/turbopack-tests/tests/snapshot/imports/resolve_error_cjs/output/79fb1_turbopack-tests_tests_snapshot_imports_resolve_error_cjs_input_index_e00120.js
- crates/turbopack-tests/tests/snapshot/imports/resolve_error_esm/output/79fb1_turbopack-tests_tests_snapshot_imports_resolve_error_esm_input_index_1a5dd4.js
- crates/turbopack-tests/tests/snapshot/imports/static/output/crates_turbopack-tests_tests_snapshot_imports_static_input_index_b8717b.js
- crates/turbopack-tests/tests/snapshot/node/node_protocol_external/output/79fb1_turbopack-tests_tests_snapshot_node_node_protocol_external_input_index_6a3d80.js
- crates/turbopack-tests/tests/snapshot/styled_components/styled_components/output/a587c_tests_snapshot_styled_components_styled_components_input_index_7b57d9.js
- crates/turbopack-tests/tests/snapshot/swc_transforms/mono_transforms/output/a587c_tests_snapshot_swc_transforms_mono_transforms_input_packages_app_index_739f58.js
- crates/turbopack-tests/tests/snapshot/swc_transforms/preset_env/output/79fb1_turbopack-tests_tests_snapshot_swc_transforms_preset_env_input_index_44c34f.js
- crates/turbopack-tests/tests/snapshot/tsconfig/baseurl/output/crates_turbopack-tests_tests_snapshot_tsconfig_baseurl_input_index_5906e5.js
HMR is handled via an `eval(newCode)`, and that eval will inherit the filepath of the currently running file (in our case, the chunk file that contains the runtime code). To properly trace, we need to know both the chunk and the item ids, so we trace via the correct item's source map.
Thankfully, we can use the (underspecified) [`//# sourceUrl` ](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/source-maps#use--sourceurl-to-name-evaluated-files-in-the-sources-tool) meta comment to name the file we're currently evaluating. That'll get used as the stack frame's file. We can then encode the chunk path and item id into the filename, and let next's stack tracing code handle the rest.
This also fixes an off-by-one on the column. Source maps are 0-based, but …
> Fix source map tracing for HMR updates

- crates/next-core/src/env.rs
- crates/next-core/src/next_config.rs
- crates/next-dev/Cargo.toml
- crates/next-dev/src/devserver_options.rs
- crates/turbopack-core/src/issue/mod.rs
> set `__NEXT_STRICT_MODE`

- cli/Makefile
Fixes publishing packages that haven't been built.
> fix(publish): corrupt packages canaries

- crates/next-dev/src/devserver_options.rs
Seems #2878 removed this accidentally
> Add clap macros for is_next_dev_command

- crates/next-core/src/next_font_google/mod.rs
- crates/next-core/src/next_font_google/options.rs
- crates/turbo-tasks/src/primitives.rs
Fixes WEB-341
This incorporates a digest of the font request into the name of the font-family defined in the stylesheet, used in the css class, and returned to the JavaScript importer. This makes font-family names returned from `@next/font/google` in stylesheets unguessable.
Note that this implementation uses 8-character long hex digests compared to the 6-character version in Next.js+webpack. 
Test Plan: imported Open Sans as a symbol, verified that stylesheet is updated to reference both `@font-face` definitions and the css class rules with `font-family: '__Open_Sans_3b020fa1';`. Verified that exported js object `style.fontFamily` references the same.
> @next/font/google: scope font names

- .cargo/config.toml
- crates/turbopack-ecmascript/src/references/mod.rs
- crates/turbopack-mdx/src/lib.rs
Clippy has gone too far, and I don't want to refactor the remaining functions to take less arguments and pass a struct.
With an unrelated small fix, this puts us at 0 clippy warnings!
> Disable clippy::too_many_arguments globally

- crates/turbopack-core/src/resolve/options.rs
- crates/turbopack/src/resolve.rs
@sokra I can't remember us ever using it. I think we should remove it until we find a use for it again in the future (if ever).
> Remove by_glob from ImportMap

- crates/next-dev/src/lib.rs
- crates/turbo-tasks/src/manager.rs
add counting seconds when something is happening. Only starts to show when compilation takes more than 1s
> add progress output to command line

- crates/next-core/src/next_config.rs
- crates/turbo-tasks-fs/src/glob.rs
- crates/turbopack-node/js/src/ipc/evaluate.ts
- crates/turbopack-node/js/src/transforms/postcss.js
- crates/turbopack-node/js/src/transforms/postcss.ts
- crates/turbopack-node/src/evaluate.rs
- crates/turbopack-node/src/lib.rs
- crates/turbopack-node/src/transforms/postcss.rs
pass the dependencies reported by postcss to turbo-tasks-fs. We don't have a good mechanism to track dependencies back-timed, so we start watching some as soon we know about the dependencies (after postcss compilation)
tailwind reports dependencies as directory + glob, so our globbing need some improvements to handle these globs reported by tailwind.
e.g. tailwind will rerun when any file changed from the tailwind config `content` globs.
fixes WEB-356
> handle dependencies reported by postcss

- crates/next-core/src/server_rendered_source.rs
Any `404.js` page would inject a `[...]` path into the server generation. The problem comes from the `pathname_for_path` function, which will extract the extension from that path. In this case, it leads to a basename of `[...` and an extension of `]`, breaking the `regular_expression_for_path` dynamic route parser.
Unfortunately, our integration tests timeout when I try to write a basic test case for this, so it's not possible to test at the moment. I've manually verified.
Fixes WEB-214
> Fix server generation of 404 pages

- crates/next-core/src/next_client/context.rs
- crates/next-core/src/next_import_map.rs
- crates/next-core/src/next_server/mod.rs
- crates/turbopack-tests/tests/snapshot.rs
- crates/turbopack/src/condition.rs
- crates/turbopack/src/lib.rs
- crates/turbopack/src/module_options/mod.rs
- crates/turbopack/src/module_options/module_options_context.rs
- crates/turbopack/src/resolve.rs
- crates/turbopack/src/resolve_options_context.rs
> add rules to alter resolve/module context depending on context path

- crates/next-core/js/package.json
- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/entry/app/layout-entry.tsx
- crates/next-dev/benches/bundlers/turbopack/mod.rs
- crates/next-dev/tests/package.json
- pnpm-lock.yaml
* add GlobalError export to layout entry (see https://github.com/vercel/next.js/pull/44066)
* update app manifest for CSS (see https://github.com/vercel/next.js/pull/44168)
> update to latest next.js

- crates/next-dev/src/lib.rs
- crates/turbopack-dev-server/src/lib.rs
#3021 [removed](https://github.com/vercel/turbo/pull/3021/files#diff-c6405fb94033af4296b1f72626fb990aaf76f645b6ed0f7812c56fcad719cf0eL304-L306) 1 level of error wrapping, and the unwrapping code was not updated to match.
> Fix retrying when port already bound

- crates/next-core/src/next_image/mod.rs
- crates/turbopack-core/src/introspect/mod.rs
- crates/turbopack-dev-server/src/source/source_maps.rs
- crates/turbopack-node/src/source_map/content_source.rs
- crates/turbopack-node/src/source_map/trace.rs
- Adds `details` to `SourceMapContentSource`
- Fixes `ty` of `SourceMapContentSource`
- Adds default `children` trait method that returns empty children
> Misc ContentSource changes

- crates/next-core/src/next_client/context.rs
- crates/next-core/src/next_server/mod.rs
- crates/node-file-trace/src/lib.rs
- crates/turbopack-ecmascript/src/lib.rs
- crates/turbopack-ecmascript/src/parse.rs
- crates/turbopack-ecmascript/src/references/mod.rs
- crates/turbopack-tests/tests/snapshot.rs
- crates/turbopack/benches/node_file_trace.rs
- crates/turbopack/src/lib.rs
- crates/turbopack/src/module_options/mod.rs
- crates/turbopack/src/module_options/module_options_context.rs
- crates/turbopack/src/module_options/module_rule.rs
- crates/turbopack/src/resolve_options_context.rs
- crates/turbopack/tests/node-file-trace.rs
fixes weird typescript errors caused by types being referenced by .ts files
> separate typescript with types from typescript transformed

- crates/next-dev/src/lib.rs
- The 10th attempt used to day "trying again" and then didn't try again because the iterator ended…
- Swaps a nested `.map() == Some(bool)` for a `and_then`
- Extracts into a helper function so code can early return without an `Option<Result>` wrapper.
> Misc fixes to starting dev server

- docs/components/pages/pack-home/PackBenchmarks.tsx
- docs/components/pages/pack-home/PackBenchmarksGraph.tsx
- docs/pages/pack/docs/comparisons/vite.mdx
> Add a SWC badge to Vite's graph label

- cli/integration_tests/basic_monorepo/profile.t
- cli/integration_tests/basic_monorepo/verbosity.t
- cli/integration_tests/find_correct_turbo.t
- cli/integration_tests/lockfile_aware_caching/berry.t
- cli/integration_tests/lockfile_aware_caching/npm.t
- cli/integration_tests/lockfile_aware_caching/pnpm.t
- cli/integration_tests/lockfile_aware_caching/yarn.t
- cli/integration_tests/monorepo_one_script_error/run.t
- cli/integration_tests/single_package/dry-run.t
- cli/integration_tests/single_package/graph.t
- cli/integration_tests/single_package/run.t
- cli/integration_tests/single_package_deps/dry-run.t
- cli/integration_tests/single_package_deps/graph.t
- cli/integration_tests/single_package_deps/run.t
- cli/integration_tests/single_package_no_config/dry-run.t
- cli/integration_tests/single_package_no_config/graph.t
- cli/integration_tests/single_package_no_config/run.t
- cli/scripts/e2e/e2e.ts
- crates/turborepo-lib/src/shim.rs
Adds an info message if the turbo shim detects it's being run in a Turborepo project, but there's no local turbo binary to invoke e.g. the Turborepo project itself
> fix: add info message when using global turbo in repo

- Cargo.lock
- cli/integration_tests/bad_flag.t
- cli/integration_tests/basic_monorepo/profile.t
- cli/integration_tests/basic_monorepo/verbosity.t
- cli/integration_tests/find_correct_turbo.t
- cli/integration_tests/global_turbo/uses_local.t
- cli/integration_tests/link.t
- cli/integration_tests/lockfile_aware_caching/berry.t
- cli/integration_tests/lockfile_aware_caching/npm.t
- cli/integration_tests/lockfile_aware_caching/pnpm.t
- cli/integration_tests/lockfile_aware_caching/yarn.t
- cli/integration_tests/login.t
- cli/integration_tests/logout.t
- cli/integration_tests/monorepo_one_script_error/run.t
- cli/integration_tests/no_args.t
- cli/integration_tests/single_package/dry-run.t
- cli/integration_tests/single_package/graph.t
- cli/integration_tests/single_package/run.t
- cli/integration_tests/single_package_deps/dry-run.t
- cli/integration_tests/single_package_deps/graph.t
- cli/integration_tests/single_package_deps/run.t
- cli/integration_tests/single_package_no_config/dry-run.t
- cli/integration_tests/single_package_no_config/graph.t
- cli/integration_tests/single_package_no_config/run.t
- cli/integration_tests/turbo_help.t
- cli/integration_tests/turbo_version.t
- cli/integration_tests/unlink.t
- crates/turborepo-lib/Cargo.toml
- crates/turborepo-lib/src/shim.rs
This parses verbosity in the shim, and then configures a shim logger that matches the format of the go logger. 
This also moves all messages about detecting local vs global and inference to DEBUG (hidden by default)
> feat(shim): add logger

- .github/CODEOWNERS
Both teams have an interest in top-level configuration, and we shouldn't block merges on changes to, e.g. `Cargo.lock`.
> Share rust config ownership between web-tooling and turbo-oss

- .github/workflows/build_rust.yml
Rather than `*` (on the wrong path), `chmod` exactly the binaries we expect to be there
> Explicitly chmod binaries

- .gitignore
- cli/cmd/turbo/version.go
- packages/create-turbo/package.json
- packages/turbo-codemod/package.json
- packages/turbo/package.json
- version.txt
Deployed, merging version bumps back into `main`.
> publish 1.7.0-canary.6 to registry

- packages/turbo/install.js
We need to ensure that both binaries are copied in our optimized case, they expect to be next to each other.
> Copy go-turbo as well as turbo in install script

- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
Deprecate package.json configs. We've had a warning and migration path (codemod) in place for close to a year.
> feat(cli): disable package.json config support

- .github/workflows/build_rust.yml
Fix from change introduced here: https://github.com/vercel/turbo/pull/3175/files
> fix(ci): swap turbo back to actions-rs/toolchain

- cli/integration_tests/no_args.t
- cli/internal/cmd/root.go
Top-level Go errors currently get swallowed, this PR sends them to `stderr`. 
Includes an integration test to ensure that the error is visible
> Show an error if no tasks are supplied to run

- .github/workflows/update-google-fonts.yml
This is currently failing as a direct commit due to `main` being protected: https://github.com/vercel/turbo/actions/runs/3869665076/jobs/6595936942
Test Plan: https://github.com/vercel/turbo/pull/3233 was opened via a manual run of the workflow on this branch.
> Open PRs for font data updates instead

- crates/turbo-tasks-fs/src/lib.rs
It fixes the case when adding, removing or renaming files on root dir doesn't trigger an update.
maybe fixes #3215, but I can confirm as I can't really reproduce with the steps provided.
> fix inconsistent sys_path leading to watching issue on root dir

- .github/workflows/pr-clean-caches.yml
`check_run` was probably overkill, also added concurrency to not make it run multiple times for the same commit
> clean cache a little less often

- docs/pages/repo/docs/core-concepts/caching.mdx
- docs/pages/repo/docs/getting-started/create-new.mdx
- docs/pages/repo/docs/handbook/dev.mdx
- docs/pages/repo/docs/reference/codemods.mdx
- docs/pages/repo/docs/reference/command-line-reference.mdx
- docs/pages/repo/docs/reference/configuration.mdx
- packages/create-turbo/templates/_shared_ts/package.json
- packages/create-turbo/templates/pnpm/package.json
- packages/create-turbo/templates/yarn/package.json
- packages/turbo-types/src/types/config.ts
This adds documentation for the `persistent` key, adds it into
documentation examples, and removes `--parallel` where it isn't
necessary. It also updates `examples/` where `dev` tasks are used.
⚠️ This PR should be merged **after** `turbo@1.7` is released to npm.
Stacked PRs:
1. #2546
2. #2258
3. #2669 (this one)
4. #2738
Separate PR so we can merge docs in after the feature has been released.
> Document `persistent` key

- crates/turbopack-ecmascript/src/lib.rs
`hygiene` pass is required to prevent duplicate variable names.
fixes WEB-393
x-ref: https://vercel.slack.com/archives/C02HY34AKME/p1673451065749759
> Apply `hygiene` pass before `fixer`

- Cargo.lock
- crates/next-core/src/next_client/context.rs
- crates/next-core/src/next_config.rs
- crates/next-core/src/next_server/context.rs
- crates/next-dev/src/lib.rs
- crates/next-dev/tests/integration/turbopack/basic/webpack-loaders/hello.raw
- crates/next-dev/tests/integration/turbopack/basic/webpack-loaders/index.js
- crates/next-dev/tests/integration/turbopack/basic/webpack-loaders/next.config.js
- crates/next-dev/tests/integration/turbopack/basic/webpack-loaders/node_modules/raw-loader/index.js
- crates/next-dev/tests/package.json
- crates/turbopack-core/src/lib.rs
- crates/turbopack-core/src/server_fs.rs
- crates/turbopack-dev-server/src/lib.rs
- crates/turbopack-node/js/package.json
- crates/turbopack-node/js/src/transforms/webpack-loaders.ts
- crates/turbopack-node/js/tsconfig.json
- crates/turbopack-node/src/transforms/mod.rs
- crates/turbopack-node/src/transforms/postcss.rs
- crates/turbopack-node/src/transforms/util.rs
- crates/turbopack-node/src/transforms/webpack.rs
- crates/turbopack/Cargo.toml
- crates/turbopack/src/module_options/mod.rs
- crates/turbopack/src/module_options/module_options_context.rs
- pnpm-lock.yaml
add the minimum to run a simple raw-loader (see test case)
* add `experimental.turbopackWebpackLoaders` to next.config.js
* key is extension like `".mdx"`, value is an array of loaders like `["mdx-loader"]`
> add basic webpack loader support

- .vscode/tasks.json
There is an auto task in our vscode task config, which opens up terminal every time. Changing options to not to open terminal by default if there aren't any failures.
> chore(editor): do not display successful auto task terminal output

- cli/integration_tests/no_args.t
- cli/integration_tests/turbo_help.t
- cli/internal/run/run.go
- crates/turborepo-lib/src/cli.rs
Specifying the CLI arg overrides outputMode from Task Definitions,
so we want to ensure that the user explicitly passes it, and not provide a default.
Fixes https://github.com/vercel/turbo/issues/3272
> Do not submit a default --output-logs argument from Rust 

- crates/next-core/src/fallback.rs
- crates/next-core/src/next_client/context.rs
- crates/next-core/src/next_config.rs
- crates/next-core/src/next_import_map.rs
- crates/next-dev/tests/integration/next/resolve-alias/basic/index.js
- crates/next-dev/tests/integration/next/resolve-alias/basic/next.config.js
- crates/next-dev/tests/integration/next/resolve-alias/basic/node_modules/bar/index.js
- crates/turbopack/src/module_options/module_options_context.rs
Fixes WEB-416.
This implements loading an alias map set as `experimental.resolveAlias` in `next.config.js`.
Test Plan: Added an integration test.
> Implement `experimental.resolveAlias` map for next.config.js

- crates/next-dev/tests/integration/next/dynamic/no-ssr/pages/_dynamic.js
- crates/next-dev/tests/integration/next/dynamic/no-ssr/pages/index.js
- crates/next-dev/tests/integration/next/dynamic/ssr/pages/_dynamic.js
- crates/next-dev/tests/integration/next/dynamic/ssr/pages/index.js
This adds two basic tests for next/dynamic:
* one ensures that SSR supports dynamic components;
* the other ensures that SSR doesn't run when `ssr: false`.
> Add basic test for next/dynamic

- docs/pages/blog/turbo-1-7-0.mdx
`turbo build --output-logs=error-only` => `turbo build --output-logs=errors-only`
> Fix name of command in blog post

- docs/pages/repo/docs/ci/circleci.mdx
- docs/pages/repo/docs/ci/gitlabci.mdx
- docs/pages/repo/docs/ci/travisci.mdx
Images were updated as part of https://github.com/vercel/turbo/pull/3274, but some were missed. This removes the rest.
> fix(docs): remove old image link

- crates/turbo-tasks-fs/src/lib.rs
- crates/turbopack-core/src/resolve/mod.rs
avoid creating very many resolve tasks by resolving the arguments before calling methods on it
> reduce function count

- crates/turborepo-lib/src/cli.rs
Ran into this while testing changes. In general we should figure out better abstractions for relative and absolute paths in Rust.
> fix(turborepo): Passing a relative path to --cwd when using --skip-infer.

- docs/pages/repo/docs/core-concepts/caching.mdx
`outputs: []` is no longer required to cache logs, and can be omitted entirely.
> fix(docs): remove empty array instruction

- .prettierignore
- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/polyfill/async-local-storage.js
- crates/next-core/js/types/globals.d.ts
https://github.com/vercel/next.js/pull/44668 refactored Next's use of `AsyncLocalStorage`, and installs a "polyfill" of the API by patching the node import onto `globalThis.` Importantly, it's then used in the module scope during imports, so we need to install the polyfill early in the app rendering startup.
Fixes https://github.com/vercel/turbo/issues/3319
> Install AsyncLocalStorage for appDir rendering

- Cargo.lock
`Cargo.lock` on main appears to be [out of date](https://github.com/vercel/turbo/actions/runs/3963061842/jobs/6790483844#step:9:276), these are the results of `cargo check`
> fix: update cargo lockfile

- Cargo.lock
- Cargo.toml
- crates/next-transform-dynamic/Cargo.toml
- crates/next-transform-strip-page-exports/Cargo.toml
This updates our `mdxjs` dependency to the tip of https://github.com/wooorm/mdxjs-rs/pull/11, so that we can update it's `swc_core` dependency (it conflicts with ours).
It also updates the `testing` crate to update it's `swc_common` dependency (also conflicting with ours), and makes it a workspace dependency.
> Update mdxjs and testing crates

- cli/Makefile
- cli/cmd/turbo/version.go
- packages/create-turbo/package.json
- packages/turbo-codemod/package.json
- packages/turbo-codemod/tsup.config.ts
- packages/turbo/package.json
- pnpm-lock.yaml
- version.txt
This includes release flow changes to pack with pnpm instead of npm to ensure we convert workspace references correctly. 
This branch has already released, which is why I'm including them here.
> publish 1.7.1-canary.3 to registry

- docs/components/Footer.tsx
- docs/components/SiteSwitcher.tsx
The footer sales link should match the behavior of the header enterprise link.
> fix(docs): use correct enterprise link in footer

- crates/turbopack-ecmascript/src/references/mod.rs
- crates/turbopack-ecmascript/src/typescript/resolve.rs
- crates/turbopack-tests/tests/snapshot/tsconfig/baseurl/output/crates_turbopack-tests_tests_snapshot_tsconfig_baseurl_input_index_5906e5.js.map
- crates/turbopack-tests/tests/snapshot/typescript/jsconfig-baseurl/input/index.js
- crates/turbopack-tests/tests/snapshot/typescript/jsconfig-baseurl/input/jsconfig.json
- crates/turbopack-tests/tests/snapshot/typescript/jsconfig-baseurl/input/prop.js
- crates/turbopack-tests/tests/snapshot/typescript/jsconfig-baseurl/output/79fb1_turbopack-tests_tests_snapshot_typescript_jsconfig-baseurl_input_index_88ac56.js
- crates/turbopack-tests/tests/snapshot/typescript/jsconfig-baseurl/output/79fb1_turbopack-tests_tests_snapshot_typescript_jsconfig-baseurl_input_index_88ac56.js.map
- crates/turbopack-tests/tests/snapshot/typescript/tsconfig-baseurl/input/index.ts
- crates/turbopack-tests/tests/snapshot/typescript/tsconfig-baseurl/input/prop.ts
- crates/turbopack-tests/tests/snapshot/typescript/tsconfig-baseurl/input/tsconfig.json
- crates/turbopack-tests/tests/snapshot/typescript/tsconfig-baseurl/options.json
- crates/turbopack-tests/tests/snapshot/typescript/tsconfig-baseurl/output/a587c_tests_snapshot_typescript_tsconfig-baseurl_input_index_8faddd.ts.js
- crates/turbopack-tests/tests/snapshot/typescript/tsconfig-baseurl/output/a587c_tests_snapshot_typescript_tsconfig-baseurl_input_index_8faddd.ts.js.map
There doesn't appear to be any issues with just returning a `jsconfig.json` when we're looking for a `tsconfig.json` (provided one didn't exist). Finding this gives a `TsConfigReferenceVc` (used for finding type definitions only) and enables the `paths`/`baseUrl` resolution options.
Fixes WEB-230
> Add support for jsconfig.json resolution

- crates/next-core/js/src/internal/page-server-handler.tsx
Our `pageData` HMR process treated an undefined response as an error condition, but if the page doesn't have a `getXyzProps` exported method, then this is the default response. This prevented us from having any pages without page props.
The new code just sends down an empty object, which seems to work for establishing the connection. HMR updates are sent down (and seem to trigger restarts, at least from what I tested with `getStaticProps`).
Fixes WEB-445
> Handle empty pageData during HMR

- cli/internal/context/context.go
- cli/internal/core/engine.go
TopologicGraph in the engine sounds like it's for tasks, since the engine is for executing tasks, but it's really the workspace graph.
> Rename TopologicGraph to WorkspaceGraph

- examples/with-docker/yarn.lock
Fixes https://github.com/vercel/turbo/issues/3419
Updates Next.js to latest so we get support for experimental `transpilePackages`
> chore(examples): update with-docker lock

- turbo.json
outputs are empty arrays by default since 1.7, so we don't need to specify them anymore.
> Remove empty outputs config from turbo.json

- crates/next-core/src/manifest.rs
- crates/next-core/src/next_image/mod.rs
- crates/next-dev/src/turbo_tasks_viz.rs
- crates/turbopack-dev-server/src/introspect/mod.rs
- crates/turbopack-dev-server/src/lib.rs
- crates/turbopack-dev-server/src/source/asset_graph.rs
- crates/turbopack-dev-server/src/source/combined.rs
- crates/turbopack-dev-server/src/source/conditional.rs
- crates/turbopack-dev-server/src/source/mod.rs
- crates/turbopack-dev-server/src/source/source_maps.rs
- crates/turbopack-dev-server/src/source/specificity.rs
- crates/turbopack-dev-server/src/source/static_assets.rs
- crates/turbopack-dev-server/src/update/stream.rs
- crates/turbopack-node/src/render/node_api_source.rs
- crates/turbopack-node/src/render/rendered_source.rs
- crates/turbopack-node/src/source_map/content_source.rs
fixes WEB-141
This changes the ContentSource API.
Before a ContentSource returned a tuple of specificity and content.
Now it returns a tuple of specificity and a get_content function.
The old way made it very inefficient to combine multiple ContentSource.
All combined ContentSources were ask before, all returned specificity and content, and they are ordered after that. That required to compute all contents, even if it is not really used after ordering.
Now we order specificity and a get_content function and only compute the content (by calling get_content) with the final result.
It also changes how data needs are expressed in the `get_content` function. Instead of asking it over and over again with more data, it statically returns the needed data with `vary` and the `get` function is only …
> refactor content sources to avoid evaluating content before serving

- .github/workflows/turborepo-release-step-3.yml
- cli/internal/packagemanager/fixtures/pnpm-patches.json
Auto create the release branch PR after release (so we don't forget)
> feat(release): auto create release PR

- cli/Makefile
We need to use turbo to build our packages because some of them now have internal dependencies that need to be built first.
> fix(release): use turbo to build packages

- .husky/pre-commit
This action started failing because `cargo fmt` was added to the pre-commit hook and the tool is not available without running Rust setup. Instead, we should just skip applying hooks when creating commits from this workflow.
~Since the create-pull-request doesn't have a way of disabling hooks, simply remove the file before husky installs it into place.~ Let `cargo fmt` run on individual files through lint-staged, but don't run it on everything on every precommit.
Test Plan: Manual workflow run on this branch which opened #3401
> don't run `cargo fmt --all` in pre-commit hook

- crates/turbo-updater/src/ui/mod.rs
In #3371, I messed up and used the number of rows instead of the number of columns as the width of the terminal. We now don't require a very tall terminal to print out the full update message:
> fix: use the correct value in termsize tuple

- .github/workflows/on-nextjs-release-publish.yml
Partially progresses WEB-457.
This PR sets up new workflow to subscribe into repository_dispatch event. The event is supposed to be dispatched from next.js upstream when there is a new release.
Currently this is for the access scope (token) verification, so it doesn't do any actual work other than payload correctly delivers ref to the release.
> ci(workflow): setup a new workflow for next.js repo_dispatch

- .config/nextest.toml
This updates nextest.toml to use the new package name for next-dev tests, `next-dev-tests` and adds up to 2 additional retries (for a total of 3 attempts) since these tests tend to be flakey.
**Note**: This requires `cargo-nextest` version 0.9.49, which includes a fix for https://github.com/nextest-rs/nextest/issues/762. Otherwise, you may receive an error when running nextest like:
```
error: failed to parse nextest config at `path/to/.config/nextest.toml`
Caused by:
profile.default.overrides[0].leak-timeout: invalid type: string "500ms", expected struct Duration
Caused by:
invalid type: string "500ms", expected struct Duration
```
Test Plan: Temporarily changed `slow-timeout` to `0s` and verified the override selected next-dev tests by marking them as slow.
> nextest.toml update to next-dev-tests and add retries

- .github/workflows/nextjs-integration-test.yml
- .github/workflows/test.yml
We'll need to run next.js test in multiple place (PR, new next.js release..). This PR makes running next.js integration test reusable without duplicating same logics.
Also this PR changes default behavior of next.js integration test to **always pull latest version of next.js**.
> ci(workflow): reusable next.js integration test

- .github/workflows/on-nextjs-release-publish.yml
This PR actually triggers integration tests when there's a new Next.js release. Collecting stats / displaying it required some trial & error, probably comes after this PR.
> ci(workflow): run next.js integration test with new release

- Cargo.lock
- Cargo.toml
This replaces our use of @jridgewell's fork as upstream has updated to `swc_core@0.56.0`.
> Use mdxjs upstream at 0.1.5

- .github/workflows/turborepo-release-step-3.yml
Swapping workflow since we don't need one that commits and creates it's own branch, we just need to open a PR from an existing branch. This is tested on my private fork
> fix(turborepo): fix create branch workflow

- examples/with-changesets/.github/workflows/release.yml
Looks like we missed the action here when we moved our examples from yarn to pnpm.
Thanks, @colbyfayock for letting us know!
> `changesets` action: `yarn` -> `pnpm`

- cli/internal/lockfile/pnpm_lockfile.go
- cli/internal/lockfile/pnpm_lockfile_test.go
- cli/internal/lockfile/testdata/pnpm-absolute-v6.yaml
- cli/internal/lockfile/testdata/pnpm-absolute.yaml
Fixes #3382
This PR adds support for when pnpm encodes a dependency version as a lockfile key instead of just a version. We already have similar logic in the npm lockfile implementation.
Thanks to @omarahm3 for the reproduction!
> fix: Support pnpm lockfile keys in dependencies

- examples/with-tailwind/.gitignore
The `dist` folder containing distributable component-library and tailwind compiled script should be ignored by git. It will grow bigger if someone didn't realize about it.
> fix(examples) tailwind - ignore ui dist/

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.js
Fixes integration test stat report in PR, due to changing workflow group with reusable one. One day we may need better than this, but changing detection more generic for now.
> ci(workflow): fix integration job log detection

- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
Once again map iteration is the culprit. The failure of `infer_pkg.t` is caused by package inference iterating over the root package before the correct candidate package. This results in `pkgPath == repoRoot` and since `fullInferencePath` is necessarily contained in the repo root, the root package will always be selected as the exact package. The fix is just skipping over the root package.
First commit adds a root package to the tests. The package inference cases will fail in a non-deterministic fashion since this bug depends on the repo root package being iterated over before the package that should be inferred. The next commit is a fix.
> fix: Skip over repo root package for package inferrence

- cli/internal/prune/prune.go
closes #2871 
Copying `.npmrc` file if it exists to keep packageManager settings the same during deploy/Docker builds.
> fix(turborepo): Add `.npmrc` support to `turbo prune`

- crates/next-core/src/next_font_google/mod.rs
- crates/next-core/src/next_font_google/options.rs
- crates/next-core/src/next_font_google/request.rs
- crates/next-dev-tests/tests/integration/next/font-google/basic/pages/index.js
Fixes WEB-501
Fixes https://github.com/vercel/turbo/issues/3139
This adds proper support for the [`variable` property](https://nextjs.org/docs/api-reference/next/font#variable) when constructing fonts. This results in:
* defining a selector in the css module for a classname defining the css custom property (css variable), whose value is the font family
* adding a `variable` property to the resulting js object whose value is the classname used in the selector above
Test Plan: Added an integration test.
> @next/font/google: support setting a css variable for fonts

- crates/next-dev/Cargo.toml
- crates/turbo-tasks/src/util.rs
Enables the anyhow backtrace feature to capture backtraces for errors too when `RUST_BACKTRACE` is enabled.
When running in release mode compiling with `CARGO_PROFILE_RELEASE_DEBUG=1` is recommended to get debug info into the errors.
> enable and fix backtracing for fatal errors in tasks

- cli/internal/fs/turbo_json.go
- cli/internal/prune/prune.go
- cli/internal/util/task_id.go
- cli/scripts/e2e/e2e.ts
Closes #1161
This is based on top of https://github.com/vercel/turbo/pull/3213
Open questions:
- do we want to include root-scoped tasks in the output?
- what should the permissions be on the new turbo file created? we could read the permissions from the old one, or set it manually (I currently do 0664)
> filter out invalid Pipelines from TurboJSON when running turbo prune

- .github/workflows/nextjs-integration-test.yml
This:
* adds `workflow_dispatch` to `on` for the integration test workflow
* adds a basic Slack message that's sent when integration tests complete
It seems like we have to land this change before manual workflow runs become available in the GitHub UI.
> Allow manual workflow dispatch and send a basic message through Slack

- crates/next-core/src/page_source.rs
The new error paths introduced in #3448 both write their outputs to `.next/server/pages/`, which conflicts with:
- The main pages source
- Each other
The infinite loop is very fun:
1. We need a `NodeJsPoolVc` to render pages
2. To get a `NodeJsPoolVc`, you need to write your files onto disk
- So a pool is dependent on the contents of those files
3. When we render an error page, we need to write those files to disk
4. The error page shares the same file entrypoint as the main page source
So, to render an error, we write the entrypoint, which is shared with main source. This alone is pretty bad, because it will invalidate our page source's node pool (and kill those processes). But, the loop is triggered by a more subtle bug:
When we write a file, we read it to see if the contents have …
> Fix infinite loop caused by error page rendering

- crates/next-core/js/src/dev/hmr-client.ts
- crates/next-core/js/src/overlay/internal/components/CodeFrame/CodeFrame.tsx
- crates/next-core/js/src/overlay/internal/components/Dialog/DialogHeader.tsx
- crates/next-core/js/src/overlay/internal/components/Terminal/Terminal.tsx
- crates/next-core/js/src/overlay/internal/components/Toast/Toast.tsx
- crates/next-core/js/src/overlay/internal/container/Errors.tsx
- crates/next-core/js/src/overlay/internal/container/RuntimeError.tsx
- crates/next-core/js/src/overlay/internal/container/TurbopackIssue.tsx
- crates/turbopack-ecmascript/js/types/index.d.ts
Next.js's integration test suite depends on these ids and data attributes to select against items in running test pages. This gets us passing some of those tests.
> Align ids and data attributes with Next.js's redbox

- crates/turbopack-ecmascript/js/src/runtime.nodejs.js
I also considered not including invalid chunks for the current environment in the `ManifestChunkAsset`. This could use the result of the `EnvironmentVc::chunk_loading()` method. I'm partial to neither solution.
> Ignore non-JS chunks on the server

- crates/turbo-tasks-build/src/lib.rs
- crates/turbo-tasks-macros/src/derive/value_debug_format_macro.rs
- crates/turbo-tasks-macros/src/derive/value_debug_macro.rs
- crates/turbo-tasks-macros/src/value_macro.rs
- crates/turbo-tasks-macros/src/value_trait_macro.rs
- crates/turbo-tasks/src/debug/mod.rs
- crates/turbo-tasks/src/read_ref.rs
Adds a mechanism for controlling the depth of `Vc` debugging, to avoid printing out huge structs when we're only interested in some superficial overview of it.
This will only affect `Vc`s: if a `Vc` contains a non-`Vc`, very deep struct, the struct will be fully printed out. This is because you can't control the printing depth of the default Rust `Debug` trait.
Marking this as a draft for now as I intend to change the name and arguments of `dbg_depth`.
```rust
eprintln!("{:?}", some_vc.dbg_depth(2).await?) // will now only print up to a depth of 2
```
> Allow controlling depth of Vc debugging

- crates/node-file-trace/src/lib.rs
So that the `next-swc` can expose it to next.config.js
> Expose memory_limit option in turbotrace

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.js
- .github/workflows/nextjs-integration-test.yml
- .github/workflows/on-default-branch-update.yml
- .github/workflows/on-nextjs-release-publish.yml
- .github/workflows/upload-nextjs-integration-test-results.yml
Closes WEB-487.
This PR amends existing workflow for next-integration test to store its aggregated test results into github artifacts, then corresponding events for the running test (main branch update / new next.js release) to upload it into specific github branch `nextjs-integration-test-data`.
> ci(workflow): upload integration test resuls from main branch, next.j… …s release

- .github/workflows/turborepo-smoke-published.yml
- scripts/smoke-published.ts
Automatically run smoke tests when new versions of Turborepo are published. 
This tests the following matrix: 
```
test: ["local", "global", "both"]
packageManager: ["yarn", "pnpm", "npm"]
localVersion: ["latest", "canary"]
globalVersion: ["latest", "canary"]
```
Where `test` described how `turbo` is installed (local is local install only, global is global install only, and both is both a local and global install. 
This effectively runs 36 tests ensuring our local turbo is cooperating with global turbo across all package managers, and install scenarios. 
Example run from development: https://github.com/tknickman/turborepo/actions/runs/4040066963
**TODO**: Slack notifications on failure
> feat(ci): published smoke tests

- .github/workflows/test.yml
Introduced when moving go integration tests into our main test workflow:
https://github.com/vercel/turbo/pull/3429
> fix(ci): require go integration

- crates/next-core/js/src/internal/page-server-handler.tsx
Returning a 404 status code is required for the client-side router to redirect to the error page.
> Return a 404 status code when a data route is `.notFound`

- cli/internal/scope/filter/parse_target_selector.go
- cli/internal/scope/filter/parse_target_selector_test.go
- Makes clear that an empty path specification (`{}`) is an error, with test (note `+` -> `*` change in regex)
- Switch regex to named capture groups to reduce arbitrary-looking indices in the code
cc @chloetedder
> Handle empty path specification

- crates/next-dev-tests/tests/integration/next/font-google/basic/pages/index.js
#3437 wasn't up to date with main when it was merged.
Test Plan: CI
> font/google test: update cssmodule classnames

- crates/next-core/src/next_edge/context.rs
some packages expect `worker` or `browser` condition to work on edge runtime
> add worker condition to edge compilation

- docs/pages/repo/docs/core-concepts/monorepos/filtering.mdx
As reported in #3480 pnpm seems to intercept filter syntax before it reaches turbo if a package script uses `--filter=./dir/*` without quotes.
Since quotes are also required to use a directory with a glob via ZSH it seems to make sense to add them to our docs.
> docs: add quotes to directory filter with glob

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
- .github/actions/next-integration-stat/tsconfig.json
- .github/workflows/nextjs-integration-test.yml
Requires https://github.com/vercel/turbo/pull/3534
Partially progresses WEB-460
This PR creates a plain text summary, so subsequent workflow can download it via download-artifact then broadcast as needed. We'll use it to posting into Slack channel. Action will only generate text file when we supposed to report (currently, release-to-release) so if download-artifact does not contain text-summary.md, it can skip to broadcast into Slack channel.
> ci(workflow): store plain text test summary

- cli/internal/ui/ui.go
#3586 changed how we calculate `IsCI` and dropped the `!IsTTY` start to the calculation. This breaks our cmdutil tests as they require the `IsCI` flag to be true when the test is running.
We need `IsCI` to be true otherwise we won't look at `VERCEL_ARTIFACTS_TOKEN` as a possible token source.
> fix: bring back tty into ci detection

- Cargo.lock
- crates/next-core/js/src/internal/page-server-handler.tsx
- crates/next-core/src/router_source.rs
- crates/turbopack-dev-server/src/http.rs
- crates/turbopack-dev-server/src/lib.rs
- crates/turbopack-dev-server/src/source/mod.rs
- crates/turbopack-dev-server/src/source/request.rs
- crates/turbopack-dev-server/src/source/resolve.rs
- crates/turbopack-dev-server/src/source/source_maps.rs
- crates/turbopack-dev-server/src/update/server.rs
- crates/turbopack-dev-server/src/update/stream.rs
- crates/turbopack-node/src/render/render_static.rs
- crates/turbopack-node/src/source_map/content_source.rs
With the addition of the Next.js routing layer at the root of our content sources, we need the update server to also be able to follow Next.js rewrites, like the HTTP server.
This requires the following:
* Rewrites need to be able to indicate a source where to "resume" after rewriting. Otherwise, we would enter an infinite loop of the Next.js layer rewriting to the Next.js layer.
* The resolving logic from `process_request_with_content_source` needs to be extracted into its own function, so it may be called both from the HTTP server (which expects fully resolved `ReadRef`s) and the update server (which needs a `VersionedContentVc`): this is where `resolve_source_request` comes in.
> Share request resolving logic between http and update servers

- crates/auto-hash-map/src/set.rs
- crates/turbo-tasks-memory/Cargo.toml
- crates/turbo-tasks-memory/src/memory_backend.rs
- crates/turbo-tasks-memory/src/output.rs
- crates/turbo-tasks-memory/src/task.rs
- crates/turbo-tasks/src/backend.rs
I used this to track down the infinite looping behavior #3525 and #3526. Running `cargo run --features print_task_invalidation --bin next-dev` will print something similar to:
```
invalidated Task { id: 16875, name: ConditionalContentSource::get }
Task { id: 16875, name: ConditionalContentSource::get } invalidates:
Task { id: 16873, name: CombinedContentSource::get }
Task { id: 16832, name: CombinedContentSource::get }
Task { id: 16815, name: CombinedContentSource::get }
Task { id: 16807, name: CombinedContentSource::get }
Task { id: 15384, name: get_from_source }
invalidated Task { id: 16873, name: CombinedContentSource::get }
invalidated Task { id: 16832, name: CombinedContentSource::get }
invalidated Task { id: 16815, name: CombinedContentSource::get }
invalidated Task { id: 16807, …
```
> Add print_task_invalidation feature

- docs/pages/repo/docs/core-concepts/monorepos/running-tasks.mdx
Fixes syntax highlighting for turbo.json in docs
> fix(docs): update turbo.json highlighting in docs

- crates/turbopack-ecmascript/src/chunk/mod.rs
- crates/turbopack-node/src/render/render_static.rs
Two minor issues that clippy complains about.
```
cargo clippy
Blocking waiting for file lock on package cache
warning: using `write!()` with a format string that ends in a single newline
--> crates/turbopack-ecmascript/src/chunk/mod.rs:515:17
|
515 | /                 write!(
516 | |                     code,
517 | |                     "throw new Error({error});\n",
518 | |                     error = &js_error_message
519 | |                 )?;
| |_________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#write_with_newline
= note: `#[warn(clippy::write_with_newline)]` on by default
help: use `writeln!` instead
|
515 ~                 writeln!(
516 |                     code,
517 ~                     "throw new …
```
> fix outstanding clippy lints

- crates/next-core/js/src/overlay/internal/container/Errors.tsx
It's difficult to test an app, if a single error blocks using the whole page.
Therefore, error overlay should always be closeable.
> always allow to close the error overlay

- crates/next-core/js/src/internal/page-server-handler.tsx
Adds support for `getStaticPaths` returning `{ fallback: false }` by building out all static paths and checking whether the resolved path is included in that list.
`buildStaticPaths` requires the `next.config.js` path, as well as other config options such as locale. I created WEB-546 to track being able to pass them to the handlers.
> Support for getStaticPaths.fallback = false

- crates/turbo-tasks-fs/src/glob.rs
Our glob parser was not able to parse alternatives that contain a slash: `{a/b}`
> fix glob parsing and improve error reporting

- .github/workflows/test.yml
This removes some long running tests (mac and windows) from the required PR checks.
Now the CI workflow is split into two parts, `Ok` (required) for the required checks and `Done` (non-blocking) for all checks.
The PR comment will show
🟢 CI likely successful 🟢
A few longer running steps are still running, but they should not be considered as blocking.
See workflow summary for details
after the required checks are done.
Once all checks are done, it will be updated to 🟢 CI successful 🟢 or to ⚠️ CI failed ⚠️ depending on the full result
> split tests into two steps, report ok and done separately

- docs/custom.css
This increases the contrast of the sidebar text against its dark background by slightly lightening it. It now passes WCAG AA guidelines.
Test Plan: https://webaim.org/resources/contrastchecker/
> docs: Increase sidebar text contrast in dark mode

- .github/workflows/nextjs-integration-test.yml
Context: https://vercel.slack.com/archives/C04KC8A53T7/p1675471724960239?thread_ts=1675469142.533699&cid=C04KC8A53T7
There are some expected failures with debug build (without proper setup) for the integration test. This PR choose to build release binary, as it'll also help overall test turnaround time since debug build is lot slower.
> ci(workflow): use release build of next-dev for integration test

- Cargo.toml
- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/entry/app/layout-entry.tsx
- crates/next-core/js/src/entry/edge-bootstrap.ts
- crates/next-core/js/types/modules.d.ts
- crates/next-dev-tests/tests/integration/next/app/async-local-storage/input/app/layout.tsx
- crates/next-dev-tests/tests/integration/next/app/async-local-storage/input/app/page.tsx
- crates/next-dev-tests/tests/integration/next/app/async-local-storage/input/app/test.tsx
- crates/next-dev-tests/tests/integration/next/app/async-local-storage/input/next.config.js
The node evaluation always renders with `type: "commonjs"` and `require()` calls, so we'll always import the CJS files. But here we're importing the ESM files. That means we have 2 distinct instances of `requestAsyncStorage` in our node instance, and they cannot properly communicate with the other.
Fixes WEB-543
> Import Next's CJS AsyncLocalStorage modules

- cli/Makefile
There was an issue with building the go binary on windows. 
Before this PR:
```
make -p
...
go-turbo".exe": internal/turbodprotocol/turbod.pb.go internal/turbodprotocol/turbod_grpc.pb.go go.mod turborepo-ffi-install
...
```
Now dropping the quotes we get the desired build target:
```
make -p
...
go-turbo.exe: internal/turbodprotocol/turbod.pb.go internal/turbodprotocol/turbod_grpc.pb.go go.mod turborepo-ffi-install
...
```
and `make go-turbo.exe` works.
> fix: remove quotes around extension in makefile

- cli/Makefile
- crates/turborepo-lib/src/lib.rs
Fixes #3647
Issue was that we were constructing a header with an unescaped `\r` on Windows as the user agent.
CRLF is the gift that keeps on giving
> fix: turbo login on Windows

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
Minor fix for calculation error.
> ci(workflow): fix summary count error

- crates/node-file-trace/src/lib.rs
- crates/node-file-trace/src/main.rs
Allow reusing `TurboTasks` cross multiple `turbotrace` runs, can create `TurboTasks` in the next.js side and pass it back to reuse it.
Partially Close WEB-562
> Reuse TurboTasks cross turbotrace runs

- cli/internal/fs/get_turbo_data_dir_go.go
Currently our release process is broken as we aren't passing any tags: https://github.com/vercel/turbo/actions/runs/4117196602/jobs/7108350138#step:6:35
Currently the default `go` tag is applied in the makefile which doesn't get picked up by goreleaser. We now default to a go implementation if the `rust` tag isn't present (or if the `go` tag is present). I did this instead of setting default tags in all of our `.yml` files to avoid needing to remember to keep in in sync with the makefile default.
> fix: Use go implementation when no build tags present

- Cargo.lock
- crates/turborepo/Cargo.toml
Currently our release process is broken due to `protoc` not being setup on the machine: https://github.com/vercel/turbo/actions/runs/4118079447/jobs/7110161689#step:6:363
We shouldn't need protoc when building the top level Rust binary as it's only used when building `turborepo-ffi` which is used by `go-turbo` to call Rust code. `turborepo-ffi` is already built if one runs `make go-turbo` which happens as part of our Rust binary's build script (when not creating a release build). During a release build we don't build `go-turbo` since it is built in an earlier step and is only needed when we package up the two binaries.
We could instead setup `protoc` in the Rust build process, but that adds time to the release process.
> fix: remove turborepo binary dependency on ffi

- crates/turborepo-lib/src/shim.rs
Adds some additional debug logs in the shim about the global/local versions:
```
olszewski@chriss-mbp sushiswap % turbo_dev -vv --version
2023-02-06T13:38:47.876-0800 [DEBUG] turborepo_lib::shim: Global turbo version: 1.7.3
2023-02-06T13:38:47.880-0800 [DEBUG] turborepo_lib::shim: Local turbo version: 1.7.2
2023-02-06T13:38:47.880-0800 [DEBUG] turborepo_lib::shim: Running local turbo binary in /private/tmp/sushiswap/node_modules/.bin/turbo
2023-02-06T13:38:47.880-0800 [DEBUG] turborepo_lib::shim: supports_skip_infer_and_single_package true
1.7.2
```
a future PR will add this to the github issues template once this gets released
> chore: add local and global versions in debug

- docs/pages/repo/docs/handbook/deploying-with-docker.mdx
I fixed two mistakes.
- `./out/json` has `package.json` and `./out/full` has `package.json` and `turbo.json` in fact.
- You don't need to copy `turbo.json` manually in Dockerfile because `turbo.json` is already copied in [the previous line](https://github.com/vercel/turbo/compare/main...m-shaka:turbo:docs/fix-pruned-directory-structure?expand=1#diff-3d80bc97cc73148cf5956531eb631ce3e7f58860e778c4b52cf2e3499f4c4f05R139)
> docs: add package.json and turbo.json to a pruned directory example

- .github/workflows/turbopack-nightly-release.yml
This adds a new workflow which automatically releases nightly versions of turbopack. Coupled with https://github.com/vercel/next.js/pull/45506, we'll be able to fully automate our release process into Next.js.
1. The process kicks of with cron every midnight-ish PST.
2. We find the latest commit that passes CI
3. We bump the latest tag version (more on this in a bit)
4. We generate a new GH release with this version
The automated tagging version will break with our current `turbopack-YYMMDD.XYZ` release process just a bit. The tag action that I'm using can't generate a date-like tag, it can only handle semver (with optional prefix). So I've set it up to generate `turbopack-MAJOR.MINOR.PATCH-nightly.XYZ` tags. The `turbopack-` here differentiates us from Turborepo, and the `nightly` tag …
> Automate nightly Turbopack release tagging

- crates/turbo-tasks/src/task_input.rs
(I would have created a Linear issue for this specifically but Linear is down)
This PR allows the use of `(A, B, ...)` as `TaskInput`s. This means that the following are now valid `turbo_tasks::function` signatures:
```rust
fn do_the_thing(path: (FileSystemPathVc, BoolVc)) -> SomeVc;
fn parse_headers(headers: Vec<(StringVc, StringVc)>) -> HeadersVc;
```
> Allow tuples as TaskInputs

- crates/turborepo-lib/src/cli.rs
- crates/turborepo-lib/src/client.rs
- crates/turborepo-lib/src/commands/link.rs
- crates/turborepo-lib/src/commands/login.rs
Adds a test for login. A little messy with the `cfgs`. Perhaps at some point we can abstract out the `dialoguer` terminal interactions into a module, then stub it more cleanly.
> test(turborepo): Login

- crates/turbopack-json/src/lib.rs
- crates/turbopack-tests/tests/snapshot/imports/json/output/crates_turbopack-tests_tests_snapshot_imports_json_input_index_6aa119.js
#3676 seems to have accidentally removed it
> fix json assets being inlined as objects instead of strings

- .github/workflows/test.yml
Expanding the patterns to include any changes to the `cli` directory as well as changing `crates/turborepo*` to `creates/turborepo*/**` which seems to be what we want.
Testing:
Under the hood get-diff-action [uses minimatch](https://github.com/technote-space/get-diff-action#usage) for matching patterns against `git diff`. I quick wrote a test script to verify these patterns should get us what we want:
```
const { minimatch } = require("minimatch")
const paths = [
'crates/turborepo',
'crates/turborepo-ffi',
'crates/turborepo-lib/src/shim.rs',
'crates/turborepo/Cargo.toml',
]
for (const pat of ['crates/turborepo*', 'crates/turborepo*/**']) {
for (const path of paths) {
console.log(`${pat} matches ${path}: ${minimatch(path, pat)}`)
}
}
```
Output:
```
"crates/turborepo* matches …
```
> fix: turborepo integration test glob

- crates/next-core/js/src/entry/config/next.js
- crates/next-core/src/next_config.rs
- crates/next-dev-tests/tests/integration/next/resolve-alias/basic/input/index.js
- crates/next-dev-tests/tests/integration/next/resolve-alias/basic/input/next.config.js
- crates/next-dev-tests/tests/integration/next/webpack-loaders/basic-options/input/next.config.js
- crates/next-dev-tests/tests/integration/next/webpack-loaders/no-options/input/next.config.js
- docs/pages/pack/docs/migrating-from-webpack.mdx
This combines Turbopack-specific options into a nested object `experimental.turbopack`, exposing `loaders` and `resolveAlias` properties.
x-ref: https://github.com/vercel/next.js/pull/45560/files/631b637f42757e20aabe84dc933527dc66b55173#r1098123643
Test Plan: Integration tests for loaders and resolveAlias.
> Combine next.config.js Turbopack options into a nested object

- .github/workflows/test.yml
When using stacked PRs with Graphite, PRs up the stack will not target `main`. This means that, with the current filter, the Test workflow will not apply to them.
> Run the Test workflow on all PRs

- crates/next-core/js/src/internal/page-server-handler.tsx
Otherwise `router.isReady` will never be true for pages without gSSP, gSP or gIP
> set nextExport flag for page rendering

- cli/internal/context/context.go
- cli/internal/core/engine.go
- cli/internal/fs/turbo_json.go
- cli/internal/graph/graph.go
- cli/internal/prune/prune.go
- cli/internal/run/dry_run.go
- cli/internal/run/run.go
- cli/internal/scope/filter/filter.go
- cli/internal/scope/filter/filter_test.go
- cli/internal/scope/scope.go
- cli/internal/scope/scope_test.go
- cli/internal/taskhash/taskhash.go
Cache reads of turbo.json and package.json in the `WorkspaceInfos` struct in CompleteGraph. PackageJSON were already cached there, so it's a natural place to expand the notion of known Workspaces.
> Dedupe TurboJSON and PackageJSON reads

- crates/next-core/src/app_source.rs
- crates/next-core/src/fallback.rs
- crates/next-core/src/next_client_chunks/client_chunks_transition.rs
- crates/next-core/src/page_source.rs
This improves the performance for client-side navigation as it can reuse the modules from the initial navigation. Same for server data requests.
> share asset and chunking context between server, server data and client navigation

- crates/next-core/js/src/dev/hmr-client.ts
This enables HMR updates, even when the update message also contains critical issues.
There were some inconsistencies with the logic previously, so I'm not sure whether this fix is fully correct. More on that in PR comments.
> Enable HMR updates even when critical issues occur

- crates/turbo-tasks-fs/src/rope.rs
Updates and fixes a few items:
- Fix: Prevents a Rope from containing an empty `Bytes` section
- Perf: Use a `Box<[RopeElem]>` instead of a `Vec<RopeElem>`, reducing memory useage
- Perf: Implement fast path for `Rope::to_str()` when containing a single `Shared` element
The first one is the important change. The assumption while iterating (for streaming, equality checks, etc) is that the only time we can hit an empty `Bytes` section is when we reach the end of the entire Rope. If an empty section is hit in the middle of a rope, we can't tell if we've reached the end or we're in the middle without calling N more times (eg, what if an empty section followed an empty section, then we'd need to call 2 more times to see).
> Various Rope updates and fixes

- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/entry/router.ts
- crates/next-core/js/src/entry/server-api.tsx
- crates/next-core/js/src/entry/server-edge-api.tsx
- crates/next-core/js/src/internal/api-server-handler.ts
- crates/next-core/js/src/internal/page-server-handler.tsx
- crates/next-core/js/src/internal/utils.ts
- crates/next-core/js/src/ipc/server.ts
- crates/next-core/js/types/turbopack.d.ts
- crates/next-core/src/router.rs
- crates/next-core/src/router_source.rs
- crates/turbopack-dev-server/src/source/mod.rs
- crates/turbopack-dev-server/src/source/resolve.rs
- crates/turbopack-node/src/render/mod.rs
- crates/turbopack-node/src/render/node_api_source.rs
- crates/turbopack-node/src/render/rendered_source.rs
- crates/turbopack-node/src/source_map/content_source.rs
This PR does a little bit more than what it says on the box. Before, we were parsing URL queries and request headers, only to serialize them some other way afterwards. The reason why we were parsing headers and queries is because we sometimes need to filter them. However, we don't need that for router/page SSR/page API. This PR makes it so we avoid parsing on Turbopack's side through `rawHeaders` and `rawQuery`.
> Add req.cookies to API requests

- Cargo.lock
- crates/turbo-updater/Cargo.toml
- crates/turbo-updater/src/lib.rs
- crates/turborepo-lib/Cargo.toml
`update-informer` has some good stuff in the pipeline that allows us to specify the http client we use. This is a quick and dirty add support for the updater on Windows ARM. If we don't want to use a non-release version of `update-informer` than #3722 should be merged instead of this.
I expect a new release of `update-informer` might take a little bit as this is a breaking change due to the updated `Registry` trait definition.
> fix: use prerelease update-informer to cut ureq

- cli/scripts/npm-native-packages/template/template.package.json
- packages/turbo/node-platform.js
This improves yarn berry support when using `nodeLinker: pnp` by using the correct binary path for the child process. This ensure our rust binary is can correctly find the go binary.
Fixes https://github.com/vercel/turbo/issues/3280
> fix(turbo): improved yarn berry pnp support (#3744

- .github/actions/next-integration-stat/action.yml
- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
- .github/workflows/nextjs-integration-test.yml
- .github/workflows/setup-nextjs-build.yml
- .github/workflows/test.yml
closes WEB-545, WEB-571.
This PR mimic upstream next.js test group config to expand turbopack's integration integration to match with it. To reduce some of duplication, this PR also sets up reusable workflow to setup  / build next.js and share its build artifact via github cache. Since those build artifacts are one-off usage per each test, it doesn't use upload/download artifact which is too slow & heavyweight for those purpose.
> ci(workflow): expand integration test groups

- cli/integration_tests/basic_monorepo/dry_run.t
- cli/integration_tests/basic_monorepo/run.t
- cli/integration_tests/composable_config/composing-bad-json.t
- cli/integration_tests/composable_config/monorepo/apps/bad-json/package.json
- cli/internal/core/engine.go
- cli/internal/fs/turbo_json.go
- cli/internal/graph/graph.go
Only allow the error where workspace config is missing, since
this config is not required. Throw other errors, including
when the contents of the workspace config are malformed.
This allows us to provide better error messaging to the end user
> Improve error bubbling

- crates/turbo-tasks-macros/src/value_trait_macro.rs
This is necessary in order to pass in a `SomeTraitVc` to a function which expects `T: ValueDebug`.
> Implement FromSubTrait for ValueDebug

- crates/next-core/src/app_source.rs
- crates/next-core/src/next_client_chunks/with_chunks.rs
- crates/next-core/src/next_client_component/with_client_chunks.rs
- crates/next-core/src/next_edge/transition.rs
- crates/next-core/src/page_loader.rs
- crates/turbopack-core/src/chunk/mod.rs
- crates/turbopack-css/src/chunk/mod.rs
- crates/turbopack-css/src/module_asset.rs
- crates/turbopack-css/src/util.rs
- crates/turbopack-ecmascript/src/chunk/loader.rs
- crates/turbopack-ecmascript/src/chunk/mod.rs
- crates/turbopack-ecmascript/src/utils.rs
- crates/turbopack-env/src/asset.rs
- crates/turbopack-env/src/embeddable.rs
- crates/turbopack-node/src/bootstrap.rs
- crates/turbopack-static/src/lib.rs
Both `stringify_str` and `stringify_module_id` are now simply `stringify_js`. We could skip this and go directly to `serde_json`, but this hides the dependency behind turbopack-ecmascript.
> Make stringify_str and stringify_module_id use Serialize

- cli/integration_tests/composable_config/composing-add-keys.t
- cli/integration_tests/composable_config/composing-add-tasks.t
- cli/integration_tests/composable_config/composing-cache.t
- cli/integration_tests/composable_config/composing-config-change.t
- cli/integration_tests/composable_config/composing-missing-workspace-config-deps.t
- cli/integration_tests/composable_config/composing-missing-workspace-config.t
- cli/integration_tests/composable_config/composing-omit-keys-deps.t
- cli/integration_tests/composable_config/composing-omit-keys.t
- cli/integration_tests/composable_config/composing-override-values-deps.t
- cli/integration_tests/composable_config/composing-override-values.t
- cli/integration_tests/composable_config/composing-persistent.t
- cli/integration_tests/composable_config/monorepo/apps/config-change/package.json
- cli/integration_tests/composable_config/monorepo/apps/config-change/src/foo.txt
- cli/integration_tests/composable_config/monorepo/apps/config-change/turbo-changed.json
- cli/integration_tests/composable_config/monorepo/apps/config-change/turbo.json
- cli/integration_tests/composable_config/monorepo/turbo.json
- cli/internal/hashing/package_deps_hash.go
When `inputs` is configured for a task, we want to ensure that changes to the `turbo.json` in that workspace cause a cache miss. This is similar to how we treat the `package.json` in the workspace, and also how we treat the root `turbo.json` for the global hash.
> Include workspace turbo.json in inputs

- crates/turborepo-lib/src/lib.rs
This reverts commit dea257ace031859ed92614aa087f8497b2056977.
> Revert "chore: add option to dump args sent to go (#3515)"

- cli/integration_tests/invalid_turbo_json/absolute_path_warning.t
- cli/integration_tests/invalid_turbo_json/monorepo/.gitignore
- cli/integration_tests/invalid_turbo_json/monorepo/apps/my-app/package.json
- cli/integration_tests/invalid_turbo_json/monorepo/package.json
- cli/integration_tests/invalid_turbo_json/monorepo/packages/util/package.json
- cli/integration_tests/invalid_turbo_json/monorepo/turbo.json
- cli/integration_tests/invalid_turbo_json/setup.sh
- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
In this PR:
- un-export `readTurboConfig`
- add warnings via global `log` to instances of absolute paths used in `turbo.json` `globalDependencies`, and per-task `inputs`, and `outputs`
Known issues:
- This is definitely not the best way to add this feature, but is minimally disruptive. During the port, we ought to ensure that we are parsing `turbo.json` and then in a separate pass validating the data so we can wire errors and warnings to the proper ui infrastructure
- We currently read `turbo.json` twice, as well as the root `package.json`. Until we refactor that, warnings will show up twice.
> Warn on absolute paths used in turbo.json

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
- .github/workflows/nextjs-integration-test.yml
- .github/workflows/upload-nextjs-integration-test-results.yml
Closes WEB-544.
PR fixes minor issue to drain logs correctly. 
Also PR adjusts summary to not to print fixed tests - upstream test sometimes flaky and displaying some test as `fixed` intermittently can cause some confusions. For now, disabling those summary. Still we display `new failed`, false negatives are relatively not occur frequently and we can try for a while to see.
> ci(workflow): adjust summary report, drain all logs correctly

- crates/turbopack-ecmascript/src/path_visitor.rs
Visiting is not necessary for those sub-trees that are already out of range.
For example, we have visitors with `ast_path` like this, and the current index is `1`, and the current path is `Path::A`:
```rust
enum Path {
A,
B,
C,
D,
E
}
visitors: vec![(vec![Path::B, Path::C], visitor), (vec![Path::B, Path::D], visitor)]
```
Given the fact that sub-trees that are not matched were already skipped, so there is no possibility for us to have things like this if we are already under `Path::B` and looking for the next path (`ast_path: [Path::B]`): 
```rust
visitors: vec![(vec![Path::B, Path::C], visitor), (vec![Path::C, Path::A], visitor)]
```
Combining all the things above, we can skip visits any furthur where its `kind` is greater than the `kind` for the current index, for the first example, the …
> perf: skip visiting if it's out of range

- crates/next-core/js/package.json
- crates/next-core/js/src/entry/router.ts
- crates/next-core/src/router.rs
- crates/next-core/src/router_source.rs
- crates/next-dev-tests/tests/integration/next/404/navigate/input/pages/index.tsx
- crates/next-dev-tests/tests/package.json
- crates/next-dev/benches/bundlers/turbopack/mod.rs
- pnpm-lock.yaml
I changed the return type of the Next.js router in https://github.com/vercel/next.js/pull/45668 to account for cases where the router does and does not find a matching rewrite.
> Fix the router when Next.js returns no result

- Cargo.lock
- crates/next-dev/src/lib.rs
- crates/node-file-trace/src/lib.rs
- crates/turbopack-cli-utils/src/issue.rs
- crates/turbopack-core/src/issue/mod.rs
- crates/turbopack-dev-server/Cargo.toml
- crates/turbopack-dev-server/src/http.rs
- crates/turbopack-dev-server/src/lib.rs
- crates/turbopack-dev-server/src/source/resolve.rs
- crates/turbopack-dev-server/src/update/server.rs
This reverts commit dae3e2155dcc5dc8e240825da4fd091296486b18.
This commit makes the `turbotrace` hanging, x-ref: https://vercel.slack.com/archives/C02UJN0A1UL/p1676369060652879
> Revert "Issue Reporters (#3707)"

- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/entry/app/layout-entry.tsx
- crates/turbopack-ecmascript/src/references/esm/export.rs
- crates/turbopack-ecmascript/src/references/mod.rs
- crates/turbopack-ecmascript/src/transform/server_to_client_proxy.rs
- crates/turbopack-tests/tests/snapshot/export-alls/cjs-2/output/crates_turbopack-tests_tests_snapshot_export-alls_cjs-2_input_index_0ea679.js
- crates/turbopack-tests/tests/snapshot/export-alls/cjs-script/output/crates_turbopack-tests_tests_snapshot_export-alls_cjs-script_input_index_1cb91d.js
This gets rid of this warning when using a client component as page:
```
warning - [analyze] [project-with-next]/src/app/client/page.jsx  unexpected export *
export * used with module [project-with-next]/src/app/client/page.jsx which has no exports
Typescript only: Did you want to export only types with `export type { ... } from "..."`?
```
* fix export * warning for client pages
* Detect `__turbopack_export_value__` as CJS style exports
* fix `__turbopack_cjs__` name
* flag turbopackHelper in client proxy
> fix export * warning for client pages

- Cargo.lock
- crates/next-dev/src/lib.rs
- crates/node-file-trace/src/lib.rs
- crates/turbopack-cli-utils/src/issue.rs
- crates/turbopack-core/src/issue/mod.rs
- crates/turbopack-dev-server/Cargo.toml
- crates/turbopack-dev-server/src/http.rs
- crates/turbopack-dev-server/src/lib.rs
- crates/turbopack-dev-server/src/source/resolve.rs
- crates/turbopack-dev-server/src/update/server.rs
This restores issue reporters, addressing a bug that prevented turbo-trace from completing. This moves `ConsoleUiVc::new` into an async block to prevent it from stalling.
Test Plan: Verify `cargo run --bin node-file-trace -- print path/to/my/app` no longer stalls.
> Restore Issue Reporters

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
- .github/workflows/upload-nextjs-integration-test-results.yml
Trying to close WEB-589: along with full test results, stores latest test failure list to skip retrying for the known failures.
> ci(workflow): store failed test path list

- cli/internal/fs/fs.go
- cli/internal/fs/fs_windows_test.go
- cli/internal/globwatcher/globwatcher.go
This can happen when a cookie file is written on Windows and the volume letters are different. It's not an error, it just means that the event is not relevant to the glob watcher.
Also update DirContainsPath to handle windows paths with different volumes. Similarly, it is not an error, we can detect that one path doesn't contain the other.
> Change error log line to debug, it's not an error

- examples/basic/packages/ui/package.json
- examples/design-system/packages/acme-core/package.json
- examples/design-system/packages/acme-utils/package.json
- examples/kitchen-sink/apps/admin/package.json
- examples/kitchen-sink/apps/api/package.json
- examples/kitchen-sink/apps/storefront/package.json
- examples/kitchen-sink/packages/logger/package.json
- examples/kitchen-sink/packages/ui/package.json
- examples/with-changesets/apps/docs/package.json
- examples/with-changesets/packages/acme-core/package.json
- examples/with-changesets/packages/acme-utils/package.json
- examples/with-create-react-app/apps/docs/package.json
- examples/with-create-react-app/apps/web/package.json
- examples/with-create-react-app/packages/ui/package.json
- examples/with-docker/apps/api/package.json
- examples/with-docker/packages/logger/package.json
- examples/with-docker/packages/ui/package.json
- examples/with-npm/packages/ui/package.json
- examples/with-prisma/packages/database/package.json
- examples/with-svelte/apps/docs/package.json
- examples/with-svelte/apps/web/package.json
- examples/with-vite/apps/docs/package.json
- examples/with-vite/apps/web/package.json
- examples/with-vite/packages/ui/package.json
- examples/with-yarn/packages/ui/package.json
- packages/create-turbo/templates/_shared_ts/packages/ui/package.json
This is not a cross-platform compatible way to set an environment variable, and it is not critical to have this as part of the examples and starter template.
Fixes https://github.com/vercel/turbo/issues/3797
> Remove TIMING=1 from eslint command in examples and create-turbo starter

- cli/internal/ui/ui.go
Closes #3799. 
| bg | before | after |
| --- | --- | --- |
| dark | <img width="312" alt="CleanShot 2023-02-14 at 16 07 13@2x" src="https://user-images.githubusercontent.com/490968/218891495-7e3abf32-1c82-486b-a534-acebf24c2d5c.png"> | <img width="313" alt="CleanShot 2023-02-14 at 16 07 09@2x" src="https://user-images.githubusercontent.com/490968/218891498-7605c95d-5dbf-4250-8069-4e6d02f84f61.png"> |
| light | <img width="311" alt="CleanShot 2023-02-14 at 16 06 59@2x" src="https://user-images.githubusercontent.com/490968/218891503-06066dcd-603e-4146-a397-e28ee13d355e.png"> | <img width="311" alt="CleanShot 2023-02-14 at 16 06 56@2x" src="https://user-images.githubusercontent.com/490968/218891507-b65ecc8e-ddbb-451f-9714-b1705a73eb34.png"> |
the new color is a bit more dull, but it is also …
> Use non-high intensity yellow for warnings for readability on white background

- docs/pages/repo/docs/ci/github-actions.mdx
The other example on this page uses `actions/checkout@v3`
> use consistent actions/checkout version in examples

- packages/turbo-types/src/types/config.ts
Updated schema to support extends
> feat(types): update turbo.json schema

- docs/pages/pack/docs/migrating-from-webpack.mdx
These docs are currently live on https://turbo.build, but don't reflect the currently available version of Turbopack. Let's revert them, and land a separate PR restoring them before 13.2 ships.
> docs: revert webpack loader documentation for now

- .github/actions/turbopack-bump/action.yml
- .github/actions/turbopack-bump/src/index.ts
- .github/workflows/turbopack-nightly-release.yml
The nightly releases are using the last commit message for the release body, which is a bit weird. This generates a "compare at https://github.com/vercel/turbo/compare/turbopack-230214.2...turbopack-230215.1" listing the commits between the last and new tag.
> Nightly releases: generate basic release body

- crates/next-core/js/src/entry/router.ts
- crates/next-core/src/router.rs
- crates/turbopack-ecmascript/src/lib.rs
This fixes 2 bugs that I've found:
1. If the `middleware.ts` file doesn't exist, then we get an unhelpful `unable to resolve relative "."` error during `next-edge` transition processing
- This is fixed by not processing the `VirtualAssetVc` with the edge transition
2. If you're using an older Next version, then the router doesn't have a `type` field
- Because the `type` field is empty, we hit neither the `rewrite` nor `none` cases and fall through to the middleware case, returning an empty response with no body.
- This is fixed by treating `{ url: string, headers: … }` as `{ type: 'rewrite', url: string, headers: … }`
> Fix routing cases

- cli/integration_tests/basic_monorepo/dry_run.t
- cli/integration_tests/basic_monorepo/run.t
- cli/internal/core/engine.go
Previously, a `validate` method would assert that tasks passed to the CLI exist. After switching to Lazy Loading Tasks and changing how errors bubble, I had removed this validation behavior. This PR adds it back.
> Error if none of the tasks passed to CLI were found

- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
- .github/workflows/nextjs-integration-test.yml
- .github/workflows/setup-nextjs-build.yml
This PR tries to implement WEB-588. Note this still need to be verified, not able to close WEB-588 completely until verification.
PR uses upstream next.js changes with latest test results in the turbo repo, attempts to skip tests if it is already known to fail. It only relies on the latest main branch's result currently. Meanwhile this PR also limits concurrency of the tests suite since it _may_ related with random sigterm causes test flaky / count drift across runs. Originally I thought WEB-544 is fixed, but seems not and require more investigations.
> ci(workflow): attempts to skip retry for the know failed tests

- .github/workflows/daily-nextjs-integration-test.yml
- .github/workflows/test.yml
- .github/workflows/upload-nextjs-integration-test-results.yml
This PR attempts to move next.js integration workflow to the daily cron job, and then post it to the slack since we don't write comment to the PR.
> ci(workflow): move integration test to daily

- crates/next-core/js/src/entry/app-renderer.tsx
- crates/next-core/js/src/entry/router.ts
- crates/next-core/js/src/internal/api-server-handler.ts
- crates/next-core/js/src/internal/headers.ts
- crates/next-core/js/src/internal/page-server-handler.tsx
- crates/next-core/js/src/ipc/server.ts
- crates/next-core/src/next_image/mod.rs
- crates/next-core/src/router.rs
- crates/turbopack-dev-server/src/http.rs
- crates/turbopack-dev-server/src/source/mod.rs
- crates/turbopack-node/src/lib.rs
- crates/turbopack-node/src/render/render_proxy.rs
This is a small cleanup extracted out of the WIP `basePath` PR.
> Use name-value tuples for headers

- docs/pages/pack/docs/advanced/profiling.mdx
`cargo-instruments` 0.4.8 has since been released with an updated cargo dependency.
> Update profiling instructions for macOS

- crates/next-core/js/src/overlay/internal/components/Terminal/styles.tsx
Before long messages would just be hidden:
> make error overlay message scrollable

- crates/next-core/src/next_route_matcher/path_regex.rs
- crates/next-core/src/router_source.rs
- crates/next-dev/src/lib.rs
- crates/turbopack-core/src/introspect/asset.rs
- crates/turbopack-core/src/introspect/mod.rs
- crates/turbopack-dev-server/src/introspect/mod.rs
- crates/turbopack-dev-server/src/source/asset_graph.rs
- crates/turbopack-dev-server/src/source/static_assets.rs
- crates/turbopack-node/src/render/node_api_source.rs
- crates/turbopack-node/src/render/rendered_source.rs
Another small cleanup stemming from the the `basePath` PR. Makes the introspection ordering consistent, which is a nice usability win.
> Use IndexSet in IntrospectableChildrenVc

- cli/integration_tests/composable_config/composing-add-keys.t
- cli/integration_tests/composable_config/composing-add-tasks.t
- cli/integration_tests/composable_config/composing-cache.t
- cli/integration_tests/composable_config/composing-config-change.t
- cli/integration_tests/composable_config/composing-cross-workspace.t
- cli/integration_tests/composable_config/composing-missing-workspace-config-deps.t
- cli/integration_tests/composable_config/composing-missing-workspace-config.t
- cli/integration_tests/composable_config/composing-omit-keys-deps.t
- cli/integration_tests/composable_config/composing-omit-keys.t
- cli/integration_tests/composable_config/composing-override-values-deps.t
- cli/integration_tests/composable_config/composing-override-values.t
- cli/integration_tests/composable_config/composing-persistent.t
- cli/integration_tests/composable_config/monorepo/apps/override-values/package.json
- cli/integration_tests/composable_config/monorepo/apps/override-values/turbo.json
- cli/integration_tests/composable_config/monorepo/turbo.json
- cli/internal/fs/turbo_json.go
- cli/internal/fs/turbo_json_test.go
Overriding `dependsOn` with _both_ a task dependency and a topo dependency seems to work, but _just_ one topo dependency doesn't work.. not sure why that would be, but test case seems to prove it also.
> Fix issue with merging dependsOn from Workspace Configs

- docs/pages/repo/docs/handbook/linting/eslint.mdx
- examples/basic/packages/eslint-config-custom/index.js
- examples/design-system/packages/eslint-config-acme/index.js
- examples/with-changesets/packages/eslint-config-acme/index.js
- examples/with-npm/packages/eslint-config-custom/index.js
- examples/with-prisma/packages/config/eslint-preset.js
- examples/with-rollup/packages/eslint-config-custom/index.js
- examples/with-tailwind/packages/eslint-config-custom/index.js
- examples/with-yarn/packages/eslint-config-custom/index.js
- packages/create-turbo/templates/_shared_ts/packages/eslint-config-custom/index.js
It was added in vercel/turbo#779 as a temporary fix but forgotten about.
> refactor: remove `react/jsx-key` ESLint rule

- crates/turbo-tasks-memory/src/cell.rs
- crates/turbo-tasks-memory/src/gc.rs
- crates/turbo-tasks-memory/src/memory_backend.rs
- crates/turbo-tasks-memory/src/memory_backend_with_pg.rs
- crates/turbo-tasks-memory/src/output.rs
- crates/turbo-tasks-memory/src/scope.rs
- crates/turbo-tasks-memory/src/task.rs
- crates/turbo-tasks-memory/tests/collectibles.rs
- crates/turbo-tasks-testing/src/lib.rs
- crates/turbo-tasks/src/backend.rs
- crates/turbo-tasks/src/manager.rs
- crates/turbo-tasks/src/raw_vc.rs
- crates/turbopack-core/src/issue/mod.rs
connect original task to collectibles reading to fix strongly consistency
move read collectibles tasks to task and scope instead of a separate cache
reading collectibles is no longer strongly consistent by default, it's opt-in now
> fix consistency issue with reading collectibles

- .github/workflows/turborepo-release-step-3.yml
- cli/cross-release.yml
> 🚨 note: I am assuming here that npm is intelligent enough to offer up the x86 package automatically, but there may be more we need to do here..
Rust's only toolchain on windows arm is msvc, which complicates linking now that we have the rust sandwich, as go uses gnu. Rather than attempt to get go building with msvc, we can instead just rely on windows' x86 emulation and publish one set of binaries for that platform until go is removed from our toolchain altogether.
> no longer build arm64 go builds

- cli/integration_tests/basic_monorepo/filter-run.t
- cli/internal/core/engine.go
> Fix turbo run when --filter is provided and no packages are affected

- crates/next-core/src/next_client_component/with_client_chunks.rs
- crates/turbo-tasks-memory/src/task.rs
`WithClientChunksChunkItem` currently only includes paths to chunks' references, but not chunks themselves.
Fixes WEB-621.
> Include chunk path in WithClientChunks

- crates/next-core/src/app_source.rs
- crates/next-core/src/app_structure.rs
- crates/next-core/src/lib.rs
- crates/next-core/src/next_config.rs
- crates/next-core/src/page_source.rs
- crates/next-core/src/pages_structure.rs
- crates/next-core/src/router.rs
- crates/next-core/src/router_source.rs
- crates/next-dev/src/lib.rs
- crates/turbo-tasks/src/completion.rs
- crates/turbopack-node/src/evaluate.rs
- crates/turbopack-node/src/pool.rs
- crates/turbopack-node/src/transforms/postcss.rs
- crates/turbopack-node/src/transforms/webpack.rs
We need to invalidate router node.js process when routes change for correctness
In future we can pass the routes list to next.js instead of only invalidating @jridgewell 
We also need the separated structure for next build @alexkirsz
> separate app and pages structure extraction from source generation

- crates/next-core/js/src/overlay/internal/ReactDevOverlay.tsx
- crates/next-core/js/src/overlay/internal/bus.ts
We now store react errors in the error overlay (hydration errors) and if the error overlay receives the "build ok" message after that it will hard reload the page to recover
> fix: allow HMR to recover from hydration errors

- crates/next-core/src/next_image/mod.rs
- crates/turbopack-dev-server/src/source/mod.rs
- crates/turbopack-dev-server/src/source/source_maps.rs
- crates/turbopack-dev-server/src/source/wrapping_source.rs
- crates/turbopack-node/src/source_map/content_source.rs
This implements a new `ContentSourceProcessor` trait and `WrappedContentSource` struct that allows our `ContentSource`s to register some processor to transform the eventual `ContentSourceContent` that an inner `ContentSource` returns. Yah, it's a bit of a mouthful with lots of very similar sounding names.
Essentially, the old `SourceMapContentSource` and `NextSourceMapTraceContentSource` wrapped some inner `ContentSource`, and would request content from them, and process that content into a source map JSON or trace JSON. But, they didn't implement the `NeedData` response, so it only supported very primitive inner content sources.
This PR extracts that knowledge into a single `WrappedContentSource`, which will recursively wrap every `ContentSourceResult` until we land on a fully resolved …
> Support NeedData responses in SourceMap/SourceMapTrace ContentSources

- crates/next-core/src/next_client/context.rs
- crates/next-core/src/next_edge/context.rs
- crates/next-core/src/next_server/context.rs
it currently breaks because it imports `crypto` in edge environment which isn't allowed.
We need to fix this properly eventually...
> disable bloom filter for now

- docs/pages/pack/docs/features/_meta.json
- docs/pages/pack/docs/features/customizing-turbopack.mdx
- docs/pages/pack/docs/migrating-from-webpack.mdx
This restores documentation for webpack loaders and resolve aliases under a new page, "Customizing Turbopack". This page is now linked to under a new section in "Migrating from Webpack".
**Do not merge until Next 13.2 lands**
> docs: Restore webpack loader documentation under "Customizing Turbopack"

- packages/turbo-utils/package.json
- packages/turbo-utils/tsup.config.ts
- pnpm-lock.yaml
Now that we're throwing a few more things in turbo-utils, we should bundle it to esm instead of cjs to support code splitting. This is an internal package, and everything that consumes this bundles to cjs, so compatibility isn't an issue, and this will ensure each package that uses a util from turbo-utils only gets what it needs instead of the entire package.
I tested this locally to see the bundle size difference. 
For turbo-ignore, the bundle size drops from `245K` to `229K`. No _huge_ (~6%) but worth it.
> feat(turbo-utils): bundle to esm (#3952

- docs/pages/repo/docs/getting-started/existing-monorepo.mdx
With the improvements to dependOn, it seems to be that this is the new best practice and not having the order defined in the `npx turbo run ...`
This would make it easier for new adopters how to structure their turborepo project
> Update getting started to depend on turbo.json for order

- docs/components/pages/landing/index.module.css
**Context:**
A typographical error in a css property resulted in extraneous css.
**Action:**
This commit removes the property in question for housekeeping the style sheet.
Even if correct, I believe the property would have had no effect on rendering or side effect with run-time style modification.  The property has a value of `0` and is not marked important.
**Alternatives at discretion of maintainers:**
- Fix the typo `transfom` -> `transform`. 
This alternative was tested locally and had no effect on document render at each of the project's breakpoints in Chrome, Firefox, and Safari (latest releases 26FEB2023), but was not tested on other browsers or mobile.  I selected the removal option as a result of this incomplete testing.
**Versioning / Stability / Urgency:**
Does not address …
> Remove non-functional css property

- cli/internal/fs/turbo_json.go
- cli/internal/prune/prune.go
Fixes #3645
Before #3216 we would ignore if `turbo.json` wasn't present. This PR restores that behavior by ignoring "not exists" errors.
Note: this is a slight UI change as we're now wrapping the not found error so we can match against it:
Previous:
` ERROR  failed to read turbo.json: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: file does not exist`
New:
` ERROR  failed to read turbo.json: Could not find turbo.json. Follow directions at https://turbo.build/repo/docs to create one: Could not find turbo.json: file does not exist`
> fix: support prune without turbo.json

- .github/CODEOWNERS
Similar to Cargo.lock changes, remove owners from pnpm-lock to avoid unnecessary tags
> chore(owners): remove pnpm-lock.yaml

- .github/CODEOWNERS
- .github/actions/next-integration-stat/index.js
- .github/actions/next-integration-stat/src/index.ts
- .github/workflows/daily-nextjs-integration-test.yml
- .github/workflows/nextjs-integration-test.yml
This PR switches daily next.js integration test to use latest default branch (canary) instead of specific published version.
> ci(workflow): daily next.js test runs against default branch

- cli/combined-release.yml
- cli/combined-shim.yml
- cli/cross-release.yml
- cli/darwin-release.yml
This enables the 'go sandwich' by flipping the go tag in our release pipeline.
> enable rust codepath in release process

- cli/turbo.json
Inputs are relative to workspace and not repo root so we need to drop the `cli` prefix here. I removed the `shim/**` input as that directory no longer exists and to correctly capture these inputs we should Turbo-fy our crates instead of listing out all of the directories out here. Also, I'm not sure how we feel about a task depending on a file outside of the workspace.
Test plan:
```
pnpm -- turbo run e2e --filter=cli
echo "console.log('big change')" >> cli/scripts/e2e/e2e.ts
pnpm -- turbo run e2e --filter=cli
```
should no longer produce a cache hit on the second run
> fix: make inputs relative to workspace root

- examples/with-prisma/apps/web/pages/api/users.ts
- examples/with-prisma/packages/database/src/client.ts
The prisma example currently exports the variable `client` but it should be `prisma`.
`database:db:seed: ReferenceError: prisma is not defined`
> fix prisma example ReferenceError

- docs/pages/repo/docs/_meta.json
Based on recent feedback in discord (come hang! https://turbo.build/discord) we're moving the reference (api and cli docs) up in the sidebar to help with discoverability.
> feat(docs): move reference up in priority (#4007

- docs/components/pages/repo-home/RepoHero.tsx
The "Get Started" CTA's were slightly different on /pack vs /repo. This updates them to be consistent.
> fix(docs): consistent cta sizes on pack & repo

- crates/next-core/js/src/overlay/internal/container/RuntimeError.tsx
Partially resolves WEB-671.
There are some test cases use `data-nextjs-dialog-header` to lookup its inner text to verify error output. Due to differences of error overlay layout between turbopack / next-dev, those 2 have different inner texts.
PR applies a workaround, by introducing new data tag `data-nextjs-turbo-dialog-body`. Next.js upstream will need following update to utilize this tag in its test suites.
> feat(overlay): apply data-* header for the error desc

- cli/turbo.json
The ❌ on formatting probably got lost in the other expected ❌
> Fix prettier

- packages/turbo/node-platform.js
This function missed the ride when we ported it over. This should give us a better error message when we encounter a installation on the wrong platform.
Here is the invocation on `main` of the nonexistent function:
https://github.com/vercel/turbo/blob/main/packages/turbo/node-platform.js#L88
> Add missing function from port.

- cli/integration_tests/basic_monorepo/verbosity.t
- cli/internal/graph/graph.go
- cli/internal/nodes/packagetask.go
- cli/internal/run/dry_run.go
- cli/internal/run/real_run.go
We want to calculate this earlier, because it has some important side effects such as gathering the hashable inputs, etc. By moving this up the chain, we can ensure that more information is available for run summary and dry run summary in a consistent way.
1. https://github.com/vercel/turbo/pull/4016 (this one)
2. https://github.com/vercel/turbo/pull/4021
3. https://github.com/vercel/turbo/pull/4020
`cd cli && make integration-tests`
> Calculate TaskHash while constructing PackageTask

- Cargo.lock
- Cargo.toml
- crates/turbopack-dev-server/Cargo.toml
- crates/turbopack-dev-server/src/http.rs
Implements WEB-666.
This PR enables gzip compressions for the responses by default. This can be extended to other compression method (i.e brotli), but for now implements minimal default compression only to pass existing test case.
Fixes `test/integration/compression/test/index.test.js`.
> feat(devserver/http): support gzipped responses

- crates/next-core/src/next_route_matcher/path_regex.rs
Closes WEB-674
if a matcher tries to split path have a slash like `/x/y`, split gives a redundant empty segment `["", 'x', 'y']`.
> fix(route_matcher): do not include empty segment

- crates/turbo-tasks-macros/src/derive/value_debug_format_macro.rs
It's annoying to debug when the whole dbg will throw an error if any nested Vc is in error state.
Instead we want to print the errors here.
[X] Auto label
> debug print errors for nested vcs

- crates/next-core/src/next_config.rs
- crates/next-core/src/router.rs
- crates/next-dev/src/lib.rs
- crates/turbo-tasks/src/completion.rs
- crates/turbopack-core/src/changed.rs
- crates/turbopack-core/src/issue/mod.rs
- crates/turbopack-core/src/lib.rs
- crates/turbopack-dev-server/src/http.rs
- crates/turbopack-node/src/lib.rs
- crates/turbopack-node/src/transforms/postcss.rs
* use completions to signal additional invalidations for evaluation
* avoid adding these modules as runtime entries, since that will unnecessarily code generate, bundle and execute these modules
* gets rid of the watch_files_hack
* change postcss.config, next.config.js, etc. -> changes will be reflected by the app and process restarts
> avoid bundling and execution of modules just of watching

- crates/next-dev/src/lib.rs
All issues from `source` are already handled here: https://github.com/vercel/turbo/blob/24801f42c4a5249854d05f3cc788e7d9a3291796/crates/turbopack-dev-server/src/lib.rs#L168
So no need to handle them multiple times
> Only handle issues in dev server

- crates/node-file-trace/src/lib.rs
- crates/node-file-trace/src/main.rs
- crates/turbopack/src/module_options/module_options_context.rs
- crates/turbopack/src/resolve_options_context.rs
This pr allows passing `ModuleOptionsContext` and `ResolveOptionsContext` in fn start, so next.js can pass enableJsx: true, enableTypes: true while tracing entries, and `enableJsx: false`, `enableTypes: false` while tracing compiled files.
> Expose module_options and resolve_options in turbotrace

- cli/cmd/turbo/main.go
- cli/go.mod
- cli/go.sum
- cli/integration_tests/no_args.t
- cli/integration_tests/turbo_help.t
- cli/internal/cache/cache.go
- cli/internal/client/client.go
- cli/internal/cmd/root.go
- cli/internal/cmdutil/cmdutil.go
- cli/internal/cmdutil/cmdutil_test.go
- cli/internal/config/config_file.go
- cli/internal/config/config_file_test.go
- cli/internal/daemon/lifecycle.go
- cli/internal/run/run.go
- cli/internal/run/run_spec.go
- cli/internal/turbostate/turbostate.go
- cli/internal/util/parse_concurrency.go
- crates/turborepo-lib/src/cli.rs
- crates/turborepo-lib/src/client.rs
- crates/turborepo-lib/src/commands/link.rs
- crates/turborepo-lib/src/commands/login.rs
- crates/turborepo-lib/src/commands/mod.rs
- crates/turborepo-lib/src/config/client.rs
- crates/turborepo-lib/src/config/mod.rs
This commit authored in part by @tm1000.
Closes #1993
Closes #2096
Closes #2428
Notes:
- You may want to look at the original diff: https://github.com/vercel/turbo/pull/2428/files?w=1
- I've completely removed `pflag` at this point. It was only being used in tests.
- I've added a new "config" in Rust land, for the API client. It only accepts `timeout` right now.
> Client timeout

- cli/combined-release.yml
- cli/combined-shim.yml
- cli/cross-release.yml
- cli/darwin-release.yml
Reverts vercel/turbo#3903
Flag rust library off until we sort out compatibility issues
> Revert "enable rust codepath in release process"

- crates/next-dev-tests/tests/integration/next/basic/swc-helpers/input/pages/index.js
- crates/turbopack-ecmascript/src/parse.rs
- crates/turbopack-tests/tests/snapshot/swc_transforms/preset_env/output/79fb1_turbopack-tests_tests_snapshot_swc_transforms_preset_env_input_index_097653.js
- crates/turbopack-tests/tests/snapshot/swc_transforms/preset_env/output/79fb1_turbopack-tests_tests_snapshot_swc_transforms_preset_env_input_index_097653.js.map
This fixed the `_extends` is not defined issue.
> inject swc helpers

- crates/next-core/src/next_config.rs
Ensures `target` is optional to match #46801 which removes the option.
> Make  in next.config.js optional

- .github/workflows/nextjs-integration-test.yml
- .github/workflows/setup-nextjs-build.yml
This PR is workaround for WEB-679. Since most of perf bottleneck comes from bind-mounted host volume to the container, PR changes it to use named volume without bind to the host. 
Note this is a stopgap workaround, not a fix for the issue.
> ci(workflow): use named volume mount for the next.js tests

- crates/node-file-trace/src/lib.rs
- crates/turbo-tasks-fs/src/attach.rs
- crates/turbo-tasks-fs/src/embed/fs.rs
- crates/turbo-tasks-fs/src/lib.rs
- crates/turbopack-core/src/server_fs.rs
- crates/turbopack-node/src/evaluate.rs
This PR reduces the our total memory usage (hopefully) for files that we write to disk.
When we write a file, we obviously have the input bytes (the bytes we want to write to disk). But we also read the file to see if the file needs to be written at all. This means we have _another_ copy of the bytes, the ones that came from the disk.
Worse, our write is strongly dependent on the read's `RopeVc`. Meaning we're stuck with that read memory until some indeterminate time. And any time we update the written contents, we're gonna get more bytes stuck in our Vc cache.
The goal here is to track the file, so that we can rewrite it if it's modified/deleted. Why not have an API specific to tracking, without actually reading any contents? This PR does exactly that. And now that we don't need to read …
> Reduce memory usage when writing files

- Cargo.lock
- crates/next-core/src/app_source.rs
- crates/next-core/src/page_source.rs
- crates/turbopack-node/Cargo.toml
- crates/turbopack-node/src/lib.rs
The isolation is unnecessary and we can reuse files when we share directories
Open multiple pages without client-side navigation in multiple tabs concurrently.
> place all pages in the same intermediate output directory

- crates/next-binding/Cargo.toml
- crates/next-dev-tests/Cargo.toml
Cargo always uses default features for workspace dependencies, so we can't use that here. See also comment.
```
$ cargo tree -p next-binding -i openssl --target x86_64-unknown-linux-gnu -e features
error: package ID specification `openssl` did not match any packages
```
> revert workspace dependency to allow building correctly

- Cargo.lock
- crates/turbo-tasks-fs/Cargo.toml
- crates/turbo-tasks-fs/src/lib.rs
Only windows and macOS support real recursive file watchers, other OS emulate it by walking the directory structure and watching all directories. But that might be really slow and use up a lot of watchers, so we don't want that. Instead we know exactly which directories are used and can watch selectively directories when they are accessed.
* only use recursive watchers on macOS and windows
* fallback to non-recursively watch read directories on other OS
Note that this implementation still has some bugs when renaming folders, but we can probably figure out these edge cases later...
> only use recursive watchers on macOS and windows
