vercel/turborepo

crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/opts.rs, turborepo-tests/integration/tests/run/one-script-error.t
- Mimic the command failure error line from Go. Not a long-term solution, but causes less thrash now
- Fix passthrough args to not append `--` if there are no args
- Allow optionally matching on the full path to the package manager that we run
- Updated integration test to allow matching on the full path to the relevant package manager
Closes TURBO-1647
=> port(Turborepo): Add summary error to match Go

turborepo-tests/integration/tests/task-dependencies/complex.t, turborepo-tests/integration/tests/task-dependencies/workspace-tasks.t
- switch to grep for error matching in task dependencies integration tests
- Updated integration tests to use error matching via `grep`
Closes TURBO-1648
=> port(Turborepo): Fix task dependencies integration tests

crates/turborepo-repository/src/package_json.rs
In Go we create the set of external deps by merging `devDependencies`, `optionalDependencies`, and `dependencies` [in that order](https://github.com/vercel/turbo/blob/main/cli/internal/context/context.go#L238). This PR changes the Rust code to use the same order. 
One might say that this order shouldn't matter and they would be right, but this is a [2yr old bug](https://github.com/vercel/turbo/commit/6077c5e4894f4fa0a95b01d5cc8f3f103a227b8b) and fixing it would require changing the FFI layer. Fixing this should be a post-port effort.
`turbo_dev build --filter='@turbo/codemod'` now passes
Closes TURBO-1654
=> fix: match dependency ordering between rust/go

crates/turborepo-lib/src/run/cache.rs
We were early exiting the `save_outputs` function when `reads_disabled` was true, not when `writes_disabled` was true
Closes TURBO-1656
=> fix: `--no-cache` flag was not working

crates/turborepo-lib/src/run/mod.rs
Makes failure to start or connect to the daemon non-fatal. It's purely a performance optimization and we can still execute without it.
Verified manually with a 1ms timeout
Closes TURBO-1655
=> Ensure daemon connection errors are non-fatal

crates/turborepo-lib/src/run/summary/execution.rs
Reworked our duration display to be closer to the Go implementation. Also swapped the error field order to match Go.
Closes TURBO-1664
=> fix: Cleaning up duration printing

crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/task_graph/visitor.rs, turborepo-tests/integration/tests/run-logging/errors-only.t, turborepo-tests/integration/tests/run/continue.t
This PR fixes up our `errors-only` behavior by making sure we flush the file writer by the time we attempt to replay the logs.
`run-logging/errors-only.t` and `run/continue.t` now both pass
Closes TURBO-1663
=> fix: displaying stdout/stderr with errors-only

crates/turborepo-lib/src/run/mod.rs, turborepo-tests/integration/tests/inference/has-workspaces.t, turborepo-tests/integration/tests/inference/nested-workspaces.t, turborepo-tests/integration/tests/inference/no-workspaces.t
- Drop two instances of "cache created" info-level log lines
- Migrate the inference integration tests to use `grep` and match on relevant lines
Updated tests
Closes TURBO-1639
=> port(Turborepo): Migrate inference tests to grep

crates/turborepo-analytics/src/lib.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/fs.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/summary/spaces.rs
Fix our too strict requirement on the presence of `team_id` for making API calls. We don't have this requirement in Go and instead have the `IsLinked` method that checks that one of them is present. This is used in exactly 2 places [spaces](https://github.com/vercel/turbo/blob/main/cli/internal/runsummary/spaces.go#L71) and [analytics](https://github.com/vercel/turbo/blob/main/cli/internal/run/run.go#L440) to check if there's some way of identifying the team. In this PR we port this behavior from Go.
One thing to note is that this also gets us to parity of the Go behavior for the HTTP cache (whether it's desired is another question). There's no requirement that `team_id` is non-empty when constructing the HTTP cache artifact signer: …
=> fix: rust spaces auth requirements

turborepo-tests/integration/tests/command-bin.t
Adds a quick test for `turbo bin` extracted from https://github.com/vercel/turbo/pull/6279
Closes TURBO-1668
=> chore: add test for turbo bin

turborepo-tests/integration/tests/inference/has-workspaces.t, turborepo-tests/integration/tests/inference/nested-workspaces.t
This is a follow up from #6437.
Using --quiet means we can avoid duplicating the same string twice and rely on the exit code to indicate a match, also making the path matching simpler for Windows (https://github.com/vercel/turbo/pull/6279). The change to not use `cat` is to just follow the pattern from #6400.
=> chore: simplify inference test grep commands

crates/turborepo-lib/src/tracing.rs, turborepo-tests/integration/tests/command-bin.t, turborepo-tests/integration/tests/find-turbo/hard-mode.t, turborepo-tests/integration/tests/find-turbo/hoisted.t, turborepo-tests/integration/tests/find-turbo/linked.t, turborepo-tests/integration/tests/find-turbo/nested.t, turborepo-tests/integration/tests/find-turbo/self.t, turborepo-tests/integration/tests/find-turbo/unplugged-env-moved.t, turborepo-tests/integration/tests/find-turbo/unplugged-moved.t, turborepo-tests/integration/tests/find-turbo/unplugged.t
- Configure our terminal logger to go to `stderr`. Note some hacking around type constraints on a `Layer`, the end result is we call `std::io::stderr()` to get the writer for the log layer.
Updated integration tests to expect output on `stderr`
Closes TURBO-1652
=> feat(Turborepo): Send logging to stderr

turborepo-tests/integration/tests/run/missing-tasks.t
A combination of regex magic and `grep` to ensure we have the relevant error strings in both implementations.
Updated `missing-tasks.t`
Closes TURBO-1646
=> fix(Turborepo): Update missing-tasks.t to pass with Rust

cli/internal/run/run.go, crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/run/mod.rs, turborepo-tests/integration/tests/run-logging/verbosity.t
- drop skipping daemon log message to debug
- switch rust process manager logging to debug
- switch highest verbosity settings to just check that we print out `DEBUG`
Closes TURBO-1642
=> fix(Turborepo): Make verbosity test pass with Rust

turborepo-tests/integration/package.json, turborepo-tests/integration/setup.sh, turborepo-tests/integration/test-interactive.sh, turborepo-tests/integration/test.mjs, turborepo-tests/integration/test.sh, turborepo-tests/integration/turbo.json
We need to encode some Windows-specific logic when launching these tests
and it's easier to do it in JS than bash (although technically feasible to do it in Bash). 
JS launcher also lets us apply tooling like linting/formatting that we don't have setup for bash.
The main drawback is that that this will launching prysk in yet another subprocess rather than
sourcing a bash script in the same process.
Closes TURBO-1675
=> chore(ci): launch prysk tests with JS instead of bash

.github/CODEOWNERS
Add @anthonyshew as an explicit owner of `examples/`
N/A
Closes TURBO-1679
=> chore(Turborepo): Add Anthony as an explicit owner of examples

turborepo-tests/integration/tests/_fixtures/ordered/packages/util/package.json, turborepo-tests/integration/tests/ordered/github.t
Similar to 81c04cba6691f4e985f9a835730cd87b3345f3de and ee7147710
Closes TURBO-1678
=> chore(test): remove another single quoted echo arg

crates/turborepo-cache/src/async_cache.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/summary/task.rs, crates/turborepo-lib/src/task_graph/visitor.rs, turborepo-tests/integration/tests/run-logging/verbosity.t
We need to check the cache so the cache metadata is in the task hash tracker. This lets us produce the correct cache data for dry run
Closes TURBO-1677
=> fix: Check cache on dry run

turborepo-tests/integration/tests/dry-json/monorepo.t
Use regex magic to allow both Go and Rust error strings
Updated test now passes with Rust
Closes TURBO-1638
=> fix(Turborepo): Fix dry-json/monorepo.t

.github/workflows/test.yml
I realized I forgot to move e2e to use bash instead of powershell as I did with the other windows jobs in #6449
This is causing the network failures on PRs e.g. https://github.com/vercel/turbo/actions/runs/6885178823/job/18729263113?pr=6473#step:4:24
e2e windows tests should pass on this PR
Closes TURBO-1683
=> fix: move e2e to use bash to match other jobs

crates/turborepo-cache/src/async_cache.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/task_graph/visitor.rs
https://github.com/vercel/turbo/pull/6466 broke `test/edit-turbo-json/task.t` as it moved the dry run execution to happen after we early exit when commands don't exist.
This PR moves the branching to happen before the early exit and avoids performing some of the work that's necessary for a real run, but unneeded for dry run. I don't love the level of nesting in the `visit` function, but it'll do for now.
`tests/edit-turbo-json/task.t` now passes on the Rust codepath.
Closes TURBO-1682
=> fix: dry run missing tasks with no script

docs/theme.config.tsx
| before | after |
|--------|--------|
|![CleanShot 2023-11-16 at 01 42 16@2x](https://github.com/vercel/turbo/assets/490968/4e215dc4-54bb-4906-b85e-ecef1273a676)| ![CleanShot 2023-11-16 at 01 42 02@2x](https://github.com/vercel/turbo/assets/490968/b741ce96-7b19-4eaf-b0bd-2fe1c2458457)
Closes TURBO-1687
=> fix(docs): change default collapse level of sidebar

.github/workflows/bench-turbotrace-against-node-nft.yml, .github/workflows/test.yml
Closes PACK-1969
CI was failing to run turbopack tests with obscure error message
```
binding) ignoring invalid dependency `turbopack-tests` which is missing a lib target
error: error parsing Cargo metadata
Caused by:
failed to construct package graph: for package 'preset_env_base 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)': no dependencies found matching 'browserslist'
```
Tried a bunch of bisect, and finally able to figure out the dependency chain
- `cargo-nextest` releases a new version, which was a culprit of above bug
- `install-action` silently installs new version 
- CI started to fail all of sudden without any repo / user level code changes
Cargo's executable won't update unless explicitly specified, so this was not reproducible locally with currently installed …
=> ci(action): pin nextest

crates/turborepo-lib/src/task_hash.rs
Powershell populates `PATH` and `SYSTEMROOT` as `Path` and `SystemRoot` causing our wildcarding to miss. These are valid populations as Windows has case-insensitive environment variables. In both Go and Rust we were explicit and forwarded `SYSTEMROOT`, but this failed on Powershell as our wildcard matching is case sensitive. The Go standard library papered over this failure since it [passes `SYSTEMROOT` for us if we don't set it](https://pkg.go.dev/os/exec#Cmd):
> As a special case on Windows, SYSTEMROOT is always added if missing and not explicitly set to the empty string.
Future work will be to investigate if we should make our environment variable matching case insensitive on Windows to better match how Windows thinks about environment variables.
Make a repository with the following …
=> fix: forward powershell style env casing

crates/turbopack-core/src/chunk/mod.rs, crates/turbopack-ecmascript/src/references/amd.rs, crates/turbopack-ecmascript/src/references/cjs.rs, crates/turbopack-ecmascript/src/references/esm/dynamic.rs, crates/turbopack-ecmascript/src/references/pattern_mapping.rs, crates/turbopack-ecmascript/src/references/require_context.rs
When chunk loading is disable, dynamic imports will just bundle all referenced modules instead of created in separate chunk group
Closes PACK-1984
=> handle dynamic imports when chunk loading is disabled

Cargo.lock, Cargo.toml, crates/turbopack-cli/src/contexts.rs, crates/turbopack-core/src/issue/mod.rs, crates/turbopack-css/Cargo.toml, crates/turbopack-css/src/asset.rs, crates/turbopack-css/src/module_asset.rs, crates/turbopack-css/src/parse.rs, crates/turbopack-css/src/process.rs, crates/turbopack-css/src/references/import.rs, crates/turbopack-css/src/references/mod.rs, crates/turbopack-css/src/references/url.rs, crates/turbopack-ecmascript-plugins/src/transform/styled_jsx.rs, crates/turbopack-ecmascript/src/resolve/mod.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_options_context.rs, crates/turbopack/src/module_options/module_rule.rs
To make WIPs small, I'm putting ligtningcss as a mode.
x-ref: https://vercel.slack.com/archives/C03EWR7LGEN/p1700025496732229?thread_ts=1700019629.866549&cid=C03EWR7LGEN
Closes PACK-1965
=> refactor: Add lightningcss mode for `turbopack-css`

.github/workflows/test.yml
With #6485 merged we should now be able to use the default shell on the Windows Runner
CI on Windows should pass now
Closes TURBO-1699
=> chore: move back to powershell on windows

cli/internal/packagemanager/packagemanager_test.go, crates/turborepo-repository/src/package_manager/mod.rs
We use the basic example as a test fixture for some of our unit tests.
Rust unit test has some changes that makes any diffs between expected and actual display better.
Future work is to use a non-example fixture so we can avoid breakages like these and we don't need to run all unit tests whenever we change an example.
Rust and Go unit tests should pass on this PR
Closes TURBO-1724
=> fix: fixup unit tests that use the basic example

crates/turbopack/src/module_options/mod.rs
Previously we only applied postcss to CSS files (not CSS modules) that were imported from javascript.
This PR makes sure the source transform gets applied to all CSS files.
=> fix(turbopack): postcss should be applied to `@import`ed CSS files

crates/turborepo-lib/src/run/summary/spaces.rs
Realized that we were sending spaces requests serially and on a `>>> FULL TURBO` run this was very noticeable as sending the summaries took longer than restoring from cache.
`EXPERIMENTAL_RUST_CODEPATH=true turbo_dev build --filter=docs --output-logs=none -vv`
Before:
```
2023-11-21T11:57:59.278-0800 [DEBUG] turborepo_lib::run::summary::spaces: created run: SpaceRun { id: "space_run_xTnqFacHOWXEGCTV1lHGPhJR", url: "https://vercel.com/teams/vercel/repos/turbo-monorepo/runs/space_run_xTnqFacHOWXEGCTV1lHGPhJR" }
2023-11-21T11:57:59.278-0800 [DEBUG] turborepo_lib::run::summary::spaces: sending task: SpaceTaskSummary { key: "docs#schema", name: "schema", workspace: "docs", hash: "46782ac6b6dc082a", start_time: 1700596678433, end_time: 1700596678441, cache: SpacesCacheStatus { status: Hit, …
```
=> fix: make spaces requests in parallel

.github/workflows/test.yml
Setting up `graphviz` for macos on CI has been flakey. It seems it fails when it tries to upgrade some existing packages on the runner.
[Successful run](https://github.com/vercel/turbo/actions/runs/6947834378/job/18904625583#step:4:84): Note that only `brew install graphviz` gets executed as part of the action
[Failed run](https://github.com/vercel/turbo/actions/runs/6949330954/job/18907649525#step:4:266): Note that homebrew tries to update python for us which we do not want.
We can opt out of this twofold:
- Skip the initial `brew update` performed by the [`setup-graphviz` action](https://github.com/marketplace/actions/setup-graphviz)
- Skip upgrading unrelated packages on the `brew install graphviz` by using the `https://docs.brew.sh/Manpage#install-options-formulacask-` environment …
=> fix: avoid upgrading outdated packages on GH actions

cli/internal/turbodprotocol/turbod.proto, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/mod.rs, crates/turborepo-lib/src/daemon/server.rs
This change is backwards compatible, since we set the starting version of the daemon protocol to be equal to the current turbo version meaning we will not get any clashes with old clients reporting a bad version. Even though the version is currently equal to the turbo version, it is not expected to always be the case.
If we want to allow other tools to interact with the turbo daemon, we should not be as strict with our versioning. As it stands, a 3rd party tool such as an LSP would need to perfectly match the version of turbo used in the repo which is an unreasonable constraint.
This also relaxes the version requirement for all _new_ versions to least the same minor version (ie. that all the features available to the client are implemented by the server). Old clients will still demand …
=> refactor: switch daemon version to be independent of turbo version

crates/turborepo-analytics/src/lib.rs
This PR primarily fixes an issue where the worker would spin if all senders were closed. Since the `select` was biased, if `self.rx.recv()` was ready then it would always be chosen. In the case that all senders are dropped, this future will always be ready with a `None` message. Solution is to just shutdown if there aren't going to be any other messages.
Other fixes:
- Joining the senders as they finish instead of an arbitrary order and then waiting for whichever one we got to finish
- Using the 20ms timeout before we send events if there's still room in the batch as opposed to 10s
The unit test for closing now exercises realistic usage of the analytics client. If you checkout the first commit, the test will fail without the fix now.
Closes TURBO-1736
=> fix: analytics closing when all senders drop

crates/turbopack-core/src/environment.rs, crates/turbopack-ecmascript/src/references/esm/base.rs, crates/turbopack/src/resolve.rs, crates/turbopack/src/resolve_options_context.rs
Some edge runtimes allow additional node.js builtins
Closes PACK-2030
=> add enable_edge_node_externals

turborepo-tests/e2e/index.ts, turborepo-tests/e2e/monorepo.ts
This behavior is covered by turborepo-tests/integration/tests/inference/ where we expect that turbo can run tasks when turbo.json and package.json roots in a subdirectory of a repo
Closes TURBO-1742
=> chore(ci): delete e2e tests covering monorepo root in subdir

examples/basic/README.md, examples/basic/package.json, examples/basic/pnpm-lock.yaml
=> Set engine on create-turbo.

crates/turborepo-lib/src/task_graph/visitor.rs
In Go we would skip running a task if the [`packageJson[taskName] == ""`](https://github.com/vercel/turbo/blob/main/cli/internal/run/real_run.go#L412) which is true for both when there's no script definition *and* when there's an empty string as the script definition.
To match the Go behavior in Rust we skip a task if `package_json.scripts.get(task_name)` is `None` or `Some("")`
`vercel-site#prepare-dev` should no longer be run via `turbo prepare-dev --filter=vercel-site`
Before
```
...
vercel-site:prepare-dev: ERROR: command finished with error: command (/Users/olszewski/code/vercel/front/apps/vercel-site) /Users/olszewski/.nvm/versions/node/v16.18.1/bin/pnpm run prepare-dev exited (1)
vercel-site#prepare-dev: command (/Users/olszewski/code/vercel/front/apps/vercel-site) …
```
=> fix: treat missing and empty scripts the same

Cargo.lock, Cargo.toml, crates/turbopack-ecmascript-plugins/src/transform/styled_components.rs
Update swc crates.
Diff: https://github.com/swc-project/swc/compare/09b3003e589409e1fffe32cf5e3328d946bd270e...c566b73bfbcd24fc34eedc2baf62d0afb8609636
Let's look at the CI of next.js
next.js counterpart: https://github.com/vercel/next.js/pull/58517
Closes PACK-1973
=> Update `swc_core` to `v0.86.81`

crates/turbopack-bench/src/bundlers/nextjs/next.config.js
This should make the benchmarks run again
Closes PACK-2041
=> fix(turbopack-bench): remove outdated `experimental.appDir` from next.config.js

docs/pages/repo/docs/reference/command-line-reference/bin.mdx, docs/pages/repo/docs/reference/command-line-reference/gen.mdx, docs/pages/repo/docs/reference/command-line-reference/link.mdx, docs/pages/repo/docs/reference/command-line-reference/login.mdx, docs/pages/repo/docs/reference/command-line-reference/logout.mdx, docs/pages/repo/docs/reference/command-line-reference/prune.mdx, docs/pages/repo/docs/reference/command-line-reference/run.mdx, docs/pages/repo/docs/reference/command-line-reference/unlink.mdx
I originally added these, but I think they look kind of bad now
Closes TURBO-1746
=> chore(docs): remove backticks from title/desc meta tags on CLI reference pages

docs/pages/repo/docs/support.mdx
Now that all our examples are being updated by the Great @anthonyshew and we're adding `engines`, I wanted to document this explicitly. We can cover the actual testing/validation gap as we iterate on our test suites
Closes TURBO-1747
=> feat(docs): add node version compatibility for examples

docs/pages/repo/docs/reference/command-line-reference/gen.mdx, docs/pages/repo/docs/reference/command-line-reference/link.mdx, docs/pages/repo/docs/reference/command-line-reference/logout.mdx, docs/pages/repo/docs/reference/command-line-reference/prune.mdx, docs/pages/repo/docs/reference/command-line-reference/unlink.mdx
Quick fix for inconsistent docs headings.
These should all be top level `#`, but a few of them are still `##` from when these used to be on page. As a result the top heading jumps around a bit if you click between them all quickly (font sizing and padding changes). This fixes that by making them all `h1`
Closes TURBO-1755
=> fix(docs): update inconsistent CLI headings

.github/workflows/test.yml
This setup step was added in #6490, and since Windows is a different job we need to copy it over
Closes TURBO-1754
=> chore(tests): setup graphviz before running tests

.github/workflows/test.yml
Windows tests are regularly exceeding 30 mins. We can monitor these instead of setting a hard limit that isn't enough time for the actual test suite.
Closes TURBO-1766
=> chore(ci): remove limited timeout for test jobs

crates/turborepo/build.rs, package.json
Ignores the error code on the rustdoc build because we have the `--keep-going` flag set. Also skips the Go binary build for docs
Closes TURBO-1767
=> docs: Fix rustdoc build

crates/turbopack-mdx/src/lib.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/module_rule.rs
Context: https://github.com/vercel/next.js/pull/58968
MDX is a special variant of an ecma|typescript asset in turbopack, once transform is completed (which makes mdx into jsx component) it is a plain ecma script asset can apply the other transforms.
PR enables those transform check condition to the mdx. 
In the end it is better to make mdx as just an ecmascript asset with source transforms, but as noted in comments its ast is incompatible with source transform in ecmascript so we have separate asset for now.
=> fix(mdx): support ecma transforms for the mdx assets

crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/multiplexer.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs, turborepo-tests/integration/tests/run-caching/remote-caching-enable.t
This PR contains intertwined changes:
- Waiting on all cache writes to finish before we exit the run. We leverage the signal handler here so we can make sure we wait regardless of how/why the run exits.
- Printing errors from artifact upload failures. This differs from Go where we [throw generated errors away](https://github.com/vercel/turbo/blob/main/cli/internal/cache/async_cache.go#L79C12-L79C12) (I'm not sure this is desired since we do [format these errors for human consumption](https://github.com/vercel/turbo/blob/main/cli/internal/client/cache.go#L70))
- Correctly deserialize Vercel API errors. As per the [docs](https://vercel.com/docs/rest-api/errors) there's a containing object with an `error` field that has the information.
- Pass team information when saving artifacts. This …
=> fix: ensure cache is done writing before exit

examples-tests/npm-non-monorepo/test.t, examples-tests/npm-with-npm/test.t, examples-tests/npm-with-yarn/test.t, examples-tests/pnpm-basic/test.t, examples-tests/pnpm-gatsby/test.t, examples-tests/pnpm-kitchen-sink/test.t, examples-tests/pnpm-with-svelte/test.t, examples-tests/setup.sh, examples-tests/yarn-non-monorepo/test.t, examples-tests/yarn-with-npm/test.t, examples-tests/yarn-with-yarn/test.t
examples now have this field already set, so tests can just validate this
Closes TURBO-1780
=> chore(tests): remove hardcoded packageManager when running examples tests

docs/.eslintrc.js, docs/components/Container.tsx, docs/components/ThemeAwareImage.tsx
Just making my way down the list when I have time. This rule feels a bit silly, but I don't want to debate the rule itself, just get our accepted ruleset passing.
Closes TURBO-1773
=> chore(lint): fix @typescript-eslint/naming-convention lint violations

docs/pages/repo/docs/faq.mdx
Based on two discussions:
- https://github.com/vercel/turbo/discussions/1077
- https://github.com/vercel/turbo/discussions/1900
Closes TURBO-1778
=> feat(docs): add FAQ entry for non-JS workspaces in the codebase

crates/turborepo-lib/src/run/summary/mod.rs, turborepo-tests/integration/package.json, turborepo-tests/integration/tests/_fixtures/spaces_failure/.gitignore, turborepo-tests/integration/tests/_fixtures/spaces_failure/apps/my-app/package.json, turborepo-tests/integration/tests/_fixtures/spaces_failure/bar.txt, turborepo-tests/integration/tests/_fixtures/spaces_failure/foo.txt, turborepo-tests/integration/tests/_fixtures/spaces_failure/package.json, turborepo-tests/integration/tests/_fixtures/spaces_failure/packages/another/package.json, turborepo-tests/integration/tests/_fixtures/spaces_failure/packages/util/package.json, turborepo-tests/integration/tests/_fixtures/spaces_failure/turbo.json, turborepo-tests/integration/tests/spaces-failure.t
When we fail to start the `SpacesClient`, this can lead to an error when we try to close it at the end of a run. Instead of erroring, we simply log out the error and continue, since spaces is not critical to execution.
Added a test for spaces failure that ensures we exit with 0
Closes TURBO-1764
=> fix: Hard error on spaces

crates/turborepo-lib/src/run/global_hash.rs
- escape `:` characters in windows paths when constructing globs for global dependency files. This is a hack to allow compiling a glob that is not going to end up working anyways, and we will eventually error earlier in the stack so that absolute paths don't make it this far.
Added a test that uses absolute paths in global dependencies
Closes TURBO-1749
=> fix(Turborepo): Handle windows absolute paths in global dependencies

crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/lib.rs, crates/turborepo-cache/src/multiplexer.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/opts.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Forking the existing PR of #6326 to see if this helps CI along. See that PR for more detail.
Manual testing:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev build --filter=docs --remote-cache-read-only --force
• Packages in scope: docs
• Running build in 1 packages
• Remote caching enabled
docs:rss: cache bypass, force executing 73afc3e91d179e7d
docs:schema: cache bypass, force executing 1783946761b14ceb
@turbo/workspaces:build: cache bypass, force executing a31c222598c45c9a
docs:schema:  WARN  Unsupported engine: wanted: {"node":"20.x"} (current: {"node":"v16.18.1","pnpm":"8.9.0"})
@turbo/workspaces:build:
@turbo/workspaces:build: > @turbo/workspaces@1.10.17-canary.6 build /Users/olszewski/code/vercel/turborepo/packages/turbo-workspaces …
```
=> feat: add read only remote cache

.github/workflows/test.yml
This only applies to the Go codepath. The Rust codepath Windows tests will become required when _all_ the Rust codepath tests become required.
Closes TURBO-1789
=> chore(ci): require tests to pass on Windows on PRs

pnpm-lock.yaml
Follow up to https://github.com/vercel/turbo/pull/6632. A couple workspaces were deleted, but we need a `pnpm install` to get them out of the lockfile
Closes TURBO-1796
=> chore: update lockfile after workspace deletion

Cargo.lock, cli/internal/turbodprotocol/turbod.proto, crates/turborepo-filewatch/Cargo.toml, crates/turborepo-filewatch/src/lib.rs, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/mod.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/package_discovery/mod.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lockfiles/src/berry/mod.rs, crates/turborepo-lockfiles/src/bun/mod.rs, crates/turborepo-lockfiles/src/lib.rs, crates/turborepo-lockfiles/src/yarn1/mod.rs, crates/turborepo-repository/Cargo.toml, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/lib.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-repository/src/package_manager/mod.rs
This adds a basic trait for discovering packages (paths to package and turbo jsons) using a variety of strategies:
- **local**: runs in-process and does a recursive walk of the FS
- **watch**: runs a file watching thread maintains a list in memory
- **daemon**: makes a request to a remote service over GRPC
- **timeout**: attempts a primary strategy and falls back in the event of errors or a timeout
This PR still needs some tests for the strategies, but it is ready for a basic look.
There is one integration test for the daemon strategy which requires a daemon to be running. It will be improved when ready to be merged.
Closes TURBO-1530
=> feat: add package discovery trait and a few discovery strategies

crates/turborepo-lib/src/shim.rs
more readable, if tests pass, we'll keep this one
Closes TURBO-1794
=> chore: use parent() method instead of .. directory traversal

.github/workflows/test.yml, turborepo-tests/example-pnpm-basic/test.t, turborepo-tests/example-pnpm-gatsby/test.t, turborepo-tests/example-pnpm-kitchen-sink/test.t, turborepo-tests/example-pnpm-with-svelte/test.t
We're no longer locking to pnpm@6 in our example tests. Instead they are using, the version in the example itself.
Our examples are on pnpm@8. It looks like the pass-through flagging for `pnpm run` has changed.
=> Updating pnpm flags in example tests.

docs/theme.config.tsx
1. `/` goes from `Index - Turbo` to `Turbo`
1. `/repo` goes from `Index - Turborepo` to `Turborepo` 
1. `/pack` goes from `Index - Turbopack` to `Turbopack`
All others remain the same
Closes TURBO-1815
=> fix(docs): improve landing page titles

turborepo-tests/integration/tests/_fixtures/ordered/apps/my-app/package.json, turborepo-tests/integration/tests/_fixtures/ordered/packages/util/package.json, turborepo-tests/integration/tests/run-logging/log-order-github.t, turborepo-tests/integration/tests/run-logging/log-order-grouped.t
This reverts commit 4b07f76c19ff607bed0e85aa0c7cbc2a36d67620.
I think we're flying a little too close to the sun with this one: https://github.com/vercel/turbo/actions/runs/7052873305/job/19199324958?pr=6649#step:7:721
I think the extra <1s when running this test is worth reducing the flakiness.
👀 
Closes TURBO-1821
=> Revert "chore: reduce sleep length in test cases (#6640)"

crates/turbopack-ecmascript/src/analyzer/graph.rs
Minor assertion to ensure eval runs with globals.
Closes PACK-2067
=> fix(ecmascript): dbg assert for the globals

crates/turborepo-repository/src/package_manager/mod.rs
Same as #6679
Unit tests should pass now
Closes TURBO-1839
=> fix(tests): update rust unit tests that rely on with-yarn fixture

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-repository/src/discovery.rs
I noticed that it seems like the daemon workspace discovery isn't functioning properly and it sometimes produces package graphs that are missing some packages resulting in no tasks getting run.
This PR gets us to just use our old behavior and gets rid of the daemon optimization until we can sort this out.
With these changes run `turbo_dev daemon stop && turbo_dev build --filter=docs` in a `create-turbo` repo and verify that a command gets run every time.
Closes TURBO-1841
=> chore(daemon) disable daemon workspace discovery

docs/pages/repo/docs/handbook/workspaces.mdx
yarn v1 uses `*`. yarn v2+ use `workspace:*`.
*audible sigh*
Closes #5261 and #6322
=> Add yarn v2+ caveat for installing Internal Packages.

crates/turbopack-ecmascript-runtime/js/src/dev/runtime/none/runtime-backend-none.ts, crates/turbopack-ecmascript-runtime/js/src/dev/runtime/none/tsconfig.json
Next.js supports injecting WASM files into the edge runtime via the middleware manifest, so we want to be able to support that usecase as well
Closes PACK-2027
=> feat(turbopack): support "loading" WebAssembly injected as global varables in edge runtime

crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Since `--remote-cache-read-only` is only implemented in Rust it should fail when used with `--go-fallback` so users understand that the read only flag won't be respected when using the Go codepath.
Added unit test to make sure the `conflicts_with` attribute behaves as we expect.
Closes TURBO-1848
=> chore: make go-fallback confilct with remote cache read only

.github/ISSUE_TEMPLATE/0-turborepo-bug-report.yml
Title!  If I messed up the `yml`, I can fix-ship it. A little hard to debug given it has to be on `main` for GitHub to render it. 😄 
Much inspiration was taken from the Next.js bug issue template.
=> Upgrade Turborepo bug issue template.

examples/basic/apps/docs/app/page.module.css, examples/basic/apps/docs/app/page.tsx, examples/basic/apps/web/app/page.module.css, examples/basic/apps/web/app/page.tsx, examples/basic/packages/eslint-config/next.js, examples/basic/packages/ui/package.json, examples/basic/packages/ui/src/button.tsx
Previously, the `basic` example (AKA create-turbo) was entirely Server Components. In this PR, we're continuing to leverage the Internal Package pattern such that we have a mix of React Server Components **and** Client components.
The Client Component is the new `Button` component in the `@repo/ui` package.
Notably, this PR closes #6019, fulfilling these requirements:
- A mix of Server Components and Client Components
- Editor go-to-definition across packages (already done in previous work)
- Using an `src` folder in the package but not having to use it when importing into another package
- Tree-shaking (already done in previous work, check out `exports` in `./packages/ui.package.json`
Non-goals of this PR:
- Including the entirety of `shadcn-ui` (We're showing you the fundamentals of how …
=> Mix of server and client components in basic example.

docs/pages/blog/turbo-1-11-0.mdx
The npm API is pulling 2.2M today but we want to align the number with what comes up on npm.com because that's what folks use to look themselves. 😄
=> Update to align with npm.com.

crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/error.rs, crates/turborepo-lib/src/signal.rs
Global `turbo` sends a `SIGTERM` to local `turbo` when it receives any of `SIGINT`/`SIGTERM`/`SIGHUP` and local `turbo` only had signal handlers setup for `SIGINT`. This PR adds a signal handler for the `SIGTERM` that gets sent.
Immediate future work is plumbing the differing signals down to the process manager. The process manager currently only allows for sending `SIGINT` to child process. I just wanted to get this out the door ASAP to get us into a better state.
Future work will be reworking the global `turbo` signal handling so that we forward the correct signals to local `turbo`.
Send a `SIGTERM` to `turbo` and make sure that the signal handler gets triggered:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ pstree 46675
-+= 46675 olszewski …
```
=> fix: properly catch sigterm sent from global

Cargo.lock, Cargo.toml
This is required to update `swc_core` in next.js.
We need to update `swc_core` of `next.js` to fix OOM bug of `inputSourceMap`
Let's look at the CI
Closes PACK-2125
=> Update `swc_core` to `v0.86.98`

examples/with-tailwind/apps/docs/next.config.js, examples/with-tailwind/apps/web/next.config.js
Puts the `transpilePackages` property into the `with-tailwind` example. Missed it on the first go around!
=> Add transpilePackages to `with-tailwind` example.

docs/pages/repo/docs/support.mdx
Yarn v4 came out with a slightly different lockfile that can break our parsing at times. We're looking to get it fixed but it is not a priority at this time.
=> Update yarn support policy.

examples/with-tailwind/README.md
Fixes the README for `with-tailwind` to reflect the source code. I had forgotten to update it on my first pass.
=> Update README for with-tailwind.

docs/pages/repo/docs/support.mdx, examples/with-docker/packages/logger/package.json
Removing the out-of-spec `source` key here. Have seen it confuse folks more than a handful of times.
=> Remove source key from with-docker example.

crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/process/mod.rs
Fixes https://github.com/vercel/turbo/issues/6754
As of `pnpm@8.10.0` `pnpm run script` will respond to a `SIGINT` with an exit code of `0` (See https://github.com/pnpm/npm-lifecycle/pull/41). `turbo` would see this exit code and assume the task successfully completed which results in unwanted behavior on our part.
In Go we don't run into this issue as we [lock the stop channel during shutdown](https://github.com/vercel/turbo/blob/main/cli/internal/process/child.go#L205) and then [will fail this check once the lock is released](https://github.com/vercel/turbo/blob/main/cli/internal/process/child.go#L251) meaning that we would never send the underlying exit code to the exit channel.
Huge thanks to @laat for reporting the bug with a paired down reproduction repo and for finding the …
=> fix: ignore exit codes when child killed by manager

examples/with-berry/packages/tsconfig/nextjs.json, examples/with-prisma/packages/config-typescript/nextjs.json, examples/with-react-native-web/packages/typescript-config/nextjs.json, examples/with-rollup/packages/config-typescript/nextjs.json, examples/with-tailwind/packages/config-typescript/nextjs.json
Using `"strict": true` is the sane default as we head into 2024. Our examples should reflect this.
=> Use `"strict": true`  for TypeScript in examples.

crates/turborepo-lib/src/process/child.rs
`assert_matches!` is a very explicit macro that expands `assert_matches!(x, y)` to `match x { y => (), ref other => panic!("got {other:?"})`. The `y` branch will be taken every time in this example since`y` refers to a named variable and *not* a bound `y` that might exist. See [matching named variables](https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#matching-named-variables) from the Rust book.
We had `_expected` instead of `expected` because clippy would warn us that the variable was never used and it was right! The the `_expected` in the `assert_matches!` was referring to a different variable than the `_expected` defined above it.
This PR changes the `assert_matches` to use an variant so the assertion is checking what we want.
Now `assert_matches!` expands to
```
match state …
```
=> fix: make assertion assert something

crates/turborepo-repository/src/package_manager/mod.rs
Fixes #6748
Added unit test making sure we don't have multiple forward slashes in the `package.json` globs.
Also tested that we no longer error if a workspace glob has a trailing slash:
```
[0 olszewski@chriss-mbp] /tmp/trailing-slash $ cat pnpm-workspace.yaml 
packages:
- "apps/*"
- "packages/*"
- ci/
[0 olszewski@chriss-mbp] /tmp/trailing-slash $ turbo_dev info                                                                               
Turbo error: discovery failed: bad pattern /private/tmp/trailing-slash/ci//package.json: malformed glob expression: adjacent component bounda
ries `/` or `**`
[0 olszewski@chriss-mbp] /tmp/trailing-slash $ turbo_dev info
You are logged in but not linked
6 packages found in workspace
- @repo/eslint-config packages/eslint-config
- @repo/typescript-config …
```
=> fix: avoid double slash if glob ends with slash

crates/turborepo-lib/src/tracing.rs
Just remove the `EnvFilter` from the chrome tracing layer as we don't actually want to filter events if we're profiling. 
Double checked that you no longer need `-vvv` when creating a `--profile`:
```
[0 olszewski@chriss-mbp] /tmp/profile-test $ turbo_dev build --profile=profile.json
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
web:build: cache hit (outputs already on disk), replaying logs 1ca71cbe42d6964f
docs:build: cache hit (outputs already on disk), replaying logs 8716c2923c92c7c2
web:build: 
web:build: > web@1.0.0 build /private/tmp/profile-test/apps/web
web:build: > next build
web:build: 
...
web:build: 
docs:build: 
docs:build: 
web:build: 
web:build: ○  (Static)  prerendered as …
```
=> chore: remove verbosity filter from chrome profile

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/tracing.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
This PR adds `--anon-profile` which will generate a profile, but without any identifying data included. It will only output where in the code that time was spent.
(The PR also adds a requirement that a user passes a non-empty path for the profile file)
Added unit tests for usage of `--profile` and `--anon-profile`. Quick spot check that `--anon-profile` removes any identifying data:
```
turbo_dev build --anon-profile="profile.json" -vv
```
Resulting [profile.json](https://github.com/vercel/turbo/files/13654482/profile.json)
Closes TURBO-1903
=> feat: add anon-profile flag

packages/turbo-benchmark/src/ttft/run.ts
We shouldn't need this now that https://github.com/vercel/turbo/pull/6779 was merged
Closes TURBO-1905
=> chore: remove verbosity flag when running benchmark

packages/turbo-gen/src/utils/plop.ts
We base all of our generators around workspace roots, anchoring execution there no matter where the command is run. However, there are still times when you may want to access the cwd where the generator command was executed. This passes that through for use in answers.
Feature request from @arlyon 
Closes TURBO-1918
=> feat(gen): pass the command cwd through

Cargo.lock
VSCode (rust-analyzer maybe?) keeps updating my lockfile with this diff. I _think_ it's because this dep was added in #6494 but the lockfile wasn't updated
=> fix: add missing dependency to cargo lockfile

crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/config/turbo.rs, crates/turborepo-lib/src/config/turbo_config.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-lib/src/task_hash.rs
I removed the bookkeeping abstraction that we ported from Go. It wasn't necessary since we can use `Option` to detect if a field is explicitly set versus not. Also renamed `RawTurboJSON` to be `RawTurboJson` to fit with the other names.
The existing tests should suffice.
Closes TURBO-1945
=> refactor: Remove bookkeeping abstraction from turbo config

Cargo.lock, crates/turborepo-lockfiles/Cargo.toml, crates/turborepo-lockfiles/src/berry/mod.rs, crates/turborepo-lockfiles/src/bun/mod.rs, crates/turborepo-lockfiles/src/lib.rs, crates/turborepo-lockfiles/src/npm.rs, crates/turborepo-lockfiles/src/pnpm/data.rs, crates/turborepo-lockfiles/src/yarn1/mod.rs, crates/turborepo-repository/src/package_manager/mod.rs
Add tracing timings to the functions used when calculating transitive closures. Didn't go deeper than the two functions that are used by `transitive_closure` as this is probably all we can do without producing a wild amount of events. This will at least let us understand from a profile if parsing is slow or if it's one of the traversal methods.
Closes TURBO-1937
=> chore: add tracing to primary lockfile functions

docs/next.config.js
Redirect old blog posts to new
Closes TURBO-1952
=> fix(docs): redirect old blog to new

crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-telemetry/src/events/task.rs
=> fix(telemetry): don’t track hash

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/login.rs, crates/turborepo-lib/src/commands/logout.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-telemetry/src/events/command.rs, crates/turborepo-telemetry/src/events/generic.rs, crates/turborepo-telemetry/src/events/mod.rs, crates/turborepo-telemetry/src/events/task.rs, crates/turborepo-telemetry/src/lib.rs, crates/turborepo-vercel-api/src/lib.rs
Previously, the parent<>child relationship between telemetry events required that both events be the same event type. This was overly restrictive, and this PR now allows any event type to be linked together.
This is accomplished by requiring that the event passed to `with_parent` implements the `Identifiable` trait, instead of it being the exact type of a generic. 
This also adds a few other events in and sets up piping for others.
=> feat(telemetry): generic parent to child event

crates/turborepo-cache/src/cache_archive/create.rs, crates/turborepo-cache/src/cache_archive/restore.rs, crates/turborepo-cache/src/cache_archive/restore_symlink.rs
We were using `Header::set_link_name` instead of using `Builder::append_link`, which handles long link names correctly. In general we should avoid using methods on `Header` and instead use the ones on `Entry`.
Modifies the long name test to include a symlink with a long link name.
Closes TURBO-1968
=> fix: Allow for long symlinks by using append_link

crates/turbo-tasks/src/native_function.rs, crates/turbo-tasks/src/registry.rs, crates/turbo-tasks/src/value_type.rs
All calls are generated by the proc-macro, so we don't need to allocate.
Closes PACK-2177
=> perf: Use `&'static str` instead of `String` if possible

docs/components/pages/home-shared/CTAButton.tsx
Adding a type to the button messed up the styling on the CTA button. The stylesheet that is overwriting this property is deeply nested into Nextra.
Because this breakage is prominent, strictly visual, I did it, and I don't wont to bother my teammates for a review during our holiday break, I'm going to push this through without review.
Fixes #6856
=> Remove button type.

docs/components/pages/home-shared/Gradient.tsx, docs/components/pages/pack-home/PackHero.tsx, docs/components/pages/repo-home/RepoHero.tsx
https://turbo.build/pack and https://turbo.build/repo are overflowing to the right on mobile screens.
- The `Gradient` component was causing screens with a width less than the `Gradient`'s `width` to overflow, here I let the `Gradient` component handle the case with a max width that will resize if the device's screen width is less than the requested one, behaving similarly to how images already resize by default with Tailwind. Another alternative is to let it overflow and wrap it to hide the overflow and center it, I think this is more a design choice than a technical one.
- The hexagon and circle images had a similar problem. Removing the explicit width and height of the container and letting the images use their `width` and `height`, and Tailwind's max width kick in fixes the overflow. …
=> fix(docs): mobile screen, prevent gradient and hero overflow

examples/design-system/packages/eslint-config/package.json
Typo fix on package.json from design-system example.
The file `storybook.js` was referenced as `storybook.j` on files field.
=> fix(examples): Typo correction on design-system package.json

crates/turborepo-lib/src/commands/login.rs
Bit of an oops here. Use the variable containing the sso team instead of the raw "sso" string.
Try logging in with SSO, should use the team passed in
Closes TURBO-1974
=> Use the sso team instead of the string 'sso'

docs/next.config.js
As we work through some restructuring of the documentation, there will be some rewrites that need to happen.
Here, I'm cleaning things up so our redirects stay as simple and easy to read as possible. I checked Search Console and none of the source paths in the list are currently being indexed by Google.
=> Remove old redirects.

crates/turborepo-repository/src/discovery.rs
Currently we're performing package discovery multiple times as we remove the cached data instead of copying it.
This change is part of #6712, but is critical enough that it can't wait for that to go through review.
👀 
Closes TURBO-1978
=> fix: avoid deleting cached package discovery data

crates/turborepo-globwalk/src/lib.rs
Fixes #6855
Since we currently construct a glob *after* joining the base path with the inclusion glob if there are special characters they can have unintended meaning and produce incorrect results. We already did a similar thing with `:` as they appear in Windows paths in the drive names.
The list of special characters comes from wax's [token/parse.rs](https://github.com/vercel/turbo/blob/main/crates/turborepo-wax/src/token/parse.rs#L245)
Future work might be using [`Glob::partition`](https://docs.rs/wax/latest/wax/struct.Glob.html#method.partition) or adding the path as part of the glob and instead relying on the `base_path` argument for `Glob::walk`.
Added unit tests for all special character globs.
`turbo build` now works with the reproduction provided in the linked issue.
Closes …
=> fix support bracket filepaths

crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/process/child.rs
These were annoying me. Minor clippy "errors".
No functional changes, all tests should pass.
Closes TURBO-1988
=> fix clippy 'errors'

crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/src/task/aggregation.rs
The delayed removal of children and collectibles for "in progress" tasks of the aggregate tree causes some inconsistency in the aggregated tree when "in progress" task are connected to other node. We need to fix that by reporting outdated children and collectibles as children/collectibles of the "in progress" tasks.
This fixes an race condition when temporary errors are incorrectly shows as final result. e. g. it was visible as `can't resolve "ACTIONS_MODULE9"` in next.js.
Closes PACK-2192
=> fix aggregation of outdated children and collectibles

crates/turbo-tasks-fs/src/glob.rs
The unicode refactoring introduced some bugs in matching of alternatives
Closes PACK-2172
=> fix glob matching of alternatives

crates/turborepo-api-client/src/lib.rs
I think some stuff got nuked in the big auth revert. This should get us building.
Try building Turborepo
Closes TURBO-1992
=> add base url getter to APIClient

Cargo.lock, crates/turborepo-analytics/src/lib.rs, crates/turborepo-api-client/Cargo.toml, crates/turborepo-api-client/src/analytics.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-api-client/src/spaces.rs, crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/fs.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/multiplexer.rs, crates/turborepo-cache/src/signature_authentication.rs, crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/summary/spaces.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-lib/src/tracing.rs
This PR does a few things:
- Adds tracing to far more functions
- Corrects our use of spans in async code (TL;DR you shouldn't hold a span guard across an await [see docs for more info](https://docs.rs/tracing/latest/tracing/span/struct.Span.html#in-asynchronous-code))
- Switch our chrome trace to show tasks vs threads. This makes the profile easier to read as a task which might get worked on by multiple threads will now show as one contiguous block instead of multiple slices across different threads.
Future work:
The keep alive HTTP/2 connection used by `h2` means that the span for our first request lasts until the connection is closed. One can still decipher what happens, but it does mean that the profile can look like one request took the entire run.
Example profile …
=> chore: tracing overhaul

.vscode/launch.json, .vscode/tasks.json
Update the vscode launch configs
1. Update the version to get access to user input and grouping
2. Remove old Go and e2e configs
3. Fix the existing configs to user skip-infer to ensure we're using the local built turbo and not the one installed in the example
4. Cleans up unused actions
Closes TURBO-1991
=> feat(launch): update vscode launch configs

crates/turborepo-auth/src/auth_file.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/login.rs, crates/turborepo-lib/src/commands/logout.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/execution_state.rs, crates/turborepo-lib/src/run/error.rs
How about I do a PR this time?
This updates the execution state to use the `turborepo_auth` crate, beginning the end of the `CommandBase` as the token holder.
Run a command with the `--go-fallback`. This should pass.
Closes TURBO-1987
=> fix: Make execution state use auth crate

docs/styles.css, docs/theme.config.tsx
Code blocks within tabs needed more room to breathe.
=> Fix code block spacing in tabs.

.github/workflows/test.yml
We're opting to drop the macOS runners. We were getting negative value out of them on the examples/documentation side and we don't believe they are contributing to core development stability.
=> Only run examples tests on ubuntu.

crates/turborepo-telemetry/src/events/generic.rs
Missed this val when rolling through events. This should be marked as sensitive when not Vercel.
=> fix(telemetry): obfuscate rc endpoint

Cargo.lock, Cargo.toml, package.json
Update swc crates
Look at the CI of https://github.com/vercel/next.js/pull/60192
Closes PACK-2191
=> Update `swc_core` to `v0.87.16`

docs/pages/repo/docs/getting-started/create-new.mdx
`https://www.npmjs.com//` => `https://www.npmjs.com/`
A minor typo fix in docs. There is npm link with extra slash. `https://www.npmjs.com//`
=> [Docs] create-new.mdx - npm double slash typo fix

crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Closes #1227
We have a few flags that only make sense in the context of others. People are mistakenly using these flags on their own and correctly observing that nothing happens. This change records those deps such that people using invalid combinations of flags are warned.
This also deprecates some old flags, and reorganises the args such that they are closer to one-another in the help doc.
- since -> scope
- no-deps -> scope
- include-dependenciese -> scope
- ignore -> scope ^ filter
New unit tests and integration tests
Closes TURBO-1902
=> Error out if dependent flags are provided without their parent

crates/turborepo-lib/src/engine/mod.rs, turborepo-tests/integration/tests/persistent-dependencies/10-too-many.t
Closes #4291
The validation check to ensure the persistent task count doesn't exceed concurrency did not check if the package actually contained a particular task, leading to erroneous validation when running persistent tasks if you have more than N packages in the project.
Closes TURBO-1914
=> fix: make sure that our concurrency check ignore packages without task

crates/turborepo-lib/src/run/scope/filter.rs
We had an unwrap on trying to parse user input as a glob. This PR just changes that to a better error message.
Current behavior results in a panic:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo run dev --filter={cli,docs}
Oops! Turbo has crashed.
A report has been written to /tmp/report-9c083809-41f9-43bb-86eb-6e7657e0b174.toml
Please open an issue at https://github.com/vercel/turbo/issues/new/choose and include this file
...
explanation = """
file 'crates/turborepo-lib/src/run/scope/filter.rs' at line 414
"""
cause = "called `Result::unwrap()` on an `Err` value: BuildError { kind: Parse(ParseError { expression: \"cli,docs\", locations: [ErrorEntry { fragment: \",web\", location: 5, kind: Nom(Eof) }] }) }"
method = "Panic"
backtrace = """
0:   0xf4ce22 - …
```
=> chore: avoid panic on invalid directory filters

Cargo.lock, crates/turborepo-ffi/src/lib.rs, crates/turborepo-globwalk/Cargo.toml, crates/turborepo-globwalk/src/lib.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/global_hash.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-scm/Cargo.toml, crates/turborepo-scm/src/lib.rs, crates/turborepo-scm/src/package_deps.rs
- adds a wrapper type for strings that we intend to use as patterns, or parts of patterns, for globwalking
- does some transformation on the raw strings (`to_slash`, `clean`, escape or error on `:`, etc.)
- DOES NOT remove any path or pattern transformations inside the `globwalk` code. Some of that is likely duplicate work now, which we ought to tackle once we're confident we're validating properly, and perhaps do an earlier step to compile to an intermediate format.
- DOES NOT propagate beyond existing call sites, with the exception of `WorkspaceGlobs`, but even that could probably use another pass. It is very likely that some of our data structures could hold `ValidatedGlob` instances rather than strings to both 1) validate earlier and 2) avoid duplicate validation
- Existing tests …
=> feat(Turborepo): Use a wrapper around the raw strings we pass to globwalk

crates/turborepo-globwalk/src/lib.rs
Fixes https://github.com/vercel/turbo/issues/6863
This brings us closer to the Go behavior where we would ignore [all IO errors](https://github.com/vercel/turbo/blob/main/cli/internal/doublestar/globwalk.go#L27).
We could do a similar thing by ignoring any error that doesn't have `ErrorKind::Other`, but that feels like slight overkill to me. I think ignoring `NotFound` and `PermissionDenied` is probably the sweet spot.
I would love a unit test, but I'm unaware of an easy way to create a file via Rust that the same process is unable to read. Using a manual test instead:
Create a directory that you can't read
```
mkdir apps/docs/protected
sudo chown root apps/docs/protected
sudo chmod go-rw apps/docs/protected
```
Verify existing canary fails when running `turbo build`:
```
[0 …
```
=> fix: ignore permission errors during globbing

docs/lib/comments.ts, docs/pages/_app.tsx, docs/theme.config.tsx
The button to active the toolbar would also show, even on  pages that don't allow the toolbar to render.
This PR keeps the two states in sync, only showing the activation/de-activation button on routes that the toolbar renders on.
=> Conditionalize comments button.

crates/turborepo-api-client/src/error.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-api-client/src/retry.rs, crates/turborepo-auth/src/mocks/mock_api_client.rs
As reported in #6921 `turbo` is panicking when making HTTP requests. This PR doesn't fix the user issue, but it does avoid the panic and provide a better warning message to the end user.
The panic can be caused in 2 ways:
- Trying to retry a request that has a streaming body. This wasn't happening, but I changed the code so we at least don't panic if we accidentally call this function with a streaming body.
- Constructing a `RequestBuilder` with an invalid url (see https://github.com/seanmonstar/reqwest/issues/1943) will cause the `try_clone` method to return `None` causing us to panic. This can easily be done if a user passes an invalid API url. We mitigate this by now only constructing `RequestBuilder` with `Url` which has already been verified instead of `&str` which delays the …
=> fix: avoid retry panic

crates/turbopack-trace-utils/src/flavor.rs, crates/turbopack-trace-utils/src/lib.rs, crates/turbopack-trace-utils/src/raw_trace.rs, crates/turbopack-trace-utils/src/trace_writer.rs
avoid allocations by recycling buffers used for collecting tracing
Closes PACK-2208
=> recycle trace buffers

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-telemetry/src/events/command.rs
Track all prune args. This is used to determine usage to inform API changes / improvements. Actual values are not recorded in this case.
=> feat(telemetry): track prune args

docs/pages/repo/docs/reference/configuration.mdx
Cleaning up the inputs doc so that it more closely aligns with https://vercel.com/docs/vercel-platform/glossary
`workspace` => `package`, mainly.
CLOSES TURBO-2007
=> Clean up inputs doc.

crates/turbopack-ecmascript-plugins/src/transform/directives/server_to_client_proxy.rs, crates/turbopack-ecmascript/src/references/esm/export.rs
Makes expanding star exports public to be used from `next-core` for generating exports in the proxy module.
Needs to be merged with the next.js PR: https://github.com/vercel/next.js/pull/59578
=> feat(turbopack-ecmascript): support named client references

crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/native_function.rs, crates/turbo-tasks/src/task/function.rs, crates/turbo-tasks/src/value_type.rs, crates/turbopack-core/src/chunk/chunking.rs
Before stuff that run after the task execution has finished wasn't accounted towards the task span. This includes cells changes which trigger a task reexecution.
Now we account these things to the task span too, which improves the trace reporting
Closes PACK-2193
=> improve nesting of tracing for invalidations

crates/turbo-tasks-malloc/src/counter.rs, crates/turbo-tasks-malloc/src/lib.rs, crates/turbopack-convert-trace/src/main.rs, crates/turbopack-trace-server/src/reader.rs, crates/turbopack-trace-server/src/server.rs, crates/turbopack-trace-server/src/span.rs, crates/turbopack-trace-server/src/store.rs, crates/turbopack-trace-server/src/viewer.rs, crates/turbopack-trace-utils/Cargo.toml, crates/turbopack-trace-utils/src/raw_trace.rs, crates/turbopack-trace-utils/src/tracing.rs
* collect memory allocation data and report it when tracing is enable
* Add value mode to trace server to show memory info
Closes PACK-2184
=> trace memory allocations and show in tracing

examples/with-svelte/apps/docs/package.json, examples/with-svelte/apps/docs/svelte.config.js, examples/with-svelte/apps/docs/tests/test.ts, examples/with-svelte/apps/docs/vite.config.ts, examples/with-svelte/apps/web/package.json, examples/with-svelte/apps/web/svelte.config.js, examples/with-svelte/apps/web/tests/test.ts, examples/with-svelte/apps/web/vite.config.ts, examples/with-svelte/pnpm-lock.yaml
- vite-plugin-svelte is now a peer dependency and therefore needs to appear in the user's `package.json`
- fixed preprocessor import in `svelte.config.js`
- removed `optimizeDeps.include` which makes Vite treat the package as an external dependency that it should bundle once, resulting in changes not getting picked up (this was introduced in #6576 but I'm not sure why)
- fixed e2e tests
check manually
=> Fix with-svelte-example

Cargo.lock
Update `Cargo.lock` to match changes made to `Cargo.toml` in  #6866
👀 
Closes TURBO-2032
=> fix: update Cargo.lock with correct workspace dependencies

crates/turborepo-ui/src/prefixed.rs
Fixes #6969
If we encounter a `\r` in a task's outputs we make sure we rewrite our prefix so it doesn't get overwritten by the output that follows the `\r`.
This does result in slightly more writing to stdout than strictly necessary on systems that use `CRLF` instead of just `LF` as we will now print out our prefix before processing `LF`. The user still sees the correct output and this keeps the implementation simple.
[`\r` reference](https://en.wikipedia.org/wiki/Carriage_return#Computers)
Unit tests for a few scenarios, but primary way to test is to run `next` using `turbo`:
```
[0 olszewski@chriss-mbp] /tmp $ npx create-turbo@latest cr-test pnpm
[0 olszewski@chriss-mbp] /tmp $ cd cr-test 
[0 olszewski@chriss-mbp] /tmp/cr-test $ pnpm rm turbo # make sure we're using locally built turbo …
```
=> fix: rewrite prefix after carriage return

crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/process/child.rs
Remove usage of the `command-groups` crate in favor of directly working with `tokio::process::Command`. This PR just inlines what the `spawn` call on unix systems was doing.
This PR doesn't add any "process group" handling for Windows as we weren't using `command-groups` Windows specialization at all:
- On Windows the `spawn` call will [actually generate](https://github.com/watchexec/command-group/blob/main/src/tokio/windows.rs#L27) a [JobObject](https://learn.microsoft.com/en-us/windows/win32/procthread/job-objects).
- Immediately after spawning through we called `into_inner` which [drops all references](https://github.com/watchexec/command-group/blob/main/src/tokio/child/windows.rs#L55) to the JobObject (keeping it open though as closing it would kill the child)
- Our kill …
=> chore: remove usage of command groups

crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/run/cache.rs
Having trouble making progress on #6934 and the daemon logs aren't especially helpful. Tonic is saying the service is unavailable, but I'm unsure of what would cause it to become unavailable. From the docs:
> The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a back-off.
From our server code, I'm not seeing us explicitly throw this anywhere.
This PR does a few things:
- Change the warning to use the default formatter for the error instead of the debug formatter
- Plumb the message from the `tonic::Status` event into our `Unavailable` error variant
👀 
Closes TURBO-2034
=> chore: add reason for service being unavailable

crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/run/graph.t
Fixes https://github.com/vercel/turbo/issues/6994
=> fix(turbo): validate graph extension

Cargo.lock, crates/turborepo-cache/src/lib.rs
`artifact verification failed` is confusing and implies that it's something to do with cache signature authentication when really it could be any `APIClient` issue.
Closes TURBO-2037
=> chore: Adjusted error message for APIClient errors in cache

.github/dependabot.yml, .github/workflows/examples-autoapprove-and-automerge.yml
This PR creates one singular PR on the `dependabot-updates` branch. Dependabot isn't able to do this by itself out-of-the-box since we have multiple workspace roots.
=> Automatically create an umbrella PR for all examples.

examples/with-react-native-web/packages/ui/src/button.tsx
- ref: https://reactnative.dev/docs/text-style-props#fontsize
This PR fixes the wrong type within examples.
=> fix(examples): fontSize type is number not string

examples/with-svelte/packages/ui/package.json
Adds a types field which is necessary in order for TS to pick up typings. SvelteKit 2 changes the default for `moduleResolution` to `bundler` (the new recommended setting from the TS team for most apps), which means the `package.json` export map is now used and needs this for TS to know where to look for the typings.
fixes #7003
Open docs/routes/+page.svelte and see that there's no more type error
=> Fix Svelte package export map

crates/turborepo-cache/src/fs.rs
I noticed on a test project that I couldn't get a cache hit even after a successful run. This came from a malformed metadata file of the form: `{"hash":"20a9a381f9d0b615","duration":5824}}` which I believe got created due to the lack of `truncate` in the open option when we write the metadata file. I believe this can get created from a `--force` run where the first run had a duration that took n+1 digits to express, but the forced run has a duration that only requires n digits to express.
The outcome of having a file like this is that you can never successfully get a cache read and thus never FULL TURBO:
```
[0 olszewski@chriss-mbp] /tmp/daemon-test $ turbo_dev build --output-logs errors-only --no-daemon   
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, …
```
=> fix(cache): truncate metadata file when writing

crates/turbopack-build/src/chunking_context.rs, crates/turbopack-build/src/lib.rs, crates/turbopack-cli/src/build/mod.rs, crates/turbopack-core/src/chunk/chunk_group.rs, crates/turbopack-core/src/chunk/chunking_context.rs, crates/turbopack-core/src/chunk/mod.rs, crates/turbopack-core/src/output.rs, crates/turbopack-dev-server/src/html.rs, crates/turbopack-dev/src/chunking_context.rs, crates/turbopack-ecmascript/src/chunk_group_files_asset.rs, crates/turbopack-ecmascript/src/manifest/chunk_asset.rs, crates/turbopack-node/src/bootstrap.rs, crates/turbopack-tests/tests/snapshot.rs
This allows to create a chunk group based on another chunk group (which skips all available modules at this point)
Similar to `webpack` `dependOn`.
Closes PACK-2229
=> allow to pass available chunk items when creating a chunk group

docs/pages/repo/docs/_meta.json
This PR adds an Easy Bake Oven to the Turborepo docs so I can easily reach for some tasty treats whenever I'm feeling snacky.
No, it doesn't. It just adds the Vercel Glossary to the sidebar.
=> Add Glossary to sidebar.

crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lsp/Cargo.toml, crates/turborepo-lsp/src/lib.rs, crates/turborepo-repository/src/package_json.rs, crates/turborepo/build.rs
#6543 accidentally broke some things. This PR:
- adds back building the Go binary to `turbo`'s build script
- Lifts TLS backend features from `turborepo-lib` to `turborepo-lsp` now that the LSP crate is an entry point to the crate. (Matters as `cargo-groups` prunes `check` runs to only run against the entry points and now errors complaining that the feature doesn't exist)
- Fixes clippy warning about `FromStr`
- Fixes test that didn't compile
CI Passes 👀 
Closes TURBO-2056
=> fix: forward fixes for LSP

crates/turborepo-filewatch/src/cookie_jar.rs
Fixes #6934
We weren't verifying that the cookie dir existed before trying to write the cookie file. This would cause cookie operations to fail if `.turbo/cookie` got deleted between runs. 
e.g.
```
[0 olszewski@chriss-mbp] /tmp/daemon-test $ turbo build --output-logs errors-only 
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
Tasks:    2 successful, 2 total
Cached:    0 cached, 2 total
Time:    7.847s 
[0 olszewski@chriss-mbp] /tmp/daemon-test $ rm -rf .turbo/cookies 
[0 olszewski@chriss-mbp] /tmp/daemon-test $ turbo build --output-logs errors-only
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web …
```
=> fix(daemon): make sure cookie dir exists before writing cookie

crates/turbopack-ecmascript/src/lib.rs
This is causing some chunk items to be loaded twice.
=> fix: add missing layer ident modifier to asset with inner assets

docs/lib/search/index.ts
Governance is likely not something that our users are concerned with when searching in our docs so let's exclude from results.
=> Remove Governance page from search box.

crates/turbo-tasks-memory/Cargo.toml, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/src/task/aggregation.rs
Add a feature flag to make it easy to disable lazy removal of children. Just in case I want to figure out if this is causing a specific problem in future.
Closes PACK-2269
=> add lazy_remove_children feature flag

crates/turbopack-ecmascript/src/parse.rs
Turbopack in next.js does not report parse errors for the input like 
```
function xyz() {
...
```
which expects to report 
```
Expected '}', got '<eof>'
```
Comparing upstream swc, the only difference is turbopack collect recoveable error eagerly _before_ actual parsing, and then parse returns a parsed program. (ref: https://github.com/swc-project/swc/blob/979061f6babbbf855027b13eb574c5f3f7e24727/crates/swc_compiler_base/src/lib.rs#L62-L77)
PR fixes ordering of error collection as same as swc does. 
Confirmed next.js with this change now reports expected error. (Note: doesn't mean tests are actually fixed, the output is not matching with snapshot still)
Closes PACK-2274
=> fix(ecmascript): collect recoverable error after parse

crates/turbopack-cli/src/dev/mod.rs, crates/turbopack-cli/src/dev/web_entry_source.rs, crates/turbopack-dev/src/chunking_context.rs, crates/turbopack-tests/tests/execution.rs, crates/turbopack-tests/tests/snapshot.rs
Ensures edge compilation outputs the right asset urls. Currently in Next.js with Turbopack enabled they show `/assets/file.hash.png` but it should be relative to the `asset_prefix` and client path.
=> Add client_root for edge

docs/pages/repo/docs/core-concepts/remote-caching.mdx
Point to the rust api lib instead of the go one
=> fix(docs): remote cache go -> rust

docs/pages/repo/docs/handbook/sharing-code.mdx, docs/pages/repo/docs/handbook/sharing-code/internal-packages.mdx
While `main` and `types` works, it often corners our users into using barrel files. Instead, let's start our users off on a path that allows them to create many entrypoints to their packages if their repo were to grow to need it).
=> Use `exports`  in Internal Packages doc.

Cargo.lock, Cargo.toml
otherwise the build fails on aarch64-unknown-linux-gnu
Closes PACK-2286
=> lock reqwest to 0.11.17 due to build issues

packages/turbo-repository/js/package.json, packages/turbo-repository/npm/darwin-arm64/package.json, packages/turbo-repository/npm/darwin-x64/package.json, packages/turbo-repository/npm/linux-arm64-gnu/package.json, packages/turbo-repository/npm/linux-x64-gnu/package.json, packages/turbo-repository/npm/win32-arm64-msvc/package.json, packages/turbo-repository/npm/win32-x64-msvc/package.json
This PR bumps the `@turbo/repository` version.
N/A
=> release: `@turbo/repository@0.0.1-canary.3`

crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/parse.rs
* Avoid read_dir calls on files
Closes PACK-2278
=> reduce work and tasks during module analysis

docs/package.json, docs/turbo/generators/utils.ts, pnpm-lock.yaml
We don't need node-fetch anymore since we're on node 20. This also gets our blog generators working again since node-fetch@3 is esm.
Closes TURBO-2141
=> chore(docs): remove node-fetch in favor of builtin

CONTRIBUTING.md
We actually build with rustls-tls and not native-tls
Closes TURBO-2145
=> docs: Update TLS info to be accurate

Cargo.lock, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/process/command.rs, crates/turborepo-lib/src/process/mod.rs
This PR adds, but doesn't hook up, the ability to spawn a child process hooked up to a pseudo terminal.
I *highly* suggest reviewing each commit on its own. I tried my best to split out prefactoring work from any feature work.
Adapt unit tests to cover all of them. It will be noted that switching to use a PTY does affect what programs output and so the tests were made to not check for identical output, but just that we got the expected output.
Closes TURBO-2128
=> feat: add ability to spawn child process with pty

cli/internal/hashing/package_deps_hash_test.go, crates/turborepo-scm/src/manual.rs
If inputs have been provided, we allow git-ignored files to be included in the hash. This behavior wasn't respected for the fallback hashing (when git isn't available). This fixes that. 
Closes TURBO-2156
=> fix(hashing): include gitignored files in fallback

.github/workflows/lsp.yml
Add a basic CI pipeline to build LSP binaries on command. Packaging will still be manual for now.
Lets run it and see!
Closes TURBO-2162
=> add turborepo-lsp build matrix based on turbo's

.github/turbo-orchestrator.yml
I have a bookmark that looks for PRs opened by external folks that was showing @anthonyshew's PRs, and I wanted tof ix that.
https://github.com/vercel/turbo/pulls?q=is%3Apr+is%3Aopen+sort%3Acreated-desc+-label%3A%22created-by%3A+turbopack%22+-label%3A%22created-by%3A+turborepo%22+-review%3Aapproved+draft%3Afalse+
Closes TURBO-2167
=> chore(ci): update created-by: turborepo labeling automation

crates/turborepo-lib/src/process/child.rs
Adding some tracing to our spawning code to measure impact of PTY usage. Quick tests make it look like the `openpty` call has a minimal impact (~.2ms) on the time it takes to spawn a process.
Look at the profiles:
[normal.json](https://github.com/vercel/turbo/files/14068301/normal.json)
[pty.json](https://github.com/vercel/turbo/files/14068303/pty.json)
Closes TURBO-2175
=> chore: add tracing to pty usage

Cargo.lock, Cargo.toml, crates/turbopack-ecmascript-plugins/src/transform/directives/server_to_client_proxy.rs, crates/turbopack-ecmascript-plugins/src/transform/styled_jsx.rs, crates/turbopack-ecmascript/src/tree_shake/graph.rs, crates/turbopack-tests/tests/snapshot/basic/ecmascript_minify/output/crates_turbopack-tests_tests_snapshot_basic_ecmascript_minify_input_index_dc5b16.js.map, crates/turbopack-tests/tests/snapshot/emotion/emotion/output/crates_turbopack-tests_tests_snapshot_b36339._.js, crates/turbopack-tests/tests/snapshot/swc_transforms/mono_transforms/output/crates_turbopack-tests_tests_snapshot_9cde7b._.js
Update SWC crates.
- next.js counterpart: https://github.com/vercel/next.js/pull/61086
Closes PACK-2286
=> Update `swc_core` to `v0.89.x`

Cargo.lock, Cargo.toml
Update swc crates to fix build issues
next.js counterpart: https://github.com/vercel/next.js/pull/61285
Closes PACK-2305
=> Update `swc_core` to `v0.89.4`

crates/turborepo-lib/src/process/mod.rs
Enable PTY usage! Will wait until #7109 is merged so there isn't any `^D` in the output caused by stdin being dropped. Measurements of impact of PTY usage can be found in #7127
Current rules for our PTY usage:
- User isn't on windows
- stdout is hooked up to a TTY as this is where we send task logs
We could strengthen the condition by requiring that stderr is hooked up to a TTY, but IMO this is overkill as we don't send any task output to that stream.
When running normally we get nice colors:
Verify that if we pipe our primary output to stdout, we don't use a PTY and get no colors:
Closes TURBO-2176
=> feat: enable pty usage

crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/parse.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-mdx/src/lib.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_rule.rs
We currently parse JSX syntax in all typescript files which is wrong.
Closes PACK-2302
Next.js PR: https://github.com/vercel/next.js/pull/61219
=> fix(turbopack): don't parse `.ts` files as `.tsx`

crates/turborepo-lib/src/process/command.rs, crates/turborepo-lib/src/process/mod.rs, crates/turborepo-lib/src/run/mod.rs
I realized that the process manager tests were broken if they were run from a TTY on non-windows. This PR does a few things:
- Switches `use_pty` calculation to happen once during process manager construction. This saves a `isatty` syscall from each process getting spawned.
- Fixes how we constructed `portable_pty::CommandBuilder` as it differs from the stdlib where if `cwd` isn't specified it uses the user home dir instead of the current process cwd [source](https://docs.rs/portable-pty/latest/src/portable_pty/cmdbuilder.rs.html#458). This came up because process manager tests don't use absolute paths to specify script paths where the child tests use absolute paths so cwd doesn't matter.
We could update the process manager tests to cover both codepaths, but the spawn method shouldn't …
=> fix: process manager tests tty

crates/turbopack-dev/src/ecmascript/content.rs, crates/turbopack-dev/src/ecmascript/mod.rs, crates/turbopack-dev/src/lib.rs
This is needed to read source map data to trace sourcemaps in Next.js
Closes PACK-2317
=> Make `EcmascriptDevChunkContent` public to other crates

crates/turbopack-dev/src/ecmascript/content_entry.rs
Fixes the error on https://github.com/vercel/next.js/pull/61369
Test run: https://github.com/vercel/turbo/blob/08e09624524425db1530381941d1fedbed27fe4f/crates/turbopack-dev/src/ecmascript/content_entry.rs#L44 
Excerpt:
```
error: type `turbopack_binding::turbopack::turbopack_dev::ecmascript::content_entry::EcmascriptDevChunkContentEntries` is private
--> packages/next-swc/crates/napi/src/next_api/project.rs:856:35
|
856 |                     let entries = content.entries().await?;
|                                   ^^^^^^^^^^^^^^^^^^^^^^^^ private type
error: type `turbopack_binding::turbopack::turbopack_dev::ecmascript::content_entry::EcmascriptDevChunkContentEntry` is private
--> packages/next-swc/crates/napi/src/next_api/project.rs:857:33
|
857 |                     let entry = …
```
=> Fix sourcemap PR compile error

crates/turbopack-ecmascript-plugins/src/transform/styled_jsx.rs
This PR partially reverts #7027 to fix build issues.
- Reopens https://github.com/vercel/next.js/issues/57718
Local override will work
Closes PACK-2322
=> fix: Revert `preset-env` mode of `styled-jsx` in turbopack

.github/workflows/turborepo-release.yml, Cargo.toml
We don't strip release symbols from our binary. This pr changes that.
Run the new command in the ci, and observe the binary size shrink.
Closes TURBO-2187
=> Add release turborepo profile

crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/test/scripts/hello_no_line.js
Some programs might not output a trailing newline. This results in us possibly writing another task's' output on the same line. In this case we should add a trailing newline.
e.g. a task of `echo -n 'building'` previously would cause output like:
```
foo:build > building bar:build > building
```
Should now look like:
```
foo:build > building
bar:build > building
```
Closes TURBO-2195
=> fix: tasks with no newline

docs/pages/repo/docs/core-concepts/caching.mdx, docs/pages/repo/docs/core-concepts/caching/file-inputs.mdx, docs/pages/repo/docs/reference/configuration.mdx
Docs for https://github.com/vercel/turbo/pull/7113
Depends on https://github.com/vercel/turbo/pull/7113
Closes TURBO-2184
=> [DO NOT MERGE] feat(docs): $TURBO_DEFAULT$

crates/turbopack-core/src/issue/resolve.rs, crates/turbopack-core/src/resolve/mod.rs
The wrong error / not all errors were caught before.
This also adds the error trace to the error message.
Closes PACK-2325
=> fix: catch import map lookup error properly in `ResolvingIssue`

Cargo.lock, Cargo.toml, crates/turbopack-ecmascript-plugins/src/transform/styled_jsx.rs
Re-enable `preset-env` mode of `styled-jsx`
Tested with https://github.com/swc-project/plugins/pull/259
Closes PACK-2330
=> feat: Re-enable `preset-env` mode of `styled-jsx` in turbopack

Cargo.lock, Cargo.toml
Update SWC crates to apply the latest bugfixes
See https://github.com/vercel/next.js/pull/61426
Closes PACK-2333
=> chore: Update `swc_core` to `v0.89.6`

docs/pages/repo/docs/telemetry.mdx
`events` is a dir not a .rs file
=> docs: fix link in telemetry

crates/turborepo-telemetry/src/config.rs
This fixes an issue with unparsable output from `--dry=json` that causes `turbo-ignore` to fail with a JSON parse error if the user has not disabled the message.
To reproduce the issue this PR seeks to resolve run the following commands in any turbo enabled repo.
```
rm ~/.config/turborepo/telemetry.json
pnpx turbo-ignore # fails with JSON parse error
```
fixes #7185
=> Print telemetry warning on stderr

Cargo.lock, crates/turborepo-lockfiles/Cargo.toml, crates/turborepo-lockfiles/src/lib.rs, crates/turborepo-repository/src/package_graph/builder.rs
I remembered that the FFI interface was what was stopping me from throwing rayon at the lockfile graph traversal. This can be done easily since we already require that all lockfile implementations are `Send` and they don't mutate the underlying lockfile.
There's a more elegant way to do this and avoid calculating inner closures multiple times, but this is a straightforward win.
From 
To
[serial.json](https://github.com/vercel/turbo/files/14106106/profile.json)
[parallel.json](https://github.com/vercel/turbo/files/14106107/parallel.json)
Closes TURBO-2197
=> feat(lockfile): traverse lockfile in parallel

crates/turborepo-lib/src/run/global_hash.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/summary/scm.rs
I noticed in the profile that we were calling `SCM::new` multiple times which should be avoided since this results in FS.
This PR does 2 things:
- Passes existing `SCM` instance around to all the places we were constructing a new instance
- Kick of a thread to construct the `SCM` instance as soon as we start run, this means it will usually be ready by the time we need it.
Old profile:
New profile:
Note how we now are able to construct the `SCM` before the package graph finishes building meaning it's available for filtering the graph immediately.
Closes TURBO-2206
=> perf: remove duplicate git construction

crates/turborepo-lib/src/task_graph/visitor.rs
Fixes #7181
Some tools when they are connected to a TTY will take stdin being closed as a sign that they should shut down. This PR changes our behavior to keep stdin open for persistent tasks to avoid premature shutdowns.
Verify that using `vite` no longer immediately exits when invoked using a pseudoterminal.
(`vite` outputs a clear screen sequence resulting in the run prelude being erased)
Closes TURBO-2208
=> fix: keep stdin open for persistent tasks

crates/turborepo-scm/src/package_deps.rs, crates/turborepo-scm/src/status.rs, turborepo-tests/integration/tests/run/path-with-spaces.t
- Don't stop `git status` parsing when encountering a space
- Added a unit test for `git status` testing
- Added an integration test for a dry run with an added file with a space in the path name
Closes TURBO-2209
=> fix(Turborepo): Handle spaces in path names in git status

cli/turbo.json
Previously we were relying on `cli/cmd/version.go` to get bumped when the version got changed, but now we just have `version.txt`. This PR declares that input and gets rid of the Go inputs.
This causes failures like [this one](https://github.com/vercel/turbo/actions/runs/7747210377/job/21127375688?pr=7205#step:7:881) where we're using an older binary due to a cache hit.
Changing `version.txt` should now result in a cache miss
Closes TURBO-2222
=> fix: declare version.txt as input

crates/turbopack-css/src/process.rs, crates/turbopack-css/src/references/import.rs
Previously, an empty medialist was converted to `@media not all`, which is wrong.
You can test it using internal sites
- Closes PACK-2360
- Closes PACK-2361
=> fix(turbopack): Fix css var issue and font issue when using `lightningcss`

crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/module_options_context.rs, crates/turbopack/src/module_options/module_rule.rs
Closes PACK-2356
This PR creates a new ModuleRuleEffect named `ExtendEcmascriptTransforms`. This is an extended version of `AddEcmascriptTransforms` effect, which will be removed once next.js replaces all of its references.
The change born in need of allowing custom rules in `ModuleOptionContext` to have a specific order of transform. This was been achieved by having a custom ecmatransform plugin in moduleoptions. However, it was not very clear for the distinction between rules & transforms, as well as there are some behavior differences we noticed (note: this still may need to be investigated separately later). After discussing with @sokra , we concluded it is better to deprecate custom ecmatransformplugin but use custom rules whereever possible.
One functional differences between …
=> feat(turbopack): extend ecmatransform moduleeffect

Cargo.lock, crates/turbopack-build/Cargo.toml, crates/turbopack-build/src/ecmascript/minify.rs, crates/turbopack-build/src/ecmascript/node/content.rs, crates/turbopack-css/Cargo.toml, crates/turbopack-css/src/chunk/mod.rs, crates/turbopack-css/src/chunk/single_item_chunk/chunk.rs, crates/turbopack-dev/Cargo.toml, crates/turbopack-dev/src/ecmascript/content.rs, crates/turbopack-dev/src/ecmascript/evaluate/chunk.rs
Some source maps weren't loading for me, might be a firefox issue, but it really didn't like spaces in the source map url (e.g. `[root of the server]`)
Closes PACK-2357
=> fix(turbopack): encode source map urls

crates/turbopack-core/src/ident.rs
very much disliked the inner assets being displayed as part of the path, now it's more like a map
Closes PACK-2358
=> style(turbopack): make idents more readable

crates/turborepo-lockfiles/src/pnpm/data.rs
Noticed that we've been improperly parsing the updated pnpm lockfile. [source](https://github.com/pnpm/pnpm/blob/main/lockfile/lockfile-types/src/index.ts#L6)
Added a unit test that verifies we get the correct info in the settings field.
Closes TURBO-2210
=> fix: correctly parse pnpm lockfile settings

.github/workflows/test.yml
For some reason Hetzner is setting `TURBO_API` which is causing us to not use the remote cache [e.g.](https://github.com/vercel/turbo/actions/runs/7757236744/job/21156328810?pr=7223#step:6:79)
Verify that JS Packages now uses the correct remote cache (no remote cache warnings):
[job](https://github.com/vercel/turbo/actions/runs/7759230611/job/21162847801?pr=7234#step:6:1)
Closes TURBO-2226
=> fix: override turbo_api env var

crates/turbopack-cli/src/contexts.rs, crates/turbopack-tests/tests/snapshot.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_options_context.rs, crates/turbopack/src/module_options/module_rule.rs
https://github.com/vercel/next.js/pull/61481 cleans up the usage of deprecated options, remove it from turbopack itself.
Closes PACK-2370
=> refactor(turbopack): remove deprecated options

examples/basic/packages/typescript-config/react-library.json
In the example tsconfig for a react library there is a trailing comma inside the compiler options which would make it invalid JSON.
=> Fix trailing comma in exapmle react-library.json

crates/turbopack-node/src/transforms/postcss.rs
Just needed to be added to the array so turbopack knows that it needs to watch it.
Closes PACK-2393
Fixes https://github.com/vercel/next.js/issues/61607
=> fix(turbopack): support reloading typescript tailwind config

examples/turbo.json
Q: how long would a `turbo lint` call would take in our repository?
A: 13 minutes
12 minutes of that is collecting inputs for `turborepo-examples:lint-prettier` which it inherits from the root definition.
This PR overrides that input list and now it only takes ~200ms to do nothing. 
Closes TURBO-2231
=> fix: avoid expensive globwalk in examples

docs/pages/repo/docs/ci/github-actions.mdx
When reading the documentation, I noticed this word was ~mispelled~ using the British spelling rather than the American spelling which other pages use. Since there's an edit on github button, figured I'd just submit a fix!
=> Fix a typo in docs page for github actions

crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/lib.rs
Seems like we had a bug in the daemon restart logic where it couldn't kill the daemon. Also, added a fallback that runs `clean` if we can't connect to the daemon.
Closes TURBO-2263
=> fix: Daemon Restarting

crates/turborepo-lib/build.rs, crates/turborepo-lib/src/lib.rs
Makes the TLS feature compile error easier to understand, currently it will tell you the build script failed and you have to look for the panic message.
=> chore(turborepo-lib): use compile error for feature validation

.github/workflows/turborepo-library-release.yml
Title says it all. Will be used for testing changes to release workflow.
[Dry run using this branch](https://github.com/vercel/turbo/actions/runs/7808479500/job/21299070519)
Closes TURBO-2274
=> chore: add dry run flag to @turbo/repository release

crates/turbopack-core/src/chunk/chunk_group.rs, crates/turbopack-core/src/chunk/chunking.rs, crates/turbopack-core/src/chunk/mod.rs
change make_chunks into a turbo_tasks function to isloate graph walk from chunk item size changes
Before any file change caused module graph walk and chunking to be reexecuted. After this change module graph walk is only reexecuted when module references change.
Closes PACK-2431
=> improve HMR performance

packages/create-turbo/package.json, pnpm-lock.yaml
We use inquirer@8 which has a nested dependency on chalk@4. Updating our
dependency to @4 means we can avoid shipping two versions of chalk to
end users.
Breaking changes notes:
- https://github.com/chalk/chalk/releases/tag/v4.0.0
- https://github.com/chalk/chalk/releases/tag/v3.0.0
🤔 . The build size looks the same before and after
CJS dist/cli.js 549.34 KB, 
but when I install the package into a test directory, I can see that
`du -sh node_modules` is 27Mb (before) vs 26mb (after).
Closes TURBO-2276
=> chore(create-turbo): update chalk to v4

.github/ISSUE_TEMPLATE/0-turborepo-bug-report.yml
We are receiving bug reports for Yarn for and they are incorrectly categorized
ref: https://github.com/vercel/turbo/issues/6805
Closes TURBO-2262
=> chore: Add Yarn 4 to Github Issue template

crates/turborepo-lib/src/config.rs, docs/pages/repo/docs/reference/command-line-reference/run.mdx
The Go timeout was being set to `0`, which meant there was _no_ timeout. We don't want to replicate that exactly, some timeout is good. This just increases the timeout a bit to reduce issues with large artifacts. 
Closes TURBO-2277
=> feat(cache): bump default timeout and add docs

crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/mod.rs
Feature-gate the imports used by the daemon-backed package discovery.
Tested manually via `cargo build --features daemon-package-discovery`
Closes TURBO-2273
=> chore(Turborepo): Delete or feature-gate imports

crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/daemon/mod.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/run/package_discovery/mod.rs, crates/turborepo-repository/src/package_graph/builder.rs
- Apply existing `wait_for_filewatching`, which returns appropriate statuses when filewatching is unavailable, as well as applies a timeout
- drop map to internal error for any package watching errors. We want to propagate back statuses like `DeadlineExceeded`
Closes TURBO-2229
=> fix(Turborepo): Route through existing wait_for_filewatching call

crates/turborepo-cache/src/async_cache.rs, crates/turborepo-lib/src/commands/run.rs
Remove the `writer_thread` reference in `AsyncCache` so we can easily clone it. 
Precursor to https://github.com/vercel/turbo/pull/7074/files
Closes TURBO-2271
=> feat(async_cache): support cloning

.github/workflows/test.yml, Cargo.toml
next-swc requires upstream pkg support for the wasi target. We can't just build everything, but PR enables check against few packages which 'just works'.
Closes PACK-2436
=> ci(test): add wasi target check for the supported packages

crates/turborepo-scm/src/lib.rs, turborepo-tests/integration/tests/run/big-status.t
- If we've already encountered a parse error, don't wait for the child process to exit cleanly, just kill it. Waiting nicely could mean waiting forever.
- Only read from `stderr` after we've killed the process, otherwise that could block forever if there is nothing available.
Added new unit test simulating a parse error with a script that would hang forever under the old method.
Closes TURBO-2212
=> fix(Turborepo): Don't block forever if we have already gotten a parse error

crates/turborepo-cache/src/lib.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/task_access.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-paths/src/anchored_system_path.rs
v0 of work required for zero config (experimental):
1. Support config caching
2. Support task tracing
Requires: https://github.com/vercel/next.js/pull/59553
=> feat(turbo): task access trace & cached configs

packages/turbo-repository/rust/src/internal.rs
A few clippy lints that were bothering me.
`rustc`
Closes TURBO-2283
=> chore: fix clippy lints in @turbo/repository

.github/workflows/test.yml
It seems that setting `RUSTC_WRAPPER` to an empty string results in [weird failures](https://github.com/vercel/turbo/actions/runs/7823191751/job/21343720629?pr=7315#step:6:461)
This is an external PR so as long as this PR can successfully build `turbo` this fix should work. 
Closes TURBO-2290
=> fix: unset RUSTC_WRAPPER when empty

crates/turborepo-cache/src/async_cache.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs
As per discussion in #7293 we should probably have a shutdown method. This PR adds a method that will prevent any future writes from being queued.
Added some shutdown tests to make sure that trying to use the cache post-shutdown will error. These probably should belong in their own testing methods, but considering the amount of work required to construct an AsyncCache I think this is acceptable.
Closes TURBO-2282
=> chore: add shutdown method for async cache

crates/turborepo-auth/src/auth/login.rs, turborepo-tests/integration/tests/command-login.t
We should _at least_ check to see if the token we see in `com.vercel.cli` is able to fetch the user.
Closes TURBO-2300
=> fix: check vercel token is still valid

crates/turborepo-filewatch/src/cookie_jar.rs, crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/globwatcher.rs, crates/turborepo-filewatch/src/lib.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-paths/src/absolute_system_path.rs
Filewatching cookies were ensuring that the filewatching task was up to date, but not downstream, filewatching-backed services. This change moves the filesystem cookie synchronization into a downstream service (glob watching) to ensure that RPCs are serviced by a task that has seen at least all of the operations that a client has done.
The process is as follows:
1. A client of a filewatching-backed service uses a `CookieWriter` to stamp its request with a serial. 
2. The CookieWriter requests a cookie file be written, and the serial returned to the client
3. The client forwards the request, now with a serial, to the filewatching-backed service
4. The service observes cookie files being created, and keeps track of the highest serial it has seen via a `CookieWatcher`. When a cookie file is …
=> fix(Turborepo): Start moving cookie watching to downstream services

crates/turborepo-api-client/src/telemetry.rs, crates/turborepo-telemetry/src/events/command.rs, crates/turborepo-telemetry/src/events/generic.rs, crates/turborepo-telemetry/src/events/mod.rs, crates/turborepo-telemetry/src/events/repo.rs, crates/turborepo-telemetry/src/events/task.rs, crates/turborepo-telemetry/src/lib.rs, crates/turborepo-vercel-api/src/lib.rs, crates/turborepo-vercel-api/src/telemetry.rs, crates/turborepo-vercel-api/src/token.rs
I think it's logical to group the kinds of Vercel responses into their own files, keeping generic stuff in `lib.rs`.
Closes TURBO-2303
=> chore: modularize vercel api crate

crates/turborepo-filewatch/src/globwatcher.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/run/cache.rs
- Change type signature on daemon client to require `ValidatedGlob` instances be passed
- Add some debug logging to `GlobTracker` about what globs we are tracking and what file paths invalidate a glob
Fixes #7131 
Closes TURBO-2301
=> fix(Turborepo): Pass validated globs to daemon for watching

crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/parser.rs, turborepo-tests/integration/tests/config.t, turborepo-tests/integration/tests/prune/produces-valid-turbo-json.t
The core goal of this PR is to make `run.run` immutable. This enforces that our config and options are all resolved before we start a run. The last remaining piece of that was picking up the `spaces_id` from the layered config system. 
Adding `spaces_id` to the layered config system necessitated a bunch of other changes due to the fact that it is not contained within the `remoteCache` field in `turbo.json`. The config system previously assumed that any config file could contain the entirety of the config, which wasn't strictly true, but now is even less true. 
To that end, I created a separate struct to represent just the `remoteCache` field in `turbo.json`. It shares much, but not all of the parser for a config file. I split the rendering of `ConfigurationOptions` into two structs, since …
=> feat(Turborepo): Add spaces_id to layered config

crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/gitignore.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/run/task_access.rs
We need to make sure .turbo is ignored for task access. This pulls the existing util out of link, and re-uses it. 
Also - tests!
=> feat(gitignore): break out gitignore util

crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, packages/turbo-repository/rust/src/lib.rs
=> chore(turbo): rename WorkspaceNode to PackageNode

crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/endpoint.rs, crates/turborepo-lib/src/daemon/mod.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lsp/src/lib.rs, packages/turbo-repository/npm/linux-x64-musl/package.json
Stepping stone to moving `CommandBase` out of `run` 
- Move daemon path handling into the daemon module
Updated existing test suite
Closes TURBO-2323
=> chore(Turborepo): Move daemon paths off of CommandBase

Cargo.lock, crates/turborepo-api-client/Cargo.toml
Enable the feature for using native certs and not just the ones shipped with `turbo`. See [this readme](https://github.com/rustls/rustls-native-certs?tab=readme-ov-file#should-i-use-this-or-webpki-roots) for a comparison between these features. If you compare the Go implementations ([linux](https://go.dev/src/crypto/x509/root_linux.go), [macos](https://go.dev/src/crypto/x509/root_darwin.go), [windows](https://go.dev/src/crypto/x509/root_windows.go)), this gets us closer to that behavior. 
Both `weppki-roots` and `rustls-native-certs` can be used at the same time and [both sources](https://docs.rs/reqwest/latest/src/reqwest/async_impl/client.rs.html#465) will be added to the [client when built](https://docs.rs/reqwest/latest/src/reqwest/async_impl/client.rs.html#482)
I believe this should …
=> fix: use system certs for tls

crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/mod.rs
- `Run` no longer requires a `CommandBase` instance, although the constructor still takes one.
Closes TURBO-2335
=> chore(Turborepo): Remote CommandBase from Run

crates/turborepo-repository/src/package_graph/mod.rs, packages/turbo-repository/__tests__/find.test.ts, packages/turbo-repository/js/index.d.ts, packages/turbo-repository/rust/src/lib.rs
This API maps a list of files (strings anchored to the root of the workspace) to a set of packages that were affected by that change. This will include the packages the files belong to ~~as well as an dependents~~.
Since this doesn't include dependents, users will have to use it with `findPackagesAndDependents()` API:
```js
const files = [/*...*/];
const w = await new Workspace(".");
const [reverseGraph, affected] = await Promise.all([
w.findPackagesAndDependents(),
w.affectedPackages(files);
]);
// For each affected package, include all the dependents as well.
// Use a set to avoid dupes.
const allAffected = new Set(affected);
for (const p of affected) {
reverseGraph[p].forEach(x => allAffected.add(x));
}
return [...allAffected] // spread into an array
```
=> feat(@turbo/repository): add affectedPackages API

crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/scope/change_detector.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/summary/task_factory.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-repository/src/change_mapper.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, packages/turbo-repository/rust/src/lib.rs
This PR renames `workspace` -> `package` in the `package_graph` module of the `turborepo-repository` crate. There are many other references to update, but since this is the canonical representation of packages in a workspace, this is an important one to define the lexicon.
You can review each commit if you want to see smaller diff
Closes TURBO-2345
=> chore(turbo): rename workspace -> package in PackageGraph module

.github/workflows/test.yml, turborepo-tests/integration/tests/bad-turbo-json.t, turborepo-tests/integration/tests/config.t, turborepo-tests/integration/tests/dry-json/monorepo-no-changes.t, turborepo-tests/integration/tests/run-summary/monorepo.t, turborepo-tests/integration/tests/run-summary/single-package.t, turborepo-tests/integration/tests/shim-errors.t
Ran into this while working on https://github.com/vercel/turbo/pull/7374
Closes TURBO-2348
=> chore(turbo): remove EXPERIMENTAL_RUST_CODEPATH env var

Cargo.lock, Cargo.toml
Update swc crates one more time.
See https://github.com/vercel/next.js/pull/61976
Closes PACK-2477
=> build: Update `swc_core` to `v0.90.8`

crates/turborepo-ci/src/vendor_behavior.rs, crates/turborepo-ci/src/vendors.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/output.rs, crates/turborepo-ui/tests/threads.rs, turborepo-tests/integration/tests/run-logging/log-order-github.t
Fixes https://github.com/vercel/turbo/issues/6709
Github Action doesn't provide a mechanism for grouping logs together and keeping them expanded which is helpful for highlighting errors.
This PR changes the behavior so we avoid emitting the grouping header/footer if task execution was a failure.
Updated GH Action log grouping integration test
Closes TURBO-2320
=> fix: avoid grouping logs from tasks which ended in error

Cargo.lock, crates/turborepo-globwalk/Cargo.toml, crates/turborepo-globwalk/src/lib.rs
This PR brings parallelism to 2 aspects of our globwalk behavior:
- parsing the input globs
- walking of each of the input globs
This will primarily provide a speedup for tasks which have a large amount of input globs, but from quick spot checks I think this doesn't negatively impact tasks with small (2-3) inputs.
Run lint against our examples (this is a noop, we just calculate task hash for this task) `turbo lint --filter=turborepo-examples`. 
Main:
This PR:
Closes TURBO-2234
=> perf: parse and walk globs in parallel

crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/error.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-auth/src/ui/mod.rs, crates/turborepo-vercel-api/src/token.rs
Found a path in which a token can be invalid but we claim it isn't. The user would have to run `turbo logout` and then login to get a new token.
1. Login
2. Go to Vercel account or whatever API issues tokens and delete the token (invalidate it)
3. run `turbo login` again
4. Ensure that login process proceeds as normal
Closes TURBO-2334
=> fix: do better validation for existing tokens

cli/Makefile
One step at a time
Closes TURBO-2367
=> chore(ci): remove Makefile targets to build Go binaries

.github/workflows/turborepo-release.yml
Example of where this was not showing anything: https://github.com/vercel/turbo/actions/runs/7905083773/job/21576872573#step:7:1
Closes TURBO-2366
=> fix(ci): fix reference to created branch during release

Cargo.lock, crates/turborepo-dirs/Cargo.toml, crates/turborepo-dirs/src/lib.rs
Add possibility for errors in `turborepo-dirs`.
=> add error enum to `turborepo-dirs`

crates/turborepo-lib/src/gitignore.rs
Clippy be clippin again
The tests still run
Closes TURBO-2369
=> fix: Clippy errors

crates/node-file-trace/src/lib.rs, crates/turbo-tasks-fetch/tests/fetch.rs, crates/turbo-tasks-fs/examples/hash_directory.rs, crates/turbo-tasks-fs/examples/hash_glob.rs, crates/turbo-tasks-fs/src/embed/dir.rs, crates/turbo-tasks-fs/src/embed/file.rs, crates/turbo-tasks-fs/src/lib.rs, crates/turbopack-cli/src/util.rs, crates/turbopack-tests/tests/execution.rs, crates/turbopack-tests/tests/snapshot.rs, crates/turbopack/benches/node_file_trace.rs, crates/turbopack/examples/turbopack.rs, crates/turbopack/tests/node-file-trace.rs
This PR allows diskfilesystem to specify certain subpath to not to cause invalidations.
Notify doesn't support actively unwatching subpath yet, so this still setup the watcher normally - only the invalidation won't be notified for the turbopack.
Closes PACK-2495
=> feat(tasks-fs): allow to skip subpath invalidation

crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/globwatcher.rs, crates/turborepo-lib/src/daemon/mod.rs, crates/turborepo-lib/src/daemon/server.rs
The daemon documentation was a little out of date. I added some docs about the architecture. Also added some docs to cookies since they're not a commonly known concept.
Closes TURBO-2364
=> docs: Refresh daemon documentation

crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-lib/src/commands/link.rs
In an effort to make things more modular and easier to implement for tests, we should make a less heavy client and instead have a base client with multiple specialty clients.
All tests currently pass - all logic should essentially be the same
Closes TURBO-2365
=> Break up Client trait

Cargo.lock, crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/globwatcher.rs, crates/turborepo-filewatch/src/lib.rs, crates/turborepo-filewatch/src/optional_watch.rs, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/package_discovery/mod.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lsp/src/lib.rs, crates/turborepo-repository/Cargo.toml, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-repository/src/package_json.rs
This is a PR for speeding up the daemon startup and setting up good practices for differentiating between data and service dependencies. To clarify the difference, file watching _service_ should start up immediately in an unavailable state, while things that need it can immediately take dependencies on its 'potentially-available' data. This also has a side-effect of fixing up our package discovery watcher as it makes the data flow a lot cleaner and ensures that the daemon can report data is unavailable when it is recalculating (using [`FutureExt::now_or_never`](https://docs.rs/futures/latest/futures/future/trait.FutureExt.html#method.now_or_never)) as well as cascading unavailable when parts of the system are no longer up to date. If a dependency wishes to wait for the data, then it can …
=> Improve daemon startup times

crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/process/mod.rs
This PR fixes an unintended behavior where an orphaned process could result in `turbo` not exiting.
Hitting this behavior required a few things:
- the user defined task spawns it's own child process that inherits stdout/stderr e.g. `sh -c "sleep 10"` will start a child process `sleep 10`
- an external program kills the parent in a way that doesn't allow it to clean up children e.g. `SIGKILL`
Use of `child.wait_with_piped_outputs` would then hang until the orphaned process exits as `stdout`/`stderr` are kept open by the orphan. We work around this by additionally checking if the child has exited and if it wasn't a successful exit we abort the reading of stdout/stderr.
We will still read stdout/stderr to completion if the parent process exits with 0 as it might intentional to have the …
=> fix: reading output from orphan process

crates/turborepo-lib/src/shim.rs, package.json, pnpm-lock.yaml
Turns out when I upgraded us, it broke the rustdoc deployment. Pinning to 1.0.2 for now.
Closes TURBO-2384
=> fix(rustdoc): Reverting back to rust-1.0.2-nightly

crates/turborepo-lsp/src/lib.rs, packages/turbo-vsc/src/extension.ts
Missed the turboPath override for this one. Also added some new features, and fixed another issue in the process:
- downgrade `^` lint to HINT
- detect missing packages in dependsOn
- detect circular dependsOn
- respect turboPath when running commands in the terminal
Closes https://github.com/vercel/turbo/issues/7394
Closes https://github.com/vercel/turbo/issues/7395
- boot up LSP
- override the turboPath
- run a command by clicking on it
- notice it is using your overridden turbo to do so
- notice the `^` is downgraded to a hint
- notice that missing tasks in dependsOn are now reported
Closes TURBO-2373
=> make turbo extension use `turboPath` for commands

crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/optional_watch.rs, crates/turborepo-filewatch/src/package_watcher.rs
We have two types of APIs in the daemon, one is request-based, and one is 'watch-based'. In the first case, a request comes in from the system and we want to make sure that the answer that is given has observed at least the filesystem events up to the point of the request. In the second case, there is constantly updating state (ie, in response to filesystem changes) that also needs to be validated against some cookie index.
CookiedOptionalWatch provides an API around some of the more complex data dependencies, making sure that complicated derived state is able to easily respect cookies when their values are requested. A cookie watch can have siblings from the same source, or children, which effectively composes two cookie watches. This is necessary because the file watching will be …
=> Add optionalwatch cookie support

crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/login.rs, turborepo-tests/integration/tests/turbo-help.t
=> chore: add force flag to login command

Cargo.lock, Cargo.toml
Update SWC crates, to apply https://github.com/swc-project/swc/pull/8647
See https://github.com/vercel/next.js/pull/62222. It's next.js counterpart.
Closes PACK-2530
=> Update `swc_core` to `v0.90.10`

Cargo.lock, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/daemon/bump_timeout_layer.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/default_timeout_layer.rs, crates/turborepo-lib/src/daemon/mod.rs, crates/turborepo-lib/src/daemon/proto/turbod.proto, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/package_discovery/mod.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lsp/src/lib.rs, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-telemetry/src/events/mod.rs
We have a few integration points with the daemon, this PR ensures they are all nicely handled.
Closes TURBO-2319
=> Audit daemon error paths and ensure we are doing everything we can to handle

crates/turbopack-css/src/process.rs
Fix `pure` lint in `lightningcss` mode. `lightningcss` does not provide location information of selectors, so we cannot provide source location. That's limitation of `cssparser` and `selectors` from `servo` project. It was the reason I didn't use them while building `swc_css`. As a last resort, we can use `Debug` implementation to print the selectors.
Trying it on the internal apps is the best way.
Closes PACK-2546
=> fix(turbopack): Fix `pure` lint for CSS Modules in lightningcss mode

crates/turbopack-ecmascript/src/tree_shake/tests.rs, crates/turbopack/tests/node-file-trace.rs, crates/turborepo-paths/src/absolute_system_path.rs, crates/turborepo-wax/src/walk/mod.rs, packages/turbo-repository/rust/src/lib.rs
Clippy be clippin
Closes TURBO-2399
=> chore: Clippy strikes again

crates/turborepo-lib/src/tracing.rs
Closes https://github.com/vercel/turbo/issues/7418 as [request warns on all parse errors](https://github.com/seanmonstar/reqwest/blob/master/src/async_impl/client.rs#L489). As the comment points out, many systems have ancient certs that aren't worth erroring on parse failures. If they needed those certs, then we'll error when actually sending the HTTPS request.
Since I'm here, I'm also upping the underlying `hyper`/`h2` crate levels to `warn` as they both produce a wild amount of debug logs that aren't useful for us or our users.
This cuts out a little over 100 lines from a short run:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ wc -l ~/Desktop/before.txt ~/Desktop/after.txt
292 /Users/olszewski/Desktop/before.txt
186 /Users/olszewski/Desktop/after.txt
478 total …
```
=> chore: lower log level for noisy crates

crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/globwatcher.rs
Some quick renaming to make some stuff a little clearer
Closes TURBO-2403
=> chore: Rename daemon code

Cargo.lock, package.json, pnpm-lock.yaml
Keeps being annoying by using too much disk space (1.4GB) and [interfering with GitHub actions cross compilation](https://github.com/vercel/turbo/actions/runs/7991485363/job/21822744158#step:7:24)
It's now getting installed via the custom install command (`pnpm add -w -O rust@1.0.2-nightly`) by the vercel builder
Closes PACK-2565
=> chore: remove "rust" npm package

crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs
Some more modularization and better checking of validity for tokens.
Try logins as normal, then login while logged in. If you can expire a token manually, try logging in again and it should do the normal login route again.
Closes TURBO-2391
=> fix: More robust token validation

crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/mod.rs
We were previously logging to a file outside the repo. This made it rather annoying to find, especially if the daemon is not running. Now we log to the `.turbo/daemon` folder inside the repository. Also, on `turbo daemon logs`, if the daemon isn't running, we fall back to looking for the latest file in `.turbo/daemon`.
Closes TURBO-2417
=> chore: Change daemon log location to be in repo

crates/turborepo-errors/src/lib.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/summary/task.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/parser.rs, docs/pages/messages/missing-root-task-in-turbo-json.mdx, turborepo-tests/integration/tests/bad-turbo-json.t, turborepo-tests/integration/tests/config.t, turborepo-tests/integration/tests/dry-json/monorepo.t, turborepo-tests/integration/tests/run/missing-tasks.t, turborepo-tests/integration/tests/task-dependencies/workspace-tasks.t
Improved error printing a little bit.
- Ported some engine/package graph errors around task dependencies. Involved threading through span info into the engine. We have to be a little careful to not hash `Span<TaskDefinition>` because sometimes the tasks are equal, but the span info is *not*.
- Added a file name to the error output. Right now we only use error output for turbo.json but eventually we might show errors in package.json
Closes TURBO-2393
=> feat: More errors work

crates/turbopack-core/src/chunk/mod.rs
`graph_node_to_referenced_nodes` no longer depends on `available_chunk_items` (which change for every dynamic import/page)
Instead `graph_node_to_referenced_nodes_with_available_chunk_items` is used when there are `available_chunk_items`. This calls the cached `graph_node_to_referenced_nodes` and modifies the response to respect `available_chunk_items`
This allows to partially cache graph walk for chunking in case of async imports.
Closes PACK-2585
=> split graph_node_to_referenced_nodes into cacheable and non-cacheable parts

docs/pages/repo/docs/reference/command-line-reference/run.mdx
As of https://github.com/vercel/turbo/pull/6779 we no longer need verbosity to be set when generating a profile.
👀 
Closes TURBO-2447
=> chore: update docs to no longer suggest verbosity for `--profile`

Cargo.lock, Cargo.toml, crates/turbopack-tests/tests/snapshot/css/css-legacy-nesting/output/crates_turbopack-tests_tests_snapshot_css_css-legacy-nesting_input_index_8e60f2.js
Update swc crates to apply https://github.com/swc-project/swc/pull/8657
next.js counterpart: https://github.com/vercel/next.js/pull/62518
Closes PACK-2595
=> Update `swc_core` to `v0.90.12`

crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-core/src/resolve/node.rs, crates/turbopack-core/src/resolve/options.rs, crates/turbopack-ecmascript/src/typescript/resolve.rs, crates/turbopack/src/resolve.rs
only main fields should be resolved in folders, the exports field should only be resolved for module requests
Closes PACK-2524
=> fix(turbopack-core): don't resolve exports field in folders

crates/turborepo-auth/src/auth/login.rs
Conditionals are hard.
`turbo logout`
`turbo login -f` <- Only 1 "authorize" popup (`-f` to skip checking for vc token)
`turbo login -f` <- Should still only be one login (`-f` to skip checking for vc token)
Closes TURBO-2418
=> fix: Remove extra login popup for Vercel

crates/turborepo-api-client/src/lib.rs
I was getting the following error
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev logout                 
>>> Logged out
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev login --sso-team=vercel
× Error making HTTP request: HTTP status server error (508 Loop Detected) for url (https://vercel.com/api/v2/team?teamId=vercel)
╰─▶ HTTP status server error (508 Loop Detected) for url (https://vercel.com/api/v2/team?teamId=vercel)
```
Checking the [docs](https://vercel.com/docs/rest-api/endpoints/teams#get-a-team) we're hitting a non-existent endpoint and incorrectly passing path parameters as query parameters. This PR fixes our `get_team` API usage.
Note: this does not fix other issues with the Vercel token workflow as `turbo link` and …
=> fix: correctly call teams api

crates/turborepo-paths/src/absolute_system_path.rs
For parsing `.npmrc` we don't want to error if it isn't there. Using `read_existing_to_string_or` doesn't feel right to me as it would require using a magic value to signify none e.g. `npmrc_path.read_existing_to_string_or(Ok("missing"))?` and then checking that value.
If nobody objects, I'm happy moving uses of `read_existing_to_string_or` to `read_existing_to_string` in a future PR.
Existing unit tests, new unit tests
Closes TURBO-2452
=> chore: add read_existing_to_string

crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/parser.rs
Closes #7522
All this does is skip us throwing if we encounter a top level `//` key in the `turbo.json`. I personally thinks this makes some sense since the `//` key is used across the JS ecosystem for comments in JSON files. We do support JSONC for `turbo.json`, but that might not be immediately obvious without reading documentation.
Closes TURBO-2462
=> feat: allow for faux comments at top level of turbo.json

crates/turbo-tasks-fs/src/lib.rs, crates/turbo-tasks-fs/src/util.rs
Fixes the apollo `node_file_trace` test on Windows
It includes a source map with `"sourceRoot":"c:/Projects/decorators/deprecated/src/"` which would get joined to the current directory, leading to an invalid path on Windows.
Closes PACK-2562
=> fix(turbopack): catch invalid source map paths

crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/dep_splitter.rs, crates/turborepo-repository/src/package_graph/mod.rs
Fixes #6744 
I highly suggest reviewing each commit on it's own as the code move done in the first commit makes the cumulative diff hard to understand. I wanted to clean up this code a bit as we'll need to extend it further for supporting https://github.com/vercel/turbo/issues/7188
This adds support for the PNPM feature of [aliasing a package via path](https://pnpm.io/workspaces#referencing-workspace-packages-through-their-relative-path). 
The slightly tricky part of this is that there are many valid specifiers for the `workspace:` protocol. We currently support `workspace:1.2.3`, `workspace:*`, [`workspace:bar@*`](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases), `workspace:../path/to/package`.
Added unit tests for the case of a dependency of the form `"foo": …
=> fix: support pnpm workspace path aliasing

.github/workflows/turborepo-native-lib-test.yml
This was preventing these tests from running when turbo core source code changes.
Follow up from: #7374
Discovered in https://github.com/vercel/turbo/pull/7549 that these tests are never running when source changes :(
Closes TURBO-2477
=> fix(ci) remove filter when running @turbo/repository tests

crates/turborepo-repository/src/package_graph/dep_splitter.rs
#7512 included an unnecessary import
No unused import warnings
Closes TURBO-2484
=> chore: remove unused import from dep_splitter

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lib/src/run/scope/mod.rs, turborepo-tests/integration/tests/filter-run.t
We didn't respect the `globalDependencies` field in `turbo.json` when determining changed packages. This meant that you could have a global dependency changed, but turbo wouldn't run.
Closes TURBO-2486
=> fix: Respect globalDependencies when determining changed packages

Cargo.lock, crates/turbopack-css/src/global_asset.rs, crates/turbopack-node/Cargo.toml, crates/turbopack-node/js/src/transforms/postcss.ts, crates/turbopack-node/src/transforms/postcss.rs
It still gets bundled if it's not a JavaScript config, but if it is, we now import it via `__turbopack_external_import__` (`import()`).
We use `import()` instead of `require` to handle ESM configs (`.mjs`).
This is similar to `postcss-load-config`.
Closes PACK-2452
=> fix(turbopack-node): don't bundle postcss config

crates/turborepo-filewatch/src/cookies.rs
- Extracts the cookie-related changes from #7183 to try to slim down that PR a bit
Closes TURBO-2480
=> feat(Turborepo): Renaming, additional cookiewriter constructor

crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs
Because `vc logout` doesn't remove it's pseudo-comments, deserialize breaks when trying to extract the token.
This PR fixes that by setting the deserialized struct to have an optional token field and then we make sure the extraction didn't encounter an error _and_ that the token is `Some`.
First, make sure you build the branch.
1. `vc login && vc logout` -> make the Vercel auth file and then remove the `token` field. You could do this manually as well.
2. `turbo login` -> Shouldn't error and ask for a new login.
Closes TURBO-2485
=> fix: vercel auth file borks login

Cargo.lock, crates/turbopack-node/Cargo.toml, crates/turbopack-node/js/src/ipc/evaluate.ts, crates/turbopack-node/js/src/ipc/index.ts, crates/turbopack-node/js/src/transforms/postcss.ts, crates/turbopack-node/js/src/transforms/webpack-loaders.ts, crates/turbopack-node/src/evaluate.rs, crates/turbopack-node/src/lib.rs, crates/turbopack-node/src/pool.rs, crates/turbopack-node/src/transforms/postcss.rs, crates/turbopack-node/src/transforms/webpack.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/mod.rs
* Increase Node.js execution timeout
* Add ready signal to node.js pool
* add tracing for Node.js bootstrapping
* fixes a tracing bug, where queue time is accounted towards Node.js execution
* refactor evaluation to allow custom message handlers
* add getResolve to webpack loader context
Closes PACK-2633
=> add getResolve to webpack loader context

crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-tests/tests/execution/turbopack/resolving/alias-field/input/index.js, crates/turbopack-tests/tests/execution/turbopack/resolving/alias-field/input/node_modules/other-package/index.js, crates/turbopack-tests/tests/execution/turbopack/resolving/alias-field/input/node_modules/other-package/sub-path.js, crates/turbopack-tests/tests/execution/turbopack/resolving/alias-field/input/node_modules/package/dir/index.js, crates/turbopack-tests/tests/execution/turbopack/resolving/alias-field/input/node_modules/package/package.json
Handles the case where alias field is circular:
```
"browser": {
"@smithy/chunked-blob-reader": "@smithy/chunked-blob-reader"
},
```
added test case
Closes PACK-2637
=> Ignore circular aliasing with alias field

crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/login_server.rs
Success page url was wrong and re-prompting with the same authorize page, even though it did nothing.
String formatting is hard sometimes.
1. `turbo logout` -> ensure you have no tokens that'll prompt the "Existing token found!" check
2. `turbo login` -> get the login page
3. Ensure that when you click `Authorize`, and it works, that the second page is the success page.
Closes TURBO-2488
=> fix: login success page redirect

crates/turborepo-auth/src/auth/logout.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/error.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-lib/src/commands/logout.rs, crates/turborepo-lib/src/commands/mod.rs, turborepo-tests/helpers/mock_turbo_config.sh
=> chore: move logout functionality into auth crate

crates/turborepo-auth/src/lib.rs, crates/turborepo-lib/src/config.rs
No need to clone - makes sense to pass in a borrowed path.
Closes TURBO-2498
=> chore: Change  to use borrowed path

Cargo.lock, crates/turbo-tasks/Cargo.toml, crates/turbo-tasks/src/magic_any.rs, crates/turbo-tasks/src/task/task_input.rs
Reverts vercel/turbo#7206
Closes PACK-2640
=> Revert "Remove mopa dependency in turbo-tasks"

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/tracing.rs
This changes the config from hard-coded to take the setup from your env vars, defaulting to info if unset. It also prevents the daemon from logging span lines. It also adds the ability to clean logs when running `daemon clean` so that users can more easily manage their logs.
Run `turbo daemon` with `TURBO_LOG_VERBOSITY` verbosity unset or set to trace to observe the difference. Run `turbo clean` and see the logs have been removed.
Closes TURBO-2450
=> Handle logging story better on daemon

crates/turborepo-auth/src/auth/sso.rs
Forgot to do the conditional check in the sso login.
Do a couple SSO logins for Vercel (no `--api` flag), the page shouldn't pop up twice.
Closes TURBO-2502
=> fix: sso login duplicate popup

Cargo.lock, crates/turborepo-lib/src/commands/telemetry.rs, crates/turborepo-telemetry/Cargo.toml, crates/turborepo-telemetry/src/config.rs, crates/turborepo-telemetry/src/lib.rs
- switch to Turbopath to handle paths, rather than strings / `fs` module
- create separate constructors that use an explicit config path vs one that uses the default
- prep for refactor to move test code into test module to better control filesystem during test execution
Closes TURBO-2495
=> chore(Turborepo): refactor telemetry to use turbopath

Cargo.lock, crates/turborepo-telemetry/Cargo.toml, crates/turborepo-telemetry/src/config.rs, crates/turborepo-telemetry/src/lib.rs
- Let unit tests manage their own temp directories so we can isolate source of test flakiness, which seems to be filesystem-based
Updated tests to create their own temp directories
Closes TURBO-2497
=> chore(Turborepo): move test filesystem setup into test code

docs/pages/repo/docs/handbook/sharing-code/internal-packages.mdx
Added the package version to the internal packages docs example. Without version in the shared internal package, Yarn will attempt to fetch from the npm registry leading to rabbitholes like this one: https://github.com/vercel/turbo/issues/6322
Confirm docs load with new text.
=> Add version to package in internal packages docs for yarn

crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/package_graph/builder.rs
- Switch some daemon tests to fully use filesystem, rather than partially using it
- Remove some generics that are no longer necessary
- Clean up some no-longer-needed clippy annotations
Modified tests to not use a mock
Closes TURBO-2513
=> chore(Turborepo): Switch tests to use filesystem, remove unused generics

crates/turborepo-cache/src/cache_archive/create.rs, crates/turborepo-cache/src/cache_archive/restore.rs, crates/turborepo-cache/src/cache_archive/restore_directory.rs
Fixes #7410 
This is just #6662, but applied to directories. See [Entry::path](https://docs.rs/tar/latest/tar/struct.Entry.html#method.path) for explanation as to why one should never rely on a header's path.
In the first commit added a failing unit test, test passes after fix.
Also tested against reproduction: https://github.com/trappar/turbo-cache-missing-output-files
Just need to update `reproduce-issue.sh` to use the `turbo` in this branch:
```
...
Diffing the original force-build's .next directory with the cache-hit-build's .next directory
[0 olszewski@chriss-mbp] /tmp/turbo-cache-missing-output-files $ 
```
Closes TURBO-2532
=> fix(cache): fix restoration issues of directories with very long paths

examples/basic/packages/ui/.eslintrc.js, examples/with-yarn/packages/ui/.eslintrc.js
As it turns out, where the parser resolves to depends on package manager, project setup, configuration, etc. Let's set  set the `tsconfigRootDir` to be __dirname to make sure it uses exactly where we want.
Closes TURBO-2540
=> Guarantee typescript-eslint parser resolving.

crates/turborepo-cache/src/cache_archive/create.rs, crates/turborepo-cache/src/cache_archive/restore.rs
Fix for secondary problem discovered in #7410
Again, reading the docs for [`Entry::link_name`](https://docs.rs/tar/latest/tar/struct.Entry.html#method.link_name) it is recommended against using a header as it might have an incomplete/differing link name from the actual entry. `restore_symlink` already uses this method over accessing the link name via the header so it doesn't need to be updated.
Added failing unit test in first commit. The test adds a symlink to a directory with a long path that gets restored before the target has been restored. This results in us hitting the `topologically_restore_symlinks` codepath which contained the bug.
Also tested against updates to https://github.com/trappar/turbo-cache-missing-output-files which also trigger this behavior.
Closes TURBO-2539
=> fix(cache): restoration symlink

packages/turbo-repository/js/package.json, packages/turbo-repository/npm/darwin-arm64/package.json, packages/turbo-repository/npm/darwin-x64/package.json, packages/turbo-repository/npm/linux-arm64-gnu/package.json, packages/turbo-repository/npm/linux-arm64-musl/package.json, packages/turbo-repository/npm/linux-x64-gnu/package.json, packages/turbo-repository/npm/linux-x64-musl/package.json, packages/turbo-repository/npm/win32-arm64-msvc/package.json, packages/turbo-repository/npm/win32-x64-msvc/package.json
=> chore(@turbo/repository): bump version to 0.0.1-canary.8

.github/workflows/turborepo-library-release.yml
Can't differentiate the two musl builds because they have a long target. Validated fix in https://github.com/vercel/turbo/actions/runs/8167045370
| before | after |
| --- | --- |
| ![CleanShot 2024-03-05 at 22 41 31@2x](https://github.com/vercel/turbo/assets/490968/4adb9470-727d-4ce7-bbef-f5ec62fd893b) | ![CleanShot 2024-03-05 at 22 42 27@2x](https://github.com/vercel/turbo/assets/490968/4b448929-c037-4c13-9d1e-e7063f21bc21) |
=> chore(ci): reorder matrix fields so generated name is easier to read

crates/turbopack-css/src/process.rs
Closes PACK-2660
I added a test.
=> fix: Fix purity lint for CSS Modules in swc mode

crates/turborepo-auth/src/lib.rs
Some unit tests for caching status.
The tests all pass
Closes TURBO-2501
=> fix: add more caching status tests

crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/references/dynamic_expression.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-tests/tests/snapshot.rs, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/input/index.js, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1001__ import(FreeVar(Math)[__quo__ra-fcce98.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1002__ require(FreeVar(Math)[__quo__r-fa7bb4.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1004__ fs.readFileSync(FreeVar(Math)[-45dc7a.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1004__ fs.readFileSync(FreeVar(Math)[-d5af53.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1005__ child_process.spawnSync(FreeVa-fa7b47.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1005__ child_process.spawnSync(__-a30479.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1005__ child_process.spawnSync(__quo_-a93044.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/issues/__l___lint TP1201__ new URL(Variable(unknown##2), -f5ba3f.txt, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/options.json, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/output/79fb1_turbopack-tests_tests_snapshot_dynamic-request_very-dynamic_input_index_0d92c3.js, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/output/79fb1_turbopack-tests_tests_snapshot_dynamic-request_very-dynamic_input_index_0d92c3.js.map, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/output/79fb1_turbopack-tests_tests_snapshot_dynamic-request_very-dynamic_input_index_4598f4.js, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/output/79fb1_turbopack-tests_tests_snapshot_dynamic-request_very-dynamic_input_index_c551c8.js, crates/turbopack-tests/tests/snapshot/dynamic-request/very-dynamic/output/79fb1_turbopack-tests_tests_snapshot_dynamic-request_very-dynamic_input_index_c551c8.js.map, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_options_context.rs
they no longer lead to an additional module not found error
Closes PACK-2673
=> very dynamic requests will only lead to a warning

.github/actions/setup-rust/action.yml, .github/workflows/turborepo-library-release.yml
Cherry-picked from #7224
Working build: https://github.com/vercel/turbo/actions/runs/8175903965/job/22354109467
=> fix(ci): turborepo library release workflow

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs
#6008 removed the actual flag, but the impl for silencing all run output still existed. This PR removes that param and the underlying implementation.
👀 
Closes TURBO-2548
=> chore: clean up silent flag impl

packages/turbo-repository/js/package.json, packages/turbo-repository/npm/darwin-arm64/package.json, packages/turbo-repository/npm/darwin-x64/package.json, packages/turbo-repository/npm/linux-arm64-gnu/package.json, packages/turbo-repository/npm/linux-arm64-musl/package.json, packages/turbo-repository/npm/linux-x64-gnu/package.json, packages/turbo-repository/npm/linux-x64-musl/package.json, packages/turbo-repository/npm/win32-arm64-msvc/package.json, packages/turbo-repository/npm/win32-x64-msvc/package.json
=> chore(@turbo/repository): bump to 0.0.1-canary.9

crates/turborepo-lib/src/global_deps_package_change_mapper.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/run/scope/change_detector.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-repository/src/change_mapper.rs, packages/turbo-repository/rust/src/lib.rs
I forgot to do this in #7549, whoops. Renames to PackageChangeMapper according to PR feedback.
Closes TURBO-2559
=> refactor(turborepo): Renaming -PackageDetector to -PackageChangeMapper

crates/turborepo-vt100/src/lib.rs, crates/turborepo-vt100/tests/helpers/mod.rs, crates/turborepo-vt100/tests/window_contents.rs
Silence these warnings to reduce noise on builds.
I chose to silence instead of fix in order to avoid a possible future headache when trying to either un-vendor the crate or cherry pick upstream commits. 
No lints on `cargo build -p vt100` or `cargo build -p vt100 --tests`
Closes TURBO-2551
=> chore: silence lint warnings from vt100 crate

Cargo.lock, crates/turborepo-vt100/Cargo.toml, crates/turborepo-vt100/src/lib.rs, crates/turborepo-vt100/tests/attr.rs, crates/turborepo-vt100/tests/basic.rs, crates/turborepo-vt100/tests/control.rs, crates/turborepo-vt100/tests/csi.rs, crates/turborepo-vt100/tests/escape.rs, crates/turborepo-vt100/tests/helpers/fixtures.rs, crates/turborepo-vt100/tests/helpers/mod.rs, crates/turborepo-vt100/tests/init.rs, crates/turborepo-vt100/tests/mode.rs, crates/turborepo-vt100/tests/osc.rs, crates/turborepo-vt100/tests/processing.rs, crates/turborepo-vt100/tests/quickcheck.rs, crates/turborepo-vt100/tests/scroll.rs, crates/turborepo-vt100/tests/split-escapes.rs, crates/turborepo-vt100/tests/text.rs, crates/turborepo-vt100/tests/weird.rs, crates/turborepo-vt100/tests/window_contents.rs, crates/turborepo-vt100/tests/write.rs
Renaming our vendored `vt100` crate to avoid confusion since `tui_term` comes with prebuilt `vt100` integration, but won't work with our vendored crate. 
CI
Closes TURBO-2553
=> chore: rename vendored vt100 crate

Cargo.lock, Cargo.toml
Update SWC crates
next.js counterpart: https://github.com/vercel/next.js/pull/62924
Closes PACK-2670
=> build: Update `swc_core` to `v0.90.17`

crates/turbopack-build/src/chunking_context.rs, crates/turbopack-build/src/ecmascript/node/chunk.rs, crates/turbopack-build/src/ecmascript/node/content.rs, crates/turbopack-build/src/ecmascript/node/entry/chunk.rs, crates/turbopack-build/src/ecmascript/node/entry/runtime.rs, crates/turbopack-build/src/lib.rs, crates/turbopack-cli/src/build/mod.rs, crates/turbopack-cli/src/dev/mod.rs, crates/turbopack-cli/src/dev/web_entry_source.rs, crates/turbopack-dev/src/chunking_context.rs, crates/turbopack-dev/src/ecmascript/chunk.rs, crates/turbopack-dev/src/ecmascript/content.rs, crates/turbopack-dev/src/ecmascript/evaluate/chunk.rs, crates/turbopack-dev/src/ecmascript/list/asset.rs, crates/turbopack-dev/src/lib.rs, crates/turbopack-tests/tests/execution.rs, crates/turbopack-tests/tests/snapshot.rs
As discussed with @sokra, this aligns the names to what they're used for.
Renaming the packages in a follow-up PR.
=> Rename `BuildChunkingContext` -> `NodeJsChunkingContext` and `DevChunkingContext` -> `BrowserChunkingContext`

crates/turborepo-lib/src/commands/login.rs, crates/turborepo-telemetry/src/events/command.rs
We want to know how often the login command is succeeding. This simply says "true" or "false" if the login succeeds or fails.
Closes TURBO-2560
=> feat: Add success rate telemetry for login

crates/turborepo-repository/src/change_mapper/mod.rs, crates/turborepo-repository/src/change_mapper/package.rs
This was also previously suggested and I thought it would introduce a circular dependency. Turns out it doesn't as long as you don't use any turbo.json code. By moving them to `turborepo-repository` we can clean up the file layout and also use them in `turborepo-filewatching`
Closes TURBO-2561
=> chore(turborepo): Move PackageChangeMappers to turborepo-repository

crates/turborepo-api-client/src/error.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/logout.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/logout.rs, turborepo-tests/integration/tests/turbo-help.t
Allows for `turbo logout --invalidate` which should call to the API to actually remove the token from the account.
Closes TURBO-2406
=> feature: Add invalidate flag to logout

crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-repository/src/discovery.rs
- Set a clientside timeout at the GRPC level for package discovery
- Refactor FallbackDiscovery to not use Option, as well as drop the impl for Option
- Only use FallbackDiscovery when we actually want to have a fallback
- Throw an error in the case where we've requested only daemon usage, but the daemon is unavailable
Closes TURBO-2549
=> chore(Turborepo): refactor client side of daemon-backed package discovery

crates/turbopack-browser/src/chunking_context.rs, crates/turbopack-browser/src/ecmascript/content.rs, crates/turbopack-ecmascript/Cargo.toml, crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/minify.rs, crates/turbopack-nodejs/Cargo.toml, crates/turbopack-nodejs/src/chunking_context.rs, crates/turbopack-nodejs/src/ecmascript/mod.rs, crates/turbopack-nodejs/src/ecmascript/node/content.rs
Ensures minifier runs for browser code.
Moves minify.rs to turbopack-ecmascript as it's shared between turbopack-nodejs and turbopack-browser.
=> Add MinifyType to BrowserChunkingContext

Cargo.lock, crates/turborepo-auth/src/auth/logout.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/error.rs, crates/turborepo-dirs/Cargo.toml, crates/turborepo-dirs/src/lib.rs, crates/turborepo-lib/src/commands/login.rs, crates/turborepo-lib/src/commands/logout.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-telemetry/src/config.rs
`turbo logout` wasn't actually logging out with the vercel token.
Also refactored the config code to produce an `AbsoluteSystemPathBuf` so we don't have to keep on doing that. There are other refactors that could be done but I wanted to keep this relatively small.
Closes TURBO-2570
=> fix(turborepo): Logout

crates/turbopack-node/js/src/transforms/webpack-loaders.ts
https://vercel.slack.com/archives/C03EWR7LGEN/p1709598188040829?thread_ts=1709595370.496449&cid=C03EWR7LGEN
One of the loader uses context's `_module` property, puts an empty one to avoid runtime exception at least.
Closes PACK-2656
=> feat(turbopack): add missing webpack context property

.github/workflows/turborepo-library-release.yml, package.json, pnpm-lock.yaml
The `@turbo/repository` release process was inadvertently depending on the rust npm package. This PR adds back a working version of that package to unblock releases until we can update the release process to no longer rely on that package, at which point we can remove it again.
Also adds the github token to the rust setup so we don't get rate-limited.
Tested via dry run on personal fork, all platforms build, manually verified alpine on arm64.
Closes TURBO-2572
=> fix(Turborepo): Add back a working version of the rust npm package

packages/turbo-vsc/package.json, packages/turbo-vsc/src/extension.ts
As identified in #7425, we can't always assume the people are able to install turbo globally, meaning we can't rely on turbo's build-in resolution in call cases. As a fallback, this will attempt to resolve the path from your package manager. It will _still_ surface a prompt to install global turbo however, unless you silence the recommendation with the "Use Local Turbo" setting. 
Also bundled in with this change is an attempt to support asdf as well by sourcing its script before finding the turbo executable.
Closes TURBO-2564
=> [LSP] Attempt to detect local turbo path from package manager as fallback

crates/turbopack/src/transition/full_context_transition.rs, crates/turbopack/src/transition/mod.rs
Add `FullContextTransition` to transition to a completely different ModuleAssetContext without inheriting the transitions
Closes PACK-2696
=> add FullContextTransition

crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/daemon/server.rs
- Only create a CookieWriter once, use clone from then on to ensure we have the right directory
- Fixes bug where we passed the wrong directory into a CookieWriter
Manual verification that the cookie directory is now correct
Closes TURBO-2566
=> fix(Turborepo): Fix cookie directory

crates/turbopack-resolve/src/typescript.rs
Simple port to https://github.com/vercel/next.js/pull/11322/files#diff-f80cef26fea96d9530aab29fcaa89b2cc296a54a826a367254997d2885727d33R179.
Maybe we can consider to expose this as sort of configuration predicate for specific filter, but the depth of this call is somewhat deep from resolve context and so far there is only one cases (excluding d.ts), so followed same practices to exising next.js behavior.
Closes PACK-2701
=> feat(resolve): skip alias to d.ts

crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/global_hash.rs, crates/turborepo-lib/src/run/mod.rs
We're going to need access to the `Run` struct in watch mode, but without the actual execution part. To facilitate this, I'm splitting it up into a `RunBuilder` that builds all of the necessary data structures and a `Run` that executes the build.
Closes TURBO-2583
=> refactor(turborepo): Split up `Run` into `RunBuilder` and `Run`

crates/turborepo-lib/src/run/cache.rs, crates/turborepo-ui/src/logs.rs, crates/turborepo-ui/tests/threads.rs
We don't need to restrict the "stdout" writer to be a `PrefixedWriter` as there are cases where we don't want the prefix added to a task's output when rendered.
👀 
Closes TURBO-2578
=> chore: generalize log writer

docs/lib/useTurborepoMinutesSaved.ts, docs/turbo/generators/utils.ts
Move the client token to env var so we can more easily rotate it
=> chore(docs): move client token to env var

crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/logs.rs, crates/turborepo-ui/src/prefixed.rs
This PR removes the cache from using concrete implementations for terminal output and instead have it take a generic writer. 
This prefactor is needed for the TUI as we cannot just write to terminal as the cursor could be in an unexpected position.
Our existing integration tests capture this behavior pretty well. Ran some tasks to double check that things appeared identical.
Closes TURBO-2596
=> chore: generalize cache terminal output

crates/turborepo-vt100/src/entire_screen.rs, crates/turborepo-vt100/src/grid.rs, crates/turborepo-vt100/src/lib.rs, crates/turborepo-vt100/src/parser.rs, crates/turborepo-vt100/src/row.rs, crates/turborepo-vt100/tests/entire_screen.rs
In order to properly persist a task's output we need to display the full terminal contents including whatever might be in the scrollback buffer. This PR adds an alternative screen where the row index includes the scrollback rows. The `Screen` trait added in https://github.com/a-kenji/tui-term/pull/152 will be implemented for `EntireScreen` allowing for us to use this structure with the `PseudoTerminal` widget.
Added some basic unit tests to verify that scrollback gets printed.
Closes TURBO-2592
=> feat: add entire screen viewer to vt100

Cargo.lock, Cargo.toml, crates/turbopack-image/Cargo.toml, crates/turbopack-image/src/process/mod.rs
This bump (https://github.com/vercel/turbo/pull/7704/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L207) causes next-swc build due to version conflict across transitive deps.
This PR bumps up some corresponding deps to resolve those - once this lands need to create next.js one as well.
Closes PACK-2719
=> build(cargo): bump up deps, resolve build failures

crates/turbopack-ecmascript/src/references/esm/dynamic.rs
Async module detection missed this previously leading to a broken bundle.
Fixes https://github.com/vercel/next.js/issues/63164
Closes PACK-2715
=> fix(turbopack-ecmascript): use correct reference type in dynamic reference

crates/turbopack-node/src/transforms/postcss.rs
This can actually happen e. g. with next/font, which creates virtual css files that are not inside of the project directory
Closes PACK-2732
=> accept css files outside of the project as virtual assets

crates/turbopack-node/src/evaluate.rs, crates/turbopack-node/src/pool.rs
* Slow start for the concurrency of parallel booting node.js processes (1, 2, 4, ...)
* Depending on historic statistics avoid booting up a new process, but wait for one to finish computing
Loading the `/home` route on 16-core machine
Before:
```
16 x Node.js process startup 9.09s avg 568.07ms
16 x Node.js initialization 10.58s avg 660.96ms
276 x Node.js evaluation 30.17s avg 109.30ms
```
After:
```
7 x Node.js process startup 1261.79ms avg 180.26ms
7 x Node.js initialization 3.15s avg 450.21ms
276 x Node.js evaluation 29.41s avg 106.55ms
```
Closes PACK-2680
=> more efficient node.js process startup

crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/references/async_module.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/chunk_item.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs, crates/turbopack-ecmascript/src/side_effect_optimization/locals/chunk_item.rs, crates/turbopack-ecmascript/src/side_effect_optimization/locals/module.rs, crates/turbopack-ecmascript/src/side_effect_optimization/reference.rs, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/index.js, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/tla/both.js, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/tla/local.js, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/tla/package.json, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/tla/reexport.js, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/tla/reexported.js, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/tla/tla-reexported.js
Async module handling was missing for side effects optimized modules
Closes PACK-2733
=> generate correct async module handling for side effects optimization

crates/turbopack-browser/src/chunking_context.rs, crates/turbopack-browser/src/ecmascript/evaluate/chunk.rs, crates/turbopack-cli/src/build/mod.rs, crates/turbopack-cli/src/dev/mod.rs, crates/turbopack-cli/src/dev/web_entry_source.rs, crates/turbopack-ecmascript-runtime/src/runtime_type.rs, crates/turbopack-nodejs/src/chunking_context.rs, crates/turbopack-nodejs/src/ecmascript/node/entry/runtime.rs, crates/turbopack-tests/tests/execution.rs, crates/turbopack-tests/tests/snapshot.rs, crates/turbopack-tests/tests/snapshot/runtime/default_build_runtime/options.json, crates/turbopack-tests/tests/snapshot/runtime/default_dev_runtime/options.json
Currently the development Turbopack runtime is always used as production builds are not fully implemented yet. This is the first step to having a production-specific runtime by adding a distinction between Development and Production for the runtime. This PR does not implement the production runtime, it only adds the plumbing for adding the production specific runtime. The runtime implementation will follow in a later PR.
=> Add distinction between Development and Production runtime_type for Turbopack

crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-paths/src/absolute_system_path.rs
- Update timeout on package discovery RPC to be a little more lenient
- Handle entire directory moves in and out of the workspaces globs
Update package discovery test to handle an entire workspace moving.
Also did some manual verification.
Closes TURBO-2595
=> fix(Turborepo): Handle directory moves in package discovery

crates/turborepo-ui/src/prefixed.rs
At the moment, it is currently the caller's responsibility to make sure that `PrefixedWriter` is only fed a single line at a time and that writes end with a newline.
If the caller doesn't do this output can be unexpected such as:
```
prefix > one
two
three
```
or
```
prefix1 > no newline prefix2 > my log line
```
We currently call this correctly since we read child output in a [line buffered manner](https://github.com/vercel/turbo/blob/main/crates/turborepo-lib/src/process/child.rs#L614) and [inserting newlines if they're missing](https://github.com/vercel/turbo/blob/main/crates/turborepo-lib/src/process/child.rs#L636). With the move to richer output such as spinners we will no longer be waiting to see a newline to forward output. 
This PR prepares us for that future by making …
=> feat: ensure PrefixedWriter is line buffered

docs/pages/repo/docs/handbook/testing.mdx
The Testing section is really helpful, but it would be clearer by specifying exactly where each of these snippets should be placed.
Before: 
After: 
Looking forward to your thoughts and feedback.
Thanks.
=> docs: Update testing configuration documentation for clarity

docs/pages/repo/docs/getting-started/add-to-project.mdx
The docs give examples of using `build` and `type-check` commands, but the text was in `lint`.
=> docs: change texts from lint to type-check

Cargo.lock, crates/turborepo-ui/Cargo.toml, crates/turborepo-ui/src/tui/input.rs
Proper handling of a user hitting `Ctrl-C`
Since we have [ISIG](https://man7.org/linux/man-pages/man3/termios.3.html) flagged off we are in charge of generating a SIGINT when Ctrl-C is pressed.
- On unix we use [raise](https://man7.org/linux/man-pages/man3/raise.3.html) to send `SIGINT` to `turbo`
- On Windows we use [GenerateConsoleCtrlEvent](https://learn.microsoft.com/en-us/windows/console/generateconsolectrlevent) to trigger the CtrlC handler [we set here](https://github.com/vercel/turbo/blob/main/crates/turborepo-lib/src/commands/run.rs#L8)
Start up a run of turbo with `TURBO_EXPERIMENTAL_UI=true` and verify that `Ctrl-C` stops execution. It should display the same as if a `SIGINT` was sent to `turbo` via `kill`
Closes TURBO-2640
=> feat(tui) proper ctrl c

crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/pane.rs
Add ability to forward input to tasks: `Enter` will start forwarding input and `Ctrl-Z` will stop forwarding input to the selected task.
There are definitely gaps in our input forwarding, but for basic text and standard keys such as arrow keys we should do the right thing. Hopefully users do not require handling `Ctrl-Alt-Home` being correctly forwarded to the underlying tasks.
This PR does not add the ability to configure non-persistent tasks to take input
Test it out with persistent tasks e.g. `with-vite` example
https://github.com/vercel/turbo/assets/4131117/abf2263b-cbf2-44d7-9440-1c11c0e28808
Closes TURBO-2639
=> feat: add ability to forward input to tasks

crates/turbopack-ecmascript-runtime/js/src/dev/client/hmr-client.ts
Whether due to a runtime error or an apply error, it should be reloaded.
Closes PACK-2751
=> Turbopack HMR: reload on any failed HMR update

crates/turbopack-ecmascript/src/references/esm/export.rs, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/side-effects/input/node_modules/package-star/index.js
When accessing many exports of a barrel file with many `export *` it was a bit inefficient before since it was walking all star exports for every accessed export.
After this change it only creates a map of the star exports once and accessing every export only looks up the result in the map. This makes it 4 times more efficient for a file with 140 `export *`. Probably even more for bigger barrel files.
Closes PACK-2747
=> make follow reexports more efficient

crates/turborepo-api-client/src/retry.rs
For repositories with a large number of tasks we can get an `REFUSED_STREAM` on a dry run due to the sheer amount of requests we're making at once.
This PR changes it so we retry requests that failed due to a timeout or a request error which don't get promoted to a full status code.
Do a dry run with remote cache enabled on a repository with 200+ tasks. You should get a consistent number of cache hits with the PR.
Closes TURBO-2648
=> fix: retry requests that fail due to timeout or request errors

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs
Fixes https://github.com/vercel/turbo/issues/7753
- Enabled `TURBO_PREFLIGHT` env var as a config source with `1` and `true` being considered truthy
- Pipe `--preflight` CLI arg into our config
- Use `config.pipeline()` instead of directly reading value from CLI args 
Expanded unit tests to cover `TURBO_PREFLIGHT`
Closes TURBO-2650
=> feat: enable env var for preflight

crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-mdx/src/lib.rs
For the `failsafe_analyze`, make it not failable by not bubbling up the error - the error will be propagated by chunk generation anyway.
Closes PACK-2764
=> fix(mdx): allow failsafe analyze for mdxasset

crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/parser.rs
Add `experimentalUI` to `turbo.json` that is equivalent to setting `TURBO_EXPERIMENTAL_UI`
Docs update will be in separate PR to be merged on release.
Verify that TUI is used in following scenarios:
- `TURBO_EXPERIMENTAL_UI=true turbo build`
- Add `"experimentalUI": true` to `turbo.json`
Closes TURBO-2652
=> chore: add ability to configure TUI via turbo.json

crates/turbopack-nodejs/src/ecmascript/node/entry/runtime.rs, crates/turbopack-tests/tests/snapshot/basic/async_chunk_build/output/[turbopack]_runtime.js, crates/turbopack-tests/tests/snapshot/basic/ecmascript_minify/output/[turbopack]_runtime.js, crates/turbopack-tests/tests/snapshot/runtime/default_build_runtime/output/[turbopack]_runtime.js
The default for asset prefix is `"/"` and not `""`
https://github.com/vercel/next.js/pull/62134
=> fix ASSET_PREFIX

crates/turborepo-ui/src/tui/app.rs
Correctly persist bytes sent to the app. 
This PR has 3 fixes:
- Support non-utf8 logs
- Support multiline writes
- Support ANSI escape sequences
All these are achieved by putting the bytes through a `vt100` parser and rendering the resulting screen.
Future work might be to avoid emitting the ansi escape codes and construct a `Text` widget directly, but this is a larger lift as we need to stop using `console::Style` throughout the codebase.
Did a quick manual test of `PersistedWriter` to make sure writes get persisted when they should in `turbo`
Closes TURBO-2655
=> fix(ui): properly handle escape codes in persisted output

crates/turborepo-filewatch/src/package_watcher.rs
- Handle scenarios where we cannot determine package manager or workspaces globs
- Add special handling for pnpm-workspace.yaml, since all of the other package managers use package.json
Added two tests, one each for pnpm and npm, to test a basic recovery from an error state
Closes TURBO-2654
=> feat(Turborepo): handle invalid states in package watching

packages/create-turbo/package.json, packages/eslint-config-turbo/package.json, packages/eslint-plugin-turbo/package.json, packages/turbo-codemod/package.json, packages/turbo-gen/package.json, packages/turbo-ignore/package.json, packages/turbo-types/package.json, packages/turbo-workspaces/package.json, packages/turbo/package.json, version.txt
Finish the failed release from https://github.com/vercel/turbo/actions/runs/8364249288/job/22899998283#step:11:1722
Closes TURBO-2663
=> publish 1.13.0-canary.2 to registry

examples/with-vite/apps/docs/package.json, examples/with-vite/apps/web/package.json
By default [`vite`](https://vitejs.dev/guide/cli) clears the terminal upon starting the server. This is not desirable when being used via `turbo` as it will  erase output from `turbo` or other tasks that have run or are still running.
Invoking the `dev` script should no longer clear the screen.
Closes TURBO-2661
=> fix(examples): avoid clearing screen when using vite

packages/turbo-types/src/types/config.ts
Update schema with new options added in #7767 and #7755 
Note: this won't update the live schema until we bump the docs site to use a version of `@turbo/types` with the updates. Also anchors in doc links won't be valid until docs PR lands.
👀
=> chore: update turbo.json schema for interactive tasks

docs/pages/repo/docs/getting-started/from-example.mdx, docs/pages/repo/docs/index.mdx
=> Use hardcoding.

Cargo.lock, crates/turborepo-repository/Cargo.toml, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/dep_splitter.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-repository/src/package_graph/npmrc.rs
Closes https://github.com/vercel/turbo/issues/7188
Start reading `.npmrc` for `pnpm` projects in order to respect [`link-workspace-packages`](https://pnpm.io/npmrc#link-workspace-packages) which changes when workspace packages will be used.
Added unit tests for verifying that when `link-workspace-packages` is set to false the `workspace` protocol must be used for a workspace package to be considered.
Also tested against repro repo in issue:
(See that the service package depends on `is-odd` and there's an `is-odd` in the workspace, but it is only used if `link-workspace-package=true`)
Closes TURBO-2666
=> feat(pnpm): respect link-workspace-packages npmrc

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs
Add a command line flag for enabling the experimental UI and hook it up to the config.
Closes TURBO-2668
=> feat: add ability to control UI via cli arg

examples/with-changesets/packages/eslint-config/package.json, examples/with-changesets/pnpm-lock.yaml
Examples check is failing due to this missing dependency in with-changesets.
This is failing in CI, and when tested locally with `pnpm lint`
=> fix(ci): fix examples CI check

crates/turborepo-lib/src/diagnostics.rs
macOS can have either Apple git or regular git depending on source.
This PR adds support for the Apple git output format.
Closes TURBO-2646
=> feat: support apple git in scan diagnostic

crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/lib.rs, crates/turborepo-ui/src/line.rs, crates/turborepo-ui/src/prefixed.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/mod.rs
If a task fails when using the UI, it isn't easy to find the reason for the failure.
This PR makes it so that if a task fails, we'll persist the logs to the terminal so they remain after the UI exits.
Closes TURBO-2681
=> feat(ui): persist logs on failure

crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/daemon/server.rs
- Always use local discovery inside package discovery process
- Keep package watching state in a local variable inside the process
- Handle recovering from package manager changes
- Added a test for changing package manager
- Switch tests to blocking calls to avoid reliance on timeout
Closes TURBO-2658
=> feat(Turborepo): handle package manager changes

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/pane.rs
Adds ability to scroll through task output when the task is not interacted with. This is so we retain the ability for users to enter `Ctrl-P`/`Ctrl-N` to the underlying task.
Current keybinds: `Ctrl-P` for scroll up and `Ctrl-N` for scroll down. `Ctrl-Up` and `Ctrl-Down` are more intuitive, but conflict with default macOS keybinds.
https://github.com/vercel/turbo/assets/4131117/3c76c9f4-2e26-4e51-8fde-80d803b708b3
Closes TURBO-2682
=> feat(ui): add ability to scroll task output

crates/turborepo-ui/src/tui/input.rs
Fixes #7808
Windows console produces an event for a key press as well as an event for when the key is released. This caused a single arrow key press to trigger 2 events. This fix is to ignore release events.
As per `crossterm` [docs](https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html#structfield.kind)
> kind: [KeyEventKind](https://docs.rs/crossterm/latest/crossterm/event/enum.KeyEventKind.html)
Kind of event.
Only set if:
Unix: [KeyboardEnhancementFlags::REPORT_EVENT_TYPES](https://docs.rs/crossterm/latest/crossterm/event/struct.KeyboardEnhancementFlags.html#associatedconstant.REPORT_EVENT_TYPES) has been enabled with [PushKeyboardEnhancementFlags](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html).
Windows: always
Use Turbo UI …
=> fix(ui): avoid dupe key events on windows

crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/task_graph/visitor.rs
Currently on a cache hit the replayed logs in the UI contain the task prefix which is unnecessary in the UI. This brings the cache hit/miss output to be the same in the UI (modulo cache hit/miss lines).
Before:
After:
(Also making sure non-UI behavior is preserved)
Closes TURBO-2684
=> fix(ui): avoid using prefix for replayed logs

crates/turbopack-trace-server/src/server.rs
The port number is too high and in the automatically chosen range. This could lead to port being already used.
Closes PACK-2798
=> change port of trace-server

crates/turbopack-node/src/transforms/webpack.rs
fixes SCSS HMR for imported files
Closes PACK-2818
fixes PACK-2809
=> fix webpack loader incorrectly calling custom_evaluate

crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs, crates/turbopack-node/src/evaluate.rs, crates/turbopack-node/src/render/render_proxy.rs, crates/turbopack-node/src/render/render_static.rs
* disable GC for tasks which use the streaming hack
* invalidate dependent tasks when assigning to a recomputing cell
Closes PACK-2787
=> fix some small bugs in turbo-tasks that are required for GC

Cargo.toml, crates/turbopack-core/src/source_map/mod.rs
While debugging https://vercel.slack.com/archives/C03EWR7LGEN/p1711146825831219?thread_ts=1711143217.892349&cid=C03EWR7LGEN, found out sourcemap lookup fails on certain source and always returns synthetictoken only.
Weirdly, the guards in this PR https://github.com/vercel/turbo/pull/7823/files#diff-2ce67e28c5b3144ec6f7a89167f3c96da9f9e268abf3fd685ce881d75a4cd8a5L319 is preventing those lookup - removing it makes correct sourcemap lookup occurs. I updated pkg to the version what swc uses and removed + ran next.js tests, seems like most of tests are running just fine 
(https://github.com/vercel/next.js/pull/63624)
Still not 100% sure if this'll be ok or not, if not open to change for the correct fixes. Some related fixes https://github.com/getsentry/rust-sourcemap/pull/60 might be the …
=> fix(sourcemap): update sourcemap, remove checker

crates/turbopack-core/src/issue/resolve.rs, crates/turbopack-tests/tests/execution/turbopack/basic/comptime/issues/__l___Module not found____c__ Can't resolve '__c_.-8f66b2.txt, crates/turbopack-tests/tests/snapshot/imports/resolve_error_cjs/issues/__l___Module not found____c__ Can't resolve '__c_d-10ac1f.txt, crates/turbopack-tests/tests/snapshot/imports/resolve_error_esm/issues/__l___Module not found____c__ Can't resolve '__c_d-b78915.txt
Avoid showing import map description in resolving issue when there is no import map mapping
Closes PACK-2828
=> Avoid showing import map description in resolving issue when there is no import map mapping

crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/table.rs
This PR changes UI behavior so all task output gets persisted to terminal after the run is finished.
Non-goals of the PR: respecting `--output-mode` for what logs get persisted.
This PR also ditches the "priority" channel for communicating with the rendering thread. This was intended to avoid a scenario where tasks were producing so many events that it took awhile to get to a "stop" event. In reality this introduces so many race conditions of a "stop" event causing events that happened not to be processed leading to missing information e.g. dropping the last line of task output since the stop event takes priority.
Run `turbo` and verify that logs get persisted under various scenarios:
Cache misses:
Failures (not displaying tasks that didn't start):
Cache hits:
Closes TURBO-2692
=> feat(ui): persist all logs

docs/pages/pack/docs/migrating-from-webpack.mdx
Now that docs have been moved to the Next.js docs site in #7511, this link is broken. Update it to link there instead.
Test Plan: Preview deployment
Closes PACK-2816
=> Turbopack docs: Fix broken webpack loaders link

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/pane.rs
With #7822 (and #7805 ) we're using `insert_before` to persist logs. This can panic (https://github.com/ratatui-org/ratatui/issues/999) if the viewport fills the entire terminal.
This PR changes our viewport construction so it now takes terminal size into account. (Previously we always would use 60, even if the terminal didn't have 60 rows)
Use UI with a terminal that has a height of 60 or less.
Closes TURBO-2695
=> fix(ui): limit viewport size based on term size

crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/daemon/server.rs
- Returns errors when package watching is in a known-invalid state. This means the client does not need to rely on timeouts when we cannot find a package manager or valid workspace globs.
- Combines the two bits of state, package manager and workspaces, into a single API call. They were effectively already used that way, but now the clients are updated to only make a single call.
Updated tests to no longer use a timeout, as we can now confirm error responses
Closes TURBO-2665
=> feat(Turborepo): return invalid states from package discovery

crates/turborepo-lib/src/run/scope/change_detector.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lib/src/run/scope/target_selector.rs, crates/turborepo-scm/src/git.rs
- Ignore uncommitted changes when both ends of a git commit comparison are specified
- Update our internal representation of git range comparisons to fix the "from" side, and make the "to" side optional.
- Slightly change our git range parsing to allow for empty ranges so that we can give a slightly better error message
Fixes #7818
Tests updated for new internal representation, also added new tests to specify that uncommitted changes are ignored when both sides of the comparison are fixed
Closes TURBO-2696
=> fix(Turborepo): ignore working tree state for fixed git comparisons

crates/turborepo-vt100/src/grid.rs, crates/turborepo-vt100/tests/scroll.rs
Port of https://github.com/doy/vt100-rust/pull/11
Should address part of #7843
Unit tests, did quick spot check that this scrolling still works.
Closes TURBO-2700
=> fix(vt100): fix scrollback underflow

crates/turborepo-telemetry/README.md, crates/turborepo-telemetry/src/config.rs, packages/eslint-config/library.js, packages/turbo-telemetry/.eslintrc.js, packages/turbo-telemetry/LICENSE, packages/turbo-telemetry/README.md, packages/turbo-telemetry/jest.config.js, packages/turbo-telemetry/package.json, packages/turbo-telemetry/src/cli.ts, packages/turbo-telemetry/src/client.test.ts, packages/turbo-telemetry/src/client.ts, packages/turbo-telemetry/src/config.test.ts, packages/turbo-telemetry/src/config.ts, packages/turbo-telemetry/src/index.ts, packages/turbo-telemetry/src/init.ts, packages/turbo-telemetry/src/utils.test.ts, packages/turbo-telemetry/src/utils.ts, packages/turbo-telemetry/tsconfig.json, packages/turbo-utils/src/logger.ts, pnpm-lock.yaml
Adds a `turbo-telemetry` library that enables tracking telemetry events from javascript packages. 
**Important**
This shares all telemetry state with turbo core's telemetry. This means users only need to disable once across all packages.
=> feat(telemetry): add JS package

crates/turborepo-ui/src/tui/pane.rs
🤦 I forgot to account for the border that we're adding to task logs.
I believe this will address the odd output seen in [this comment](https://github.com/vercel/turbo/issues/7843#issuecomment-2021162101)
Before
After
Closes TURBO-2701
=> fix(ui): account for border when reserving size for logs

crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks/src/manager.rs
This resolves an issue that caused Turbopack to panic with https://github.com/vercel/turbo/blob/04e2a9f0cb9439913975a325ce3eb59b46380ff8/crates/turbo-tasks-memory/src/task/aggregation.rs#L211
When marking a task dirty:
- Reuse the aggregation context instead of creating
- Apply queued updates
Closes PACK-2846
=> Turbo tasks: Reuse aggregation context and apply queued updates

crates/turbo-tasks-memory/src/count_hash_set.rs
This fixes too many allocations when collecting from a CountHashSet
Closes PACK-2854
=> fix size_hint on count hash set

crates/turborepo-repository/src/package_graph/dep_splitter.rs
Fixes #7732
It seems that Yarn 4 supports using workspace-root relative paths with the `workspace:` protocol. 
I cannot find [any](https://yarnpkg.com/features/workspaces#cross-references) [reference](https://yarnpkg.com/protocol/workspace) to this behavior in the docs, but confirmed that it's supported by a default `yarn` configuration.
Added unit test for `workspace:` protocol used with a workspace root relative path.
Verify that dependencies declared via a workspace root relative path:
```
[0 olszewski@chriss-mbp] /tmp/yarn4 $ turbo prune web          
Generating pruned monorepo for web in /private/tmp/yarn4/out
- Added @repo/eslint-config
- Added @repo/typescript-config
- Added web
[0 olszewski@chriss-mbp] /tmp/yarn4 $ turbo_dev --skip-infer prune web
Generating pruned monorepo for …
```
=> fix(yarn4): properly handle workspace protocol with path

crates/turbopack-ecmascript/src/chunk/placeable.rs, crates/turbopack-ecmascript/src/references/esm/export.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs, crates/turbopack-ecmascript/src/side_effect_optimization/locals/module.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/module_options_context.rs
This is required to support `experimental.optimizePackageImports` of `next.config.js`.
next.js counterpart: https://github.com/vercel/next.js/pull/63268
Closes PACK-2527
Look at the test case I added to https://github.com/vercel/next.js/pull/63268
=> feat(turbopack): Support marking packages as side-effect-free

crates/turbo-tasks-memory/src/count_hash_set.rs
=> fix panic in subtract

packages/turbo-vsc/src/extension.ts
This adds bun's bin folder to the path when looking for global turbo
as well as attempting to search the bun local bin folder when looking
for local turbo.
Closes TURBO-2698
=> LSP bun bin support

crates/turbopack-ecmascript/src/chunk/placeable.rs, crates/turbopack-ecmascript/src/references/esm/export.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs, crates/turbopack-ecmascript/src/side_effect_optimization/locals/module.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/module_options_context.rs
This reverts commit ad6b88b0a711f9851013a1780865215e363136ab.
Closes PACK-2869
=> Revert "feat(turbopack): Support marking packages as side-effect-free (#7731)"

.github/workflows/test.yml, Cargo.toml
This pull request updates the build flags for the 'turbopack' wasm32-wasi target and increases the number of target packages.
In the GitHub workflow file for tests, the `cargo check` command for the 'turbopack-wasi' target now specifies the `CARGO_BUILD_TARGET` environment variable. Additionally, in the 'Cargo.toml' file, the list of packages that can be compiled against the wasm32-wasi target has been expanded to include more turbo-task related crates.
To test these changes, run the GitHub workflows and check whether the 'turbopack' build process and the associated tests succeed.
Updating the build flags and target packages for the wasm32-wasi build process in 'turbopack' may lead to better performance and broader feature support.
=> ci(workflow): expands more wasi targets

crates/turbopack-ecmascript/src/chunk/placeable.rs, crates/turbopack-ecmascript/src/references/esm/export.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs, crates/turbopack-ecmascript/src/side_effect_optimization/locals/module.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/module_options_context.rs
This reverts commit 060a1467925e5fece2518b9e5e07603324ea3589.
=> feat(turbopack): Support marking packages as side-efffect-free

packages/create-turbo/__tests__/index.test.ts, packages/create-turbo/package.json, packages/create-turbo/src/cli.ts, packages/create-turbo/src/commands/create/index.ts, packages/create-turbo/src/commands/create/types.ts, packages/turbo-telemetry/README.md, packages/turbo-telemetry/src/client.test.ts, packages/turbo-telemetry/src/client.ts, packages/turbo-telemetry/src/events/create-turbo.ts, packages/turbo-telemetry/src/events/turbo-ignore.ts, packages/turbo-telemetry/src/events/types.ts, packages/turbo-telemetry/src/index.ts, packages/turbo-telemetry/src/init.ts, packages/turbo-telemetry/src/utils.ts, pnpm-lock.yaml
Add anonymous usage telemetry to create-turbo. If you have already opted out of turbo telemetry, you have opted out of this telemetry as well.
=> feat(create-turbo): usage metrics

crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-telemetry/src/events/generic.rs
Adds tracking for usage of `globalDotEnv` and `dotEnv` in `turbo.json`
👀 
Closes TURBO-2741
=> chore(telemetry): track dot env usage

packages/create-turbo/src/commands/create/index.ts, packages/create-turbo/src/commands/create/types.ts, packages/turbo-telemetry/src/config.test.ts, packages/turbo-telemetry/src/config.ts, packages/turbo-telemetry/src/init.ts
If something goes wrong with telemetry init (bad file, bad perms etc.) we shouldn't error, just proceed without.
Fixes https://github.com/vercel/turbo/issues/7880
Closes TURBO-2744
=> fix(telemetry): support bad init

Cargo.lock, Cargo.toml
`tui-term` has released `0.1.9` which has the functionality we require to use it with our `vt100` fork
Verify build and that terminal renders as expected:
Closes TURBO-2734
=> chore(ui): upgrade tui-term

crates/turborepo-lib/src/run/scope/filter.rs
Fixes bug from port where `...` filter would only select immediate dependencies.
In Go we used [`graph.Ancestors`](https://github.com/vercel/turbo/blob/v1.10.3/cli/internal/scope/filter/filter.go#L182) which performs a full DFS, not just immediate ancestors. This PR updates so we do the same in Rust.
Added unit test that uses `...` filter on a project with transitive dependencies.
We already have test cases for the reverse case of [including reverse dependants](https://github.com/vercel/turbo/blob/main/crates/turborepo-lib/src/run/scope/filter.rs#L806)
For good measure did a manual check in repo with following dep chain: `docs -> @repo/ui -> foo`
```
[0 olszewski@chriss-mbp] /tmp/foo $ turbo_dev --skip-infer build --filter=docs... --output-logs=errors-only --no-daemon     
• Packages in …
```
=> fix(filter): dependencies filter should match transitive deps

turborepo-tests/integration/package.json
- sets `COREPACK_ENABLE_DOWNLOAD_PROMPT=0` for the integration tests
Newer versions of `corepack` have extra text output when downloading a version, but the environment variable can disable it 
Observe GH Actions integration tests passing.
Closes TURBO-2753
=> fix(Turborepo): Disable the new corepack notification

packages/create-turbo/package.json, packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/package.json, packages/turbo-ignore/src/cli.ts, packages/turbo-ignore/src/ignore.ts, packages/turbo-ignore/src/types.ts, packages/turbo-telemetry/package.json, packages/turbo-telemetry/src/client.ts, packages/turbo-telemetry/src/events/create-turbo.ts, packages/turbo-telemetry/src/events/turbo-ignore.ts, packages/turbo-telemetry/src/index.ts, pnpm-lock.yaml
Anonymous usage metrics for turbo-ignore. Will help inform future roadmap for the tool.
=> feat(turbo-ignore): usage metrics

examples/kitchen-sink/packages/logger/package.json
Fixed the problem of @repo/logger not watching for changes. I think a part of this issue would also be fixed https://github.com/vercel/turbo/issues/7871.
After running the dev script of the monorepo, making changes in logger package and saving it should result in building the logger package once more.
=> fix typo in dev script of a kitchen-sink's package

examples/with-gatsby/apps/docs/package.json, examples/with-gatsby/apps/web/gatsby-config.ts, examples/with-gatsby/apps/web/package.json, examples/with-gatsby/package.json, examples/with-gatsby/packages/eslint-config/package.json, examples/with-gatsby/packages/ui/package.json, examples/with-gatsby/pnpm-lock.yaml
Removes the `gatsby-plugin-pnpm` dependency because:
1) It doesn't look like it is needed. `turbo build` and `turbo dev` still work.
2) It makes `npm` installation crash.
Note that the only substantive changes are `web/package.json` and `web/gatsby-config.ts`. The rest are from npm re-ordering the dependency lists, package manager cleanup, and the lockfile updating.
Closes TURBO-2769
=> Remove pnpm plugin in Gatsby example.

crates/turbopack-cli/src/build/mod.rs, crates/turbopack-cli/src/dev/mod.rs, crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-core/src/resolve/parse.rs, crates/turbopack-css/src/references/import.rs, crates/turbopack-ecmascript/src/references/typescript.rs, crates/turbopack-ecmascript/src/typescript/mod.rs, crates/turbopack-resolve/src/typescript.rs
=> Revert "feat(turbopack): Handle fragment in requests"

docs/pages/pack/docs/features/css.mdx
Updates the Turbopack CSS documentation to reflect reality.
=> Update Turbopack CSS docs

docs/pages/pack/docs/features/frameworks.mdx, docs/pages/pack/docs/features/static-assets.mdx
=> Update Next.js mention in Turbopack docs

Cargo.lock, Cargo.toml, crates/turbopack-core/src/source_map/mod.rs, crates/turbopack-css/src/process.rs, crates/turbopack-tests/tests/snapshot/emotion/emotion/output/crates_turbopack-tests_tests_snapshot_b36339._.js
Update SWC crates.
1. To keep in sync
2. Prepare usage of source map range mappings. https://github.com/getsentry/rust-sourcemap/pull/77
See next.js counterpart.
https://github.com/vercel/next.js/pull/63790
Closes PACK-2861
=> build: Update `swc_core` to `v0.90.29`

crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-ecmascript/src/chunk/chunk_type.rs, crates/turbopack-ecmascript/src/references/async_module.rs, crates/turbopack-ecmascript/src/references/esm/base.rs, crates/turbopack-ecmascript/src/references/esm/url.rs, crates/turbopack-ecmascript/src/references/external_module.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-ecmascript/src/references/pattern_mapping.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs, crates/turbopack-resolve/src/typescript.rs, crates/turbopack/src/lib.rs
This should prevent issues when an external module is removed from the require cache leading to 2 version used from the bundle.
=> feat(turbopack-ecmascript): cache external modules with wrapper

docs/pages/repo/docs/handbook/sharing-code/internal-packages.mdx
This commit uses the `@repo/` pattern in `math-helpers` example, consistent with the `@repo/` pattern used in the [getting started](https://turbo.build/repo/docs/getting-started/create-new) page and the starter repos.
n/a, documentation change
Please verify that
- I have prefixed the package names correctly with `@repo/` 
- I did not prefix any folder names by accident!
=> feat: use @repo/ pattern in `math-helpers` example, consistent with "getting started" and starter repo

crates/turbopack-trace-server/src/span_ref.rs, crates/turbopack-trace-server/src/viewer.rs
=> fix panic when searching an the root span

crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-vt100/src/entire_screen.rs, crates/turborepo-vt100/src/parser.rs
Fix for #7843
Verify that there is no longer a panic when persisting tasks with large amount of lines e.g. `yes | head -n 1000`
(Waiting on user test to confirm fix works)
Closes TURBO-2735
=> fix(ui): avoid rendering area more than u16::MAX

crates/turbopack-ecmascript/src/references/external_module.rs
With `is_esm: true` `module` is not available.
Closes PACK-2961
=> fix external module

crates/turborepo-lib/src/commands/prune.rs
Related to https://github.com/vercel/turbo/pull/7948, in running the `turbo prune` when specifying a package name, it is assumed that the package name is the name of the **folder** in `apps/web` or `packages/eslint-config`. The real case is that the package name is the name found in the `package.json` file in the `apps/*` directory.
This pull requests adds more detail and clarity towards the uncertainty of defining what the package means.
**Files Edited**
Line 46 of https://github.com/vercel/turbo/blob/main/crates/turborepo-lib/src/commands/prune.rs
```rs
#[error("invalid scope: package {0} not found")]
MissingWorkspace(PackageName),
```
to
```rs
#[error("invalid scope: package with name {0} in package.json not found")]
MissingWorkspace(PackageName),
```
=> Fix(commands/prune.rs): Add More detail in MissingWorkspace error

.github/actions/setup-turborepo-environment/action.yml
The root package.json and .node-version files are set to node 20,
so we should running our CI on the same version
Testing here: https://github.com/vercel/turbo/pull/7968
Closes TURBO-2805
=> chore(ci): use node 20 in CI

packages/eslint-plugin-turbo/__fixtures__/workspace/package.json
eslint 9.0.0 has some breaking changes that our current fixture isn't set up to support. This is [preventing us from releasing](https://github.com/vercel/turbo/actions/runs/8693806507/job/23842782558#step:5:256) new versions of `turbo`.
Future work is to update the fixture to work with eslint 9
`turbo test --filter=eslint-plugin-turbo` now passes
Closes TURBO-2808
=> chore: pin eslint version

.github/workflows/turborepo-release.yml
#7409 deleted `rust-toolchain` in favor of `rust-toolchain.toml` which isn't supported by the no longer maintained `action-rs/toolchain`
This broke our release process: https://github.com/vercel/turbo/actions/runs/8695260821/job/23846306200#step:7:12
[Release dry run](https://github.com/vercel/turbo/actions/runs/8697187026)
Closes TURBO-2810
=> chore(ci): switch from action-rs/toolchain to actions-rust-lang/setup-rust-toolchain

.github/workflows/turborepo-release.yml
=> chore(ci): use node 20 to run JS smoke tests before release

.github/workflows/test.yml
=> chore(ci): remove invalid action argument

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/opts.rs, turborepo-tests/integration/tests/bad-flag.t, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Remove legacy filter flags now that they've been deprecated for quite awhile.
Existing test suite passes. Updated tests that are still applicable and removed those that aren't.
=> chore: remove legacy filter flags

crates/turbopack-node/src/transforms/postcss.rs
Absolute paths don't work for imports on windows because `c:\` is interpreted as a URI scheme. The workaround is to use an unambiguous `file://` URI.
Fixes https://github.com/vercel/next.js/issues/63755
Similar to https://github.com/vercel/next.js/pull/64386
<details>
<summary>patch next.js's Cargo.toml to point to the updated branch</summary>
```
bgw@BENJAMINWOOCDA2 CLANGARM64 ~/Documents/next.js (canary)
$ git diff Cargo.toml
diff --git a/Cargo.toml b/Cargo.toml
index ffabdcc19..3ce91bc04 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -37,11 +37,11 @@ swc_core = { version = "0.90.30", features = [
testing = { version = "0.35.22" }
-turbopack-binding = { git = "https://github.com/vercel/turbo.git", tag = "turbopack-240416.1" }
+turbopack-binding = { git = …
```
=> fix(turbopack-node) postcss.config.js path resolution on Windows

.cargo/config.toml, Cargo.lock, package.json, packages/turbo-repository/rust/build.rs, pnpm-lock.yaml
Ported from the next.js PR.
Library release: https://github.com/vercel/turbo/actions/runs/8711878544
Closes PACK-2970
=> build(turbo-repository): fix napi build with LLD

crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/manager.rs
When cells become unused after recomputation of a task, drop them.
Closes PACK-2788
=> Drop excessive cells after task reexecution

crates/turborepo-lockfiles/fixtures/pnpm-v9.yaml, crates/turborepo-lockfiles/src/pnpm/data.rs, crates/turborepo-lockfiles/src/pnpm/dep_path.rs, crates/turborepo-lockfiles/src/pnpm/mod.rs
Closes #7993
Only thing that required updating is that as of `9.0.0-rc.0` the lockfile version was updated to `9.0` instead of `7.0` that was used from `9.0.0-alpha.0`-`9.0.0-beta.3`. I believe this was the only change made since I added support for lockfile v7 in #7853.
Added roundtrip test along with unit test for package resolution.
Manual test with repro provided in #7993
```
[0 olszewski@chriss-mbp] /tmp/pnpm-prune-repro $ turbo_dev --skip-infer prune app-a 
Generating pruned monorepo for app-a in /private/tmp/pnpm-prune-repro/out
- Added app-a
- Added pkg-a
- Added tooling-config
[0 olszewski@chriss-mbp] /tmp/pnpm-prune-repro $ cd out 
[0 olszewski@chriss-mbp] /tmp/pnpm-prune-repro/out $ pnpm i --frozen-lockfile
Scope: all 4 workspace projects
Lockfile is up to date, resolution step …
```
=> fix(pnpm): support pnpm lockfile v9

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/engine/execute.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/task_id.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Instead of using `--filter` in our re-running of tasks for watch mode, we instead prune the task graph to run the changed task and its dependent tasks. This has the benefit of following the task graph and not the package graph.
You can verify this works by creating a task dependency relation that is not in the package graph. So, make a `ui#test` task that depends on a `docs#test` task, but don't have `ui` depend on `docs`. Then verify that when the `docs` are changed, we re-run the `ui#test` task too.
Closes TURBO-2752
=> feat: Re-run dependent tasks in watch mode

Cargo.lock, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/proto/turbod.proto, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_hash.rs
- Wire up daemon-backed file hashing into the client
Existing integration test suite
Closes TURBO-2736
=> feat(Turborepo): wire file hashing to grpc server

crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/daemon/proto/turbod.proto, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/engine/execute.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/scope/mod.rs, crates/turborepo-lib/src/run/task_id.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Implements an MVP version of watch mode that takes the package changes stream and re-runs package tasks as needed.
Closes TURBO-2519
=> feat(turborepo): Watch mode

crates/turbopack-mdx/src/lib.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_options_context.rs
Part 1 for PACK-2978, extending & consolidating existing mdx transform options to support partial set of parse / transform options. Notably to support construct between gfm vs commonmark.
Closes PACK-2979
=> feat(mdx): support custom parse construct options

crates/turbopack-browser/src/chunking_context.rs, crates/turbopack-core/src/chunk/chunking_context.rs, crates/turbopack-ecmascript/src/references/esm/base.rs, crates/turbopack-nodejs/src/chunking_context.rs
improves error message
Closes PACK-2930
=> allow to give a chunking context a name

crates/turborepo-filewatch/src/hash_watcher.rs
- Adds a debouncer for file changes to cut down on needless rehashing
Added a small test for the debouncer
Closes TURBO-2756
=> feat(Turborepo): add a debouncer to file hash watching

crates/turborepo-lib/src/daemon/client.rs, crates/turborepo-lib/src/run/watch.rs
Some of our error messages were a little opaque for watch mode. This threads the diagnostic code through the watch mode errors and adds some help text.
Closes TURBO-2856
=> chore: Improved errors for watch mode

crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/manager.rs
Reverts vercel/turbo#7765
Seems like it's causing a regression, will revisit later.
Closes PACK-2985
=> Revert "Drop excessive cells after task reexecution"

crates/turbopack-trace-server/src/reader/heaptrack.rs
show allocated memory while loading to allow finding peek memory.
Closes PACK-2989
=> Turbopack Tracing: show memory consumption

.github/workflows/bench-turborepo.yml, .github/workflows/lsp.yml, .github/workflows/test.yml, .github/workflows/turborepo-library-release.yml, .github/workflows/turborepo-native-lib-test.yml, .github/workflows/turborepo-release.yml
macos-14 appears to not be able to build turborepo successfully
and macos-latest was recently updated to point to macos-14.
Pinning this until we figure out how to make macos-14 work
I didn't change JS package tests or turbopack related things
Closes TURBO-2862
=> chore(ci): pin Github Actions runner that builds turborepo to macos-12

.github/actions/setup-rust/action.yml, .github/workflows/bench-turborepo.yml, .github/workflows/test.yml, .github/workflows/turborepo-library-release.yml, .github/workflows/turborepo-native-lib-test.yml, .github/workflows/turborepo-release.yml
Bumping `setup-protoc` to version 2 as it supports fetching MacOS `arm64` builds which are required for `macos-latest` now that it runs on an M1 chip.
Bumping `protoc` from `3.20` to `3.26` as `3.20` didn't have builds available for MacOS arm64.
Note: Starting with 3.21 the protobuf project has switched it's versioning scheme so the major version 3 is implied. `setup-protoc` matches this as of 2.0.0 so we specify version with the format of `MINOR.PATCH`.
We cannot update to `setup-protoc` to 3.0 as it uses Node20 which requires too high of glibc version for us to support our x86 musl builds.
CI Passes
Verify that library release is able to build on arm64 machines: https://github.com/vercel/turbo/actions/runs/8806177110/job/24170410394
Dry run of release process: …
=> chore(ci): bump protoc version

.github/workflows/turborepo-library-release.yml
Changes:
- Upgrade `curl` version to avoid https://github.com/alpinelinux/docker-alpine/issues/383
- Do `PATH` alterations in build step as for some reason the alpine container doesn't respect alterations from previous steps.
- Remove `rustup toolchain install` commands as this would require parsing TOML to extract the Rust version we want. Instead we rely on the behavior of `rustup show` which will install the toolchain override if it isn't installed yet.
Dry run: https://github.com/vercel/turbo/actions/runs/8808289531
Closes TURBO-2869
=> chore: fix turborepo-repository MUSL release

crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
I messed up a resolving a merge conflict and didn't migrate some args that moved from `ExecutionArgs` to `RunArgs` in #7613 
Tests on CI pass
Closes TURBO-2872
=> fix(cli): fix bad merge conflict resolution

crates/turbopack-browser/src/chunking_context.rs, crates/turbopack-core/src/chunk/chunking_context.rs, crates/turbopack-nodejs/src/chunking_context.rs
This is unused.
Closes PACK-2995
=> Remove `can_be_in_same_chunk`

crates/turborepo-filewatch/src/globwatcher.rs, crates/turborepo-filewatch/src/hash_watcher.rs, crates/turborepo-paths/src/anchored_system_path.rs
- adds support for `inputs` that are contained within a package to daemon file hashing. `inputs` are tracked after the first request for them.
Added tests that use `inputs`.
Closes TURBO-2762
=> feat(Turborepo): support inputs for file hash watching

crates/turbo-tasks-hash/src/xxh3_hash64.rs, crates/turbo-tasks-memory/src/aggregation_tree/mod.rs, crates/turbo-tasks/src/state.rs, crates/turbo-tasks/src/task/function.rs, docs/pages/repo/docs/core-concepts/monorepos/running-tasks.mdx
=> chore: remove repetitive words

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-repository/src/package_json.rs
Deletes the handling of the "legacy" config, i.e. the `turbo` key from `package.json`
=> chore(turbo)!: remove check for legacy turbo config in package.json

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/watch.rs
We were previously processing the package change events synchronously, which ended up creating too much lagging and therefore crashes. Now we spin up a thread that reads in the package change events, and accumulates the changed packages. A separate thread handles execution by taking those changed packages and spinning up a new run.
Also I changed our logic to just send rediscover events on lagging with the channel in the daemon server. No reason to crash the server in that case.
The first commit is more of a refactor to put the watch state into `WatchClient`, to clean up the state ahead of splitting into two threads. You can review commit by commit if you wish.
Tested on `next.js`, lagging is definitely improved.
=> feat(turborepo): Process package change events asynchronously

packages/turbo-telemetry/src/config.test.ts, packages/turbo-telemetry/src/config.ts
Fix parsing the telemetry config alerted date in the JS lib
=> fix(telemetry): correctly parse alerted date

examples/with-prisma/packages/database/package.json, examples/with-prisma/packages/database/src/seed.ts, examples/with-prisma/yarn.lock
Fix missing dependency `tsup` and incorrect import path of the `database` package of the `with-prisma` example.
I was boostrapping an app using the prisma example and ran into some errors mostly likely caused by some minor missing pieces in the previous update https://github.com/vercel/turbo/pull/6571. This patch should fix them.
=> fix(example): Fix Prisma example

crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-repository/src/package_manager/yarn.rs
- change `Error::Which` to not be transparent, and to display the binary we tried to find
- update the calls to `which("bun")` and `which("yarn")` to use the new pattern.
Closes TURBO-2900
=> feat(Turborepo): Be explicit about which binary we failed to find

packages/turbo-vsc/src/extension.ts
Adds a logging channel for the turbo vsc extension and rework some logging to prevent noisiness in the notification bar. This also adds some extra handling for homebrew based npm installs, and some additional handling to ensure paths are trimmed properly.
Build and boot up the extension and observe the new output tab for Turbo.
Closes TURBO-2894
=> add some more logging to the extension startup

crates/turborepo-filewatch/src/debouncer.rs, crates/turborepo-filewatch/src/hash_watcher.rs, crates/turborepo-filewatch/src/lib.rs, crates/turborepo-filewatch/src/package_watcher.rs
- move the debouncer to its own module so that it is reusable
- apply the debouncer to package discovery
- make package discovery async so it doesn't block the file watching channel
Existing test suite.
Fixes #3455
Closes TURBO-2909
=> fix(Turborepo): Make package discovery async, and apply a debouncer

docs/pages/repo/docs/handbook/linting/eslint.mdx
Updating the name of the ESLint configuration package to use a namespace, similar to our examples.
=> Update eslint-config package name.

.github/turbo-orchestrator.yml
I use the [`needs: triage` label][1] during my OSS rotation and [a separate link][3] to find external contributions. Adding this should make it easier to streamline, but also kick out PRs that someone is already owning that I can ignore during triage.
Closes TURBO-2932
[1]: https://github.com/vercel/turbo/issues?q=is%3Aissue+is%3Aopen+label%3A%22needs%3A+triage%22+label%3A%22owned-by%3A+turborepo%22+
[3]: https://github.com/vercel/turbo/pulls?q=is%3Apr+is%3Aopen+sort%3Acreated-desc+-label%3A%22created-by%3A+turbopack%22+-label%3A%22created-by%3A+turborepo%22+-review%3Aapproved+draft%3Afalse+
=> Update rules for PR labeling

crates/turbopack-node/js/src/transforms/webpack-loaders.ts
Minor fix to next.js specific loader won't fail if they try to stop current span.
Closes PACK-3033
=> feat(webpack-loaders): support dummy span interface

crates/turbopack-node/src/transforms/webpack.rs
Minor improvement for debugging.
Closes PACK-3037
=> fix(webpack): print resource, project path when relative calc fails

Cargo.toml, crates/turbopack-binding/Cargo.toml, crates/turbopack-binding/src/lib.rs, crates/turbopack-cli/Cargo.toml, crates/turbopack-trace-server/src/lib.rs
Implement turbopack_bindings for the trace server. Added under `turbopack_bindings::turbopack::trace_server`. Currently only exposing one function: `turbopack_bindings::turbopack::trace_server::start_turbopack_trace_server`
=> Implement bindings for Turbopack trace server

crates/turborepo-filewatch/src/hash_watcher.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-scm/src/package_deps.rs
- inputs in a `HashSpec` are no longer an option, but can be default, default with extras (`$TURBO_DEFAULT$`), or specific globs (`inputs` w/o `$TURBO_DEFAULT$`).
- Properly invalidate `HashSpec` instances that use `$TURBO_DEFAULT$`
Add previously-failing test for inputs that use `$TURBO_DEFAULT$`.
Closes TURBO-2988
=> feat(Turborepo): Add support for $TURBO_DEFAULT$ to file hash watcher

Cargo.lock, crates/turborepo-analytics/Cargo.toml, crates/turborepo-analytics/src/lib.rs, crates/turborepo-api-client/Cargo.toml, crates/turborepo-api-client/src/analytics.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-api-client/src/telemetry.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/logout.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-telemetry/Cargo.toml, crates/turborepo-telemetry/src/lib.rs
- Removed `async-trait` dependency from `turborepo-analytics` and `turborepo-api-client`
- Refactored implementation of async functions in `turborepo-api-client` and `turborepo-telemetry`
This crate isn't needed on newer rust toolchains (as long as you are not using trait objects).
If it compiles it's good enough.
Closes TURBO-2973
=> Remove async-trait from a few crates

crates/turbo-tasks-malloc/src/lib.rs
=> fix memory counting without custom allocator

crates/turbo-tasks-macros/src/func.rs
Previously, we'd generate function return types like:
```rust
<Vc<AssetIdent> as TaskOutput>::Return
```
which is equivalent to the much simpler:
```rust
Vc<AssetIdent>
```
That approach is nice because it's easier to implement in the macros, and it's more correct, because it uses the type system to verify the type of `Vc` and `Result` are what we expect. However, it makes the rustdoc output much harder to read.
This attempts to the expansion of `TaskOutput::Return` inside the macro to generate more readable documentation, at the cost of some correctness.
<details>
<summary><strong>Rustdoc Before</strong></summary>
</details>
<details>
<summary><strong>Rustdoc After</strong></summary>
</details>
<details>
<summary><strong>Example compilation error</strong> with an invalid return …
=> turbo-tasks: Expand `<T as TaskOutput>::Return` values in macros

Cargo.lock, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/package_changes_watcher.rs
We leverage the file hash watcher to make watch mode more stable. Basically, once we get a list of changed packages, we query the file hash watcher to see if there are file hashes available. If so, we check if we've seen these file hashes before. If they are, then we don't re-run.
This does have some caveats. For one, file hashes are not exactly correct for whether a task should be re-run. We really should be checking task hashes, but that will require more daemon infrastructure. Also files are most likely the only changes a user will make with watch mode (will they edit env vars? Probably not), so this is good enough.
Also, this will only work on the *second* run, since we need to get the file hash and store it. Maybe even the third if hashing takes too long to get.
I tested on the …
=> feat(turborepo): Using file hashing for package watching

crates/turborepo-api-client/src/lib.rs, crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/fs.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/summary/spaces.rs
We currently have a single API client however some types of calls should be handled differently that others. The cache in particular should not cause a hard error if it times out during upload, only if it fails to connect. `cache_client` is currently only used for uploading artifacts.
TODO: decide on an env var name and add docs. Going to defer to monday's meeting for this.
New unit tests.
Closes TURBO-2974
=> add support for cache_timeout as well as timeout

crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/lib.rs
In the case of upload timeouts and connection timeouts we can yield a more useful error than the one that reqwest gives us.
Before: `error sending request for url (https://vercel.com/api/v8/artifacts/1e1db6d9c17b138d): operation timed out`
After: `the cache artifact for d6b10341668ff294 was too large to upload within the timeout`
And: `could not connect to the cache`
For complete timeouts and connection timeouts respectively
Closes TURBO-2975
=> yield a different warning when the cache upload times out

crates/turbopack-node/src/transforms/postcss.rs
A followup requested by @sokra in https://github.com/vercel/turbo/pull/7995#discussion_r1568285539
There's no meaningful change in behavior here, as node on windows interprets both `/` and `\` as valid path separators, but this makes the intent clearer.
<details><summary>Repeated the test plan for #7995. Tested on both Windows and Linux.</summary>
</details>
Closes PACK-3049
=> turbopack-node: Use path.join for postcss loader

crates/turbopack-trace-server/Cargo.toml, crates/turbopack-trace-server/src/lib.rs, crates/turbopack-trace-server/src/main.rs, crates/turbopack-trace-server/src/server.rs
`websocket` can't be compiled to some system targets for Windows and Linux. Based on the readme of the project they recommend using `tungstenite` instead, this PR implements `tungstenite` for turbo-trace-server.
While investigating some borrowing issue with @arlyon we found that one of the threads spawned to send messages every 500ms isn't really being used, so I've removed that in favor of the sending on `ack` that is already used.
=> Replace websocket with tungstenite for turbo-trace-server

crates/turbopack-css/src/process.rs
> grid-template-areas and grid-area behaves differently in lightningcss and that leads to some user problems, so we need a check to catches these errors.
> Since lightning css in css modules is renaming grid area names, you have to use grid-area and grid-template-areas in the same file together. Using them in different files would be an error.
> 
> So it would be great to have a check that emits an error when using grid-area in a CSS file but not declaring the name in grid-template-areas.
Closes PACK-3022
I added some tests
=> feat: Add lint for `grid-template-areas`

packages/turbo-gen/src/templates/simple-js/package.json, packages/turbo-gen/src/templates/simple-ts/package.json
As described by #5657, the default `simple-*` templates creates a template that is broken for `"type": "module"` packages.
When digging into this issue I found out that a simple `package.json` with `"type": "commonjs"` solves the problems by telling the runtime to treat the file diferently from the parent package.
- Initialize a new monorepo with `"type": "module"` in the `package.json`
- on this branch it should now be possible to generate the sample generator (either `js` or `ts`) and not have any errors about the module type.
- it should also be possible to run the generator and it should create the file in the project root normally.
resolves #5657
=> fix(gen): isolate generator to `commonjs`

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs
I believe this addresses JavaScriptBach's issue in #8088
We weren't properly propagating unrecoverable errors to `turbo`'s exit code. So things like writing a log file failing could cause a zero exit code even though `turbo` had a failure that left us in a bad state. This PR now propigates internal errors up to the `run` command so it will have a non-zero exit when these are encountered.
Force an internal failure like making a log file owned by root
Before
(Note exit code and the fact that run summary is displayed)
After
(Note the non-zero exit code)
Closes TURBO-3034
=> fix: properly propigate internal errors

Cargo.lock, crates/turbo-tasks-macros/Cargo.toml, crates/turbo-tasks-macros/src/value_macro.rs, crates/turbopack-css/src/module_asset.rs, crates/turbopack-ecmascript-plugins/src/transform/swc_ecma_transform_plugins.rs, crates/turbopack-node/src/route_matcher.rs, crates/turbopack-node/src/transforms/postcss.rs, crates/turbopack-node/src/transforms/webpack.rs
Most `#[turbo_tasks::value(transparent)]` types leave their inner value as private. I think this okay, but because rustdoc hides private fields by default, it makes it hard to understand at a glance the contained value, without scrolling down to the `impl` of `VcValueType`. This PR generates documentation for these.
<details>
<summary>Also checked that it works if there's an existing doc comment, extending rather than replacing the existing documentation.</summary>
</details>
**Alternative:** We could fail if the field is non-`pub`, and update the callsites. Let me know if this is preferred. The contained fields are *basically* public anyways, as they can be accessed via `Vc`'s APIs.
While modifying this code, I realized that we don't generate an error if …
=> #[turbo_tasks::value(transparent)]: Generate docs & fail on invalid callsites

Cargo.lock, crates/turbopack-trace-server/Cargo.toml
Hoping this fixes https://github.com/vercel/next.js/pull/65527#issuecomment-2101221673 🤞
=> Remove websocket dependency in turbo-trace-server

crates/turborepo-lib/src/engine/mod.rs
Fixing persistent tasks in watch mode. I accidentally reversed the dependency relation which created a circular dependency which in turn caused a deadlock.
Try out `turbo watch dev` in create turbo
Closes TURBO-3020
=> fix(turborepo): Persistent tasks in watch mode

crates/turborepo-filewatch/src/globwatcher.rs, crates/turborepo-filewatch/src/hash_watcher.rs
- `GlobSet::as_inputs` now prefixes exclusions with `!` so they are properly parsed
Added new hash watching test with exclusions in the inputs.
Fixes #8112
=> fix(Turborepo): Fix as_inputs to include !

crates/turborepo-lockfiles/src/berry/mod.rs, crates/turborepo-lockfiles/src/lib.rs, crates/turborepo-lockfiles/src/npm.rs, crates/turborepo-lockfiles/src/pnpm/data.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, turborepo-tests/integration/tests/lockfile-aware-caching/new-package.t
When comparing lockfiles between revisions to identify what packages have been affected, we treated missing packages in the previous lockfile (added in the new lockfile) as errors, and fell back to considering all packages as affected. This change adds a boolean to determine what the behavior should be when we can't find a package that we expect. When building the package graph, it continues to be an error, as well as when tracing the dependencies of a package we've already found in the lockfile. However, for the first round of packages that we look for in a previous lockfile, we ignore missing packages. This allows us to more gracefully handle comparisons between commits that add new packages.
Added an integration test inspired by the repro from the linked issue.
Fixes #8125
=> fix(Turborepo): Handle new packages in lockfile comparisons

crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/table.rs
Two minor changes to the UI:
- Add trailing space after title
- Make dividing line after task table header a single line
=> fix(ui): minor formatting

crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/table.rs, crates/turborepo-ui/src/tui/task.rs
Integrates new UI with watch mode. Pulls out the UI handle and sender outside the `Visitor` and `Run` struct, so it can be owned by the `WatchClient`. Also adds an `Event` for updating the task names, so on rediscovery we can keep using the same UI thread but just update the task names.
Give it a shot!
Closes TURBO-2801
=> feat(turborepo): new ui + watch mode

crates/turborepo-lib/src/run/scope/filter.rs
Previously we would infer scope for name filters if there was exactly one matching package.
e.g. `turbo build --filter=ui` would run `@a/ui#build` if there was a `@a/ui` package in the workspace
This is confusing and can result in accidentally breaking filters when a conflicting package is added e.g. adding `@b/ui` would cause *no* tasks to be run along with a zero exit code.
Updated unit test to verify inference no longer works and using the explicit package name still works.
=> feat(filter): no longer infer scope in filters

packages/create-turbo/src/cli.ts
We replaced this with an option instead of an arg, but cleaning up here!
=> chore!(create-turbo): remove old pm arg

crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks-testing/src/lib.rs, crates/turbo-tasks/src/id.rs, crates/turbo-tasks/src/id_factory.rs, crates/turbo-tasks/src/registry.rs, crates/turbo-tasks/src/task/task_input.rs
reduces memory usage by ~10%
We never have more than 4 billion tasks
Closes PACK-3052
=> change ids from usize to u32

Cargo.toml
This PR compiles all non-workspace dependencies, as well as `turbo-tasks-memory` (which is particularly sensitive) with basic optimizations. Most crates in the workspace still use opt-level 0 locally.
While not as good as applying opt-level 1 everywhere, this significantly reduces execution times versus opt-level 0, while making cold builds about 50-60% slower. Warm build times are largely unaffected.
The debugging (gdb/lldb) experience may also be slightly worsened by the optimizations.
**What about `cargo check`/`cargo clippy`/`rust-analyzer`?** No expected change, as (outside of proc macros) these don't perform LLVM code generation.
**Why selectively, and not everywhere?** While applying this everwhere can give us about 3x faster execution, this still gives us *most* of the runtime …
=> Selectively enable opt-level 1

crates/turbopack-core/src/reference_type.rs, crates/turbopack-ecmascript-plugins/src/transform/directives/server_to_client_proxy.rs, crates/turbopack-ecmascript/src/analyzer/imports.rs, crates/turbopack-ecmascript/src/annotations.rs, crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/references/esm/base.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-resolve/src/ecmascript.rs, crates/turbopack/src/lib.rs
No more magic string literal 🎉 
This also enables `with { type: "json }`
Blocked by https://github.com/vercel/next.js/pull/59494
Closes PACK-2119
=> feat(turbopack-ecmascript): use import attributes for annotations

crates/turbopack-trace-server/src/reader/heaptrack.rs, crates/turbopack-trace-server/src/reader/mod.rs, crates/turbopack-trace-server/src/viewer.rs
allocations are zero indexed...
Closes PACK-3043
=> fix off-by-one bug while reading heaptrack files

crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/mod.rs, turborepo-tests/integration/tests/invalid-package-json.t
We now will error if we encounter a package with a missing or empty package name.
This is done in the graph validation step as opposed to construction since we don't want to impose this restriction on `@turbo/repository` users.
Added integration test
=> feat: error on empty package name

crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lib/src/run/scope/simple_glob.rs, crates/turborepo-lib/src/run/scope/target_selector.rs, crates/turborepo-paths/src/relative_unix_path.rs, crates/turborepo-paths/src/relative_unix_path_buf.rs, turborepo-tests/integration/tests/dry-json/monorepo-no-changes.t, turborepo-tests/integration/tests/dry-json/single-package-no-change.t, turborepo-tests/integration/tests/filter-run.t, turborepo-tests/integration/tests/inference/has-workspaces.t, turborepo-tests/integration/tests/inference/nested-workspaces.t, turborepo-tests/integration/tests/inference/no-workspaces.t
This PR changes `--filter` so it now will error on certain malformed filters:
- Name filters with no globs that don't match any packages e.g. `--filter=fo` instead of `--filter=foo`
- Directory filters that reference a directory that doesn't exist: e.g. `--filter='./pakcages/*'`
Each commit of the PR can be reviewed on it's own.
Updated existing unit tests. Added additional ones along with an integration test.
=> feat(filter): error on invalid filters

Cargo.lock, Cargo.toml
- Closes PACK-3042
- Closes NEXT-3241
- Closes NEXT-3242
- Closes https://github.com/vercel/next.js/issues/46887
- Closes https://github.com/vercel/next.js/issues/65064
- Closes https://github.com/vercel/next.js/issues/65066
- Closes https://github.com/vercel/next.js/issues/65237
See [next.js counterpart](https://github.com/vercel/next.js/pull/65450)
=> build: Update `swc_core` to `v0.92.5`

crates/turbo-tasks-memory/src/aggregation/tests.rs
=> improve performance test case

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/watch.rs
We were using the set of filtered packages to limit change events. That's not exactly right since we need to account for the dependencies of filtered packages as well. Therefore we take the transitive closure of the filtered packages and restrict package change events to that set.
=> fix(turborepo): use transitive closure of filtered packages in watch mode

.cargo/config.toml, .github/actions/setup-rust/action.yml, CONTRIBUTING.md
**What's wrong with `ld`?** It's very slow and uses a lot of memory.
**Why `lld`?** It's fast, mature, and well-supported. Meta and Google use it for all their linking workloads. We're already using it for macos and x86-64 Windows. There is [ongoing work to make it the default for rustc](https://github.com/rust-lang/rust/issues/71515), and it already is default on a few platforms.
**Why not `mold`?** Mold is generally faster, but the margin is slim enough for our workloads that it doesn't really matter. Mold only recently got support for LTO, doesn't support v0 rust symbol demanging, doesn't support BOLT (though we don't use that yet), etc. Mold is maturing quickly, but `lld` still seems like the "safer" choice.
This is using https://github.com/bgw/benchmark-scripts. That machine has a …
=> Switch from ld (the default linker) to using lld for GNU Linux targets

packages/turbo-ignore/__tests__/ignore.test.ts, packages/turbo-ignore/src/ignore.ts, packages/turbo-types/src/types/dry.ts
Single package repo dry runs can not include a packages key at all.
Fixes https://github.com/vercel/turbo/issues/8172
=> feat(turbo-ignore): don’t fail on single package repos

Cargo.lock, crates/turborepo-api-client/Cargo.toml, crates/turborepo-api-client/src/analytics.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-api-client/src/retry.rs, crates/turborepo-api-client/src/spaces.rs, crates/turborepo-api-client/src/telemetry.rs
Certain APIs should time out in different ways. For the cache, we want to retry connection attempts but not retry upload timeouts as a retry is unlikely to change your connection speed.
New unit tests.
Closes TURBO-2976
=> add two retry strategies to allow requests to timeout gracefully

crates/turbopack-trace-server/src/bottom_up.rs, crates/turbopack-trace-server/src/span_ref.rs
unfortunately there is a rustc bug that crashes when the typechecking in run in this crate during compiles for next-swc when using `Either<impl Iterator, impl Iterator>`. Solution is to use a Boxed iterator
Existing tests OK
=> fix rustc bug in turbopack-trace-server

Cargo.lock, Cargo.toml, crates/turbopack-css/src/process.rs, crates/turbopack-tests/tests/snapshot/css/css-modules/output/crates_turbopack-tests_tests_snapshot_css_css-modules_input_8abc52._.js, crates/turbopack-tests/tests/snapshot/css/css-modules/output/crates_turbopack-tests_tests_snapshot_css_css-modules_input_8abc52._.js.map, crates/turbopack-tests/tests/snapshot/css/css-modules/output/crates_turbopack-tests_tests_snapshot_css_css-modules_input_style_module_71f14f.css, crates/turbopack-tests/tests/snapshot/css/css-modules/output/crates_turbopack-tests_tests_snapshot_css_css-modules_input_style_module_7d7e1c.css
Implements https://github.com/parcel-bundler/lightningcss/pull/739/files.
Grid scoping in CSS Modules is disabled because Webpack CSS Modules handling doesn't handle grid currently. This ensures moving from Webpack to Turbopack doesn't have mismatching behavior around CSS grid.
=> Upgrade lightningcss, disable grid scoping

crates/turborepo-lib/src/run/global_hash.rs, turborepo-tests/integration/fixtures/global_deps/README.md, turborepo-tests/integration/fixtures/global_deps/turbo.json, turborepo-tests/integration/tests/global-deps.t
Handle exclusions in `globalDeps` 
Updated `global-deps.t` to test negative globs.
=> feat: allow for negative globs in globalDeps

Cargo.lock, crates/turborepo-api-client/Cargo.toml, crates/turborepo-api-client/src/error.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-cache/Cargo.toml, crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/lib.rs, crates/turborepo-cache/src/multiplexer.rs, crates/turborepo-cache/src/upload_progress.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/run/mod.rs
When turbo is waiting for the cache, don't really expose any data to the user. This PR modifies the cache put operation to take a stream and introduces a new stream adapter that captures a running history of writes using a ring buffer. These requests are stored in a hashmap which is read by the spinner while waiting for shutdown, and a live number is posted with the remaining bytes and current upload speed.
Also gracefully shuts down the upload phase when pressing ctrl-c
Before:
```
>>  ...Finishing writing to cache...                                                                                                                                                                                                                     WARNING  failed to contact remote cache: skipping HTTP …
```
=> add support for upload speed / remaining in the cache upload step

crates/turbopack-trace-server/src/viewer.rs
This adds a few modes to see allocations per unit time. The hierarchy is a bit hard but by selecting the one you want to inspect and changing the view for sub-items you can usually find some useful data.
Closes TURBO-2574
=> [turbo-trace] add additional filter modes for allocs over time

deny.toml
In this PR https://github.com/vercel/turbo/pull/8174 the library prehash is licensed using MPL2.0 (great) but without the copyleft exception.
I believe that we are OK. From what I understand this prevents us from making and redistributing changes to this library under one of the MPL secondary licenses ("Secondary License" means either the GNU General Public License, Version 2.0, the GNU Lesser General Public License, Version 2.1, the GNU Affero General Public License, Version 3.0, or any later versions of those licenses).
It does not exclude us from using that library in a 'larger work' that is licensed using a different (compatible) license so for the purpose of distributing a binary it is the same as MPL-2.0
N/A
=> add MPL-2.0-no-copyleft-exception to the allow list

.github/actions/install-global-turbo/action.yml
Just so we don't accidentally break all of our workflows when we cut a 2.0 canary we should pin ourselves to the latest 1.x release.
Once a 2.0 canary is released we will migrate ourselves and unpin the version.
CI
=> chore: pin global turbo to 1.x release

crates/turbopack-css/src/process.rs
Reverts vercel/turbo#8060
https://github.com/parcel-bundler/lightningcss/pull/739 is now applied, so we don't need this lint anymore
=> feat: Remove lint for `grid-template-areas`

packages/turbo-codemod/__tests__/__fixtures__/add-package-names/correct-names/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/correct-names/packages/ui/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/correct-names/packages/utils/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/duplicate-names/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/duplicate-names/packages/apps/docs/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/duplicate-names/packages/apps/web/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/duplicate-names/packages/ui/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/duplicate-names/packages/utils/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/missing-names/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/missing-names/packages/ui/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/missing-names/packages/utils/package.json, packages/turbo-codemod/__tests__/add-package-names.test.ts, packages/turbo-codemod/__tests__/generate-package-name.test.ts, packages/turbo-codemod/src/cli.ts, packages/turbo-codemod/src/transforms/add-package-manager.ts, packages/turbo-codemod/src/transforms/add-package-names.ts, packages/turbo-codemod/src/transforms/clean-globs.ts, packages/turbo-codemod/src/transforms/create-turbo-config.ts, packages/turbo-codemod/src/transforms/migrate-env-var-dependencies.ts, packages/turbo-codemod/src/transforms/rename-output-mode.ts, packages/turbo-codemod/src/transforms/set-default-outputs.ts, packages/turbo-codemod/src/transforms/stabilize-env-mode.ts, packages/turbo-codemod/src/transforms/transform-env-literals-to-wildcards.ts, packages/turbo-codemod/turbo/generators/templates/transformer.hbs
Codemod to add missing name (or fix duplicates)
=> feat(codemod): add missing package names

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/run/scope/filter.rs, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Removes the `--ignore` flag as it's interaction with other `--filter` flags is hard to explain.
If we want to bring it back, then it should be put it into a configuration file.
I removed the command line flag and how it feeds into the package filtering, but left the underlying implementation of change detector as-is. This should make it easy to bring back this behavior via a configuration file.
Existing tests
=> chore: remove --ignore flag

Cargo.lock, crates/turbo-tasks-hash/Cargo.toml, crates/turbo-tasks-hash/src/base16.rs, crates/turbo-tasks-hash/src/hex.rs, crates/turbo-tasks-hash/src/lib.rs, deny.toml
Noticed these dependencies/functions were unused.
For the most part, it's better to do these conversions with the built-in `format!()`.
Parsing base16 could make sense for this as a dependency, but we're not doing that.
```
cargo check
```
Also grepped through next.js to check that we're not using it there.
=> chore: Remove unused `base16` dependency and dead `hex` wrapper function

CONTRIBUTING.md
Had to ask this info from the rest of the team, ensures it's documented.
=> Update contributing guide to mention snapshot test updating

crates/turbopack-ecmascript/Cargo.toml, crates/turbopack-ecmascript/src/transform/mod.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_options_context.rs
In Next.js with webpack we have a feature to inline `typeof window` in server/client environments. That allows e.g.
```
"use client"
if(typeof window === 'undefined') {
import('server-only-package')
}
```
Today with Turbopack above code causes `server-only-package` to still be loaded in the browser compilation. Which causes issues like https://github.com/vercel/next.js/issues/66058 where the `if`/`else` condition is used to use different modules for server and client.
This change is required to pass the test in https://github.com/vercel/next.js/issues/66058
Pushing up the Next.js changes in that PR.
=> Add option for inlining typeof window

docs/pages/repo/docs/core-concepts/monorepos/task-graph.mdx
Remove the repeated word "the" before 'dependencies' to improve readability and clarity.
The fix, just remove a repeated work in the following sentence:
> In our Task Graph, the nodes are tasks and the edges are the dependencies between tasks.
Head over to the page [The Task Graph](https://turbo.build/repo/docs/core-concepts/monorepos/task-graph) and on the second paragraph, the word "the" is repeated in the sentence
> In our Task Graph, the nodes are tasks and the edges are the the dependencies between tasks.
=> Fix typo in Turborepo task-graph documentation

crates/turborepo-lib/src/daemon/mod.rs
Handshake logic works, we just need to bump the daemon version since it's independent(?) of the client version.
Future work is to keep this constant in lockstep with our client version to help us avoid forgetting to bump this.
Verify that running binary in a repo with a running 1.x daemon will result in the daemon getting shut down and a new one being started:
```
2024-05-28T10:17:35.750-0700 [DEBUG] turborepo_lib::daemon::connector: found pid: 6563                                                      
2024-05-28T10:17:35.750-0700 [DEBUG] turborepo_lib::daemon::connector: got daemon with pid: 6563                                                                                                                 
2024-05-28T10:17:35.766-0700 [DEBUG] turborepo_lib::daemon::connector: no pid …
```
=> chore: bump daemon version

crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/task_hash.rs, crates/turborepo/Cargo.toml
Turning off file hashing in run for now.
=> chore(turborepo): Feature flagged off file hashing

.github/workflows/turborepo-test.yml
It seems that something with the [Node 18.20.2 -> 18.20.3](https://github.com/actions/runner-images/pull/9941/files#diff-66aec6097318276b09842a3ba2caf3037afbd8dadca2dfcdf76631100613ea69L26) bump in `ubuntu-latest` is breaking how we expect corepack to behave. 
Pinning it for now.
CI
=> chore: pin node version to 18.20.2

packages/turbo-utils/__fixtures__/common/old-workspace-config/turbo.json, packages/turbo-utils/__fixtures__/common/single-package/turbo.json, packages/turbo-utils/__fixtures__/common/workspace-configs/apps/web/turbo.json, packages/turbo-utils/__fixtures__/common/workspace-configs/packages/ui/turbo.json, packages/turbo-utils/__fixtures__/common/workspace-configs/packages/utils/turbo.json, packages/turbo-utils/__fixtures__/common/workspace-configs/turbo.json, packages/turbo-utils/__tests__/getTurboConfigs.test.ts
I've confirmed that `turbo test -F @turbo/utils` passes on this branch
=> chore(@turbo/utils): update tests/fixtures to use tasks key

Cargo.lock
https://github.com/vercel/turbo/pull/8081 ended up breaking our Windows builds specifically when trying to build the test binaries. e.g. https://github.com/vercel/turbo/actions/runs/9187223596/job/25264529837#step:5:523
I'm still unsure of exactly why, but removing the `curl` and `tokio` version bumps that happened in that PR get us back to a working build.
Future work might be to switch from the MingW backend we're currently using to MSVC as that has better support and I believe we only needed to use MingW to support linking to Go.
Windows tests should now pass
=> chore: downgrade curl to fix Windows rust tests

.github/workflows/turborepo-test.yml
On the self hosted Ubuntu runners `TURBO_API` is set to a URL that the Turbo Team doesn't have permission to access leading to a loss of the remote cache functionality.
e.g.
https://github.com/vercel/turbo/actions/runs/9276119063/job/25522446449#step:7:478
This PR overrides this env var so we can leverage the remote cache.
The Ubuntu build of `turbo` should be a cache hit on this PR
https://github.com/actions/runner-images/pull/9941/files#diff-66aec6097318276b09842a3ba2caf3037afbd8dadca2dfcdf76631100613ea69L26
=> chore: override bad api url on ubuntu runners

crates/turborepo-scm/src/git.rs, crates/turborepo-scm/src/ls_tree.rs, crates/turborepo-scm/src/status.rs
We weren't passing `--no-optional-locks` when calling git. This was unnecessarily locking the index when we didn't need to. Now we pass the flag.
=> fix(turborepo): Remove optional git locks

crates/turborepo-lib/src/config.rs
TSIA
~~Unit test update shows that default is now true~~ I forgot that these tests don't run in a TTY so they still won't have the UI enabled.
Manual test that a fresh repo with no `experimentalUI` key in `turbo.json` will use the UI.
=> feat: enable UI by default

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/turbo_json/mod.rs
Rename `experimentalUI` to `ui` along with `TURBO_EXPERIMENTAL_UI` to `TURBO_UI` and removing `--experimental-ui` flag as now this is enabled by default so the flag isn't useful.
Existing test suite / 👀
=> chore: stabilize ui

packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/no-dot-env/turbo.json, packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/no-pipeline/turbo.json, packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/with-dot-env/turbo.json, packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/workspace-configs/apps/docs/turbo.json, packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/workspace-configs/apps/web/turbo.json, packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/workspace-configs/packages/ui/turbo.json, packages/turbo-codemod/__tests__/__fixtures__/migrate-dot-env/workspace-configs/turbo.json, packages/turbo-codemod/__tests__/migrate-dot-env.test.ts, packages/turbo-codemod/src/transforms/migrate-dot-env.ts
#8253 and #8248 ended up landing close enough that they broke the branch. This PR updates the latter to use `tasks` instead of `pipeline`.
CI
=> chore: migrate dot-env migration to support latest schema

packages/turbo-codemod/__tests__/__fixtures__/migrate/turbo-1/package.json, packages/turbo-codemod/__tests__/__fixtures__/migrate/turbo-1/turbo.json, packages/turbo-codemod/__tests__/migrate.test.ts, packages/turbo-codemod/src/commands/migrate/index.ts, packages/turbo-codemod/src/commands/migrate/steps/getTransformsForMigration.ts, packages/turbo-codemod/src/transforms/add-package-names.ts, packages/turbo-codemod/src/transforms/migrate-dot-env.ts, packages/turbo-codemod/src/transforms/rename-output-mode.ts, packages/turbo-codemod/src/transforms/rename-pipeline.ts, packages/turbo-codemod/src/transforms/set-default-outputs.ts, packages/turbo-codemod/src/transforms/stabilize-ui.ts, packages/turbo-codemod/src/types.ts, packages/turbo-utils/src/getTurboConfigs.ts, packages/turbo-utils/src/index.ts
Add migration logic for the 1->2 move.
For the major bump we run all existing transforms that are safe to be run twice to ensure that `turbo.json` is in the desired state. 
A few things to note:
- We change the introduction version for the 2.0 codemods to the canary to allow for easier testing
- I updated `migrate-dot-env` to work with either `pipeline` or `tasks` as there isn't a great way to order transforms that are introduced in the same version.
- Add an idempotent flag to transformers that defaults to `true`. This is used to mark a transformation as one to avoid re-running.
Added unit test for major version migration.
Manual testing on repos via `turbo build --filter='@turbo/codemod'` and then using `node ~/code/turbo/packages/turbo-codemod/dist/cli.js migrate --to 2.0.0-canary.0` …
=> feat(codemod): add logic for major version bump

crates/turborepo-lib/src/config.rs
This was bothering me. We aren't deprecating `pipeline` (deprecation means the feature still exists but we don't recommend using it)
=> chore(turborepo): adjust error message for pipeline

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-ui/src/tui/app.rs
We had a race previously between switching to the alternative screen and the prelude being run. This PR moves the prelude printing to always happen before we switch to the alternative screen.
We also now flush `stdout` to ensure all of the prelude has been written before switching to the alternative screen.
No longer have bleed in `Terminal.app`
=> fix(ui): ensure prelude gets printed before ui starts

packages/turbo-codemod/src/transforms/rename-pipeline.ts
Change order of the object reconstruction so the spread operator happens first to keep the existing ordering of the keys, but only append tasks.
Run codemod on a test repo
Before:
After:
=> feat(codemod): place tasks last in turbo.json rewrites

Cargo.lock, Cargo.toml
Update swc_core
See [next.js counterpart](https://github.com/vercel/next.js/pull/66479)
---
- Closes https://github.com/vercel/next.js/issues/66378
- Closes https://github.com/vercel/next.js/issues/66237
- Closes https://github.com/vercel/next.js/issues/65763
=> feat: Update `swc_core` to `v0.92.8`

Cargo.lock, Cargo.toml, crates/turbo-prehash/Cargo.toml, crates/turbo-prehash/src/lib.rs
We have a few cases where certain keys are repeatedly inserted into hashmaps. In these situations we can prehash items. This crate will do that.
There is a basic doctest to demonstrate the functionality. The code is pretty straight forward.
=> add crate to calculate prehashes

packages/turbo-codemod/__tests__/__fixtures__/migrate/turbo-1/turbo.json, packages/turbo-codemod/package.json, packages/turbo-codemod/src/transforms/clean-globs.ts, packages/turbo-codemod/src/transforms/migrate-dot-env.ts, packages/turbo-codemod/src/transforms/migrate-env-var-dependencies.ts, packages/turbo-codemod/src/transforms/rename-output-mode.ts, packages/turbo-codemod/src/transforms/rename-pipeline.ts, packages/turbo-codemod/src/transforms/set-default-outputs.ts, packages/turbo-codemod/src/transforms/stabilize-env-mode.ts, packages/turbo-codemod/src/transforms/stabilize-ui.ts, packages/turbo-codemod/src/transforms/transform-env-literals-to-wildcards.ts, packages/turbo-codemod/src/utils/loadTurboJson.ts, pnpm-lock.yaml
Add a new utility for parsing `turbo.json` that uses JSON5.parse to support comments. This is already used for parsing workspace `turbo.json`s: https://github.com/vercel/turbo/blob/main/packages/turbo-utils/src/getTurboConfigs.ts#L95
Future work is probably unifying all of these read methods to a single one.
Added comment to top level to `turbo-1` fixture. This is a good candidate since the major version upgrade runs all codemods.
👀
=> fix(codemod): support jsonc when parsing root turbo.json

packages/turbo-codemod/__tests__/add-package-manager.test.ts, packages/turbo-codemod/__tests__/add-package-names.test.ts, packages/turbo-codemod/__tests__/clean-globs.test.ts, packages/turbo-codemod/__tests__/create-turbo-config.test.ts, packages/turbo-codemod/__tests__/migrate-dot-env.test.ts, packages/turbo-codemod/__tests__/migrate-env-var-dependencies.test.ts, packages/turbo-codemod/__tests__/migrate.test.ts, packages/turbo-codemod/__tests__/rename-output-mode.test.ts, packages/turbo-codemod/__tests__/rename-pipeline.ts, packages/turbo-codemod/__tests__/set-default-outputs.test.ts, packages/turbo-codemod/__tests__/stabilize-env-mode.test.ts, packages/turbo-codemod/__tests__/stabilize-ui.test.ts, packages/turbo-codemod/__tests__/transform-env-literals-to-wildcards.test.ts, packages/turbo-codemod/__tests__/transform.test.ts, packages/turbo-codemod/src/commands/migrate/index.ts, packages/turbo-codemod/src/commands/transform/index.ts, packages/turbo-codemod/src/runner/Runner.ts, packages/turbo-codemod/src/types.ts, packages/turbo-codemod/src/utils/logger.ts
In a silly turn of events, the object returned by the CLI has a `dryRun` field and not a `dry` field as expected.
Make sure `--dry` and `--dry-run` are respected. (Note that the pipeline rename transform is "skipped")
```
[0 olszewski@Chriss-MacBook-Pro] /tmp/codemod-tests $ node ~/code/vercel/turborepo/packages/turbo-codemod/dist/cli.js migrate --to=2.0.0-canary.2 --dry
? Where is the root of the repo to migrate? .
Upgrading turbo from 1.13.3 to 2.0.0-canary.2 (11 required codemods)
(1/11) Running add-package-manager
INFO  Set "packageManager" key in root "package.json" file...
UNCHANGED  package.json
Results:
┌──────────────┬─────────────┬───────────┬───────────┬────────┐
│ (index)      │ action      │ additions │ deletions │ error  │ …
```
=> fix(codemod): respect --dry flag

turborepo-tests/integration/tests/run-caching/root-deps.t
#8277 broke the branch by not properly updating the snapshot for the integration test
CI should pass
=> fix: update integration test to expect correct output

crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
This flag hasn't ever been respected in Rust. Use 2.0 to remove the frontend
Integration tests / 👀
=> chore: remove cpuprofile flag

crates/turbopack-trace-server/src/server.rs, crates/turbopack-trace-server/src/viewer.rs
This adds extra filtering options to the trace server to limit by some concrete value and occurences. There is an accompanying PR for the trace-viewer to add filtering options to the web UI
Closes TURBO-2575
=> [turbo trace] add ability to filter by value and occurences

Cargo.lock, Cargo.toml
Update `swc_core`, to apply https://github.com/swc-project/swc/pull/9019
It's required to use `swc_ecma_parser/tracing-spans`.
=> feat: Update `swc_core` to `v0.92.10`

crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/turbo_json/mod.rs, packages/turbo-codemod/__tests__/stabilize-ui.test.ts, packages/turbo-codemod/src/transforms/stabilize-ui.ts, packages/turbo-types/src/types/config.ts
It was mentioned that `"ui": false` doesn't make much sense. We replace that in this PR with `"tui"` for the rich terminal output and `"stream"` for the non-TTY behavior.
Updated migration and unit tests. Quick manual check on a test repo.
=> feat: change values of "ui" in turbo.json

crates/turbo-tasks-macros-shared/src/expand.rs, crates/turbo-tasks-macros/src/derive/deterministic_hash_macro.rs, crates/turbo-tasks-macros/src/derive/trace_raw_vcs_macro.rs, crates/turbo-tasks-macros/src/derive/value_debug_format_macro.rs, crates/turbo-tasks/src/debug/internal.rs
I noticed that `ValueDebugFormat` was pretty common near the top of `cargo llvm-lines`. It looked like this was probably due to the large number of await points inserted into the code. Each await point complicates the state machine that rustc must generate and pass to LLVM.
This reduces the number of await points from one per field to one per struct. There's a minor change in behavior as the child fields are awaited concurrently (`join_all`) instead of one-at-a-time.
Less code generated by macros and passed to LLVM should mean faster compiles and a smaller binary that we're shipping to the user. The total change here is pretty small though, so it's probably not worth benchmarking compile times.
```
cargo test -p turbo-tasks-macros-tests
```
```
cargo llvm-lines -p next-swc-napi
``` …
=> Reduce amount of code generated by ValueDebugFormat

crates/turbo-tasks/src/task/function.rs
I noticed a number of small optimizations that could be applied to these hot and heavily-monomorphized functions:
- Using `with_context()` instead of `.context()`, to avoid evaluating the error message in the common case that it's unused. I also tried `concat!()` since this can be a static string, but the resulting binary is slightly larger, and we don't need to optimize for the unlikely error case.
- Extracted the parts of the monomorphized functions that didn't require the type parameters into separate non-generic functions. While the goal here is mostly to reduce binary size and compilation time, this optimization on it's own seems to help with the runtime benchmarks too (though I didn't test it rigorously in isolation).
Here's a section from [Rust for …
=> Minor optimizations to the codegen of TaskFnInputFunction

crates/turbopack/src/module_options/mod.rs
We create `Internal` `ReferenceType`s for these config files that need to be processed as JSON. This sets the ModuleEffect for JSON types to run on all references, like other file types.
Test TBD
=> Postcss: fix failures processing .postcssrc.json

packages/turbo-codemod/__tests__/__fixtures__/add-package-names/ignored-packages/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/ignored-packages/packages/ui/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/ignored-packages/packages/utils/package.json, packages/turbo-codemod/__tests__/__fixtures__/add-package-names/ignored-packages/pnpm-workspace.yaml, packages/turbo-codemod/__tests__/add-package-names.test.ts, packages/turbo-workspaces/src/getWorkspaceDetails.ts, packages/turbo-workspaces/src/utils.ts
Closes #8327. We now factor in negated globs
Added a test to `add-package-name` migration that ensures we ignore package covered by negated glob
=> fix(turborepo): factor in negated globs for workspace detection in codemods

crates/turbopack-ecmascript-plugins/src/transform/directives/client_disallowed.rs, crates/turbopack-ecmascript-plugins/src/transform/directives/mod.rs, crates/turbopack-ecmascript-plugins/src/transform/directives/server_to_client_proxy.rs
needed for next.js to disallow "use client" on middleware and instrumentation
=> add client disallowed transform

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/mod.rs
Fixes #8323
The TUI was crashing as it was failing when attempting to read from `stdin` that was closed by `pre-commit`. The fix is to not read from `stdin` if there isn't user input coming from there.
Closing `stdin` should no longer cause `turbo` to crash if stdout is still a TTY e.g. `turbo_dev build < /dev/null`
Also verify that reproduction https://github.com/isaacharrisholt/turborepo-precommit-bug/tree/main no longer crashes when using changes from this PR.
=> fix(ui): no longer attempt to read from stdin if non-tty

crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/fixtures/monorepo_with_root_dep/turbo.json, turborepo-tests/integration/tests/prune/produces-valid-turbo-json.t
Solves the issue reported here: https://github.com/vercel/turbo/issues/8311#issuecomment-2148968155 
The `biome` deserialization defaults to camel case, whereas the `serde` serialization implementation doesn't.
Added unit tests as well as updated the `prune` test fixture to include `"ui": "stream"`
=> fix: correctly serialize ui values

Cargo.lock, crates/turbopack-ecmascript-plugins/Cargo.toml, crates/turbopack-ecmascript-plugins/src/transform/directives/client.rs, crates/turbopack-ecmascript-plugins/src/transform/directives/server.rs, crates/turbopack-ecmascript-plugins/src/transform/emotion.rs, crates/turbopack-ecmascript-plugins/src/transform/modularize_imports.rs, crates/turbopack-ecmascript-plugins/src/transform/relay.rs, crates/turbopack-ecmascript-plugins/src/transform/styled_components.rs, crates/turbopack-ecmascript-plugins/src/transform/styled_jsx.rs, crates/turbopack-ecmascript-plugins/src/transform/swc_ecma_transform_plugins.rs, crates/turbopack-ecmascript/src/parse.rs
allows to investigate parsing slowness
=> add more tracing to transforms and parsing

crates/turbo-tasks/src/manager.rs
avoid keeping the borrow too long
=> improve borrow_mut

crates/turborepo-lib/src/task_hash.rs
[`NODE_OPTIONS`](https://nodejs.org/api/cli.html#node_optionsoptions) can do many things, but it is especially used to bump heap limits. With env mode strict this can cause OOMs when using `turbo`.
👀
=> fix: add NODE_OPTIONS to default pass through env vars

crates/turborepo-lib/src/task_hash.rs
=> chore: add additional env vars to default pass through

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs
The concept of log ordering doesn't apply to the TUI. If a user requests a specific log order we should disable the TUI to achieve that.
This PR disables the TUI if a user specifies a non-default `--log-order`
```
[0 olszewski@chriss-mbp] /tmp/turbov2 $ turbo_dev build --log-order=grouped
• Packages in scope: app-a, app-b, pkg-a, pkg-b, tooling-config
app-b:build: cache hit (outputs already on disk), replaying logs 5fa82274708c3b22
app-b:build: 
app-b:build: > build
app-b:build: > mkdir -p dist && echo "Your application output!" > dist/app-output.txt && echo "Application B is built!"
app-b:build: 
app-b:build: Application B is built!
pkg-b:prebuild: cache hit (outputs already on disk), replaying logs cf6a216ade97c1f2
pkg-b:prebuild: …
```
=> fix(ui): disable TUI if log order is specified

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-repository/src/change_mapper/mod.rs, crates/turborepo-repository/src/package_graph/mod.rs, turborepo-tests/integration/tests/run-caching/root-deps.t
When using a git based filter, internal package dependencies of the root should be accounted for. Since these contribute directly to the global hash any of these changes trigger all packages ending up in scope.
Added integration test using SCM based filter
=> fix(filter): account for root internal dependencies in git based filter

crates/turbopack-core/src/chunk/mod.rs, crates/turbopack-core/src/environment.rs, crates/turbopack-ecmascript-runtime/src/dev_runtime.rs, crates/turbopack-ecmascript/src/references/esm/dynamic.rs
Changing the name in order to reflect reality after talking to @sokra.
=> Rename ChunkLoading::None to ChunkLoading::Edge

crates/turbopack-tests/tests/execution/turbopack/minification/paren-remover/input/index.js
I copied the test from https://github.com/swc-project/swc/pull/8442. This input file fails if the `paren_remover` is not applied.
Closes PACK-3110
=> test: Add an execution test for `paren_remover`

crates/turborepo-lib/src/shim.rs
Let's make sure we give an extra little bump in this situation. A warn, instead of only a `println!`. Realistically, this isn't a situation that folks want to be getting themselves into often/purposefully.
=> Warn instead of print when no locally installed  version.

crates/turborepo-lib/src/task_hash.rs
By convention, CI systems will set a `CI` environment variable. Given the ubiquity of this variable, there are some tools that rely on this variable, which is what I think we're seeing in #8281.
=> Add CI to default passthroughs.

crates/turbopack-trace-server/src/viewer.rs
getting the id of the root span is not valid
=> fix panic in debug mode

Cargo.lock, Cargo.toml
Update `swc_core`. The regression of minifier is fixed by https://github.com/swc-project/swc/pull/9031
- Closes https://github.com/vercel/next.js/issues/66182
=> build: Update `swc_core` to `v0.93.2`

crates/turbo-tasks-malloc/src/counter.rs, crates/turbo-tasks-malloc/src/lib.rs
reallocations were not counted correctly in the tracing
=> fix counting of reallocations

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/process/mod.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-repository/src/package_manager/mod.rs
We don't need these serde derives anymore since we're not serializing the args to pass to Go.
=> chore(turborepo): remove unused code

Cargo.lock, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/panic_handler.rs, crates/turborepo/Cargo.toml, crates/turborepo/src/main.rs
When running in CI persisting the panic backtrace to a tempfile makes it harder (or impossible) to get the entire backtrace.
This PR changes our behavior to no longer will persist the backtrace to a file if we detect we're running in CI or a vendor, instead we include the serialized backtrace in the message we print to the console.
First commit is moving the panic handler to the library crate to avoid adding dependencies to the binary crate.
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev --version
Oops! Turbo has crashed.
A report has been written to /var/folders/3m/rxkycvgs5jgfvs0k9xcgp6km0000gn/T/report-319148de-342d-49f8-a87c-aa9c6d7b0cbd.toml
Please open an issue at https://github.com/vercel/turbo/issues/new/choose and include this file
[101 …
```
=> fix: disable panic handler in ci

examples/basic/turbo.json
Improve handling of `.env`s in `basic` example.
=> Remove global dep from basic example.

docs/repo-docs/guides/ci-vendors/github-actions.mdx
As I see it, since the default cache location is now `<root-dir>/turbo/.cache` due to #8126, there's no longer a point in specifying the --cache-dir=.turbo as it is redundant no?
Run a GitHub actions with https://turbo.build/repo/docs/guides/ci-vendors/github-actions#caching-with-github-actionscache and see if it caches properly
=> docs: Remove --cache-dir from github actions docs due to #8126

Cargo.lock, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/error.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-ui/Cargo.toml, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/mod.rs
Avoids starting the UI when the terminal is too small. Also bumps crossterm because apparently we get an incorrect terminal size on older versions.
Tested with `lefthook` on create-turbo
=> fix(turborepo): avoid starting ui on too small terminals

crates/turbopack-cli-utils/src/runtime_entry.rs, crates/turbopack-cli/src/dev/web_entry_source.rs, crates/turbopack-core/src/chunk/mod.rs, crates/turbopack-core/src/introspect/utils.rs, crates/turbopack-core/src/reference/mod.rs, crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-css/src/asset.rs, crates/turbopack-ecmascript/src/references/mod.rs
That reduces the task count and improve memory usage
=> reduce resolve tasks for resolving

crates/turbopack-core/src/resolve/mod.rs, crates/turbopack-core/src/resolve/plugin.rs
This expands `BeforeResolvePluginCondition` to match on individual modules rather than just the request string.
Needed for https://github.com/vercel/next.js/pull/66622
=> BeforeResolvePluginCondition: allow module filtering as a condition for `BeforeResolvePlugin`s

packages/create-turbo/src/transforms/official-starter.ts
Previously, we were putting `turbo@latest` into `package.json` for the `devDep` when creating a repo with `create-turbo`. Generally, using the `latest` tag isn't a great practice, so let's use the carat version of `create-turbo` itself instead. We're safe to use this since `create-turbo`'s version tracks along with `turbo` itself.
Tested locally by building the package and running the `dist/cli.js`. I also tried it out with canary and stable versions manually placed into the `create-turbo` `package.json#version`.
=> Update `create-turbo` to use carat versions.

crates/turborepo-lib/src/shim/local_turbo_state.rs
Since this function is now possibly getting user input, we shouldn't hard crash if whatever they have listed in their lockfile doesn't pass the `semver` crate's version requirement.
This shouldn't happen as all lockfiles are generated with fully resolved versions, but this prevents a panic if that expectation changes.
Added unit tests that would trigger a panic previously
=> fix(shim): avoid panic if user has malformed lockfile

packages/turbo-codemod/__tests__/migrate.test.ts
This test has recently been [exceeding the default timeout](https://github.com/vercel/turbo/actions/runs/9490414083/job/26153864516#step:6:977) when trying to cut a release. Bumping this to prevent this from blocking releases.
CI
=> chore: bump timeout for migration

crates/turbopack-ecmascript/src/references/external_module.rs
Gets called via `content_changed` to detect source changes.
Closes PACK-3114
=> fix(turbopack): make external module wrapper return not found instead of panicking

Cargo.lock, Cargo.toml
Update `swc_core` to `v0.93.4`.
To apply https://github.com/swc-project/swc/pull/9036 and https://github.com/swc-project/swc/pull/9037. Those PR makes parsing of some files 5x faster.
See next.js counterpart: https://github.com/vercel/next.js/pull/66781
=> build: Update `swc_core` to `v0.93.4`

crates/turborepo-lib/src/task_hash.rs
Partially addresses #8429
`chalk` the widely used library doesn't just factor in if stdout/stderr are TTY for emitting color. In [heavily relies](https://github.com/chalk/chalk/blob/386909ee0bfe4346d04e3eeba712f0db597c038d/source/vendor/supports-color/index.js#L60) on environment variables for deciding what level of color to output.
In strict mode many of these env vars are stripped leaving us with [color level 0](https://github.com/chalk/chalk/blob/386909ee0bfe4346d04e3eeba712f0db597c038d/source/vendor/supports-color/index.js#L94) aka disabled.
`TERM`/`COLORTERM`/`TERM_PROGRAM` should cover the bases for most terminals looking at the `chalk` source.
Eslint should now have produce color even in env strict mode:
=> fix(ui): pass through terminal env vars to appease chalk

packages/devlow-bench/package.json
npm scoped packages are private access by default. This opts `@vercel/devlow-bench` into public publishing.
=> Publish `@vercel/devlow-bench`

Cargo.lock, crates/turbo-tasks-malloc/Cargo.toml, crates/turbo-tasks-malloc/src/lib.rs
- **Update mimalloc** dependency.
- **Enable mimalloc for Linux on aarch64 with glibc:** it seems to work just fine!
- **Disable mimalloc for wasm and musl.** Mimalloc is already disabled for these platforms in next-swc, but I want to centralize these platform checks: https://github.com/vercel/next.js/blob/73918c6711b538678dd66303fdbd61bfd10b288c/packages/next-swc/crates/napi/src/lib.rs#L71
- **Reduce duplicate code across platforms.** The two implementations of `TurboMalloc` were identical, aside from the base allocator used. Move the compile-time branch into an inlined function.
**Related Next.JS PR:** https://github.com/vercel/next.js/pull/66815
```
pnpm pack-next
```
Install into a test project and try running the development server.
I have not tested other platforms, and will rely on …
=> Update mimalloc, enable for glibc Linux aarch64, explicitly disable for wasm and musl

crates/turborepo-repository/src/package_graph/mod.rs, turborepo-tests/integration/tests/run-caching/root-deps.t
Dependency and dependent filters should factor in root dependencies since they're implicit dependencies of all packages in the workspace.
We cannot add the root deps to `immediate_dependencies` or `immediate_ancestors` as these are used during a graph traversal and adding in the root deps can easily cause cycles.
The transitive versions of these are safe to add the root dependencies to since they return entire closures.
Added integration tests
Manual testing:
```
[0 olszewski@chriss-mbp] /tmp/pnpm-test $ turbo_dev build --filter='web...' --dry=json | jq '.packages'
WARNING  No locally installed `turbo` found. Using version: 2.0.4-canary.2.
[
"@repo/eslint-config",
"@repo/typescript-config",
"@repo/ui",
"@repo/util",
"web"
]
[0 olszewski@chriss-mbp] /tmp/pnpm-test $ turbo_dev build …
```
=> fix: factor in root dependencies into ... filters

crates/turbopack-trace-server/src/reader/mod.rs, crates/turbopack-trace-server/src/store_container.rs
This allows to read files faster when they are also open in the trace viewer
=> read larger chunks when reading a trace file

crates/turbopack-core/src/reference/mod.rs
cheaper graph traversal as we don't have to process these modules multiple times
=> avoid duplicates in primary_modules

crates/turbo-tasks/src/graph/graph_traversal.rs
=> only create spans for nodes that are actually visited

crates/turbopack-bench/README.md, crates/turbopack-bench/src/bundlers/nextjs/mod.rs, crates/turbopack-bench/src/util/mod.rs
- Ensures that the benchmarks don't fail on installing as `prefer-offline` doesn't work reliably.
- Installs `react@rc` and `react-dom@rc` for `next@canary` as it requires React 19.
- Updated the benchmark docs to show to to run one suite
=> Fix Turbopack benchmark for next@canary
