crates/turborepo-lib/src/commands/link.rs
=> Spruce up Remote Cache linking message.

packages/turbo-codemod/src/transforms/stabilize-env-mode.ts, packages/turbo-types/src/types/config.ts
Env mode config was stabilized back in 1.10, this PR removes the experimental fields. 
Type checking and codemod tests pass
=> chore(@turbo/types): remove deprecated fields

crates/turborepo-lib/src/commands/link.rs, crates/turborepo-vercel-api/src/lib.rs
Vercel changed how personal accounts work so that they are team accounts. This meant this implementation was writing personal teams twice.
Note: This change should only affect Vercel to compensate for those internal changes. Non-Vercel systems should be unaffected.
Run `turbo link`.
=> Fix outdated user listing.

crates/turbo-tasks-memory/tests/scope_stress.rs
I've noticed this test often times out on CI (after >10 minutes!), possibly because it runs out of ram and starts swapping.
This decreases the size significantly (this is `O(n^2)`). Locally the test now runs in about 1-2 seconds on my local machine (versus >30 seconds).
```
cargo test -p turbo-tasks-memory rectangle_stress
```
```
TURBOPACK_TEST_RECTANGLE_STRESS_SIZE=100 cargo test -p turbo-tasks-memory rectangle_stress
```
=> Decrease default scope_stress test size, add env var config

packages/turbo-codemod/__tests__/add-package-manager.test.ts, packages/turbo-codemod/src/transforms/add-package-manager.ts
Fixes #8308
Previously we would attempt to update the `packageManager` field to whatever version we found for the listed package manager based on the current `PATH`/cwd. This PR removes that behavior and now trusts the user if they have one listed in `package.json`.
With the adoption of `corepack` more often then not, we want the contents of `package.json` to inform the binary used instead of the other way around. 
Updated existing unit tests to no longer expect changes
=> fix(codemod): avoid overwriting existing packageManager field

Cargo.lock, Cargo.toml
This PR updates swc_core from https://github.com/swc-project/swc/commit/e640972daec683edea836368a8fccb5b41520c2a to https://github.com/swc-project/swc/commit/60ae1f75b55732dd509647d7294b53fb711af7f8
To keep in sync and apply performance improvements of SWC.
See next.js counterpart: https://github.com/vercel/next.js/pull/67082
=> Update `swc_core` to `v0.95.4`

.github/workflows/lsp.yml, crates/turborepo-lib/src/lib.rs, crates/turborepo-lsp/src/lib.rs, packages/turbo-vsc/.vscodeignore, packages/turbo-vsc/package.json, pnpm-lock.yaml
A small fix to surface an error in UI if there is a version mismatch in turbo, as well as updating the LSP to support the new protocol version.
This also updates the lsp CI to use our setup-rust workflow rather than hand rolling one
Open up a project with 2.0 of the extension, with turbo 1.0. Observe a nice error message, instead of returning an internal error. Observe that LSP features don't 'work' but at least gracefully degrade.
=> Release LSP 2.0

.github/workflows/lsp.yml
I omitted them on the 1.x PR since I assumed the breakage happened post 2.0. That is not the case. Proof it works here:
https://github.com/vercel/turbo/actions/runs/9647796759
1/6 is expected to fail, since we don't support arm windows (yet)
=> Get LSP building on 1.x branch

crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/table.rs
Some light TUI refactors.
- Removing some of the borders around the logs pane for less visual clutter
- Interactivity instructions in logs pane use state to show "enter" vs. "exit" instructions
- "Localize" the instructions for moving up and down the task list to the task list itself
👀 
If we could get the red-to-blue gradient on the left sidebar when interactive... :chefs-kiss: - but I haven't looked at how to do that with Ratatui yet.
=> Light refactoring of TUI pane and instructions.

crates/turbo-tasks-build/src/lib.rs
I noticed this wasn't implemented when trying to write some unit tests inside of `mod tests`.
The same visibility requirements apply (must be at least `pub(crate)`).
Tested as part of https://github.com/vercel/turbo/pull/8529
=> Support turbo tasks inside of `mod` blocks

Cargo.lock, crates/turbo-tasks-build/Cargo.toml, crates/turbo-tasks-build/src/lib.rs
If a task is conditionally compiled, we must conditionally register it.
Noticed this when trying to write a test with `#[cfg(test)]`.
**Related:** #8530 adds support for registering tasks inside of `mod foo { ... }` blocks.
Tested as part of #8529
=> Handle `#[cfg(...)]` attributes on turbo tasks

crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks/src/backend.rs
I noticed this logic was duplicated across `turbo-tasks-memory` and `PersistentTaskType`.
This makes sense as a method on `PersistentTaskType`, so put the logic there, and call it from both places.
```
cargo test -p turbo-tasks test_get_name
```
=> Deduplicate persistent task get_function_name logic

crates/turbopack-cli/src/main.rs, crates/turbopack-trace-utils/Cargo.toml, crates/turbopack-trace-utils/src/exit.rs
I need a better system for handling process exit to handle flushing to cache hit statistics (#8286).
- Supports letting another thing listen for <kbd>ctrl</kbd> + <kbd>c</kbd>. In the case of next-server, we need to let node.js own and configure these signal handlers.
- Supports setting up a <kbd>ctrl</kbd> + <kbd>c</kbd> handler for you, but now explicitly panics if you would try to set up multiple global <kbd>ctrl</kbd> + <kbd>c</kbd> listeners.
- Allows async work to happen during cleanup. This wasn't possible using `Drop` because `Drop` isn't async.
- Allows cleanup work to be scheduled after application initialization, potentially making the API a bit more flexible.
```
cargo test -p turbopack-trace-utils
```
Add some `println!()` logging to the end of the `on_exit` future in …
=> Add new ExitHandler API as an alternative to ExitGuard

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/input.rs
Previously we weren't `app.stop()` would exit before the TUI cleanup completed. This resulted in a race condition between the TUI cleanup and the run summary getting printed.
This PR changes the call to now wait until cleanup completes before returning ensuring that the run summary is written only after the TUI exits.
Run a task a few times and you should see the run summary either not get rendered *or* getting rendered before the terminal is back in cooked mode.
Before:
After:
=> fix(ui): wait until task output is fully rendered on stop

crates/turborepo-repository/src/package_graph/builder.rs
Fixes #8168
When adding the additional variant for pnpm9 the logic for parsing `.npmrc` didn't get enabled for it. This meant if the user explicitly enabled `link-workspace-packages = true` in `.npmrc` it wouldn't be respected.
Verify that `.npmrc`'s `link-workspace-packages` is now respected for pnpm9:
Clone https://github.com/issueset/turborepo-pnpm9-graph
Checkout branch `pnpm9-2.0.4`
Make sure that all edges are picked up
```
[0 olszewski@chriss-mbp] /tmp/turborepo-pnpm9-graph $ turbo_dev --skip-infer build --graph
digraph {
compound = "true"
newrank = "true"
subgraph "root" {
"[root] @acme/core#build" -> "[root] @acme/eslint-config#build"
"[root] @acme/core#build" -> "[root] @acme/tsconfig#build"
"[root] @acme/docs#build" -> "[root] @acme/core#build"
"[root] @acme/docs#build" -> …
```
=> fix(pnpm): enable npmrc parsing for pnpm 9

.github/turbo-orchestrator.yml
Most of Alex's PRs are not turborepo related anymore. Applying this label also creates a Linear issue, so I'm removing it here.
=> chore: updated team members who get turborepo label

docs/repo-docs/reference/configuration.mdx
Fixes #8582.
Removed trailing commas where not needed and added where needed.
Honestly this was a blind fix, I tried to run docs locally following `contributing` and `troubleshooting`, installed `go`, `capnp`, and all other packages, but I always run in some sort of problem.
`pnpm docs` opened `https://www.npmjs.com/package/cli` on the browser, sometimes i had
> × No package found with name 'docs' in workspace
I'm sorry if I wasn't able to follow a real contribution steps, if someone can help me go through this I will be happy for this and future contribution.
Have a nice day!
=> docs: fixing trailing commas in `configuration.mdx`

crates/turbo-tasks/src/id.rs, crates/turbo-tasks/src/lib.rs
This is currently unused. It existed for persistent caching, but it sounds like we likely won't go with this mapping approach:
> It was used for persistent caching, but it looks like we probably take a different approach (same ids between persistent cache and memory cache). So you can remove it.
-- https://vercel.slack.com/archives/C03EWR7LGEN/p1719340628045969?thread_ts=1719338013.257509&cid=C03EWR7LGEN
=> Delete unused TASK_ID_MAPPING support

crates/turbo-tasks-memory/src/task.rs
this reduces the memory size of TaskState
=> move stateful flag into Done state

crates/turbopack/src/module_options/mod.rs
Currently MDX files are incorrectly compiled using the development transform which causes `jsxDev` calls that don't work in production, this PR ensures MDX follows the JSX setting.
=> MDX support: Ensure development transform is only used in development

crates/turbo-tasks-memory/src/output.rs
remove unused updates counter
box rarely used panic enum variant to reduce enum size
=> reduce size of task output struct

docs/repo-docs/guides/tools/typescript.mdx
Removed extra `{` at the end of the code snippet for a tsconfig.json file.
=> fix(docs): update docs typo

examples/kitchen-sink/apps/blog/package.json
`@repo/ui` is being used as a monorepo dependency and `^` is not a valid version number. This is supposed to be `*` as it is in other packages. This causes `npm install` to fail while installing dependencies.
=> fix(turborepo): update package.json typo

Cargo.lock, Cargo.toml, crates/node-file-trace/src/lib.rs, crates/turbo-tasks/Cargo.toml, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/read_ref.rs, crates/turbo-tasks/src/task/concrete_task_input.rs, crates/turbo-tasks/src/triomphe_utils.rs, crates/turbo-tasks/src/value.rs, crates/turbo-tasks/src/value_type.rs, crates/turbopack-cli/src/dev/mod.rs, crates/turbopack-core/src/issue/mod.rs
This eliminates the unused weakref count in `std::sync::Arc`, saving 64 bits per unique `SharedReference`.
I noticed there's additional potential optimizations we could do here too (not included in this PR), of increasing levels of difficulty:
- We can deduplicate `ValueTypeId` by moving it inside the `Arc`.
- We can build a mapping of `std::any::TypeId` to `ValueTypeId`, and avoid storing the `ValueTypeId` entirely.
- We can deduplicate the fat pointer's layout metadata by also storing it inside the `Arc` using the nightly `ptr_metadata` feature, similar to `triomphe::ThinArc` (but that only works for slices of non-dst elements, presumably because they don't want to depend on nightly).
Using dhat for measuring the max heap size (vercel/next.js/67166)...
Do a release build
``` …
```
=> Memory: Use `triomphe::Arc` for `SharedReference`

crates/turborepo-ui/src/tui/spinner.rs
User feedback has let us know that the constant spinner on persistent tasks can be annoying. Let's use the static double arrow instead to indicate that the tasks are in-progress.
👀
New:
=> fix(ui): Use double arrow instead of spinner for active tasks.

docs/repo-docs/reference/configuration.mdx
`v2.0.6` flipped the default `ui` config back to `stream`: #8631
=> docs(turborepo): correct default `ui` config value

crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/src/task/aggregation.rs
=> box InProgress task state

crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/completion.rs, crates/turbo-tasks/src/debug/mod.rs, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/task/concrete_task_input.rs, crates/turbo-tasks/src/task/function.rs, crates/turbo-tasks/src/task/task_input.rs, crates/turbo-tasks/src/trait_ref.rs, crates/turbo-tasks/src/triomphe_utils.rs, crates/turbo-tasks/src/vc/cast.rs, crates/turbo-tasks/src/vc/mod.rs, crates/turbo-tasks/src/vc/read.rs, crates/turbo-tasks/src/vc/traits.rs
Docs live here: https://turbopack-rust-docs.vercel.sh/rustdoc/turbo_tasks/index.html
- Fixed lots of links.
- Export `VcCast`, `VcValueTypeCast`, and `VcValueTraitCast`, as they're used in some type signatures, and some documentation is impossible to follow without it. This introduces the sealed trait pattern to `VcCast` to continue to strongly prevent foreign implementations.
```
cargo doc --keep-going -p turbo-tasks
cargo doc --keep-going --document-private-items -p turbo-tasks
```
=> Lots of small fixes to docs in the turbo-tasks crate

crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/completion.rs, crates/turbo-tasks/src/debug/mod.rs, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/raw_vc.rs, crates/turbo-tasks/src/task/concrete_task_input.rs, crates/turbo-tasks/src/task/function.rs, crates/turbo-tasks/src/task/task_input.rs, crates/turbo-tasks/src/trait_ref.rs, crates/turbo-tasks/src/triomphe_utils.rs, crates/turbo-tasks/src/vc/cast.rs, crates/turbo-tasks/src/vc/mod.rs, crates/turbo-tasks/src/vc/read.rs, crates/turbo-tasks/src/vc/traits.rs
I noticed we were doing the typecast inside `ReadRawVcFuture`. This felt bad for a few reasons:
- It's confusing that `IntoFuture` for `Vc` exposes a "raw" type to userspace. `RawVc` is a concept that only turbo-tasks internals and backends should deal with.
- `RawVc` is the type-erased version of `Vc`, so it's wrong for it to do the cast. `Vc` should do the cast.
- `ReadRawVcFuture` has a large `poll` method and many different values for `T`, so it would be ideal to avoid monomorphizing that (this seems to be a huge advantage of `RawVc`!), but unfortunately since this did a cast, it was being monomorphized.
This moves the casting logic and type annotations into a new `ReadVcFuture` type that wraps `ReadRawVcFuture`.
*This is an easy-to-measure proxy metric for rustc build times. As …
=> Move the typecast out of ReadRawVcFuture and into a new wrapper type

crates/turbo-tasks-auto-hash-map/src/map.rs, crates/turbo-tasks-memory/src/aggregation/mod.rs, crates/turbo-tasks-memory/src/aggregation/notify_lost_follower.rs, crates/turbo-tasks-memory/src/aggregation/uppers.rs, crates/turbo-tasks-memory/src/count_hash_set.rs, crates/turbo-tasks-memory/src/task.rs
When unloading tasks, edges from the aggregation structure are removed, but their memory is not reclaimed as Vecs don't shrink automatically.
This adds a `shrink_amortized` method which shrinks the Vec/HashMap when capacity is 2 times larger than length.
This also calls `shrink_to_fit` when running GC on a task.
=> automatically shrink aggregation lists

crates/turbopack-ecmascript-plugins/src/transform/relay.rs
`swc_relay` implements its own logic for locating the `__generated__` directory relative to the input file[0]
Test Plan: `TURBOPACK_BUILD=1 TURBOPACK=1 pnpm test-dev test/integration/relay-graphql-swc-single-project/test/index.test.js`
[0] https://github.com/swc-project/plugins/blob/8c1c1513b9d445e27d47407a9a3dea4fc53e185a/packages/relay/transform/src/lib.rs#L250-L254
=> Turbopack + Relay: don’t manually provide a fallback artifact_directory

.vscode/extensions.json
We don't use Go anymore - so these aren't needed.
It's a no-op to remove these.
=> remove Go VSCode recommendations in `extensions.json`

docs/repo-docs/crafting-your-repository/structuring-a-repository.mdx
Corrected a missing comma between items in a JSON array, which caused an error when copying and pasting a code fragment into a JSON file
=> fix: repo-docs

.github/actions/setup-node/action.yml, .github/workflows/turborepo-release.yml
Our release was broken due to a bump in the global NodeJS version which causes a failure when trying to setup `pnpm`: https://github.com/vercel/turbo/actions/runs/9812173678
Following directions on https://github.com/pnpm/action-setup/issues/135 to update to v4 of the action
We also need to add `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION` in order to keep using Node 16 for checking out our code for our MUSL builds where we need an old version of GLIBC.
Test run: https://github.com/vercel/turbo/actions/runs/9812969175
=> chore: bump pnpm action version

.github/actions/setup-rust/action.yml, .github/actions/setup-turborepo-environment/action.yml, .github/workflows/bench-turborepo.yml, .github/workflows/turborepo-release.yml, .github/workflows/turborepo-test.yml
Now that we no longer need to support linking to a Go library we can use the MSVC backend.
This PR removes our overrides for Windows to use the GNU backend and removes the parameter to enable this as well.
CI
[Test release](https://github.com/vercel/turbo/actions/runs/9813223825). Verified produced binary runs as expected on a Windows machine.
=> chore: use msvc for turborepo

.cargo/config.toml, Cargo.lock, Cargo.toml, crates/turbopack-core/src/environment.rs, crates/turbopack-ecmascript-plugins/src/transform/relay.rs, crates/turbopack-ecmascript/src/parse.rs, crates/turbopack-swc-ast-explorer/src/main.rs, crates/turbopack-tests/tests/snapshot/emotion/emotion/output/crates_turbopack-tests_tests_snapshot_b36339._.js
Update SWC crates to https://github.com/swc-project/swc/commit/226617e73edb2070ea1d4be2da93239b3f3ebc88 and https://github.com/swc-project/plugins/commit/b7658c3153b1f1e3c941bc0f6bdae6856f5d278c
- Closes https://github.com/vercel/next.js/issues/64890
- Closes https://github.com/vercel/next.js/issues/63104
See https://github.com/vercel/next.js/pull/67378
=> Update `swc_core` to `v0.96.5`

docs/repo-docs/crafting-your-repository/structuring-a-repository.mdx, docs/repo-docs/guides/multi-language.mdx
The extension for a pnpm workspace manifest file should be `yaml`, not `yml`. Using `yml` provides an error: `The workspace manifest file should be named "pnpm-workspace.yaml"`
pnpm documentation for workspace manifests: https://pnpm.io/pnpm-workspace_yaml
=> fix(docs): fix pnpm workspace filename extension

docs/repo-docs/crafting-your-repository/running-tasks.mdx
`errors-only` is the correct option
option that only shows logs for task failures.
Fixes a minor typo in `crafting your repository` section of turbo repo docs.
=> docs: Fix typo in filter option.

crates/turbo-tasks-memory/src/aggregation/followers.rs, crates/turbo-tasks-memory/src/aggregation/increase.rs, crates/turbo-tasks-memory/src/aggregation/tests.rs, crates/turbo-tasks-memory/src/aggregation/uppers.rs
Improves performance for larger applications by up to 30%
improves memory usage a bit
=> improve performance of the graph aggregation

.github/workflows/turborepo-test.yml, cli/turbo.json
It appears that when using the MSVC backend `rustc` depends on `ProgramData` for finding Windows libs. This getting trimmed resulted in failing builds.
Windows CI now passes
=> fix(windows): pass through programdata env var

crates/turbopack-css/src/process.rs
@rauchg reported:
```
thread 'tokio-runtime-worker' panicked at /Users/geist/.cargo/git/checkouts/turbo-df7a549334890fa5/2af6b12/crates/turbopack-css/src/process.rs:439:22:
internal error: entered unreachable code: this case should be filtered out while parsing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(https://vercel.slack.com/archives/C01A2M9R8RZ/p1720449958135569)
A review of the code confirms that this should be unreachable under normal circumstances:
> There's a check here that `FileContent::Content` exists before constructing the `ParseCssResult::Ok` that's needed to reach the line that contains the `unreachable!` assertion: https://github.com/vercel/turbo/blob/main/crates/turbopack-css/src/process.rs#L491
But there's no guarantee that the …
=> Replace `unreachable` with `bail` in `finalize_css`

crates/turborepo-lib/src/task_hash.rs
Fixes https://github.com/vercel/turbo/issues/8553
User confirmed that adding `SystemRoot` to pass through fixed his issue: https://github.com/vercel/turbo/issues/8553#issuecomment-2194773860
=> fix: add more windows vars to default pass through env

crates/turborepo-lib/src/task_hash.rs
From https://github.com/microsoft/vscode-js-debug/blob/5b0f41dbe845d693a541c1fae30cec04c878216f/src/targets/node/nodeLauncherBase.ts#L320
=> Add VSCode's debugger variables to default passthroughs.

Cargo.lock, Cargo.toml, crates/turbopack-core/src/environment.rs, crates/turbopack-ecmascript-plugins/src/transform/relay.rs, crates/turbopack-ecmascript/src/parse.rs, crates/turbopack-swc-ast-explorer/src/main.rs, crates/turbopack-tests/tests/snapshot/emotion/emotion/output/crates_turbopack-tests_tests_snapshot_b36339._.js
Reverts vercel/turbo#8646
I failed to make next.js CI pass, so I'm creating this PR to unblock other team members updating turbopack
=> Revert "Update `swc_core` to `v0.96.5`"

crates/turborepo-lib/src/framework.rs
Updates the environment variables prefix for SvelteKit framework inference to match SvelteKit documentation: https://learn.svelte.dev/tutorial/env-static-public
Closes #8684
See #8684 for issue reproduction.
=> update env_wildcards for SvelteKit

crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/vc/mod.rs, crates/turbo-tasks/src/vc/resolved.rs
We want a way to more strongly guarantee that a `Vc` is resolved for the sake of "local" tasks.
This introduces it in a low-risk way with zero breaking changes. Eventually, we'd want to eliminate `.resolve()` or make `.resolve()` return `ResolvedVc` instead of using a separate `.to_resolved()` method.
Some rough notes about why here: https://www.notion.so/vercel/Resolved-Vcs-Vc-Lifetimes-Local-Vcs-and-Vc-Refcounts-49d666d3f9594017b5b312b87ddc5bff
Tested as a part of #8678
=> Create a minimum viable `ResolvedVc` type

crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/trace.rs, crates/turbo-tasks/src/vc/mod.rs, crates/turbo-tasks/src/vc/resolved.rs
This trait will provide a best-effort indication that a type is safe to return from a local task function.
This PR also makes some improvements to the `TraceRawVcs` impls that I noticed as opportunities while working on `ResolvedValue`.
https://www.notion.so/vercel/Resolved-Vcs-Vc-Lifetimes-Local-Vcs-and-Vc-Refcounts-49d666d3f9594017b5b312b87ddc5bff
Tested as part of #8678
=> Add a minimum viable ResolvedValue marker trait

crates/turborepo-lib/src/run/graph_visualizer.rs, crates/turborepo-ui/src/tui/table.rs
The unicode codepoint (✔) we used for a checkmark is not monospace on some platforms (i.e. linux).
This PR updates that to use the [characters matching Next.JS](https://github.com/vercel/next.js/blob/1a04d94aaec943d3cce93487fea3b8c8f8898f31/packages/next/src/build/output/log.ts) (and many other CLI tools before it).  Prior to this PR, this resulted in the checkmark overflowing its boundary into the border.
| BEFORE | AFTER |
| - | - |
| ![image](https://github.com/vercel/turbo/assets/15232461/92e18df7-8ba9-4a31-9d13-59d183861e25) | ![image](https://github.com/vercel/turbo/assets/15232461/223aab8b-0efd-49f7-85b8-9348e5a3b00a) |
```sh
cargo tr-build
./target/debug/turbo test --filter "./packages/*" --continue --force
```
=> fix constant width for checkmark

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/run/cache.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/table.rs, crates/turborepo-ui/src/tui/term_output.rs
This hooks up the `--output-logs` flag  and `outputLogs` in `turbo.json` to the logic that persists task output.
Previously these values were not respected and task output was always printed.
`new-only` should only print cache status on a cache hit, but everything on a miss.
```
[0 olszewski@chriss-mbp] /tmp/tui-output-logs $ turbo_dev --skip-infer build --output-logs=new-only --no-daemon                 12:46:14 [2/570]
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web                                                          
• Running build in 5 packages                                                                                                                   
┌ web#build > cache miss, executing e45fd0a9bad40e92 
│ 
│ …
```
=> fix(ui): respect `--output-logs` and `outputLogs` for persisting logs after TUI exits

crates/turborepo-lib/src/run/mod.rs
Previously we would crash if a user provided a filter that matched zero tasks. We should avoid starting the UI at all in this situation.
Before
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev build --filter='./packages/'
Oops! Turbo has crashed.
A report has been written to /var/folders/3m/rxkycvgs5jgfvs0k9xcgp6km0000gn/T/report-5f29ea16-7ad7-428f-ac6a-28607b4eb04a.toml
Please open an issue at https://github.com/vercel/turbo/issues/new/choose and include this file
No tasks were executed as part of this run.
Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
Time:
402ms
Run: https://vercel.com/teams/vercel/repos/turbo-monorepo/runs/space_run_xgkHsGl7exeeqKI3RfLZq2iK
Oops! Turbo has crashed.
A report has been written to …
```
=> fix(ui): only start ui if there are tasks to run

crates/turbo-tasks/src/rcstr.rs, crates/turbopack-ecmascript/src/parse.rs
This removes the weakref from each `Arc`, which we weren't using, saving 64 bits per unique `RcStr`.
https://docs.rs/triomphe/latest/triomphe/struct.Arc.html
The difference in memory is too small to easily measure with heaptrack, but it should be a small win regardless, and it's a drop-in replacement that doesn't make the code any more complicated.
Built using
```
cargo build --release -p next-build-test
```
Ran heaptrack on a single page (`/sink`) in `shadcn/ui` with:
```
cd ~/ui/apps/www
RUST_LOG=next_build_test=info heaptrack ~/nextpack/target/release/next-build-test run sequential 1 1 '/sink'
```
And analyzed the results with
```
heaptrack --analyze /home/bgw.linux/ui/apps/www/heaptrack.next-build-test.3066837.zst | tail -100
```
```
total runtime: 135.14s.
calls to allocation …
```
=> Switch RcStr from std::sync::Arc to triomphe::Arc

crates/turbopack-ecmascript/src/references/esm/binding.rs, crates/turbopack-ecmascript/src/references/mod.rs
Merge multiple `EsmBinding` into single `CodeGeneratable`
This is a pure optimization, so if the behavior is same it's all good.
Closes PACK-3147
=> perf: Merge multiple `EsmBinding`

docs/repo-docs/crafting-your-repository/configuring-tasks.mdx, docs/repo-docs/guides/tools/prisma.mdx
While reading the "crafting-your-repository/configuring-tasks" page, I noticed that one link was broken, so I examined the markdown written in `[text](#link)` format.
In addition, the `Interacting with tasks` item on the "crafting-your-repository/developing-applications" page also appears to have a broken link, but I left it as is because I didn't know where to send it to.
=> fix(docs): fix broken link

examples/basic/apps/docs/tsconfig.json, examples/basic/apps/web/tsconfig.json
Change next.config extension in `tsconfig.json` from `next.config.js` to `next.config.mjs` because the file actually is `next.config.mjs`
=> fix(examples): correct next.config extension in tsconfig

packages/turbo-telemetry/package.json, packages/turbo-telemetry/src/client.ts, packages/turbo-telemetry/src/config.ts, packages/turbo-test-utils/package.json, packages/turbo-test-utils/src/useFixtures.ts, pnpm-lock.yaml
I have replaced in the packages `packages/turbo-telemetry` and `packages/turbo-test-utils` the `uuid` dependency with native code.
This is recommended by the `uuid` library itself that to do a uuidv4 use crypto.randomUUID().
You can see it at: [here](https://www.npmjs.com/package/uuid)
=> Replace UUID to native

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
This PR adds the `--ui` flag to the CLI, where the options are `stream` or `tui`.
1. run with the `--ui` flag with no options to see the error text (describing the available options)
1. run `--help` and see this flag listed as an option
1. run with `--ui stream` to force the stream UI
1. run with `--ui tui` to force TUI
=> adds CLI flag for controlling tui/stream

.github/actions/setup-turborepo-environment/action.yml
Playwright is only used on the Turbopack side, so we can skip downloading its browsers when we're about to run Turborepo's CI.
CI
=> chore(ci): Skip downloading Playwright browsers in Turborepo CI.

.cargo/config.toml, Cargo.lock, Cargo.toml, crates/turbopack-core/src/environment.rs, crates/turbopack-ecmascript-plugins/src/transform/modularize_imports.rs, crates/turbopack-ecmascript-plugins/src/transform/relay.rs, crates/turbopack-ecmascript/src/parse.rs, crates/turbopack-swc-ast-explorer/src/main.rs, crates/turbopack-tests/tests/snapshot/emotion/emotion/output/crates_turbopack-tests_tests_snapshot_b36339._.js
Update swc crates
See [next.js counterpart](https://github.com/vercel/next.js/pull/67378)
- Closes https://github.com/vercel/next.js/issues/64890
- Closes https://github.com/vercel/next.js/issues/63104
=> build: Update `swc_core` to `v0.96.9`

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/inference.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_manager/bun.rs, crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-repository/src/package_manager/npm.rs, crates/turborepo-repository/src/package_manager/pnpm.rs, crates/turborepo-repository/src/package_manager/yarn.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Give users the ability to opt out of the required package manager if they feel strongly. 
This is still highly discouraged as this prevents proper usage of daemon package watching and leaves us dependent on system configuration to infer the correct package manager.
Reviewer notes: Each commit can be reviewed on it's own. The second commit just adds back code deleted in https://github.com/vercel/turbo/pull/8017
Added unit tests where applicable for configuration.
Quick manual verification of the config options:
```
[0 olszewski@chriss-mbp] /tmp/no-pm $ turbo_dev build                                                                
WARNING  No locally installed `turbo` found. Using version: 2.0.7-canary.0.
× missing packageManager field in package.json
[1 olszewski@chriss-mbp] /tmp/no-pm $ …
```
=> feat: allow opting out of required package manager

docs/repo-docs/crafting-your-repository/configuring-tasks.mdx
Uses the exact task name that is described in the `turbo.json` file. This confused me at first, I thought the `:root` was a custom syntax for defining where lint would be ran.
=> docs: Make root task more clear

docs/pack-docs/features/css.mdx
This PR removes "LESS" from the first section title in the documentation for clarity and consistency.
👀
=> Docs: Remove LESS from the first section title in documentation

crates/turbo-tasks-memory/src/output.rs, crates/turbopack-core/src/source_map/mod.rs, crates/turbopack-css/src/process.rs
* Check for equal Vc on returning a value
* Avoid PartialEq checks for values that are never equal
=> fix equal checks for cells and output

crates/turbo-tasks-memory/src/aggregation/mod.rs, crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks-memory/src/gc.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/task.rs
Inactive tasks can be completely unloaded. This disconnects them from the graph and frees nearly all memory (except for the TaskId mapping).
When running GC for a task we check if it's inactive and unload it when it is.
But we also need to enqueue a task for GC again when it becomes inactive. So we maintain a queue of potentially inactive tasks and walk the children during GC.
=> add unloading of tasks to GC

crates/turbo-tasks-memory/src/task.rs
We need to move up the check so it prevents unloading tasks with state.
=> fix unloading stateful check

crates/turborepo-api-client/src/lib.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/run/builder.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Changed `Opts` to be derived from more than just `RunArgs` and `ExecutionArgs`. This means that `Opts` contains the fully resolved config, which gets rid of some messy mutable logic in `RunBuilder` and creates a single source of truth.
Existing tests cover this pretty well.
=> refactor(turborepo): derive `Opts` from `Config`

crates/turbo-tasks/src/capture_future.rs, crates/turbo-tasks/src/manager.rs
Appears to be unused.
```
cargo check
cargo check --tests
```
=> Remove unused instant return value from `CaptureFuture`

Cargo.lock, Cargo.toml, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/memory_backend_with_pg.rs, crates/turbo-tasks/src/id.rs, crates/turbo-tasks/src/id_factory.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/registry.rs, crates/turbo-tasks/src/util.rs
The real goal here was to extend `IdFactory<T>` to work with 64-bit ids, which I'll need soon for globally unique (and non-reusable) "execution ids" (#8771) to support the safety requirements of local uncached Vcs.
I got a little carried away and essentially rewrote this:
- (Debatable if this is an improvement or not) ID generation re-use requires an almost-but-not-entirely-free check of the concurrent queue, so it is now opt-in using the `IdFactoryWithReuse`.
- ID generation is always performed with an AtomicU64 (which shouldn't really be any more or less expensive than AtomicU32 on 64 bit architectures).
- u32 overflow detection is performed by using a `TryFrom` conversion from a NonZeroU64. Previously we could only detect and panic on the first id generated after overflow. Now we …
=> Rewrite IdFactory and IdFactoryWithReuse

crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/id.rs
The plan for task-local Vcs is to extend the `RawVc` type into:
```
enum RawVc {
TaskOutput(TaskId),
TaskCell(TaskId, CellId),
LocalCell(ExecutionId, LocalCellId),  // new variant!
}
```
Where `ExecutionId` is a globally unique value representing the current task execution. That will be used with runtime safety checks to ensure that a given `LocalCellId` (which is an index into a task-local arena/vec) is valid upon read.
https://www.notion.so/vercel/Resolved-Vcs-Vc-Lifetimes-Local-Vcs-and-Vc-Refcounts-49d666d3f9594017b5b312b87ddc5bff?pvs=4
This PR extends the `define_id` macro to support arbitrary integer types, and uses that to define `ExecutionId`.
```
cargo nextest r -p turbo-tasks -p turbo-tasks-memory
```
=> Add u64 ExecutionId type

crates/turbo-tasks-macros/src/func.rs, crates/turbo-tasks-macros/src/function_macro.rs, crates/turbo-tasks-macros/src/lib.rs, crates/turbo-tasks-macros/src/value_impl_macro.rs, crates/turbo-tasks-macros/src/value_trait_macro.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/tests/call_types.rs, crates/turbo-tasks-testing/src/lib.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/lib.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/native_function.rs, crates/turbo-tasks/src/raw_vc.rs, crates/turbo-tasks/src/task/concrete_task_input.rs, crates/turbo-tasks/src/task/function.rs, crates/turbo-tasks/src/task/mod.rs, crates/turbo-tasks/src/trait_helpers.rs, crates/turbo-tasks/src/value_type.rs
Make this argument in turbo-tasks function calls explicit
=> turbo-tasks this calls

crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks/src/manager.rs
Collectibles are removed in `execution_completed` and that might add some tasks to the task local of tasks_to_notify. We need to make sure to notify these tasks otherwise changes get lost.
=> notify tasks when collectibles change

crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/tests/dirty_in_progress.rs
This saves some memory and streamlines the behavior.
It also lazily removes collectibles, children and dependencies even when entering the previous InProgressDirty (now InProgress stale) state.
=> merge InProgressDirty into InProgress

.github/workflows/turborepo-test.yml, crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/mod.rs, turborepo-tests/integration/tests/no-args.t
Instead of showing a generic error when a user calls `turbo run` with no tasks, we show the potential tasks along with the packages where they're defined. We cut off this list at 80 characters to prevent wrapping. Also obeys the filter flag.
Added tests in `no-args.t`
=> feat(turborepo): give potential tasks on empty `turbo run`

.github/workflows/test-js-packages.yml
Testing in https://github.com/vercel/turbo/pull/8788
=> chore(ci): JS tests don't need to setup rust and capnproto

crates/turbo-tasks-fs/src/watcher.rs
Sometimes file creation is reported as ModifyKind::Data on macOS. We need to account for that... FS weirdness...
=> fix watcher bug with file creation

crates/turborepo-lib/src/task_hash.rs
This is required so frameworks like svelte can auto detect their CI environment without always needing to include it in your turbo.json
=> feat(turbo): add VERCEL to pass through

crates/turbopack-core/src/diagnostics/mod.rs, crates/turbopack-core/src/issue/mod.rs
impl Ord for Diagnostics and Issue so they are sorted correctly
Collectibles are unordered by default and need to be ordered correctly to avoid over invalidation
=> impl Ord for Diagnostics and Issue so they are sorted correctly

crates/turbo-tasks/src/read_ref.rs, crates/turbo-tasks/src/task/function.rs, crates/turbo-tasks/src/vc/cast.rs, crates/turbo-tasks/src/vc/cell_mode.rs
IMO, many of these types are hard to read:
- Use a `VcReadTarget` type alias in `read_ref` to reduce the amount of syntax needed.
- Replace a few uses of `<<T as VcValueType>::Read as VcRead<T>>` with `<T::Read as VcRead<T>>` in places where `T` is already unambiguously `VcValueType`.
- Remove an unnecessary turbofish for an inferred type.
```
cargo check
cargo nextest r -p turbo-tasks -p turbo-tasks-memory
```
=> Simplify some of the syntax used with VcRead<T>

crates/turbopack-ecmascript/src/analyzer/builtin.rs, crates/turbopack-tests/tests/execution/turbopack/dynamic-requests/basic/input/index.js
Adds support for `String.prototype.concat` which `dayjs` uses in an `import()` pattern.
Closes PACK-3118
Fixes https://github.com/vercel/next.js/issues/66826
=> feat(turbopack): support analysing string concatenation

crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-ecmascript/src/parse.rs, crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs, crates/turbopack-ecmascript/src/side_effect_optimization/locals/module.rs, crates/turbopack-ecmascript/src/tree_shake/asset.rs, crates/turbopack-mdx/src/lib.rs
change from failsafe_analyse to failsafe_parse as ParseResult is flat and can be snapshot easily
failsafe_analyze didn't work correctly as it stores nested Vcs in State which breaks GC and dropping of excessive cells since these Vcs point to stale cells that no longer exist
=> change from failsafe_analyse to failsafe_parse

.github/actions/setup-rust/action.yml, .github/workflows/bench-turbotrace-against-node-nft.yml, .github/workflows/test-turbopack-rust-bench-test.yml, .github/workflows/turbopack-test.yml
In some cases we can time out in CI because the cargo install action will fetch binaries from github.
Run CI 100 times and see our rust setup step hang less :P
=> make sure that all the taiki-e/install-action calls use our env

crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/task.rs, crates/turbo-tasks-memory/tests/emptied_cells.rs
Refactor cell reading to handle removed cells
handle recomputation of cells on read
use start event instead of done event when waiting for task reading
That's how the Cell state changes:
=> Refactor cell reading to handle removed cells

docs/repo-docs/reference/link.mdx, docs/repo-docs/reference/logout.mdx
In Turborepo's [reference page](https://turbo.build/repo/docs/reference/link) for the `link` command, the `logout` command flags are listed.
I just moved those flags to the right page.
* Check the updated docs
=> docs(link): wrong mention of the `logout` command in the `link` flags

crates/turbo-tasks-fetch/src/lib.rs, crates/turbo-tasks-fs/src/attach.rs, crates/turbo-tasks-fs/src/lib.rs, crates/turbo-tasks-fs/src/read_glob.rs, crates/turbo-tasks-macros/src/function_macro.rs
=> add tags to turbo tasks

crates/turbo-tasks-memory/src/task.rs
This makes the enum smaller for the Done state, which is the common one
=> box Scheduled task state to save memory

crates/turborepo-repository/src/inference.rs
Add unit test for broken behavior described in #8599
This does not fix the issue, but will start failing if our behavior changes.
Unit test passes
=> chore(infer): add test for current behavior

crates/turbo-tasks-memory/src/cell.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-testing/src/lib.rs, crates/turbo-tasks/src/backend.rs, crates/turbo-tasks/src/manager.rs, crates/turbo-tasks/src/persisted_graph.rs, crates/turbo-tasks/src/raw_vc.rs, crates/turbo-tasks/src/read_ref.rs, crates/turbo-tasks/src/task/shared_reference.rs, crates/turbo-tasks/src/task/task_input.rs, crates/turbo-tasks/src/trait_ref.rs, crates/turbo-tasks/src/value.rs, crates/turbo-tasks/src/vc/cast.rs
This change reworks the structure to drop an option such that data which is colocated with its type information doesn't need to store it twice.
Existing tests should suffice.
=> reduce memory and consolidate shared vs transient cells

crates/turbo-tasks/src/completion.rs
It's probably not want to want. You want ptr_eq instead.
=> avoid implementing Eq on Completion

crates/turbo-tasks-memory/src/gc.rs, crates/turbo-tasks-memory/src/memory_backend.rs, crates/turbo-tasks-memory/src/task.rs
When GC is inefficient and can't collect enough memory, increase the provided memory limit automatically.
We rather want to consume more memory than requested then crashing or hanging the compilation due to GC.
=> GC auto increase memory limit on inefficient GC

crates/turborepo-lib/src/task_graph/visitor.rs
Fixes #8281 
With this PR we now close `stdin` for any task that is not marked as `"interactive": true` or `"persistent": true`.
**Explanation**
The `del-cli dbschema/edgeql-js dbschema/interfaces.*` part of `dram:codegen` task waits for user input if `stdin` isn't closed even if it isn't hooked up to a TTY:
```
dram:codegen: Checking the generated query builder into version control
dram:codegen: is not recommended. Would you like to create a .gitignore file to ignore
dram:codegen: the query builder directory? [y/n] (leave blank for "y")
```
This caused the task to never exit since there was no user to answer the prompt.
The prompt was never surfaced as GH Action runs have logs grouped together by default and they are not flushed if a run is interrupted before it finishes.
**How We Got …
=> fix: close stdin for non-interactive tasks

crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/lib.rs
Catch 403 HTTP requests and understand them as meaning this token doesn't have cache access. This will cause the token to be ignored and the login flow will continue.
Inspecting result of sending cache status request with bad token. Result is a `ReqwestError` with a 403 status code, not an `UnknownStatus`.
=> chore(auth): catch forbidden cache access error

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-telemetry/src/events/command.rs
The turbo version shuold be enough in telemetry now to know what people are using, since both paths aren't supported in very many versions.
=> chore(telemetry): remove unused codepath field

packages/turbo-types/src/types/config.ts
Update schema with config added in https://github.com/vercel/turbo/pull/8738
👀 and `turbo check-types`
=> chore(schema): update schema with dangerouslyDisablePackageManagerCheck

crates/turbopack-ecmascript/src/lib.rs, crates/turbopack-tests/tests/execution/turbopack/renaming/eval/input/index.js
=> fix: Use `hygiene_with_config` instead of `hygiene`

crates/turbo-tasks-fs/src/read_glob.rs
* fix dot files handling while reading glob fix symlink handling while reading glob
* fix symlink handling while reading glob
=> fix symlinks and dotfiles while reading glob

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-telemetry/src/events/command.rs, crates/turborepo-ui/src/tui/table.rs
The task status was getting cut off because we were clamping an incorrect length for the table instructions. Moved the instructions for the table into a constant so we can use that for the clamp call.
Try it and see.
=> fix(turborepo): task table width bug

crates/turbo-tasks-memory/tests/all_in_one.rs, crates/turbo-tasks-memory/tests/generics.rs
- Move the tests out of `all_in_one` so that we can see exactly which parts are failing more easily.
- Add a few more tests. **The newly added `test_read_ref_round_trip` fails** (and is ignored), indicating a bug in the generics implementation!!! This is fixed in #8845.
The theory is that Vcs are supposed to be stored as `<<T as VcValueType>::Read as VcRead<T>>::Repr`. However, it looks like due to an oversight, `ReadRef::cell` is trying to store the value as `T`.
The plan (as of yesterday) is to remove support for generics, but I'd feel more confident if I can fix the casting issues in my local Vc PRs before I do that.
These tests should help me understand what's happening and debug things.
```
cargo nextest r -p turbo-tasks -p turbo-tasks-memory
```
=> Add/move tests for Vc generics

crates/turbo-tasks-memory/tests/generics.rs, crates/turbo-tasks/src/read_ref.rs, crates/turbo-tasks/src/triomphe_utils.rs
Fixes the test case introduced in #8843.
The theory is that Vcs are supposed to be stored as `<<T as VcValueType>::Read as VcRead<T>>::Repr`. However, it looks like due to an oversight, `ReadRef::cell` is trying to store the value as `T`.
This introduces a way to perform 
```
cargo nextest r -p turbo-tasks -p turbo-tasks-memory
```
=> Fix `ReadRef<T>::cell` when `T` != `T::Read::Repr`

crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/table.rs
Added a cache hit symbol, `⊙` in purple. Also italicized the task name for cache hits.
=> feat(turborepo): added specific symbol for cache hit

Cargo.lock, crates/turborepo-ui/Cargo.toml, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/clipboard.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/mod.rs, crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/term_output.rs, crates/turborepo-vt100/src/cell.rs, crates/turborepo-vt100/src/grid.rs, crates/turborepo-vt100/src/row.rs, crates/turborepo-vt100/src/screen.rs, crates/turborepo-vt100/tests/select.rs
Adds mouse selection and copying in the terminal pane. When selecting text, pressing `c` will copy the current text. Users are allowed to interact with tasks while having a selection, but `c` will still be intercepted to copy the selection.
Future work:
- Double click should select the entire line
Reviewer Guide:
- Review each commit on it's own
- We implement selection at the virtual terminal level, this allows us to take into account the current scroll state and translate mouse events into "absolute" position.
- I did a bad thing and fixed some bugs in this PR. They have their own commits, but easier to do here as they would cause merge conflicts if done independently.
Added unit tests for the vt100 level copying. Testing this in actual terminals is the best way to test mouse inputs …
=> feat(tui): terminal pane mouse copying

crates/turbopack-ecmascript/src/references/esm/export.rs, crates/turbopack-ecmascript/src/tree_shake/asset.rs, crates/turbopack-ecmascript/src/tree_shake/mod.rs, crates/turbopack-tests/tests/snapshot/basic-tree-shake/dynamic-import/output/79fb1_turbopack-tests_tests_snapshot_basic-tree-shake_dynamic-import_input_lib_f28c6f.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/export-named/output/crates_turbopack-tests_tests_snapshot_basic-tree-shake_export-named_input_35ea42._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/export-namespace/output/79fb1_turbopack-tests_tests_snapshot_basic-tree-shake_export-namespace_input_c0eca6._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/import-named-all/output/79fb1_turbopack-tests_tests_snapshot_basic-tree-shake_import-named-all_input_71b07f._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/import-named/output/crates_turbopack-tests_tests_snapshot_basic-tree-shake_import-named_input_ed0d99._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/import-namespace/output/79fb1_turbopack-tests_tests_snapshot_basic-tree-shake_import-namespace_input_351ad1._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/import-side-effect/output/79fb1_turbopack-tests_tests_snapshot_basic-tree-shake_import-side-effect_input_cdc49f._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/require-side-effect/output/a587c_tests_snapshot_basic-tree-shake_require-side-effect_input_6b5862._.js, crates/turbopack-tests/tests/snapshot/basic-tree-shake/tree-shake-test-1/output/a587c_tests_snapshot_basic-tree-shake_tree-shake-test-1_input_index_87c735.js
Fix server action and rename the injected variable.
The previous code fails if the name of the top-level variable is `v`. This was not a problem for almost all modules, but some packages like [`@firebase/webchannel-wrapper`](https://unpkg.com/@firebase/webchannel-wrapper@0.2.41/dist/index.esm.js) is published after mangling, so it can be a problem
See https://github.com/vercel/next.js/pull/66689
=> fix: Fix tree shaking even more

crates/turbopack-ecmascript/src/references/mod.rs, crates/turbopack-ecmascript/tests/analyzer/graph/conditional-import/graph-effects.snapshot, crates/turbopack-ecmascript/tests/analyzer/graph/conditional-import/input.js, crates/turbopack-ecmascript/tests/analyzer/graph/conditional-import/resolved-effects.snapshot, crates/turbopack-tests/tests/execution/turbopack/side-effects-optimization/comptime/input/index.js, crates/turbopack-tests/tests/execution/turbopack/side-effects-optimization/comptime/input/node_modules/package/dep.js, crates/turbopack-tests/tests/execution/turbopack/side-effects-optimization/comptime/input/node_modules/package/dep2.js, crates/turbopack-tests/tests/execution/turbopack/side-effects-optimization/comptime/input/node_modules/package/package.json, crates/turbopack-tests/tests/execution/turbopack/side-effects-optimization/comptime/options.json, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/comptime/input/index.js, crates/turbopack-tests/tests/execution/turbopack/tree-shaking/comptime/options.json
skips import to modules that are side effect free and have no exports referenced
This allows to e. g. skip the `package` import completely in the following code:
``` js
import { something } from "package"; // package is marked as side effect free
if (falsy) {
something();
}
```
This could happen e. g. with code like `if(process.env.NODE_ENV === "production")`
=> only add import references when they are used

crates/turbopack-mdx/src/lib.rs, crates/turbopack/src/lib.rs, crates/turbopack/src/module_options/mod.rs, crates/turbopack/src/module_options/module_rule.rs
Remove `ModuleType::Mdx` and instead handle mdx files using
```rust
ModuleRuleEffect::ModuleType(ModuleType::Typescript {
transforms: ts_app_transforms,
tsx: true,
analyze_types: enable_types,
options: ecmascript_options_vc,
}),
ModuleRuleEffect::SourceTransforms(Vc::cell(vec![Vc::upcast(
MdxTransform::new(mdx_transform_options),
)])),
```
I ran these Next.js tests, which appear to be all mdx related tests there are
```
mdx with-mdx-rs
app directory
✓ should work in initial html (1262 ms)
✓ should work using browser (1460 ms)
✓ should work in initial html with mdx import (145 ms)
✓ should work using browser with mdx import (1179 ms)
✓ should allow overriding components (1163 ms)
✓ should allow importing client components (26 ms)
✓ should work with next/image (424 ms)
pages directory
✓ …
```
=> Replace MDX ModuleType with MDX SourceTransform

docs/repo-docs/crafting-your-repository/using-environment-variables.mdx
=> (docs): Callout for using dotenv.

crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/config.t
This PR adds support and testing for a `TURBO_DAEMON` environment variable, as well as a `{ daemon: boolean }` field to the `turbo.json` file.  This change allows us to remove `daemon` from `RunOpts`, as well.
You can run `turbo daemon status` to see the status of the daemon after each run (and also `turbo daemon stop` to kill it).
1. run with `--no-daemon`
1. run with `TURBO_DAEMON=false`
1. run with `{"daemon":false}` in your turbo.json
1. run with `--daemon`
1. run with `TURBO_DAEMON=true`
1. run with `{"daemon":true}` in your turbo.json
=> adds daemon flag for env var and turbo.json

crates/turborepo-lib/src/process/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs
I forgot that ConPTY behaves differently than Linux-style psuedoterminals. If `stdin` is closed on a process hooked up to a ConPTY, then the process will immediately end.
Cut a canary and test it on a Windows machine.
=> fix(windows): keep stdin open for conpty processes

.github/workflows/bench-turbopack.yml
Trying to fix the workflow by checking if the directory exists, a team member should check.
=> fix(ci): Trying to fix `benchmark-turbopack` workflow

crates/turborepo-lib/src/process/child.rs
Copying and pasting from #7109:
Disable ECHOCTL for the pseudo terminal that we start:
ECHOCTL
(not in POSIX) If ECHO is also set, terminal special
characters other than TAB, NL, START, and STOP are echoed
as ^X, where X is the character with ASCII code 0x40
greater than the special character. For example,
character 0x08 (BS) is echoed as ^H.
This will remove the ^D that gets generated from the EOT when using a PTY. Using PTY still does generate a leading \n as EOT is only respected if it immediately follows a newline. portable_pty tries to prevent failed EOT by emitting a \nEOT on drop in case end users didn't end the last write with a newline.
Verify that `^D` no longer appears in output:
```
[0 olszewski@chriss-mbp] /tmp/echoctl-test $ TURBO_UI=0 turbo_dev --skip-infer build --force …
```
=> fix(pty): disable echoctl for child processes

crates/turborepo-lib/src/global_deps_package_change_mapper.rs, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-lib/src/run/scope/change_detector.rs, crates/turborepo-repository/src/change_mapper/mod.rs, crates/turborepo-repository/src/change_mapper/package.rs, packages/turbo-repository/rust/src/lib.rs
The ultimate goal for me is to figure out why I'm seeing _all_ packages invalidated when running with `--filter='[sha]'` . In a lot of cases, we return a sigil for `PackageChanges::All`. I'm not sure how to bubble this up with higher fidelity information in a good way, so this PR settles for a more granular "reason" why all packages changed and includes it in debug logging. This should help a little bit with debugging.
=> feat(turborepo): log reason why all packages were considered changed

crates/turborepo-lib/src/task_graph/visitor.rs, docs/repo-docs/reference/system-environment-variables.mdx
Tools being used inside Turborepo tasks may want to know if they are being ran in our multiplexer, similar to the way other terminal tooling set environment variables that other programs can read (e.g. `ZSH`,`TMUX`, `ALACRITTY_WINDOW_ID`).
In this PR, we're exposing a `TURBO_IS_TUI` variable for this purpose.
Using the `with-shell-commands` example, I edited one of the `build` scripts to echo the value.
With TUI:
```
TURBO_UI devturbo build --force --skip-infer
<omitted for brevity>
┌ pkg-b#build > cache bypass, force executing 33b029c222753bd2
│
│
│ > pkg-b@ prebuild /Users/anthonyshew/projects/debugs/with-shell-commands/packages/pkg-b
│ > echo "Executing pre-build step..."
│
│ Executing pre-build step...
│
│ > pkg-b@ build /Users/anthonyshew/projects/debugs/with-shell-commands/packages/p …
```
=> feat(tui): Set TURBO_IS_TUI environment variable when using TUI.

docs/repo-docs/reference/run.mdx
Adding a bit of nuance to the advanced filtering patterns documentation. It's a union - but its a weird union.
Addresses #8552
=> docs(filters): Clarity for advanced patterns.

Cargo.lock, Cargo.toml
This patch was used by Turbopack so we can get rid of it in our `Cargo.toml` and no longer get a warning about it.
`cargo build -p turbo` no longer produces: `warning: Patch `pathfinder_simd v0.5.3 (https://github.com/vercel/pathfinder?branch=rm-stdarch_arm_crc32#ddc0696d)` was not used in the crate graph.`
=> chore: remove unused patch

.vscode/settings.json, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/config.t
1. (temporarily) update `@turbo/gen`'s `check-types` command to `    "check-types": "env | sort | tee /dev/tty | wc -l"`
1. execute `turbo run check-types --filter @turbo/gen` and observe the number
1. add `  "envMode": "loose",` to the root `turbo.json`
1. run the command above again, observer the number is larger, indicating more environment variables have been included.
=> add envMode to `turbo.json`

README.md
This Pull Request improves the visual appearance of the badges in the README.md file by removing unnecessary line breaks between the badge images, eliminating the unwanted blue link lines that previously appeared and resulting in a cleaner and more cohesive look.
Removed unnecessary line breaks between badge images in the README.md file to eliminate the unwanted blue link lines and improve the overall visual presentation.
Previously, the badges were displayed with line breaks between them, causing blue link lines to appear, which disrupted the clean look of the badges. By removing these line breaks, the badges now appear without the blue link lines, providing a more cohesive and visually appealing README.
Removed the line breaks between badge images in the README.md file.
x-ref: [New …
=> chore(docs): improve visual appearance of badges in README.md

CONTRIBUTING.md
=> chore(turbo): simplify contributing

.github/ISSUE_TEMPLATE/0-turborepo-bug-report.yml
with turbopack being removed in #8906, we can also remove the owned-by label for bug reports.  also, with the merging of https://github.com/vercel/turbo/pull/8914 they won't really matter anymore anyway
=> removes owned-by from bug report template now that turbopack is gone

.prettierignore
with turbopack being removed in #8906, we can also remove mentions of turbopack crates in the prettierignore
=> removes prettierignore files related to turbopack

.vscode/settings.json
When you run integrations tests and there's an error it creates *.t.err files in the cram format.  With this file association added, now those files will be correctly associated and therefore get syntax highlighting and all that good stuff.
=> adds *.t.err to file associations

.vscode/settings.json
with turbopack being removed in https://github.com/vercel/turbo/pull/8906, we can also remove this from the vscode settings
=> removes turbopack search exception

.gitattributes
with turbopack being removed in https://github.com/vercel/turbo/pull/8906, we can also remove these gitattributes files
=> removes gitattributes for turbopack files

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/config.t, turborepo-tests/integration/tests/turbo-help.t, web-ui/next-env.d.ts
Right now we internally represent the `ui` config as a boolean. This isn't very extensible, so I refactored it to be an enum instead
=> refactor(turborepo): change the ui config to use an enum

Cargo.lock, crates/turborepo-api-client/Cargo.toml, crates/turborepo-ci/Cargo.toml, crates/turborepo-env/Cargo.toml, crates/turborepo-filewatch/Cargo.toml, crates/turborepo-globwalk/Cargo.toml, crates/turborepo-globwalk/src/lib.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-paths/Cargo.toml, crates/turborepo-paths/src/absolute_system_path.rs, crates/turborepo-pidlock/Cargo.toml, crates/turborepo-pidlock/src/lib.rs
Flushing some old branches.
Tempdir is deprecated. Long live tempfile. Also did the liberty of running udeps and sorting some dev deps out. Saving entire grams of CO2.
Existing tests cover. Split into two commits since tempdir is the majority here.
=> remove / move unused or test crates

crates/turborepo-lib/src/config.rs
https://github.com/vercel/turbo/pull/8919 accidentally disabled TUI usage when hooked up to a TTY
Verify that you can now use the TUI if hooked up to TTY:
https://github.com/user-attachments/assets/1ae1d7db-4714-4abe-a1e6-13b4e564d006
=> fix(tui): allow for TUI use when hooked up to tty

Cargo.lock, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-telemetry/Cargo.toml, crates/turborepo-telemetry/src/events/command.rs, crates/turborepo-telemetry/src/events/generic.rs, crates/turborepo-telemetry/src/events/mod.rs, crates/turborepo-telemetry/src/events/repo.rs, crates/turborepo-telemetry/src/events/task.rs
Reduce volume of telemetry logs
=> feat(telemetry): reduce data volume

docs/repo-docs/crafting-your-repository/creating-an-internal-package.mdx
Correct comma json syntax in sample code in document at [Creating an Internal Package > Add a package.json section](https://turbo.build/repo/docs/crafting-your-repository/creating-an-internal-package#add-a-packagejson)
=> docs: Correct json comma syntax in sample code 

docs/repo-docs/crafting-your-repository/developing-applications.mdx, docs/repo-docs/reference/watch.mdx
The `watch` docs weren't clear enough. Addressing that in this PR with better details.
=> (docs): Improve clarity for watch.

crates/turborepo/src/main.rs, turborepo-tests/integration/tests/bad-turbo-json.t, turborepo-tests/integration/tests/invalid-package-json.t
https://github.com/vercel/turborepo/pull/7169 changed error printing from `stderr` to `stdout`. This changes that behavior so we print errors to `stderr` once again. This provides a better experience if `turbo` is piped e.g. `turbo --dry=json build | jq .`
```
[0 olszewski@Chriss-MacBook-Pro] /Users/olszewski/code/test $ turbo -F '[commit]' ci-run-build-container | jq .
WARNING  No locally installed `turbo` found. Using version: 2.0.12-canary.0.
turbo 2.0.12-canary.0
jq: parse error: Invalid numeric literal at line 1, column 4
```
After
```
[5 olszewski@Chriss-MacBook-Pro] /Users/olszewski/code/test $ turbo_dev -F '[commit]' ci-run-build-container | jq .
WARNING  No locally installed `turbo` found. Using version: 2.0.12.
turbo 2.0.12
x Invalid package dependency graph: cyclic dependency …
```
=> fix: print application errors to stderr instead of stdout

crates/turborepo-repository/src/change_mapper/mod.rs, crates/turborepo-repository/src/package_graph/mod.rs
It can be confusing why a package is invalidates everything if it isn't a direct dependency of the root package. This PR adds a function for displaying paths between the root package and a workspace packages.
Check debug logs:
```
2024-08-09T11:37:14.913-0400 [DEBUG] turborepo_repository::change_mapper: packages/logger/index.ts changes root internal dependency: "@api/logger"
shortest path from root: Some("// -> @api/util-integrations -> @api/logger")
```
=> chore(change_mapper): add debug log explaining why package is root dep

.cargo/config.toml
The aliases don't work, as noted by the warning:
> warning: user-defined alias `test` is ignored, because it is shadowed by a built-in command
So I just removed them. Also removed the xtask one because only turbopack uses xtask
=> chore: remove aliases

.github/workflows/turborepo-test.yml
Speed up CI by combining the `lint` and `clippy` jobs, and removing `build_turborepo`. Also added sccache to the rust tests.
=> chore: speed up CI

crates/turborepo-repository/src/inference.rs
I noticed in the CI logs a warning that this was an unused function.  Looks like we just forgot the test annotation in https://github.com/vercel/turbo/pull/8825
Tests pass.
=> enables test_gh_8599 test

turbo.json
My understanding is that this is not needed anymore - so just cleaning it up on the basis of that assumption.
Reminder: there is some Go code left in `turborepo-lib/hash`, but from what I can tell that's entirely separate from this.
=> removes GOROOT from globalPassThroughEnv for local dev

packages/turbo-utils/src/examples.ts
This bug broke create-turbo when we renamed the repo. This bug is explained in the comments but the tl;dr is that downloading the repo works because the download URL automatically redirects from the old name to the new name. However the download is always put into a directory of the name {repoName}-{branch} where the repoName is the name of the repo at the time and NOT always the name used to download it.
=> fix(create-turbo): support renamed repositories

socket.yaml
This PR updates the configuration for [Socket](https://socket.dev/), our supply chain security tool. The change:
- Prevents Socket from commenting on PRs with dependency alerts.
- Stops Socket from showing dependency overviews within PRs
- Keeps Socket running in the background.
The intention is to reduce potential noise in PRs, while still giving us overall health and supply chain security insights behind the scenes.
To Review
=> Update Socket config

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/debouncer.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/mod.rs, crates/turborepo-ui/src/tui/size.rs, crates/turborepo-ui/src/tui/term_output.rs
Resize the layout including the pane on terminal resize events.
We completely sidestep `vt100`'s inability to properly handle resize events by storing a copy of task outputs and recreating the virtual terminal from scratch on a resize. A start at adding this functionality to vt100 can be found in [this commit](https://github.com/vercel/turbo/commit/6def8c819ab4d84a75afa068ace91bbd3e8eb9c9).
Generally speaking, this is inefficient, but there is a clear path forward if performance here becomes an issue.
Each commit can be reviewed individually.
Added a few basic unit tests. Manual testing works best to verify terminal looks like how we want it to look.
https://github.com/user-attachments/assets/661495d1-1a4a-4aa8-91de-cc0c2face05d
=> feat(tui): resize terminal pane

packages/turbo-types/src/types/config.ts
In making https://github.com/vercel/turborepo/pull/9011 I noticed that some (but not most) of the [@defaultValue](https://tsdoc.org/pages/tags/defaultvalue/) tags used the inline code blocks (added to all in 32f30d2b2446190f6512ffec83ea0138587c1539), and others were missing a @defaultValue altogether (which, we do have some booleans that default to true, so it's best to include them) (added in 1ff9ae7e453189726deeebd9fb0cb5a7685453f5). 
Make sure the defaults added in 1ff9ae7e453189726deeebd9fb0cb5a7685453f5 are correct.  Otherwise, you can hover over any of these types to see the codeblock used in the hover overlay.
=> makes @defaultValue usages consistent (and correct)

packages/turbo-utils/src/examples.ts
Don't use platform specific path separator when filtering the download from Github.
=> fix(create-turbo): correct path usage

packages/turbo-types/src/types/config.ts
This PR adds to the TypeScript types for [cacheDir](https://github.com/vercel/turborepo/pull/8947), [daemon](https://github.com/vercel/turborepo/pull/8728), and [envMode](https://github.com/vercel/turborepo/pull/8757), all recently added items to the `turbo.json`.
None, just ensure the values and documentation looks correct.  The links don't all exist yet, but are being added in a followup PR to the docs.
=> TypeScript types for `cacheDir`, `daemon`, and `envMode`

Cargo.toml
In latest version of tui-term, it breaks the usage of ui_term::widget::Cell without change the minor number of version, makes turborepo-lib impossible to be build as crate without modify.
This fix lock the tui-term version and solve the problem above.
=> fix: lock tui-term version to pass rust type check

crates/turborepo-lib/src/task_graph/visitor.rs
Related to https://github.com/vercel/turborepo/pull/9008/files
- color order is no longer tied to task execution order
- color is no longer tied to task hashes which change frequently
This should end up with more consistent colors between runs
=> feat: color no longer tied to task execution order

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/task.rs
Fixes https://github.com/vercel/turborepo/issues/9016
Crash was caused by two issues:
- Mistakenly calling `update_tasks` instead of `restart_tasks` when handling a restart event 🙃 . This meant if a package changed that did not matter (a package in scope, but that didn't have a task definited) we would "restart" no tasks, but this would end up clearing out the entire task list.
- The watch client can declare it is restarting a task that is not in the current list. This happens if a `build` script is added to a workspace `package.json` after `turbo watch build` is run.
Added unit tests that test we no longer crash when:
- updating task list to nothing (TUI cannot display this)
- restarting tasks that were not in original list
=> fix(tui): avoid panic on restarting tasks during watch

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/ls.rs, turborepo-tests/integration/tests/affected.t, turborepo-tests/integration/tests/command-ls.t
Support output format for `ls`
=> feat(ls): support output format

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/mod.rs, crates/turborepo-ui/src/tui/task.rs
As https://github.com/vercel/turborepo/issues/9016 displayed, panicking in the render thread leads to a very poor user experience. We should do our best effort to avoid this by using errors so we can make sure the `cleanup` code gets run.
This PR removes (almost) all `unwrap`s/`expect`s in favor of returning an `Err` which will cause us to exit `run_app_inner`.
Existing unit tests. 👀
=> chore(tui): remove unwraps from tui

Cargo.lock, Cargo.toml, crates/turborepo-cache/src/lib.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/daemon/default_timeout_layer.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/query.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-vercel-api-mock/src/lib.rs, turborepo-tests/integration/tests/affected.t, turborepo-tests/integration/tests/command-query.t
Adds a GraphQL query interface to turborepo via the `turbo query` command. If you pass it a query string, then it directly runs the query. If you pass it a file, it reads the file and runs the query. If you don't pass a query, then it opens up a server with GraphiQL (we can ITG this interface).
Added tests to `affected.t` and `command-query.t`
=> feat: implement a query interface for turborepo

docs/repo-docs/reference/configuration.mdx, docs/repo-docs/reference/run.mdx, packages/turbo-types/schemas/schema.json, packages/turbo-types/schemas/schema.v2.json, packages/turbo-types/src/types/config-v2.ts
This PR adds documentation for https://github.com/vercel/turborepo/pull/8947, https://github.com/vercel/turborepo/pull/8728, and https://github.com/vercel/turborepo/pull/8757, all recently added items to the turbo.json (and env vars).
View the preview deployment :point_down:
=> documentation for for `cacheDir`, `daemon`, and `envMode` (config values, and env vars)

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/mod.rs, crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/search.rs, crates/turborepo-ui/src/tui/task.rs, crates/turborepo-ui/src/tui/term_output.rs
This PR adds the ability to search though the task list by using `/` and scroll through the results with the arrow keys. 
A user can exit the search by pressing `Esc` or `Backspace` when there search bar is already empty to return the the selected task before the search. If they press `Enter` it will exit the search at selected result.
Searching is currently done via a naive substring search, but could be enhanced with a fuzzy matcher if desired.
Each commit can be reviewed on it's own.
Extensive unit tests for state changes.
https://github.com/user-attachments/assets/8cc06e76-e2c8-4639-9c2b-db0d8ae5c636
=> feat(tui): allow searching for tasks

crates/turborepo-lib/src/cli/mod.rs
We already would throw for `turbo ls`, but for some reason `clap` would accept `--filter` and `--affected` on `run`.
```
[0 olszewski@Chriss-MacBook-Pro] /Users/olszewski/code/vercel/turborepo $ turbo_dev ls --affected --filter='cli'                                     
WARNING  No locally installed `turbo` found. Using version: 2.0.15-canary.0.
ERROR  the argument '--affected' cannot be used with '--filter <FILTER>'
Usage: turbo ls --affected [PACKAGES]...
For more information, try '--help'.
[1 olszewski@Chriss-MacBook-Pro] /Users/olszewski/code/vercel/turborepo $ turbo_dev run build --affected --filter='!cli'
WARNING  No locally installed `turbo` found. Using version: 2.0.15-canary.0.
turbo 2.0.15-canary.0
• Packages in scope: 
• Running build in 0 packages
• Remote caching enabled
No …
```
=> fix(affected): prevent affected from being used with filter

crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/query.rs, crates/turborepo-lib/src/run/scope/change_detector.rs, crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lib/src/run/scope/target_selector.rs, crates/turborepo-scm/src/git.rs, crates/turborepo-scm/src/lib.rs, turborepo-tests/integration/tests/config.t
We use `main` as our default for base branch, but a lot of repos are likely using `master`, we should fall back to that if `main` isn't a valid ref.
see unit tests https://github.com/vercel/turborepo/pull/9045/files#diff-db1296fb6f1a06e197e7cd6cdf5979b738c6b56b7700b048ab3b00fd767f8aecR734-R746 for situations to test manually.
=> allow multiple fallbacks for --affected base branch

crates/turborepo-lib/src/config.rs, crates/turborepo-lib/src/run/scope/change_detector.rs
Users can set empty string env vars which will end up getting chosen over our defaults. Empty env vars can accidentally get set when using [`docker compose`](https://docs.docker.com/compose/environment-variables/set-environment-variables/#additional-information) if a pass through env is declared in the YAML, but the shell does not have the var defined. 
This means that `Some("")` will no longer be a valid value in for `from_ref`. This is already the case for `TargetSelector`s from `--filter`s: [source](https://github.com/vercel/turborepo/blob/main/crates/turborepo-lib/src/run/scope/target_selector.rs#L145)
This also allows us to remove the awkward comparison where we check if the scm base and skip calculating changes if it is `Some("")`, but do the calculation if it is `None`.
Added unit …
=> fix(affected): don't respect empty scm env vars

crates/turborepo-lib/src/cli/mod.rs
We've seen segfaults from running `turbo run` on [CI]()
We believe this is due to `process::exit` being called before some `Drop` implementations have been run. We make sure `Drop`s are run by returning the exit code instead of exiting.
Run in CI multiple times:
- [Run 1](https://github.com/vercel/turborepo/actions/runs/10562720469/job/29261407172?pr=9065)
- [Run 2](https://github.com/vercel/turborepo/actions/runs/10562720469/job/29262901217?pr=9065)
=> fix(cli): avoid use of process exit

crates/turborepo-ui/src/tui/app.rs
We were getting lint warnings from not using the result of some functions with in these tests.
`cargo test -p turborepo-ui ` should no longer produce build warnings.
=> chore(tui): fix lint warnings in tests

docs/repo-docs/reference/run.mdx
Add documentation for new `turbo run` behavior on the `run` reference.
I decided to not show the output as the syntax highlighting was odd
=> docs: document run displaying available tasks

Cargo.lock, Cargo.toml, crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
Fixes https://github.com/vercel/turborepo/issues/9080
Upgrade `clap` and completion generation to get https://github.com/clap-rs/clap/pull/5545
Also change the long flag name from `--[no-]daemon` to `--(no-)daemon` as `[]` are reserved chars for zsh autocompletes.
⚠️ This will break anyone who uses `--[no-]daemon` to enable the daemon.
`turbo_dev completion zsh > ~/.zsh/completions/_turbo` (or where ever your completions are stored)
Open a new shell and enter `turbo -- <TAB> <TAB>`
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo --
--__test-run                                 --no-daemon           --version                                                                                         
--experimental-space-id                      --pkg-inference-root …
```
=> fix(zsh): fix completion generation for zsh

examples/kitchen-sink/apps/admin/src/app/index.tsx, examples/kitchen-sink/apps/blog/app/routes/_index.tsx, examples/kitchen-sink/apps/storefront/src/app/page.tsx, examples/kitchen-sink/packages/ui/package.json, examples/kitchen-sink/packages/ui/src/index.tsx, examples/kitchen-sink/packages/ui/tsconfig.json, examples/kitchen-sink/packages/ui/tsup.config.ts, examples/kitchen-sink/packages/ui/turbo.json, examples/kitchen-sink/pnpm-lock.yaml, packages/turbo-types/tsconfig.json
The TypeScript strategy on this example wouldn't take you to source. It does now!
=> examples: Fix sourcemapping in kitchen-sink.

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs
https://github.com/vercel/turborepo/pull/8728 accidentally disconnected the `--no-daemon` and `--daemon` flags. The config was populated using `args.run_args` which is explicitly set to `None` for all `run` commands [here](https://github.com/vercel/turborepo/blob/main/crates/turborepo-lib/src/cli/mod.rs#L1044).
This resulted in the config never getting the flag values.
Before
```
[0 olszewski@chriss-mbp] /tmp/turbo-bug $ turbo_dev run build --no-daemon -vv 2>&1 | rg turbod
2024-08-30T16:05:12.441-0400 [DEBUG] turborepo_lib::run::builder: skipping turbod since we appear to be in a non-interactive context
[0 olszewski@chriss-mbp] /tmp/turbo-bug $ turbo_dev run build --daemon -vv 2>&1 | rg turbod 
2024-08-30T16:05:23.639-0400 [DEBUG] turborepo_lib::run::builder: skipping turbod since we …
```
=> fix(daemon): use correct arg group for deciding daemon config

crates/turborepo-lib/src/cli/mod.rs, turborepo-tests/integration/tests/conflicting-flags.t, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
in https://github.com/vercel/turborepo/pull/9082 we determined that it's best to move forward with just removing the alias for --no-daemon/--daemon.
- follow instructions in https://github.com/vercel/turborepo/pull/9082 and observe that `--daemon` now works
- `turbo --help` shows lines for both values, `--daemon` and `--no-daemon`
=> remove alias for --daemon/--no-daemon

examples/with-prisma/packages/database/prisma/schema.prisma
`referentialIntegrity = "prisma"` is deprecated, the latest feature is `relationMode = "prisma"`.
Also since `"referentialIntegrity"` is deprecated, preview feature functionality can be used without specifying it.
Didn't do any testing steps, i just saw this warning as i'm setting up my own monorepo and decided to update your example aswell. (should not mess anything up, based on https://pris.ly/d/relation-mode)
=> feat: update Prisma schema

crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/login.rs, crates/turborepo-lib/src/commands/unlink.rs, crates/turborepo-lib/src/config/file.rs, crates/turborepo-paths/src/absolute_system_path.rs
Remove `read_existing_to_string_or` in favor of `read_existing_to_string` to consolidate on the more Rust-y API for reading a path to a file.
`read_existing_to_string_or` is an awkward API due:
- It conflates two outcomes: The file not existing and the file existing with the contents of the default
- The default is provided as `Result<impl Into<String>, io::Error>`. `impl Into<String>` was chosen so unnecessary work could be avoided. This is limiting compared to `FnOnce() -> String`.
- It prevents us from using the battle tested `Option` API
The benefits of not conflating the two outcomes is best displayed when trying to read a config file. Instead of defaulting having a default of `{}` and then parsing it as JSON we can skip the parse and just use `ConfigurationOptions::default()` …
=> chore(path): make path reading api more rusty

docs/repo-docs/reference/watch.mdx
Document that caching is disabled for `turbo watch`
👀
=> docs(watch): call out no caching

docs/repo-docs/guides/tools/typescript.mdx
More or less a typo fix.
Also, what does "topo" mean? Searching the docs for "topo" yields nothing, and searching the repo yields
https://github.com/vercel/turborepo/blob/a8f38f13b6cd2a4c12f3dd08f2f631a9af4df19c/turbo.json#L215-L219
Why should `check-types` depend on `topo`? The docs point me to "[Transit Nodes](https://turbo.build/repo/docs/core-concepts/package-and-task-graph#transit-nodes)", but I'm still confused. In particular,
> Turborepo calls the `ui` package a Transit Node in this scenario, because it doesn't have its own `build` script.
So should we not have a `topo` script? If this is the case, why do other `turbo.json` files in this repo have a `topo` task (which does nothing; see below)?
Also, this repo's own `check-types` [doesn't depend on …
=> Fix invalid JSON

crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/process/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs
Fixes https://github.com/vercel/turborepo/issues/9060
[From the issue](https://github.com/vercel/turborepo/issues/9060#issuecomment-2312651231)
> I think I see the issue, it appears that rspack adds enough trailing spaces in the progress bar output the fill the current line:
> 
> ```
> ● ESC[1mESC[0m ESC[32mESC[37mESC[2m━━━━━━━━━━━━━━━━━━━━━━━━━ESC[0mESC[0m (0%) ESC[2msetup compilation                                                                                                                                           ESC[0m^MESC[2K
> ```
> 
> The `ESC[2K` operation at the erases the current line, but if the trailing spaces have caused the line to wrap, it won't erase the intended line instead just the line overflow. This probably indicates we have a mismatch in the PTY dimensions and …
=> fix(tui): start pty with matching TUI size

crates/turborepo-lib/src/run/scope/filter.rs, crates/turborepo-lib/src/run/scope/target_selector.rs
Fixes #9096
The issue was that the validation was run against an already filtered set of packages if another selector was provided i.e. `--filter foo[commit]` the name filter `foo` would run against only packages that were changed since `commit`. This meant that `foo` would be incorrectly reported as not existing.
This PR changes so the package existence check is run against all packages in the graph instead of an already filtered set.
Added red->green unit test
Verify that this PR correctly handles the repro provided in #9096 
```
[1 olszewski@chriss-mbp] /tmp/turbo-filter-break $ turbo_dev --skip-infer run lint '--filter=...@repo/eslint-config[HEAD~1]' 
turbo 2.1.1
• Packages in scope: 
• Running lint in 0 packages
No tasks were executed as part of this run. …
```
=> fix(filter): validate package name on full graph

Cargo.toml
Removing all top level dependencies that don't appear in our `Cargo.lock`:
List of crates to remove generated via
```
$ tail -n+42 < Cargo.toml | cut -d' ' -f1 > /tmp/top_level_crates.txt
$ rg -F -f /tmp/top_level_crates.txt Cargo.lock -o -N | sort -u > /tmp/matches.tx
$ rg -F -f /tmp/matches.txt -v /tmp/top_level_crates.txt
```
Everything builds and passes on CI
=> chore: remove turbopack top level crates

crates/turborepo-ui/src/tui/app.rs
`ratatui` does a great job of only updating cells that are different between render, but constructing the `vt100` screen can be intensive. 
This PR avoid constructing the screen if there are no updates to the the app state meaning there's no reason to re-render the TUI.
There are some additional changes we can also make to lower CPU usage more:
- We're currently spending a lot of time polling for terminal events see if there's a less resource intensive alternative.
- Patch vt100 so constructing `Screen` is less resource intensive e.g. https://github.com/doy/vt100-rust/pull/14
Using TUI in [next.js](https://github.com/vercel/next.js)
```
pnpm dev -F next
```
Before
After
Ran via `cargo build -p turbo --release` and `turbo_dev --skip-infer dev -F next`
=> perf(tui): only rerender if a non-tick event has been received

crates/turborepo/README.md
I was setting up turborepo locally on macOS. ran into the follow error. installing capnp fixed it
```bash
Compiling turborepo-lockfiles v0.1.0 (turborepo/crates/turborepo-lockfiles)
error: failed to run custom build command for `turborepo-lib v0.1.0 (turborepo/crates/turborepo-lib)`
Caused by:
process didn't exit successfully: `turborepo/target/debug/build/turborepo-lib-167cf8cfecddd530/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=./src/daemon/proto/turbod.proto
cargo:rerun-if-changed=./src/daemon/proto
--- stderr
thread 'main' panicked at crates/turborepo-lib/build.rs:27:23:
schema compiler command: Error { kind: Failed, extra: "Failed to execute `capnp --version`: No such file or directory (os error 2). Please verify that version 0.5.2 or higher of the capnp …
```
=> docs(crates/turborepo): add capnp to build dependencies

crates/turborepo-lib/src/run/scope/filter.rs, turborepo-tests/integration/tests/affected-rdeps.t
This PR changes `--affected` so packages that depend on affected packages also get added.
Added integration test to makes sure dependents of changed packages get ran for `--affected`.
=> fix(affected): include dependents in affected filter

crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/panic_handler.rs, crates/turborepo-lib/src/shim/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-lib/src/task_hash.rs, crates/turborepo-paths/src/absolute_system_path.rs, crates/turborepo-paths/src/lib.rs, crates/turborepo-scm/src/ls_tree.rs, crates/turborepo-scm/src/status.rs, crates/turborepo-vt100/src/screen.rs, rust-toolchain.toml
- features `fs_try_exists` and `panic_info_message` are stable
- fs::try_exists is now fs::exists
- PanicInfo is now PanicHookInfo (use `to_string` method for it)
- switch to 1.81.0-nightly in rust-toolchain.toml
`cargo test` to ensure the code has the same behavior as before
=> feat: support rust 1.81.0

packages/create-turbo/src/cli.ts
When we forgot to add the example argument in create-turbo, example was treated as true.
The error log below makes me a little confused.
``` shell
vscode ➜ /workspaces $ npx create-turbo -e
Need to install the following packages:
create-turbo@2.1.2
Ok to proceed? (y) 
? Where would you like to create your Turborepo? ./my-turborepo
? Which package manager do you want to use? npm
>>> Could not locate an example named "true". It could be due to the following:
1. Your spelling of example "true" might be incorrect.
2. You might not be connected to the internet or you are behind a proxy.
```
I couldn't find a reason why the example argument is optional, so I'm making it require.
```
vscode ➜ /workspaces/turborepo (fix/create-turbo) $ ./packages/create-turbo/dist/cli.js -e
error: option '-e, …
```
=> fix(create-turbo): Require specific argument for example option

crates/turborepo-lib/src/task_hash.rs
Add `COREPACK_HOME` to default passthrough list
=> feat(turbo): COREPACK_HOME to default passthrough

crates/turborepo-lib/src/run/watch.rs
This PR fixes an issue where the TUI was getting events from a previous run after an `update_tasks` call causing it to exit.
One can tell this is happening by inspecting the logs:
```
2024-09-16T13:17:16.509-0400 [DEBUG] turborepo_ui::tui::app: updating task list: ["docs#dev", "web#dev"]
...
2024-09-16T13:17:16.512-0400 [DEBUG] turborepo_ui::tui::app: finishing task web#dev
```
The TUI is receiving that `web#dev` finish event from the previous run which confuses the TUI as web#dev hasn't been started yet in this run. This appears to only happen for tasks that don't exit within a 500ms of receiving `SIGINT` and need to be forcibly killed.
Use `create-turbo` to create a basic repro. Change one of the dev scripts to have a long running `SIGINT` handler:
```
"dev": "trap 'sleep 5 && echo fin' …
```
=> fix(watch): await persistent run task instead of abort

crates/turborepo-lib/src/query.rs, turborepo-tests/integration/tests/command-query.t
We have a `dependencies` field on our `Package` type in `turbo query`. This returned all the transitive dependencies, i.e. the dependencies of the package's dependencies and their dependencies, and so on. This is a little confusing, so now we have explicit `directDependencies`, `indirectDependencies` and `allDependencies` fields.
Tests in `command-query.t` are updated.
=> refactor(query): make immediate dependencies default

crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/summary/task.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/tests/run/allow-no-root-turbo.t
In response to https://github.com/vercel/turborepo/pull/9149#discussion_r1761805304 this PR avoids mutating `opts` when building `Run` we now set env mode at the task level.
A majority of this PR is adding the ability to set env mode at the task level.
Updated integration test (update needed as task hash changed since env mode is now set at the task level instead of the global level).
=> feat(env mode): allow for tasks to override the global env mode

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config/env.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/summary/task.rs, crates/turborepo-lib/src/run/task_access.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/.gitignore, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/apps/my-app/package.json, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/bar.txt, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/foo.txt, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/package.json, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/packages/another/package.json, turborepo-tests/integration/fixtures/monorepo_no_turbo_json/packages/util/package.json, turborepo-tests/integration/tests/run/allow-no-root-turbo.t
This PR adds the ability to use `turbo` in a monorepo that doesn't have a `turbo.json`. This feature is currently gated behind `--experimental-allow-no-turbo-json`/`TURBO_ALLOW_NO_TURBO_JSON`.
A majority of the PR is refactoring the `EngineBuilder` so that it no longer directly loads `TurboJson`s, but delegates to a `TurboJsonLoader`. This allows us to use different strategies for resolving `TurboJson` loads depending on runtime options e.g. single package mode or task access.
Reviewing this PR is best done by viewing each commit individually.
Unit testing for `turbo.json` loading changes.
Integration test for verifying the new loader is activated with the new env var/flag.
=> feat: allow usage of `turbo` without turbo.json

crates/turborepo-lib/src/query.rs, turborepo-tests/integration/package.json, turborepo-tests/integration/tests/affected.t, turborepo-tests/integration/tests/command-query.t
Added an `Array` type that automatically adds a `length` and `items` field to GraphQL responses.
=> feat(query): add array type

docs/repo-docs/reference/run.mdx
The "UI" section was added at the wrong place in the documentation
=> Docs: fix line location for TURBO_TEAM env

docs/repo-docs/crafting-your-repository/using-environment-variables.mdx
This PR uses the `frameworks.json` file to populate the table in the docs referring to framework env inferencing.
Pull docs from this PR locally and build the docs.
=> use frameworks.json for docs

docs/repo-docs/crafting-your-repository/using-environment-variables.mdx
The formatter hurt us here.  Here's what I originally wrote and tested:
| Code | Website | DOM |
| - | - | - |
| ![Screenshot_20240918_184346](https://github.com/user-attachments/assets/cde68cb0-10bf-4b12-908f-8a998d886f51) | ![Screenshot_20240918_184612](https://github.com/user-attachments/assets/a9290436-2bec-4031-bf1b-7155ae498ca8) | ![Screenshot_20240918_184433](https://github.com/user-attachments/assets/d60ae9a9-e0f4-432e-901e-ade4d880ad5e) |
But here's what happens with this seemingly insignificant formatting change that I wasn't aware would affect the rendered output and didn't test.
| Code | Website | DOM |
| - | - | - |
| ![Screenshot_20240918_184037](https://github.com/user-attachments/assets/fe4fcf6f-047b-4884-8fe4-80a30db3a9af) | …
=> Update using-environment-variables.mdx formatting to remove extra p tag

docs/repo-docs/getting-started/add-to-existing-repository.mdx
It's suggested to install this into the repository root. If you do this, you must use `--workspace-root` flag or you will get this error:
>  ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.
=> docs: add -w flag to pnpm example

docs/repo-docs/guides/tools/typescript.mdx
In [Use a base tsconfig file](https://turbo.build/repo/docs/guides/tools/typescript#use-a-base-tsconfig-file), it is state that `base.json`, a TypeScript config file, is extended by every other `package.json`. I guess we should say extended by every other `tsconfig.json` in the workspace.
=> base.json is extended by other tsconfig.json, not package.json

docs/repo-docs/crafting-your-repository/caching.mdx
Just happened to notice this grammatical error when reading the docs: "from the first time the task was run" and "the first time the task ran" are both good, but "was ran" is not grammatical with the "was" auxiliary.
=> docs: grammar error

docs/repo-docs/crafting-your-repository/caching.mdx, docs/repo-docs/crafting-your-repository/configuring-tasks.mdx, docs/repo-docs/reference/configuration.mdx
To avoid the impression that cache is disabled when Task `outputs` key is ommitted.
`API reference` was more accurate for that behavior, than `Crafting your repository`.
I'm new to Turborepo, and was reading [Crafting your repository](https://turbo.build/repo/docs/crafting-your-repository). Two sections lead me to conclude that when there is no `outputs` key in a Task, then caching is disabled. I think the wording in `API reference` is better.
We have to account for Logs output even if there are no file outputs (which is really nice for linters).
* Review the modified documentations.
* Take into account that I'm not a native english speaker (you probably notice already ;) )
=> docs: Task outputs clarifications

docs/repo-docs/guides/tools/typescript.mdx
=> Add "go-to-definition" instructions to TypeScript docs.

crates/turborepo-lib/src/query/mod.rs, turborepo-tests/integration/tests/affected.t
Add the ability to filter in `affectedPackages`
=> feat(query): add filter to `affectedPackages`

crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/query/server.rs, crates/turborepo-lib/src/run/ui.rs, crates/turborepo-ui/src/wui/mod.rs, crates/turborepo-ui/src/wui/query.rs, crates/turborepo-ui/src/wui/subscriber.rs
We need the `currentRun` field to exist on `turbo query` to easily generate types from the GraphQL server.  This adds the field and also deduplicates the server code so both `wui` and `query` use the same `run_server` code
=> feat(query): add `currentRun` field to `turbo query`

crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-vercel-api-mock/src/lib.rs
Fixes #9177
In #8081 we changed from setting the body of our `PUT` requests from a vec of bytes to a stream of bytes.
This results in the underlying `hyper` request having a body with `Kind::Wrapped` instead of `Kind::Once`. This results in the body no longer having an [exact length](https://github.com/hyperium/hyper/blob/0.14.x/src/body/body.rs#L437). With the body no longer having an exact length, `hyper` would no longer set `Content-Length` for us [source](https://github.com/hyperium/hyper/blob/0.14.x/src/proto/h2/client.rs#L377).
This PR explicitly sets the content length header. It would be nice if we could set the length on the body itself, but `hyper` doesn't allow for this flexibility. (We cannot simply implement a size hint on `UploadProgress`, but the size hint should return the …
=> fix(cache): set content length for put artifact

docs/repo-docs/guides/tools/typescript.mdx
The newline was rending an extra `<p>` tag and messing up the layout.
=> (docs) Fix spacing on link.

turborepo-tests/integration/tests/command-query.t
The current `command-query.t` will start failing anytime a version is released and we merge in the version bump branch.
This PR changes the comparison to now check against the contents of `version.txt` instead of a literal string.
Integration test should pass now. This is the same way we test the `--version` flag: [command-version.t](https://github.com/vercel/turborepo/blob/main/turborepo-tests/integration/tests/command-version.t)
=> chore(query): fix query integration test

crates/turborepo-scm/src/git.rs
Fixes #9208
With #9169 we started using `GITHUB_BASE_REF` to determine the base of our `--affected` comparison. This can return a commit that doesn't exist in the current checkout, but will pass `rev-parse` since the reference exists.
This PR avoids crashing by treating `bad object` git errors the same as `no merge base` so if we get passed a commit that is valid, but non-existent in the checkout we still run.
I only have a manual test as creating a repository where a commit exists according to `rev-parse`, but not as part of the checkout is beyond my git-fu levels.
Create a shallow checkout:
`git clone git@github.com:vercel/turborepo.git --depth=1`
Find a commit that exists in the repo, but does not exist in the checkout e.g. `ce11d86705632160dd234ec4cf04bb1bd4ddeebc`
```
[0 …
```
=> fix(affected): handle Github Actions provided commit not part of checkout

docs/repo-docs/crafting-your-repository/creating-an-internal-package.mdx
The trailing comma is a compile time problem
=> Removed an extra comma

README.md
Removes an unnecessary `and` from the `README.md` around the Updates sections
N/A - `README.md` changes only.
=> chore: fix grammar in README.md for project update

docs/repo-docs/crafting-your-repository/creating-an-internal-package.mdx
- ~~The JSON code block's indentation has been corrected for better readability and proper JSON structure~~
- ~~Added the `inputs` property to `build` to match the actual [turbo.json](https://github.com/vercel/turborepo/blob/053a46031df7970059e458d3cc705f11b1daf313/examples/basic/turbo.json#L7) content~~
- Added a missing `}` to the JSON code block and removed a trailing comma
=> docs: add missing `}` and remove comma

examples/kitchen-sink/packages/ui/package.json
The `types` field must come before the other `exports` to be read by tooling.
=> (examples) Move types field into first position of exports of kitchen-sink example.

CONTRIBUTING.md, troubleshooting.md, turborepo-tests/helpers/setup_integration_test.sh
Ran into some weird integration test failures due to wrong `npm` version. Put a note in docs and in the setup script. While I was there, added some stuff to `CONTRIBUTING.md` and removed old references to Go.
=> chore: update contributing and troubleshooting docs

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/query/package.rs, crates/turborepo-lib/src/query/task.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, turborepo-tests/integration/tests/command-query.t, turborepo-tests/integration/tests/query/tasks.t
Adds `direct_dependencies` and `direct_dependents` fields to `Task`
Added some tests in `tests/query/task.t`
=> feat(query): add task dependencies/dependents

packages/turbo-repository/package.json, packages/turbo-repository/scripts/build.sh, pnpm-lock.yaml
`napi-rs` generates a .d.ts file for us in `turbo-repository`.  Unfortunately, this file doesn't match our project's formatting (the generated file doesn't include semicolons).  This means that every time we locally run a command (for example, `pnpm test`) that courses through this generation we jiggle this file, creating a lot of noise when developing.
This small PR fixes this by simplifying the script and running prettier on it.
run `pnpm build` from `packages/turbo-repository` before this PR and see the file change, and notice that after this PR the file change goes away.
=> fix napi double .d.ts formatting

crates/turborepo-lib/src/config/mod.rs, docs/repo-docs/reference/configuration.mdx
Setting `daemon: true` in `turbo.json` can cause timing out on deploys.  Using the daemon in CI/CD is almost* never the desired behavior.  Instead, we will detect a CI environment and force the daemon off in these situations.
<sub>*perhaps the only use-case is for us, internally, testing the daemon in our internal tests (which, run on the CI).</sub>
=> log::debug and ignore on daemon usage in CI

examples/basic/pnpm-lock.yaml, examples/kitchen-sink/apps/storefront/next-env.d.ts, examples/kitchen-sink/pnpm-lock.yaml, examples/with-vite/pnpm-lock.yaml, turborepo-tests/helpers/setup_example_test.sh
On main, `pnpm test` fails (sometimes intermittently, depending on cache scenarios, but all the time without cache).  Why?  Well..
Three of the examples had version 9 lockfiles checked in to git, when version 6 is what's required by their `packageManager` fields.  This causes tests to fail quite frequently ([example](https://github.com/vercel/turborepo/actions/runs/11238389716/job/31243099738)) in many PRs.  This happens because when installing in these repos you get `Lockfile not compatible with current pnpm` errors, and it totally blows away the old lockfile and grabs a new one.  Then, since our Next.js version is specified as `^4.1.1` in these package.jsons, it will resolve to `4.2.15` instead of the old `4.1.1`.  Then, it turns out that this minor update causes this diff in the …
=> fix broken examples causing `pnpm test` to fail

crates/turborepo-graph-utils/src/lib.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/query/package.rs, crates/turborepo-lib/src/query/task.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-ui/src/wui/query.rs, turborepo-tests/integration/fixtures/task_dependencies/query/app-a/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/app-b/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/lib-a/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/lib-b/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/lib-c/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/lib-d/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/package.json, turborepo-tests/integration/fixtures/task_dependencies/query/turbo.json, turborepo-tests/integration/tests/query/tasks.t, turborepo-tests/integration/tests/run-logging/log-order-stream.t
Adds indirect and all dependencies as fields on tasks. 
You can review commit by commit.
Adds tests along with a new fixture based off of `task-dependencies/complex`
=> feat(query): adding indirect and all dependencies for tasks

crates/turborepo-lib/src/shim/parser.rs
I was looking at hoisting daemon detection up to shim level so we could avoid reloading a filtered tracing layer. This ended up not being the solution I wanted, but I figured I should add the tests that I added.
⚠️ This PR does have an extremely minor behavior change. See [this comment](https://github.com/vercel/turborepo/pull/9248#discussion_r1797232220)
Unit tests pass
=> chore(shim): add unit tests for shim parsing

crates/turborepo-lib/src/run/scope/filter.rs
Fixing some clippy lints that only get displayed if compiled with when `test` is enabled.
👀
=> chore: fix clippy lint in filter tests

docs/repo-docs/guides/ci-vendors/circleci.mdx
In this example we need to remove the colon at the end, since we're calling the command without params.
Otherwise we get a schema validation error since it attempts to use lines below as mapping.
=> fix(docs): circleci config - remove excess colon when calling node/install-packages

crates/turbo-trace/src/main.rs
`Tracer::new` returns `Tracer` not a try-able type so we remove the `?`
Future work is getting this crate covered by CI so we make sure it compiles.
It compiles now
=> chore(trace): fix compilation error in turbo-trace

.github/workflows/turborepo-test.yml, packages/turbo-repository/rust/src/lib.rs
Since we're no longer sharing a repo with turbopack, we can now build all the crates instead of using cargo groups
=> ci: build all rust packages

crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/run/builder.rs, turborepo-tests/integration/fixtures/persistent_dependencies/3-workspace-specific/turbo.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/app-a/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/app-b/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/lib-a/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/lib-b/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/lib-c/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/lib-d/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/package.json, turborepo-tests/integration/fixtures/task_dependencies/invalid-dependency/turbo.json, turborepo-tests/integration/tests/query/validation.t
We don't want to validate certain issues with graphs with `turbo query`, because it should be still usable even with an invalid graph.
Added a test that shows that `turbo query` is tolerant of issues that `turbo run` is not.
=> fix(query): remove engine validation for query

Cargo.lock, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_graph/visitor.rs, crates/turborepo-ui/Cargo.toml, crates/turborepo-ui/src/sender.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/handle.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/mod.rs, crates/turborepo-ui/src/tui/search.rs
This PR makes the driving the TUI async, the actual operation on the state is still completely sync. The primary driver behind this PR is it allows us to make use of [`crossterm::event::EventStream`](https://docs.rs/crossterm/latest/crossterm/event/struct.EventStream.html) which seems to be far more performant than polling for user input.
The first commit of the PR just changes types from `std::sync::mpsc` to `tokio::sync::mpsc` (and make use of `tokio::sync::oneshot` for our callbacks instead of a channel of size 1). 
The second commit removes our usage of `crossterm::event::poll` in favor of a dedicated task that reads and forwards events from `crossterm::event::EventStream`.
The final commit moves the production of ticks to it's own task to avoid the need for timing out our reads. …
=> perf(tui): bring async to tui

turborepo-tests/integration/tests/run-logging/log-order-stream.t
I've noticed this integration test has been flakey lately:
- https://github.com/vercel/turborepo/actions/runs/11387765428/job/31683165527
- https://github.com/vercel/turborepo/actions/runs/11386983833/job/31680539914
- https://github.com/vercel/turborepo/actions/runs/11356438462/job/31587646091
Partially reverts changes from #9236 for the cases that I've seen fail. I don't remember this test being flakey before, so I'm changing it back. I'm assuming we're now capturing [some lines](https://github.com/vercel/turborepo/blob/ef2dc90030c6103393d42bdd5fb7f3584f1466a8/turborepo-tests/integration/tests/run-logging/log-order-stream.t#L47) that aren't deterministic in ordering.
Ran the test a few times and didn't get any failures. Hopefully CI is green.
=> chore: fix flakey log stream integration test

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/query/mod.rs, turborepo-tests/integration/tests/query/variables.t
Inject variables into a query using a json file.
Added tests to `tests/query/variables.t`
=> feat(query): variables

crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/input.rs
This PR does 3 things:
- Fix run summary from being printed out during watch mode which corrupts the TUI
- Adds additional debug logs recording the reason for the TUI shutting down
- Fixes bug where `poll` could now return `None` even if input streams were still available
The bug came down to:
- A crossterm event was received
- Translating the crossterm event via `input_options.handle_crossterm_event` returned `None` (This makes total sense, not every terminal event requires a response from the TUI)
- This `None` was returned instead of waiting for more input or a tick event
- The `while let Some(event) = poll(...)` loop would exit which triggers a TUI shut down
`npx create-turbo@latest` and then start up the TUI `turbo dev --ui=tui`, without hitting `Enter` to focus the task hit `q` …
=> fix(tui): avoid tui shutdown on unrecognized input

crates/turborepo-ui/src/tui/input.rs
Previously we had used a `None` return from the input handler as a signal that the TUI should shut down. We no longer do this so we need to explicitly return `Event::InternalStop` to signal that we should shut down the TUI.
Start up a dev task with 2.2.1 and observe that on Ctrl-C the terminal is left in raw mode:
With the build from the PR you should note that the on Ctrl-C the terminal is returned to a cooked mode:
=> fix(tui): generate stop event on ctrl c

Cargo.lock, Cargo.toml, crates/turborepo-graph-utils/Cargo.toml, crates/turborepo-graph-utils/src/lib.rs, crates/turborepo-vercel-api/Cargo.toml
As mentioned in https://github.com/vercel/turborepo/issues/9270 we currently output all strongly connected components. This PR just adds a test to display the current behavior where we show the set of nodes and not all cycles that might be contained in the SCC.
Test runs and CI is green
=> chore(test): add test for cyclic error

crates/turborepo-auth/src/lib.rs, crates/turborepo-dirs/src/lib.rs, crates/turborepo-filewatch/src/cookies.rs, crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-globwalk/src/lib.rs, crates/turborepo-repository/src/change_mapper/package.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-ui/src/prefixed.rs, crates/turborepo-ui/src/wui/query.rs, rust-toolchain.toml
fix https://rust-lang.github.io/rust-clippy/master/index.html#too_long_first_doc_paragraph and https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant clippy lints
`cargo t`
=> feat: Upgrade to Rust 1.82.0

crates/turborepo-vercel-api/src/lib.rs
Fix CONTRIBUTOR role for remote caching (cc @mrmckeb 👋🏼😄 )
=> fix(auth): add missing role

Cargo.lock, crates/turborepo-api-client/Cargo.toml, crates/turborepo-api-client/src/lib.rs, crates/turborepo-cache/Cargo.toml, crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/lib.rs
This PR makes the error message for the case that the provided token does not have [permission to upload an artifact](https://vercel.com/docs/rest-api/endpoints/artifacts#upload-a-cache-artifact-response-codes). Currently this case leads to us printing `WARNING  failed to contact remote cache: unknown status forbidden: Not authorized` the PR will change this to `WARNING Insufficient permissions to write to remote cache. Please verify that your role has write access for Remote Cache Artifact at https://vercel.com/docs/accounts/team-members-and-roles/access-roles/team-level-roles`
This does not replace the more detailed warnings when we [get a cache status](https://github.com/vercel/turborepo/blob/main/crates/turborepo-api-client/src/lib.rs#L266). These errors get printed as warnings via …
=> chore(cache): better forbidden error message

docs/repo-docs/getting-started/support-policy.mdx
Closes https://github.com/vercel/turborepo/issues/8878 by documenting that `turbo` requires the Microsoft C Runtime Libraries.
Tested out docs site and made sure the footnote links and back reference links worked.
=> docs: document MSVC requirement

packages/turbo-test-utils/src/useFixtures.ts
From Jest docs ([here](https://jestjs.io/docs/setup-teardown#repeating-setup))
> beforeEach and afterEach can handle asynchronous code in the same ways that [tests can handle asynchronous code](https://jestjs.io/docs/asynchronous) - they can either take a done parameter or return a promise
=> fix(test-utils): return promise from lifecycle

crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/watch.rs
We were accidentally stopping persistent tasks when we shouldn't have because we were reusing the same stopper.
We need a way to test persistent stuff and also run construction stuff.
=> fix(watch): stopping persistent tasks

Cargo.lock, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/snapshots/turborepo_lib__engine__builder__test__run_package_task_exact_error-2.snap, crates/turborepo-lib/src/engine/snapshots/turborepo_lib__engine__builder__test__run_package_task_exact_error.snap, turborepo-tests/integration/tests/workspace-configs/cross-workspace.t
Currently if you run `turbo cli#build` you will get the following failure*:
```
Error:   × could not find task `cli#build` in project
```
*It works if you had `"tasks": {"cli#build": {...}}` in your root level `turbo.json`
After this PR, passing a fully qualified task id to run will now work, regardless of how the task definition is defined:
- In the root `turbo.json` as `build`
- In the root `turbo.json` as `cli#build`
- In the `cli` workspace's `turbo.json` as `build`
The usage of `#` is safe here as you already have been unable to use `#` in a unqualified task name. 
- If you attempt to use a `#` in a task name in a workspace level `turbo.json` you will get an error about using package task syntax in a workspace file.
- If you attempt to specify a task in the root `turbo.json` of the …
=> feat: support task id entrypoints

crates/turborepo-lib/src/task_graph/visitor/command.rs
In https://github.com/vercel/turborepo/pull/9306 I somehow dropped the `cmd.open_stdin()` call so we never started tasks hooked up to stdin.
I verified I copied the closing/forwarding stdin logic in my refactor [as seen here](https://github.com/vercel/turborepo/blob/main/crates/turborepo-lib/src/task_graph/visitor/exec.rs#L376), we were just never opening it in the first place.
`turbo_dev dev` should now let you interact with `persistent` tasks
=> fix(tui): make sure to open stdin for all tasks

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/table.rs
Toggle the visibility of the task list with an `h` hotkey.
https://github.com/user-attachments/assets/7a8b3ad1-5ead-47d0-9aaf-513acce6ad3c
Future note: I don't love that I'm stealing a vertical line from the task list. Screen real estate is valuable. It's likely we could give the `Task` header and footer instructions a faded style and get rid of the horizontal bars. (I'd recommend doing this regardless of the result of this PR.
👀
=> feat(ui): Hide task list with `h` key.

Cargo.lock, crates/turborepo-ui/Cargo.toml, crates/turborepo-ui/src/tui/table.rs
Currently, when running tasks using the new UI, turbo inserts passed / failed tasks below cached tasks (in order of completion) meaning the stuff users probably want to see (failed things) end up at the bottom of the list or off screen. This change attempts to improve that by inserting those items in front of the list of cached tasks. That way cached tasks (likely the least interesting) end up last and preceded by successful tasks and then failed tasks. This assumes that users will more interested in failed tasks than successful ones but I am also open to ordering just the failed / successful task in order of completion instead.
In practice this means if running turbo in a large project with `--continue` where the majority of tasks are and will remain cached between runs, then the things …
=> fix: order tasks in order of interest, namely failed, successful, then cached

crates/turbo-trace/src/import_finder.rs, crates/turbo-trace/src/lib.rs, crates/turbo-trace/src/tracer.rs, crates/turborepo-lib/src/query/file.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__turbo_trace_get_`import_value_and_type.ts`_with_all_dependencies_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__turbo_trace_get_`import_value_and_type.ts`_with_type_dependencies_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__turbo_trace_get_`import_value_and_type.ts`_with_value_dependencies_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__turbo_trace_get_`link.tsx`_with_all_dependents_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__turbo_trace_get_`link.tsx`_with_type_dependents_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__turbo_trace_get_`link.tsx`_with_value_dependents_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/turbo_trace/import_just_type.ts, turborepo-tests/integration/fixtures/turbo_trace/import_just_value.ts, turborepo-tests/integration/fixtures/turbo_trace/import_value_and_type.ts, turborepo-tests/integration/fixtures/turbo_trace/link.tsx, turborepo-tests/integration/fixtures/turbo_trace/types.ts
Allow for turbo trace to filter by import type so you can get just the type imports. Note, this just checks syntactically, so it's possible it will miss type imports that are not labeled as such. However, this is a pretty common lint rule to split out type imports.
Added tests in `turborepo-lib/tests/query.rs` including both dependencies and dependents with import type filtering
=> feat(trace): filtering by import type

Cargo.lock, Cargo.toml, crates/turborepo-api-client/Cargo.toml, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/daemon/default_timeout_layer.rs, crates/turborepo-updater/Cargo.toml
Unfortunately this does *not* get us to build Windows ARM natively, but it at least eliminates the first blocker, which is ring 0.16. ring is a crypto library that `rustls` uses under the hood, and because it relies on inline assembly, it can't be built for Windows ARM. However, ring 0.17 added Windows ARM support. To get all our deps into ring 0.17, we need to bump reqwest and ureq. The first one is easy, but the second one is used by update-informer, so this PR redirects to my fork of update-informer that has a bumped ureq version.
Try building on Windows ARM and validate that we "only" get an error for building tokio
=> chore: bump dependencies for Windows ARM support

Cargo.lock, Cargo.toml, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/micro_frontends.rs, crates/turborepo-lib/src/process/command.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/error.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/task_graph/visitor/command.rs, crates/turborepo-lib/src/task_graph/visitor/exec.rs, crates/turborepo-lib/src/task_graph/visitor/mod.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-micro-frontend/Cargo.toml, crates/turborepo-micro-frontend/fixtures/sample.jsonc, crates/turborepo-micro-frontend/src/error.rs, crates/turborepo-micro-frontend/src/lib.rs, crates/turborepo-repository/src/package_graph/mod.rs
This PR adds all support necessary for starting a MFE local proxy:
- Adds new `CommandProvider` to allow for multiple strategies for constructing a command depending on the type
- Adds parsing logic for `micro-frontends.jsonc`
- Parses all `micro-frontends.jsonc` found in the package graph*
- Adding a task definition for the generated `proxy` task if MFE configs are found
- Explicitly include the `proxy` tasks in engine building step if a MFE dev task is found in the product of the package `--filter` and the tasks specified in `turbo run`
- Adds a `CommandProvider` that construct a command that invokes the MFE local proxy
⚠️ This currently only support MFE configs that are located in shared packages and doesn't respect a loose MFE configs.
Follow up work:
In a repository with MFE, run a …
=> feat(mfe): inject local proxy

packages/turbo-codemod/__tests__/get-turbo-upgrade-command.test.ts
I have tried 5 times to cut a release. Temporarily bumping these so I can get one out.
See https://github.com/vercel/turborepo/actions/runs/11619011909/job/32359529053
👀
=> hack(js): bump codemod test timeout

crates/turbo-trace/src/tracer.rs, crates/turborepo-lib/src/query/file.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__turbo_trace_get_`export_conditions`_with_dependencies_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/turbo_trace/export_conditions.js, turborepo-tests/integration/fixtures/turbo_trace/package.json
`package.json` exports can be selected based on conditions such as whether the package is being imported as an esm `import` or a `require`. We added `import` and `require` as default conditions for the resolver so packages that define these conditions trace properly.
Added a test with `swr` which uses these package export conditions
=> feat(trace): add export conditions `import` and `require` to trace resolver

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/table.rs, crates/turborepo-ui/src/tui/task.rs
Move the new task ordering from just the view to the underlying state so that the task list syncs up with the pane.
Added unit testing for new insertion order.
=> fix(tui): sort tasks in state not just view

.github/workflows/lsp.yml, .github/workflows/test-js-packages.yml, .github/workflows/turborepo-test.yml
We need to do this because macOS 12 runners are getting deprecated. 
CI should pass
=> chore(ci): bump macOS runner to 13

crates/turborepo-repository/src/package_graph/mod.rs, docs/repo-docs/getting-started/add-to-existing-repository.mdx
There doesn't necessarily need to be a `name` field in the root package.json, since it won't get used for other work throughout the graph.
I wrote a test and tested against `create-turbo` by removing the `name` field from the root package.json
=>  fix: Don't require a name for the root package.json.

.github/workflows/test-js-packages.yml, .github/workflows/turborepo-native-lib-test.yml
There were quite a few checks running when making docs changes that were unnecessary. They were slowing us down and quite noisy, so let's get them out of the way.
=> chore: Stop running unnecessary checks for docs-only changes.

crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-micro-frontend/src/lib.rs, crates/turborepo-unescape/src/lib.rs
Previously we were relying on the proxy already being built, for non-internal use cases this will be true, but for the internal case we need to make sure it is built before we try to start the proxy.
- Edit `packages/micro-frontends/dist/bin/cli.cjs` and add a `throw new Error("oops")` to the top
- `turbo vercel-docs#dev` should fail due to the proxy script failing
- Now try with the PR `turbo`: `turbo_dev --skip-infer vercel-docs#dev`, you will see the MFE package being built before the proxy is started.
=> fix(mfe): build internal package if present in graph

crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/query/package.rs, crates/turborepo-lib/src/query/task.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__basic_monorepo_get_package_that_doesn't_exist_(npm@10.5.0).snap
Before we'd just trust that a package would exist with the name provided. This would lead to errors when using the package but not when constructing it. Now we actually validate it during construction.
Added test for invalid package constructor
=> fix(query): validate package name

Cargo.lock, crates/turbo-trace/Cargo.toml, crates/turbo-trace/src/tracer.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/query/file.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__turbo_trace_get_`invalid.ts`_with_dependencies_(npm@10.5.0).snap, turborepo-tests/integration/tests/turbo-trace.t
To help debug trace, pretty print the errors to stderr by default. Includes fancy error messages either via SWC or our own miette infrastructure
Try using trace and hit an error
=> feat(trace): pretty print trace errors to logs

docs/repo-docs/getting-started/add-to-existing-repository.mdx
There were a few parts to the copy on this page that needed some touching up, according to user feedback.
👀
=> docs: Updates for accuracy in Add to Existing Repository page.

crates/turborepo-lib/src/micro_frontends.rs, crates/turborepo-lib/src/task_graph/visitor/command.rs, crates/turborepo-lib/src/task_graph/visitor/exec.rs
MFE development tasks may want to know if there's a corresponding proxy that is being run. Just checking if the proxy is running is error prone since they're both persistent tasks and there's no consistent way to prevent the check from running before the proxy server is listening on the port.
We avoid needing to perform this check by setting an environment variable for each development task if there's an associated proxy task in the configuration. It is then up to the underlying task to alter it's behavior depending on the presence of this variable.
In a project with a MFE, run a development task and verify that `TURBO_TASK_HAS_MFE_PROXY` is set to `true`
=> feat(mfe): add env var indicating mfe proxy

crates/turborepo-lib/src/daemon/server.rs
Before we'd initialize the package changes watcher when the daemon starts up. Now we do it only when watch mode needs it.
Tested manually:
```
cargo run -p turbo -- --cwd ../my-turborepo --skip-infer daemon restart 
```
In different terminal:
```
cargo run -p turbo -- --cwd ../my-turborepo --skip-infer daemon logs 
```
Change a file in the repository, note that no logs are emitted for this change.
Then run
```
turbo watch dev
```
Note that package changes start showing up.
=> chore(daemon): lazy load package changes watcher

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/mod.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
A command to provide debugging information for reproductions or otherwise understand a machine better. Output will look something close to this.
```
CLI:
Version: 2.2.4-canary.4
Location: /Users/anthonyshew/projects/open/turbo/target/debug/turbo
Daemon status: Running
Package manager: pnpm
Platform:
Architecture: aarch64
Operating system: macos
Available memory (MB): 13598
Available CPU cores: 10
Environment:
CI: None
Terminal (TERM): xterm-256color
Terminal program (TERM_PROGRAM): tmux
Terminal program version (TERM_PROGRAM_VERSION): 3.4
Shell (SHELL): /bin/zsh
stdin: false
Turborepo System Environment Variables:
TURBO_INVOCATION_DIR: /Users/anthonyshew/projects/open/turbo
```
Try it out!
=> feat: `turbo info` command for debugging

crates/turbo-trace/src/tracer.rs, crates/turborepo-lib/src/query/file.rs
- Added more conditions
- Made emitting errors configurable
- Add inference for multiple node_modules
=> chore(trace): fixes and improvements

crates/turborepo-paths/src/anchored_system_path.rs, crates/turborepo-paths/src/relative_unix_path.rs
I ended up hitting a panic using this function incorrectly, we can make it safer.
**Explanation of Issue**
Take the following code snippet:
```
let absolute = AbsoluteSystemPath::new("/").unwrap();
let foo = String::from("foo/bar/baz");
let bar = RelativeUnixPath::new(foo).unwrap();
let baz = absolute.join_unix_path(bar); // panics
```
It panics with the following error:
```
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
```
The issue is with the line `let bar = RelativeUnixPath::new(foo);` so lets take a look at the definition of `RelativeUnixPath::new`:
```
pub fn new<'a, P: AsRef<str> + 'a>(value: P) -> Result<&'a Self, PathError> {
let path = value.as_ref();
/* body …
```
=> fix(turbopath): avoid incorrect lifetime in RelativeUnixPath::new

examples/with-shell-commands/package.json
Fixes https://github.com/vercel/turborepo/issues/9150
yarn classic errors when using workspaces without setting private to true
=> fix(examples): add private to with-shell-cmds

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/process/child.rs, crates/turborepo-lib/src/run/watch.rs
I noticed in https://github.com/vercel/turborepo/issues/9389 that the TUI wasn't exiting if `watch` exited from anything other than a `Ctrl-C` (including a direct SIGINT to the process). This PR ensures that we shut down the TUI and the persistent task handle regardless of how `watch.start()` exits.
- Start up a watch task `turbo_dev watch dev`
- Find the pid file via `turbo_dev daemon status`
- Kill the daemon `kill $(cat /path/to/pid/file)`
Before
After
=> fix(watch): ensure TUI is shutdown regardless of exit path

crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/engine/snapshots/turborepo_lib__engine__builder__test__run_package_task_invalid_package.snap
With package tasks being accepted by `run` users can now bypass our package existence check in `--filter`. We add an additional check in the task graph builder where we verify that the `bad-package` in a `turbo run bad-package#task` command will error with a message explaining that `bad-package` doesn't exist.
Added unit test that hits this error path along with snapshotting the error message
=> chore(engine): error about missing package in package task

crates/turborepo-ui/src/tui/app.rs, pnpm-lock.yaml
We previously didn't let you "wrap" your selection to the selected task if you were at the top or bottom of the task list. Now we do!
Run some tasks with the TUI and:
-  Press ↑ when you have the top item in the list selected.
- Press ↓ when you have the bottom item in the list selected.
=>  feat: Wrap-around selection for TUI.

crates/turborepo-lib/src/commands/info.rs
We have had cases in the past where it would be nice to know if the user is using WSL. This adds best effort detection for printing out if you're using WSL.
Note that this isn't a 100% solution, according to [this superuser answer](https://superuser.com/questions/1749781/how-can-i-check-if-the-environment-is-wsl-from-a-shell-script/1749811#1749811). But, if you're doing something like is listed in the caveats...That's an extreme edge case.
=>  feat: Detect WSL in `turbo info`.

docs/repo-docs/core-concepts/remote-caching.mdx
Clarify that use can use environment variables. You don't have to use the flags all the time. 😄
👀
=> docs: Clarify how to use values for self-hosted Remote Cache.

docs/repo-docs/reference/info.mdx, docs/repo-docs/reference/meta.json
2.3 release
Adds https://github.com/vercel/turborepo/pull/9368 to the docs.
👀
=> docs: `turbo info`

crates/turborepo-lib/src/run/watch.rs
Closes https://github.com/vercel/turborepo/issues/9401
`turbo watch` cannot function without the daemon, we should warn users of this if they have tried to disable the daemon.
We could error if the daemon is disabled, but that would lead to awkward behavior if it is disabled in `turbo.json`. It's possible to want the daemon disabled for `turbo run`, but still want to use `turbo watch`.
Attempt running watch with an explicit request to disable the daemon:
```
[1 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev --no-daemon watch @turbo/types#build            
WARNING  No locally installed `turbo` found. Using version: 2.2.4-canary.8.
turbo 2.2.4-canary.8
WARNING  daemon is required for watch, ignoring request to disable daemon
• Packages in scope: …
```
=> chore(watch): warn if daemon is disabled

crates/turborepo-lib/src/cli/mod.rs
Handle the package inference env var in watch mode with the same logic we use for run
Try it out by running the binary in a nested directory. Note, you'll have to remove your local turbo for this to work properly
=> feat(watch): package inference in watch mode

Cargo.lock, crates/turborepo-lib/src/micro_frontends.rs, crates/turborepo-micro-frontend/Cargo.toml, crates/turborepo-micro-frontend/src/error.rs, crates/turborepo-micro-frontend/src/lib.rs
We should avoid crashing if we encounter a version of MFE config that we don't currently support.
Added unit test. Quick spot check by changing version in an example to an unsupported version:
```
[1 olszewski@chriss-mbp] /Users/olszewski/code/ $ turbo_dev --skip-infer micro-frontends-example-web#dev --dry=json > /dev/null
turbo 2.2.4-canary.10
WARNING  Ignoring /Users/olszewski/code/packages/micro-frontends-example-site-config/micro-frontends.jsonc: Unsupported micro-frontends configuration version: 2. Supported versions: ["1"]
```
=> fix(mfe): avoid crashing if unsupported mfe version found

docs/repo-docs/crafting-your-repository/running-tasks.mdx, docs/repo-docs/reference/run.mdx
Documenting https://github.com/vercel/turborepo/pull/9344.
👀
=> docs: Add doc for running by task ID.

crates/turborepo-env/src/lib.rs, crates/turborepo-lib/src/task_hash.rs
In https://github.com/vercel/turborepo/issues/9424 a user had `path` as their Windows env var instead of `Path` or `PATH`. On Windows environment variables are case insensitive e.g. `process.env.PATH` and `process.env.Path` would both return the same. While fetching them might be the same [`std::env::vars`](https://doc.rust-lang.org/std/env/fn.vars.html) returns the environment variable names cased as they were declared even though [`std::env::var`](https://doc.rust-lang.org/std/env/fn.var.html) is case insensitive on Windows.
Take for example the following code:
```
for (key, value) in std::env::vars() {
println!("{key}: {value}");
let lowercase = key.to_ascii_lowercase();
println!("{lowercase}: {:?}", std::env::var(&lowercase));
}
```
On Windows it outputs:
```
...
PUBLIC: …
```
=> fix(windows): fix env var glob casing

.github/ISSUE_TEMPLATE/0-turborepo-bug-report.yml
Updating our bug issue template to include `turbo info`, among other assorted changes.
👀
=> chore: Update bug issue template.

crates/turborepo-filewatch/src/lib.rs, crates/turborepo-lib/src/daemon/server.rs
When setting up manual recursive watching on folders (as is the case under Linux), the watching thread should not exit if a directory no longer exists. This is likely to occur within build output directories and it should not be the cause for interrupting the daemon.
Likely fixes https://github.com/vercel/turborepo/issues/8800 and https://github.com/vercel/turborepo/issues/8491
`cargo test -p turborepo-filewatch`
(Within a Fedora Linux VM)
1. Prerequisites
```bash
sudo dnf check-update
sudo dnf install webkit2gtk4.1-devel \
openssl-devel \
curl \
wget \
file \
libappindicator-gtk3-devel \
librsvg2-devel
sudo dnf group install "C Development Tools and Libraries"
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
```
2. Obtain test project sources
```bash
git clone …
```
=> Fix(filewatcher): handle removed directories #8800

.github/turbo-orchestrator.yml, .github/turborepo-release.yml
We used to need these labels when Turbopack was in this repository as well but its not anymore. No need for the cruft!
=> chore: Remove obsolete GitHub labels.

.github/workflows/bench-turborepo.yml, .github/workflows/lsp.yml, .github/workflows/turborepo-compare-cache-item.yml, .github/workflows/turborepo-library-release.yml, .github/workflows/turborepo-release.yml
v3 of `actions/upload-artifact` and `actions/download-artifact` will be fully deprecated by **5 December 2024**. Jobs that are scheduled to run during the brownout periods will also fail. See:
1. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
2. https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/
Run the CI jobs
=> ci: update `upload-artifact` and `download-artifact` actions to v4

docs/repo-docs/crafting-your-repository/configuring-tasks.mdx
=> docs: Clarify output globs relativeness.

crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__force_remote_r,local_r.snap
As mentioned in #9453 if a user sets `--force` when `TURBO_CACHE` is set we currently error. `--force` should be applicable in this case an just remove any reads from the `TURBO_CACHE` setting.
Updated unit test, manual verification of behavior for other cases:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ turbo_dev @turbo/types#build --force --cache=local:rw 
WARNING  No locally installed `turbo` found. Using version: 2.3.1-canary.0.
ERROR  the argument '--force [<FORCE>]' cannot be used with '--cache <CACHE>'
Usage: turbo --force [<FORCE>]
For more information, try '--help'.
[1 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ TURBO_FORCE=1 turbo_dev @turbo/types#build --cache=local:rw       
WARNING  No locally installed `turbo` found. Using …
```
=> fix(cache): allow force to override any cache settings

.github/workflows/turborepo-release.yml
https://github.com/vercel/turborepo/pull/9447 bumped us to `upload-artifact` to v4 which uses Node 20. Node 20 required a newer glibc version than was available on our build that targeted AWS's Lambda2's glibc version. See [this job](https://github.com/vercel/turborepo/actions/runs/11897321603/job/33151832964#step:12:21) for an example failure.
Requiring this glibc version isn't necessary for the musl builds since it uses musl instead of glibc for libc.
I do not think this was intentional to have the musl binary building in this container as we changed this back when we were cross compiling: https://github.com/vercel/turborepo/commit/8ca67c3c0cd9601909730953b9d03699a01b1da8
Future work: This does not fix the `@turbo/repository` release.
Ran test release and x86 msul build now passes: …
=> chore(release): fix release by avoiding old glibc version

crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/diagnostics.rs, docs/repo-docs/reference/link.mdx, turborepo-tests/integration/tests/command-link.t, turborepo-tests/integration/tests/turbo-help.t
Adds `--yes` and `--scope` flags
Added tests for parsing those flags
=> feat(link): add `--yes` and `--scope` flags to `link`

docs/pack-docs/features/dev-server.mdx, docs/pack-docs/incremental-computation.mdx, docs/pack-docs/meta.json, docs/pack-docs/why-turbopack.mdx
This depends on some images (these are placeholders, I'll get the real assets from @anthonyshew)
=> docs(turbopack): Add incremental-computation page, intended to replace core-concepts page

docs/repo-docs/getting-started/support-policy.mdx
The way the Markdown footnote attribution looked just felt a little out of place. Simplifying and localizing here.
Before
After
=>  docs: Small stylistic change for footnote.

crates/turborepo-scm/src/git.rs
Previously we would only consider the destination file moved as changed and not the source. We use `diff-tree` instead of `diff` to track these moves. 
This PR also fixes an issue where `include_uncommitted: false` was not respected if `to_commit` wasn't present i.e. we would always return uncommitted changes. This did not affect users since this API isn't exposed to users and there's no way to set `include_uncommitted: false` without setting a `to_commit`.
Added unit test where a file is moved between packages. Also added additional checks for our `changed_files` tests
=> fix(affected): consider both source and destination as changed

crates/turborepo/tests/snapshots/query__turbo_trace_monorepo_get_`apps__my-app__index.ts`_with_dependencies_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/turbo_trace_monorepo/apps/my-app/index.ts, turborepo-tests/integration/fixtures/turbo_trace_monorepo/apps/my-app/package.json, turborepo-tests/integration/fixtures/turbo_trace_monorepo/packages/ship-types/index.ts, turborepo-tests/integration/fixtures/turbo_trace_monorepo/packages/ship-types/package.json
Use a mocked `@types` package instead of a real one in test so we don't hit the npm registry.
=> chore: use mocked package in test

.github/actions/setup-node/action.yml, .github/actions/setup-rust/action.yml, .github/workflows/bench-turborepo.yml, .github/workflows/lsp.yml, .github/workflows/test-js-packages.yml, .github/workflows/turborepo-compare-cache-item.yml, .github/workflows/turborepo-native-lib-test.yml, .github/workflows/turborepo-release.yml, .github/workflows/turborepo-test.yml
Upgrade all of our various actions to versions that use Node 20 since Node 16 is getting shut down December 5
Note this does not switch us off of [get-diff-action](https://github.com/technote-space/get-diff-action/) which has been deprecated so we will need to find a new solution.
CI on this PR
Test Release: 
[workflow](https://github.com/vercel/turborepo/actions/runs/11955946798) <- failed because I wrote `actions/checkout@4` instead of `actions/checkout@v4` on the last step
[workflow with fix](https://github.com/vercel/turborepo/actions/runs/11956800941)
You should notice the lack of Node 16 warnings on the workflow summary page: https://github.com/vercel/turborepo/actions/runs/11954973491
=> chore(ci): upgrade GitHub Actions to Node 20

packages/turbo-repository/js/index.js
This will speed up the report generation and avoid unwanted DNS queries during the report
See https://github.com/lovell/detect-libc/pull/21
=> perf: Exclude network while doing getReport

crates/turbo-trace/src/tracer.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__turbo_trace_get_`incorrect_extension.mjs`_with_dependencies_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/turbo_trace/incorrect_extension.mjs
Invalid extensions are unfortunately too common in imports. Therefore if we can't resolve with the extension, we strip it and try again.
Added a test where we try to import with the wrong extension
=> feat(trace): resolve incorrect extension

crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/pane.rs
Just wanting to spruce things up a bit.
- Left-aligned the text so that it bounces around less when changing states. This is considered a generally good practice in UI design.
- Re-writing text chunks for simplicity
In the process of adjusting the text with a comma as a separator, I realized I could refactor the logic for which text to render to be a little easier to read. Isn't it great when the simplicity of the visual design is reflected in the code?!
You'll want to put the TUI into different states to see them all. Matrix is:
- Task list open/closed
- Text selected/not selected
- Task being interacted with/ not interacted with
A sample of the spirit of the changes is below.
Before
After
=> refactor(tui): Improve aesthetics for helper text.

docs/repo-docs/reference/run.mdx
Makes the documentation for `--cache` more clear.
👀
=> docs: Improve clarity on `--cache`.

crates/turborepo-micro-frontend/src/lib.rs
This PR allows `@vercel/microfrontends` to be considered a MFE dependency in addition to `@vercel/micro-frontends-internal`.
=> feat(mfe): allow @vercel/microfrontends to be considered a MFE package dependency

crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs
Switch to no longer hardcode the MFE package name when making sure it is built before we attempt to start the proxy.
Ran in repository with external MFE package name. Confirmed that it's build task was picked up.
=> fix(mfe): build either mfe package name

packages/eslint-config-turbo/flat/index.js, packages/eslint-config-turbo/index.js, packages/eslint-config-turbo/package.json
Adds ESLint Flat Config Support to `eslint-config-turbo`. Users will be able to use:
```
import turboConfig from "eslint-config-turbo/flat"
export default [
...turboConfig
]
```
This is meant to be backwards compatible with ESLint v8, leaving the `extends` key in place for that purpose.
Difficult to test this, so we'll be cutting a canary shortly after to make sure.
=> feat: update `eslint-config-turbo` to support ESLint Flat Config.

crates/turborepo-ui/src/tui/input.rs
**Summary:**
This PR introduces support for basic Vim-style key bindings within the `tui` component of TurboRepo, specifically for pane navigation. The goal is to improve navigation efficiency for users familiar with Vim-like key motions.
**Key Changes:**
- Added support for `h`, `j`, `k`, and `l` Vim keybinds for interactive mode:
- **`Ctrl+h`**: Exit interactive mode.
- **`Ctrl+j`**: Move down.
- **`Ctrl+k`**: Move up.
- **`Ctrl+l`**: Enter interactive mode.
- General Vim-style motions:
- **`j`**: Move down.
- **`k`**: Move up.
- **`l`**: Enter interactive mode.
**Motivation:**
Adding these motions provides a more intuitive interface for users familiar with Vim commands, enhancing navigation within the pane section of the TurboRepo UI.
*[Related …
=> feat(tui): add Vim motions support for task list selection

docs/repo-docs/getting-started/installation.mdx, docs/repo-docs/reference/create-turbo.mdx
=> docs: describe using a custom URL with `create-turbo`.

docs/repo-docs/getting-started/installation.mdx
Fixes https://vercel.com/vercel/turbo-site/7YWCRzojaypxXMLNjRcpqWzWUSP1?filter=errors
=> docs: fix formatting on `/repo/docs/getting-started/installation`

.github/workflows/lint-pr-title.yml
Pattern is `^[^A-Z].*$ ` which means the string can't start with uppercase. The message was saying the opposite ("doesn't start with a lowercase character).
=> chore: fix error message when PR title does not conform to pattern

crates/turborepo-lib/src/task_hash.rs
Closes #9402 by adding `DISPLAY` to the default pass through map. TL;DR `xdg-open` uses `DISPLAY` to decide which display it should open a new window on.
👀
=> fix(env): add DISPLAY to default pass through

crates/turborepo-ui/src/tui/input.rs
In #9243, we added these keybinds for Vim. This refactors to put them in an `|` OR and into the section that is for fallthroughs of interactive mode.
Try it out!
=> refactor(tui): cleanup where Vim binds were added.

docs/repo-docs/guides/tools/docker.mdx, examples/with-docker/apps/api/Dockerfile, examples/with-docker/apps/web/Dockerfile
`--filter` isn't needed after running `prune` since the target from the prune is the only application in the pruned workspace. This was confusing someone in https://github.com/vercel/turborepo/discussions/9496.
=> fix(examples): remove `--filter` from `with-docker` example.

examples/basic/apps/docs/package.json, examples/basic/apps/web/package.json, examples/basic/package.json, examples/basic/packages/eslint-config/next.js, examples/basic/packages/ui/package.json, examples/basic/pnpm-lock.yaml
I left some unneeded dependencies behind when I was upgrading this example in #9501. This gets rid of them.
I've verified that ESLint violations get reported as expected in my editor and when running `turbo lint`. You can also clone with `npx create-turbo@canary -e https://github.com/vercel/turborepo/tree/shew-0f804/examples/basic basic-eslint-9` to have a play with it.
=> chore(examples): remove spare dependencies from basic example

crates/turborepo-ui/src/tui/input.rs
I did the incorrect directions for up/down in #9508. This fixes it.
=> fix: correct TUI vim binds direction

crates/turborepo-ui/src/tui/input.rs
I hadn't realized that the list was separated such that the fallthrough binds were at the end of the list. Putting `h` at the bottom so its in the right spot now.
👀
=> chore(tui): move `h` bind to correct section

crates/turborepo-ui/src/tui/pane.rs
I started noticing that my logs and the text help were looking quite similar. This differentiates the two so its more obvious at a glance.
=> chore(tui): dim pane text helpers and remove dead code.

docs/repo-docs/reference/system-environment-variables.mdx
Before, we were only able to link people to the page itself, and having them find the variable in the table itself.
Instead, let's put an `id` tag on things so we can give hashlinks to users.
This should be a no-op on the visual rendering of the page, as I've pasted the rendered HTML from the page directly into the Markdown file. The only change is the addition of the `id`s.
=> chore(docs): enable hashlinking for System Environment Variables entries

.github/ISSUE_TEMPLATE/0-turborepo-bug-report.yml
I thought this would be good vibes but it just looks like noise since we keep our Issues scoped to bugs and only bugs. We'll keep the title for the docs requests but this was noisy for the bugs template.
=> chore: remove leader from bug report template

crates/turborepo-filewatch/src/package_watcher.rs, crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/commands/ls.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/task_graph/visitor/exec.rs, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/inference.rs, crates/turborepo-repository/src/lib.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/dep_splitter.rs, crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-repository/src/workspaces.rs, packages/turbo-repository/rust/src/internal.rs
A prefactor for cleaning up the `PackageManager` enum. If we want to make this a richer data structure we need to remove some behaviors that other crates might be depending on. This is just a small PR, the far larger one will be removing direct pattern matching on `PackageManager` variants.
This is purely removal of code and moving of code. Relying on existing unit tests
=> chore(pm): reduce PackageManager surface area

crates/turborepo-lib/src/microfrontends.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/turbo_json/loader.rs
This PR adds the MFE support for repositories that do not contain a `turbo.json`. All this boils down to is:
- Slight refactor for constructing MFE configs to allow for us to test this without hitting disk
- Going down the "no turbo.json" codepath even if not explicitly enabled as long as MFE configs are present
- Update generated `turbo.json` with `proxy` tasks injected
Added unit test for sans-`turbo.json`, but containing a MFE config.
Manual test on a MFE test repo w/o a `turbo.json`
=> feat(mfe): enable proxy for no turbo json

crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/login.rs, crates/turborepo-lib/src/commands/ls.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/commands/unlink.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/diagnostics.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__force.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__force_remote_r,local_r.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__no-cache.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__no-cache_remote_w,local_rw.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__remote-cache-read-only.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__remote-cache-read-only_remote_rw,local_r.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__remote-only.snap, crates/turborepo-lib/src/snapshots/turborepo_lib__opts__test__remote-only_remote_r,local_rw.snap
Refactors our config setup to explicitly transform the `Args` and `Config` to `Opts` in the `CommandBase` constructor. This accomplishes a few things:
- Limits our usage of args beyond `cli`. Args are structured according to the CLI parsing logic, so there are multiple fields that do the same thing (args.command.run_args and args.run_args). By compiling down to `Opts`, we can use a more normalized structure.
- Remove the requirement that we have a `Command::Run` to create a `Run` struct. This requires us to mock out a `Command::Run` in places like `query` or `ls`, which is unnecessary.
- Fix a potential nasty bug where we change the `Args` struct via `CommandBase::args_mut` but that change is not propagated to the config because it's cached via a `OnceCell`.
- Finally, and most …
=> refactor: compile args + config to opts

.github/workflows/lint.yml, .github/workflows/test-js-packages.yml, .github/workflows/turborepo-test.yml
Remove our usage of `technote-space/get-diff-action` which uses Node 16 and is deprecated. Node 16 jobs are getting shut off tomorrow!
In places where it made sense, I used the [paths](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) syntax to limit when workflows get run. Reading the docs I think this only works at the workflow level?
CI on this PR
=> chore(ci): remove determine step

crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/lib.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/commands/login.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lib/src/commands/unlink.rs, crates/turborepo-lib/src/diagnostics.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/watch.rs
Remove the config field from `Opts` entirely. I'm doing this because the config data already gets partially moved into `Opts`, so by keeping the config around, we have multiple sources for the same data. Now `Opts` is the fully transformed, normalized config for a run.
You can review this commit by commit if you like
=> refactor(opts): remove config from opts

crates/turborepo-scm/src/lib.rs
In the case of an error when parsing `git` output. We would drop a `Child` without `wait`ing on it which results in a zombie process as the pid is never reaped.
From [Rust docs](https://doc.rust-lang.org/std/process/struct.Child.html#warning)
> On some systems, calling [wait](https://doc.rust-lang.org/std/process/struct.Child.html#method.wait) or similar is necessary for the OS to release resources. A process that terminated but has not been waited on is still around as a “zombie”. Leaving too many zombies around may exhaust global resources (for example process IDs).
> The standard library does not automatically wait on child processes (not even if the Child is dropped), it is up to the application developer to do so. As a consequence, dropping Child handles without waiting on them first …
=> chore(scm): avoid dropping child before wait

pnpm-lock.yaml
https://github.com/vercel/turborepo/pull/9533 accidentally bumped our lockfile be a pnpm 9 lockfile, we're on pnpm 8
`corepack enable && pnpm i --frozen-lockfile` will now work
=> fix: downgrade lockfile to match pnpm version in package.json

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/cli/snapshots/turborepo_lib__cli__test__turbo---filter=foo-run-build.snap, crates/turborepo-lib/src/cli/snapshots/turborepo_lib__cli__test__turbo---filter=web-watch-build.snap, crates/turborepo-lib/src/cli/snapshots/turborepo_lib__cli__test__turbo---no-daemon-run-build.snap, crates/turborepo-lib/src/cli/snapshots/turborepo_lib__cli__test__turbo---no-daemon-watch-build.snap, crates/turborepo-lib/src/cli/snapshots/turborepo_lib__cli__test__turbo-watch-build---no-daemon.snap
Currently we have a bug where run args can be specified incorrectly and we'll silently ignore them.
- Specified for non-run commands e.g. `turbo --no-daemon watch`
- Specified before a subcommand e.g. `turbo --filter=foo run build` `turbo --filter=foo watch build` which will silently ignore any arguments provided before the subcommand.
This PR makes these explicit failures instead of silently ignoring them. There is a solution where we attempt to "merge" args provided on either side of the subcommand, but that would require us to switch to `clap`'s builder interface which would make our 80 line top level CLI interface ~1k lines. I do not think this is worth the time to go about that refactor to allow for awkward syntax.
⚠️ This will very possibly break user workflows, but I think this is …
=> fix(cli): error on out of place run args

docs/repo-docs/reference/run.mdx
The description on these flags wasn't clear enough about what the default is that the flag is meant to be switching on/off. Added it!
👀
=> docs: clarify default daemon usage

.github/ISSUE_TEMPLATE/1-docs.yml
The template was trying to apply a non-existent label. This makes it so the right label gets applied.
=> chore: fix outdated docs issue template label

Cargo.lock, crates/turborepo-lib/src/microfrontends.rs, crates/turborepo-microfrontends/Cargo.toml, crates/turborepo-microfrontends/src/lib.rs
Start factoring in any MFE configs found into task hashes so changes to the config will invalidate any applications that are a part of a MFE setup.
⚠️ We achieve this by adding this to the global cache. This is sub-optimal as it means tasks unrelated to MFEs get invalidated, but we make this temporary trade off in favor of correctness. See TODO for the planned path forward.
Added unit tests, verified that changing a MFE config file will now invalidates all MFE apps:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/front $ turbo_dev --skip-infer microfrontends-example-docs#build --output-logs=hash-only
turbo 2.3.4-canary.1
• Running microfrontends-example-docs#build in 84 packages
• Remote caching enabled
@vercel/microfrontends:build: cache hit (outputs already on disk), …
```
=> fix(mfe): factor in configs to hashes

docs/repo-docs/crafting-your-repository/structuring-a-repository.mdx
I was helping a user and realized that this section describes the intended behavior, but doesn't say why. Providing that context is helpful to build up a justification for why this behavior isn't supported.
👀
=> docs: provide reasoning on why Turborepo doesn't support nested workspaces

.github/workflows/turborepo-test.yml, cli/turbo.json, crates/turbo-trace/src/tracer.rs
Enable sccache for building the turbo binary in integration tests.
This should provide a speedup for our integration tests:
- [Normal run](https://github.com/vercel/turborepo/actions/runs/12209798573?pr=9545):
- Ubuntu: 12m 17s
- macOs: 25m 45s
- Windows: 26m 13s
- [Run with sccache](https://github.com/vercel/turborepo/actions/runs/12245380679?pr=9597)
- Ubuntu: 7m 8s 
- macOs: 18m 44s 
- Windows:  23m 31s 
(I quick double checked that none of these were `turbo` cached, but they did have a warmed `sccache` so external dep changes will degrade speed)
=> chore(ci): enable sccache for integration tests

examples/basic/apps/docs/package.json, examples/basic/apps/web/package.json, examples/basic/packages/eslint-config/package.json, examples/basic/pnpm-lock.yaml
Upgrading the `basic` example (and `create-turbo`) to [Next.js 15.1](https://nextjs.org/blog/next-15-1).
=> chore(examples): update `basic` example to Next.js 15.1

crates/turborepo-lib/src/cli/mod.rs
=> fix(watch): watch command require tasks argument

crates/turborepo-lib/src/microfrontends.rs, crates/turborepo-lib/src/task_graph/visitor/command.rs, crates/turborepo-microfrontends/src/lib.rs
We had a bug where if there were multiple MFE configs that contained the same application we would defer to config name ordering for which config would get selected. This PR makes it so we now select the newest versioned configuration.
⚠️ Fix a bug I introduced in https://github.com/vercel/turborepo/pull/9582 where I cast the relative unix path to a basic `str` and I then misused it with `join_component`. 
Updated and added unit tests. Tested on a repo with multiple overlapping configs with different versions.
=> fix(mfe): multiple versions

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/popup.rs
While task selection pinning is convenient when tasks are changing order and status, it can sometimes get in the way. 
When you haven't selected a task yet (e.g. pressed one of ↑/↓/j/k), you are in an _unpinned_ state. You'll always be looking at the first task in the list, even as they shuffle around in order. When you do press one of those keys, you end up in a _pinned_ state such that the task you selected continues to be selected.
This feels good until you select a task, and then want to "exit" that pinned state and let tasks flow around beneath your cursor again. In this PR, we solve this problem, adding a keybind for `p` that toggles the pinned/unpinned state of your selection.
Pick out your favorite Turborepo, run tasks with the TUI, and try out this new feature.
=> feat(tui): bind to toggle task selection pinning

crates/turborepo-lib/src/cli/error.rs, docs/repo-docs/crafting-your-repository/understanding-your-repository.mdx, docs/repo-docs/reference/watch.mdx, turborepo-tests/integration/tests/no-args.t
Additional fixes for https://github.com/vercel/turborepo/pull/9598
- Unified output texts from `some potential ones to run` to `some potential ones` across both run and watch commands when no tasks are provided. Let me know if there is a better way!
- Added documentation and tests.
Added integration tests.
=> fix(watch): fix output text when no tasks are provided

crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/popup.rs
This PR changes the binds for scrolling logs from `CTRL+P` and `CTRL+N` to `u` and `d`. I'm learning into simple here, both by making the bind a simple one-tap instead of a chord and matching up with the mnemonic device of "**u**p and **d**own".
`CTRL+n` and `CTRL+p` are familiar to power users of a few terminal tools, but I personally don't see this as a great justification for our tool, which gets used by a much broader audience. I'm erring on the side of simplicity, but happy to hear dissent/pushback/other thoughts.
Additionally, I've updated our UI hints slightly:
- Added the hints for these binds to the logs pane
- Separating binds using spaces instead of commas
Pick out your favorite Turborepo and try it out!
=> feat(tui): change binds for log scrolling and add UI hints

CONTRIBUTING.md, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/package_manager/mod.rs, turborepo-tests/integration/tests/invalid-package-json.t, turborepo-tests/integration/tests/package-manager.t
Fixes #9611
Field `packageManager` of `package.json` can now use a custom URL, e.g. `npm@https://registry.npmjs.org/some-npm-fork/-/some-npm-fork-1.0.0.tgz`
(I also fixed some minor formatting issues in `CONTRIBUTING.md`)
Added both an integration test and a unit test.
=> fix(package-manager): allow custom URL for `packageManager` version

README.md, docs/repo-docs/community.mdx, docs/repo-docs/index.mdx, packages/turbo/README.md
We're migrating from Discord to Vercel Community for a variety of reasons. This PR changes the links to go to the new target.
=> chore: change Discord links to Vercel Community

crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/dep_splitter.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-repository/src/package_graph/yarnrc.rs, crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-repository/src/package_manager/npmrc.rs, crates/turborepo-repository/src/package_manager/yarnrc.rs
This implements a fix for #8989 to honour `enableTransparentWorkspaces` in a yarn config. 
The patch folds the config setting into the existing `link_workspace_packages` npm settings as they're equivalent.
Massive Kudos to @me4502 as she helped throughout the implementation process with testing and figuring things out.
* Use https://github.com/me4502/turborepo-reproduction reproducer
* Run compiled turbo build against workspace `a`: `turborepo/target/debug/turbo build --force --skip-infer --no-daemon --filter a`
=> fix(repository): honour handleTransparentWorkspaces setting in Yarn/Berry

crates/turborepo-env/src/lib.rs
Include `VERCEL_ENV` as an environment variable that affects the global hash. Can be opted out by specifying `!VERCEL_ENV` in `globalEnv`.
Unit test, quick manual test as a smoke test:
```
[0 olszewski@chriss-mbp] /tmp/env-var $ VERCEL_ENV=dev turbo_dev --skip-infer build --output-logs=hash-only --ui=stream
turbo 2.3.4-canary.4
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
web:build: cache miss, executing 7a2bad92132801df
docs:build: cache miss, executing 744d362ee9e1eb1b
Tasks:    2 successful, 2 total
Cached:    0 cached, 2 total
Time:    13.166s 
[0 olszewski@chriss-mbp] /tmp/env-var $ VERCEL_ENV=dev turbo_dev --skip-infer build --output-logs=hash-only --ui=stream
turbo 2.3.4-canary.4
• …
```
=> chore(env): add VERCEL_ENV into default global env map

examples/basic/packages/eslint-config/package.json, examples/basic/pnpm-lock.yaml
It appears I missed adding this dependency when I worked through getting this example moved to ESLint v9. Getting it added in here.
=> fix(examples): add missing ESLint dependency

examples/basic/README.md, examples/with-berry/README.md, examples/with-docker/README.md, examples/with-gatsby/README.md, examples/with-nestjs/README.md, examples/with-npm/README.md, examples/with-rollup/README.md, examples/with-vue-nuxt/README.md, examples/with-yarn/README.md
=> feat(examples): utm source

CONTRIBUTING.md
When setting up the project, `cargo build` resulted in an error.
Perhaps this PR can clear some confusion for new devs in project.
=> docs: mention capnp in the dependencies

crates/turborepo-lib/src/run/watch.rs
Fixes: https://github.com/vercel/turborepo/issues/9538
The `WatchClient::new` already lists packages as a part of `start_ui`.
Therefore, an additional prelude print in `WatchClient::start` appears redundant.
1. setup a [devturbo alias](https://github.com/vercel/turborepo/blob/main/CONTRIBUTING.md#manually-testing-turbo)
1. clone https://github.com/remotion-dev/remotion
1. run `devturbo watch make`
=> fix: packages listed twice in watch mode

docs/repo-docs/guides/tools/docker.mdx
Hi everybody! I'm learning Turborepo and I think there's an incorrect example in the Docker guide.
To reproduce the issue I just created a new repository and runned the `turbo prune` command. In this case, `docs` app is equivalent to `api` app.
```
npx create-turbo@latest
npm install turbo --global
turbo prune docs --docker
```
It's my first time opening a PR here, please let me know if I should do something different! Thanks
=> docs: add missing `api` folder in `turbo prune api --docker` example

docs/repo-docs/crafting-your-repository/managing-dependencies.mdx
We've gotten reports before about the documentation being wrong when it's actually an issue with a package manager behaving in a bizarre way or a specific setting for a package manager not working with the strategy proposed in the documentation.
We won't be able to document every edge case or odd behavior of every package manager's module resolution algorithm, so I'd prefer to make mention of this in the docs.
We do our best. 😬
👀
=> docs: mention module resolution differences for package managers

crates/turborepo-lib/src/task_graph/visitor/mod.rs, docs/repo-docs/messages/recursive-turbo-invocations.mdx, turborepo-tests/integration/tests/recursive-turbo.t, turborepo-tests/integration/tests/run/missing-tasks.t
Closes #9224 
This is a state that you can get into two ways:
- Genuinely configuring their way into a loop with misconfigured scripts and tasks
- Accidentally misconfiguring their package manager Workspace
- In some misconfigurations, the Workspace will look like a single-package Workspace, but the previous iteration of our error message didn't give any hints about this.
Either way, we should be providing an informative error message, so this PR provides a message that caters to both situations. We'll need a more verbose explanation, so an error link has been added here, as well.
Delete `pnpm-workspace.yaml` from `create-turbo`, remove `turbo` from `devDependencies`, re-run package manager installation, and try to run `turbo build`. You should be greeted by this new and improved error …
=> docs(errors): improve error message for recursive calls

crates/turborepo-lib/src/query/external_package.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/run/scope/change_detector.rs, crates/turborepo-lockfiles/src/berry/mod.rs, crates/turborepo-lockfiles/src/bun/mod.rs, crates/turborepo-lockfiles/src/lib.rs, crates/turborepo-lockfiles/src/npm.rs, crates/turborepo-lockfiles/src/pnpm/data.rs, crates/turborepo-lockfiles/src/yarn1/mod.rs, crates/turborepo-repository/src/change_mapper/mod.rs, crates/turborepo-repository/src/package_graph/mod.rs
Add `added` and `removed` fields for lockfile changes to show exactly why a workspace package was marked as changed due to a lockfile change.
```
query {
affectedPackages() {
length
items {
name
reason {
... on LockfileChanged {
added {
items {
name
}
}
removed {
items {
name
}
}
}
}
}
}
}
```
Results:
```
...
{
"name": "@repo/package",
"reason": {
"added": {
"items": []
},
"removed": {
"items": [
{
"name": "tslib@2.7.0"
}
]
}
}
},
```
=> feat(query): add lockfile package changes to `affectedPackage`

docs/repo-docs/guides/tools/playwright.mdx
Guide on how to use Playwright in Turborepo.
👀
=> docs: guide for Playwright

docs/repo-docs/core-concepts/package-and-task-graph.mdx
In https://github.com/vercel/turborepo/issues/8806, it was mentioned that we should mention `--graph` on the page where we talk about graphs - so let's do that!
=> docs: mention --graph on graphs page

CONTRIBUTING.md, crates/turborepo-errors/src/lib.rs
To make it easier to test out the links we supply in our error messages, this PR lets us supply a base URL of our own choosing so you can point errors at places like `http://localhost:3000` or a preview build of `turbo.build`.
You can try this out yourself with:
```bash
TURBO_SITE="http://localhost:3000" cargo build
```
=> feat: optional `TURBO_SITE` environment variable at compilation time for development

CONTRIBUTING.md
This PR improves the file via the use of language fences, ensuring that the GFM pre-processor will highlight the code correctly.
=> chore: add missing language fences to CONTRIBUTING.md

docs/repo-docs/guides/tools/typescript.mdx
Corrected a minor typo in the docs/repo-docs/guides/tools/typescript.mdx file of the documentation. This update ensures better readability and accuracy for users.
No specific testing is required, as this is a simple documentation update.
To verify the change:
Navigate to docs/repo-docs/guides/tools/typescript.mdx.
Confirm that the typo has been corrected and the updated text appears as expected.
=> docs: fix typo in typescript.mdx of repo-docs

.github/workflows/test-js-packages.yml
This'll make the execution time of this specific action faster, as it has to create and run less script files.
=> chore: merge `summary` into a single step

docs/repo-docs/guides/tools/shadcn-ui.mdx
shadcn/ui recently added [experimental support for monorepos](https://ui.shadcn.com/docs/monorepo), so let's make a pointer for folks who come to Turborepo first.
👀
=> docs: guide for shadcn/ui

crates/turborepo-lib/src/task_graph/visitor/command.rs
The standard naming for microfrontends does not have a hyphen. This updates Turborepo to look for the binary without the hyphen.
=> feat(mfe): remove hyphen from microfrontends binary name

docs/repo-docs/core-concepts/remote-caching.mdx
Making sure folks know Remote Cache is free to use! Got a few questions about this so trying to surface it more.
=> docs: mention free remote caching earlier on page

crates/turborepo-lib/src/opts.rs
Fixes #9681
We were setting remote cache items to whatever the value of `remoteCache.enable` was. This incorrectly re-enabled parts of the cache that had previously been disabled. The fix is to only care if users explicitly disable remote caching, this works since if `remoteCache.enable` isn't specified it is assumed to be `true`.
Added failing unit test in first commit, it passes after the second commit.
=> fix(cache): no longer let remoteCache.enable override force

docs/repo-docs/core-concepts/internal-packages.mdx
The comma was preventing the actual highlighting and causing it to print to the content.
=> docs(fix): correct line highlighting by removing extra comma

crates/turborepo-cache/src/config.rs, crates/turborepo-lib/src/cli/mod.rs
Fixes #9699
Added some small unit tests to verify how the `--cache` flag gets parsed.
=> fix(cache): suggest proper --cache flag for --remote-cache-read-only

crates/turborepo-lib/src/config/env.rs
Previously we would erroneously warn users that `TURBO_REMOTE_ONLY` was being deprecated even if the correct `TURBO_CACHE` was also present. This happened because we have `TURBO_FORCE` erase caching behavior and this was happening before we checked if `TURBO_REMOTE_ONLY` had a matching `TURBO_CACHE` declaration. The fix is just doing that check before doing the force override.
Before
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vercel/turborepo $ TURBO_FORCE=1 TURBO_REMOTE_ONLY=1 TURBO_CACHE=remote:rw turbo_dev @turbo/t
ypes#build > /dev/null                                                                                                                      
WARNING  No locally installed `turbo` found. Using version: 2.3.4-canary.6. …
```
=> fix(cache): avoid warning if TURBO_FORCE, TURBO_REMOTE_ONLY, and TURBO_CACHE

packages/turbo-types/schemas/schema.json, packages/turbo-types/schemas/schema.v2.json, packages/turbo-types/src/types/config-v2.ts
Add `interruptible` to `turbo.json` schema
👀
=> chore(@turbo/types): add interruptible to schema

packages/create-turbo/src/transforms/official-starter.ts
We have the repo name hardcoded to identify official examples, but we didn't update the name when we changed the name of the repository many moons ago.
=> fix(create-turbo): correct repo name

crates/turborepo-vt100/src/cell.rs, crates/turborepo-vt100/src/grid.rs, crates/turborepo-vt100/src/row.rs, crates/turborepo-vt100/src/screen.rs, crates/turborepo-vt100/src/tui_term.rs, crates/turborepo-vt100/tests/helpers/fixtures.rs
The crate `tui_term` renders the `vt100::Screen` by [fetching each cell](https://github.com/a-kenji/tui-term/blob/development/src/state.rs#L27) and then filling the `ratatui::buffer:Cell` [with the vt100 cell's contents](https://github.com/a-kenji/tui-term/blob/development/src/vt100_imp.rs#L37).
This leads to the following functions being called once for each cell on the users terminal:
- [`Cell::contents`](https://github.com/vercel/turborepo/blob/main/crates/turborepo-vt100/src/cell.rs#L90) which unnecessarily allocates on every call even though there's a fixed limit to the size of the `str` that could be returned. This PR changes this method to return a `&str` that is constructed from the content bytes. The new helper function `append_char` is basically …
=> perf(vt100): increase render performance for `tui_term` codepath

crates/turborepo-ui/src/tui/clipboard.rs
As discovered in https://github.com/vercel/turborepo/pull/9652#discussion_r1918688510
We could create a zombie process if writing to the clipboard program failed as we handled the write failure without `wait`ing the clipboard process.
We no longer get a lint warning when removing `allow(clippy::zombie_process)`
=> fix(tui): avoid zombie process on clipboard write failure

Cargo.lock, crates/turborepo-fs/Cargo.toml, crates/turborepo-fs/src/lib.rs, packages/create-turbo/src/transforms/official-starter.ts
This PR addresses https://github.com/vercel/turborepo/issues/1292 so that `turbo prune` now respects `.gitignore` patterns so that files excluded via `.gitignore` are properly omitted from the pruned output.
You can test the built CLI against this repository confirming that secret.txt is not added to the output with turbo prune: https://github.com/thebrubaker/turbo-prune-test
=> feat: respect gitignore during turbo prune

examples/basic/README.md, examples/basic/meta.json, examples/design-system/README.md, examples/kitchen-sink/README.md, examples/kitchen-sink/meta.json, examples/non-monorepo/README.md, examples/non-monorepo/meta.json, examples/with-angular/README.md, examples/with-berry/README.md, examples/with-changesets/README.md, examples/with-docker/README.md, examples/with-gatsby/README.md, examples/with-nestjs/README.md, examples/with-npm/README.md, examples/with-prisma/README.md, examples/with-react-native-web/README.md, examples/with-rollup/README.md, examples/with-shell-commands/README.md, examples/with-shell-commands/meta.json, examples/with-svelte/README.md, examples/with-svelte/meta.json, examples/with-tailwind/README.md, examples/with-tailwind/meta.json, examples/with-typeorm/README.md, examples/with-vite/README.md, examples/with-vue-nuxt/README.md, examples/with-yarn/README.md, packages/create-turbo/src/commands/create/index.ts, packages/create-turbo/src/transforms/official-starter.ts, packages/create-turbo/src/transforms/types.ts
The community has been contributing more and more examples as Turborepo usage has grown. This is _so exciting_ for those of us on the core team, but we've had a hard time maintaining so many examples. It's a lot of work to keep up with the breadth of tools that work great with Turborepo, and the JavaScript ecosystem moves fast.
Because of this, we've come up with a strategy so that we can set expectations correctly with the community. We're picking out ~5 examples that we're committing to maintaining as shining representatives of JavaScript monorepo greatness, leaving the rest to be maintained by the community.
We will communicate this directly in `create-turbo` invocations, leaving a note for users when they pick out a community-supported example.
Should not show a `Note` log: …
=> chore(examples): mark core supported examples

cli/Makefile, packages/turbo-types/package.json, packages/turbo-types/turbo.json, packages/turbo/.gitignore, packages/turbo/package.json
Add a new `@turbo/types#copy-schema` task which will copy the current schema into `packages/turbo`. We do this since we explicitly exclude the `turbo` package from our workspace so it's easier to have this hang off of `@turbo/types`.
We then add this task to the `build` target which is a dependency of the `publish-turbo` target which is what gets run on release: https://github.com/vercel/turborepo/actions/runs/12796720464/job/35678219119#step:11:2
Resolves #7466
Do a test run of the release and make sure we end up running the new `copy-schema` task. [Started here](https://github.com/vercel/turborepo/actions/runs/12812613189), will take a sec to get to the point in the release where we hit this codepath.
You can see schema gets copied into the `turbo` package …
=> chore(turbo): include schema in turbo package

crates/turborepo-env/src/lib.rs, crates/turborepo-lib/src/task_graph/visitor/mod.rs, crates/turborepo-lib/src/task_hash.rs
Fixes https://github.com/vercel/turborepo/issues/9659
Fixing required a fair amount of code shuffling before it can be addressed. This PR is a collection of prework that I did before fixing the issue that will probably be easier to review in isolation. The final commit is the actual fix.
The important moves in the commit is moving some logic out of `TaskHasher` and into `turborepo-env` crate where we can easily test this logic without constructing a full `Run`.
Each commit is a small incremental change to this codepath that shouldn't have any behavioral changes until the final commit.
Added unit tests for pass through env creation, existing integration tests that cover this behavior as well.
Quick manual test:
```
[0 olszewski@chriss-mbp] /tmp/signal2 $ NODE_ENV=foobar turbo_dev …
```
=> fix(env): allow `passThroughEnv` to negate built ins and `globalPassThroughEnv`

docs/repo-docs/getting-started/add-to-existing-repository.mdx
Fix misplaced backticks for link
=> fix(docs): correct backticks causing broken links

Cargo.toml, crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-ci/src/lib.rs, crates/turborepo-lib/src/boundaries.rs, crates/turborepo-lib/src/commands/link.rs, crates/turborepo-lib/src/engine/mod.rs, crates/turborepo-lib/src/framework.rs, crates/turborepo-lib/src/gitignore.rs, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/rewrite_json.rs, crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/summary/spaces.rs, crates/turborepo-lib/src/task_graph/visitor/command.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lockfiles/src/yarn1/ser.rs, crates/turborepo-repository/src/package_graph/builder.rs, crates/turborepo-repository/src/package_graph/dep_splitter.rs, crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/debouncer.rs, crates/turborepo-ui/src/tui/term_output.rs, crates/turborepo-ui/src/wui/query.rs, crates/turborepo-vt100/src/screen.rs, rust-toolchain.toml
- map_or -> is_some_and in case of bool operations
- add `[workspace.lints.rust]` to ignore `cfg(debug_assertion)` warning
=> chore: upgrade to Rust 1.84.0

Cargo.lock, crates/turborepo-fs/Cargo.toml, crates/turborepo-fs/src/lib.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/prune.rs, docs/repo-docs/reference/prune.mdx
Closes #9789
Adds a flag for opting out of respecting `.gitignore`. If you want to copy over files that are ignored by `git` you can now pass `--use-gitignore=false` to `turbo prune`.
Added unit tests. Quick manual test:
```
[0 olszewski@chriss-mbp] /tmp/turborepo-gitignore-bug $ stat apps/web/.turbo       
16777234 160702923 drwxr-xr-x 6 olszewski wheel 0 192 "Jan 24 14:05:04 2025" "Jan 24 14:05:04 2025" "Jan 24 14:05:04 2025" "Jan 24 14:05:04 2025" 4096 0 0 .turbo
[0 olszewski@chriss-mbp] /tmp/turborepo-gitignore-bug $ turbo_dev --skip-infer prune web --use-gitignore=false
turbo 2.3.4
Generating pruned monorepo for web in /private/tmp/turborepo-gitignore-bug/out
- Added @repo/eslint-config
- Added @repo/typescript-config
- Added @repo/ui
- Added web
[0 olszewski@chriss-mbp] …
```
=> feat(prune): add `--use-gitignore` flag

.github/workflows/turborepo-test.yml
I can't explain why, but switching the ordering of these globs finally does what I want. Previously, the right behavior would only happen for `docs/**` but not `examples/**`. It appears switching the order does what I'm looking for.
On my fork, you can see this change [here](https://github.com/anthonyshew/turborepo/blob/anthonyshew-patch-14/.github/workflows/turborepo-test.yml#L56C1-L56C43).
I've tested with a hand-rolled matrix of file changes on separate PRs:
- https://github.com/anthonyshew/turborepo/pulls
These should match our expectations of what should run when. Please gut check me!
=> ci: correctly ignoring in turborepo-test.yml

Cargo.lock, crates/turborepo-paths/src/absolute_system_path.rs, crates/turborepo-paths/src/anchored_system_path_buf.rs, crates/turborepo-repository/src/change_mapper/mod.rs, packages/turbo-repository/README.md, packages/turbo-repository/__tests__/affected-packages.test.ts, packages/turbo-repository/__tests__/fixtures/monorepo/apps/app/package.json, packages/turbo-repository/__tests__/fixtures/monorepo/package.json, packages/turbo-repository/__tests__/fixtures/monorepo/pnpm-lock.yaml, packages/turbo-repository/js/index.d.ts, packages/turbo-repository/rust/Cargo.toml, packages/turbo-repository/rust/README.md, packages/turbo-repository/rust/src/lib.rs
This PR passes lockfile change information to the `turbo-repository` NAPI interface.
Run `pnpm test` from `packages/turbo-repository` to see the new test pass, which validates lockfile changes.
=> feat: makes `affectedPackages` lockfile aware

crates/turborepo-lib/src/microfrontends.rs, crates/turborepo-lib/src/task_graph/visitor/command.rs, crates/turborepo-microfrontends/src/configv1.rs, crates/turborepo-microfrontends/src/lib.rs, crates/turborepo-repository/src/package_manager/mod.rs
Adds support for users specifying a custom proxy command instead of the default MFE one. This is done by having a `proxy` script on the default application. 
The interface the proxy must implement:
- First argument is the path to the `microfrontends.json` file
- Next arguments are `--name` and a list of applications currently being run. These will be a subset of the `applications` section in the passed configuration file.
The schema that Turborepo will require of `microfrontends.json` is very permissive to allow for extensibility:
- `version?: string` field can be omitted or must be `"2"` explicitly
- `applications: {[string]: { dev?: string, local?: { port:?: number } } }`: keys must match the `name`s in `package.json`
To use the provided `@turbo/proxy` implementation, …
=> feat(mfe): support user specified local proxy

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/run/watch.rs
Turn on caching in watch mode. Not completely stable but worth trying.
=> feat(watch): caching

packages/turbo-repository/rust/Cargo.toml
The recent Rust version bump started yielding these errors locally and on CI:
This is due to the `#[napi]` proc macro expanding to include a reference to a `noop` feature. To silence this lint we forward this feature to `napi-derive`: [src](https://github.com/napi-rs/napi-rs/blob/main/crates/macro/Cargo.toml#L20).
`cargo clippy` should now produce no warnings
=> chore(@turbo/repository): silence noop lint

Cargo.lock, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/process/child.rs, crates/turborepo-ui/Cargo.toml, crates/turborepo-ui/src/tui/input.rs
`winapi` is abandoned and had no updates since 2020, while `windows-sys` is supported by Microsoft. also updated `winapi-util` to use `windows-sys` too
=> fix(deps): use windows-sys instead of winapi

packages/create-turbo/src/transforms/official-starter.ts, packages/turbo-utils/src/createProject.ts, packages/turbo-utils/src/examples.ts
Fixes some logic that was introduced https://github.com/vercel/turborepo/pull/9708 that allows classifying official examples.
=> feat(create-turbo): fix official examples

Cargo.lock, crates/turborepo/Cargo.toml
it was added in #3671 but wasn't used
=> fix(deps): remove unused `winapi` for turborepo

crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/query/package.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__basic_monorepo_get_packages_with_less_than_1_dependents_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__basic_monorepo_get_packages_with_less_than_2_dependents_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__basic_monorepo_get_packages_with_more_than_0_dependents_(npm@10.5.0).snap
Fixing a very dumb bug with predicates in `query`
Added a test for predicates
=> fix(query): predicate bug

packages/create-turbo/src/commands/create/index.ts
The note was being printed after the success and it looked a little funny.
Additionally, it was the only thing being printed that was more than ~60 columns wide so it looked funny. Some `\n`'s clean that up nicely.
=> chore: move `create-turbo` community note and format it better

crates/turborepo-ci/src/vendors.rs
Properly classify azure devops as a CI env
Based on:
* https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables
* https://stackoverflow.com/questions/77214920/does-azure-set-and-expose-the-ci-environment-variable
=> feat(turbo): update Azure Devops env

docs/repo-docs/getting-started/examples.mdx, docs/repo-docs/getting-started/index.mdx, docs/repo-docs/getting-started/installation.mdx, docs/repo-docs/getting-started/meta.json, docs/repo-docs/getting-started/support-policy.mdx
Sprucing up the way we're handling examples in the docs.
- Dedicated page for starting with an example
- Splits the tables so that we can have a core-maintained section and a community-maintained section
👀
=> docs: new page for examples

crates/turbo-trace/src/import_finder.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__turbo_trace_get_`export_all.js`_with_dependencies_(npm@10.5.0).snap, crates/turborepo/tests/snapshots/query__turbo_trace_get_`export_named.js`_with_dependencies_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/turbo_trace/export_all.js, turborepo-tests/integration/fixtures/turbo_trace/export_named.js
Closes #9828. We now check export statements since they can import from other modules, e.g. `export * from "./foo"`
Added a test for both `export * from "./foo"` and `export { foo } from "./foo"`
=> fix(turbo-trace): check exports

.github/workflows/turborepo-library-release.yml
In a [recent release](https://github.com/vercel/turborepo/actions/runs/13038773591/job/36375503780) of `@turbo/repository` I noticed that on `x86_64-unknown-linux-gnu` is failing checkout with:
```text
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
```bash
docker pull amazon/aws-lambda-nodejs:18
docker run --rm -it --entrypoint /bin/sh amazon/aws-lambda-nodejs:18
```
then run
```bash
ldd --version
```
To verify that the version was indeed 2.26:
```text
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for …
```
=> fix: use an image that supports glibc for @turbo/repository ubuntu

.github/workflows/turborepo-library-release.yml
The pipeline using the `amazon/aws-lambda-nodejs:20` image [is failing](https://github.com/vercel/turborepo/actions/runs/13063935350/job/36452835658).
This is because:
> The Amazon Linux 2023 minimal image uses microdnf as package manager, symlinked as dnf, replacing yum in AL2-based images. Additionally, curl and gnupg2 are also included as their minimal versions curl-minimal and gnupg2-minimal.
> - https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda
```
docker pull amazon/aws-lambda-nodejs:20
docker run --interactive --tty --rm --entrypoint /bin/sh amazon/aws-lambda-nodejs:20
```
then run
```
microdnf install -y gcc gcc-c++ git
curl https://sh.rustup.rs -sSf | bash -s -- -y
npm i -g pnpm@8.9.0
```
=> fix: use microdnf for ubuntu images

docs/repo-docs/getting-started/editor-integration.mdx
Documenting `schema.json` availability in `node_modules` starting in 2.4.
👀
=> docs: `schema.json` in `node_modules`

docs/repo-docs/crafting-your-repository/developing-applications.mdx, docs/repo-docs/reference/configuration.mdx
Document the new TUI keybinds.
👀
=> docs: keybinds for tui

examples/install-all.ts, examples/package.json, pnpm-lock.yaml
=> fix(pnpm): revert lockfile upgrade

docs/repo-docs/guides/tools/eslint.mdx
Replace semicolon with comma in array spread syntax
=> chore(docs): correct syntax error in ESLint configuration example

.github/actions/setup-node/action.yml
Always use latest corepack version regardless of Node version. Specifically unbreak CI as we pick up https://github.com/nodejs/corepack/pull/614
CI passes
=> chore(ci): always use latest corepack version

crates/turborepo-lib/src/run/builder.rs, crates/turborepo-microfrontends/src/configv1.rs, crates/turborepo-microfrontends/src/error.rs, crates/turborepo-microfrontends/src/lib.rs
Make it so any invalid MFE configs no longer fail the process. 
We had this behavior previously for unsupported versions, but it broke somewhere along the lines where we were throwing `InvalidVersions` instead.
Added unit test. Quick manual verification:
```
[0 olszewski@chriss-mbp] /Users/olszewski/code/vapi $ turbo_dev --skip-infer build --dry > /dev/null
turbo 2.4.0
WARNING  Ignoring control-plane-default: Unsupported microfrontends configuration version: 2. Supported versions: ["1"]
```
=> fix(microfrontends): fix handling of unsupported version

.github/dependabot.yml
The `/`s in the branch names make it a little annoying to run `create-turbo` on the branches for the Dependabot upgrades. It's easy to forget to have to use `create-turbo --example-path` rather than just `--example`.
Using `-` for separators is just a slight bit simpler.
=> ci: more usable separator

.github/workflows/turborepo-release.yml, scripts/version.js
Npm requires all published versions to have a dist tag. If we want to backport a fix we don't want to release this under the `latest` or `canary` tag. Instead we should release it under a `v${SPECIFIC_MINOR}` tag if we want to cut another patch under an old version (or `v${SPECIFIC_MAJOR}` for a minor release for a previous major)
This updates what we write to `version.txt` which is what gets used for our [NPM publish](https://github.com/vercel/turborepo/blob/main/cli/Makefile#L2).
[`prepatch` release without an override](https://github.com/vercel/turborepo/actions/runs/13144407776/job/36679014437#step:5:12)
[`prepatch` release with an override](https://github.com/vercel/turborepo/actions/runs/13144412891/job/36679032662#step:5:12)
=> feat(release): allow for overriding npm dist tag

crates/turborepo-lib/src/boundaries.rs
SWC currently cannot parse svelte or vue. Therefore we ignore them when it comes to boundaries, but we do emit a warning for users. Note that we specifically do *not* emit a warning per file, since that could be a lot of warnings. We do however emit per package, but that should hopefully not be too excessive
closes #9874
=> feat(boundaries): ignore svelte and vue files (but warn)

.github/workflows/turborepo-test.yml, examples/basic/apps/docs/package.json, examples/basic/apps/web/package.json, examples/basic/packages/ui/package.json, examples/basic/pnpm-lock.yaml, examples/kitchen-sink/apps/admin/package.json, examples/kitchen-sink/apps/api/package.json, examples/kitchen-sink/apps/blog/package.json, examples/kitchen-sink/apps/storefront/package.json, examples/kitchen-sink/packages/ui/package.json, examples/kitchen-sink/pnpm-lock.yaml, examples/with-svelte/apps/docs/package.json, examples/with-svelte/apps/web/package.json, examples/with-svelte/packages/ui/package.json, examples/with-svelte/pnpm-lock.yaml, examples/with-tailwind/apps/docs/package.json, examples/with-tailwind/apps/web/package.json, examples/with-tailwind/packages/ui/package.json, examples/with-tailwind/pnpm-lock.yaml, package.json, pnpm-lock.yaml, turborepo-tests/helpers/setup_example_test.sh
After working well for a brief moment in time, the examples are inexplicably quite broken somehow. This PR has a good number of fixes to try to unstuck them once again:
- I had to install ESLint into each package to fix pnpm usage. Unfortunately, this isn't in service of making the examples better. Rather, we were getting the ESLint version running from the outer repository when there wasn't an ESLint specified in the repo.
- This PR improves logging with a `tee` for CI debugging. We previously had poor visibility in CI and were getting vastly different behavior between CI and local (still are 😞). The `tee` should help a little.
- We're using a real temp_dir now. This was done to try to fix the aforementioned ESLint issue, but it's probably what we should have been doing anyway before.
- …
=> ci: many examples fixes

Cargo.lock, Cargo.toml, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/query/package_graph.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo/tests/query.rs, crates/turborepo/tests/snapshots/query__basic_monorepo_get_package_graph_(npm@10.5.0).snap
A very basic API for getting your package graph. You can query nodes and edges between those nodes:
```
{
packageGraph {
nodes {      
items {
name
}
}
edges {
items {
source
target
}
}
}
}
```
=> feat(query): studio graph

crates/turborepo-lib/src/run/summary/mod.rs, crates/turborepo-lib/src/run/summary/task.rs, crates/turborepo-lib/src/run/summary/task_factory.rs, turborepo-tests/integration/tests/dry-json/single-package-no-config.t, turborepo-tests/integration/tests/run/single-package/no-config.t
Closes #9903
If caching is disabled, then we don't cache the task logs. We shouldn't display a path to a log file that doesn't exist.
Run a task that doesn't get cached with `--summarize` and make sure that `logFile` isn't present:
```
[0 olszewski@macbookpro] /tmp/summarize-colon-missing-logfile $ turbo_dev --skip-infer colon:command --summarize
turbo 2.4.1-canary.0
• Packages in scope: app-a, app-b, pkg-a, pkg-b, tooling-config
• Running colon:command in 5 packages
pkg-a:colon:command: cache bypass, force executing 71e88464fc594d21
pkg-a:colon:command: 
pkg-a:colon:command: 
pkg-a:colon:command: > colon:command
pkg-a:colon:command: > echo "Colon command!"
pkg-a:colon:command: 
Colon command!
Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
Time: …
```
=> fix(summary): no longer display non existent logfile

.github/workflows/update-examples-on-release.yml, scripts/update-examples-dep.sh
First try at it failed here: https://github.com/vercel/turborepo/actions/runs/13079564971
=> ci: fix examples update workflow

.github/actions/install-global-turbo/action.yml, .github/workflows/turborepo-release.yml
Our release flow installs the most recent version of turbo to run tests even if it's deprecated. This allows that to be overriden so we can still release forward after a bad release.
=> chore(ci): support custom turbo version for ci

crates/turborepo-lib/src/framework.rs, crates/turborepo-lib/src/task_hash.rs, packages/turbo-types/src/json/frameworks.json, packages/turbo-types/src/types/frameworks.ts
Support framework conditional env vars
=> feat(turbo): framework conditionals

.github/workflows/turborepo-test.yml
We're seeing sporadic failures on the `dorny/paths-filter` part, and[ the recommended recourse](https://github.com/dorny/paths-filter/issues/24#issuecomment-841818275) from the workflow author is to add a checkout.
Failures:
- https://github.com/vercel/turborepo/actions/runs/13208878667/job/36878355246
- https://github.com/vercel/turborepo/actions/runs/13205111177/job/36866322671
However, it's notable that it looks like GHA just...does this sometimes?
- https://github.com/actions/checkout/issues/417
- https://github.com/actions/runner-images/issues/9632
- https://github.com/actions/runner-images/issues/9882
CI
=> ci(fix): checkout before doing path filtering

crates/turborepo-lockfiles/src/pnpm/data.rs
Adds pnpm lockfile ignoredOptionalDependencies
I'm unaware if i need to make changes anywhere else, this works as expected in e.g copying lockfile during pruning
Fixes: https://github.com/vercel/turborepo/issues/8959
=> feat: adds pnpm lockfile ignoredOptionalDependencies

crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-auth/src/lib.rs
Adding some tests before I do some bug hunting/fixing.
CI
=> test: add tests for authentication tokens and SSO

.github/workflows/turborepo-release.yml
We can cut down on the time it takes to cut a release by starting to build the binary before tests have run.
For example in [this run](https://github.com/vercel/turborepo/actions/runs/13246084115):
- Rust tests took 8m48s
- Slowest binary build took 15m38s
[Test run](https://github.com/vercel/turborepo/actions/runs/13271787502)
=> chore(release): run tests as we build binary

crates/turborepo-microfrontends/src/lib.rs
TSIA
We were requiring the version to exist in `VersionOnly` schema so we could decide which config schema to use.
I'm assuming I broke this in https://github.com/vercel/turborepo/pull/9883, but it's not immediately obvious to me how.
Added failing unit test for versionless `Config::load_from_dir` call
=> fix(mfe): properly handle versionless configuration

crates/turborepo-repository/src/change_mapper/package.rs
I noticed that this had `"package.json"` when it should have had `"package-lock.json"` and @chris-olszewski made the astute suggestion to use a constant so such an error can't happen again ([here](https://github.com/vercel/turborepo/pull/9950/files#r1954538580)).
Tests should pass.
=> fix: errant lockfile reference

.github/workflows/turborepo-release.yml
We aren't doing any compilation in containers anymore. These configuration options just make it harder to read the workflow.
[Test run](https://github.com/vercel/turborepo/actions/runs/13271668896)
=> chore(release): remove unused container config

crates/turborepo-lib/src/boundaries/mod.rs, turborepo-tests/integration/fixtures/boundaries/apps/my-app/index.ts
Add ability to ignore imports for boundaries by commenting `// @boundaries-ignore` 
Added tests to boundaries fixture
=> feat(boundaries): add ignore directive

crates/turborepo-lockfiles/src/pnpm/data.rs
Closes #9947
```
[0 olszewski@macbookpro] /tmp/pnpmcjs $ turbo_dev --skip-infer prune web
turbo 2.4.2
Generating pruned monorepo for web in /private/tmp/pnpmcjs/out
- Added @repo/eslint-config
- Added @repo/typescript-config
- Added @repo/ui
- Added web
[0 olszewski@macbookpro] /tmp/pnpmcjs $ cd out 
[0 olszewski@macbookpro] /tmp/pnpmcjs/out $ cp ../.pnpmfile.cjs ./
[0 olszewski@macbookpro] /tmp/pnpmcjs/out $ pnpm i --frozen-lockfile
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +452
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 452, reused 452, downloaded 0, added 452, done
devDependencies:
+ prettier 3.5.0
+ turbo 2.4.2
+ typescript …
```
=> fix(prune): preserve pnpmfileChecksum in lockfile

docs/repo-docs/crafting-your-repository/running-tasks.mdx
Add a section in [crafting-your-repository/running-tasks](https://turbo.build/repo/docs/crafting-your-repository/running-tasks) on filtering to include dependencies.
Clarifies the use of `turbo dev --filter=web...` to limit the scope to an app and its dependencies.
N/A
=> docs(repo): add section on filtering to include dependencies

docs/repo-docs/guides/single-package-workspaces.mdx
Add a JSON schema to the `turbo.json` reference in `single-package-workspaces.mdx`, found in the Guides section.
This is useful for newcomers who are setting up Turborepo and learning how to set that file up from this guide - they will fall into the pit of success and have the JSON schema set up.
N/A
=> docs(repo): add JSON Schema to `turbo.json` ref in `single-package-workspaces.mdx`

examples/kitchen-sink/package.json
The kitchen-sink example currently has its check types command set up as "typecheck": "turbo run typecheck" however none of its packages or apps have it set up that way instead utilizing check-types. This causes the following error where none of the type checking jobs run:
This pull request changes the root package.json's check types command to check-types so that all the packages and apps correctly run type checking. This also matches other examples such as basic and with-tailwind.
To test open up the examples/kitchen-sink folder and run yarn check-types you will see the type checking jobs successfully run.
=> fix: check-types in kitchen-sink example

examples/with-shell-commands/README.md
If you run `turbo typecheck` which the documentation currently suggests you get an error that it could not find `typecheck` in project.
This pull request updates the documentation to `type-check` which aligns with what is in the packages and apps.
Go into `examples/with-shell-commands` and run `turbo type-check`
=> fix: documentation for type-check in with-shell-commands example

examples/basic/package.json, examples/with-svelte/package.json
There were a couple examples (basic, with-svelte) that have turbo tasks for type checking, but do not have them in the root package.json. There are other examples like (with-kitchen-sink, with-tailwind) that do include the type checking in the root package.json so this PR standardizes it across the board by adding it to the examples that are missing it. This change would be especially good for the basic package.json so beginners can easily run/find the task.
Open up examples and run `pnpm type-check`
=> chore: add check-types to root package.json if available

crates/turborepo-ui/src/tui/pane.rs
We should only be displaying the interactive message if the underlying task has a `stdin` allowing it to be interacted with.
Added unit test. Quick verified that tasks that aren't interactive don't have the footer text.
=> fix(tui): only display interactive message on tasks with stdin

crates/turborepo-lib/src/task_graph/visitor/output.rs, crates/turborepo-ui/src/lib.rs, crates/turborepo-ui/src/logs.rs
If a task is run without a TTY (e.g. in CI) the logs will be created with LF (`\n`) line endings. The TUI assumes that logs are produced hooked up to a TTY where CRLF (`\r\n`) is used to return the cursor to the first column and move to the next row (`\n` behavior in non-TTY).
This PR adds a log replay method that replays logs with CRLF line endings regardless of what is in the actual file.
Future PR is to refactor this to share code with the standard log replay as I didn't have time to tackle this right at this moment.
Added quick unit test to verify this swaps out LF for CRLF and is a noop if the logs already use CRLF.
Manual Test:
First populate the logs with a non-TTY run:
```
[0 olszewski@macbookpro] /tmp/tui-test $ turbo @repo/ui#build > /dev/null
```
Using `turbo@2.4.2`:
Using …
=> fix(tui): replay all logs sent to tui with forced crlf

docs/repo-docs/reference/link.mdx, docs/repo-docs/reference/login.mdx, docs/repo-docs/reference/system-environment-variables.mdx
Clarifying that you don't need the login configurations, flags, environment variables, etc. unless you're building a server-side solution that can dynamically generate tokens.
👀
=> docs: clarify login url usage

examples/basic/package.json, examples/design-system/package.json, examples/with-changesets/package.json, examples/with-gatsby/package.json, examples/with-nestjs/package.json, examples/with-tailwind/package.json, examples/with-typeorm/package.json, examples/with-vite-react/package.json, examples/with-vite/package.json
This pull request goes through and makes sure each example uses "turbo run _x_" instead of "turbo _x_". I did this as [in the docs](https://turbo.build/repo/docs/reference/run) it says "We recommend using `turbo run` in CI pipelines and `turbo` with global turbo locally for ease of use". In the examples some packages were one way, others the opposite, some mixed. Since these command will be run by proxy by pipelines it would be good to standardize across the board to `turbo run`.
I went through each package where there were changes and ran every command.
=> chore: standardize how turbo is ran in example packages

examples/with-changesets/README.md, examples/with-changesets/package.json
Currently the release job points to the `docs` package. This is incorrect as the package is actually called `@acme/docs` causing the following error:
This pull request changes filter name to `@acme/docs` fixing the job.
This pull request also updates the documentation to reflect the actual package name.
Navigate to the `with-changesets` example and run `pnpm release`
=> fix: package name in with-changesets release job

Cargo.lock, crates/turborepo-auth/Cargo.toml, crates/turborepo-auth/src/lib.rs
When you already have a token but don't have SSO scopes, we were throwing an error that didn't have much information. The error should be more clear now when you are in this state, informing you to use `--force`.
Specifically you could get into this state by doing:
```
turbo login
turbo login --sso-team=my-team
```
I happy-pathed (error-pathed?) this for the specific case I wanted to solve for. I'm not sure if this is accidentally changing the error for other problematic states you can be in.
I'm struggling to write a unit test. Help would be appreciate if you think one would be good for this (I do).
Additionally, here's a before and after:
Before:
```
▲ 👟 turbo on shew/6b0e1
turbo login
turbo 2.4.0
>>> Opening browser to https://vercel.com/turborepo/token?redirect_uri=redacted
>>> …
```
=> feat: better error when not enough scopes for SSO login

docs/repo-docs/getting-started/add-to-existing-repository.mdx
Fixed a grammatical error in the setup message:  
"You now up and running with Turborepo" -> "You're now up and running with Turborepo."
=> fix(docs): correct grammar in turborepo setup message

docs/repo-docs/crafting-your-repository/structuring-a-repository.mdx, docs/repo-docs/guides/tools/typescript.mdx, examples/basic/apps/docs/next-env.d.ts, examples/basic/apps/web/next-env.d.ts, examples/basic/packages/ui/package.json, examples/with-tailwind/packages/ui/package.json
@thdxr kindly pointed out that the wildcard recommendations in our docs weren't matching what he was seeing in his editor. I investigated and am similarly seeing that wildcard recommendations work as one would hope. The last time that I tried this, there was some limit at 10 exports paths or 10 variable exports (my memory is fuzzy). But that appears to be removed now in latest versions of TypeScript with modern settings (which is what the Turborepo docs on other tools always assume).
Additional credit to @baptisteArno who also was pointing this out to me in #9827. I'm going to use this PR since it has a few more spots in docs where things are updated, and has additional updates to our examples. But let the record show that @baptisteArno deserves credits here!
I hand-tested this in my …
=> docs: update TypeScript wildcard recommendations

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/preferences.rs
Fixes #9999
The TUI should function even if we fail at loading preferences. 
Add test to verify that if the preferences file contains invalid JSON a loader is still created. User probably was hitting a perms issue or some other FS issue and not an invalid JSON, but the test is just meant to show we don't crash.
=> fix(tui): no longer error if preferences cannot be read

crates/turborepo-lib/src/cli/mod.rs
Small refactor pulling the boolean condition `should_print_version` into a helper function with the same name. I also decompose the boolean condition into the two relevant states: whether print version is disabled by environment variable, and whether this run of `turbo` is in continuous integration.
I used `enum`s to disambiguate these states, because previously we were negating a negative boolean to produce a positive one, and it would easy during modification to inadvertently produce opposite behavior by forgetting a negation. The enums make it clear which state each of the two relevant conditions are in, and make the final boolean calculation easy to read.
=> chore: refactor `should_print_version` into helper for clarity

crates/turborepo-lib/src/run/scope/change_detector.rs
I was getting confused about why I was seeing this log in a PR and the issue was that I wasn't cloning my repo with enough depth in CI. It would have saved me a little time to have a better log message here.
=> chore(change_detector): improve log message on invalid ref range

docs/repo-docs/core-concepts/remote-caching.mdx
Documents using the `--manual` flag for self-hosting.
👀
=> docs: add `--manual` flag mention to self-hosting section

docs/repo-docs/reference/run.mdx
Minor correction. `--parallel` does not automatically exhibit `--continue` behavior. You would still need to use `--continue` if you desire such behavior.
👀
=> docs: remove --continue mention with --parallel

docs/repo-docs/guides/migrating-from-nx.mdx
@jamesHenry pointed out in https://github.com/vercel/turborepo/pull/10003 that the "Migrating from Nx" doc leaves room to make it sound like the "Why switch?" reasons sound like they come from the Turborepo team. Here, making sure that it's known on the page that that's not the case. These are reasons that come from Nx users looking to switch, brought together on their common themes.
Thanks, James!
=> docs: more insightful leadin for Nx doc

docs/repo-docs/guides/migrating-from-nx.mdx
@jamesHenry pointed out some inaccuracies on the Nx page, so correcting them here! 
I apologize for these. I'm not an Nx expert and, as made more clear in this PR, the sections in the "Why switch?" come from Nx users looking to migrate. I tried my best to bring together their words, but missed the mark. Namely, I learned that Nx's plugins are optional to use and I mis-characterized how Nx's starter templates work.
=> docs: corrections for Nx page

crates/turborepo-lib/src/cli/mod.rs
Refactor to pull the logic for getting a `Command` from `cli_args` into a named helper. 
The `get_command` helper further uses a helper that makes it clear that `Command::Run` is the default if no command is specified when Turborepo is invoked.
There's still some future work to do based on the comment here:
https://github.com/vercel/turborepo/blob/b6a97bdc947f0b4855a1c9051df7eb0295cae39e/crates/turborepo-lib/src/cli/mod.rs#L1250
to make `cli_args` to be non-mutable.
=> chore: extract logic for defaulting to run into helper

crates/turborepo-lib/src/cli/mod.rs
Refactor to replace `map_or` with `map` and `unwrap_or`. The separation of these two steps makes it clear in the code that the `unwrap_or` case is the default, where it was obscured by the density and argument order of `map_or` before.
=> chore: change use of `map_or` to `map` and `unwrap_or` in cli helper

docs/repo-docs/reference/prune.mdx
I received a question about how `pnpm deploy` and `turbo prune` differ and figured I would document my findings since they both server similar purposes.
👀
=> docs(prune): document how prune differs from pnpm deploy

crates/turborepo-lib/src/cli/mod.rs
Refactors the logic in `run` related to setting run flags into a named helper. 
If you're not dealing with `Watch` or `Run`, this logic is a barrier to understanding how `run` works, extracting this logic into a helper makes it easier to read `run`'s logic. 
The `set_run_flags` helper uses the same mutation of `command` that was previously present in the `run` function body, but future work could include removing the necessity for mutation.
=> chore: extract `set_run_flags` logic as named helper

crates/turborepo-lib/src/turbo_json/mod.rs
`turbo watch dev` wasn't working properly with local proxies if they were marked as `persistent` as they would be in a different run than the proxy task.
This isn't a perfect fix as we're introducing the same failure to find locally running dev tasks that *aren't* marked as persistent. 
A few possible follow ups:
- Error on any dev tasks that aren't marked as persistent to ensure the proxy ends up in the same run as the dev tasks.
- (Stretch): Lift requirement to have dev tasks marked as persistent, this would probably require an overhaul of either `watch` or our `Run` abstraction to "share" parts of one run with another.
`turbo watch dev` with a microfrontend should no longer fail to find which locally running apps dev tasks
=> fix(proxy): make proxy task persistent

Cargo.lock, Cargo.toml, crates/turbo-trace/src/tracer.rs, crates/turborepo-lib/src/query/file.rs
Upgrades oxc-resolver and fixes a bug that we found in Windows. We need to canonicalize paths manually since they may be the abbreviated version and that breaks our path equality logic.
=> fix: update oxc-resolver and fix windows bug

docs/repo-docs/reference/run.mdx
Fix minor oversight in #10023 when we reworded the options
N/A
=> docs: fix typo on continue docs

Cargo.lock, Cargo.toml
Reverts vercel/turborepo#9812
Seems this is breaking library release: https://github.com/vercel/turborepo/actions/runs/13531184493/job/37813511248#step:7:353
Test run: https://github.com/vercel/turborepo/actions/runs/13543906840
=> fix(@turbo/repository): revert "chore(deps): update git2 to 0.20.0"

crates/turborepo-repository/src/change_mapper/mod.rs, crates/turborepo-repository/src/change_mapper/package.rs, packages/turbo-repository/__tests__/affected-packages.test.ts, packages/turbo-repository/rust/src/lib.rs
Make sure we keep as much of the default behavior as possible.
We now have a nesting doll sorta structure for change mappers:
```
Most conservative > Least Conservative
Default > DefaultWLockfile > Global
```
=> fix(repository): still assume files not belonging to a package result in a global change

crates/turborepo-lib/src/boundaries/imports.rs, crates/turborepo-lib/src/boundaries/mod.rs, crates/turborepo-lib/src/boundaries/tsconfig.rs, crates/turborepo-lib/src/query/boundaries.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo/tests/snapshots/boundaries__boundaries_get_boundaries_lints_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/boundaries/apps/my-app/tsconfig.json, turborepo-tests/integration/fixtures/boundaries/apps/my-app/types.ts
Support tsconfig path aliases such as:
```json
{
"compilerOptions": {
"paths": {
"@/*": ["./*"]
}
}
}
```
We check if we can resolve the import as a path alias and if so, check the resolved path
Can be reviewed commit by commit
Turns out we already had a test for this in `turborepo-tests/integration/fixtures/boundaries/apps/my-app/types.ts`. Added another import and updated snapshot
=> feat(boundaries): support tsconfig path aliases

turborepo-tests/helpers/setup_integration_test.sh, turborepo-tests/helpers/setup_package_manager.sh
Spun out from https://github.com/vercel/turborepo/pull/10023#issuecomment-2679724673
setup_package_manager.sh exports `PATH`, so we need to source it for the isolated corepack shims to actually get used in tests. Otherwise certain npm integration tests can fail, depending on the global npm version and if corepack's npm shims haven't been explicitly enabled globally. This can lead to false positives and wasted time debugging integration tests locally.
This hasn't been an issue under GitHub Actions, since actions/setup-node is installing the same version of npm (10.5.0) that the tests expect, but could otherwise become problematic down the road.
Fixing this uncovers two new problems around testing under Windows, which this PR also addresses:
- the corepack path needs to be POSIX-ified, …
=> chore: fix corepack wiring in integration tests

turbo.json
After https://github.com/vercel/turborepo/pull/9961 this field is no longer used and produces a warning.
No warning on CI about the spaces id
=> chore(spaces): remove spaces id

turborepo-tests/helpers/setup_integration_test.sh, turborepo-tests/helpers/setup_package_manager.sh
Reverts vercel/turborepo#10044
This seems to be causing failures https://github.com/vercel/turborepo/actions/runs/13571078355/job/37935992392?pr=9995#step:9:1167
Failures seem to be flakey:
[attempt 1](https://github.com/vercel/turborepo/actions/runs/13570184039/attempts/1)
[attempt 2](https://github.com/vercel/turborepo/actions/runs/13570184039/attempts/2)
=> fix: revert "chore: fix corepack wiring in integration tests"

Cargo.lock, Cargo.toml, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/commands/boundaries.rs, crates/turborepo-lib/src/commands/ls.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/commands/run.rs, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/error.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-signals/Cargo.toml, crates/turborepo-signals/src/lib.rs, crates/turborepo-signals/src/listeners.rs, crates/turborepo-signals/src/signals.rs
Prefactors:
- moved signal listening to own crate
- return signal received to subscribers
- support streams instead of single futures for signal sources
PR that prefactors the signals code to prepare for:
- Subscribers getting all signals sent to `turbo`
- Additional signal handlers to be sent transparently to children
There are no behavior changes in this PR. I highly suggest reviewing each commit on its own.
Existing unit tests.
Quick manual verification that existing `SIGINT` behavior remains the same:
```
$ turbo_dev watch build
...
│    Finalizing page optimization  .   Collecting build traces  .
└────>
× Watch interrupted due to signal
```
=> chore(signals): prefactor

examples/with-tailwind/README.md
the next.config.js and tailwind.config.js are now next.config.ts and tailwind.config.ts in the tailwind repository I updated the readme of the repo to correct this
=> docs: update README.md in examples with-tailwind to correctly reference .ts config files instead of .js

Cargo.lock, Cargo.toml
Reverts vercel/turborepo#10045
This was not the straw that broke the camel's back, the introduction of `turborepo-scm` to the [native library](https://github.com/vercel/turborepo/pull/9950/files#diff-74cfbd08b3cb8946fb49f42e0ec3b53a441952c2189730a2fb508026f6d23ec4R21) is what caused the native library release to fail.
=> chore(deps): update git2 to 0.20.0

Cargo.toml, crates/turborepo-lib/Cargo.toml, crates/turborepo-signals/Cargo.toml
Bump `futures` version to match that of `turborepo-lib`
Existing tests
=> chore: unify futures versions

docs/repo-docs/crafting-your-repository/using-environment-variables.mdx
A user mentioned that it was annoying to write out all the various iterations of their `.env` files explicitly. Making sure to mention that you can capture them all at once with a `*`.
=> docs: add explicit mention for capturing multiple .env files

crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/commands/boundaries.rs, crates/turborepo-lib/src/commands/ls.rs, crates/turborepo-lib/src/commands/query.rs, crates/turborepo-lib/src/query/mod.rs, crates/turborepo-lib/src/run/watch.rs
TSIA
👀 All of these error types had existing transparent conversions from `run::Error` so this should match the current behavior if we fail to register a listener.
=> chore(signals): lift error conversion to each command that sets up signal handler

crates/turborepo-filewatch/Cargo.toml, crates/turborepo-filewatch/src/hash_watcher.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-scm/Cargo.toml, crates/turborepo-scm/src/hash_object.rs, crates/turborepo-scm/src/lib.rs, crates/turborepo-scm/src/ls_tree.rs, crates/turborepo-scm/src/manual.rs, crates/turborepo-scm/src/package_deps.rs, crates/turborepo-scm/src/status.rs
We're having failures when trying to cross compile `git2` for the library. This PR gates the `turborepo-scm` functionality that requires `git2` behind a feature flag so the library can depend on the crate without building `git2`.
Existing test suite passes. [Dry run](https://github.com/vercel/turborepo/actions/runs/13639486544/job/38125884886#step:7:347) of library release built
=> chore(scm): gate git2 behind feature flag

Cargo.lock, Cargo.toml, crates/turborepo-fixed-map/Cargo.toml, crates/turborepo-fixed-map/src/lib.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/boundaries/tags.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/mod.rs, crates/turborepo-lib/src/turbo_json/loader.rs
`TurboJsonLoader::load` only took a mutable self reference because we were using `HashMap` to cache the results. This PR changes the data type we use to cache results and removes the exterior mutability.
We move to use a `FixedMap` which has the following properties:
- Only works with the keys provided at construction
- Append only
- Thread safe
I went with this just because the implementation is straightforward and matches our use case since we know all of the possible places a `turbo.json` will be before we start loading them.
Future work can be reworking boundaries code to no longer eagerly load all of the `turbo.json`s at the start of execution.
Existing test suite. Additional unit tests for `FixedMap`
=> chore(turbo_json): remove exterior mutability from loader

packages/turbo-repository/scripts/build.sh, rust-toolchain.toml
Latest `rustup` stopped installing toolchain by default, we need to handle it ourselves. This is a one off to unblock us.
[Turborepo Library Release](https://github.com/vercel/turborepo/actions/runs/13644580496)
=> fix: install nightly toolchain

packages/turbo-repository/scripts/build.sh, rust-toolchain.toml
We discovered that Rust 1.28 release requires us to manually install the toolchain, not just the target.  This command should install both and ensure compatibility.
Running the Turbo Repository Library Release workflow.
=> fix(release): manually install target toolchain

.github/workflows/turborepo-library-release.yml, .github/workflows/turborepo-native-lib-test.yml, packages/turbo-repository/js/index.js, packages/turbo-repository/js/package.json, packages/turbo-repository/npm/linux-arm64-gnu/package.json, packages/turbo-repository/npm/linux-x64-gnu/package.json, packages/turbo-repository/package.json, packages/turbo-repository/turbo.json
Revert #10062 as we need them and now we avoid cross compiling `git2`
[Test run](https://github.com/vercel/turborepo/actions/runs/13644965628)
=> chore(release): add back gnu builds

docs/repo-docs/crafting-your-repository/developing-applications.mdx
Found a documentation error where a package.json code example was incorrectly labeled as turbo.json in the official Turborepo documentation:
- The example contains typical package.json fields like name and scripts section, which are not part of turbo.json schema
- turbo.json typically contains pipeline configurations, not npm package metadata
- This mislabeling could confuse users trying to set up their Turborepo projects
https://turbo.build/repo/docs/crafting-your-repository/developing-applications#watch-mode
=> docs: fix json title for Watch Mode docs

examples/basic/packages/eslint-config/base.js, examples/basic/packages/eslint-config/next.js, examples/basic/packages/eslint-config/react-internal.js
This is a very minor change I noticed when copying the basic example.
The JSDoc annotation for the ESLint flat configs is incorrect, indicating a config object instead of an array of config objects, which prevents the IDE from providing proper autocomplete.
The IDE autocomplete feature allows to very quickly validate the change.
=> docs: fix JSDoc annotation for ESLint flat configs of basic example

crates/turborepo-lib/src/cli/mod.rs, docs/repo-docs/crafting-your-repository/understanding-your-repository.mdx, turborepo-tests/integration/tests/affected.t, turborepo-tests/integration/tests/command-ls.t
This feature is no longer in experimental. We just forgot to remove the warning.
=> chore: remove experimental warning from ls command

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/cli/snapshots/turborepo_lib__cli__test__turbo-watch-build---no-daemon.snap, docs/repo-docs/guides/migrating-from-nx.mdx, docs/repo-docs/reference/run.mdx, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
#10023 added values for the `--continue` flag, but this unintentionally broke commands such as `turbo --continue build` as `build` would be interpreted as a `continue` value
Added failing test for the previous breakage and updated snapshots.
=> fix(cli): no longer attempt to parse task name as continue value

docs/repo-docs/crafting-your-repository/constructing-ci.mdx, docs/repo-docs/guides/ci-vendors/index.mdx, docs/repo-docs/reference/system-environment-variables.mdx
A user mentioned that its unclear what "The account name associated with your repository." means when using Vercel. I added a better description and a deep link to where the value can be found.
👀
=> docs: clarify TURBO_TEAM slug usage

crates/turborepo-lib/src/cli/error.rs, crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/clone.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/diagnostics.rs, crates/turborepo-scm/src/clone.rs, crates/turborepo-scm/src/git.rs, crates/turborepo-scm/src/lib.rs, crates/turborepo-scm/src/ls_tree.rs, crates/turborepo-scm/src/package_deps.rs, crates/turborepo-scm/src/status.rs, turborepo-tests/integration/tests/clone/basic-monorepo.t, turborepo-tests/integration/tests/clone/new-repo.t
Implements `turbo clone`, essentially a small wrapper around `git clone` that does simple optimizations like blobless clones for local development and treeless clones for CI.
Wrote some tests but not convinced they're actually effective. See comments below
=> feat(clone): turbo clone

crates/turborepo-lib/src/opts.rs, turborepo-tests/integration/fixtures/passthrough/.gitignore, turborepo-tests/integration/fixtures/passthrough/apps/my-app/package.json, turborepo-tests/integration/fixtures/passthrough/package.json, turborepo-tests/integration/fixtures/passthrough/turbo.json, turborepo-tests/integration/tests/passthrough-args.t
Closes #10086. Parses the task as a `TaskName` before checking if task matches for passthrough args, to account for tasks being passed `pkg#task`.
Added a test for passthrough args
=> fix: correctly forward passthrough arguments when using pkg#task format

docs/repo-docs/getting-started/add-to-existing-repository.mdx
Refs: [10099](https://github.com/vercel/turborepo/issues/10099)
Adds callout for installation instructions in documentation page.
=> fix: adds callout for installation instructions for PNPM

crates/turborepo-scm/src/manual.rs
We're getting some dead code warning when building `@turbo/repository`:
```
warning: function `git_like_hash_file` is never used
Warning:   --> crates/turborepo-scm/src/manual.rs:12:4
|
12 | fn git_like_hash_file(path: &AbsoluteSystemPath) -> Result<String, Error> {
|    ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: function `to_glob` is never used
Warning:   --> crates/turborepo-scm/src/manual.rs:31:4
|
31 | fn to_glob(input: &str) -> Result<Glob, Error> {
|    ^^^^^^^
warning: function `hash_files` is never used
Warning:   --> crates/turborepo-scm/src/manual.rs:38:15
|
38 | pub(crate) fn hash_files(
|               ^^^^^^^^^^
warning: function `get_package_file_hashes_without_git` is never used
Warning:   --> crates/turborepo-scm/src/manual.rs:59:15
|
59 | …
```
=> chore(scm): gate manual file hash behind git2

crates/turborepo-lib/src/boundaries/tsconfig.rs
Accidentally made it warn when we can't find a tsconfig in *any* directory. Now we only warn for other errors
=> fix(boundaries): unnecessary tsconfig warnings

packages/eslint-config-turbo/index.ts, packages/eslint-config-turbo/package.json, packages/eslint-config-turbo/src/index.ts, pnpm-lock.yaml
In #9976, I erroneously turned the named export from `packages/eslint-config-turbo/index.js` into a default export in `packages/eslint-config-turbo/index.ts`. Users reported the breakage for ESLint v8 projects [here](https://github.com/vercel/turborepo/pull/9978/files#r1974406494).
This PR fixes by turning it back into a named export.
I've hand-tested the fixed export path with the following steps:
1. `npx create-turbo@latest -e https://github.com/vercel/turborepo/tree/39f94e9af2e51504fa268c92011a96fa04f14190/examples/basic` - This is far back enough in history that the example is using ESLint v8.
2. `turbo run build --filter=packages/eslint-config-turbo` on this branch
3. `pnpm pack --pack-destination=your-favorite-destination`
4. In the example, change the dependency in …
=> fix: `eslint-config-turbo` module export

crates/turborepo-repository/src/change_mapper/mod.rs
#10083 missed including `turbo.jsonc` as a global dependency when doing SCM based filters
👀
=> fix(affected): consider turbo.jsonc as a default global dependency

crates/turborepo-lib/src/commands/prune.rs, turborepo-tests/integration/tests/prune/includes-root-deps.t
Realized we weren't considering `jsonc` as a possible source when copying files for `prune`.
Some future work is to make `prune` work with the now exposed `root_turbo_json()` method off of the configuration object, but didn't have time for that refactor at the moment.
Added `turbo.jsonc` test to the prune e2e tests
=> fix(prune): support copying turbo.jsonc

docs/repo-docs/getting-started/support-policy.mdx
Erroneously added this to the Experimental list when I did #10091.
=> docs: remove `ls` from Experimental phase in Support Policy

crates/turborepo-lib/src/boundaries/config.rs, crates/turborepo-lib/src/boundaries/imports.rs, crates/turborepo-lib/src/boundaries/mod.rs, crates/turborepo-lib/src/boundaries/tags.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/parser.rs, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__empty_boundaries.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__empty_tags.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__implicit_dependencies.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__implicit_dependencies_and_tags.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__tags_and_dependencies.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__tags_and_dependencies_2.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__tags_and_dependents.snap, turborepo-tests/integration/fixtures/boundaries/packages/module-package/my-module.mjs, turborepo-tests/integration/fixtures/boundaries/packages/utils/index.jsx, turborepo-tests/integration/fixtures/boundaries/packages/utils/turbo.json, turborepo-tests/integration/fixtures/boundaries/turbo.json
Allow users to allowlist implicit dependencies for boundaries. This is useful in cases where testing libraries or frameworks can inject globals such as `server-only`
Can be reviewed commit by commit
Added test to boundaries. Note the snapshots do *not* change since no errors are produced. To verify stuff is working as intended, try removing the `implicitDependencies` key and note that an error is produced.
=> feat(boundaries): implicit dependencies

packages/turbo-types/schemas/schema.json, packages/turbo-types/schemas/schema.v2.json, packages/turbo-types/src/types/config-v2.ts
Added boundaries config to schema
=> chore: update schema with boundaries

docs/site/components/search-dialog.tsx
Forgot that this variable gets used on the frontend, which means I need to prefix it with NEXT_PUBLIC.
Try search on the preview.
=> fix(docs): prefix environment variable for search dialog

docs/site/content/repo-docs/guides/tools/typescript.mdx
Fixed commas order.
Use a JSON schema tester.
=> fix(docs): fix commas in package exports example

docs/site/content/repo-docs/guides/tools/storybook.mdx
Follow latest Storybook instructions and conventions for setup. Using yarn or pnpm dlx otherwise will only install versions of storybook older than 8.3. Very simple change that uses the `create` command instead
For testing, you could try the two different initiation options:
`pnpx dlx storybook@latest init`
Then verify your installed version, which will show a version older than 8.3. Delete the directory and create a new storybook directory, then run:
`pnpm create storybook@latest` 
Afterwards, the version should show the latest version, either 8.3 or older.
Also just a note, I think it is on storybooks side, but the most recent version of nextjs that they use in their examples is 8.
=> docs: update storybook initiation instructions

crates/turborepo-lockfiles/src/bun/de.rs, crates/turborepo-lockfiles/src/bun/mod.rs
We were not properly handling recursing when traversing the lockfile. Resolving a package would give a `package@version` key instead of the key into the `packages` array. Our `all_dependencies` implementation assumed that we were given the key into `packages`.
This is a little odd as the keys can have different "paths" (keys to the packages object) that map to identical entries. This PR adds a check to verify that the entries are in fact the same package by comparing checksums.
Fixed unit tests and added one with mismatched checksums.
`create-turbo` using bun should no longer display ` WARNING  Unable to calculate transitive closures: No lockfile entry found for '@types/react@19.0.10'`
=> fix(bun): properly handle bun lockfile keys

packages/eslint-config-turbo/src/flat/index.ts, packages/eslint-plugin-turbo/package.json
Fixes builds of the `eslint-config-turbo` package that were failing on type checking.
=> chore: fix types for ESLint package builds

.github/workflows/turborepo-test.yml
This globbing syntax refuses to work how I want it to, no matter how hard I try. I'm just going to swap the order for now so I can work on docs fast without running all our 20 minute checks.
(This will make working on examples slow again, but that's a tradeoff I'm willing to make at this time.)
=> ci: make working on docs faster

docs/site/app/(no-sidebar)/blog/not-found.tsx, docs/site/app/(no-sidebar)/confirm/page.tsx, docs/site/app/_components/footer.tsx, docs/site/app/_components/logos.tsx, docs/site/components/search-dialog.tsx, docs/site/content/extra/governance.mdx, docs/site/content/repo-docs/community.mdx, docs/site/content/repo-docs/crafting-your-repository/understanding-your-repository.mdx, docs/site/content/repo-docs/guides/ci-vendors/github-actions.mdx, docs/site/content/repo-docs/messages/invalid-env-prefix.mdx, docs/site/content/repo-docs/reference/run.mdx, docs/site/content/repo-docs/reference/scan.mdx, docs/site/lib/constants.ts, docs/site/lib/create-metadata.ts, docs/site/scripts/generate-rss.cjs
Swapping out places where things say "Turbo" to be "Turborepo" as we convert the site. When we say "Turbo", we mean `turbo` or "Turborepo".
=> chore(docs): convert 'Turbo' into 'Turborepo'

crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-unescape/src/lib.rs, docs/site/content/repo-docs/reference/configuration.mdx
Microsyntax for file globbing from the workspace root. Our file globs are anchored to packages, but there are use cases where anchoring at the root is more preferable.
Adds `$TURBO_ROOT$` which can be used in task `inputs` and `outputs`. It can only be used at the start of an inclusion/exclusion so `../$TURBO_ROOT$/config.txt` isn't valid usage.
We achieve this by swapping out `$TURBO_ROOT$` as we convert a raw task definition to a usable one. This allows us to not handle this at any later steps since all inputs/outpus are expected to be relative to the package directory.
Added unit tests for:
- Replacing of `$TURBO_ROOT$` with the relative path to the repo root
- Calculation of the relative path to repo root for packages
```
[0 olszewski@macbookpro] /tmp/watch-time $ bat turbo.json …
```
=> feat: workspace root microsyntax

.github/workflows/test-js-packages.yml
See failure on #10168
```
Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```
[source](https://github.com/vercel/turborepo/actions/runs/13862424976/job/38794202787#step:6:461)
Rollup distributes binaries using the same strategy we do so skipping installing optional dependencies skips installing the actual binary.
Will open PR against this one that triggers `eslint-config-turbo#build`: https://github.com/vercel/turborepo/actions/runs/13862902922?pr=10171
=> chore(ci): install optional deps when testing JS packages

docs/site/app/api/remote-cache-minutes-saved/route.ts, docs/site/content/repo-docs/core-concepts/remote-caching.mdx, docs/site/lib/create-metadata.ts, docs/site/package.json, docs/site/scripts/sync-algolia.mjs, pnpm-lock.yaml
Fixes a bug that made the OpenAPI spec inputs not interactive. You can now type into the inputs and it will show up in the snippets for your copy-pasting enjoyment.
=> docs: bump openapi framework version

docs/site/content/blog/turbo-2-0.mdx, docs/site/content/repo-docs/crafting-your-repository/configuring-tasks.mdx, docs/site/content/repo-docs/guides/single-package-workspaces.mdx, docs/site/content/repo-docs/reference/turbo-codemod.mdx
For the verb "run," the past participle is "run," not "ran." Hope it helps! :)
=> docs: fix typos

crates/turborepo-lib/src/commands/prune.rs, crates/turborepo-lockfiles/src/bun/de.rs, crates/turborepo-lockfiles/src/bun/mod.rs, crates/turborepo-lockfiles/src/bun/ser.rs
Resolves https://github.com/vercel/turborepo/issues/9058 and https://github.com/vercel/turborepo/discussions/7456
Building on https://github.com/vercel/turborepo/pull/9783 to add `prune` support for bun. This is a simple implementation that allow turbo to properly prune a `bun.lock` file
Basically, it just creates a new `BunLockfileData` with the filtered dependencies/workspaces and serializes it to `bun.lock` via `serde_json`. This is made simple since the internal layout matches the bun.lock format, so the only special serialization case I had to do was `PackageEntry`. This also required updating the _deserialization_, since it skipped parsing some parts that we need to write back out.
1. Clone https://github.com/mugencraft/turbobun (or any other turbo + bun repo)
2. `bun install …
=> feat(bun): bun prune support

docs/site/content/repo-docs/reference/run.mdx
In our dogfooding, we've learned that this checkout method works great for ensuring `--affected` has the right history available. Performance is good and things work.
=> docs: add checkout optimization for `--affected`

crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/microfrontends.rs, crates/turborepo-lib/src/run/summary/task.rs, crates/turborepo-lib/src/task_graph/mod.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/parser.rs, docs/site/content/repo-docs/reference/configuration.mdx, packages/turbo-types/schemas/schema.json, packages/turbo-types/schemas/schema.v2.json, packages/turbo-types/src/types/config-v2.ts
Make public the feature added in #9504 that allows for pulling in extra tasks into the graph without a `dependsOn` relationship.
Renamed to `with` as it is better than `sibling` since that indicates a shared parent, which isn't required.
Added quick unit test for parsing and error validation.
Basic test:
```
[0 olszewski@macbookpro] /tmp/with-test $ git diff
diff --git a/turbo.json b/turbo.json
index d6a7fe0..35fa9cd 100644
--- a/turbo.json
+++ b/turbo.json
@@ -15,7 +15,8 @@
},
"dev": {
"cache": false,
-      "persistent": true
+      "persistent": true,
+      "with": ["build"]
}
}
}
[0 olszewski@macbookpro] /tmp/with-test $ turbo_dev --skip-infer web#dev --graph
turbo 2.4.5-canary.4
digraph {
compound = "true"
newrank = "true"
subgraph "root" {
"[root] @repo/eslint-config#build" -> …
```
=> feat(turbo json): make `with` public

examples/with-react-native-web/apps/native/package.json, examples/with-react-native-web/packages/ui/package.json, examples/with-react-native-web/yarn.lock
Removed obsolete `@types/react-native` as it has peer deps that might break expo/metro version compatibility and no longer needed.
Resolved issues ([mentioned here](https://github.com/vercel/turborepo/pull/9872#issuecomment-2727301096)) due to the use of obsolete types package.
=> fix(example): remove obsolete @types/react-native from with-react-native-web

crates/turborepo-lib/src/boundaries/config.rs, crates/turborepo-lib/src/boundaries/mod.rs, crates/turborepo-lib/src/boundaries/tags.rs, crates/turborepo-lib/src/query/boundaries.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__implicit_dependencies_and_tags.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__package_rule.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__tags_and_dependencies.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__tags_and_dependencies_2.snap, crates/turborepo-lib/src/turbo_json/snapshots/turborepo_lib__turbo_json__tests__tags_and_dependents.snap, crates/turborepo/tests/snapshots/boundaries__boundaries_tags_get_boundaries_lints_(npm@10.5.0).snap, turborepo-tests/integration/fixtures/boundaries_tags/package-lock.json, turborepo-tests/integration/fixtures/boundaries_tags/package.json, turborepo-tests/integration/fixtures/boundaries_tags/packages/allowed-and-denied-tag/package.json, turborepo-tests/integration/fixtures/boundaries_tags/packages/allowed-tag/package.json, turborepo-tests/integration/fixtures/boundaries_tags/packages/not-allowed-dependency/package.json, turborepo-tests/integration/fixtures/boundaries_tags/packages/package-with-boundaries-rules/package.json, turborepo-tests/integration/fixtures/boundaries_tags/packages/package-with-boundaries-rules/turbo.json
Adds the ability for boundaries rules to be defined in the package `turbo.json`. These rules are specific to that package and are designed to work with code owners so that a package can restrict who imports it.
=> feat(boundaries): package rules

packages/turbo-types/src/json/frameworks.json
#9860
Deployment providers provide environmental variables to be detected.
[Nitro](https://nitro.build) uses this mechanism to auto-detect deployment providers when building.
I have made a handcrafted list of some common items to nuxt and nitro frameworks + `SERVER_*` (nitro supported env).
- aws_amplify: AWS_APP_ID
- azure_static: INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN
- cleavr: CLEAVR
- cloudflare_pages: CF_PAGES
- firebase_app_hosting: FIREBASE_APP_HOSTING
- netlify: NETLIFY
- stormkit: STORMKIT
- vercel: NOW_BUILDER 
- zeabur: ZEABUR
- cleavr: CLEAVR
- render.com: RENDER
> [!IMPORTANT]
> This list will be most likely updated over time, meaning turborepo support will be broken from time to time and need to manually be updated. Nitro uses …
=> fix: update env variables supported by nitro

Cargo.lock, Cargo.toml, crates/turborepo-frameworks/Cargo.toml, crates/turborepo-frameworks/src/lib.rs, crates/turborepo-lib/Cargo.toml, crates/turborepo-lib/src/lib.rs, crates/turborepo-lib/src/run/summary/task_factory.rs, crates/turborepo-lib/src/task_hash.rs
Did this prefactor for a feature that we didn't end up needing, but figured it still was a bit of cleanup.
- Move this logic out of `turborepo-lib`
- Hide framework slug behind a newtype to allow for safe framework lookup by slug
👀 + `rustc`
=> chore(frameworks): move framework logic to new crate

docs/site/content/blog/turbo-2-4.mdx, docs/site/content/repo-docs/reference/watch.mdx
The documentation incorrectly specifies that the `--experimental-write-cache` command is to be used with `turbo run`, while in reality it is supposed to be used in conjunction with `turbo watch`. This PR updates the documentation to reflect this.
=> docs: switch turbo run to turbo watch for --experimental-write-cache

docs/site/content/repo-docs/reference/configuration.mdx
This used to be true, but is no longer true as of (at latest) 1.10.16.
More cache hits! Woohoo!
=> docs: remove stale callout

docs/site/content/repo-docs/core-concepts/remote-caching.mdx
I realized I remove the link to the web-hosted JSON in https://github.com/vercel/turborepo/pull/10172/files#diff-24fd2507ec67403cc099bc4ebb6b0b8ffda016451400a1437548956bb33be770. This brings it back, with some slight reformatting now that we have a human-readable viewer, too.
👀
=> docs: links for OpenAPI spec for both human-readable and JSON

examples/with-nestjs/packages/eslint-config/base.js
```
Error: ESLint configuration in .eslintrc.js » @repo/eslint-config/nest.js » ./base.js » eslint-config-turbo is invalid:
- Unexpected top-level property "default".
```
When I run this example application and use `npm run lint` it will retrun an error:
```
api:lint: Oops! Something went wrong! :(
api:lint: 
api:lint: ESLint: 8.57.1
api:lint: 
api:lint: Error: ESLint configuration in .eslintrc.js » @repo/eslint-config/nest.js » ./base.js » eslint-config-turbo is invalid:
api:lint:       - Unexpected top-level property "default".
api:lint: 
api:lint: Referenced from: /.../packages/eslint-config/base.js
```
My changes fixing issue and there is no more errors:
```
Tasks:    4 successful, 4 total
Cached:    0 cached, 4 total
Time:    1.821s 
```
1. Clone repo
2. `npm i`
3. `npm run lint`
=> fix: unexpected top-level property `default` in `base.js` eslint config

crates/turborepo-lib/src/config/turbo_json.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs
#10083 introduced a bug where we swallow validation errors and end up silently ignoring these workspace `turbo.json` files. This PR fixes that by distinguishing a missing `turbo.json` from a failed read.
The bug stems from the fact that a missing file and a failed read were both errors so `turbo_json.or(turbo_jsonc)` could choose a missing turbo.json error (which is fine, not all workspaces need `turbo.json`s) over a validation error for the file that is present. We replace `.or` with an extremely explicit `match` that goes through all the possible combinations.
Quick manual verification
```
[0 olszewski@macbookpro] /Users/olszewski/code/vercel/turborepo $ turbo_dev build   
WARNING  No locally installed `turbo` found. Using version: 2.4.5-canary.6.
turbo 2.4.5-canary.6 …
```
=> fix(turbo_json): avoid workspace validation errors

crates/turborepo-lockfiles/src/bun/de.rs, crates/turborepo-lockfiles/src/bun/mod.rs, crates/turborepo-lockfiles/src/bun/ser.rs
Resolves https://github.com/vercel/turborepo/issues/9058 and https://github.com/vercel/turborepo/discussions/7456 (again)
When I tested my previous PR (#10175) on another repo, I discovered an issue with a missing dep in the pruned lockfile
To reproduce this in the `with-yarn` example repo:
`cd apps/web && bun install dd-trace`
and
`cd apps/docs && bun install @opentelemtry/api`
Then run prune for `web` and try `bun install --frozen-lockfile` and you'll get this:
```
error: Failed to resolve peer dependency '@opentelemetry/api' for package '@opentelemetry/core'
at bun.lock:1:16974
InvalidPackageInfo: failed to parse lockfile: 'bun.lock'
```
The underlying error is rather straightforward -- it was deserializing most dependencies (`peerDependencies`, `devDependencies`, …
=> fix(bun): deserialize correctly and use optionalPeers

docs/site/content/repo-docs/guides/tools/index.mdx
Add missing shadcn/ui tile to the section's index page.
=> docs: add missing shadcn/ui tile

docs/site/components/docs-layout/docs.client.tsx
Moves the Remote Cache time saved counter below the Table of Contents. Users being able to find their content is more important.
=> docs: move CTA below TOC

crates/turborepo-ui/src/tui/term_output.rs
Breaking up https://github.com/vercel/turborepo/pull/10247 into PRs that only do one thing. This handles the bump for default scrollback length.
Performance was assessed here: https://github.com/vercel/turborepo/pull/10247#discussion_r2021313622
👀
=> feat(tui): bump default scrollback length

crates/turborepo-filewatch/Cargo.toml, crates/turborepo-filewatch/src/fsevent.rs, crates/turborepo-process/Cargo.toml
in #10114 I tried to update turborepo-filewatch, but it failed due to functions being automatically marked as unsafe when using `unsafe extern "C"`. Rust provides a `safe` keyword to fall to previous behavior.
turborepo-process was added recently but it used edition 2021
CI. I don't have an Apple machine :(
=> chore: upgrade turborepo-process and turborepo-filewatch to Rust 2024 edition

docs/site/package.json, packages/create-turbo/package.json, packages/turbo-gen/package.json, pnpm-lock.yaml
Update `proxy-agent` to pick up https://github.com/TooTallNate/proxy-agents/pull/322
Closes https://github.com/vercel/turborepo/issues/8483
```
$ docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy mitmweb --web-host 0.0.0.0
$ NODE_TLS_REJECT_UNAUTHORIZED=0 HTTPS_PROXY=http://localhost:8080 ~/code/vercel/turborepo/packages/turbo-gen/dist/cli.js workspace --copy https://github.com/vercel/turborepo/tree/main/examples/with-tailwind/packages/tailwind-config
```
=> chore: upgrade to `proxy-agent` 6.5.0

.github/workflows/update-examples-on-release.yml
[This workflow](https://github.com/vercel/turborepo/actions/runs/14248783731/job/39936314642)
is complaining that it doesn't have all the history it needs, so hoping that fetching it will help it out?
I don't totally get why this would be the case given that:
1) I works when I do a manual workflow trigger.
2) The first step is to checkout...
🤷
=> ci(fix): ensure history is up to date

.github/release.yml, .github/turbo-orchestrator.yml
Instruct the labeler to mark PRs with conventional commits that are `ci` or `chore`. Then, ignore it when generating release notes.
=> chore: ignore ci and chore PRs in release notes

docs/site/.gitignore, docs/site/app/api/remote-cache-spec/route.ts, docs/site/scripts/generate-docs.mjs
The self-hosted OpenAPI spec is generated from the Vercel Remote Cache spec. However, that there can be spots where the Vercel Remote cache spec has information that the self-hosted spec doesn't need.
This PR introduces some light pre-processing so that we can make the self-hosted spec better for OSS-only users. See https://github.com/vercel/turborepo/pull/10318/files#diff-03cadc255ad9d43cf46b7ed6185da0eba06ef11294de0f9a784274a1863b6aa0R1 for more.
👀 
https://turbo-site-git-shew-240ef.vercel.sh/api/remote-cache-spec now doesn't have `examples` fields, since the Vercel Remote Cache spec has examples specific to Vercel.
This also removes the erroneous example string from https://turbo-site-git-shew-240ef.vercel.sh/docs/openapi/artifacts/download-artifact.
=> docs: improve accuracy for self-hosted OpenAPI spec

docs/site/scripts/generate-docs.mjs
Closes #9217 by adding the response header for `x-artifact-tag` to a successful GET.
=> docs: add response header to OpenAPI spec

docs/site/app/_components/footer.tsx, docs/site/app/_components/not-found-template.tsx, docs/site/components/nav/footer.tsx, docs/site/components/search-dialog.tsx, docs/site/content/docs/community.mdx, docs/site/content/docs/index.mdx, docs/site/content/extra/governance.mdx, docs/site/next.config.ts
The Vercel Community team has moved from `vercel.community` to `community.vercel.com`. This PR moves our links over.
👀
=> docs: use new community domain

crates/turborepo-lib/src/commands/config.rs, crates/turborepo-lib/src/commands/mod.rs, crates/turborepo-lib/src/config/env.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/config/turbo_json.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/turbo_json/mod.rs, docs/site/content/docs/reference/configuration.mdx, docs/site/content/docs/reference/system-environment-variables.mdx, turborepo-tests/integration/tests/config.t, turborepo-tests/integration/tests/persistent-dependencies/10-too-many.t
This adds a couple new ways to configure task run concurrency: 
- A `TURBO_CONCURRENCY` environment variable
- A `concurrency` configuration value in `turbo.json`
These options should follow the same precedence rules for other options which are made available in multiple locations. I think the environment variable is the most valuable to me (IMO), as this would make it a lot easier to turn off or drastically reduce concurrency in CI scenarios with restricted performance, where running multiple test suites at the same time could cause flaky results due to timeouts, or too much resource contention in general scenarios. Being able to specify this in the configuration file is maybe less valuable, but there are situations where it might be desirable.
The `--concurrency` option is obviously …
=> feat: allow specifying concurrency in config / environment

.github/workflows/turborepo-library-release.yml
It seems the nightly version of Zig we were using has fallen off the downloads page. Moving us to the standard 0.14.0 version now that it has been released.
Test run: https://github.com/vercel/turborepo/actions/runs/14456436894
=> chore(@turbo/library): use stable release of zig

examples/basic/packages/ui/turbo/generators/config.ts, examples/with-nestjs/packages/ui/turbo/generators/config.ts, examples/with-npm/packages/ui/turbo/generators/config.ts, examples/with-typeorm/packages/ui/turbo/generators/config.ts, examples/with-vitest/packages/ui/turbo/generators/config.ts, examples/with-yarn/packages/ui/turbo/generators/config.ts, packages/turbo-gen/README.md, packages/turbo-gen/src/generators/custom.ts, packages/turbo-gen/src/templates/simple-js/templates/turborepo-generators.hbs, packages/turbo-gen/src/templates/simple-ts/templates/turborepo-generators.hbs
See: https://github.com/vercel/turborepo/issues/10344
=> docs: replace incorrect generator links (#10344)

docs/site/components/docs-layout/sidebar.tsx
```Refering the Discussion```: [#10328](https://github.com/vercel/turborepo/discussions/10328)
This PR improves the accessibility and user experience of the sidebar folder links by separating the navigation and toggle functionality into distinct interactive elements.
**Key Changes:**
- Separated the folder link and toggle button into distinct elements for clearer interaction patterns
- Added proper `aria-label` attributes for screen readers to indicate expand/collapse actions
- Improved visual feedback with hover states on the toggle button
This is what it was earlier:
https://drive.google.com/file/d/1-XLu9N_nAoksvfLQQlQQndniZFstABaM/view?usp=sharing
And this is how it looks now:
https://drive.google.com/file/d/1YOqaRRn6L-cFq2cgZH5Lg7u5HSx-d6A9/view?usp=sharing
1. **Basic Functionality** …
=> feat(sidebar): improve folder link accessibility and UX

docs/site/app/(sidebar)/docs/[[...slug]]/layout.tsx, docs/site/app/(sidebar)/docs/[[...slug]]/page.tsx, docs/site/components/copy-to-markdown.tsx, docs/site/tsconfig.json
Provides a button for a docs page to be copied to the user's clipboard as markdown, presumably to paste into an LLM.
Try the button!
https://turbo-site-git-shew-454de.vercel.sh/docs/getting-started/examples
=> docs: copy to markdown button

README.md, cli/README.md, examples/design-system/README.md, examples/kitchen-sink/apps/admin/src/app/index.tsx, examples/kitchen-sink/apps/blog/app/routes/_index.tsx, examples/kitchen-sink/apps/storefront/src/app/page.tsx, examples/kitchen-sink/packages/ui/src/link/index.test.tsx, packages/create-turbo/README.md, packages/create-turbo/package.json, packages/create-turbo/src/commands/create/index.ts, packages/turbo-codemod/package.json, packages/turbo-gen/package.json, packages/turbo-ignore/package.json, packages/turbo-releaser/src/native.ts, packages/turbo-repository/js/package.json, packages/turbo-repository/package.json, packages/turbo-telemetry/package.json, packages/turbo-test-utils/package.json, packages/turbo-types/README.md, packages/turbo-types/package.json, packages/turbo-utils/package.json, packages/turbo-workspaces/README.md, packages/turbo-workspaces/package.json, packages/turbo/README.md, packages/turbo/package.json
In #10368, I swapped out the links for the domain, but forgot to get rid of `turborepo.com/repo`, which is a vestigial from when Turbopack was in the repo. Fixing that here.
👀
=> docs(chore): remove `/repo` references from a few places

.github/workflows/lint.yml, crates/turborepo-repository/src/package_manager/berry.rs, crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-repository/src/package_manager/pnpm.rs, knip.jsonc
Fixes #10387 by adding partial support for the new configuration location added in https://github.com/pnpm/pnpm/pull/9121. There will be future work to add additional configuration options that lived in `.npmrc` and `package.json` to the YAML definition.
I highly suggest reviewing the first 2 commits on their own as they are prefactors. They both get a slightly smaller to slimming down the `impl PackageManager` so we can move to an interface instead of a single struct with `match`s for every package manager x version.
Added new unit tests for this behavior, also manually verified behavior change in repro provided in #10387. Note that after this PR the topological `^lint` dependency is correctly applied so the application lints to not start until `@repo/lint` completes.
Before
```
[0 …
```
=> fix(pnpm): read linkWorkspacePackages from pnpm-workspace.yaml

docs/site/next.config.ts, examples/basic/README.md, examples/non-monorepo/README.md, examples/with-berry/README.md, examples/with-gatsby/README.md, examples/with-nestjs/README.md, examples/with-npm/README.md, examples/with-prisma/README.md, examples/with-solid/README.md, examples/with-vitest/README.md, examples/with-vue-nuxt/README.md, examples/with-yarn/README.md, turborepo-tests/integration/fixtures/turbo_trace/README.md
Update several README files in the examples section, fixing the broken links in the Useful links section.
The CLI usage link is broken as well. I wasn't sure of the right page, so I've left it as is. Suggestions welcome! Thank you.
=> docs: fix broken links in useful links section of readme

crates/turborepo-ui/src/tui/term_output.rs
@anthonyshew 
```
[0 olszewski@macbookpro] /Users/olszewski/code/vercel/turborepo $ turbo_dev build -F @turbo/workspaces --ui=tui
WARNING  No locally installed `turbo` found. Using version: 2.5.3-canary.0.
turbo 2.5.3-canary.0
• Packages in scope: @turbo/workspaces
• Running build in 1 packages
┌ @turbo/types#build > cache hit (outputs already on disk), replaying logs 77441397910de3fd 
> @turbo/types@2.5.3-canary.0 build /Users/olszewski/code/vercel/turborepo/packages/turbo
-types
> tsc && pnpm generate-schema
> @turbo/types@2.5.3-canary.0 generate-schema /Users/olszewski/code/vercel/turborepo/pack
ages/turbo-types
> tsx scripts/generate-schema.ts
└────>
┌ @turbo/workspaces#build > cache hit (outputs already on disk), replaying logs 5162f88d2ed536c3 
> …
```
=> feat(ui): remove gutter from persisted task output

crates/turborepo-lockfiles/src/bun/mod.rs
TSIA
`turbo_dev prune` on a bun repo should produce a `bun.lock` that isn't a single line
=> chore(bun): pretty print bun lockfile

docs/site/app/(no-sidebar)/graphics/effortless.tsx, docs/site/app/(no-sidebar)/graphics/providers.tsx, docs/site/app/(no-sidebar)/graphics/remote-caching.tsx, docs/site/app/(no-sidebar)/graphics/sizing-string.ts
The SVGs are client-rendered, so were creating layout shift. This PR puts a div with the same dimensions in their place on the server, preserving sizing.
👀
=> docs(fix): layout shift on home page

.github/turbo-orchestrator.yml
It looks like I'd written this labeller regex wrong. We'll see if it works next time a chore PR rolls through.
=> chore: fix release notes ignore label

Cargo.lock, crates/turborepo-lib/src/shim/mod.rs, crates/turborepo-updater/Cargo.toml, crates/turborepo-updater/src/lib.rs
Small bit of polish to make our update notifier be package manager aware. Defaults to npm.
Manually tested in a Bun repo.
```
▲ 👟 bun on main
dt scan
╭───────────────────────────────────────────────────────────────────────────────────╮
│                                                                                   │
│                Update available v2.4.5-canary.5 ≫ v2.5.3-canary.1                 │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.5.3-canary.1    │
│                 Run "bunx @turbo/codemod@latest update" to update                 │
│                                                                                   │
│              Follow @turborepo for updates: https://x.com/turborepo               │ …
```
=> feat: conditional update notifier message using package manager

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/mod.rs, crates/turborepo-ui/src/tui/scroll.rs, docs/site/content/blog/turbo-2-5.mdx
#10415 Adds momentum-based scrolling to the TUI for a smoother and more natural scroll experience.
1. Run a long-running task that prints many lines, e.g.:
```bashs
perl -E '$i=1; for (1..1500) { say "[$i] " . "=" x int(rand(100) + 1); $i++ }' && read
```
2. Use the TUI to scroll through the output and observe the new scrolling behavior.
=> feat(tui): momentum-based scrolling

docs/site/content/docs/guides/tools/tailwind.mdx, examples/with-tailwind/apps/docs/app/globals.css, examples/with-tailwind/apps/docs/tailwind.config.ts, examples/with-tailwind/apps/web/README.md, examples/with-tailwind/apps/web/app/globals.css, examples/with-tailwind/apps/web/package.json, examples/with-tailwind/apps/web/tailwind.config.ts, examples/with-tailwind/packages/tailwind-config/package.json, examples/with-tailwind/packages/tailwind-config/postcss.config.js, examples/with-tailwind/packages/tailwind-config/shared-styles.css, examples/with-tailwind/packages/tailwind-config/tailwind.config.ts, examples/with-tailwind/packages/tailwind-config/tsconfig.json, examples/with-tailwind/packages/ui/src/gradient.tsx, examples/with-tailwind/packages/ui/tailwind.config.ts, examples/with-tailwind/pnpm-lock.yaml
Found out that JS configurations aren't hip with the kids these days, so switching out the approach. The CSS variables are a bit contrived, but work great for showing off what we're needing to show off.
=> docs(examples): drop JS config from Tailwind example

Cargo.lock, Cargo.toml
Work around for https://github.com/async-graphql/async-graphql/issues/1703
`turbo_dev --skip-infer query` in repo of your choice. GraphiQL IDE should load correctly.
=> fix(query): use patched version of async-graphql

examples/with-svelte/packages/ui/package.json, examples/with-svelte/packages/ui/svelte.config.js, examples/with-svelte/packages/ui/tsconfig.json, examples/with-svelte/pnpm-lock.yaml
Inspired by @DoctorRyner in #10437, a set of changes to make TypeScript work better for the `with-svelte` example.
This set of changes works correctly in my editor.
=> fix(examples): with-svelte example TypeScript

docs/site/content/docs/guides/migrating-from-nx.mdx
The deleted statement was **never** accurate in Nx. We briefly openly explored some alternative solutions and pricing structures for self-hosted caching but this _never_ landed as a requirement in Nx. We took on the feedback loud and clear that our initial thinking was misguided and we changed course _before_ it landed.
We offer a broader array of free cache hosting options than Turborepo, with the OpenAPI spec being the exact equivalent of how Turborepo chooses to approach the problem, you can learn more here:
https://nx.dev/recipes/running-tasks/self-hosted-caching
For this change, I went for the most generous correction I could, but you may decide the overall section is redundant without this key incorrect point.
While I'm here, I'd suggest you run through this guide yourself again …
=> docs: [correction] nx remote caching is free like Turborepo

docs/site/content/docs/crafting-your-repository/managing-dependencies.mdx
Added [pnpm catalogs](https://pnpm.io/catalogs) as another option to keep dependency versions in sync across packages.
None, just docs.
=> docs: added pnpm catalogs

docs/site/content/docs/crafting-your-repository/structuring-a-repository.mdx, docs/site/content/docs/getting-started/add-to-existing-repository.mdx
This PR updates the package.json configuration example in the documentation to include the `workspaces` field, which is necessary for multi-package repositories using Turborepo.
While following this documentation page, I noticed that the package.json example showed how to add the `packageManager` field, but omitted the `workspaces` field. Although this information is later explained at https://turborepo.com/docs/crafting-your-repository/structuring-a-repository#declaring-directories-for-packages, including it in this initial example would make the documentation more consistent and help prevent confusion for new users who are following the steps sequentially.
I've updated the diff example in the "Add a `packageManager` field to root `package.json`" section to show the `workspaces` field …
=> docs: add workspace configuration example to package.json

crates/turborepo-env/src/platform.rs
This PR corrects the link used in a warning when building a project using environment variables without setting them up in `turbo.json`
Fixes #10461
=> fix: correct link to docs in platform-environment-variables warning

docs/site/content/docs/crafting-your-repository/managing-dependencies.mdx
Hey,
In the "Best practices for dependency installation" section, the example command should be updated to align with the "Getting started" tutorial, where the default setup installs the docs/ and web/ apps.
Right now, it references @repo/web, but that package doesn't exist, what we actually have is @repo/ui.
The correct command should be:
```
pnpm install jest --save-dev --recursive --filter=web --filter=@repo/ui --filter=docs
```
Instead of:
```
pnpm install jest --save-dev --recursive --filter=web --filter=@repo/ui --filter=@repo/web
```
(I'm reading the Turborepo docs and testing)
1. Follow the [Getting Started Tutorial](https://turborepo.com/docs/getting-started/installation)
2. Go to [[Best practices for dependency installation](https://turborepo.com/docs/crafting-your-repository/man …
=> docs: Update managing-dependencies.mdx

packages/eslint-plugin-turbo/__tests__/lib/no-undeclared-env-vars/workspace-configs/reload.test.ts, packages/eslint-plugin-turbo/lib/rules/no-undeclared-env-vars.ts, packages/eslint-plugin-turbo/lib/utils/calculate-inputs.ts
Fixes #10140 so that updating the `env` key in `turbo.json` is reflected in ESLint in your editor.
TODO
=> feat: hot-reloading for `no-undeclared-env-vars` ESLint rule

docs/site/content/docs/core-concepts/remote-caching.mdx
Hola my good peeps from Turbo 👋
I'm just adding a little line here to the docs, linking a Turborepo cache server implementation I built a little while ago.
[brunojppb/turbo-cache-server](https://github.com/brunojppb/turbo-cache-server) is a Github Action that can be used throughout your workflows, only requiring a S3-compatible storage.
Let me know. 🤝
=> docs: add community implementation of cache server

docs/site/scripts/sync-algolia.ts
Our script allowed for a custom environment to write to production. Instead, we make sure only the `VERCEL_TARGET_ENV` that is "production" can do so.
=> docs: account for Custom Environments

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/shim/mod.rs, crates/turborepo-lib/src/shim/parser.rs, turborepo-tests/integration/tests/no-args.t, turborepo-tests/integration/tests/turbo-help.t
When a user tries to use `--debug` or `--verbose` as flags, we can make a pretty strong bet that they're trying to get some debug logging from us. In this case, we can supply better direction to the developer.
Before:
```
▲ 👟 turbo on shew/8d2a6
dt anything --debug
× The --debug flag is not supported. Please use --verbosity instead.
│  if you are trying to pass `--debug` as a value, use `-- --debug`.
```
AFTER:
```
▲ 👟 turbo on shew/8d2a6
turbo anything --debug
ERROR  unexpected argument '--debug' found
tip: to pass '--debug' as a value, use '-- --debug'
Usage: turbo <--cache-dir <CACHE_DIR>|--concurrency <CONCURRENCY>|--continue[=<CONTINUE>]|--single-package|--framework-inference [<BOOL>]|--global-deps <GLOBAL_DEPS>|--env-mode [<ENV_MODE>]|--filter <FILTER>|--affected|--output-logs …
```
=> feat: specific error message for potential debugging flags

crates/turborepo-lib/src/turbo_json/parser.rs, turborepo-tests/integration/fixtures/turbo-configs/syntax-error.json, turborepo-tests/integration/tests/bad-turbo-json.t
Fixes #10499
```
[0 olszewski@macbookpro] /tmp/trailing $ turbo build
turbo 2.5.4-canary.0
turbo_json_parse_error
× Failed to parse turbo.json.
╰─▶   × Expected a property but instead found '}'.
╭─[turbo.json:9:5]
8 │       "outputs": [".next/**", "!.next/cache/**"],
9 │     },
·     ─
10 │     "lint": {
╰────
[1 olszewski@macbookpro] /tmp/trailing $ turbo_dev --skip-infer build
turbo 2.5.4
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
```
=> feat(turbo.json): allow for trailing commas

docs/site/content/blog/turbo-1-6-0.mdx, docs/site/content/blog/turbo-1-7-0.mdx, docs/site/content/docs/crafting-your-repository/managing-dependencies.mdx, docs/site/content/docs/getting-started/index.mdx, docs/site/content/docs/getting-started/installation.mdx, docs/site/content/docs/guides/migrating-from-nx.mdx, docs/site/content/docs/guides/single-package-workspaces.mdx, docs/site/content/docs/guides/tools/jest.mdx, docs/site/content/docs/guides/tools/storybook.mdx, docs/site/content/docs/guides/tools/tailwind.mdx
It should be `pnpm add <pkg>` instead of `pnpm install <pkg>`.
`pnpm install` is used to install all dependencies for a project while `pnpm add <pkg>` is used to install a package and any packages that it depends on.
More info (official source):
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
---
`pnpm install <pkg>` does the same as `pnpm add <pkg>` today, but it might stop functioning that way in future versions since the official docs clarify the difference between the two. It might be that `pnpm install <pkg>` was used in past versions, and the PNPM team didn't want to remove support for it right away after introducing `pnpm add <pkg>`.
=> fix(docs): use `pnpm add <pkg>` instead of `pnpm install <pkg>`

docs/site/content/docs/guides/tools/jest.mdx
Fixes #10542
Fixed this small issue which I found when I copy pasted the package.json examples from the Jest docs page. The missing commas caused JSON parsing errors when trying to use the files.
=> fix(docs): missing commas in package.json files of jest docs

examples/with-tailwind/packages/ui/src/styles.css
This PR fixes [vercel/turborepo#10566](https://github.com/vercel/turborepo/issues/10566) by adding the missing Tailwind import to `shared-styles.css` in the `packages/ui` directory of the `with-tailwind` example.
Shared components like `Card` or `Button` had Tailwind classes, but styles were not applied because Tailwind layers were never included.
Added:
```css
@import "tailwindcss";
```
to packages/ui/shared-styles.css.
Tested locally using:
```
pnpm install
pnpm dev --filter=with-tailwind
```
UI components are now styled correctly.
Closes #10566
=> fix(example): add missing Tailwind import to shared ui styles

docs/site/content/docs/guides/ci-vendors/github-actions.mdx
These changes make it slightly clearer that you're meant to use one strategy or the other.
=> docs: clarity for GitHub Actions caching strategies

docs/site/content/docs/crafting-your-repository/configuring-tasks.mdx
Relate to https://github.com/vercel/turborepo/pull/10596, I'm sorry I find this after the PR merged.
The original doc link: https://turborepo.com/docs/crafting-your-repository/configuring-tasks
The command sequence is inconsistent with the illustration.
=> fix(docs): inconsistent turbo command with the illustration

crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/turbo_json/mod.rs, packages/turbo-types/schemas/schema.json, packages/turbo-types/schemas/schema.v1.json, packages/turbo-types/schemas/schema.v2.json, packages/turbo-types/src/types/config-v2.ts
We want to smooth migration paths for users when we introduce functionality with breaking changes. This can be difficult with point-in-time majors that might force a user to make many breaking changes at once.
Instead, we can introduce the concept of "future flags" to allow you to opt into breaking changes early. As a user, you get to have more control over when you adopt breaking changes. As a core team, we get more freedom to iterate, resulting in faster feedback cycles with users.
This PR only introduces the flag to the parser, not adding any flags quite yet. This key is only allowed in root `turbo.json`s.
Added some tests. I also tried it out manually (and trivially). It worked how I'd hoped.
=> feat: opt into breaking changes and pre-stable features early with `turbo.json` configuration

.github/workflows/turborepo-test.yml, packages/turbo-types/schemas/schema.v2.json
In https://github.com/vercel/turborepo/pull/10590, I edited the JSON schema directly, which [isn't the right way](https://github.com/vercel/turborepo/pull/10590#discussion_r2171962005).
This PR introduces a CI check that I (and others) can't make this sort of mistake in the future.
[This commit](https://github.com/vercel/turborepo/pull/10609/commits/3108ad0c57bfbeccfb60b87e7115b3398444e1de) shows a failure because I added a `test` key to the schema (and malformatted it in the process).
=> ci: ensure turbo-types schemas are in sync

examples/with-nestjs/apps/web/tsconfig.json
Removes duplicate Next.js TypeScript plugin configuration from `examples/with-nestjs/apps/web/tsconfig.json`.
The `"next"` plugin was configured in two places:
- ✅ `packages/typescript-config/nextjs.json` (shared config)
- ❌ `apps/web/tsconfig.json` (duplicate)
Since the app already extends the shared config, the duplicate plugin definition is unnecessary.
**File:** `examples/with-nestjs/apps/web/tsconfig.json`
**Removed:**
```json
"compilerOptions": {
"plugins": [
{
"name": "next"
}
]
}
```
The plugin is already inherited from `@repo/typescript-config/nextjs.json`.
=> refactor(examples): remove duplicate Next.js plugin from app tsconfig files

crates/turborepo-updater/src/lib.rs
Optimizes the `should_skip_notification()` function by combining two separate environment variable checks into a single chained iterator operation.
- **Before**: Two separate `.any()` calls on `NOTIFIER_DISABLE_VARS` and `ENVIRONMENTAL_DISABLE_VARS`
- **After**: Single chained iterator using `.chain()` method
- **Improved readability**: Cleaner, more idiomatic Rust code
- **Reduced redundancy**: Eliminates duplicate iteration logic
- **Better maintainability**: Follows Rust iterator best practices
- **Same functionality**: Zero behavioral changes
=> refactor(turborepo-updater): chain environment variable iterators in should_skip_notification

crates/turborepo-lib/src/shim/mod.rs
This warning was a bit vague about why it exists, and didn't give information about how to improve the situation. Now, it does!
=> refactor: improve messaging in global warning

crates/turborepo-lib/src/cli/mod.rs, docs/site/content/docs/crafting-your-repository/caching.mdx
Minimal contribution because the alert of --no-cache deprecation gave a wrong command to use now with newer versions
In a project with a recent enough version of turbo such as 2.5.4 :
turbo run build --no-cache
--> You'll receive the alert on the use of --no-cache
=> docs: fixing --no-cache alert

crates/turborepo-analytics/src/lib.rs, examples/with-tailwind/apps/docs/app/globals.css, examples/with-tailwind/apps/docs/app/layout.tsx, examples/with-tailwind/apps/web/app/globals.css, examples/with-tailwind/apps/web/app/layout.tsx, examples/with-tailwind/packages/ui/src/card.tsx, examples/with-tailwind/packages/ui/src/gradient.tsx, examples/with-tailwind/packages/ui/src/styles.css
As described in #10642, CSS specificity wasn't being handled correctly in the example. This PR fixes it by ensuring the compiled stylesheet from the package:
- Uses a prefix. This fixes all specificity issues by itself, but also...
- Is used directly in the app instead of trying to go through the app's Tailwind compilation process
- Is applied _before_ the app's stylesheet, so that things can be properly overridden by the app (since they're later in the CSS evaluation)
Try it out!
=> fix(examples): css specificity in Tailwind example

crates/turborepo-analytics/src/lib.rs
Improves test coverage for  from 87.50% to 90.57% (+3.07%) in `turobrepo-analytics`.
Added 3 new tests to cover previously untested code paths:
- Tests the  method to ensure it handles timeouts gracefully
- Tests error handling when the analytics client fails to record events  
- Tests the  utility function to ensure it properly sets session IDs
- **Before**: 87.50% coverage (12 missed regions out of 96 total)
- **After**: 90.57% coverage (10 missed regions out of 106 total)
- **Improvement**: +3.07 percentage points
All tests pass and cover important error handling and utility function scenarios.
=> test(turborepo-analytics): improve unit test coverage

crates/turborepo-analytics/src/lib.rs, crates/turborepo-auth/src/auth/login.rs, crates/turborepo-auth/src/auth/mod.rs, crates/turborepo-auth/src/auth/sso.rs, crates/turborepo-lib/src/commands/login/manual.rs, crates/turborepo-lib/src/commands/login/mod.rs, crates/turborepo-lib/src/config/env.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/opts.rs, docs/site/content/docs/reference/system-environment-variables.mdx
In some situations, users might want to change the port for the callback when logging in. This PR allows such behavior through an ` environment variable.
I manually tested that the port changes in the URL. Also added some tests.
=> feat(auth): optional callback port

examples/with-react-native-web/packages/typescript-config/package.json
When setting up the react native web template, you get hit with `File '@repo/typescript-config/nextjs.json' not found.` in `apps/web/tsconfig..json`.
Properly exporting the config files from `packages/typescript-config` so it works out the box.
Clone the template, notice no more `no found` errors.
=> fix: typescript-config export form react-native-web

examples/with-vitest/vitest.config.ts
The current `--with-vitest` example's root vitest.config.ts has `*` in the paths which seems to be invalid as shown below:
```
The project root contains the "*" character (/workspace/tmp/my-turborepo/packages/*), which may not work when running Vite. Consider renaming the directory / file to remove the characters.
The project root contains the "*" character (/workspace/tmp/my-turborepo/apps/*), which may not work when running Vite. Consider renaming the directory / file to remove the characters.
DEV  v3.2.4 /workspace/tmp/my-turborepo
No test files found. You can change the file name pattern by pressing "p"
0  
include: **/*.{test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, …
```
=> fix(examples): update vitest config paths for packages and apps in `with-vitest`

examples/with-react-native-web/packages/ui/tsconfig.json
- `examples/with-react-native-web/packages/ui/tsconfig.json` extends `react-native-library`.
- There was missing `.json`
- Happy CI
- Run 
- `pnpm dlx create-turbo@latest --example https://github.com/Franck-Fernandez-pro/turborepo/tree/main/examples/with-react-native-web`
- `pnpm i`
- `pnpm dev`
- Your app should run without errors
=> fix(examples): add missing extension to with-react-native-web ui tsconfig

crates/turborepo-lib/src/cli/mod.rs, crates/turborepo-lib/src/commands/daemon.rs, crates/turborepo-lib/src/commands/info.rs, crates/turborepo-lib/src/daemon/connector.rs, crates/turborepo-lib/src/daemon/server.rs, crates/turborepo-lib/src/diagnostics.rs, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/run/watch.rs, crates/turborepo-lsp/src/lib.rs
Unblock Watch Mode from being used with `--root-turbo-json`. 
I tested this manually by using `turbo watch lint --root-turbo-json=./some-dir/turbo.json` in a `create-turbo` and changing that file. The tasks would be picked up and re-ran the same as if I omitted the `--root-turbo-json` and used a standard path.
I also tried it with a JSONC and it worked.
=> feat: allow Watch Mode with `--root-turbo-json`

crates/turborepo-analytics/src/lib.rs, crates/turborepo-api-client/src/lib.rs, crates/turborepo-auth/src/lib.rs, crates/turborepo-cache/src/async_cache.rs, crates/turborepo-cache/src/cache_archive/restore.rs, crates/turborepo-cache/src/fs.rs, crates/turborepo-cache/src/http.rs, crates/turborepo-cache/src/test_cases.rs, crates/turborepo-filewatch/src/fsevent.rs, crates/turborepo-filewatch/src/hash_watcher.rs, crates/turborepo-filewatch/src/lib.rs, crates/turborepo-globwalk/src/lib.rs, crates/turborepo-graph-utils/src/lib.rs, crates/turborepo-lib/src/microfrontends.rs, crates/turborepo-lib/src/shim/parser.rs, crates/turborepo-lockfiles/src/pnpm/data.rs, crates/turborepo-lockfiles/src/yarn1/mod.rs, crates/turborepo-paths/src/anchored_system_path_buf.rs, crates/turborepo-process/src/child.rs, crates/turborepo-process/src/lib.rs, crates/turborepo-repository/src/discovery.rs, crates/turborepo-repository/src/package_graph/mod.rs, crates/turborepo-repository/src/package_manager/mod.rs, crates/turborepo-scm/src/git.rs, crates/turborepo-scm/src/manual.rs, crates/turborepo-scm/src/package_deps.rs, crates/turborepo-scm/src/status.rs, crates/turborepo/tests/common/mod.rs
A bunch of lints failures got into tests. This PR fixes them with `cargo clippy --fix`
👀
=> chore: fix lints in tests

docs/site/content/docs/reference/run.mdx
- Update docs for `--log-prefix` to match actual CLI enum values.
- Replace `prefix` with `task` and clarify description.
- Viewed `docs/site/content/docs/reference/run.mdx` and verified options table now lists `task`, `none`, `auto`.
- Cross-checked CLI enum in `crates/turborepo-lib/src/cli/mod.rs` (`LogPrefix::{Auto,None,Task}`).
=> docs(run): fix --log-prefix options to match CLI (task, not prefix)

crates/turborepo-lib/src/config/env.rs, crates/turborepo-lib/src/config/mod.rs, crates/turborepo-lib/src/config/turbo_json.rs, crates/turborepo-lib/src/engine/builder.rs, crates/turborepo-lib/src/opts.rs, crates/turborepo-lib/src/package_changes_watcher.rs, crates/turborepo-lib/src/run/builder.rs, crates/turborepo-lib/src/turbo_json/ARCHITECTURE.md, crates/turborepo-lib/src/turbo_json/extend.rs, crates/turborepo-lib/src/turbo_json/future_flags.rs, crates/turborepo-lib/src/turbo_json/loader.rs, crates/turborepo-lib/src/turbo_json/mod.rs, crates/turborepo-lib/src/turbo_json/processed.rs, turborepo-tests/integration/fixtures/turbo-configs/interruptible-but-not-persistent.json
This PR adds a new DSL keyword for array task definitions that alters the behavior when using `extends` in a package `turbo.json`. Usually a field from a package task definition will completely override the root field e.g.
Root: `{ "env": ["FOO"] }`
Package: `{ "env": ["BAR"] }`
Result: `{"env": ["BAR"] }`
If the package uses the new `$TURBO_EXTENDS$` the root field value will be extended from instead of overridden. e.g.
Root: `{ "env": ["FOO"] }`
Package: `{ "env": ["$TURBO_EXTENDS$", "BAR"] }`
Result: `{"env": ["FOO", "BAR"] }`
This functionality allows for greater flexibility when specializing package task definitions without needing to copy/paste the shared values and remembering to update them if the root changed.
It is currently gated by `turboExtends` feature flag in the root …
=> feat(turbo_json): add `$TURBO_EXTENDS$`

examples/with-nestjs/packages/api/tsconfig.json
After using the with-nestjs example and I started facing this issue:
=> fix: add types node to fix minimatch issue

.github/workflows/test-js-packages.yml, packages/eslint-config-turbo/package.json, packages/eslint-config-turbo/src/index.ts, pnpm-lock.yaml, turbo.json
Because JavaScript packaging is so finnicky, I'm thinking its a good idea to make sure our interfaces stay ecosystem compliant. PRs like https://github.com/vercel/turborepo/pull/10747 and https://github.com/vercel/turborepo/pull/10754 have potential to break things, so its nice to have some sanity checking. (I haven't checked yet if those PRs specifically are right, but they made me think about adding some tooling like this.)
CI
=> ci: checks for `eslint-config-turbo` interface

crates/turborepo-lockfiles/src/lib.rs
Add/update doc comments for the titular `Lockfile` trait exposed by the `turborepo_lockfiles` crate.
👀
=> docs: add more doc comments for working with the lockfile trait

docs/site/app/lib/llms-utils.ts, docs/site/app/llms-full.txt/route.ts, docs/site/app/llms.md/[[...slug]]/route.ts, docs/site/app/llms.txt/route.ts, docs/site/next.config.ts
[Twitter dutifully informed me that I'm doing llms.txt wrong](https://x.com/mazeincoding/status/1959919330520428619).
Looking around at other implementations, it seems I fell behind. This PR:
- Makes `/llm.txt` a list of links
- Makes `/llms-full.txt` a full readout of all of our markdown
- Adds `.md` extension paths (e.g. `/docs/core-concepts.md`) to our usual docs paths so they're directly visitable
This is all in addition to our existing "Copy to markdown" button. More ways to access!
Visit the paths mention for some sweet, sweet markdown.
=> docs: rework llms.txt and add .md responses

docs/site/content/docs/crafting-your-repository/creating-an-internal-package.mdx
A user mentioned that this page didn't make mention of how you need a `main` field in package.json
👀
=> docs: add `name` field mention to migration page

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/popup.rs, crates/turborepo-ui/src/tui/term_output.rs
I use turborepo for long running `dev` tasks and sometimes I want to clear the output of just one pane, for example server logs before triggering a request. 
If I clear my terminal buffer it clears everything including the TUI, and the content is still there to be scrolled to. What I really want is to only clear the logs for a single task.
This PR introduces the "Clear logs" option, currently bound to `shift-c` (I tried to pick a shortcut inkeeping with the others). It clears the logs only for the current task
Example screencasts below
- Run some tasks with the `--ui=tui`
- Press `shift-c` on a pane with output
- See that only that panes output is cleared, and new logs appear as normal
I attempted to write tests for this but I wasn't keen on all the hoops I had to jump through to try and …
=> feat(tui): add shortcut for clearing task logs

packages/turbo-types/src/json/frameworks.json
Added Expo to turborepo common frameworks and EXPO_PUBLIC_ env wildcard to work with Framework Inference
=> feat: add Expo to common frameworks

.github/workflows/lint.yml, .github/workflows/test-js-packages.yml, .github/workflows/turborepo-native-lib-test.yml
Replaces the deprecated `TURBO_REMOTE_ONLY: true` with `TURBO_CACHE: remote:rw` in the following GitHub Actions workflows:
- `.github/workflows/turborepo-native-lib-test.yml`
- `.github/workflows/lint.yml`
- `.github/workflows/test-js-packages.yml`
This change addresses the deprecation warning while maintaining read-write remote caching behavior for these CI jobs.
Verify that the `lint`, `test-js-packages`, and `turborepo-native-lib-test` GitHub Actions workflows run successfully and no longer display the `TURBO_REMOTE_ONLY` deprecation warning.
=> ci: update deprecated turbo setting

crates/turborepo-ui/src/tui/app.rs, crates/turborepo-ui/src/tui/event.rs, crates/turborepo-ui/src/tui/input.rs, crates/turborepo-ui/src/tui/pane.rs, crates/turborepo-ui/src/tui/table.rs
Add task list searching in terminal UI.
Features:
- UI hint for searching
- Locks query when the user presses ENTER
- Dims tasks in table list that don't match query
Use the TUI and try:
- Searching by pressing the `/` key
- Cycling tasks with `↑`/`↓` while typing a query
- Pressing ENTER so you can cycle with `j`/`k`
CLOSES TURBO-4197
=> feat(tui): task list search with `/`
